### DISCUSSION TITLE
GCP Cloud Function failed to deploy

### DISCUSSION THREAD

**Discussion by Adelabumowe** [cloud-custodian/cloud-custodian#10191] [GCP]
**Problem**
When I run the custodian command from my local, it runs successfully with the following log output:

```
2025-06-07 12:56:40,255: custodian.gcp.funcexec:INFO Provisioning policy function check-all-bucket-versioning
2025-06-07 12:57:03,272: c7n_gcp.mu:INFO function code uploaded
2025-06-07 12:57:06,931: c7n_gcp.mu:INFO creating function
```

**Policy**
```
policies:
  - name: check-all-bucket-versioning
    resource: gcp.bucket
    filters:
      - type: value
        key: versioning.enabled
        value: absent
    mode:
      type: gcp-periodic
      service-account: cloud-custodian@<project/-id>.iam.gserviceaccount.com
      schedule: "*/2 * * * *"  # Runs every 2 minutes
    actions:
      - type: notify
        slack_template: slack
        to:
          - https://hooks.slack.com/services/XXXXXX/XXXXXXXXXXX/XXXXXXXXXXXXXX
        transport:
          type: pubsub
          topic: "projects/<project_id>/topics/MyTopic"
```

But in my gcp console, I get a dependency conflict error
**Error**
<img width="956" alt="image" src="https://github.com/user-attachments/assets/9880c5db-fd41-4938-9dc9-f19fe40af5f8" />

**Another question I was hoping to get an answer to is: instead of creating 1st gen Cloud Functions, can I create 2nd gen Cloud Functions instead?**
