### DISCUSSION TITLE
No action performed on the policy(mark and delete unused databases)

### DISCUSSION THREAD

**Discussion by youzhoutai** [cloud-custodian/cloud-custodian#7320] [General]
There is one RDS in my account, which i launched some days ago. And nothing connected with it. after excuting the policy, there is no mark and deletion, i am not sure if some filtration are not correct.
```
vars:
  metrics-filters: &metrics-filter
        type: metrics
        name: DatabaseConnections
        days: 1
        value: 0
        op: equal

policies:
- name: rds-unused-databases-notify
  resource: rds
  description: |
    Take the average number of connections over 1 days for databases that are greater than 1
    days old and notify the resources owner on any unused RDS and mark for delete action in 1 days.
  filters:
    - "tag:c7n_rds_unused": absent
    - type: value
      value_type: age
      key: InstanceCreateTime
      value: 1
      op: greater-than
    - <<: *metrics-filter
    - or:
        - "tag:Resource Contact": present
        - "tag:CreatorName": present
  actions:
    - type: mark-for-op
      tag: c7n_rds_unused
      op: delete
      days: 1
- name: rds-unused-databases-delete
  resource: rds
  description: |
    Take the average number of connections over 1 days and delete
    any unused databases that have already been marked for delete
  filters:
    - "tag:c7n_rds_unused": present
    - type: marked-for-op
      tag: c7n_rds_unused
      op: delete
    - type: value
      value_type: age
      key: InstanceCreateTime
      value: 1
      op: gte
    - <<: *metrics-filter
    - or:
        - "tag:Resource Contact": present
        - "tag:CreatorName": present
  actions:
    - type: delete
      skip-snapshot: true
```
