### DISCUSSION TITLE
cross-account lambda assumeRole throwing error.

### DISCUSSION THREAD

**Discussion by dtd379** [cloud-custodian/cloud-custodian#7325] [General]
the below policy creates the first lambda function but gives the following error on the second:

```yaml
policies:
  - name: aws-0000000000-account-cloudtrail-enabled
    resource: account
    region: us-east-1
    mode:
        type: periodic
        schedule: "rate(12 hours)"
        role: arn:aws:iam::0000000000:role/tf-cloud-custodian-lambda-role
    actions:
      - type: enable-cloudtrail
        trail: cloud-custodian
        global-events: true
        multi-region: true
        bucket-region: us-east-2
        bucket: cloudtrail-bucket
  - name: aws-111111111111-account-cloudtrail-enabled
    resource: account
    region: us-east-1
    mode:
        type: periodic
        schedule: "rate(5 minutes)"
        role: arn:aws:iam::0000000000:role/cloud-custodian-lambda-role
        execution-options:
          assume_role: arn:aws:iam::111111111111:role/cloud-custodian-lambda-role
          metrics_enabled: false
          region: us-east-1
    actions:
      - type: enable-cloudtrail
        trail: cloud-custodian
        global-events: true
        multi-region: true
        bucket-region: us-east-2
        bucket: cloudtrail-bucket
```

iam_role_policy attached to role being assumed above:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowAssumeLambda",
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "AllowAssumeRole",
      "Effect": "Allow",
      "Principal": {
        "AWS":[
           "arn:aws:iam::0000000000:root",
           "arn:aws:iam::1111111111111:root"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
iam_role_policy attached to lambda function role:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AllowAssumeLambda",
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
ERROR:
InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.

Do I have this configured wrong?
