### DISCUSSION TITLE
delete vpc / subnet action

### DISCUSSION THREAD

**Discussion by mason67git** [cloud-custodian/cloud-custodian#7331] [General]
Hi,

After going through the Cloud Custodian Docs I can't seem to find a way to delete VPC's with a certain port is open, eg: search all vpc's if any have port 80 open then delete the VPC.

I believe it should be something like:

```
policies:
  - name: delete-vpc-with-port-80-open
    resource: vpc
    filters:
      - type: ingress
        OnlyPorts: [80]
    actions:
      - delete
```

But this doesn't work...

Any Ideas?
