### DISCUSSION TITLE
Tagging CloudFormation on Create - Race Condition

### DISCUSSION THREAD

**Discussion by cpollard0** [cloud-custodian/cloud-custodian#7335] [General]
When executing the below policy we run into an issue where stack creation takes longer than it takes for the create stack event to fire. Creating tags at the stack resource is advantageous to creating at the individual resource level. 

Any advice on how to best deal with it? 

```
  - name: add-cfn-tag
    resource: cfn
    mode:
      type: cloudtrail
      role: arn:aws:iam::{account_id}:role/inf-c7ntag-iam-role
      events:
        - source: cloudformation.amazonaws.com
          event: CreateStack
          ids: "responseElements.stackId"
    filters:
      - tag:creator: absent
    actions:
      - type: auto-tag-user
        tag: creator
      - type: tag
        tags:
          datecreated: "{now}"`
```
