### DISCUSSION TITLE
Question: Custodian Lambda function logs or Outputs

### DISCUSSION THREAD

**Discussion by sri321** [cloud-custodian/cloud-custodian#7336] [General]
Hello,

i specified a s3 bucket while provisioning the custodian lambda policy, but the lambda function logs are missing in the bucket, 
can someone point out where i can find those logs ?

Thank you 
Sri

**Comment by kapilt** [comment]
at the moment logs for policy lambdas have to be explicitly set via `execution-options:` on the policy mode. I think we'll want to change this to automatically propagate cli options to the lambda policies.

**Comment by sri321** [comment]
do you mean like this ?

```yaml
policies:
  - name: my-first-policy-cross-account
    mode:
        type: periodic
        schedule: "rate(1 day)"
        role: arn:aws:iam::123456789012:role/lambda-role
        execution-options:
          assume_role: arn:aws:iam::210987654321:role/target-role
          output_dir: s3-bucket-arn
```
