### DISCUSSION TITLE
tools/c7n_mailer: Feature Request - Using vars in mailer.yml file

### DISCUSSION THREAD

**Discussion by Shelvey-Kansal** [cloud-custodian/cloud-custodian#7338] [General]
There is an amazing feature in c7n_org tool, under account.yml there is an option to add vars and then refer it in policy file, I am looking for the same feature for c7n_mailer tool. If we are able to specify vars in mailer.yml file then there will be no need to specify things explicitly in policy file.

**Comment by kapilt** [comment]
if you had vars for mailer config, wouldn't they be effectively static from a template usage perspective? just trying to understand the use case. fwiw, its possible to define vars in jinja templates, and use an include to pull them in.

**Comment by Shelvey-Kansal** [comment]
The use case is that I want to read the value of **to** (dest address) from a separate file and pass that in the policy file.
For ex. let there be a file named details.txt (or any other format) containing the email addresses, then the notification should be send to the email listed in the particular file. According to the requirement, there should not be any hardcoded value in the policy file.

**Comment by Shelvey-Kansal** [comment]
The idea behind this is, if in future, the particular person leaves the organisation and another person comes up, then to modify the email of the person, policy file should not be changed, only the file containing the email address can be modified and "to address" in policy file will also get updated automatically without modifying the original policy file.

**Comment by kapilt** [comment]
the notify action already supports picking up `to` values from external locations, see `to_from` you can supply a json file in s3 for example.

**Comment by Shelvey-Kansal** [comment]
I tried to apply to_from in the policy file, as this can fulfill my use case, but it is resulting to an error. Please help me if I am doing anything wrong.
This is my policy file:

```
policies:
 - name: mark-stopped-ec2-terminate
   resource: ec2
   description: Mark the stopped instance for backup and termination
   filters:
        - "tag:instance_status": absent
        - "State.Name": stopped
   actions:
        - type: mark-for-op
          tag: instance_status
          op: terminate
          days: 2
        - type: notify
          to_from:
                 url: s3://pocrdemo/emails.json
                 format: json
                 expr: emails
          subject: "EC2 Stopped Instance Restarted [custodian {{ account }} - {{ region }}]"
          violation_desc: "Following EC2(s) have been stopped:"
          action_desc: |
            Your EC2 server(s) are now stopped
          template: default.html
          transport:
              type: sqs
              queue: https://sqs.us-east-1.amazonaws.com/1234567789/SQS-CUS-A-PC-01
```
