### DISCUSSION TITLE
aws.asg.filters.metrics  not filtering out resource properly.

### DISCUSSION THREAD

**Discussion by ShivaSharm** [cloud-custodian/cloud-custodian#7341] [General]
Below metrics filter on ASG is not filtering out the ASG properly. As per my understanding, it should filter out an ASG (with tag Name as 'ASG-Name') and that has **ALL** the 10 datapoints (captured at a period of 60 seconds) in the last 0.00694444 days ( i.e. last 10 minutes) with Minimum statistics greater than 0.

```yaml
policies:
  - name: long-running-ib-workers
    resource: asg
    filters:
      - 'tag:Name': 'ASG-Name'
      - type: metrics
         namespace: 'AWS/AutoScaling'
         name: 'GroupInServiceInstances'
         statistics: 'Minimum'
         days: 0.00694444
         period: 60
         value: 0
         op: gt
```

But instead, it filters the ASG even if **not** all datapoints returns Minimum statistics greater than 0.
Seems it is evaluating the metrics sequentially as per below and filters out the ASG as it has found the Minimum > 0 at first item . While it is not further checking all the other Minimum values for all the timestamps with in the range. Nor the Items are arranged sequentially based on Timestamp.
I would have wanted it to check the Minimum value for all the datapoints returned and then only filter out the ASG if Minimum for ALL the datapoints are greater than 0.

Below is Snippet of c7n.metrics field as returned in resource.json file.

```json
"c7n.metrics": {
      "AWS/AutoScaling.GroupInServiceInstances.Minimum": [
        {
          "Timestamp": "2019-05-21T14:51:00+00:00",
          "Minimum": 1.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:47:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:43:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:52:00+00:00",
          "Minimum": 1.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:48:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:44:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:49:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:45:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:50:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        },
        {
          "Timestamp": "2019-05-21T14:46:00+00:00",
          "Minimum": 0.0,
          "Unit": "None"
        }
      ]
    },
```
