### DISCUSSION TITLE
Filtering S3 Bucket Policies by Principals.AWS

### DISCUSSION THREAD

**Discussion by ppestinger** [cloud-custodian/cloud-custodian#7346] [General]
I'm trying to create a Cloud Custodian policy that will detect S3 buckets whose policies enable public access. Part of it requires checking for policy statements that have an Allow Effect and a Principal of "\*" or {"AWS":"\*"}.

To this end, I'm trying using a pair of s3.has-statement filters:

```
policies:
  - name: s3-public-access
    resource: s3
    filters:
      - or:
        - type: has-statement
          statements:
            - Effect: Allow
              Principal: '*'
        - type: has-statment
          statements:
            - Effect: Allow
              Principal:
                AWS: '*'
```

The first filter works successfully, matching buckets that have a Principal property set to "*". But the second filter returns an "Invalid filter type" error. Is there a way to use has-statement to filter more granular Principals?
