### DISCUSSION TITLE
execution-options: region key not respected or not the same as --region

### DISCUSSION THREAD

**Discussion by nitrocode** [cloud-custodian/cloud-custodian#7353] [General]
account-root-user-login-detected.yml
```
policies:
  - name: root-user-login-detected
    resource: account
    description: |
      Notifies Security and Cloud Admins teams on any AWS root user console logins
    mode:
      type: cloudtrail
      events:
          - ConsoleLogin
      execution-options:
        region: us-east-1
```

```
✗ custodian-cask -s out policies/account-root-user-login-detected.yml
```

The lambda and cw event do not get created in us-east-1 but instead get created in us-west-2 which is my default region.

If I run this instead

```
✗ custodian-cask -s out policies/account-root-user-login-detected.yml --region us-east-1
```

It works as intended.

```
✗ custodian-cask version  
Custodian Cask 20190904.1 (cloudcustodian/c7n:latest)
Skipped image pull - Last checked 36 minutes ago.

0.8.45.4
```
