### DISCUSSION TITLE
Snapshot delete periodic timezone not working

### DISCUSSION THREAD

**Discussion by Taurino3** [cloud-custodian/cloud-custodian#7365] [General]
I am running into an issue that when deleting a snapshot checking periodically it does not consider the timezone... 

So say the delete of a snapshot is marked for May 7 pst, the periodic check runs and deletes the snapshot on May 6 pst, this is because it is considering UTC time, which in UTC time it is 7 hours ahead.

In periodic mode I add the "tz: pt" as a filter for "marked-for-op" but it is ignored. If I do not run the policy in periodic mode then the "tz: pt" is considered and the snapshot is not deleted. 

Mark Policy:
```yaml

policies:
- name: ebs-snapshots-mark
  resource: aws.ebs-snapshot
  comment: EBS Snapshots Mark Delete
  mode:
      type: periodic
      schedule: rate(2 minutes)
      role: arn:aws:iam::XXXXXXX:role/acct-managed/custodian-tag-compliance-role
  filters:
    - "tag:marktest": present
    - "tag:custodian_cleanup": absent
    - type: age
      days: 0
      op: ge
  actions:
    - type: mark-for-op
      tag: custodian_cleanup
      op: delete
      tz: pt
      days: 1
```
Delete Policy:
```yaml
policies:
- name: ebs-snapshots-delete
  resource: aws.ebs-snapshot
  comment: EBS Snapshots Delete
  mode:
      type: periodic
      schedule: rate(3 minutes)
      role: arn:aws:iam::XXXXXXX:role/acct-managed/custodian-tag-compliance-role
  filters:
    - "tag:marktest": present
    - type: marked-for-op
      tag: custodian_cleanup
      op: delete
      tz: pt
  actions:
    - delete
```
