### DISCUSSION TITLE
"Access denied api:SendMessage" - does error refer to slack or IAM?

### DISCUSSION THREAD

**Discussion by Mike-Landers** [cloud-custodian/cloud-custodian#7371] [General]
I'm trying to set up custodian + c7n-org + c7n-mailer within AWS in order for custodian to run policies + send messages to sqs / receive messages from sqs and forward messages on to a slack channel using a slack webhook.

Currently when I run policies everything completes successfully but slack messages aren't delivered to the channel configured via slack webhook. I've already created the slack webhook and tested that it works to send messages to a particular slack channel using curl from the same host c7n runs from.

- I've set up and tested c7n-org can run policies. This works.
- I've set up an SQS queue that allows SendMessage at account level from all of our accounts, and ReceiveMessage at account level on the account with the queue.
- I've created a c7n IAM role with ReadOnlyAdmin + sqs:* on the above queue.
- I've allowed the c7n IAM role to be assumed by the IAM role running the c7n host (this works since c7n-org can run policies)
- I've specified the c7n IAM role to be used by all components of c7n
- I've created a slack webhook that I tested works to send messages to a particular slack channel from the same host c7n runs from using curl.
- I've created a c7n policy that makes use of the slack webhook to send messages
- I've checked sqs monitoring- I can see that messages are being received by the queue. "Approximate Number Of Messages Visible" goes up every time the policy is run, but it seems like nothing is draining the messages / sending to slack.
```
actions:
      - type: notify
        slack_template: slack
        to:
          - https://hooks.slack.com/services/T0<masked>
        transport:
          type: sqs
          queue: https://sqs.<masked>
```

How should I determine why messages aren't showing up from here?
