### DISCUSSION TITLE
Filter gke-clusters by labels

### DISCUSSION THREAD

**Discussion by dbarranco** [cloud-custodian/cloud-custodian#7375] [General] [answered]
Hello folks!

I am working on adding support for the "delete" operation for the `gcp.gke-cluster` resource and before starting coding the _delete_ function I did some tests to filter GKE clusters in one of my Google Cloud Projects.

All of the clusters I'm interested in contain the following Google Cloud labels:

![Screenshot 2020-08-20 at 17 02 52](https://user-images.githubusercontent.com/9199512/90789290-0a947880-e307-11ea-98ea-569bd93c75f4.png)

But when I try to filter some of them by adding policies like:

```
policies:
- name: bkpr-delete-gke-clusters
  resource: gcp.gke-cluster
  comment: |
    Clean-up temporary R53 hosted zones created by Jenkins-BKPR
    for its continuous integration tests
  filters:
    - 'tag:created_by': 'jenkins-bkpr'
```

I see that none of them got filtered.
I also have tried with some variations, like:

```
  filters:
    - type: value
      key: Name
      op: eq
      value: "<. . .>"
```

or 

```
  filters:
    - type: value
      label: 'created_by'
      op: eq
      value: 'jenkins-bkpr'
```

But still, it doesn't work.
Am I missing something here?

Thanks in advance.

**Comment by dbarranco** [comment]
cc/ @kapilt

**Comment by rockhowse** [comment]
@dbarranco I ran into this today while attempting to do something similar

sample policy file:

```
vars:
    sample-tag-filters: &sample-tag-filters
          - "tag:env": present

  policies:
  - name: gke-cluster-sample
    resource: gcp.gke-cluster
    filters:
      - and: *sample-tag-filters
 ```

As expected, the list of clusters was empty, even with the `env` label set on the cluster. 

If you examine the raw data output from the `cloud-custodian` run, the actual key in the `gke-cluster` JSON isn't one of the normal ones `tags`, `Tags` or `labels`, it's a new and exciting key named `resourceLabels` 

```
[
  {
    "name": "cluster-name",
    ...
    "resourceLabels": {
      "env": "test",
    },
    ...
  }
]
```

And if we examine the code that is currently being used to filter on the `tag` like varients, that key isn't currently being considered:

https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/filters/core.py#L230-L257

Although it looks like there might be a capacity to use a more advanced or different filter to accomplish the filtering. I am relatively new to `cloud-custodian` so I can't provide the exact override but I am going to try a couple things and report back. 

I will also take a stab at putting up a PR to add `resourceLabels` to the list of expected normalized keys so that the expected use of `tags:filter-value` will work in a similar fashion to how the existing `GCP` + `labels` is done.

**Reply by rockhowse** [reply, marked as answer]
Ok, looks like you can work around this by using [Generic Filters](https://cloudcustodian.io/docs/filters.html#filters):

There's not a deep link to the section but here it is: 

![image](https://user-images.githubusercontent.com/463231/175789716-dfad2ec6-63a1-4372-820f-1f02957d075f.png)

For my use case, I was able to successfully update the policy file: 

```
vars:
  sample-tag-filters: &sample-tag-filters
    - resourceLabels.env: present

  policies:
  - name: gke-cluster-sample
    resource: gcp.gke-cluster
    filters:
      - and: *sample-tag-filters
```
Note that I changed it from a string, to a non-string value. This format takes advantage of the [JSMEPath](https://jmespath.org/tutorial.html) format as shown in the [Generic Filters](https://cloudcustodian.io/docs/filters.html#filters) docs.
