### DISCUSSION TITLE
Allow inspection of lambda aliases and versions

### DISCUSSION THREAD

**Discussion by soncaocc** [cloud-custodian/cloud-custodian#7377] [General]
**Is your feature request related to a problem? Please describe.**
I currently use policies with ```resource:lambda``` to inspect the resource based policy to ensure only approved accounts have the ```lambda:InvokeFunction``` action available. I use the cross-account filter type and the ```actions``` property of that filter type in my policy, Custodian only inspects the unqualified reference to the lambda function, which defaults to $LATEST. Users can circumvent the custodian policy by creating an alias or version of the function, modify the resource based policy, and invoke the alias or version.

**Describe the solution you'd like**
I would like an enhancement to ```resource: lambda``` to account for lambda's versioning/aliasing capabilities. 

**Describe alternatives you've considered**
I haven't attempted any alternatives but have tested this gap in differing scenarios to validate the gap exists.

**Additional context**

**Comment by kapilt** [comment]
the resource policy is not versioned, the cross account filter doesn't take into account the resource specification on statements, ie this is a non issue for cross-account access checking. you'll have to give a fuller example to illustrate the problem. ie whats the resource iam policy, whats your custodian policy, and what isn't happening the way you expect.

**Comment by soncaocc** [comment]
Here's an example of the constraint.
A function is created with a lambda resource policy specifying that one other account can perform only the InvokeFunction. The function is compliant. My custodian policy runs successfully, vetting the allowed account ID against an approved list, and determines the resource as compliant. The policy also checks the action of the lambda resource policy to ensure a couple of permissions are not included in the lambda resource policy.
```yaml
name: lambda-perms  
resource: lambda
  filters:
    ### Check if lambda resource policy meets an approved account list
    - type: cross-account
      whitelist_from:
        expr: "accountList.*.accountId"
        url: *accounts-list
    ### Check if lambda resource policy includes any violating actions
    - type: cross-account
      actions:
        - "lambda:UpdateFunctionCode"
        - "lambda:UpdateFunctionConfiguration"
```
The policy runs successfully and the resource passes the filter.

Consider now, that the resource owner creates a version 1 of the function. Furthermore, the resource owner runs "aws lambda add-permission" to allow another account that is not on the approved list. The unapproved account could then invoke Version 1. The above policy inspects only the $LATEST version and custodian offers no option to inspect Version 1 for compliance.
