### DISCUSSION TITLE
possible to copy-related-tag from AMI to ebs-snapshot?

### DISCUSSION THREAD

**Discussion by JonGilmore** [cloud-custodian/cloud-custodian#7386] [General]
Is it possible to use `copy-related-tag` to copy all tags from AMIs to their associated ebs-snapshot's? I feel like it _might_ be possible because when I lookup `ebs-snapshot` and `ami`'s in my accounts, they both have an associated `SnapshotId`. Here's an example policy that I have attempted so far:

```
policies:
  - name: tag-snapshot-from-ami
    resource: ebs-snapshot
    actions:
      - type: copy-related-tag
        resource: ami
        skip_missing: True
        key: "ImageId"
        tags: "*"
```

**Comment by MichaelDavisTSN** [comment]
I think the problem is that the describe-snapshots call does not return an ami id. However, the reverse is possible.

```
policies:
  - name: ebs-ami-inherit-tags
    description: |
       Copies ebs snapshot tags to related AMIs.
    resource: aws.ami
    filters:
      - or:
        - "tag:test-tag": empty
        - "tag:test-tag": absent
    actions:
      - type: copy-related-tag
        resource: ebs-snapshot
        skip_missing: False
        key: BlockDeviceMappings[0].Ebs.SnapshotId
        tags: 'test=tag'
```
