### DISCUSSION TITLE
How to interpolate date variable during runtime

### DISCUSSION THREAD

**Discussion by Vishnu-Lakkimsetty-E3640** [cloud-custodian/cloud-custodian#7387] [General]
Hi Custodian team,

I saw there is a provision for interpolating {{account}}, {{region}} variable on runtime in the notify block of the custodian policy. In the same way, do we have a way to interpolate the `date` variable during runtime in the notify block?

I saw the `{now}` variable but it is getting substituted during the deployment of policy that too for `tag` action. But I need something similar for the notify block where the date value will be interpolated during the runtime of the policy. Can someone please help me here?

**Comment by kapilt** [comment]
can you provide an example of the policy, {{now}} is runtime interpolated, but for lambda policies thats also subject to provisioning time interpolation.

**Comment by Vishnu-Lakkimsetty-E3640** [comment]
Sample policy is here

```
policies:
    - name: test_date_interpolation
      resource: network-addr
      mode:
        type: periodic
        schedule: "rate(5 minutes)"
        role: arn:aws:iam::{account_id}:role/CustodianRole
      description: |
        Test policy to check date interpolation
      filters:
        - "tag:test_tag": present
      actions:
    # In this action block {now:%d-%m-%Y} is getting replaced with current date once the policy is getting deployed as lambda
        - type: tag
          tag: date_adjusted
          value: "{now:%d-%m-%Y}"
    # In this action block {now:+4d%d-%m-%Y} is getting replaced with date which is after 4 days from current date once the policy is getting deployed as lambda
        - type: tag
          tag: after_date
          value: "{now:+4d%d-%m-%Y}"
    # In this action block {{ account }} & {{ region }} are not getting replaced with any value once after policy is deployed as lambda but the mail sent is having these variables interpolated with proper values
    # But {{ now }} is getting replaced as { now } once after the policy is deployed as lambda but it is not getting replaced/interpolated with any value in the mail notification 
        - type: notify
          template: my_custodian.html
          priority_header: 1
          subject: "Test mail - [custodian {{ account }} - {{ region }}]"
          violation_desc: "This EIP is found on date {{ now }}"
          action_desc: |
            Actions Taken: No action taken. This is a test mail to check interpolation of dates.
          to:
            - xxx@abc.com
```
