### DISCUSSION TITLE
Compare two lists in custodian policy

### DISCUSSION THREAD

**Discussion by VishalGupta04** [cloud-custodian/cloud-custodian#7390] [General]
I want to ensure that tags associated to the container images stored in ECR follow:

- Tag value is either 'latest' or follow semantic versioning scheme (Major.Minor.Patch) 

```
policies:
  #Ensure that images stored in ECR follow Semantic Versioning (semver) scheme for tags
  - name: ecr-tagging-filter
    resource: ecr
    description: |
      ensure ECR images follow semver tagging scheme
    mode:
      type: config-poll-rule
      role: XXXX
      schedule: TwentyFour_Hours
    filters:
      - not:
        - or:
          - type: value
            key: "imageTags[]"
            op: regex
            value: '^\d*\.\d*\.\d*$'
          - type: value
            key: "imageTags[]"
            op: eq
            value: 'latest'
```

Above policy is not giving expected results as I need ensure that all tag values must be either 'latest' or '^\d*\.\d*\.\d*$'
