### DISCUSSION TITLE
Feature to support role / resource specific whitelisting for cross account access validation

### DISCUSSION THREAD

**Discussion by rams3sh** [cloud-custodian/cloud-custodian#7393] [General]
**Is your feature request related to a problem? Please describe.**

I have a scenario regarding IAM role specific whitelisting.

I took a look at cross-account filter , but apparently I understand that cross-account filter along with whitelist_from or whitelist basically results in allowing any roles to having the principal as account part of the whitelist i.e if an account is whitelisted , it can technically be part of any role as a principal.This is fine when the whitelisted accounts are internal accounts since we trust all of them by default. 

If there exists a case where there is a genuine need of an external vendor account to be a principal for one of the roles (**not all roles**), then role specific principal lookup will be required as we don't want to allow that vendor as whitelisted principal across in general.

So problem is I would want to manage exceptions as a one to one relation with the given role to a principal , rather than the entire account being whitelisted across all roles.

Below is a sample solution that I would like to propose to handle such cases.
One can have a custom external lookup whitelisted role specific json file, that looks like this :-

**exception-specific-roles-and-allowed-principals.json** :-
```json
{

        "<role-arn-1>" : ["role-arn-1_specific_whitelisted_external_vendor_account_principal_1", "role-arn-1_specific_whitelisted_external_vendor_account_principal_2"],
        "<role_arn_2>" : ["role-arn-2_specific_whitelisted_external_vendor_account_principal_3"]
}
```
**Sample Policy**

```yaml
policies:
  - name: iam_role_with_unauthorised_external_account_principals
    resource: iam-role
    filters:
      #  Identify roles with AWS principals other than allowed ones for the respective role in external exception json.
           - type: value
             key: "AssumeRolePolicyDocument[].Statement[].Principal.AWS"
             op: difference 
             value_type: swap
             value_from:
                url: s3://cloud-custodian-bucket/exception-specific-roles-and-allowed-principals.json
                format: json
                expr: "{resource['Arn']}"   # resource's attributes as a dynamic interpolation variable for lookup in sample external json
```
**Describe the solution you'd like**

Feature supporting  resource context as a dynamic interpolation variable that is being  processed at the time of evaluation under the filter context would help in such situations. 

**Describe alternatives you've considered**
I use a custom script as of now to do this task.

**Additional context**

The context of the problem statement of the policy is more from a security standpoint. This is one of the requirements of PCIDSS and SOC with relation to controls pertaining to authorised access to AWS Account. 
`cross-account` filter is granular at an account level, however it would not be helpful in case exceptions of principals are to be managed at per IAM Role level.
