### DISCUSSION TITLE
Testing for list difference

### DISCUSSION THREAD

**Discussion by PodioSpaz** [cloud-custodian/cloud-custodian#7396] [General]
Hello,

I'm trying to create a `config-rule` to validate trusted entities of a Role.

I want to compare the list of Principals vs. a list that I maintain.  I want the Rule to be `NON_COMPLIANT` if the lists do not match.  I tried the following filter, but it only works if there is no intersection in the lists.

```
filters:
  - not:
    - type: value
      key: "AssumeRolePolicyDocument.Statement[?Action=='sts:AssumeRole'].Principal.*[][]"
      op: intersect
      value:
        - "arn:aws:iam::123456789012:root"
        - "arn:aws:iam::999999999999:user/foo"
  - type: value
    key: "RoleName"
    value: "Admin"
```

Is there a way to test for a difference between two lists?

Thanks,
Charles

**Comment by ajkerrigan** [comment]
Hi there @PodioSpaz - thanks for the report. I've played with this a bit locally, and the only reliable way I've found so far is something like this:

```
filters:
  - type: value
    key: "AssumeRolePolicyDocument.Statement[?Action=='sts:AssumeRole'].Principal.*[][] | sort(@)"
    op: not-equal
    value:
      - "arn:aws:iam::123456789012:root"
      - "arn:aws:iam::999999999999:user/foo"
```

The wonky part there is that because we're testing equality of the whole rather than membership, we need to both add `sort(@)` to the `key` and provide a sorted list for `value` or the results can be flaky. I'm going to poke around a bit to see if there's a friendlier way to handle this, or if this warrants a code change.
