### DISCUSSION TITLE
Azure - "All Resources" Support required for Inventory

### DISCUSSION THREAD

**Discussion by aakifshaikh** [cloud-custodian/cloud-custodian#7401] [Azure]
**Is your feature request related to a problem? Please describe.**
In Azure, they have something called "all resources" which provides the detailed inventory for the entire subscription. I looked at the documentation and nowhere custodian supports this. Wondering, if we can just get a filter to identify them all will be great. Following problems will be solved-
1) Inventory of resources

**Describe the solution you'd like**
Support Cloud Custodian for "All resources" so that we can identify all the resources. In other words- get ALL resource count, resource type, and ALL resources.

**Describe alternatives you've considered**
We have been doing this manually today- meaning exporting from Azure.

**Additional context**
Inventory of resources from Azure Subscription.

**Comment by kapilt** [comment]
please provide a documentation link re all resources. custodian does support generic arm resources which is the equivalent afaict.. its unclear what your use case is related to custodian policy enforcement vs just a data export tool, ie the inventory your referencing is some internal application...

**Comment by stefangordon** [comment]
Following on from @kapilt's comment the examples below may do this for you.

However, please be advised that full asset exports are not a supported use case for Cloud Custodian and I expect you will hit limits and throttling in various places for any larger subscriptions as this isn't something we have tested for.

```
policies:
  - name: all-resources
    resource: azure.armresource
```

And if you wanted to exclude or include specific resource types you could use some variation of this filter:

```
    filters:
      - type: resource-type
        values:
          - Microsoft.Network/virtualNetworks
          - Microsoft.Storage/storageAccounts
          - Microsoft.Compute/virtualMachines
```
