### DISCUSSION TITLE
How do I execute a policy on creation, in addition to the criteria of the mode parameter?

### DISCUSSION THREAD

**Discussion by Richard-Hansen** [cloud-custodian/cloud-custodian#7403] [General]
**Goal**: I have an AWS account with a large number of 'lost and forgotten' resources which are accruing unnecessary costs. I'm looking to deploy a policy that will enforce some configuration options to better monitor our resources. Ideally, we can deploy a policy that will:
1. Evaluate the compliance status of all existing resources
2. Evaluate the compliance status of all new/modified resources

Step 2 is handled by the example policy below with the `config-rule` mode. But I'm unsure how to achieve step 1.

```
policies:
  - name: my-first-policy
    mode:
        type: config-rule
        role: arn:aws:iam::123456789012:role/some-role
    resource: ec2
    filters:
      - "tag:Custodian": present
    actions:
      - stop
```
AWS config rules have an action option to re-evaluate, which will evaluate all existing resources (of the specified type). Is there a way to have new policies do an initial full evaluation upon deployment, and then run in accordance to the specified mode?

**Comment by thisisshi** [comment]
Thanks for the question. At this point in time, no-- there is no way to trigger an on-demand evaluation of a config rule. However, there is a AWS Action (see: https://docs.aws.amazon.com/config/latest/APIReference/API_StartConfigRulesEvaluation.html) that we could use in conjunction with the `config-rule` resource, a potential policy would look like this:

```yaml
policies:
  - name: trigger-config-eval
    resource: aws.config-rule
    filters:
      - ConfigRuleName: "my-config-rule"
    actions:
      - type: evaluate
```

It would probably also be beneficial to have a related resource for `aws.lambda` to find any config rules attached to specific custodian lambda functions. Though, the name of the config rule should be the same as the lambda afaicr.
