### DISCUSSION TITLE
GCP {account_id} get value of project_id

### DISCUSSION THREAD

**Discussion by rahulvinodsharma** [cloud-custodian/cloud-custodian#7409] [General] [answered]
In GCP, how do you use account_id to get project name Following https://cloudcustodian.io/docs/quickstart/advanced.html?highlight=account_id

```
service-account: "demo@{account_id}.iam.gserviceaccount.com"
```

Getting value
```
c7n-gcp-sa@None.iam.gserviceaccount.com
```

**Comment by kapilt** [comment]
account_id is the project name for gcp, its picked up via environment variable for c7n (CLOUDSDK_CORE_PROJECT) per gcloud cli/sdk, and via config in c7n-org

**Comment by sarangard** [comment]
[UPDATE: Issue resolved]

Hi, I've run into the same issue and am unable to resolve this. Any feedback is appreciated.

Policy
```
  - name: compute-disk-mark-unattached-deletion
    resource: gcp.disk
    description: |
      Lists all unattached compute disks and mark them for deletion.
    mode:
      type: gcp-periodic
      schedule: "every 6 hours"
      service-account: custodian-user@{account_id}.iam.gserviceaccount.com
      target-type: pubsub
    filters:
      - "tag:maid_status": absent
      - key: "users"
        type: value
        value: absent
    actions:
      - type: mark-for-op
        label: maid_status
        op: delete
        days: 2
```

Custodian Version
```
custodian version
0.9.29
```

The output of `gcloud config list`

```bash
[compute]
region = us-west1
zone = us-west1-b
[core]
account = xxxxxxx
disable_usage_reporting = False
project = my_project_id
```

Checked to see if I exported the right env vars.

```bash
env | grep PROJECT

GOOGLE_CLOUD_PROJECT=my_project_id
CLOUDSDK_CORE_PROJECT=my_project_id
```
