### DISCUSSION TITLE
Purging the (legacy) 'current' Lambda function aliases

### DISCUSSION THREAD

**Discussion by llange** [cloud-custodian/cloud-custodian#7411] [General]
Back in the days, when deploying policies on AWS as Lambda functions, c7n used to create a `current` alias pointing to the latest release of the Lambda.

Sometime in 2019, this behaviour (`current` alias) was scrapped (I believe in this commit : 1b594cee6dbda6001a60d6b3fd48ec8d91354382), and Lambda are now aliasless. Which is ok I think.

Back to now, when I'm trying to apply the action `trim-versions` to my huge pool of Lambdas, I cannot get rid of any old version which are pointed to by this `current` alias.

Here is my policy for reference:
```
policies:
- name: cleanup-old-c7n-lambda-versions
  resource: aws.lambda
  filters:
  - type: value
    key: FunctionName
    op: regex
    value: ^(custodian-?)\w+
  actions:
  - type: trim-versions
    exclude-aliases: true
    retain-latest: true
```

When I apply this policy, all the snapshotted versions are removed (as expected), except for the ones that are aliased to `current`.

When I try to be smart (and fail) specifying `exclude-aliases: false`, I'm treated with an error message:
```
error:An error occurred (ResourceConflictException) when calling the DeleteFunction operation: Unable to delete version because the following aliases reference it: [current]
```

As much as I understand that this is more a 'legacy' use-case than something that could benefit modern c7n users, I'd be happy to find a (preferentially c7n-based) solution to either remove aliases, or force-trim.

What would be the preferred approach in this case ? I'd be happy to provide a PR if a c7n solution is encouraged.
