### DISCUSSION TITLE
GC function is not running if we create periodic rules of pubsub type

### DISCUSSION THREAD

**Discussion by swati-delphix** [cloud-custodian/cloud-custodian#7413] [General]
**Describe the bug**
GC function is not returning anything if we create GC function of PUB SUB TYPE using c7n rules.

**To Reproduce**
I have created GC rules like below:
```yaml
    resource: gcp.image
    mode:
      type: gcp-periodic
      schedule: "0 3 * * 0"
      service-account: "X"
      trigger-type: pubsub
      pubsub_topic: XXX
```
And run it aganst my rules using c7n-org.
But it failed.

Then, I troubleshooted mu.py in c7n_gcp file and found below condition in policy handler template
if trigger_type == 'HTTP_TRIGGER' 👍 

**Expected behavior**
Cloud Function should run against pubsub trigger type.

**Background (please complete the following information):**
 - Python Version: python 3.7.9
 - Custodian Version: 0.9.12.0
 - Cloud Provider: gcp
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
Issue in mu.py, which is c7n-gcp package. 
I have debugged it and updated it to make it run like below:
if trigger_type == 'HTTP_TRIGGER' or trigger_type == 'CLOUD_PUBSUB_TRIGGER':

**Comment by kapilt** [comment]
when you say it failed, please provide log output.

**Comment by kapilt** [comment]
its not valid to provide a pubsub_topic in the mode there, ie. that policy fails validation.. use `custodian validate policy.yml` to check your policy before using c7n-org.

**Comment by kapilt** [comment]
trigger-type is supposed to be target-type.

**Comment by kapilt** [comment]
simplifying the policy to 

```yaml
policies:
 -  name: my-image
    resource: gcp.image
    mode:
      type: gcp-periodic
      schedule: "0 3 * * 0"
      target-type: pubsub
```

works fine. you'll have to actually provide output from running with custodian (not c7n-org)
