### DISCUSSION TITLE
Document support for server-side filters via the query block

### DISCUSSION THREAD

**Discussion by robbie-demuth** [cloud-custodian/cloud-custodian#7418] [General]
**Describe the bug**

Our organization is trying to use Cloud Custodian to garbage collect expired AWS EBS snapshots belonging to a specific system. Initially, we created the following policy:

```yaml
policies:
  - name: garbage-collect-snapshots
    resource: ebs-snapshot
    filters:
      - type: value
        key: tag:appian:system
        value: SiteWorkerGroupOperator
      - type: value
        key: tag:appian:deletion-protected
        op: ne
        value: "true"
      - type: value
        key: tag:appian:expires-at
        value_type: age
        op: gt
        value: 0
    actions:
      - delete
``` 

As the policy suggests, all snapshots belonging to the system are tagged with `appian:system=SiteWorkerGroupOperator`. They are also tagged with `appian:expires-at=<DATETIME>`. Snapshots that are exempt from garbage collection are tagged with `appian:deletion-protected=true`.

When run against accounts / regions with a substantial number of snapshots, however, Cloud Custodian failed with read timeouts as discussed in the following issues:
* #3217 
* #5174

As suggested in the above issues, we looked to better leverage server-side filtering. After all, if we could use server-side filters to reduce the amount of data returned by the EC2:DescribeSnapshots API, we should be less susceptible to read timeouts. Therefore, we added a new tag, `appian:expires-on` to all of our snapshots. Instead of a datetime, the tag's value is a ISO8601 date (e.g. `2021-08-30`). We then updated our policy, run daily, to be dynamically generated as follows:

```yaml
policies:
  - name: garbage-collect-snapshots
    resource: ebs-snapshot
    filters:
      - type: value
        key: tag:appian:system
        value: SiteWorkerGroupOperator
      - type: value
        key: tag:appian:deletion-protected
        op: ne
        value: "true"
      - type: value
        key: tag:appian:expires-on
        value: "<DATE>"
    actions:
      - delete
```

With the above policy, we expected both the `tag:appian:system=SiteWorkerGroupOperator` and `tag:appian:expires-on=<DATE>` filters to be handled server-side by AWS using the [`Filter.N`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html#API_DescribeSnapshots_RequestParameters) request parameter:

![image](https://user-images.githubusercontent.com/20929870/131350639-8ef0a638-4244-4df4-9c55-b36fc565e242.png)

To our surprise, however, the filters were not applied server-side. This is supported by CloudTrail. The following JSON shows the `requestParameters` field in the event record for a EC2:DescribeSnapshots invocation from Cloud Custodian for the above policy:

```json
"requestParameters": {
    "snapshotSet": {},
    "ownersSet": {
        "items": [
            {
                "owner": "self"
            }
        ]
    },
    "sharedUsersSet": {},
    "filterSet": {},
    "includeRecoveryBin": false
}
```

As you can see, the `filterSet` field does not include any filters. Here it is for the following AWS CLI command:

```
aws ec2 describe-snapshots --filters Name=tag:appian:system,Values=SiteWorkerGroupOperator Name=tag:appian:expires-on,Values=2021-08-30
```

```json
"requestParameters": {
    "snapshotSet": {},
    "ownersSet": {},
    "sharedUsersSet": {},
    "filterSet": {
        "items": [
            {
                "name": "tag:appian:system",
                "valueSet": {
                    "items": [
                        {
                            "value": "SiteWorkerGroupOperator"
                        }
                    ]
                }
            },
            {
                "name": "tag:appian:expires-on",
                "valueSet": {
                    "items": [
                        {
                            "value": "2021-08-30"
                        }
                    ]
                }
            }
        ]
    },
    "includeRecoveryBin": false
},
```

As you can see, the filters in this case are being applied server-side.

When possible, Cloud Custodian should use server-side filtering to optimize policy execution speed and reduce the likelihood of read timeouts when operating against large amounts of data w/out paging.

**To Reproduce**

Run Cloud Custodian against a policy using tag equality filters

**Expected behavior**

Cloud Custodian should apply the filters server-side

**Background (please complete the following information):**
 - OS: `Linux 47c05caf41de 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Python Version: `Python 3.8.5`
 - Custodian Version: `0.9.11`
 - Cloud Provider: AWS
 - Policy: See above
 - `custodian version --debug` output
```
Custodian:   0.9.11
Python:      3.8.5 (default, Jan 27 2021, 15:41:15)
             [GCC 9.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='f50e6da2a3a1', release='5.10.47-linuxkit', version='#1 SMP Sat Jul 3 21:51:47 UTC 2021', machine='x86_64')
Using venv:  True
Docker: True
Installed:

PyJWT==1.7.1
PyYAML==5.4.1
adal==1.2.6
appdirs==1.4.4
applicationinsights==0.11.9
apscheduler==3.7.0
argcomplete==1.12.2
attrs==20.3.0
azure-common==1.1.26
azure-core==1.12.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.6.0
azure-graphrbac==0.61.1
azure-identity==1.5.0
azure-keyvault==4.1.0
azure-keyvault-certificates==4.2.1
azure-keyvault-keys==4.3.1
azure-keyvault-secrets==4.2.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.0.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==6.1.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.0.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.0.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.0.0
azure-mgmt-subscription==1.0.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.8.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.4.1
azure-storage-queue==12.1.5
boto3==1.17.33
botocore==1.20.33
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
cryptography==3.4.6
decorator==4.4.2
distlib==0.3.1
dogpile.cache==1.1.2
google-api-core==1.26.1
google-api-python-client==1.12.8
google-auth==1.28.0
google-auth-httplib2==0.1.0
google-cloud-core==1.6.0
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.36.2
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
httplib2==0.19.0
idna==2.10
importlib-metadata==3.7.3
iso8601==0.1.14
isodate==0.6.0
jmespath==0.10.0
jsonpatch==1.32
jsonpickle==1.3
jsonpointer==2.1
jsonschema==3.2.0
keystoneauth1==4.3.1
kubernetes==10.0.1
msal==1.10.0
msal-extensions==0.3.0
msrest==0.6.21
msrestazure==0.6.4
munch==2.5.0
netaddr==0.7.20
netifaces==0.10.9
oauthlib==3.1.0
openstacksdk==0.52.0
os-service-types==1.7.0
packaging==20.9
pbr==5.5.1
portalocker==1.7.1
protobuf==3.15.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
ratelimiter==1.2.0.post0
requests==2.25.1
requests-oauthlib==1.3.0
requestsexceptions==1.4.0
retrying==1.3.3
rsa==4.7.2
s3transfer==0.3.6
setuptools==44.0.0
six==1.15.0
stevedore==3.3.0
tabulate==0.8.9
tzlocal==2.1
uritemplate==3.0.1
urllib3==1.26.4
websocket-client==0.58.0
zipp==3.4.1
```

**Additional context**

**Comment by ajkerrigan** [comment]
Thanks for another detailed issue report @robbie-demuth ! The `filters` block in a custodian policy is for custodian filters which evaluate client-side. Any support for server-side filters is defined per-resource and handled in the `query` block of a policy. In the case of EBS snapshots, the query schema is defined [here](https://github.com/cloud-custodian/cloud-custodian/blob/bb5dc8d5f1b2c9500e26d02630b64742dffcb432/c7n/resources/ebs.py#L134-L146). It looks like server-side filters can help with at least _some_ of the logic you're working with. For example, this policy:

```
policies:
  - name: garbage-collect-snapshots
    resource: ebs-snapshot
    filters:
      - type: value
        key: tag:appian:system
        value: SiteWorkerGroupOperator
      - type: value
        key: tag:appian:deletion-protected
        op: ne
        value: "true"
      - type: value
        key: tag:appian:expires-at
        value_type: age
        op: gt
        value: 0
```

Could take advantage of some server-side filtering with some changes like this:

```
policies:
  - name: garbage-collect-snapshots
    resource: ebs-snapshot
    query:
      - Name: "tag:appian:system"
        Values: ["SiteWorkerGroupOperator"]
      - Name: "tag-key"
        Values: ["appian:expires-at"]
    filters:
      - type: value
        key: tag:appian:deletion-protected
        op: ne
        value: "true"
      - type: value
        key: tag:appian:expires-at
        value_type: age
        op: gt
        value: 0
```

With those changes, server-side filters could make sure you only see system snapshots with an expiration tag set. Then your client-side filters could handle the more advanced conditional/date logic. (You may also want `value_type: expiration` for cases where you're looking at future dates.)

With all that said, this is at least a gap in the docs and possibly something we can revisit at a higher level. There is a lot of room for confusion given the overloaded meaning of `filter`, and the fact that `query` is a source-specific concept (see its usage with a [config source](https://cloudcustodian.io/docs/aws/topics/config.html#config-source)). Thanks again for opening this issue.
