### DISCUSSION TITLE
GCP saving resource details to GCS bucket

### DISCUSSION THREAD

**Discussion by harsh-cldcvr** [cloud-custodian/cloud-custodian#7443] [GCP]
### Ask your question

I am trying to get save custodian resource output to GCS bucket, it working fine and creating the Resource.json.gz file into Bucket. 

```
policies:
  - name: put-details-to-gcp-bucket
    description: |
      put-details-to-gcp-bucket
    resource: gcp.gke-cluster
```

### Relevant log/traceback output

But when i am trying to get the Resource from bucket i am getting this weird SSL error. 

i also tried by making bucket public if SSL due to any Auth issue. 

```shell
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
2022-02-21 12:35:31,865: custodian.commands:ERROR The following policies had errors while executing
```

### Get policy

```
policies:
  - name: get-details-from-gcp-bucket
    description: |
      get-details-from-gcp-bucket
    resource: gcp.gke-cluster
    filters:
      - type: value
        key: "subnetwork"
        op: intersect
        value_from:
            url: https://storage.googleapis.com/test-cloud-custodian/put-details-to-gcp-bucket/2022/02/21/06/resources.json.gz
            format: json
```
