### DISCUSSION TITLE
AWS China Lambda Not Triggering

### DISCUSSION THREAD

**Discussion by ghost** [cloud-custodian/cloud-custodian#7456] [AWS]
### Ask your question

CC lambda functions aren't triggering in AWS China. Policy is below.

When I try to test the lambda I get the following response:
```
{
  "errorMessage": "'detail'",
  "errorType": "KeyError",
  "requestId": "1a9a46b1-1e22-462b-949b-e28a26cc0141",
  "stackTrace": [
    "  File \"/var/task/custodian_policy.py\", line 4, in run\n    return handler.dispatch_event(event, context)\n",
    "  File \"/var/task/c7n/handler.py\", line 165, in dispatch_event\n    p.push(event, context)\n",
    "  File \"/var/task/c7n/policy.py\", line 1201, in push\n    return mode.run(event, lambda_ctx)\n",
    "  File \"/var/task/c7n/policy.py\", line 443, in run\n    resources = self.resolve_resources(event)\n",
    "  File \"/var/task/c7n/policy.py\", line 643, in resolve_resources\n    return super().resolve_resources(event)\n",
    "  File \"/var/task/c7n/policy.py\", line 415, in resolve_resources\n    resource_ids = CloudWatchEvents.get_ids(event, mode)\n",
    "  File \"/var/task/c7n/cwe.py\", line 145, in get_ids\n    resource_ids = cls.get_trail_ids(event, mode)\n",
    "  File \"/var/task/c7n/cwe.py\", line 109, in get_trail_ids\n    event_name = event['detail']['eventName']\n"
  ]
}
```
Here is my account.yml entry:
```
- account_id: '123456789123'
  email: some.email@email.com
  name: Account Name
  role: arn:aws-cn:iam::123456789123:role/MyRole
  vars:
    lambda_role: CloudEng-CloudCustodianRole
  regions:
    - cn-northwest-1
```

### Policy

```shell
policies:
  - name: EC2-AutoTag-Creator
    resource: ec2
    description: Cloud Custodian policy to auto tag EC2 instances.
    mode:
      type: cloudtrail
      role: "{lambda_role}"
      events:
        - RunInstances
    filters:
      - tag:cc:creator: absent
    actions:
      - type: auto-tag-user
        tag: cc:creator
```
