### DISCUSSION TITLE
Setting up Docker Custodian

### DISCUSSION THREAD

**Discussion by engineertree5** [cloud-custodian/cloud-custodian#7457] [General]
### Ask your question

I'm looking to run custodian as a custom docker image on AKS (azure Kubernetes). I'm having trouble deciphering your setup here in github. My understanding of docker is a simple one. Write down the steps to build the image in the `Docker` file. What I'm looking at in this repo is more so an advanced level of image building. I'd love to get a better understanding of how this works. Maybe you can add a simple README for custom docker images? Or if you have any blog or website that can assist with my learning of your Docker build setup? love the tool but would like to customize and containerize it. 

Clarity - I know I can run the container using `docker run -it` and passing in variables to do what necessary. However, I'd prefer to have those vars within the docker file itself. so building a cusom image i can add those variables within the docker file.Pass the RUN cmd which will execute the policies.yml ... or maybe I'm going about this wrong?

**Comment by thisisshi** [comment]
it's not ideal to build the image with vars built in, the image found at https://hub.docker.com/r/cloudcustodian/c7n is an omnibus image containing c7n, c7n azure, c7n, gcp, etc. Could you clarify why you want to build the variables into the image itself?

**Reply by engineertree5** [reply]
I believe it's a misunderstanding of how I'm to run this image as a container. I'm fully aware that I can use `docker run -it` like in the link you posted

```bash
$ docker run -it \
  -v $(pwd)/output:/home/custodian/output \
  -v $(pwd)/policy.yml:/home/custodian/policy.yml \
  -v $(cd ~ && pwd)/.aws/credentials:/home/custodian/.aws/credentials \
  -v $(cd ~ && pwd)/.aws/config:/home/custodian/.aws/config \
  --env-file <(env | grep "^AWS") \
  cloudcustodian/c7n run -v -s /home/custodian/output /home/custodian/policy.yml
```

I'll try the following this weekend (below) and report back in the event others have the same misunderstanding as me. Do you mind doing a quick scan of my thought process? want to make sure I'm headed in the right direction. Running locally everything works as expected (that is always the case, right?) but prior to your comment, I was attempting to build the c7n image myself + add the env vars and policy into the image. Now I'll be running it as a batch job. 

**c7n.yml**
Because I'm looking to run this as a container in my AKS cluster I'll just deploy this as a job (only run once). I've attached my own storage account where I'll be storing policies and saving the output as well. my ENV vars are set to use subscription "X" and assume the identity of the cluster. 

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: custodian
  namespace: janitors-closet
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: custodian
        image: "cloudcustodian/c7n"
        command: [ "cloudcustodian/c7n run -v -s /home/c7n/shared/output /home/c7n/shared/policy.yml"]
        env:
        - name: AZURE_SUBSCRIPTION_ID
          value: "xxx-xxx-xx-xxx"
        - name: AZURE_USE_MSI
          value: 1
        resources:
        volumeMounts:
        - name: azure
          mountPath: /home/c7n/shared
      volumes:
      - name: azure
        azureFile:
          secretName: storage-secret
          shareName: azurestorageacct
          readOnly: false
      restartPolicy: Never
  backoffLimit: 0
```
