### DISCUSSION TITLE
aws.iam-group | Detach Managed Policies

### DISCUSSION THREAD

**Discussion by joyceol** [cloud-custodian/cloud-custodian#7472] [AWS] [answered]
Hello, 

I'm trying to remove any new groups that is with the AdminstratorAccess attached.

However, I noticed that there ir no specific action for delete managed policies.

I've try to delete the group itself, but I get the error:  An error occurred (DeleteConflict) when calling the DeleteGroup operation: Cannot delete entity, must detach all policies first.

The Policy:

```yaml
policies:
  - name: iam-group-detach-policy
    resource: iam-group
    description: Detach AdministratorAccess policy from new roles
    mode:
        type: cloudtrail
        events:
          - source: iam.amazonaws.com
            event: CreateGroup
            ids: requestParameters.groupName
    filters:
    - type: has-specific-managed-policy
      value: AdministratorAccess
    actions:
      - type: delete
```
