### DISCUSSION TITLE
Can you make a tag mandatory provided another tag key/value exists

### DISCUSSION THREAD

**Discussion by timnolan1** [cloud-custodian/cloud-custodian#7483] [General] [answered]
Hello,
Is there a way to do this?  Our use case is as follows:
- **environment** is a mandatory tag that must be one of several values in a list (i.e., dev, prod, test, etc.)
- **IF** this value = 'test', then the tag **test-type** must be present on the resource
- **IF** this value != 'test', then the tag **test-type** is optional
Thank you

**Comment by thisisshi** [comment, marked as answer]
You can accomplish this with boolean filters, example below:

```yaml
policies:
- name: find-non-compliant-tagged-resources
  resource: aws.ec2
  description: checks to see if the tag environment is present and \
               if the value is "test" checks that tag tag-test \
               is also present.
  filters:
    - not:
      - or:
        - and:
          - tag:environment: present
          - tag:environment: test
          - tag:test-type: present
        - and:
          - tag:environment: present
```
