### DISCUSSION TITLE
How to use mutiple op values together with regex

### DISCUSSION THREAD

**Discussion by kukrejashyam** [cloud-custodian/cloud-custodian#7504] [General]
Hi Team & @kapilt ,

I wrote below piece of code that ensures that if a tag has value "test", "no backup" or "actifio", it is left untouched or else replaced with tag "test".
Now the issue is some users tag as "Test" or "Actifio" and hence I want to make above values case-insensitive using regex but how do I do it along with using "-ne" operation along with regex.

I would highly appreciate your help on this.
Thanks.

Regards,
Shyam Kukreja.

![image](https://user-images.githubusercontent.com/19922253/174793682-db46a1ef-14af-4cc7-bb0f-86814d4b9cde.png)

**Comment by thisisshi** [comment]
@kukrejashyam this can be accomplished with just the regex op:

```yaml
policies:
  - name: enforce-backup-tags
    resource: aws.ec2
    filters:
      - not:
        - type: value
          key: tag:test
          value: actifio|no backup|test
          op: regex
```

**Reply by kukrejashyam** [reply]
Hi @thisisshi ,
Appreciate your quick answer but this doesn't cover the scenario where if the tag "biorad:git:backup" (or its value) is absent. I want the "biorad:git:backup" tag to take "test" value by default & hence using "or" operator. Is there any way to combine "or" & "-ne" (not equal) operation together with "regex" feature ?

Attaching the absent snippet from above screen-shot to highlight.

![image](https://user-images.githubusercontent.com/19922253/174875611-6bca6e1e-9080-4262-a1f7-81dbc0029f4d.png)

**Reply by thisisshi** [reply]
Yes, you can nest the not/or filters:
```yaml
policies:
  - name: foo
    filters:
      - or:
        - tag:biorad:git:backup: absent
        - type: value
          key: tag:biorad:git:backup
          value: test
          op: regex
      - or:
        - not:
          - type: value
            key: tag:biorad:git:backup
            value: actifio|no backup
            op: regex
```

**Reply by kukrejashyam** [reply]
Hey @thisisshi ,
Thanks for the above code. I tried running above code but it **doesn't meet all** my requirements.

Let me try explaining the requirement again.
The code scans "biorad:git:backup" of all ec2 resources &

1. It will ignore if the tag "biorad:git:backup" has value "actifio" or "no backup" or "test" (case insensitive) - **above code meets this req.** 
2. If the tag is absent or blank, it creates the one with value "test" - **Not met.**
3. If the value of tag "biorad:git:backup" is other than in case 1, it would rename the value to "test" - **Not Met**

Can you help me with what is missing here ? I tried some combinations but none of them worked.

**Reply by thisisshi** [reply]
This will require multiple policies if you want to do different actions based on different conditions. I would recommend breaking down each case into a separate policy

**Reply by kukrejashyam** [reply]
Hey @thisisshi 
Highly appreciate your help. Finally the below piece of code met all my requirements in a single script. 
Thanks again.
```
policies:
  - name: enforce-backup-tags
    description: |
      Apply back-up tags to all EC2 instances with missing or incorrect
      `biorad:git:backup` tags.
    mode:
      type: periodic
      schedule: "cron(00 21 ? * * *)"  # 4pm EST time is 9 pm UTC us-east-2
      role: arn:aws:iam::{account_id}:role/service-role/Custodian-AWS-Lambda-Role
    resource: ec2
    filters:
      - or:
        - "tag:biorad:git:backup": absent
        - tag:biorad:git:backup: empty
        - type: value
          key: tag:biorad:git:backup
          value: test           #this value should be changed to production
          op: regex
        - not:
          - type: value
            key: tag:biorad:git:backup
            value: actifio|no backup|non-production   #
            op: regex

    actions:
      - type: tag
        key: biorad:git:backup
        value: "test"           #this value should be changed to production
```
