### DISCUSSION TITLE
Parsing a date format YYYY-MM-DD for EBS Volumes and Snapshot

### DISCUSSION THREAD

**Discussion by Oluadun** [cloud-custodian/cloud-custodian#7508] [General]
Hi all, please I need you all input on this. At my organization we implemented a cost optimization policy for unattached EBS Volume and unused EBS Snapshot leveraging the native mark-for-ops tag. Any volume/snapshot that has this tag will be excluded by this clean-up policy until the date specified in the tag's value.  We have an exception for tagged volumes/snapshot (tag the volume with date-to-archive or date-to-delete ‘ key and value). The date-based mechanism provided is YYYY-MM-DD. It been confirmed that there is nothing in CC for customizing that tag-value format for marked-for-op. The value must end with ": op@date", where "op" is some operation and "date" is "YYYY/MM/DD
.Therefore, any volume/snapshot that has this tag will be excluded by this clean-up policy that already exist until the date specified in the tag's value. I wiill appreciate your feedbacks. 
Regards.

**Comment by thisisshi** [comment]
Thanks for the question, I think this is actually a potential enhancement to the value filter to support a keyword "today", like so:

```yaml
policies:
  - name: test
    resource: aws.iam-role
    filters:
      - type: value
        key: tag:test
        value: today
        value_type: date
        op: eq
```

You would then be able to to less than, equal to, not equal, etc comparisons on your date tags or other attributes. Does this look like it would resolve? https://github.com/cloud-custodian/cloud-custodian/pull/7512

**Reply by thisisshi** [reply]
Actually, you should be able to just use the `age` value_type rather requiring new functionality, for example to find things that have a date tag that matches today:

```yaml
policies:
  - name: test
    resource: aws.iam-role
    filters:
      - type: value
        key: tag:test
        value: 0
        value_type: age
        op: eq
```
