### DISCUSSION TITLE
Check for 2 AWS active keys at the same time

### DISCUSSION THREAD

**Discussion by sumyrules** [cloud-custodian/cloud-custodian#7542] [AWS]
### Describe the feature

I was trying to implement some of the CIS AWS Foundations Benchmark v1.4.
I was able to finish most of those. The one below is bothering me a bit and I wonder if its already possible to do?

1.13 _Ensure there is only one active access key available for any single IAM user_

I am not able to find out if any of the IAM users in our account have 2 active access keys at the same time.

```
policies:
- name: iam-user-single-access-key 
  resource: aws.iam-user
  comment: |
    CIS AWS Foundations v1.4.0 (1.13)
   Ensure there is only one active access key available for any single IAM user
  filters:
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
         key: access_keys
         value: 1
         value_type: integer
         op: gt
```

I found out that the above code wont work as "access_keys" is an array as seen in resource.json.

How can I filter based on the status of the 2 active keys? Like below?
How do I specify a check with an array like :
` access_key_1.status = active &&  access_key_2.status = active`

```

{
  "Path": "/",
  "UserName": "",
  "UserId": "",
  "Arn": "arn:aws:iam:::user/
  "CreateDate": "2021-xxxxxx",
  "PasswordLastUsed": "2022-xxxxx",
  
  ],
  "c7n:AccessKeys": [
    {
      "UserName": "",
      "AccessKeyId": "",
      **"Status": "Active"**,
      "CreateDate": "2021-xxx",
      "c7n:match-type": "access"
    },
    {
      "UserName": "",
      "AccessKeyId": "",
      **"Status": "Active",**
      "CreateDate": "2022-xxx",
      "c7n:match-type": "access"
    }
  ],
```

**Comment by thisisshi** [comment]
Hi @sumyrules thanks for the question, you should be able to accomplish this with a JMESPath expression:

```yaml
policies:
- name: iam-user-single-access-key 
  resource: aws.iam-user
  filters:
      - type: credential
        key: access_keys.active
        value: true
      - type: value
        key: length("c7n:AccessKeys"[?Status == 'Active'])
        value: 1
        op: gt
```
