### DISCUSSION TITLE
EC2 instance not filtered by tag value with on/off hour

### DISCUSSION THREAD

**Discussion by Mornor** [cloud-custodian/cloud-custodian#7551] [AWS] [answered]
I have an EC2 instance tagged with "Schedule: OfficeHours". 

Using Cloudcustodian policy, I can filter it out: 
```
policies:
  - name: stop-after-hours
    resource: ec2
    filters:
      - tag:Schedule: "OfficeHours"
    actions:
      - stop
    mode:
      type: periodic
      schedule: "rate(10 minutes)"
      role: arn:aws:iam::XXXXXX:role/LambdaRoleCloudCustodian
```

Running a dry-run, I get
```
$> custodian run --dry-run -s out shutdown-out-of-office.yml
2022-07-05 14:41:36,062: custodian.policy:INFO policy:stop-after-hours resource:ec2 region:eu-central-1 count:1 time:0.70
```

Which is what I want to have. 

However, using `offhours`
```
policies:
  - name: stop-after-hours
    resource: ec2
    filters:
      - tag:Schedule: "OfficeHours"
      - type: offhour
        weekends: true
        default_tz: cet
        offhour: 15
    actions:
      - stop
    mode:
      type: periodic
      schedule: "rate(10 minutes)"
      role: arn:aws:iam::XXXXXX:role/LambdaRoleCloudCustodian
```

The instance is not found:
```
$> custodian run --dry-run -s out shutdown-out-of-office.yml
2022-07-05 14:43:29,265: custodian.policy:INFO policy:stop-after-hours-cologne resource:ec2 region:eu-central-1 count:0 time:0.00
```

It is currently 14:43pm, if that matters with `offhour`. 

What do I miss?
