### DISCUSSION TITLE
Usage of `fallback_schedule` option in RDS offhours policy

### DISCUSSION THREAD

**Discussion by alekhya114** [cloud-custodian/cloud-custodian#7581] [AWS]
Hi,
As per the [PR](https://github.com/cloud-custodian/cloud-custodian/pull/6603) I am using the `fallback_schedule` option in offhour filter as follows for non prod RDS instances with tag `rds_offhours:on` at the instance level with the below policy definition

```yaml
- name: Non-Prod-Off-Hours-RDS
    resource: aws.rds
    filters:
      - tag:rds_offhours: present
      - DBInstanceStatus: available
      - type: offhour
        opt-out: True
        fallback_schedule: off=(M-F,22)
    action:
      - stop
```

but when I run `custodian run` in dry-run mode It's asking for the required property offhour. If I provide it's considering only the value present at offhour key but not the fallback_schedule

Can anyone give an example of how I can achieve this with fallback_schedule

**Comment by thisisshi** [comment]
offhour is a required attribute, you need to add it in the filter:

```yaml
- name: Non-Prod-Off-Hours-RDS
    resource: aws.rds
    filters:
      - tag:rds_offhours: present
      - DBInstanceStatus: available
      - type: offhour
        opt-out: True
        fallback_schedule: off=(M-F,22)
        offhour: 22
    action:
      - stop
```
