### DISCUSSION TITLE
c7n-org dry-run with policy using resource: iam-policy always fails (all accounts) with UnrecognizedClientException

### DISCUSSION THREAD

**Discussion by iamperson347** [cloud-custodian/cloud-custodian#7606] [AWS]
Here is the policy - this is being executed against govcloud accounts.

```
  - name: iam-policy-account-audit-policy
    resource: iam-policy
    description: |
      Cloud Custodian IAM Policy account:* Audit
    mode:
      type: periodic
      role: arn:aws-us-gov:iam::{account_id}:role/<role removed>
      schedule: "rate(1 day)"
      packages: [boto3, botocore, urllib3]
    filters:
      - type: has-allow-all
      - type: used
    actions:
      - type: notify
        template: default.html
        template_format: "html"
        priority_header: "5"
        subject: "Cloud Custodian - Security Audit: IAM All"
        to:
          - <email address>
        transport:
          type: sqs
          queue: <sqs queue>

```

Here is the error we receive for all accounts:

`error:An error occurred (UnrecognizedClientException) when calling the GetResources operation: The security token included in the request is invalid`

What's odd is we have other policies working just fine, no others using the resource: iam-policy though. I see no errors/access denied exceptions in AWS Cloudtrail. Another oddity is that this only appears to happen during a dry-run.
