### DISCUSSION TITLE
AWS Lambda Regex Variables Environment

### DISCUSSION THREAD

**Discussion by marciogchahad** [cloud-custodian/cloud-custodian#7658] [AWS] [answered]
Hi everyone! 
I have many lambda functions using environment variables and I need to collect an information from all variables defined in all functions.

I tried to set the regex filter, but didn't work. 
Anyone made this configuration using regex on the filter?

This is an example about the filter:
```yaml
policies:
- name: find-all-lambdas
  resource: aws.lambda
  filters:
    - type: value
      key: Environment.Variables[]
      op: regex
      value: '^.*SOME_INFORMATION.*$'
```
  I appreciate the help guys!

**Comment by thisisshi** [comment, marked as answer]
Hi @chahadze we'll need some more info on what you're trying to do here, are you trying to find a value or key in all of the environment variables? Here's a sample policy to find any lambda functions that have a certain environment variable defined:

```yaml
policies:
  - name: find-key-in-env-vars
    resource: aws.lambda
    filters:
      - Environment.Variables: present
      - type: value
        key: keys(Environment.Variables)
        value: some_key
        op: in
        value_type: swap
```

here's a policy to find any functions that have a certain value in their environment variables

```yaml
policies:
  - name: find-key-in-env-vars
    resource: aws.lambda
    filters:
      - Environment.Variables: present
      - type: value
        key: values(Environment.Variables)
        value: some_value
        op: in
        value_type: swap
```

Edit Answer from the thread:

It's a bit of a hack as right now regex over list is not supported but you can do this with some jmespath functions:

```yaml
policies:
  - name: find-environment-variables-that-have-AKIA
    resource: aws.lambda
    filters:
      - Environment.Variables: present
      - type: value
        key: "values(Environment.Variables)[].starts_with(@, 'AKIA')"
        value: true
        op: in
        value_type: swap
```

**Reply by marciogchahad** [reply]
Hi @thisisshi, thank you for reply!
I tried to use this kind of configuration and I didn't have success.
I wish to use in the filter parameter the regex option, searching one specific information in the variables from Lambda. An example is to find all information that have "AKIA" (initials of AWS Access Keys).

**Reply by thisisshi** [reply]
It's a bit of a hack as right now regex over list is not supported but you can do this with some jmespath functions:

```yaml
policies:
  - name: find-environment-variables-that-have-AKIA
    resource: aws.lambda
    filters:
      - Environment.Variables: present
      - type: value
        key: "values(Environment.Variables)[].starts_with(@, 'AKIA')"
        value: true
        op: in
        value_type: swap
```
