### DISCUSSION TITLE
event shortcut not defined: CreateDistribution

### DISCUSSION THREAD

**Discussion by gsl-ghassengabsi** [cloud-custodian/cloud-custodian#7667] [AWS] [answered]
hello, 
I need to detect non compliant distribution by using this policy:
policies:
  - name: cf-disable-noncompliant-cloudfront
    mode:
      type: cloudtrail
      role: custodian-execution-iam-role
      events:
        - CreateDistribution
    resource: distribution
    filters:
      - "tag:ignore-custo-naming-rule": absent

i had this error:
policies += policy_load(config, f).filter(options.policy_filter)
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 60, in load
    [p.validate() for p in collection]
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 60, in <listcomp>
    [p.validate() for p in collection]
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 1084, in validate
    m.validate()
  File "/usr/local/lib/python3.7/site-packages/c7n/policy.py", line 628, in validate
    assert e in CloudWatchEvents.trail_events, "event shortcut not defined: %s" % e
AssertionError: event shortcut not defined: CreateDistribution

this error is related to that CreateDistributiondoeas not exist in  CloudWatchEvents.trail_events (https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/cwe.py )??
 if yes should i do a pr to add CreateDistribution inCloudWatchEvents.trail_events   or there is an other solution??
Someone can help me please?
Thanks.

**Comment by thisisshi** [comment, marked as answer]
Hi @gsl-ghassengabsi, we dont maintain a full list of shortcuts as there are a high number of events that users may want to trigger off of. To create a policy using the CreateDistribution event, you can define the event as so

```yaml
policies:
  - name: cf-disable-noncompliant-cloudfront
    mode:
      type: cloudtrail
      events:
        - event: CreateDistribution
          source: cloudfront.amazonaws.com
          ids: responseElements.distribution.id
    resource: distribution
    filters:
      - "tag:ignore-custo-naming-rule": absent

```
