### DISCUSSION TITLE
Running c7n-org via Lambda with containers

### DISCUSSION THREAD

**Discussion by jeff-wassouf** [cloud-custodian/cloud-custodian#7677] [AWS]
I am attempting to run the below Lambda code using docker images to execute c7n-org and potentially get it to run on a schedule. - reference: https://docs.aws.amazon.com/lambda/latest/dg/python-image.html

**Dockerfile**
```
FROM amazon/aws-lambda-python:latest

RUN pip3 install awscli
RUN pip3 install c7n-org 
COPY accounts.yml "${LAMBDA_TASK_ROOT}"
COPY friday-report-policy.yml "${LAMBDA_TASK_ROOT}"
COPY app.py "${LAMBDA_TASK_ROOT}"

CMD ["app.handler"]
```

**app.py**
```
import sys
import subprocess
import os

def handler(event, context):
    os.system('c7n-org run -c accounts.yml -s s3://example/c7n-org/ -u example.yml -r us-east-1 --dryrun'
```

**Example Policy** 
```
policies:
  - name: s3-global-access
    resource: s3
    region: us-east-1
    filters:
      - type: global-grants
        allow_website: false
      - tag:public: absent
    actions:
      - type: notify
      -  etc
```
 
Here is the error Lambda is outputting: 

**> OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'**

After some research 
_/tmp_ seems to be the only writable directory in AWS Lambda, all other directories are 'read only' 

In this scenario the error seems to be generating due to c7n-org writing to a read only cache folder under _/home/sbx_user1051/.cache/c7n-org_

My question is how can I change the path of this cache folder to write onto the _/tmp_ directory  instead? or is there a better solution, I am open to suggestions . Thank you.
