### DISCUSSION TITLE
How to set linuxFxVersion for Azure CloudCustodian

### DISCUSSION THREAD

**Discussion by blim747** [cloud-custodian/cloud-custodian#7716] [Azure] [answered]
Hello,

Azure Functions are deprecating Python 3.6 support in a month on Sep 30, 2022 ([Azure update doc](https://azure.microsoft.com/en-us/updates/azure-functions-support-for-python-36-is-ending-on-30-september-2022/))

My `azure-periodic` CloudCustodian rules run as Azure Functions and they either have `linuxFxVersion` unset or set to `python|3.6` (`az` command based on [this Azure doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level#changing-python-version)):
```
% az functionapp config show --ids <Azure Function ID>
{
  ...
  "limits": null,
  "linuxFxVersion": "python|3.6",
  "loadBalancing": "LeastRequests",
  ...
}
```

I notice in AWS there is a way to configure the `runtime` [here in CloudCustodian docs](https://cloudcustodian.io/docs/aws/resources/aws-modes.html#config-rule) and [this Medium example](https://ismsguy.medium.com/cloud-custodian-gz-output-files-6cd0fbfaed8a):

```
policies:
- name: sec-n-elb-internet-facing
  resource: aws.elb
  description: |
     This policy identifies all Load Balancers that are facing the
     Internet.
  filters:
    - Scheme: internet-facing
  mode:
    type: periodic
    schedule: "rate(3 days)"
    execution-options:
      output_dir: s3://example-bucket/cclogs/policy/{account_id}
    runtime: python 3.8
```

I looked through the [`azure-periodic` CloudCustodian Azure Reference](https://cloudcustodian.io/docs/azure/resources/azure-modes.html#azure-periodic) and couldn't find anything similar. **Is there a configuration to set the `linuxFxVersion` value for Azure CloudCustodian?**

Also asked [here on StackOverflow](https://stackoverflow.com/questions/73560996/how-to-set-linuxfxversion-for-azure-cloudcustodian)
