### DISCUSSION TITLE
Unused SNS Topic Policy Throws Warning

### DISCUSSION THREAD

**Discussion by PraxisTwirly** [cloud-custodian/cloud-custodian#7836] [AWS]
I tried to create a policy to identify SNS topics that are unused, but the following warning is raised and no resources are matched:

`custodian.filters:WARNING CW Retrieval error: 'TopicName'`

This is the policy that raises the warning message:

```
policies:
  - name: sns-topic-unused
    resource: sns
    filters:
      - type: metrics
        name: NumberOfMessagesPublished
        days: 60
        value: 0
        missing-value: 0
        statistics: Sum
        op: equal
```

According to custodian schema sns, the metrics filter is supported for SNS, so I believe this is the correct policy.  If I remove the filter altogether, then I get my expected unfiltered list of resources in the resources.json output file.

The following is an example of a redacted SNS topic that I get in the resources.json file when I have no filter.

```
  {
    "TopicArn": "arn:aws:sns:xx-xxxx-x:xxxxxxxxxxxxx:some_sns_topic_name",
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Sid\":\"__default_statement_ID\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"SNS:GetTopicAttributes\",\"SNS:SetTopicAttributes\",\"SNS:AddPermission\",\"SNS:RemovePermission\",\"SNS:DeleteTopic\",\"SNS:Subscribe\",\"SNS:ListSubscriptionsByTopic\",\"SNS:Publish\",\"SNS:Receive\"],\"Resource\":\"arn:aws:sns:xx-xxxx-x:xxxxxxxxxxxxx:some_sns_topic_name\",\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"xxxxxxxxxxxxx\"}}}]}",
    "Owner": "xxxxxxxxxxxxx",
    "SubscriptionsPending": "0",
    "EffectiveDeliveryPolicy": "{\"http\":{\"defaultHealthyRetryPolicy\":{\"minDelayTarget\":20,\"maxDelayTarget\":20,\"numRetries\":3,\"numMaxDelayRetries\":0,\"numNoDelayRetries\":0,\"numMinDelayRetries\":0,\"backoffFunction\":\"linear\"},\"disableSubscriptionOverrides\":false}}",
    "SubscriptionsConfirmed": "1",
    "DisplayName": "",
    "SubscriptionsDeleted": "0",
    "Tags": []
  }
```

Either I have encountered a bug for which I can file an issue or I am doing something wrong.  Any feedback is appreciated.
