### DISCUSSION TITLE
Creating a custom event filter

### DISCUSSION THREAD

**Discussion by SteveL1** [cloud-custodian/cloud-custodian#7855] [General]
I'm trying to extend custodian so that I can parse custom events.

Initially, all i'm trying to do is get it so that when a custom event is received in the default eventbridge uses the filter to parse the jmespath and perform an action.  But I can't get this part working

I've added it to the resource map and everything deploys ok, it just doesn't fire off the lambda.

I feel like i'm missing quite fundamental about how the class is constructed but I don't know what that is.

I would really appreciate it if someone can help me out here!

I've created a very simple class to look for "sltest" events
```
from c7n.query import (QueryResourceManager, TypeInfo)
from c7n.manager import resources

@resources.register('sltest')
class sltest(QueryResourceManager):

    class resource_type(TypeInfo):
        service = 'sltest'
        name = 'sltest'
        id = 'sltest'
```

and deployed this policy
```
  - name: sltest
    resource: sltest
    mode:
      type: cloudtrail
      role:CustodianLambdaExecutionRole
      events: 
        - source: sltest
          event: testevent
          ids: id
    filters:
      - "detail.type": "abc"
```

and the event looks like this
```
{
    "version": "0",
    "detail-type": "testevent",
    "source": "sltest",
    "account": "112233445566",
    "time": "2022-10-07T10:27:41Z",
    "region": "us-east-1",
    "resources": [],
    "detail": {
        "type": "abc",
        "eventSource": "sltest",
        "eventName": "testevent",
        "id": "123456"
    }
}
```
