### DISCUSSION TITLE
CodeCommit tags missing

### DISCUSSION THREAD

**Discussion by marcusit** [cloud-custodian/cloud-custodian#7955] [AWS]
We can't seem to get tags out of our CodeCommit repositories. When we run the exact same filter against other resources we do get a list of tags back. Our repos have tags attached to them.

**Install command:**
```
python3 -m venv custodian
source custodian/bin/activate
pip install c7n c7n-org
c7n-org run -c Accounts/aws-accounts.yml -s comp -u Policies/tag-compliance.yml -r us-east-1
```

**Filter (tag-compliance.yml):**
```
vars:
  tag-filters: &tag-compliance-filters
        - type: value
          key: "tag:my-tag"
          op: regex-case
          value: ^[a-z A-Z0-9_\\-]+$
policies:
  - name: codecommit
    resource: aws.codecommit
    filters:
      - not:
        - and: *tag-compliance-filters
```

**Output:**
```
 {
    "accountId": "1234567890",
    "repositoryId": "abc123-abc123-abc123-abc123-abc123",
    "repositoryName": "my-repo-name",
    "repositoryDescription": "This is a codecommit repository",
    "defaultBranch": "main",
    "lastModifiedDate": "2022-10-28T12:39:27.098000+00:00",
    "creationDate": "2022-03-08T16:08:21.915000+00:00",
    "cloneUrlHttp": "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-repo-name",
    "cloneUrlSsh": "ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-repo-name",
    "Arn": "arn:aws:codecommit:us-east-1: 1234567890:my-repo-name"
  },
```
