### DISCUSSION TITLE
Simple Policy with "gcp-audit" mode

### DISCUSSION THREAD

**Discussion by tnbabeysekara** [cloud-custodian/cloud-custodian#8000] [GCP]
Hi All, I'm trying to create a simple custodian policy using gcp-audit mode. This is the Policy file I'm using. 

```
vars:
  disallowed-machine-types: &disallowed-machine-types
    - "f1-micro"
    - "g1-small"
    - "n1-highcpu-32"
    - "n1-highcpu-64"
    - "n1-highcpu-96"
policies:
  - name: gcp-instance-approved-types
    resource: gcp.instance
    mode:
      type: gcp-audit
      methods:
        - "compute.instances.insert"
    filters:
      - type: value
        key: properties.machineType
        op: in
        value: *disallowed-machine-types
    actions:
      - type: delete
```

When I ran this. It's not getting any errors and successfully getting deploy the pub-sub topic and the cloud function. When I try to create a compute instance with a machine type in the disallowed list, I can see the cloud function is getting triggered. But nothing is happening. (Action is not working) Am I doing anything wrong here?
