### DISCUSSION TITLE
Use GCP labels for on/offhours

### DISCUSSION THREAD

**Discussion by hannachi-cision** [cloud-custodian/cloud-custodian#8046] [GCP]
Hi, I'm trying to use GCP labels to turn on and off instances but I can't get the labels to work.

I tested several codes and ways of doing this but did not succeed, here is an example of a policy I could use:

```yml
  policies:
  - name: stop-after-23
    resource: gcp.instance
    filters:
      - type: offhour
        weekends: false
        tag: GCPLABELNAME
        default_tz: Europe/Paris
        offhour: 23
    actions:
      - stop
```

I saw this piece of code on github and it seems to be part of the answer to my question but I don't understand it very well since there is no doc on it.

```py
# NOTE for GCP resources, eg sql-instance
        if found == self.fallback_schedule and 'labels' in i:
            found = i.get('labels', {}).get(self.tag_key) or found
        if found in (False, None):
            return False
```

Could someone explain to me how to use GCP labels with on/off hours?
