### DISCUSSION TITLE
How Cloud Custodian compute the filter?

### DISCUSSION THREAD

**Discussion by dehamzah** [cloud-custodian/cloud-custodian#8321] [General]
In [generic filter](https://cloudcustodian.io/docs/filters.html), we can pass multiple filter parameters to query the resources, is the order of the filter defined matter? How it works behind the scene?

**Comment by ajkerrigan** [comment]
### Short Answer

- Yes, the order matters - filters are evaluated top-down in the order they're defined in the policy
- Each filter sees only the resources that have matched the filters that came before it
- "Put value filters first!" is a good rule of thumb

### How Does it Work Behind the Scenes

While the details vary a bit based on a policy's [execution mode](), eventually custodian calls [`filter_resources()`](https://github.com/cloud-custodian/cloud-custodian/blob/e5d8be6d20ec47f654716fa4831c5d81979835c9/c7n/manager.py#L100-L119) which loops through filters in order.

Each filter has a chance to trim the list of resources that will be passed into the next filter in the list.

### How This Factors Into Policy Authoring

The "cost" of evaluating a filter can vary quite a bit. The generic filters you mentioned already have all the data they need, so they're usually pretty quick and easy to evaluate. Others (like the [metrics](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#aws-common-filters-metrics) filter) need to make additional API calls to get the data they need.

If we're looking at [unused RDS instances](https://cloudcustodian.io/docs/aws/examples/rdsdeleteunused.html) for example, this filter setup has to fetch CloudWatch metrics for all RDS instances:

```yaml
filters:
  - type: metrics
    name: DatabaseConnections
    days: 14
    value: 0
    op: equal
  - type: value
    value_type: age
    key: InstanceCreateTime
    value: 21
    op: gte
```

While this one only has to fetch metrics for instances that are over 21 days old, making it a more efficient policy:

```yaml
filters:
  - type: value
    value_type: age
    key: InstanceCreateTime
    value: 21
    op: gte
  - type: metrics
    name: DatabaseConnections
    days: 14
    value: 0
    op: equal
```

So as a rule of thumb... put those value filters first!

**Note:** If you have two _different_ value filters, the order doesn't typically matter so much. So go with whatever makes the policy the most readable/sensible to you and your fellow policy readers/writers.
