### DISCUSSION TITLE
Run Cloud Custodian against LocalStack

### DISCUSSION THREAD

**Discussion by ajkerrigan** [cloud-custodian/cloud-custodian#8335] [Tips and Tricks]
For testing or demo purposes it can sometimes be helpful to run Cloud Custodian policies against mock services. One way to do that is by:

- Running [LocalStack](https://localstack.cloud/)
- Defining [AWS config settings](https://gist.github.com/ajkerrigan/b5bb73a301c1a37187b3c4ec943cf471#file-config) that point to your LocalStack endpoints
- Using a [wrapper command](https://gist.github.com/ajkerrigan/b5bb73a301c1a37187b3c4ec943cf471#file-c7n-local) that forces Custodian to talk to the LocalStack endpoints

Note that this is experimental and does _not_ cover all use cases, but for some common resource types it can be a useful tool in your policy authoring/testing toolbelt.

**Comment by ajkerrigan** [comment]
Thanks to [changes in boto3 >= 1.28](https://github.com/boto/boto3/issues/2099#issuecomment-1626117882) this has become _so much easier_ :partying_face: . You now have two options:

1. Define a localstack profile in `~/.aws/config` that uses `endpoint_url` to target your running localstack instance. Example:

```ini
[profile localstack]
region                = us-east-2
output                = json
aws_access_key_id     = fake
aws_secret_access_key = fake
endpoint_url          = http://localhost:4566
```

2. Use the `AWS_ENDPOINT_URL` environment variable at runtime:

```console
> aws sts get-caller-identity

{
    "UserId": "AROA...:aj@speckledmonkey.com",
    "Account": "<real account id>",
    "Arn": "arn:aws:sts::<real>:assumed-role/..."
}

> env AWS_ENDPOINT_URL=http://localhost:4566 aws sts get-caller-identity

{
    "UserId": "AKIAIOSFODNN7EXAMPLE",
    "Account": "000000000000",
    "Arn": "arn:aws:iam::000000000000:root"
}
```

No plugins, no wrappers, carry on with your lives!

**Note:** If you're getting a bit more advanced and using this with _event-based_ policies, you'll also need to specify an endpoint override in your policy's `mode` block. For example:

```yaml
policies:
  - name: root-user-login-detected
    resource: aws.account
    mode:
      type: cloudtrail
      events:
        - ConsoleLogin
      role: ajtest
      # Make sure we have current versions of boto3 and botocore that support custom endpoint URLs...
      packages: [boto3, botocore]
      environment:
        Variables:
          AWS_ENDPOINT_URL: http://localhost:4566
```
