### DISCUSSION TITLE
Is monitoring for the lack of something possible?

### DISCUSSION THREAD

**Discussion by carmstrong23** [cloud-custodian/cloud-custodian#8605] [Tips and Tricks]
Hi,

I'm new to cloud custodian and I've searched around as much as I can for this, however I've got a use-case where I'd like to take action (Alert to SNS etc) when there are zero matches for a filter. Consider the case where I need to for example ensure VPC flow logging is there. There are examples to ensure that configuration on an existing resource is correct, however what if I wanted to say for example that there has to be at least one VPC flow log config as well.

Another example would be looking for an organisation cloudtrail trail in AWS, looking for existing organisation trails that are logging is ok, but what about looking for the existance of an organisation trail in the first place and alerting if it's not there (i.e a malicious actor removes it etc.)

**Comment by ajkerrigan** [comment]
There are a few different ways to approach this. Here are a few ideas...

### `not` Blocks

Sometimes it's helpful to write a filter that matches your "good" case, and then tucking it inside a `not` block to reverse the logic Using flow logs as an example, you might use a filter like this to make sure a VPC has active flow logs configured:

```yaml
policies:
  - name: aws-vpc-flow-logs
    resource: aws.vpc
    filters:
      - type: flow-logs
        enabled: true
```

But you can use this to see if there are _no_ active flow logs:

```yaml
policies:
  - name: aws-vpc-flow-logs
    resource: aws.vpc
    filters:
      - not:
        - type: flow-logs
          enabled: true
```

A similar approach can work for finding missing cloudtrail configurations.

### Account-Level Checks with the `missing` Filter

At an account level there's also the [missing filter](https://cloudcustodian.io/docs/aws/resources/account.html#aws-account-filters-missing) which can identify missing resources in an account. It's easier to describe with an example. This checks to see if an expected S3 bucket is missing in an account:

```yaml
policies:
  - name: missing-s3-bucket
    resource: account
    filters:
      - type: missing
        policy:
          resource: s3
          filters:
            - Name: my-bucket
```

More generally, this filter lets you run a separate "child" policy against an account and catch cases where that policy has no matches.

-----

There are other less-commonly-used ways too, but hopefully these two are a good start!
