### DISCUSSION TITLE
AWS: Tagging Using Hardcoded key-value

### DISCUSSION THREAD

**Discussion by mayankmajreti1** [cloud-custodian/cloud-custodian#8633] [AWS]
HIi, We use custodian regarding our compliance checks (mainly tag existence) and we wanted to go further by validating tag values as well.
We didn't find a way through custodian to allow check of tag values ?

**Comment by ajkerrigan** [comment]
There are some example policies checking tag compliance [here](https://cloudcustodian.io/docs/aws/examples/tagcompliance.html). The examples check for missing tags, but since they're using the [value filter](https://cloudcustodian.io/docs/filters.html#value-filter) you can check for values too.

For example you might start by finding resources that are missing a required tag:

```yaml
policies:
  - name: ec2-tag-compliance
    resource: ec2
    filters:
      - type: value
        key: "tag:Environment"
        value: absent
```

And then decide you want to find resources with tag values outside an approved list:

```yaml
policies:
  - name: ec2-tag-compliance
    resource: ec2
    filters:
      - type: value
        key: "tag:Environment"
        op: not-in
        value:
          - dev
          - qa
          - prod
```

And later try to maintain that list of valid tag values outside the policy, looking them up on demand with [value_from](https://cloudcustodian.io/docs/filters.html#value-from):

```yaml
policies:
  - name: ec2-tag-compliance
    resource: ec2
    filters:
      - type: value
        key: "tag:Environment"
        op: not-in
        value_from:
          url: s3://bucket/valid_tag_values.json
          expr: Environment[]
```

Where the contents of `s3://bucket/valid_tag_values.json` look like:

```json
{
    "Environment": [
        "dev",
        "qa",
        "prod"
    ]
}
```

The idea is that it can be helpful to start with a simple policy and test/refine it in stages from there.
