### DISCUSSION TITLE
ec2 scheduled shutdown specifying hour and minute for time.

### DISCUSSION THREAD

**Discussion by drewkrrb** [cloud-custodian/cloud-custodian#8804] [AWS] [answered]
Am running the offhour policy using tag base configuration. 

Here is my policy:
```
policies:
  - name: ec2-powerschedule-off
    resource: ec2
    description: |
       This policy checks EC2s periodically and power off based on the ec2 tag:powerschedule.
    mode:
        type: periodic
        schedule: 'rate(5 minutes)'
    filters:
       - type: offhour
         tag: powerschedule
         default_tz: sgt
    actions:
      - type: stop

  - name: ec2-powerschedule-on
    resource: ec2
    description: |
      This policy checks EC2s periodically and power on based on the ec2 tag:powerschedule.
    mode:
        type: periodic
        schedule: 'rate(5 minutes)'
    filters:
       - type: onhour
         tag: powerschedule
         default_tz: sgt
    actions:
      - type: start
```

Currently this is my schedule:
on=(M-F,8);off=(M-F,18)
so far it works fine, but i wanted to know if it is possible to specify the minutes on the schedule syntax.
Example:
 on=(M-F,8:30);off=(M-F,18)
