### DISCUSSION TITLE
Filter for check-permission for iam-policy for permissions that match "aws_resource:*"

### DISCUSSION THREAD

**Discussion by bostrowski13** [cloud-custodian/cloud-custodian#8864] [AWS] [answered]
Trying to find iam-policy resources that match things like "s3:*" or "sqs:*", not just *:*.  Im using the "check-permissions" type.

```
policies:
  - name: iam_policy_has_star_action
    resource: iam-policy
    filters:
        - type: check-permissions
          match: allowed
          actions:
            - '\w+:\*'
```

this is returning some, but not all resources that match this pattern.

is there a better way to do this?
