### DISCUSSION TITLE
Invalid policy error when running a documentation example

### DISCUSSION THREAD

**Discussion by entrustgabri** [cloud-custodian/cloud-custodian#9026] [AWS] [answered]
I am getting started with Cloud Custodian. I have taking a look at the AWS docs, and tried to reproduce an [example ](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#aws-common-filters-metrics) found in the Filters documentation. It is a very simple policy:

```
- name: ec2-underutilized
  resource: ec2
  filters:
    - type: metrics
      name: CPUUtilization
      days: 4
      period: 86400
      value: 5
      op: less-than
```

For some reason, when I run `custodian run --dryrun -s out ec2-underutilized ` I get the following error: 

`2023-10-03 17:44:36,980: custodian.commands:ERROR invalid policy file: ec2-underutilized error: Policy file top level data structure should be a mapping/dict, instead found:list
2023-10-03 17:44:36,981: custodian.commands:ERROR Found 1 errors.  Exiting`

I have been trying to find the cause of the error, but I have not been successful. What am I missing?

**Comment by ajkerrigan** [comment, marked as answer]
In a Cloud Custodian policy file, policies show up under a top-level `policies` key.

Some documentation examples (like the [write your first policy](https://cloudcustodian.io/docs/aws/gettingstarted.html#write-your-first-policy) section of getting started) include that `policies` key, while others include only the policy body.

For your example, the assumption is that an individual policy:

```yaml
- name: ec2-underutilized
  resource: ec2
  filters:
    - type: metrics
      name: CPUUtilization
      days: 4
      period: 86400
      value: 5
      op: less-than
```

would be part of a policy _file_ that could potentially contain multiple policies:

```yaml
policies:

  - name: ec2-underutilized
    resource: ec2
    filters:
      - type: metrics
        name: CPUUtilization
        days: 4
        period: 86400
        value: 5
        op: less-than

  - name: ec2-other-policy
    resource: ec2
    filters:
      - ...

  ...and potentially more policies...
```
