### DISCUSSION TITLE
How to add cloud custodian policy in AWS lambda function to run periodically?

### DISCUSSION THREAD

**Discussion by rameshprasath824** [cloud-custodian/cloud-custodian#9217] [AWS] [answered]
Can any one guide my how can I add my cloud custodian policy as a lambda function?

I have written a basic custodian policy which will look for particular tag is present or not, if not it will stop the instance.

```
policies:
  - name: list-ec2-instances
    resource: aws.ec2
    description: list the ec2-instances present in particular region
    filters:
      - "tag:Owner": "absent"
    actions:
      - stop
```
I am trying to add a lambda function with this custodian policy, which will run periodically/when any new instances state is "running".

Can anyone guide me how I can configure this policy in lambda function ?

**Comment by ajkerrigan** [comment]
If you want to run your policy any time an instance moves into "running" state, you can use the [ec2-instance-state execution mode](https://cloudcustodian.io/docs/aws/resources/aws-modes.html#ec2-instance-state). Adding it to your policy could look like this:

```yaml
policies:
  - name: stop-ec2-instances-without-required-tags
    resource: aws.ec2
    description: stop ec2 instances without an Owner tag
    mode:
      type: ec2-instance-state 
      role: arn:aws:iam::111111111111:role/cloud-custodian
      events: 
        - running
    filters:
      - "tag:Owner": "absent"
    actions:
      - stop
```

That would only see and stop instances as they transition _into_ a running state (either a fresh launch or starting a stopped instance), so it would ignore any instances that are already running.
