### DISCUSSION TITLE
Is it possible to ignore onhour?

### DISCUSSION THREAD

**Discussion by topfblumen** [cloud-custodian/cloud-custodian#9229] [AWS]
Hi Custodian Team,

i only want to turn off EC2 instances if for example I forgot to turn it off. For that reason I configured `maid_offhours = "off=[(M-F,17)];tz=cet"`.

But every morning my EC2 instances get started due to the configured [onhour](https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/filters/offhours.py#L542).

Is it possible to skip default onhours? Would it be a feature request?

My configuration policy looks like follwoing:

```yaml
policies:
  - name: ec2-power-on-working-hours-tag-value
    resource: ec2
    mode:
      type: periodic
      schedule: "{lambda-schedule}"
      role: "arn:aws:iam::{account_id}:role/{project-name}-lambda-ec2-role"
    filters:
      - and:
        - type: onhour
          weekends: false
          default_tz: cet
        - type: value
          key: "tag:custodian"
          value: "enabled"
    actions:
      - start

```

[1]: https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/filters/offhours.py#L542
