### DISCUSSION TITLE
Identify Public Subnet

### DISCUSSION THREAD

**Discussion by stephy14** [cloud-custodian/cloud-custodian#9369] [AWS]
I am trying to create a cloud custodian policy to check if a subnet is public or not. Basically trying to check if it has a route to the igw. The filter 'subnet' cannot be applied on the aws.subnet resource. Please share some thoughts on this

**Comment by ajkerrigan** [comment]
Yeah there's no subnet filter on a subnet itself. Since the check is against routes though, a policy like this will look at the route table:

```yaml
policies:
  - name: igw-routes
    resource: aws.route-table
    filters:
      - type: subnet
        igw: yes
        key: SubnetId
        value: present
```

Matching resources in the output from that policy would have a `c7n:matched-subnets` annotation listing matching subnets.
