### DISCUSSION TITLE
Consolidated metrics into single account in periodic mode

### DISCUSSION THREAD

**Discussion by danielhros** [cloud-custodian/cloud-custodian#9493] [AWS]
Hello, I'm trying to deploy periodic policy across multiple accounts using c7n-org tool and consolidate all metrics into one single account.  I have tried sooo many things already and I just can't figure out how to accomplish it. What am I missing?

**My configuration:**

*accounts.yml*
```
accounts:
  - account_id: "123456789012"
    name: account-A
    regions:
      - us-east-1
    role: arn:aws:iam::123456789012:role/c7n-org-role
  - account_id: "98765432109"
    name: account-B
    regions:
      - us-east-1
    role: arn:aws:iam::98765432109:role/c7n-org-role
```

*policy-periodic.yml*
```
  - name: metrics-test-periodic-ec2
    resource: aws.ec2
    filters:
      - "tag:custodian": present
    mode:
      type: periodic
      schedule: "rate(1 minute)"
      role: c7n-role
```

Command to deploy policies (from account-A)
```
c7n-org run --cache-period 0 -c metrics/accounts.yml -s outputs -u  metrics/policy-periodic.yml -r us-east-1 --verbose --metrics-uri 'aws://master?namespace=CloudMaid-Test&region=us-east-1'
```

Of course, this only sends metrics to the same account that is being executed against.

**Things I tried**
- used policy in pull mode instead of periodic -> that worked perfectly fine, metrics were consolidate into one account from both accounts
- set `assume-role` under `execution-options` -> lambda was executed in account where the role was assumed for (I want to execute policy in same account and then just send metrics to other account)
