### DISCUSSION TITLE
How to filter aws.iam-policy based on IAM Policy Statement fields?

### DISCUSSION THREAD

**Discussion by moharam-dev** [cloud-custodian/cloud-custodian#9506] [AWS]
I'm trying to filter AWS IAM policies based on different values in the policy statements but I can't get this to work. For example:
```
policies:
  - name: iam-policies-with-kms-decryption-permissions
    resource: iam-policy
    filters:
      - type: value
        key: Statement
        value:
          - Effect: Allow
            Action: kms:Decrypt
            Resource: "*"
```
I always getting matched count:0 

I didn't deep dive into code, but I can see that the value filter is working on the response from the "iam:GetPolicy" AWS API. while what I'm looking for is to work on "iam:GetPolicyVersion" response instead.

How to achieve that?

Thanks
