### DISCUSSION TITLE
Check IAM role inline policies permissions

### DISCUSSION THREAD

**Discussion by steromano87** [cloud-custodian/cloud-custodian#9602] [AWS] [answered]
Hello,

we are using the following rule to check for any IAM role which has full permissions on all resources and services (either using an inline policy or an atttached managed policy):
```yaml
policies:
  - name: notify-on-admin-role-creation
    resource: aws.iam-role
    description: |
      Notify via email when an IAM role with administrative permissions is created, excluding roles named "AdministratorAccess".
    filters:
      - type: check-permissions
        match: allowed
        actions:
          - '*:*'
```

Among all roles in the target AWS account, we have a role with the following inline policy:
```json
{
    "Statement": [
        {
            "Action": "*",
            "Effect": "Allow",
            "Resource": "*"
        }
    ],
    "Version": "2012-10-17"
}
```

We are not able to detect this role using the aforementioned policy.
Are we making any mistake when defining the policy?
We have used other filters (like the role name) and they work.

Best regards,
Stefano
