### DISCUSSION TITLE
Need to filter IAM resources with "resource:*"  permissions

### DISCUSSION THREAD

**Discussion by anilaws** [cloud-custodian/cloud-custodian#9727] [AWS]
```
policies:
  - name: filter-iam-roles-with-regex
    resource: iam-role
    filters:
      - type: value
        key: "tag:harsha-test"
        value_type: regex
        value: "resource:\".*\""
    actions:
      - type: tag
        key: working-success
        value: true
```
        
        for example, above policy is not able to flag an IAM role with  * permissions
