### DISCUSSION TITLE
Cannot handle "any array"

### DISCUSSION THREAD

**Discussion by jesayafn** [cloud-custodian/cloud-custodian#9746] [GCP]
I made some simple policy:
```yaml
policies:
  - name: instance-with-public-ip
    resource: gcp.instance
    filters:
    - type: value
      key: networkInterfaces[].accessConfigs[].natIP
      op: ni
      value: [null]
```

I got all instance by using that policy

If I specify the array like this:
```yaml
policies:
  - name: instance-with-public-ip
    resource: gcp.instance
    filters:
    - type: value
      key: networkInterfaces[0].accessConfigs[0].natIP
      op: ni
      value: [null]
```

One instance filtered. Can someone help me?

The goal: filtered that one instance without specify index of array
