### DISCUSSION TITLE
Why don't these 2 policies validate?

### DISCUSSION THREAD

**Discussion by matthewdeanmartin** [cloud-custodian/cloud-custodian#9798] [General]
These are from the documentation

```
❯ custodian version
0.9.41
```

```yaml
policies:
  - name: ec2-checker
    resource: aws.ec2
    mode:
      type: config-rule
      role: MyLambdaConfigRole
    filters:
      - type: image
        tag: "NotSupported"
        value: absent
```

```
2024-10-24 17:56:49,132: custodian.commands:ERROR Configuration invalid: bad_examples/config.yml
2024-10-24 17:56:49,132: custodian.commands:ERROR             Error on policy:ec2-checker resource:aws.ec2
Additional properties are not allowed ('tag' was unexpected)

            Failed validating 'additionalProperties' in schema[10]:
                {'type': 'object',
                 'additionalProperties': False,
                 'required': ['type'],
                 'properties': {'type': {'enum': ['image']},
                                'key': {'type': 'string'},
                                'value_type': {'$ref': '#/definitions/filters_common/value_types'},
                                'default': {'type': 'object'},
                                'value_regex': {'type': 'string'},
                                'value_from': {'$ref': '#/definitions/filters_common/value_from'},
                                'value': {'$ref': '#/definitions/filters_common/value'},
                                'op': {'$ref': '#/definitions/filters_common/comparison_operators'},
                                'value_path': {'type': 'string'}}}

            On instance:
                {'type': 'image', 'tag': 'NotSupported', 'value': 'absent'}
2024-10-24 17:56:49,132: custodian.commands:ERROR unknown
```

Also this one... after fixing indentation for role, it complains about `remove-keys`

```yaml
policies:
 - name: remediate
   resource: aws.iam
   mode:
     type: hub-finding
     role: MyRole
   filters:
     - type: event
       key: detail.findings[].ProductFields.aws/securityhub/ProductName
       value: GuardDuty
     - type: event
       key: detail.findings[].ProductFields.aws/securityhub/ProductName
       value: GuardDuty
   actions:
     - remove-keys
```

```
2024-10-24 18:05:20,132: custodian.commands:ERROR Configuration invalid: bad_examples/security_hub.yml
2024-10-24 18:05:20,132: custodian.commands:ERROR             Error on policy:remediate resource:aws.iam
{'name': 'remediate', 'resource': 'aws.iam', 'mode': {'type': 'hub-finding', 'role': 'MyRole'}, 'filters': [{'type': 'event', 'key': 'detail.findings[].ProductFields.aws/securityhub/ProductName', 'value': 'GuardDuty'}, {'type': 'event', 'key': 'detail.findings[].ProductFields.aws/securityhub/ProductName', 'value': 'GuardDuty'}], 'actions': ['remove-keys']} is not valid under any of the given schemas

            Failed validating 'anyOf' in schema['properties']['policies']['items']:
                {'anyOf': [{'$ref': '#/definitions/resources/aws.ec2/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-capacity-reservation/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-host/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-reserved/policy'},
                           {'$ref': '#/definitions/resources/aws.ec2-spot-fleet-request/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-certificate/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-group/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-oidc-provider/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-policy/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-profile/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-role/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-saml-provider/policy'},
                           {'$ref': '#/definitions/resources/aws.iam-user/policy'},
                           {'$ref': '#/definitions/resources/aws.launch-template-version/policy'},
                           {'$ref': '#/definitions/resources/aws.ops-item/policy'},
                           {'$ref': '#/definitions/resources/aws.securityhub-finding/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-activation/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-data-sync/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-document/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-managed-instance/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-parameter/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-patch-group/policy'},
                           {'$ref': '#/definitions/resources/aws.ssm-session-manager/policy'},
                           {'$ref': '#/definitions/resources/aws.step-machine/policy'}]}

            On instance['policies'][0]:
                {'name': 'remediate',
                 'resource': 'aws.iam',
                 'mode': {'type': 'hub-finding', 'role': 'MyRole'},
                 'filters': [{'type': 'event',
                              'key': 'detail.findings[].ProductFields.aws/securityhub/ProductName',
                              'value': 'GuardDuty'},
                             {'type': 'event',
                              'key': 'detail.findings[].ProductFields.aws/securityhub/ProductName',
                              'value': 'GuardDuty'}],
                 'actions': ['remove-keys']}
2024-10-24 18:05:20,146: custodian.commands:ERROR remediate
```
