### DISCUSSION TITLE
Another policy from docs that do not validate- OCI- tag-fast-connect

### DISCUSSION THREAD

**Discussion by matthewdeanmartin** [cloud-custodian/cloud-custodian#9812] [General]
This OCI example...

```yaml
    policies:
    - name: tag-fast-connect
      description: |
        Tag all the fast connect in the tenancy
      resource: oci.cross_connect
      actions:
       - type: update-cross-connect
         params:
           update_cross_connect_details:
             freeform_tags:
               TagName: TagValue
```

gives me 

```json
Error on policy:tag-fast-connect resource:oci.cross_connect
{'type': 'update-cross-connect', 'params': {'update_cross_connect_details': {'freeform_tags': {'TagName': 'TagValue'}}}} is not valid under any of the given schemas
```
