### DISCUSSION TITLE
Microsoft Team incoming Webhooks integration

### DISCUSSION THREAD

**Discussion by billlcosta** [cloud-custodian/cloud-custodian#9818] [AWS]
Hi everyone,

I tried setup a policy in cloudcustodian with action to send events to incoming webhook in Microsoft Teams. I setup too many times, in different modes, but, ever fails with HTTP 400 error. Now, my code block is:

```
    actions:
      - type: webhook
        url: https://sample.webhook.office.com
        body: |-
          '{"text": "Hello World!"}'
        headers:
          static-value: '`Content-Type: application/json`'
```

Relevants points:

- My Webhook its ok. I can send messages from curl command (example).

- If add other webhook URL (how slack) in cloudcustodian action, can send messages.

Anywhere can help-me?
