### DISCUSSION TITLE
Notifying when a change is made by ClickOps.

### DISCUSSION THREAD

**Discussion by ronaldoafonsoncsa** [cloud-custodian/cloud-custodian#9968] [AWS]
Is it possible to use Cloud Custodian so it will notify me when users make any changes via ClickOps? I mean, I need to know when some of my AWS users try to change anything using the AWS console.
  I tried something like:

```
    mode:
      type: cloudtrail
      role: CustodianRole
      events:
        - source: "*"
          event: "*"
          ids: "*"
```

  But it seems very intrusive (and seems that I'll have to pay a lot of money to AWS) and it didn't work.
