### DISCUSSION TITLE
Help needed setting up custodian policy to detect S3 OperationsFailedReplication

### DISCUSSION THREAD

**Discussion by mrvalterhugo** [cloud-custodian/cloud-custodian#9979] [AWS]
Hi, I have been trying to setup a policy that notifies bucket owners if there are any object replication failures based on the OperationsFailedReplication metric, but with not success.

I am using this policy:
```
- name: s3-failedreplication
  resource: s3
  filters:
    - type: metrics
      name: OperationsFailedReplication
      statistics: Sum    
      days: 2
      period: 86400
      value: 0
      missing-value: 0
      op: greater-than
```

This returns no resources, even though I can see some resources in cloudwatch metrics with replication failures.
I have tried a few different things, but no luck. I fell like this policy should work, but maybe I am missing something.

Appreciate any suggestions, thank you.
