### ISSUE TITLE
AWS - Support ElastiCache replication group automatic failover

### ISSUE THREAD

**Issue by jflim** [cloud-custodian/cloud-custodian#10069]
### Describe the feature

Would be useful to support automatic failover checking for `elasticache-group`

### Extra information or context

Resource type: AWS::ElastiCache::ReplicationGroup
AWS Config rule: elasticache-repl-grp-auto-failover-enabled

**Comment by ajkerrigan** [comment]
Since the `aws.elasticache-group` resource has `AutomaticFailover` as a top-level resource key, the generic [value filter](https://cloudcustodian.io/docs/filters.html#value-filter) can check in:

```yaml
policies:
  - name: elasticache-automatic-failover-enabled
    resource: aws.elasticache-group
    filters:
      - AutomaticFailover: enabled
```

Or the longer, more explicit form of the same policy:

```yaml
policies:
  - name: elasticache-automatic-failover-enabled
    resource: aws.elasticache-group
    filters:
      - type: value
        key: AutomaticFailover
        op: eq
        value: enabled
```
