### ISSUE TITLE
aws.dynamodb-table: set point in time `RecoveryPeriodInDays` parameter for `set-continuous-backup` action

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#10070]
### Describe the feature

I'd like to not only enable point in time continuous backup but I'd like to also set the `RecoveryPeriodInDays` parameter

```yaml
policies:
  - name: dynamodb-table-set-continuous-backup
    resource: aws.dynamodb-table
    tags:
      - schedule:daily
    filters:
      - type: continuous-backup
        key: PointInTimeRecoveryDescription.PointInTimeRecoveryStatus
        op: eq
        value: DISABLED
    actions:
      - type: set-continuous-backup
        state: true
        recovery-period: 14
```

https://github.com/cloud-custodian/cloud-custodian/blob/320d80397ebc774313c447ae15882e6edef2e028/c7n/resources/dynamodb.py#L206-L210

Might be as simple as

```diff
                client.update_continuous_backups(
                    TableName=r['TableName'],
                    PointInTimeRecoverySpecification={
                        'PointInTimeRecoveryEnabled': self.data.get('state', True)
+                       'RecoveryPeriodInDays': self.data.get('recovery-period', 14)
                    })
```

### Extra information or context

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PointInTimeRecoverySpecification.html
