### ISSUE TITLE
aws.kms-key - Add last-rotation filter

### ISSUE THREAD

**Issue by KarlCF** [cloud-custodian/cloud-custodian#10099]
### Describe the feature

I'd like to be able to utilize a filter in kms-key that leverages the list-key-rotation api, to be able to query/filter on the last rotation information.

Example:
```yaml
policies:
  - name: aws-kms-rotation-age
     resource: kms-key
     filters:
      - type: last-rotation
        key: RotationDate
        value: 30
        value_type: age
        op: gte

  - name: aws-kms-rotation-type
     resource: kms-key
     filters:
      - type: last-rotation
        key: RotationType
        value: ON_DEMAND
```

Reference:
https://docs.aws.amazon.com/kms/latest/APIReference/API_ListKeyRotations.html

Additionally, that information would also be either added to the schema or to the annotations, same as the key-rotation-status filter.
