### ISSUE TITLE
Azure Guest Configuration Assignments Filter for VM Resources

### ISSUE THREAD

**Issue by ratmav** [cloud-custodian/cloud-custodian#10188]
### Describe the feature

The azure.vm resource supports checking VM extensions via vm-extensions filter but has no equivalent for Guest Configuration assignments. Can verify Guest Configuration extension presence but cannot determine assigned configurations or compliance status.

Without this filter type, any attempt to check for guest configuration assignments will always return "absent" because Cloud Custodian has no way to retrieve the assignment data from the API. The filter type must exist before meaningful assignment queries are possible.

### Extra information or context

Affected Resource: azure.vm

Reference Implementation: Existing vm-extensions filter pattern

[Azure API](https://learn.microsoft.com/en-us/rest/api/guestcon
  figuration/guest-configuration-assignments/list?view=rest-guestconfigu
  ration-2024-04-05&tabs=HTTP): `GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/providers/Microsoft.GuestConfiguration/guestConfigurationAssignments?api-version=2024-04-05`

Azure CLI Command: `az rest --method GET --url "https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Compute/virtualMachines/<vm-name>providers/Microsoft.GuestConfiguration/guestConfigurationAssignments?api-version=2024-04-05"`

Example Usage

```yaml
# Check assignment existence:
resource: azure.vm
filters:
  - type: guest-config-assignments
    key: "[?name=='WindowsDefenderExploitGuard']"
    value: absent

# Check compliance status:
resource: azure.vm
filters:
  - type: guest-config-assignments
    key: "[?name=='WindowsDefenderExploitGuard'].properties.complianceStatus"
    value: "Compliant"
    op: not-equal
```
