### ISSUE TITLE
Add support for Azure Stack HCI Clusters resource

### ISSUE THREAD

**Issue by ratmav** [cloud-custodian/cloud-custodian#10198]
### Summary
Add support for `Microsoft.AzureStackHCI/clusters` resource type in Cloud Custodian to enable policy creation for Azure Stack HCI cluster security compliance monitoring.

### Use Cases
- **WDAC Compliance Monitoring**: Check Windows Defender Application Control enforcement status across HCI clusters
- **Security Baseline Validation**: Verify clusters maintain consistent security configurations  
- **Version Compliance**: Ensure clusters meet minimum version requirements for security features
- **Drift Detection**: Identify clusters with inconsistent application control policies

### Current Limitation
Cloud Custodian's existing Azure resources don't include support for `Microsoft.AzureStackHCI/clusters`, preventing governance of hybrid infrastructure security policies.

### Proposed Solution
Add a new resource type `azure.azurestackhci-cluster` that can:
- Query cluster properties including `reportedProperties.clusterVersion`
- Access security settings via `securitySettings/securityComplianceStatus.wdacCompliance`
- Enable filtering and actions on Azure Stack HCI clusters

### Example Usage
```yaml
policies:
  - name: azurestackhci-wdac-non-compliant
    resource: azure.azurestackhci-cluster  
    filters:
      - type: value
        key: reportedProperties.clusterVersion
        op: version-greater-than
        value: "10.0.20350"
      - type: value
        key: securitySettings.securityComplianceStatus.wdacCompliance
        op: not-in
        value: ["Compliant", "Pending"]
    actions:
      - type: notify
```

### API Reference
- **Clusters API**: https://learn.microsoft.com/en-us/rest/api/stackhci/clusters/get?view=rest-stackhci-2024-04-01
- **Security Settings API**: https://learn.microsoft.com/en-us/rest/api/stackhci/deployment-settings/get?view=rest-stackhci-2024-01-01

### Technical Challenge
The security compliance status is accessed via a separate `deploymentSettings` sub-resource, requiring either:
1. Sub-resource querying capability, or  
2. Resource augmentation to populate security settings from the deployment settings API
