### ISSUE TITLE
Azure VM Security Profile Properties Support

### ISSUE THREAD

**Issue by ratmav** [cloud-custodian/cloud-custodian#10233]
### Describe the feature

Cloud Custodian's Azure Virtual Machine resource (`azure.vm`) cannot access security profile properties from the Azure API response. This prevents implementing security policies that require checking VM security configurations such as secure boot status, trusted platform module (TPM) settings, and security type configurations.

The current VM implementation provides basic properties like size, OS configuration, and network settings, but not the security profile properties which are critical for compliance with security frameworks requiring specific VM security configurations.

### Extra information or context

Add security profile property access similar to existing VM property patterns.

**Proposed implementation:**
- Extend VM resource schema to include `securityProfile` properties
- Add filters for `securityType`, `uefiSettings.secureBootEnabled`, `uefiSettings.vTpmEnabled`
- Actions: `enable-secure-boot`, `configure-trusted-launch`

**Example policy syntax:**
```yaml
policies:
- name: vm-secure-boot-required
  resource: azure.vm
  filters:
  - type: value
    key: securityProfile.securityType
    value_type: swap
    op: in
    value: [TrustedLaunch, ConfidentialVM]
  - type: value
    key: securityProfile.uefiSettings.secureBootEnabled
    value: false
  actions:
  - type: enable-secure-boot
```

**Azure API Reference:**
- https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/get
- https://learn.microsoft.com/en-us/azure/virtual-machines/trusted-launch
