### ISSUE TITLE
Azure API Management Operations Usage Analytics Filter

### ISSUE THREAD

**Issue by ratmav** [cloud-custodian/cloud-custodian#10232]
### Describe the feature

Cloud Custodian's Azure API Management resource (`azure.api-management`) cannot access operation usage analytics to identify unused API endpoints. This prevents detecting operations that haven't received traffic for specified periods, which is critical for removing stale endpoints that increase attack surface.

The current implementation only supports service-level properties and certificates, but not usage analytics from API Management reports endpoints.

### Extra information or context

Add usage analytics filter similar to the existing `certificates` filter pattern.

**Proposed implementation:**
- `usage-report` filter accessing `/reports/byOperation` endpoint
- Filter by `callCountTotal`, `callCountSuccess` for configurable time periods
- Actions: `disable-operation`, `delete-operation`, `mark-for-review`

**Example policy syntax:**
```yaml
policies:
- name: api-management-unused-operations
  resource: azure.api-management
  filters:
  - type: usage-report
    days: 30
    threshold: 0
    report-type: operation
  actions:
  - type: mark-for-review
    tag: unused-endpoint
```

**Current limitations:**
- [azure.api-management](https://github.com/cloud-custodian/cloud-custodian/blob/main/tools/c7n_azure/c7n_azure/resources/apimanagement.py) only supports certificates (lines 45-60), not analytics
- [GenericArmResource](https://github.com/cloud-custodian/cloud-custodian/blob/main/tools/c7n_azure/c7n_azure/resources/generic_arm_resource.py) cannot access service-specific analytics APIs

**Azure API Reference:**
- https://learn.microsoft.com/en-us/rest/api/apimanagement/reports/list-by-operation?view=rest-apimanagement-2022-08-01

**Related Issues:**
Part of broader API Management sub-resource support: #10201, #10210, #10200, #10174
