### ISSUE TITLE
s3 filter for custodian role permissions on bucket

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#1027]
iam simulate to sanity check bucket policies for a set of actions or perhaps on named policy in the same file.

**Comment by whit537** [comment]
Stream of conscious channeling of @kapilt on weekly call:

> We're trying to scan through lots of s3 buckets for reasons that are a little bit silly, but ...
> 
>you can lock other people out of your s3 bucket
>
>want to check when someone locks someone out
>
>can custodian or another iam role or user access a bucket?
>
>using iam simulate w/ current user or passing in a user or role, + bucket to verify permissions (* to start with)
>
>resource-based policy vs. iam policy
>
>iam is complicated

**Comment by whit537** [comment]
Targeting policy like:

```yaml
policies:
  - name: s3-perm-check
    resource: s3
    filters:
    - type: access
      as: arn:::
      actions: []
      value: denied      
```

Aiming to make this a generic filter that can be applied to any resource.
