### ISSUE TITLE
RDS Offhours support ?  Example RDS Offhours policy ? 

### ISSUE THREAD

**Issue by dthauvin** [cloud-custodian/cloud-custodian#1310]
Hi
Is Offhours supported for RDS ? 
I find a "rds start/stop actions" commit so i guess yes indeed.

Could this policy works ? 
```
policies:
  - name: offhours-stop
    resource: rds
    filters:
      - type: offhour
        weekends: false
        default_tz: pt
        tag: downtime
        opt-out: true
        onhour: 8
        offhour: 20
```
thanks a lot

**Comment by scotwk** [comment]
@damdr - I don't have specific experience writing offhour policies, but I do see an offhour filter available for the `rds` resource.  You can see what actions and filters are available via the `schema` subcommand, e.g.

```
$ custodian schema rds
rds:
  actions: [auto-patch, auto-tag-user, delete, invoke-lambda, mark, mark-for-op, modify-security-groups,
    notify, put-metric, remove-tag, resize, retention, snapshot, start, stop, tag,
    tag-trim, unmark, upgrade]
  filters: [and, db-parameter, default-vpc, event, health-event, kms-alias, marked-for-op,
    metrics, network-location, not, offhour, or, security-group, subnet, tag-count,
    upgrade-available, value]
```

**Comment by jantman** [comment]
@damdr Have you tried it?

**Comment by mdxp** [comment]
I couldn't get it to work either.

**Comment by studiorak** [comment]
Hi,

Is there a workaround to the fact special characters (equal, commas, parentheses) are forbidden into some service's tags (for instance : rds).

Is that does exists, could you please share some example of configuration ?

PS: @mxdp : maybe you could share the tags you used as it could be a part of the solution...

Kind regards 
Jean-Luc R.

**Comment by dlut2** [comment]
As a workaround we use a custom tag to determine whether an RDS will be acted upon by a policy with explicitly pre-set timezone options.

```
- name: rds-offhour-stop-pstdown
    resource: rds
    comment: |
      At 7 PM PST, stop all RDS instances that have the tag custodian_rds_offhours_marker = 'stopped'
      AND the tag custodian_rds_offhours_timezone = 'estup_pstdown'
    filters:
      - type: value
        key: "tag:custodian_rds_offhours_timezone"
        op: eq
        value: "estup_pstdown"
      - type: value
        key: "tag:custodian_rds_offhours_marker"
        op: eq
        value: "stopped"
      - type: offhour
        tag: custodian_rds_offhours
        opt-out: True
        default_tz: pt
        offhour: 19
    actions:
        - stop
```
