### ISSUE TITLE
Notify action with SNS transport requires `to` field

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#1513]
Currently, the notify action requires the `to` / `to_from` field for all transport types:

```json
{
"oneOf": [
        {
            "required": [
                "type",
                "transport",
                "to"
            ]
        },
        {
            "required": [
                "type",
                "transport",
                "to_from"
            ]
        }
    ],
...
``` 

When using the notify action to trigger an SNS topic, however, only the topic should be required, since the `to` email address isn't actually being used. 

```python
    def send_sns(self, message):
        topic = self.data['transport']['topic']
        if topic.startswith('arn:aws:sns'):
            region = region = topic.split(':', 5)[3]
            topic_arn = topic
        else:
            region = message['region']
            topic_arn = "arn:aws:sns:%s:%s:%s" % (
                message['region'], message['account_id'], topic)
        client = self.manager.session_factory(
            region=region, assume=self.assume_role).client('sns')
        client.publish(TopicArn=topic_arn, Message=self.pack(message))
```
[`source`](https://github.com/capitalone/cloud-custodian/blob/master/c7n/actions.py#L496-L507)

This is confusing when writing policies, leading to the following:

```yaml
  actions:
      - type: notify
        to:
          - <some_email>@<some_domain>.xyz
        transport:
          type: sns
          topic: arn:aws:sns:<region>:<account_id>:<topic_name>
```

instead of:

```yaml
  actions:
      - type: notify
        transport:
          type: sns
          topic: arn:aws:sns:<region>:<account_id>:<topic_name>
```
