### ISSUE TITLE
Return Security Group id based on Tag key & value

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#1618]
Use case: Given that the modify-security-groups action when used with "remove" requires an isolation-group: security group id, there is a need to be able to determine that security group id dynamically rather than a static id, as static ids in policies are not sustainable in a multi-account scenario.

Request: The ability to lookup a Security Group Id based on Tag key & value.

**Comment by kapilt** [comment]
the common way we do this is to use a security-group filter on a resource, that will allow use of the sg group attributes as a filter mechanism, and then for modify-security-group you use the 'matched' key word, which will use the attributes matched

ie. here's a unit test with policy by way of example
https://github.com/capitalone/cloud-custodian/blob/master/tests/test_vpc.py#L409

and an example policy re using sg tagkey/value to find all ec2 instances with a given sg with a given tag key/value.

```
policies:
  - name: ec2-usage
    resource: ec2
    source: config
    filters:
      - type: security-group
        key: "tag:Name"
        value: InboundCore 
```

**Comment by FireballDWF** [comment]
Problem is I'm already using attribute matched to supply the parameter to removed, as seen in policy below, who's purpose is to remove any security groups which have been tagged for deletion from EC2 instances, so then a later run of another policy can delete those security groups which are tagged for deletion.  So need another way to populate the value for isolation group. 

```
policies:
  - name: security-group-remove-if-tagged-to-be-deleted
    resource: ec2
    description: |
      Remove security group from instances when the SG has been tagged to be deleted
    filters:
      - State.Name: running
      - type: security-group
        key: "tag:ToBeDeleted"
        value: "True"
    actions:
      - type: modify-security-groups
        remove: matched
        isolation-group: sg-123   # invalid for now
```
