### ISSUE TITLE
New policies to forbid S3 objects from having public ACLs

### ISSUE THREAD

**Issue by nchammas** [cloud-custodian/cloud-custodian#1714]
I'm new to Custodian and still tinkering with it (e.g. #1713), but I find the declarative style of Custodian policies very attractive and easy to understand.

I think the following policy capabilities would be a solid feature add to Custodian:
1. Prevent any `PutObject` or `PutObjectAcl` actions from writing objects to S3 with public ACLs.
2. Find and remediate existing or incoming S3 objects that have public ACLs.

I imagine this would be structured similar to the [S3 encryption policies](http://www.capitalone.io/cloud-custodian/docs/usecases/s3encryption.html). Perhaps it would look something like this:

```yaml
policies:
  - name: s3-no-public-keys
    resource: s3
    actions:
     - type: no-public-keys
       report-only: yes
  - name: s3-attach-no-public-keys
    resource: s3
    actions:
      - type: attach-no-public-keys
        role: arn:aws:iam::123456789012:role/my-role
        topic: arn:aws:sns::123456789012:my-topic
  - name: s3-no-public-keys-policy
    resource: s3
    actions:
     - no-public-keys-policy
```

Relevant docs:
* [PutObject](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) and [PutObjectAcl](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTacl.html) docs, showing how you can set `public-read` permissions on individual objects in S3, even if the bucket is private.
* [Bucket policy example](https://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html) showing how to reject `PutObject*` calls that set public ACLs.
* [Example CloudWatch + Lambda setup](https://aws.amazon.com/blogs/security/how-to-detect-and-automatically-remediate-unintended-permissions-in-amazon-s3-object-acls-with-cloudwatch-events/) showing how to detect and automatically remediate incoming S3 object writes that have public ACLs.

Is this feature a good fit for Custodian? If so, I would be interested in contributing it to the project. It seems like a non-trivial undertaking, so it would probably only work out if I had a shepherd willing to spend a little time with me providing guidance. But I am willing to put in the time here to contribute something that meets the project's standards.

**Comment by kapilt** [comment]
we've moving most of our object level processing in s3 to tools/c7n_salactus which does have this capability, on the basis that any at scale consideration needs scale out capabilities. it would probably still be good to have the ability to lambda attach this functionality on to bucket notifications (or indirectly via sns bucket notify)

**Comment by nchammas** [comment]
> we've moving most of our object level processing in s3 to tools/c7n_salactus which does have this capability

So are you saying that controlling S3 object ACLs is possible today with Cloud Custodian? Or just that the building blocks are available via `tools/c7n_salactus`?

There are three bits of related functionality that I provided examples for. I modeled them after similar functionality that Cloud Custodian has today to encrypt S3 objects:
1. Remediate existing objects with bad ACLs.
2. Catch new objects that come in with bad ACLs and remediate them immediately.
3. Prevent bad object ACLs from being created in the first place.

I gather from your comment here

> it would probably still be good to have the ability to lambda attach this functionality on to bucket notifications (or indirectly via sns bucket notify)

that you're saying feature 2 is not possible today. So are features 1 and 3 possible today?

I'm not clear from your comment whether a contribution is welcome or needed here. 😅

**Comment by ewbankkit** [comment]
@nchammas For point 3 above we are intending on adding an `add-bucket-policy-statement` (or some such name) action to allow bucket policy statements to be added to a bucket.

**Comment by ewbankkit** [comment]
@nchammas, following the merge of https://github.com/capitalone/cloud-custodian/pull/1773 you will be able to specify S3 bucket policies that block objects with public ACLs being created. e.g.
```
policies:
  - name: deny-s3-acls
    resource: s3
    actions:
      - type: set-statements
        statements:
          - Sid: "DenyPublicCannedAcl"
            Effect: "Deny"
            Principal: "*"
            Action:
              - "s3:PutBucketAcl"
              - "s3:PutObjectAcl"
              - "s3:PutObjectVersionAcl"
            Resource:
              - "arn:aws:s3:::{bucket_name}"
              - "arn:aws:s3:::{bucket_name}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl":
                  - "public-read"
                  - "public-read-write"
                  - "authenticated-read"
```
