### ISSUE TITLE
Empty metrics

### ISSUE THREAD

**Issue by Fodoj** [cloud-custodian/cloud-custodian#1719]
When I try to use --metrics option, only new dimensions (CloudMain) get created in CloudWatch - but no data points.

```
# tag-compliance.yml
policies:
  - name: tag-compliance
    resource: ec2
    filters:
      - "State.Name": running
      - or:
        - "tag:Owner": absent
        - "tag:CostCenter": absent
```

```
custodian run --region all --output-dir s3://my-bucket/custodian --metrics tag-compliance.yml
```

There are 4 instances that match this policy, and I can see them in CSV reports, as well as S3 bucket.

What am I doing wrong?
