### ISSUE TITLE
Is there an ability to add a tag to a snapshot that is created from the ec2 'snapshot' action?

### ISSUE THREAD

**Issue by caversa** [cloud-custodian/cloud-custodian#1777]
We currently create snapshots from each EC2 instance itself via a cron job and add an Expiration tag at the time of creation.  I'd like to use custodian policies instead for the creation to have it more centrally managed.  The snapshot action works great - just looking to add a tag for how long to keep it.  I already have a policy that looks for an 'Expiration' tag and deletes the snapshot when the time is greater than what is in the tag (which also works great).  

Although I'd love to use a robust solution like mentioned in  #226, my more basic workaround would be to have a tag set at the EC2 instance on how often the instance needs to be backed up (hourly, daily, weekly, etc or any combo), and then have a policy that looks for that tag and creates the snapshot at that time/interval with basic rules that I define on retention based upon that policy.  Although it could be more advanced/configurable than that, this meets the majority of my needs.  Aside from the policy below, I was thinking I'd also have an hourly, weekly, and monthly backup policy.

I do see the copy-tags, but do not see the ability to add a new tag (though I see in tag.py the utility is intended to be used pretty globally).  Am I missing something by chance, or is this functionality that would need to be added?  

```
policies:
  - name: ec2-daily-backup
    resource: ec2
    filters:
       - type: value
        key: "tag:custodian-backup"
        op: "regex"
        value: ".*daily.*"
     actions:
       - type: snapshot
         copy-tags:
         - Name
         - CostCenter
         - POC
         - Service
         tag:                     <------ something like this?
           key: "Expiration"
           value: timestamp + 7 days logic (don't have that syntax just yet)
```

Thanks, Carrie

**Comment by jtroberts83** [comment]
Hi Carrie, 
          The current method you are using would not work as its not supported.  What about if you copied that backup tag from the EC2 over to the snapshot (like the policy below) and then you could use the backup tag from a custodian ebs-snapshot policy like the one below.  Let me know if I am way off. :)

- Jamison
```
- name: ec2-daily-backup
    resource: ec2
    filters:
       - type: value
         key: "tag:custodian-backup"
         op: "regex"
         value: ".*daily.*"
     actions:
       - type: snapshot
         copy-tags:
         - Name
         - CostCenter
         - POC
         - Service
         - custodian-backup


- name: delete-old-daily-snapshots
  resource: ebs-snapshot
  filters:
        - type: age
          days: 7
          op: ge
        - type: value
          key: Description
          op: regex
          value: ^(Automated,Backup,-?)\w+
        - type: value
           key: "tag:custodian-backup"
           op: "regex"
           value: ".*daily.*"
  actions:
   - delete

```

**Comment by caversa** [comment]
Hi Jamison,

Thanks for that thoughtful answer; I do think that would work.  However, we use the Expiration tag across resources and it is a widely used convention within our company, so I was hoping to tie this in with the policies we already use and set the Expiration tag as the snapshot was created.

I'll mull this over - I may choose to add that 'add tag' feature on my own, or let the snapshots continue to be created via their cron jobs in order to add whatever tags we need.  Has anyone else expressed interest in having that as a feature, where it would benefit others to have this as well?  It may influence my decision on which option I choose.

Thanks, Carrie

**Comment by kapilt** [comment]
thats interesting re expiration tag, thanks for sharing, we could probably support something like that as a feature addition.

**Comment by caversa** [comment]
Hi Kapil, I missed your question earlier.   We use a UTC formatted date, such as '2018-01-05 14:01:02 UTC'.

**Comment by caversa** [comment]
For @jtroberts83 's suggestion (in case other people are considering this as well).  I think in many use cases, the same EC2 instance is backed up with different frequencies, such as both daily and weekly.  So if this is the case, you'd need two different custodian tags on the instance to indicate the backups.  Then you'd only copy the one tag down to the snapshot so that you aren't deleting the wrong snapshots.

```
policies:
  - name: ec2-daily-backup
    resource: ec2
    filters:
      - type: value
        key: "tag:custodian-daily-backup"
    actions:
       - type: snapshot
         copy-tags:
         - Name
         - CostCenter
         - custodian-daily-backup

  - name: ec2-weekly-backup
    resource: ec2
    filters:
      - type: value
        key: "tag:custodian-weekly-backup"
    actions:
       - type: snapshot
         copy-tags:
         - Name
         - CostCenter
         - custodian-weekly-backup
```

I was envisoning a single tag  that would indicate the frequencies of the backup, but this is doable for a workaround.
