### ISSUE TITLE
Can i filter resources created in any other region except us-east-1? 

### ISSUE THREAD

**Issue by dharaghodasara** [cloud-custodian/cloud-custodian#2053]
I want to delete all the resources which are being created in any region except us-east-1. 
Based on our policy, we need to us only us-east-1. If any thing is getting created, i want to delete as soon as it created. 

Can you provide some way?

**Comment by alfredgamulo** [comment]
In your policy, you can specify the regions to which the rule should be enforced. Eg:

```
- name: monitor-ec2-west
 resource: ec2
 region: us-west-2
 filters:
 ...
```
