### ISSUE TITLE
Need way to 'copy-volume-tags' to snapshot

### ISSUE THREAD

**Issue by davidclin** [cloud-custodian/cloud-custodian#2497]
Does Cloud Custodian have the ability to copy volume tags to snapshots?

Would love to replace [Graffiti Monkey](https://github.com/Answers4AWS/graffiti-monkey) with Cloud Custodian to:

(1) copy instance tags to volumes 
(2) copy volume tags to snapshots

This would also help my clients reduce their tooling footprint. 

By way of example, here's how several of my clients are using Graffiti Monkey:

```
_instance_tags_to_propagate:
  - 'Name'
  - 'Owner'
  - 'Team'

_volume_tags_to_propagate:
  - 'Name'
  - 'instance_id'
  - 'device'
  - 'Owner'
```

`_instance_tags_to_propagate` is used to define the tags that are propagated from an instance to its volumes. 
`_volume_tags_to_propagate` defines the tags that are propagated from a volume to its snapshots.

Looking at the **ebs schema**, it looks like (1) can be accomplished using the `copy-instance-tags` action. 

Looking at the **ebs-snapshot schema**, I was hoping to see a `copy-volume-tags `action.  Unless that's performed a different way?

**custodian schema ebs.actions**
(c7n_mailer) $ custodian schema ebs.actions
aws.ebs:
  actions: [auto-tag-user, **copy-instance-tags**, delete, encrypt-instance-volumes, invoke-lambda,
    mark, mark-for-op, modify, normalize-tag, notify, put-metric, remove-tag, rename-tag,
    snapshot, tag, tag-trim, unmark, untag]

**custodian schema ebs-snapshot.actions**
(c7n_mailer) $ custodian schema ebs-snapshot.actions
aws.ebs-snapshot:
  actions: [auto-tag-user, copy, delete, invoke-lambda, mark, mark-for-op, normalize-tag,
    notify, put-metric, remove-tag, rename-tag, tag, tag-trim, unmark, untag]

Hoping this is just my lack of knowing where to look and someone's done this before!

**Comment by davidclin** [comment]
Okay, good to know. This would be a well received enhancement and deployed immediately into our production.

**Comment by davidclin** [comment]
For the benefit of new users looking to replace Graffiti Monkey with Cloud Custodian to copy instance tags to ebs volumes and where the second use case of copying volume tags to snapshots is NOT business critical, the following policy has been proven to work in a production environment:

```
policies:
  - name: copy-instance-tags
    resource: ebs
    description: |
      Cloud Custodian Copy Instance Tag to Volume
    comment: |
      Copy instance tags to respective instance's ebs volume.
    mode:
      type: periodic
      role: arn:aws:iam::1234567890:role/CloudCustodian
      schedule: "rate(15 minutes)"
    filters:
      - type: value
        key: "Attachments[0].Device"
        value: not-null
    actions:
      - type: copy-instance-tags
        tags:
          - Name
      - type: copy-instance-tags
        tags:
          - Owner
      - type: copy-instance-tags
        tags:
          - Team
```

**Comment by thisisshi** [comment]
@AndrewCi not that I'm aware of, this does seem to be a fairly popular feature request though.

**Comment by thisisshi** [comment]
@scoleri yeah this looks like two enhancements:

1. copy-volume-tags action
```yaml
policies:
  - name: copy-vol-tags-to-snapshot
    resource: ebs-snapshot
    actions:
      - type: copy-volume-tags
        tags:
          - Name
```
2. copy volume tags to snapshot
```yaml
policies:
  - name: copy-vol-tags-on-snapshot
    resource: ebs
    actions:
      - type: snapshot
        copy-tags:
          - Name
```

**Comment by baptiste-s** [comment]
We would also need this feature :)

**Comment by tzd-sh** [comment]
Add me to this feature request.  graffiti-monkey does this well for one account, but I really need c7n-org's feature to do the same across multiple accounts.

**Comment by sri321** [comment]
We need this  feature too , Is there an update when this would roll out ??

**Comment by thisisshi** [comment]
@davidclin started working on this here: https://github.com/cloud-custodian/cloud-custodian/pull/3271

**Comment by thisisshi** [comment]
@davidclin this was added in a more generic way: https://github.com/cloud-custodian/cloud-custodian/pull/3489

gist of it is you can now copy any related tag onto the resource by specifying the resource type, the key where the related resource id will be queried from, and the tags you want to copy

**Comment by baptiste-s** [comment]
Hi guys,

thanks for the new feature. I needed to copy the tags from ebs volume to snapshot. I used the policies given as example. But It only copy the tag on the oldest snapshot and not all the snapshot. 

Am I doing something wrong ?

**Comment by baptiste-s** [comment]
Ok I figured out you only have one snapshot related to a volume. 

Then is it possible to copy the tags to all the snapshot one way or another ?

Actually my problem is that I am using snapshot action from ec2 ressources, but for some of them, I don't want to snapshot all the volume. Any clever way to proceed ?

thanks again

**Comment by kapilt** [comment]
@davidclin  the tags section is an array on that action so you can do a single api call to copy tags
ie.
```
    actions:
      - type: copy-instance-tags
        tags:
          - Name
          - Owner
          - Team
```
@baptiste-s wrt to copying via copy-related-tag, if your volumes have tags, the first policy sonny had can copy 1-n tags from volumes to snapshots.

i'll look at extending snapshot volume action to take additional tagging options
