### ISSUE TITLE
aws phd event policy lambda

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#2501]
ie subscribe to phd events and send notifications, we currently do filters on phd events for resources in periodics, it would be nice to structure those as event subscriptions.

**Comment by kumarsiyer** [comment]
@taohungyang FYI

**Comment by taohungyang** [comment]
I thought of this before.
Just wanna confirm if the schema would be something like this:
```
policies:
  - name: health-lambda-mode
    resource: ec2
    mode:
      type: health
      category: scheduleChange
      code: AWS_EC2_PERSISTENT_INSTANCE_RETIREMENT_SCHEDULED
    actions:
      - type: notify
        to:
          - resource-owner
```
Thanks!
