### ISSUE TITLE
Tag Filtering not working in GovCloud

### ISSUE THREAD

**Issue by thisRalff** [cloud-custodian/cloud-custodian#2544]
We are using Cloud Custodian for tag Enforcement. We have several AWS accounts, one that is in the GovCloud. Lambda, RDS, and Elasticache are all returning incorrect results when running within the govcloud. Here is an example:

```
  - name: elasticache-tag-compliance-notification
    comments: |
      The following elasticaches are either have an incorrect Group or the Group doesn't exist
    resource: cache-cluster
    filters:
    - type: value
      key: tag:Group
      op: ni
      value: ["value_1","value_2","value_3","value_4","value_5","value_6","value_7","value_8","value_9"]
```

In our normal accounts, this filter easily filters out any value for the 'Group' tag that doesn't match up. However, in govcloud, this returns 100% of the resources located within a resources within one of the resources above:

```
custodian run --output-dir=/opt/cloud_custodian/logs/ custodian run --output-dir=/opt/cloud_custodian/logs/ /opt/cloud_custodian/reports/absent_report.yml --cache-period 0 --region us-gov-west-1 -p elasticache-tag-compliance-notification -d
2018-06-20 18:30:19,549: custodian.policy:INFO policy: elasticache-tag-compliance-notification resource:cache-cluster region:us-gov-west-1 count:44 time:2.81
```

Please advise if there is any sort of special configuration that I need to do to get these resources working in govcloud.
