### ISSUE TITLE
How the root-login-detect policy work for iam user login?

### ISSUE THREAD

**Issue by nitinitare** [cloud-custodian/cloud-custodian#2614]
i want to get a notification when an IAM user logs into the console. I have used below script:
```yaml
policies:
- name: root-login-detected
  resource: iam-user
  description: |
    Notifies on root user logins
  mode:
     role: arn:aws:iam::{Account Id}:role/CloudCustodian
     type: cloudtrail
     events:
        -  ConsoleLogin
  filters:
    - type: event
      key: "detail.userIdentity.type"
      value: IAMUser
  actions:
    - type: notify
      template: default.html
      priority_header: 2
      subject: "Acccount - Root Login Detected - [custodian {{ account }} - {{ region }}]"
      violation_desc: "The Root User has logged in:"
      action_desc: "Actions Taken:  Notify Only"
      to:
        - email@example.com
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/{account ID}/custodiantest
        region: us-east-1
```
can someone please help me out.

**Comment by thisisshi** [comment]
what's your question?

**Comment by kapilt** [comment]
root account logins must use the `account` resource, since they are not an actual iam user.

**Comment by nitinitare** [comment]
Sorry my bad.... My question is what changes should i do to detect iam user login?

**Comment by selvidgej** [comment]
I too am seeking to do this. 
I tried to change the 
`  filters:
    - type: event
      key: "detail.userIdentity.type"
      value: IAMUser`
and then changed 
`
filters:
       - type: event
         key: "detail.userIdentity.type"
         value_type: swap
         op: in
         value: IAMUser
       - type: IAMuser
         key: "detail.userIdentity.userName"
         op: in
         userName: "selvidgej"
         accountId: 123412341234`

**Comment by coingraham** [comment]
Found this doing a search for the same.  Just remove the filter.

```policies:
  - name: console-login-detected
    resource: account
    description: |
      Notifies on console logins
    mode:
       type: cloudtrail
       role: arn:aws:iam::{account_id}:role/custodian
       events:
          - ConsoleLogin

**Comment by deepthimm** [comment]
- name: console-login-detected
    resource: account
    description: |
      Notifies on console logins
    mode:
       type: cloudtrail
       role: arn:aws:iam::{account_id}:role/custodian
       events:
          - ConsoleLogin
          Tried this to check the console logins but its not working. @coingraham Did you test it?

**Comment by coingraham** [comment]
I'm sorry it's been over a year and I'm not sure @deepthimm

**Comment by kapilt** [comment]
so your not trying to detect a root login, but any regular iam user login to the console?

**Comment by deepthimm** [comment]
@kapilt Hi Kapil, 
Yes. IAM users and SSO users.

**Comment by kapilt** [comment]
afaics it just needs a full event expression ie. ids (jmespath expression to extract user ids from event), source (signin.amazonaws.com), events (ConsoleLogin)

**Comment by deepthimm** [comment]
@kapilt something like this?

resource: account
    description: |
      Notifies Security and Cloud Admins teams on any AWS root user console logins
    mode:
       type: cloudtrail
       events:
         - source: signin.amazonaws.com
           event: ConsoleLogin
           ids: userIdentity.arn
    actions:
       - type: notify

**Comment by coingraham** [comment]
@kapilt @deepthimm so something like this?
```
- name: iam-login
  resource: iam-user
  comment: detect login
  mode:
    type: cloudtrail
    role: arn:aws:iam::123456789:role/cloud_custodian_role
    events:
      - source: signin.amazonaws.com
        event: ConsoleLogin
        ids: userIdentity.userName
```

**Comment by deepthimm** [comment]
@kapilt @coingraham 
- name: iam-login
  resource: iam-user
  comment: detect login
  mode:
    type: cloudtrail
    role: arn:aws:iam::123456789:role/cloud_custodian_role
    events:
      - source: signin.amazonaws.com
        event: ConsoleLogin
        ids: userIdentity.userName
        
        I tried that but it still doesn't work.

**Comment by ahmadzaikk** [comment]
@kapilt 

I tried the following policy but it still dose not work

- name: iam-login
  resource: iam-user
  comment: detect login
  mode:
    type: cloudtrail
    role: arn:aws:iam::123456789:role/cloud_custodian_role
    events:
      - source: signin.amazonaws.com
        event: ConsoleLogin
        ids: userIdentity.userName

**Comment by cguardia** [comment]
This works for me:

```
policies:
- name: user-login-detected
  resource: account
  mode:
    type: cloudtrail
    role: arn:aws:iam::1234567890:role/test_role
    events:
      - ConsoleLogin
  actions:
    - type: webhook
      url: https://mysite.com/
      query-params:
        policy: policy.name
        user: event.detail.userIdentity.userName
        type: event.detail.userIdentity.type
        mfa: event.detail.additionalEventData.MFAUsed
        result: event.detail.responseElements.ConsoleLogin
```

This will also detect root user logins, so if you need to skip those, just add the filters:

```
  filters:
    - type: event
      key: "detail.userIdentity.type"
      value: IAMUser
```
