### ISSUE TITLE
unable to exceute policies with mode:cloud trial

### ISSUE THREAD

**Issue by ngupta7** [cloud-custodian/cloud-custodian#2668]
This is my custodian policy 
```yaml
policies:
   - name: name-ec2-volumes-1
     description: |
       to tag ec2 instance
     resource: ec2
     mode:
       type: cloudtrail
       role: arn:aws:iam::<account-id>:role/Cloudcustodian
       events:
         - source: ec2.amazonaws.com
           event: RunInstance
           ids: "responseElements.instancesSet.items[].instanceId"
         - source: ec2.amazonaws.com
           event: CreateTag
           ids: "requestParameters.resourcesSet.items[].resourceId"
         - source: ec2.amazonaws.com
           event: DeleteTag
           ids: "requestParameters.resourcesSet.items[].resourceId"
     filters:
       - tag:onwer: absent
     actions:
       - type: tag
         key: rootvolume
```
when i execute the lambda it shows me unable to find resource ids :do i need to add something
```
[DEBUG]	2018-07-25T07:26:05.527Z	fcd5cd53-8fdb-11e8-866c-bbada918b0c7	Disabling cache
[INFO]	2018-07-25T07:26:05.527Z	fcd5cd53-8fdb-11e8-866c-bbada918b0c7	Found resource ids: []
[WARNING]	2018-07-25T07:26:05.527Z	fcd5cd53-8fdb-11e8-866c-bbada918b0c7	Could not find resource ids
```
