### ISSUE TITLE
VPN Connections, up or down?

### ISSUE THREAD

**Issue by larsrnielsen** [cloud-custodian/cloud-custodian#2683]
I cannot seem to find the right formula for determining if at least one of the tunnels are up or both are down. VPN connections are supported by Cloudwatch metrics, but the filter type metrics is not. If I try to do some JMESPath magic then something like `VpnConnections[*].VgwTelemetry[*].Status` or `[*].VgwTelemetry[*].Status` fails, even though they work fine with a JSON path tester. Is there some magic around?

Lars

~~~~
    "VgwTelemetry": [
      {
        "Status": "UP",
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2018-05-23T01:38:56+00:00",
        "OutsideIpAddress": "100.100.100.100",
        "StatusMessage": ""
      },
      {
        "Status": "DOWN",
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2018-07-26T23:53:41+00:00",
        "OutsideIpAddress": "100.100.100.101",
        "StatusMessage": ""
      }
    ]
~~~~

**Comment by kapilt** [comment]
sorry missed this issue, you wouldn't have the initial VpnConnections key, when custodian is looking at resources, its looking at individual resources, so the outer container wrapper key isn't present. As an example of what your trying to do.

```
name: down-connections
resource: vpn-connection
filters:
  - type: value
     key: VgwTelemetry[*].Status
     value: "DOWN"
     op: in
     value_type: swap
```
