### ISSUE TITLE
filter to find ec2 instance with an empty tag value.

### ISSUE THREAD

**Issue by nitinitare** [cloud-custodian/cloud-custodian#2684]
Hi All, I am trying to find out the instance which have "Test_Tagcc" tag and having no values.
Below is the policy. Can you please help me out what is the issue with it.
when i do the dry run it lists all the instances.

```yaml
policies:
- name: ec2-tag-compliance
  mode:
   role: arn:aws:iam::{AccountID}:role/CloudCustodian
   type: periodic
   schedule: 'cron(0/5 * * * ? *)'
  resource: ec2
  comment: |
    Find all (non-ASG) instances that are not conformant
    to tagging policies, and stop them.
  filters:
    - "tag:aws:autoscaling:groupName": absent
    - or:
        - "tag:Test_Tagcc": empty
  actions:
     - stop
```

**Comment by thisisshi** [comment]
it looks like what you actually want is:

```yaml
policies:
- name: ec2-tag-compliance
  mode:
   role: arn:aws:iam::{AccountID}:role/CloudCustodian
   type: periodic
   schedule: 'cron(0/5 * * * ? *)'
  resource: ec2
  comment: |
    Find all (non-ASG) instances that are not conformant
    to tagging policies, and stop them.
  filters:
    - "tag:aws:autoscaling:groupName": absent
    - "tag:Test_Tagcc": empty
  actions:
     - stop
```
