### ISSUE TITLE
azure - Add examples of delayed operation policies

### ISSUE THREAD

**Issue by billpratt** [cloud-custodian/cloud-custodian#2755]
We should add examples of how to do delayed operation policies to the Azure policies and examples documentation.

Example:
```
policies:
    - name: rg-mark-empty-for-deletion
      description: |
        Find any empty resource groups and mark for deletion in 7 days
      resource: azure.resourcegroup
      filters:
        - "tag:c7n_rg_empty": absent
        - type: empty-group
      actions:
        - type: mark-for-op
          tag: c7n_rg_empty
          op: delete
          days: 7
        - type: notify
          template: default.html
          priority_header: 1
          subject: "C7N - Empty Resource Groups Marked for Deletion - [custodian {{ account }} - {{ region }}]"
          violation_desc: "The following empty resource groups will be deleted in 7 days. Add resources to any empty group that should not be deleted."
          action_desc: |
              "Actions Taken:  Resource group deletion has been scheduled for 7 days from now.
              Add resources to an empty group that should not be deleted."
          to:
            - resource-owner
          transport:
            type: asq
            queue: https://storageaccount.queue.core.windows.net/queue-name
    - name: rg-unmark-if-not-empty
      resource: azure.resourcegroup
      description: |
        Remove the deletion tag from any resource group which now contain resources
        so it doesn't get deleted by the following policy
      filters:
        - "tag:c7n_rg_empty": not-null
        - not:
          - type: empty-group
      actions:
        - type: untag
          tags: ['c7n_rg_empty']
    - name: rg-delete-empty
      resource: azure.resourcegroup
      description: |
        Delete any marked resource groups which are empty
        if it has been that way for 7 days or more.
      filters:
        - type: marked-for-op
          tag: c7n_rg_empty
          op: delete
      actions:
        - type: delete
        - type: notify
          template: default.html
          priority_header: 1
          subject: "C7N - RG - Deleted Empty Resource Groups - [custodian {{ account }} - {{ region }}]"
          violation_desc: "No resources have been added for over 7 days:"
          action_desc: "Actions Taken:  The Resource Group has been deleted"
          to:
            - resource-owner
          transport:
            type: asq
            queue: https://storageaccount.queue.core.windows.net/queue-name
```
