### ISSUE TITLE
azure - expose app service plan metrics filters

### ISSUE THREAD

**Issue by wesyao** [cloud-custodian/cloud-custodian#2771]
App service plan are unable to filter by [metrics](http://capitalone.github.io/cloud-custodian/docs/azure/policy/genericarmfilter.html#azure-genericarmfilter). App service plans are quite expensive and policies can be written to clean up unused app service plans.

**Comment by logachev** [comment]
Metric filter does support app service plans:

```
policies:
  - name: sample
    resource: azure.appserviceplan
    filters:
      - type: metric
        metric: CpuPercentage
        aggregation: average
        op: ge
        threshold: 5
        timeframe: 12
```
