### ISSUE TITLE
How to remove a particular tag from ec2 instance?

### ISSUE THREAD

**Issue by nitinitare** [cloud-custodian/cloud-custodian#2856]
Below is the policy : 

```
policies:
- name: ec2-auto-tag-startinstance
  resource: ec2
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/CloudCustodian
    events:
      - source: ec2.amazonaws.com
        event: StartInstances
        ids: "responseElements.instancesSet.items[].instanceId"
  filters:
    - "tag:custodian": present
  actions:
    - type: remove-tag
      key: LastStartedBy
    - type: auto-tag-user
      tag: LastStartedBy
```

I have tried the above policy to remove the tag "LastStartedBy" but it is giving error.
Please let me know what is wrong in this policy? and what needs to be done?
