### ISSUE TITLE
EC2 Instance CreatedDate Tag

### ISSUE THREAD

**Issue by rajanbaski** [cloud-custodian/cloud-custodian#2864]
Hi,

We wanted to auto-tag EC2 Instance with username who created the Instance and CreatedDate to know when was the Instance first created. We are able to auto tag username using auto-tag-user action. Similar to auto-tag-user, can you also develop auto-tag-time with the EventName 'RunInstances'.

**Comment by kapilt** [comment]
There's built in formatting and variables for tag values that allow you to do this. The variable is `now` we have some extended syntax as well for performing date arithmetic as well.

here's an example, that will add two tags one with the current time, and one with the time in the future, date formatting options are documented at http://pyformat.info


```
policies:
 - name: ec2-image-check
   resource: ec2
   filters:
    - or:
      - Launched: absent
      - Expires: absent
   actions:
    - type: tag
      tags:
        Launched: "{now:%Y-%m-%d}"
        Expires: "{now:+7d%Y-%m-%d}"
```
