### ISSUE TITLE
azure - get service properties for tables/queues/blob

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#2889]
azure.storage resource doesn't return logging or metrics information on queues/tables/blob, need new filter to get service properties back

proposed syntax:
```yaml
policies:
  - name: logging-on-az-queues
    resource: azure.storage
    filters:
      - type: queue-service-properties
        key: logging.read
        value: true
      - type: queue-service-properties
        key: logging.write
        value: true
      - type: queue-service-properties
        key: logging.delete
        value: true

  - name: logging-on-az-blob
    resource: azure.storage
    filters:
      - type: blob-service-properties
        key: logging.read
        value: true
      - type: blob-service-properties
        key: logging.write
        value: true
      - type: blob-service-properties
        key: logging.delete
        value: true

```
