### ISSUE TITLE
BUG - Failure to execute second actions when some resources failed first.

### ISSUE THREAD

**Issue by rbowlby** [cloud-custodian/cloud-custodian#2892]
For policies whose filter matches multiple resources, where a given action fails on a subset of those resources, the second action fails to execute for the resources that succeeded on the first action.

Example:

A policy that terminates EC2 instances, where it succeeded in termination for some and failed for others - due to disableApiTermination. The first action was `terminate` and the second a `notify`. Those resources that were successfully terminated did not have the notify action execute. Leaving end-users unaware that some instances were terminated.

Resolution:

For a group of resources have those that succeed on the first action continue. Limit stop of execution to only those resources that failed on the current action.

```
policies:
  - name: ec2-terminate-stopped-instances
    resource: ec2
    filters:
      - "State.Name": stopped
    actions:
      - type: terminate
      - type: notify
        template: slack
        violation_desc: |
            These EC2 instances were stopped and have been terminated.
        to:
          - arn:aws:sns:us-west-2:REDACTED:cloud-custodian-slack
        transport:
          type: sqs
          queue: https://sqs.us-west-2.amazonaws.com/REDACTED/cloud-custodian-mailer
          region: us-west-2
```
