### ISSUE TITLE
asg resource doesn't follow the standard pattern for `remove-tag` action

### ISSUE THREAD

**Issue by nerdyness** [cloud-custodian/cloud-custodian#2928]
All resources support the action `remove-tag` via the following syntax:
```
actions:
  - type: remove-tag
    tags:
      - tag1
      - tag2
```
Except for asg which expects the following syntax:
```
actions:
  - type: remove-tag
    key: tag1
```
It would be nice to have consistency around the `remove-tag` action.
