### ISSUE TITLE
aws - member-role againt metrics on central account

### ISSUE THREAD

**Issue by cholletjo** [cloud-custodian/cloud-custodian#2932]
Hello,

Coming back again with the policy to detect S3 buckets from central account to many account based on event bus and using the member-role.  :)
I activate the generation of metrics on it, but metrics are created on distant account and not on central account as I would like.

Maybe I'm missing something, is there any chance to have a configuration to allow to have this metric on central account?

Here my configuration:
```
policies:
  - name: S3Public
    comment: "Detection  S3 public"
    mode:
          timeout: 200
          type: cloudtrail
          events:
              - source: s3.amazonaws.com
                ids: requestParameters.bucketName
                event: CreateBucket
              - source: s3.amazonaws.com
                ids: requestParameters.bucketName
                event: PutBucketAcl
          function-prefix: lambda-custod-
          role: arn:aws:iam::xxxxxxxx:role/role-cloudcustodianmgt
          member-role: arn:aws:iam::{account_id}:role/role-cloudcustodian
          execution-options:
            metrics_enabled: true
    description: |
        Cloud Custodian Policy - Based on bus event, catch S3 ACL Bucket update and remove public access.
    resource: s3
    filters:
       - type: global-grants
    actions:
        - type: delete-global-grants
          grantees:
            - "http://acs.amazonaws.com/groups/global/AllUsers"
            - "http://acs.amazonaws.com/groups/global/AuthenticatedUsers"
        - type: notify
          to:
            - arn...
          template: template
          transport:
            type: sqs
            queue: queue...
```

Thanks for your support,
Regards,
