### ISSUE TITLE
aws c7n_mailer - user is a valid email in IAM and I can use it to notify him by email

### ISSUE THREAD

**Issue by cholletjo** [cloud-custodian/cloud-custodian#2933]
Hello,

We did a test on policy which check Access Keys expiration on IAM and if Access Keys is older than 90 days, we notify directly user by email to renew it. Taking into account that our user are valid email, we did a very small modification on c7n_mail in c7n_mailer/email_delivery.py to make it work.

Creation of new function:
```
    def get_user_name_from_iam(self, sqs_message, resource):
        if 'iam-user' not in sqs_message['action']['to']:
            return []
        iam_user_mail = [resource.get("UserName", "")]
        return self.get_valid_emails_from_list(iam_user_mail)

```

Call to the function when building resource_emails:
```
# add the username to the list of users
            iam_user_mail = self.get_user_name_from_iam(sqs_message, resource)
            resource_emails = resource_emails + iam_user_mail
```

From policy we add as "to", iam-user, which allow to send an email to each user which is mathing with the filter:

```
       - type: notify
         to:
          - iam-user
         template: template.html
         template_format: html
         subject: "My subject"
```

If someone is interesting I can attached the complete code of email_delivery.py.
Hope it can give some help for people which need such use case.

Regards,
