### ISSUE TITLE
CloudTrail - Support for enabling log file validation

### ISSUE THREAD

**Issue by mukavik** [cloud-custodian/cloud-custodian#2951]
It would be good if an action on CloudTrail can be added to enable log file validation for new or existing trails.

**Comment by kapilt** [comment]
missing where this isn't possible today, ie. find all the multi-region trails with log file validation disabled via.. 

```
policies:
    - name: trails-missing-logfile
      resource: cloudtrail
      filters:
        - IsMultiRegionTrail: true
        - LogFileValidationEnabled: false
```
