### ISSUE TITLE
"Periodic" runs when I deploy my rule...

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#2952]
Hi,

So I've created this policy:

```
policies:
  - name: untagged-offhour-ec2-rule-stop
    resource: ec2
    mode:
     type: periodic
     schedule: "cron(00 20 ? * MON-FRI *)"
     role: [Insert Role Here]
    filters:
     - "tag:OffHour": empty
    actions:
      - stop
```
and it all works fine, stops untagged ec2's at the right time and all is good... Besides one thing...

When I run this from my terminal to create a Lambda, and then run the lambda, it will stop all untagged ec2's before the time I have set. 

Although it will run at the time I set, it also runs when I deploy which is the issue.
