### ISSUE TITLE
Variables interpolation with c7n-org and without

### ISSUE THREAD

**Issue by danieleb0101** [cloud-custodian/cloud-custodian#3014]
I have the following policy:
```
 - name: ebs-mark-unattached-deletion
    resource: ebs
    filters:
      - Attachments: []
      - "tag:maid_status": absent
    actions:
      - type: mark-for-op
        op: delete
        days: 1
```
but I would like to customize the number of days depending on the account in use.
For example for account1 I would like to delete the volumes the day after, while in account2 I would like to delete them after 30 days.
It would be nice if I could do something like

How can I achieve this behavior with c7n-org and without?
