### ISSUE TITLE
DynamoDB encryption filter

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3066]
I've tried everything I can think of. Have changed the filter to tags and it works fine, but it won't with encryption.

```
policies:
   - name: unencrypted-dynamodb-delete-on-create
     resource: dynamodb-table
     mode:
       type: cloudtrail
       events:
       - CreateTable
       role: arn:aws:iam::**********:role/cloudcustodian_lambda_role
     filters:
       - Encrypted: false
     actions:
       - delete
```

The only bit i need is an encryption filter so I can make a policy to delete un encrypted dynamoDB tables.
