### ISSUE TITLE
Azure - Resize App service plan - B SKU absent

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#3140]
### Description: 
The Basic (B) tier SKU is absent from the code in appserviceplan.py which was merged in with #3130. Output from a policy run of trying to resize an app service plan currently in B tier results with an error. Is it not possible to resize a B tier? I'm unclear if the tier was intentionally left out of the recently merged code: 

### Output
```
  File "/virtualenv/lib/python3.7/site-packages/c7n_azure/resources/appserviceplan.py", line 89, in process_resource_set
    client.app_service_plans.update(plan['resourceGroup'], plan['name'], model)
  File "/virtualenv/lib/python3.7/site-packages/azure/mgmt/web/operations/app_service_plans_operations.py", line 465, in update
    raise models.DefaultErrorResponseException(self._deserialize, response)
azure.mgmt.web.models.default_error_response_py3.DefaultErrorResponseException: Operation returned an invalid status code 'Bad Request'
```
Adding in the B tier to the static method and the schema in my pip env still results with the same error: 
```    @staticmethod
 92     def lookup_tier(size):
 93         tiers = {
 94             'F': 'Free',
 95             'B': 'Basic',
 95             'S': 'Standard',
 96             'D': 'Shared',
 97             'P': 'Premium'
 98         }
```
```    schema = utils.type_schema(
 64         'resize-plan',
 65         **{
 66             'size': {'type': 'string', 'enum': ['F1', 'B1', 'B2', 'B3', 'D1', 'S1', 'S2', 'S3', 'P1', 'P2', 'P3']},
 67             'count': {'type': 'integer'}
 68         }
 69     )
```

**Comment by stefangordon** [comment]
I updated that PR with an exception handler that dumps the inner exception object out before the exception is raised.  That is the only way to really see what is causing the "bad request" -- If you are updating that code by hand anyway perhaps add that exception handler in and see what is behind your error? 

https://github.com/capitalone/cloud-custodian/pull/3141/files#diff-427f53eef9225c43717c50667f730a4dR90

**Comment by jdogg89** [comment]
@stefangordon thanks I'll start testing this morning

**Comment by stefangordon** [comment]
fwiw my policy looked like this

```
policies:
  - name: azure-resize-plan
    resource: azure.appserviceplan
    filters:
     - type: 'value'
       key: 'name'
       op: 'eq'
       value_type: 'normalize'
       value: 'test-appserviceplan'
    actions:
     - type: resize-plan
       size: 'B1'
```

**Comment by jdogg89** [comment]
Perhaps the issue is the policy I'm using, I'll try yours out and see what my results are. Here's the policy I'm using:
```
policies:
  - name: azure-resize-plan
    resource: azure.appserviceplan
    filters:
      - tag:scaledown: present
    actions:
     - type: resize-plan
       size: 'S2'
```
Here's the output after adding in your try/catch. It doesn't like the sku.name for some reason:

```
2018-11-15 07:58:20,970: custodian.actions:ERROR Failed to resize cloud-custodian.  Inner exception: {'additional_properties': {'Details': [{'Message': 'The parameter SKU.Name has an invalid value.'}, {'Code': 'BadRequest'}, {'ErrorEntity': {'MessageTemplate': 'The parameter {0} has an invalid value.', 'Parameters': ['SKU.Name'], 'Code': 'BadRequest', 'Message': 'The parameter SKU.Name has an invalid value.'}}], 'Code': 'BadRequest', 'Target': None, 'Innererror': None, 'Message': 'The parameter SKU.Name has an invalid value.'}, 'error': None}
2018-11-15 07:58:20,970: custodian.actions:ERROR Execution failed with error: Operation returned an invalid status code 'Bad Request'
```
When I checkout the resources.json file it looks like the sku name shows up as B1: 
```
 },
 "properties": {
"status": "Ready",
"maximumNumberOfWorkers": 3,
 "numberOfSites": 0,
"resourceGroup": "cloud-custodian"
 },
"sku": {
 "name": "B1",
"tier": "Basic",
 "size": "B1",
"family": "B",
"capacity": 1
},
"resourceGroup": "cloud-custodian",
"c7n:MatchedFilters": [
"tag:scaledown"
```
