### ISSUE TITLE
Missing required parameter in input: "Enable" when using c7n-guardian

### ISSUE THREAD

**Issue by eamonnfaherty** [cloud-custodian/cloud-custodian#3209]
I am running the command:

```c7n-guardian enable --config guard-duty-accounts.yaml --master <account1_id>```

with the following config:

```
accounts:
 - name: account1_name
 email: xxxx1@yyy.com
 account_id: "accountid1"
 role: "arn:aws:iam::accountid1:role/CustodianGuardDuty"
 - name: account2_name
 email: xxxx2@yyy.com
 account_id: "accountid2"
 role: "arn:aws:iam::accountid2:role/CustodianGuardDuty"
```

I am using the following versions:
    "C7NVersion": "0.8.32.1",
    "C7NOrgVersion": "0.5.0",
    "C7NGuardianVersion": "0.3"
