### ISSUE TITLE
IAM Role action to attach a specified policy

### ISSUE THREAD

**Issue by matthew-sinn** [cloud-custodian/cloud-custodian#3212]
Hi c7n folks.

I have a feature enhancement request for the c7n.resources.iam.py file. I can contribute a pull request with the changes, but want to find out if you have any concerns or requirements that I should be aware of before I do.

We would like to create an action which can automatically attach a specified IAM policy to roles discovered using the NoSpecificIamRoleManagedPolicy filter.

The use-case for this new action is a desire to have a specific policy attached to all IAM roles in an AWS account for security purposes.

My intention is to design the action to accept a policy arn or policy name; if the name is provided the arn will automatically be discovered.

A c7n policy using this new action, called `attach-specific-policy` might be structured like this:

```
policies:
  - name: find-roles-without-policy-and-attach
    description: looks for existing IAM roles which do not have a required policy attached and attaches it
    resource: iam-role
    filters:
      - and:
        - type: no-specific-managed-policy
          value: my-iam-policy
    actions:
      - type: attach-specific-policy
        value: my-iam-policy
```

Thanks for your time.
