### ISSUE TITLE
ecs - related filter for services, tasks, container instances

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3218]
Add a related filter to filter on metadata on the cluster for services, tasks, etc.

```yaml
policies:
  - name: ecs-service-query-with-cluster-tags
    resource: ecs-service
    filters:
        - type: ecs-cluster
          key: tag:Application
          value: Application1
```
