### ISSUE TITLE
Request to add event shortcut for cloud trail event : CreateQueue

### ISSUE THREAD

**Issue by sri321** [cloud-custodian/cloud-custodian#3227]
- name: terminate-sqs
    resource: sqs
    mode:
      type: cloudtrail
      role: arn:aws:iam::acctnumber:role/account
      events:
        - CreateQueue
    filters:
      - type: cross-account
    actions:
      - type: delete
when we are trying to validate this policy we are getting the following error 

AssertionError: event shortcut not defined: CreateQueue

can this shortcut be added ?

**Comment by kapilt** [comment]
you can specify the full syntax for any api call, by using source/ids/event  here per the docs
https://cloudcustodian.io/docs/policy/lambda.html#cloudtrail-api-calls

**Comment by sri321** [comment]
Yeah , we tried and got an assertion error and the policy won’t run , we are running the latest version of custodian 
Resource SQS seems to be throwing a lot of other errors too 

We have 10 sqs queues in our account and when we try to list them using the policy below the output is zero ,  
 name: listsqs 
 Resource: sqs

**Comment by mason67git** [comment]
@sri321 I could never get this to work either... Did you manage it in the end?

**Comment by sri321** [comment]
@mason67git : nope

**Comment by kapilt** [comment]
seems like both of you are running into basic authoring issues, i'd suggest coming to the channel on gitter. wrt to the actual policy on sqs, i just ran through it all works as expected. closing this issue out as an answered question, example below.

```
policies:
  - name: sqs-checker
    resource: aws.sqs
    mode:
     type: cloudtrail
     events:
      - ids: responseElements.queueUrl
        source: sqs.amazonaws.com
        event: CreateQueue
```
