### ISSUE TITLE
CloudTrail events for SQS

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3228]
Hi,

I need the name of the cloudtrail event for newly created SQS queues.

Guessing there is already a command for this but I can't find it now the docs have changed recently...

I opened a similar issue for this (but for RDS) a while back but as previously mentioned the docs have changed. #2918

**Comment by kapilt** [comment]
generally the best way to do that is to just create a resource and then view the event name in the cloud trail console

**Comment by mason67git** [comment]
@kapilt I have tried this, the event is CreateQueue but this doesn't work... My policy is:

```
policies:
   - name: untagged-sqs-delete-on-create
     resource: sqs
     mode:
      type: cloudtrail
      events:
      - CreateQueue
      role: arn:aws:iam::219800341919:role/cloudcustodian_lambda_role
     filters:
      - "tag:Name": empty
      - "tag:Role": empty
      - "tag:Contact": empty
      - "tag:Project": empty
      - "tag:Team": empty
      - "tag:Owner": empty
      - "tag:Client": empty
      - "tag:Environment": empty
     actions:
       - delete
```

**Comment by mason67git** [comment]
@kapilt I have tried this, the event name is CreateQueue but this doesn't work... The code to my policy is:

```
policies:
   - name: untagged-sqs-delete-on-create
     resource: sqs
     mode:
      type: cloudtrail
      events:
      - CreateQueue
      role: arn:aws:iam::123456789123:role/cloudcustodian_lambda_role
     filters:
      - "tag:Name": empty
      - "tag:Role": empty
      - "tag:Contact": empty
      - "tag:Project": empty
      - "tag:Team": empty
      - "tag:Owner": empty
      - "tag:Client": empty
      - "tag:Environment": empty
     actions:
       - delete
```

**Comment by kapilt** [comment]
you'll need to specify the full event description with source/ids/event syntax see https://cloudcustodian.io/docs/policy/lambda.html#cloudtrail-api-calls

**Comment by kapilt** [comment]
as a complete tested example, you'll need to update the role name, also your policy would only fire if all of those are where empty, you'll need to wrap with `or:` block if you want it to delete if any of those conditions are true.

```yaml
policies:

  - name: queue-trigger
    resource: aws.sqs
    mode:
      type: cloudtrail
      role: arn:aws:iam::{account_id}:role/custodian-mu
      events:
        - event: CreateQueuedetail.requestParameters.queueName
          ids: requestParameters.queueName
          source: sqs.amazonaws.com
```
