### ISSUE TITLE
RDS DeletionProtection filter does not work in Lambda

### ISSUE THREAD

**Issue by steveparker-1984** [cloud-custodian/cloud-custodian#3239]
The following policy executed locally correctly identifies RDS instance with no Deletion Protection. However when I deploy it as a periodic lambda, it filters to 0 and detects nothing.

```yml

policies:
  - name: rds-instances-no-deletion-protection
    resource: rds
    description: Detect rds db instances with no deletion protection
    filters:
      - DeletionProtection: false

```

Custodian version is 0.8.32.1
