### ISSUE TITLE
kms-key cloudtrail notification not triggering

### ISSUE THREAD

**Issue by steveparker-1984** [cloud-custodian/cloud-custodian#3241]
I want to notify on changes to kms key policy changes. My policy is below, I've omitted the notify action. I don't really want any filters as such. Is my understanding off here? Lambda logs indicate I am extracting the key id correctly, but suggest it can't find resources:

Found resource ids: [u'someid']
Resources []

Running aws kms describe-key --key-id someid shows the key as expected.

```yml
policies:
  - name: kms-key-policy-changed
    resource: kms-key
    description: Report on changes to a key policy
    mode:
      type: cloudtrail
      events:
        - source: kms.amazonaws.com
          event: PutKeyPolicy
          ids: requestParameters.keyId
```
