### ISSUE TITLE
Lambda Cloudtrail issue

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3292]
Hi,

I am trying to create this rule: 

```
policies:
  - name: untagged-lambda-rule
    resource: lambda
    mode:
     type: cloudtrail
     role: arn:aws:iam::219800341919:role/cloudcustodian_lambda_role
     events:
       - source: lambda.amazonaws.com
         event: CreateFunction
         ids: "responseElements.instancesSet.items[].instanceId"
    filters:
     - "tag:Team": empty
    actions:
      - delete
```

However it simply does not work... I don't see what I'm doing wrong. (account number changed for security reasons)
