### ISSUE TITLE
Notify when no resources matched

### ISSUE THREAD

**Issue by steveparker-1984** [cloud-custodian/cloud-custodian#3319]
Is it possible to still trigger notification actions when no resources are matched? I can't see anything in the docs. It would be helpful in terms of how we're planning to visualise.

**Comment by kapilt** [comment]
it is possible, via using the `missing` filter on the account. normally we don't execute actions and filters on things that don't exist. to generically support the use cases around validating/asserting the existence of things, on the account resource we support the missing filter, which is effectively an embedded custodian policy, the missing filter matches if the embedded policy doesn't match any resources.

pseudo policy that uses that, ie notifies if an account region is missing an ec2 instance with a given tag.

```yaml
policies:
 - name: assert-ec2-instance
   resource: account
   filters:
    - type: missing
      policy:
        name: ec2-bluebox
        resource: ec2
        filters:
          - "tag:Usage": "ssh-bastion"
   actions:
    - type: notify
      ...
```
