### ISSUE TITLE
Azure - Bad Request when attempting to tag App Service Plan

### ISSUE THREAD

**Issue by joescars** [cloud-custodian/cloud-custodian#3327]
**Issue** 

When trying to run policy to tag app service plans, custodian fails with the following error:

```
Error: 400 Client Error: Bad Request for url: https://management.azure.com/subscriptions/[SUBSCRIPTION_ID]/resourceGroups/[RESOURCE_GROUP]/providers/Microsoft.Web/serverfarms/[RESOURCE_NAME]?api-version=2018-11-01
2019-01-09 13:18:48,598: custodian.azure.utils.TagHelper:ERROR Failed to update tags for the resource.
Type: Microsoft.Web/serverfarms.
Name: EastUSPlan.
```

**Steps to Reproduce**

Attempt to run the following policy against your subscription (note you must have active app service plans)

```yaml
policies:
    - name: tag-app-service-plan
      description: |
        Adds a tag to all app service plans
      resource: azure.appserviceplan
      actions:
       - type: tag
         tag: Hello
         value: World
```
**Root Cause**

The Azure API requires a 'sku' property in the payload which is not provided in the API call. This can be empty but it is still required

**Proposed Resolution**

it **tools/c7n_azure/tags.py** change this 

https://github.com/cloud-custodian/cloud-custodian/blob/29225dd4740c98c7480f71025f49c67e11ec252b/tools/c7n_azure/c7n_azure/tags.py#L48-L53

to this:

```python
            generic_resource = GenericResource(location=az_resource.location,
                                               tags=tags,
                                               properties=az_resource.properties,
                                               kind=az_resource.kind,
                                               managed_by=az_resource.managed_by,
                                               identity=az_resource.identity,
                                               sku={})
```

I've tested locally and it works. It does not seem to affect any other type of call. 

Thoughts?

@aluong @logachev @luisalvesmartins @stefangordon
