### ISSUE TITLE
Azure Event Grid mode does not respect filters

### ISSUE THREAD

**Issue by omusavi** [cloud-custodian/cloud-custodian#3332]
When deploying cloud custodian policy to Azure functions with the `azure-event-grid` mode, filters do not get run when the policy gets executed.

1. Deploy policy:
```yaml
policies:
  - name: my-policy
    description: Tag all resources in a RG when they get created
    resource: azure.resourcegroup
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.Resources/subscriptions/resourceGroups',
          event: 'write'
        }
      ]
    filters:
      - tag:myfilter: present
    actions:
      - type: auto-tag-user
        tag: CreatorEmail
```
2. `az group create -l westus2 -n custodian-test`

Expected:
Since `myfilter` tag is not present when creating `custodian-test` resource group, the policy actions should not run, and CreatorEmail should not be added as a tag on the resource

Actual:
CreatorEmail is added as a tag on the resource
