### ISSUE TITLE
aws - elasticache support t2 snapshots

### ISSUE THREAD

**Issue by umitseremet** [cloud-custodian/cloud-custodian#3334]
Hi,

When I want to create a snapshot for **t-type** Redis via c7n it can not be created while other types (r and m) can be created. Is there a special reason for that? Because I can create a manual snapshot for all type of Redises but C7N can trigger snapshot just for "r" and "m" type Redises.

In the documentation(https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/backups.html#backups-constraints) it says:

> For Redis (cluster mode disabled) clusters, backup and restore are not supported on cache.t1.micro nodes. All other cache node types are supported.

But there is not a negative definition for t2 types and I test t2 type;

**_Test Redises are totally identical except their types (t vs m)_**
```
1- redis-test-t-type -----> cache.t2.micro --------> can NOT be triggered via c7n
2- redis-test-m-type----> cache.m3.medium ----> can be triggered via c7n
```

**_Result is snapshots just for m-type one but not for t-type one, although I have tested it for several times:_**
```
backup-c7n-redistest-m-type-001-2019-01-10-09-31 | c7n-redistest-m-type-001 | manual | available | 4 MB |  
backup-c7n-redistest-m-type-002-2019-01-10-09-31 | c7n-redistest-m-type-002 | manual | available | 4 MB |  
backup-c7n-redistest-m-type-003-2019-01-10-09-31 | c7n-redistest-m-type-003 | manual | available | 4 MB |
```

**_Policy and Local-Run logs are below for my test Redises:_**

# policy
```
policies:
  - name: elasticache-cluster-snapshot
    resource: cache-cluster
    filters:
      - type: value
        key: CacheClusterStatus
        op: not-in
        value: ["deleted","deleting","creating"]
    actions:
      - snapshot
```

#custodian-run.log
```
2019-01-10 09:31:34,131 - custodian.policy - INFO - policy: elasticache-cluster-snapshot resource:cache-cluster region:us-east-1 count:6 time:2.40
2019-01-10 09:31:36,948 - custodian.policy - INFO - policy: elasticache-cluster-snapshot action: snapshotelasticachecluster resources: 6 execution_time: 2.80
```

*update*: omit json resource files
