### ISSUE TITLE
c7n mailer can't find queue/permissions

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3335]
Hi, 

So the custodian rule I want to use is:

```
policies:
  - name: untagged-s3-mailer-test
    resource: s3
    mode:
      type: cloudtrail
      events:
      - CreateBucket
      role: arn:aws:iam::123456789101:role/cloudcustodian_lambda_role
    filters:
     - "tag:Team": empty
     - "tag:Owner": empty
     - "tag:Client": empty
     - "tag:Environment": empty
    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: testing the c7n mailer
        to:
          - mason.*******@*****.co.uk
        transport:
          type: sqs
          queue: https://sqs.eu-west-1.amazonaws.com/12345678910/Mailing_queue_test
```

**On it's own, the rule works and puts an email into the SQS queue.**

The 'mailer.yml' I am using is:

```
queue_url: https://sqs.eu-west-1.amazonaws.com/12345678910/Mailing_queue_test
role: arn:aws:iam::12345678910:role/CloudTeam
from_address: mason.******@*****.co.uk
```

Yet when I run this I get:

"botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the ReceiveMessage operation: The specified queue does not exist or you do not have access to it."

When running the policy & mailer together I get "Cross-account pass role is not allowed"...

I understand this is a permissions issue, yet the SQS queue has SQS:* and the role I am using has full administrator access...
