### ISSUE TITLE
Reference parameters support

### ISSUE THREAD

**Issue by Shelvey-Kansal** [cloud-custodian/cloud-custodian#3345]
Hey,

@thisisshi @kapilt 
I have prepared a policy for marking an EC2 instance for termination but the requirement is that the power should be in user's hand to define the days after which termination should take place i.e the user can extend or reduce the number of days after which he can set the termination to happen.
Below is the code I wrote:
```yaml
policies:
 - name: mark-stopped-ec2-terminate
   resource: ec2
   description: Mark the stopped instance for termination
   filters:
        - "tag:instance_status": absent
        - "tag:exclude_server": absent
        - "State.Name": stopped
   actions:
        - type: mark-for-op
          tag: instance_status
          op: terminate
          days: 60      //This should be in variable form
```
Is there any way to achieve this?

**Comment by kapilt** [comment]
thats a bit nebulous wrt to use case, the user could just modify the tag (can use skew or other parameters on marked-for-op to detect ranges out of scope), what does variable form mean that satisfies that intent here.

**Comment by thisisshi** [comment]
@Shelvey-Kansal are you referring to an ability to use a resource attribute to define the number of days to terminate?

in terms of the suggestion given by kapil, the user should still have access to modify the tags on the resource itself-- that should be sufficient to give the user the ability to move the termination date to a later date.

**Comment by Shelvey-Kansal** [comment]
@kapilt @thisisshi  I understand the point. I was just looking for an option where I don't need to modify the script. If we can paas that as a variable or Reference. I don't want to hardcode the value, it should be variable so that we can change that using console or any other interface.
I have prepared the interface on EC2  for the extension period where the user can extend the number of days for the policy to terminate the instance (if he wants to). 
But the problem is the hardcoding of the number of days in the script.
If you can tell me the path to achieve this, it would be very helpful

**Comment by Shelvey-Kansal** [comment]
Or, Please let me know if there is a way by which I can pass value of one tag to another tag.
Say, I have a tag "instance_status" as mentioned in above comments which takes value in form of op@action_date. What I want now is to add another tag ex: extend_period. So the user has set the value of extend_period to 15 (suppose). Then I want that the instance_status tag should get updated by 15 days. If earlier its value was 2019/01/20 then after addition of extend_period it should get modify to 2019/02/04 (yyyy/mm/dd)

**Comment by Shelvey-Kansal** [comment]
@thisisshi @kapilt Something like this?
policies:
 - name: mark-stopped-ec2-terminate
   resource: ec2
   description: Mark the stopped instance for backup and termination
   filters:
        - "tag:instance_status": absent
        - "tag:exclude_server": absent
        - "State.Name": stopped
   actions:
        - type: tag
          tags:
             extend: 10
             othertags: value
        - type: mark-for-op
          tag: instance_status
          op: terminate
          days: "{extend:+20d}"

**Comment by Shelvey-Kansal** [comment]
@thisisshi @kapilt Is this possible or not?

**Comment by thisisshi** [comment]
@Shelvey-Kansal no, but you could achieve a similar effect with a policy like so before you do your deletion, basically check if an extend-20 tag is on the resource and if so remove the previous mark for op tag and re-mark it:

```yaml
policies:
  - name: extend-marked-for-op
     resource: ec2
     filters:
      - type: marked-for-op
        tag: instance_status
        op: terminate
      - "tag:extend-20": present
    actions:
      - type: mark-for-op
        tag: instance_status
        op: terminate
        days: 20
```
