### ISSUE TITLE
aws.DynamoDB  sleep function is needed for auto-tagging

### ISSUE THREAD

**Issue by umitseremet** [cloud-custodian/cloud-custodian#3361]
As it can be seen from the details, Lamda function which is created by the custodian is trying to "describe" the table/resource which has been just created, but can't do it, because the table is in "creation state". It can be observed in CloudTrail logs events for the Lambda function.
Currently, it seems that custodian is not checking the state of the table before doing the "Describe" step. A workaround will be to set a small sleep in custodian lambda function before it does the "Describe" step. "Describe" step is required to get the list of existing tags within the table and after that, it applies new tags.

Here is the result of aws-cli list table;

```
(custodian)# aws dynamodb  list-tables
{
    "TableNames": [
        "owner-tag-test"
    ]
}
(custodian) #
```

I can also list manual added tags of this tables like below;

```
(custodian)# aws dynamodb list-tags-of-resource --resource-arn arn:aws:dynamodb:eu-west-1:XXXXXXXXXXXX:table/owner-tag-test --output text
TAGS	Manual-Tag	Test
(custodian)#
```

But when I check the cloud-watch logs of my lambda functions, here are the logs ;

```
[WARNING]	2019-01-02T08:37:51.976Z	afd705b5-0e69-11e9-b02d-bfde41ffa0ce	Exception getting DynamoDB tags 
An error occurred (ResourceNotFoundException) when calling the ListTagsOfResource operation: Requested resource not found: ResourcArn: arn:aws:dynamodb:eu-west-1:XXXXXXXXXXXX:table/owner-tag-test not found
```

As a result,   **a sleep function** will be an easy work around solution for that case. So I wonder, Is there a way to put a sleep command to manipulate it like 5 seconds in Lambda function via yml or is it possible to put this sleep inside of related function as a native part?

**Comment by kapilt** [comment]
Thanks for the detailed bug report, a few followups for more information/context would be helpful re determining best solution. What does the policy look like and what's it trying to do?, also what's creating the Dynamodb table in question, and what version of custodian?

Dynamodb is a create table, then tag via multiple api calls type of resource. So tag enforcement will always be racy if trying to do so on cloud trail, and this also depends somewhat on the software doing the create, ie. CloudFormation might wait ~ 30s while before tagging the table. If your using aws config, then doing a custodian config rule will probably handle this better.

A yaml sleep in this context wouldn't help, as its pre execution of the filters/actions, that we grab tags. in general sleeps in this context will be quite racy.

**Comment by umitseremet** [comment]
Thanks for your message, 

Things you have wanted are like below.

It seems maybe a temporary workaround "function embedded sleep function" will help us if it can not be done yaml as you have mentioned.

**Purpose** is;

`When somebody creates a table, a owner tag must be put automatically by the help of Cloud-Trial. (I am currently using EC2 version, and it works perfect)`


**version** is;

```
(custodian)# custodian version
0.8.33.1
```


**Table create style** is

`not via CloudFormation, as manual via aws web console`



**Policy** is like that

```
policies:
- name: auto-tag-dynamodb-table
  description: |
     Autotags any newly created rds instances
  resource: dynamodb-table
  mode:
     type: cloudtrail
     role: arn:aws:iam::{account_id}:role/administrator
     events:
       - CreateTable
  filters:
     - "owner": absent
  actions:
     - type: auto-tag-user
       tag: creator-name
       principal_id_tag: creator-id
```
