### ISSUE TITLE
aws - s3 block public object ACLs erroring out

### ISSUE THREAD

**Issue by viswa-a** [cloud-custodian/cloud-custodian#3362]
After deploying [Block Public S3 Objects ACLs](https://cloudcustodian.io/docs/usecases/s3denypublicobjectacls.html) successfully and confirming that a lambda function named "custodian-s3-deny-public-object-acl" was created, I'm getting the below error in CloudWatch logs. The bucket itself is also still publicly accessible.
 

> [ERROR]	2019-01-14T18:46:57.643Z	67ff7b4d-f27b-43ac-b899-09ccdab191c2	Error while executing policy
> Traceback (most recent call last):
> File "/var/task/c7n/policy.py", line 273, in run
> results = a.process(resources)
> File "/var/task/c7n/resources/s3.py", line 725, in process
> results += filter(None, [f.result()])
> File "/var/runtime/concurrent/futures/_base.py", line 455, in result
> return self.__get_result()
> File "/var/runtime/concurrent/futures/thread.py", line 63, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/var/task/c7n/resources/s3.py", line 1084, in process_bucket
> current = {s['Sid']: s for s in policy.get('Statement', [])}
> File "/var/task/c7n/resources/s3.py", line 1084, in <dictcomp>
> current = {s['Sid']: s for s in policy.get('Statement', [])}
> KeyError: u'Sid'

Here is the policy that was deployed:
```
policies:
  - name: s3-deny-public-object-acl
    comment: Identifies S3 buckets and ensures that they have a restriction in them to not allow objects to be written with public access
    resource: s3
    description: |
      Appends a bucket policy statement to all existing s3 buckets to
      deny anyone from setting s3 objects in the bucket to public-read,
      public-read-write, or any authenticated AWS user.
    actions:
      - type: set-statements
        statements:
           - Sid: "DenyS3PublicObjectACL"
             Effect: "Deny"
             Action: "s3:PutObjectAcl"
             Principal: "*"
             Resource:
                - "arn:aws:s3:::{bucket_name}/*"
                - "arn:aws:s3:::{bucket_name}"
             Condition:
               StringEqualsIgnoreCaseIfExists:
                  's3:x-amz-acl':
                      - "public-read"
                      - "public-read-write"
                      - "authenticated-read"
```
