### ISSUE TITLE
CloudTrail Governing Rule

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3364]
Hi,

I am trying to make a CloudTrail governing rule, that watches over Cloudtrail trails in an account and notify's us when something is wrong. Unfortunately, there is nothing in the docs for this...

I want my rule to check if the logs made by the trail are encrypted by KMS & check if the trails are still on.

My rule currently looks like:

```
policies:
  - name: PCI-cloudtrail_encryption_rule
    resource: cloudtrail
    mode:
     type: periodic
     schedule: "cron(00 21 ? * MON-FRI *)"
     role: arn:aws:iam::12345678910:role/cloudcustodian_lambda_role
    filters:
      - "SSEDescription.SSEType": KMS
      - status: on
    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: testing the c7n mailer
        to:
          - mason.*********@*****.co.uk
        transport:
          type: sns
          region: eu-west-1
          topic: cc-test-topic
```

The only bits that don't work are the filters, I can't find out how to check if logs made are using KMS and a filter to check the status of the trail.

EDIT:
I am aware that my 'status' filter isn't going to work... But I can't find out what is applicable for what I want it to do.
