### ISSUE TITLE
aws.docdb - add new resource 

### ISSUE THREAD

**Issue by getglad** [cloud-custodian/cloud-custodian#3367]
DocumentDB has an overlapping control plane API with RDS, but is fronted with own namespace (`docdb` vs `rds`). It does, however, emit as an `rds` resource from CloudTrail.

Proposing attempt to bolt `docdb` resource to existing `rds` actions, see what comes out. Will have a WIP shortly (probably).

**Comment by getglad** [comment]
So it does have its own API set:
- boto3: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/docdb.html
- cli: https://docs.aws.amazon.com/cli/latest/reference/docdb/index.html#cli-aws-docdb

But if you compare RDS to DocDB actions, they are extremely similar both in name and structure:
- DocDB: https://docs.aws.amazon.com/documentdb/latest/developerguide/API_Operations.html
- RDS: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_Operations.html

Weirdly, it does emit from `rds` so `CloudTrail` policies will work...
```
resource: rds-cluster
mode:
      type: cloudtrail
filters:
      - type: value
        key: Engine
        value: 'docdb'
        op: eq
```

... but I don't believe that will work for periodic bc `rds` doesn't return `docdb` resources.
