### ISSUE TITLE
aws.support-case resource returns zero resources even with empty filter

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3371]
The aws.support-case resource is returning zero results, both for a policy with nothing in the filter section as well as when filter is just 
```
   filters:
      - type: value
        key: "status"
        value: not-null
```
noticed the c7n/resources/support.py code is very minimal and there is no unit test
