### ISSUE TITLE
aws.vpn-gateway.filters.unused 

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#3424]
Add an "unused" filter to vpn-gateway which looks for if the vpn-gateway id is listed as a target in any route table

Use Case: See #3423

**Comment by anovis** [comment]
this policy should work without the need for a new filter.

```
policies:
  - name: vpn-gateway-unused
    resource: vpn-gateway
    filters:
      - or:
        - type: value
          key: "VpcAttachments[?State=='attached']"
          value: 'not-null'
```
