### ISSUE TITLE
lambda function failing for resource: security-group

### ISSUE THREAD

**Issue by praveenk0535** [cloud-custodian/cloud-custodian#3474]
Seeing the below error in for the lambda function
File "/var/task/c7n/handler.py", line 83, in dispatch_event
if 'assume_role' in options_overrides:
TypeError: argument of type 'NoneType' is not iterable

Policy trying to execute
```
  - name: high-risk-security-groups-remediate
    resource: security-group
    mode:
        type: periodic
        schedule: "cron(*/5 * * * ? *)"
    resource: security-group
    filters:
      - type: ingress
        Cidr:
            value: "0.0.0.0/0"
    actions:
        - type: remove-permissions
          ingress: matched
```

Version using 
custodian version --- 0.8.33.1
