### ISSUE TITLE
Delete for c7n_mailer lambda function?

### ISSUE THREAD

**Issue by cbarensfeld** [cloud-custodian/cloud-custodian#3482]
Will there be functionality added to delete the c7n-mailer lambda function? I'm trying to decide if I should execute the c7n-mailer command in my terraform or just provision the lambda function with Terraform itself.

Thanks kapilt!

**Comment by kapilt** [comment]
there isn't any delete functionality directly supported by mailer cli, and. the mugc script won't pick it up, at the moment its a manual delete, but is there common cause for needing to delete mailer? if so we can address within the mailer cli. its typically been a deploy and update scenario that I've seen.

**Comment by cbarensfeld** [comment]
The only thing we would really use it for is cleanup after testing new conifgurations in dev, or migrating to a new aws account. Not a big use case for us, we were just curious if the tool had it. Thanks!

**Comment by niuscloud2** [comment]
@cbarensfeld 

There's a way to delete the c7n-mailer lambda via the mugc script:
 Save the following code into a file as a fake policy:  "**fake.policy**"

```
  policies:
  - name: delete-c7n-mailer-lambda
    resource: lambda
    filters:
      - "tag:delete_c7n_mailer_lambda": "do_nothing"
      - type: reduce
        limit: 0
          
    actions:
      - type: notify
        priority_header: '2'
        subject: "delete c7n-mailer lambda"
        to:
          - abcd@abc.com
        transport:
          type: sqs
          region: fake_region
          queue: https://fake_queue.sqs.us-east-1.amazonaws.com
```

then can use the mugc script to delete the mailer lambda, for example:
```
 python cloud-custodian/tools/ops/mugc.py \
                -r "${region_name}" \
                --prefix  <replace_with_c7n_mailer_lambda_name>  \
                 "fake.policy"
```
