### ISSUE TITLE
tools/mailer - slack delivery and datadog delivery should respect owner_absent_contact

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3521]

**Comment by kapilt** [comment]
honestly datadog delivery was a bit of a hack from the start, it should probably only be allowed in `to:`

**Comment by thisisshi** [comment]
So looking at the slack address resolution a bit more, unfortunately to support slack channel delivery and all the various options we have for slack address designation (slack://owners, slack://#channel, hooks.slack.com..., etc.) it's gonna require a more substantial rewrite of part of email_delivery... which is not something I want to modify just to support this.

For the time being we can make the change to support email address -> slack user resolution in the owner absent contact field, e.g.

```yaml
policies:
  - name: ec2
    resource: ec2
    actions:
      - type: notify
        to: ['slack://owners']
        owner_absent_contact: ['foo@bar.com']
...
```
That _should_ be able to be picked up by the existing logic inside of get_email_to_addrs_to_resources_map function, and slack_delivery should be able to resolve the resulting owner_absent_contact to a slack user (given that it's a valid email of course), i think this would be better implemented after a rewrite on mailer (which i have in progress to some extent)
