### ISSUE TITLE
c7n-org: define values that are inherited by policies

### ISSUE THREAD

**Issue by jofwar** [cloud-custodian/cloud-custodian#3553]
Our accounts are used by different teams therefore are associated with separate project codes, charge codes etc..

It would be extremely useful if we were able to define these in the c7n-org account configuration file and then inherited by the policies.

Here is an example concept:

**c7n-org configuration**
```yaml
accounts:
- account_id: '123123123123'
  name: account-1
  regions:
  - us-east-1
  - us-west-2
  role: arn:aws:iam::123123123123:role/CloudCustodian
  tags:
  - type:prod
  inherit:
  - project_code:W0023424
```

**policy example**
```yaml
policies:
- name: ec2-auto-tag-project-code
  resource: ec2
  description: |
    Tag any new instance with project code
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/role
    events:
      - RunInstances
  filters:
    - tag:projectCode: {project_code}
  actions:
    - type: tag
      key: projectCode
      value: {project_code}
```
