### ISSUE TITLE
How to place current time in a tag?

### ISSUE THREAD

**Issue by k7faq** [cloud-custodian/cloud-custodian#3561]
As Custodian does not offer a filter to determine how long an RDS instance has been alive (which I need for a special use case) and it is not something that would be needed on a recurring basis ... I am needing to figure out how to insert a time stamp as a value in a tag.

Is there an existing feature that I have not found documentation on how to use? Or is there an ability to execute an external command? e.g. `(bash) date "+%Y%m%d"`

an example code block would be:

```
policies:
  - name: Example Tag Policy
    resource: aws.rds
    filters:
      - tag:Name MyCustomValue
    actions:
      - type: tag
        key: CreationTime
        value: (bash) date "+%Y%m%d"
```
NOTE: This command could be a python command in place of a bash command. Regardless the result would be to return a date/time string.
