### ISSUE TITLE
Custodian lambda example created config rule but not the tag

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3566]
Hi. I followed the example to create the custodian lambda from the following yaml file

```yaml
policies:
  - name: my-first-policy
    mode:
        type: config-rule
        role: <myarn>
    resource: ec2
    filters:
      - "tag:Custodian": present
    actions:
      - stop
```

which created my lambda and my config rule

```bash
$ aws configservice describe-config-rules --config-rule-names custodian-my-first-policy
{
    "ConfigRules": [
        {
            "ConfigRuleName": "custodian-my-first-policy",
            "ConfigRuleArn": "arn:aws:config:us-east-1:redacted:config-rule/config-rule-z6f75r",
            "ConfigRuleId": "config-rule-z6f75r",
            "Description": "cloud-custodian lambda policy",
            "Scope": {
                "ComplianceResourceTypes": [
                    "AWS::EC2::Instance"
                ]
            },
            "Source": {
                "Owner": "CUSTOM_LAMBDA",
                "SourceIdentifier": "arn:aws:lambda:us-east-1:redacted::function:custodian-my-first-policy",
                "SourceDetails": [
                    {
                        "EventSource": "aws.config",
                        "MessageType": "ConfigurationItemChangeNotification"
                    },
                    {
                        "EventSource": "aws.config",
                        "MessageType": "OversizedConfigurationItemChangeNotification"
                    }
                ]
            },
            "ConfigRuleState": "ACTIVE"
        }
    ]
}
```

when I went to my config rule, there weren't any tags there. I'm assuming that `Custodian` tag should have been in the config rule otherwise how would it know to trigger the lambda?
