### ISSUE TITLE
Policies to identify deleted resources from CloudTrail should work

### ISSUE THREAD

**Issue by i-n00b** [cloud-custodian/cloud-custodian#3580]
Policies that trigger if certain resources are deleted from an AWS account (such as IAM roles, S3 buckets, DynamoDB tables etc) do not work as expected.

Example policy:
```
  - name: s3-bucket-deleted
    resource: s3
    description: |
        Alerts on every deletion of an S3 bucket
    mode:
      type: cloudtrail
      role: arn:aws:iam::{account_id}:role/custodian-lambda-role
      events:
        - source: s3.amazonaws.com
          event: DeleteBucket
          ids: "requestParameters.bucketName"
    actions:
      - type: notify
        template: default_template.html
        priority_header: 1
        subject: "[Custodian Alert][{{ account }}][{{ region }}] S3 bucket deleted"
        violation_desc: "S3 bucket deleted:"
        action_desc: |
            Please investigate if needed.
        to:
          - email-id@test.com
        transport:
          type: sqs
          queue: https://sqs.us-west-2.amazonaws.com/{account_id}/custodian-email
```

**Expected behavior:**
The policies should be triggered, and an e-mail notification should be sent with the message that an S3 bucket has been deleted. 

**Observed behavior:**
The s3-bucket-deleted lambda is triggered, but never forwards the notify message to the custodian mailer lambda. 

It seems once the policy is triggered, the lambda tries to get more information about the resource in the function _resolve_resources()_ in the file **policy.py**. Because the resource is already deleted, it is not able to fetch any information about the resource and gets an empty result back. From the function _run()_ in **policy.py**, the function then returns without carrying out the intended action which is to notify the user that the resource has been deleted. Also, no error is generated in the logs.
