### ISSUE TITLE
c7n_logexporter error

### ISSUE THREAD

**Issue by Shelvey-Kansal** [cloud-custodian/cloud-custodian#3623]
I am trying to use c7n_logexporter tool to send cloudwatch logs to S3. I have configured everything as stated in documentation. But I am still getting the error:
 INFO:c7n-log-exporter:config file valid, accounts:1
ERROR:c7n-log-exporter:Error on account shelvey err: get_session() takes at least 2 arguments (1 given)

This is my config.yml file:
```yaml
destination:
   bucket: poccloudcustodian
   prefix: new

accounts:
  - name: shelvey
    role:
       "arn:aws:iam::123456789:role/poc"
    groups:
      - "/aws/lambda/custodian-mark-stopped-ec2-terminate"
      - "/aws/lambda/cloud-custodian-mailer"
```
I am not able to understand, why I am getting this error.
