### ISSUE TITLE
Guard-duty filter is not returning master information

### ISSUE THREAD

**Issue by ryanash999** [cloud-custodian/cloud-custodian#3628]
Version = 0.8.42.0
Issue = When using the following guardduty filter it for a member account it is not returning the master account information.  

```
    filters:
      - type: guard-duty
        Detector.Status: ENABLED
        Master.AccountId: "xxx"
        Master.RelationshipStatus: "Enabled"
```
Example resource.json which should show master information
```
  {
    "c7n:guard-duty": {
      "Detector": {
        "Status": "ENABLED",
        "ServiceRole": "arn:aws:iam::xxx:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty",
        "UpdatedAt": "2018-11-02T10:16:15.132Z",
        "FindingPublishingFrequency": "SIX_HOURS",
        "CreatedAt": "2018-11-02T10:16:15.132Z"
      },
      "Master": null
    },
    "account_id": "xxx",
    "account_name": "xxx"
  }
]
```
Using AWS CLI and the ```get-master-account``` I can see ```Master``` information for this account
```
{
    "Master": {
        "InvitationId": "xxxx", 
        "InvitedAt": "2018-11-02T10:16:21.134Z", 
        "RelationshipStatus": "Enabled", 
        "AccountId": "xxx"
    }
}
```
