### ISSUE TITLE
AWS S3 - Feature Request - Reduce Non-Essential API Calls

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#3633]
Jamison Roberts @jtroberts83 12:02
@kapilt Would there be a way to limit what api calls are being made when running an s3 policy? The reason I ask is because we have a few S3 lambda based policies that run on a periodic basis, some as frequently as every 5 minutes for compliance, and even if the policy filters are only checking bucket encryption for example, the policy still queries all the other properties such as lifecycle, versioning, logging, bucket acl etc. This is generating hundreds of thousands of useless api calls and some of our customers are "not happy" about all the Cloud Custodian S3 api clutter in CloudTrail that they have to sift through. Would it be possible for custodian to only make the needed api calls for the filters provided? I know the odds are pretty slim but thought I would ask

Kapil Thangavelu @kapilt 12:16
It’s possible, file an issue with the use case, it would be additional config for the s3 resource policies, but yeah that could be done

My use case for this would be for an S3 policy which enables default bucket encryption for newly created buckets.  Per our compliance regulations we have to have all S3 buckets encrypted ASAP after being created as files could start getting uploaded to new buckets within seconds or minutes after creation.  We do have a policy that triggers on CreateBucket cloudtrail api and configures several aspects of of the new buckets but we can't apply encryption at the CreateBucket event because several customers had an issue with the policy as they were trying to apply their own custom KMS key encryption which would get overwritten by the S3 Cloud Custodian policy.  Being that the CreateBucket event doesn't show if encryption is being enabled by the customer I can't use those events to determine if the customer is applying encryption.  Currently I have the CreateBucket triggered policy tag the new buckets for a followup policy to check encryption which runs every 5 minutes and then the followup periodic policy will check the encryption and if still missing it will apply the default encryption.  While this works as a solution, it is generating so many useless api calls as it queries every aspect of every bucket every 5 minutes and generating so many CloudTrail events.  Limiting these to what the filters need or the users specifies would be nice.  Here is the policy set for our usecase:

```

- name: s3-enable-standards-realtime
  resource: s3
  description: | 
    New S3 buckets get tagged with creators ID, enables versioning,
    enables logging, and it applies a deny public objects bucket policy.
  mode:
    type: cloudtrail
    events:
      - CreateBucket
    role: arn:aws:iam::{account_id}:role/Cloud_Custodian_Role
    timeout: 300
  filters:
    - type: event
      key: "region"
      op: in
      value:
          - us-east-1
          - eu-west-1
  actions:
    - type: auto-tag-user
      tag: CreatorName
    - type: toggle-versioning
      enabled: true
    - type: toggle-logging
      target_bucket: "{account_id}-{region}-s3-logs"
      target_prefix: "{source_bucket_name}/"
    - type: set-statements
      statements:
        - Sid: "DenyS3PublicObjects"
          Effect: "Deny"
          Action: "s3:PutObjectAcl"
          NotPrincipal:
             "AWS":
                 - "arn:aws:iam::858827067514:root"
                 - "arn:aws:iam::193672423079:user/logs"
                 - "arn:aws:iam::210876761215:user/logs"
                 - "arn:aws:iam::127311923021:root"
                 - "arn:aws:iam::156460612806:root"
          Resource:
             - "arn:aws:s3:::{bucket_name}/*"
             - "arn:aws:s3:::{bucket_name}"
          Condition:
            StringEqualsIgnoreCaseIfExists:
               's3:x-amz-acl':
                   - "public-read"
                   - "public-read-write"
                   - "authenticated-read"
    - type: tag
      key: c7n_CheckEncryption
      value: "Status"
    - type: tag
      key: c7n_CheckLifeCycle
      value: "Status"


##Followup Policy Generating way too many api calls below

- name: s3-check-encryption-status-tag-disabled
  resource: s3
  description: |
     This is part of a policy chain which checks to see if the bucket
     has encryption enabled and if not it enables AES-256 default key.
  mode:
      type: periodic
      schedule: "rate(5 minutes)"
      role: arn:aws:iam::{account_id}:role/Cloud_Custodian_Role
      timeout: 300
  filters:
    - "tag:c7n_CheckEncryption": present
    - not:
        - type: bucket-encryption
  actions:
    - type: set-bucket-encryption
    - type: unmark
      tags: ['c7n_CheckEncryption']

- name: s3-check-encryption-status-tag-enabled
  resource: s3
  description: |
     This is part of a policy chain which checks to see if the bucket
     has encryption enabled and if so it removed the check tag.
  mode:
      type: periodic
      schedule: "rate(30 minutes)"
      role: arn:aws:iam::{account_id}:role/Cloud_Custodian_Role
      timeout: 300
  filters:
    - "tag:c7n_CheckEncryption": present
    - type: bucket-encryption
  actions:
    - type: unmark
      tags: ['c7n_CheckEncryption']

```
