### ISSUE TITLE
If {account_id} can be used for the role we should be able to omit most of the arn

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3657]
I'm proposing that instead of using this

```yaml
    role: arn:aws:iam::{account_id}:role/CloudCustodian
```

Since the `account_id` is interpolated, we could omit most of the arn and leave it as this

```yaml
    role: CloudCustodian
```

Put just the name in and the rest of the arn will be calculated based on the profile used to execute the policy.

**Comment by claque2000** [comment]
I love the idea so I do the modifications. 
Do not hesitate to tell me if something is missing

**Comment by claque2000** [comment]
Fixed via PR #3661. If it's OK for you @nitrocode, we can close this issue.

**Comment by nitrocode** [comment]
@claque2000 beautiful!

**Comment by nitrocode** [comment]
@claque2000 does this also apply to sqs urls?

For example, instead of

```yaml
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/1234567890/cloud-cloudcustodian
```

could we do

```yaml
        transport:
          type: sqs
          queue: cloud-cloudcustodian
```

If not, I can create a separate ticket.
