### ISSUE TITLE
aws.ebs - proposal of "stop-instance" action

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#3658]
In our usage (mainly tagging policy compliance actions) we have a need to stop EC2 instances attached to EBS volumes (the filters are on the EBS volumes).

Our use-case is something like (our real filter is more complex for the Tag Policy compliance part, but you get the idea. Also, there is notification, etc...):
```yaml
policies:
- name: ebs-tag-compliance-stop-instance
  resource: ebs
  filters:
    # => EBS older than 20 minutes
    - type: value
      key: CreateTime
      op: ge
      value_type: age
      value:
        minutes: 20
    # => EBS attached to running instances
    - type: instance
      key: State.Name
      op: in
      value: 
        - running
        - pending
    # => EBS attached to non-spot instances
    - or:
      - type: instance
        key: InstanceLifecycle
        value: absent
      - type: instance
        key: InstanceLifecycle
        op: not-equal
        value: "spot"
    # => EBS not properly tagged
    - or:
      - "tag:TagCompliance": absent
  actions:
    - stop-instance
```

To this end we've created the "stop-instance" EBS (volume) action that is shared in the attached Pull Request, for comments and feedback.
