### ISSUE TITLE
Request: policy can read json array of key values and run against it

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3662]
This came up because we have a script that reads a JSON file with the following auto scaling group information

```json
[
  {
    "name": "Company-Service-01",
    "desiredCount": 16,
    "minCount": 8,
    "maxCount": 20,
    "other-params": "other-vals"
  },
  {
    "name": "Company-Service-02",
    "desiredCount": 12,
    "minCount": 8,
    "maxCount": 20,
    "other-params": "other-vals"
  }
]
```

It would be nice to be able to read this JSON file using a jmespath and create a dynamic policy from it.

```yaml
policies:
  - name: asg-scale-profile-high-traffic
    description: Apply high traffic scaling profile to ASGs
    resource: asg
    values_from: s3://somebucket/someprefix.json (see json file above)
    filters:
      - type: "tag:Name"
        value: "jmespath([].Name)"
    actions:
      - type: resize
        desired-size: "jmespath([].desiredCount)"
      - type: min-size
        value: "jmespath([].minCount)"
      - type: max-size
        value: "jmespath([].maxCount)"
```

The above is shot from the hip so apologies if I didn't get the properties correctly.

The workaround until something like the above is implemented is to write a python script that generates a policy file from the json file. Not ideal but it can be done.
