### ISSUE TITLE
Stop Idle Ec2 instances

### ISSUE THREAD

**Issue by Shelvey-Kansal** [cloud-custodian/cloud-custodian#3663]
Hey,

I am trying to implement a policy to stop instances which are in ideal state in order to reduce or terminate them. Below is the policy I am implementing, it has no error while running but it is not able to execute what I want.

```yaml

 policies:
  - name: ec2-stop
    resource: ec2
    description: EC2 instances that are idle will be stopped.
    filters:
       - type: metrics
         name: CPUUtilization
         percent: 2
         op: lt
      - type: metrics
	 name: NetworkIn
	 value: 5
	 op: lt
      - type: metrics
	 name: NetworkOut
         value: 5
         op: lt
     actions:
       - type: mark-for-op
         tag: instance_status
         op: stop
         days: 7
```
