### ISSUE TITLE
Exclude instances in an ASG from rule

### ISSUE THREAD

**Issue by mason67git** [cloud-custodian/cloud-custodian#3686]
Hi,

So i have created this rule for ec2:

```
policies:
  - name: untagged-ec2-rule
    resource: ec2
    mode:
     type: cloudtrail
     role: arn:aws:iam::{account_id}:role/cdl/cloudteam/cloudcustodian-ec2-role
     events:
       - source: ec2.amazonaws.com
         event: StartInstances
         ids: "responseElements.instancesSet.items[].instanceId"
       - source: ec2.amazonaws.com
         event: RunInstances
         ids: "responseElements.instancesSet.items[].instanceId"
       - source: ec2.amazonaws.com
         event: RebootInstances
         ids: "responseElements.instancesSet.items[].instanceId"
     tags:
      Name: Untagged_EC2_Rule
      Role: CloudTeam
      Contact: CloudTeam
      Project: Custodian
      Owner: CloudTeam
      Team: CloudTeam
      Client: Client
    filters:
     - "tag:Role": empty
     - "tag:Contact": empty
     - "tag:Project": empty
     - "tag:Team": empty
     - "tag:Owner": empty
     - "tag:Client": empty
     - "tag:Environment": empty
    actions:
     - terminate

```
However this even terminates instances inside of an ASG, is there a way of filtering out instances inside of an asg? Maybe something similar to:

```
.
.
      Owner: CloudTeam
      Team: CloudTeam
      Client: Client
    filters:
     If: inside-asg
         - ignore
     - "tag:Role": empty
     - "tag:Contact": empty
     - "tag:Project": empty
     - "tag:Team": empty
     - "tag:Owner": empty
     - "tag:Client": empty
     - "tag:Environment": empty
    actions:
     - terminate
```
