### ISSUE TITLE
c7n: Filter for EC2 scheduled events

### ISSUE THREAD

**Issue by davidclin** [cloud-custodian/cloud-custodian#3689]
Is there a way to have Cloud Custodian send a notification when AWS creates a scheduled event for EC2 instances running on degraded hardware (or scheduled maintenance)? ([AWS details here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-instances-status-check_sched.html#viewing_scheduled_events))

We recently received email notices from AWS regarding instances running on degraded hardware and would like a way to have Cloud Custodian send email/Slack notifications when this happens along with the AWS account ID, instance ID's, and instance key names.
 
Example of instance running on degraded hardware:

```
$ aws ec2 describe-instance-status --instance-id i-1234567890abcdef0 --query "InstanceStatuses[].Events"

[
    "Events": [
        {
            "Code": "instance-stop",
            "Description": "The instance is running on degraded hardware",
            "NotBefore": "2015-05-23T00:00:00.000Z"
        }
    ]
]
```

**Comment by kapilt** [comment]
we use health events which over lap with this but cover a wider set of issues and support cloud watch event. See `$ aws health help` and `custodian schema ec2.filters.health-event`

**Comment by davidclin** [comment]
That's great news.

Are there any examples available of how to use the ec2.filters.health-event filter?

**Comment by davidclin** [comment]
Ok - I was able to figure it out.  Sorry for the newb question.  :)

Just for posterity and anyone who may stumble upon a similar situation, the following policy was able to retrieve all my upcoming EC2 statuses and exactly what I needed for retrieving all instances reported running on degraded hardware :

```
policies:
  - name: ec2-health-event
    resource: ec2
    description: |
      Cloud Custodian EC2 Health Event
    comments: |
      Retrieve EC2 Attributes
    filters:
      - type: health-event
        statuses: [upcoming]
```
