### ISSUE TITLE
Run simple tag compliance check on all supported resources?  List of supported resources

### ISSUE THREAD

**Issue by mirnujAtom** [cloud-custodian/cloud-custodian#3695]
Hey Guys.

I am trying to build a tag compliance check which should check everything possible for a couple of mandatory tags within our account. 
As far as I understood I cannot simply set a wildcard value of "*" or "all" for the "resource:" field which only accepts a single resource, right? 
So, if I want to count all the resources can I somewhere fin the list of supported, high-level, resource names?  
The list returned by 'custodian schema aws' looks a bit too overkill to me.

Thanks a lot!

**Comment by kapilt** [comment]
`custodian schema aws` is the list and count of all supported high level resource names. why is it over kill, its sounds like what your looking for.

**Comment by mirnujAtom** [comment]
Hey @kapilt 

Thanks a lot for the reply!
So, is there a way to loop over all of the schema items? What I need is to find all the resources which support tagging but do not have my mandatory tag, something like this

```
policies:
  - name: untagged-$schema_item
    resource: $schema_item
    filters:
      - or:
        - "tag:MyMandatoryTag" : absent
```
