### ISSUE TITLE
regex on asg tag

### ISSUE THREAD

**Issue by Mike-Landers** [cloud-custodian/cloud-custodian#3713]
```
policies:
  - name: asg-test
    resource: asg
    filters:
      - type: value
        key: tag:Name
        op: regex
        value: ^(egress*)
```

I'm trying to match autoscaling groups with a tag:Name starting with egress, but get 0 matches when they definitely exist. What's wrong here? I think the regex syntax is correct but I'm thinking the way the Name tag for an asg is specified may need to be different somehow.
