### ISSUE TITLE
EC2 Instance Resize yaml syntax

### ISSUE THREAD

**Issue by tzd-sh** [cloud-custodian/cloud-custodian#3714]
I am trying to write a policy to resize ec2 instances, but am not able to find sufficient example documentation on how to do it.

The only documentation I found was:

```
$ custodian schema ec2.actions.resize

Schema
------

properties:
  default:
    type: string
  restart:
    type: boolean
  type:
    enum:
    - resize
  type-map:
    type: object
required:
- type
```

I do not know how to construct a type-map of type:object

For example, I wrote the following policy to attempt to resize existing m4.xlarge instances which I have already tagged with Key:"ResizeTo, Value:"m5.xlarge", to the m5.xlarge size.  However it threw error when I ran it.

```
policies:
  - name: resize-to-m5-xlarge
    resource: ec2

    filters:
      - type: value
        key: "tag:ResizeTo"
        value: "m5.xlarge"

    actions:
      - type: resize
        type-map: "m5.xlarge"
        restart: true
```
        
Can you please provide some pointer on how the yaml should be written?

Thanks!
