### ISSUE TITLE
tag-count is broken for aws.ebs-snapshot

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3721]
when i run this policy, i receive an error

```
policies:
- name: remove-old-ebs-snapshots-2
  resource: ebs-snapshot
  filters:
    - type: tag-count
      value: 1
  actions:
    - delete
```

the error is

```
Exception: Failed to validate on policy remove-old-ebs-snapshots-2
 Additional properties are not allowed ('value' was unexpected)

Failed validating u'additionalProperties' in schema[6]:
```

i used what i saw coming from the custodian schema command
```
✗ custodian schema ebs-snapshot.filters.tag-count

Help
----

Simplify tag counting..

ie. these two blocks are equivalent

.. code-block :: yaml

   - filters:
       - type: value
         key: "[length(Tags)][0]"
         op: gte
         value: 8

   - filters:
       - type: tag-count
         value: 8
```
