### ISSUE TITLE
docs - validate sample policies in docstrings

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3738]
docstrings can get out of date or are just blatantly wrong sometimes, using string.format we can pass in policies into the docstrings while also systematically validating that they are correct through unit tests

example

```python
class TestClass(object):
    """
    A test doc

    {policy_1}

    {policy_2}
    """

    sample_policies = {
        'policy_1': """
          policies:
            - name: test
              resource: ec2
              actions:
                - type: stop
        """,
        'policy_2': """
          policies:
            - name: test-2
              resource: ec2
              actions:
                - type: stop
        """
    }

    @staticmethod
    def get_doc():
        print(TestClass.__doc__.format(**TestClass.sample_policies))

TestClass.get_doc()
```

output:
```

    A test doc


          policies:
            - name: test
              resource: ec2
              actions:
                - type: stop



          policies:
            - name: test-2
              resource: ec2
              actions:
                - type: stop

```

from there we can easily write a test to iterate over the sample policies and do a simple validate on them.

also, this could support shared actions/filters and generate docs for that resource, e.g.:

```
policies:
  - name: notify-{resource}
    resource: {resource}
    actions:
      - type: notify
...
```

would become:
```
policies:
  - name: notify-ec2
    resource: ec2
    actions:
      - type: notify
...
```
