### ISSUE TITLE
send to webhook notify/action support

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3770]
It would be nice if we could specify an action to use an HTTP method like GET or POST to hit an endpoint with hard-coded data, data coming from the triggered event, or send specific resource information that triggered to be sent, etc.

Use case: Every time an EC2 is created, I'd like to update a google spreadsheet. A google app script exposes an endpoint for the lambda to hit. CloudCustodian could then be used to generate a lambda that triggers when an EC2 is created and when its triggered, it uses metadata from the EC2 resource json to send to the google app script endpoint to update the spreadsheet.

**Comment by thisisshi** [comment]
Why not use the built in invoke-lambda action?

**Comment by nitrocode** [comment]
Yes but wouldn't you still have to generate or manually code the lambda? If not, could you show the policy?

I'm hoping we can create a policy file that does the following

* Define a trigger on some resource say ec2 creation
* Define an end point (if its GET put query args data in here too)
* Define an HTTP method
* Define data to be sent (if put / post)
* Code nothing

**Comment by kapilt** [comment]
there's a general notion of supporting a webhook which sounds good. Then there's a notion of allowing arbitrary configuration with no code, which i don't think its realistic, but i'm curious do you have some examples of what this might look like.

**Comment by nitrocode** [comment]
Yes, something like this

```yaml
policies:
  - name: send-resource-data-to-webhook
    resource: ebs
    filters:
      - type: value
        key: "Attachments[0].Device"
        value: not-null
        #Attachments: []
    actions:
      - type: webhook
        url: https://example.com/api/v1/send-data
        method: POST
        data: | 
{"key1": "value1", "key2": "value2", "key3", "{{ Attachments[0].Device }}"}
        paginate: 50
```

The above was written as an example of using the resources information within the POST data to be sent to the webhook. So when this runs it should scan all your ebs volumes, for every one thats attached, it should either 1) call the webhook for each one or 2) call the webhook only once with a large list of the above json data. Perhaps it could be paginated so for every 50 ebs volumes that match the above filter, it will hit the webhook until all the ebs volumes detected have had their json data sent.
