### ISSUE TITLE
Specify Maximum age of a resource in a tag

### ISSUE THREAD

**Issue by danieleb0101** [cloud-custodian/cloud-custodian#3776]
I need to write a policy where if the age of the resource is bigger than a value specified in a tag that resource is deleted, but I'm not sure how to do it for several reasons.
1. Can I achieve my goal with the policy below?
```yaml
policies:
  - name: delete-old-stacks
    resource: cfn
    filters:
      - "tag:Retention": present
      - or:
          - type: value
            key: LastUpdatedTime
            op: greater-than
            value_type: age
            value: tag:Retention
          - and:
              - type: value
                key: CreationTime
                op: greater-than
                value_type: age
                value: tag:Retention
              - type: value
                key: LastUpdatedTime
                value: absent

    actions:
      - type: delete
```

2. Sometimes it may happen that the value of the tag `Retention` is not a number and I would like that Cloud Custodian doesn't fail, ideally I would like that Cloud Custodian skips that resource without blowing up. How can I achieve it?

**Comment by thisisshi** [comment]
currently, no but I think we could extend the value_form syntax to support that, something like the following?

```yaml
policies:
  - name: delete-old-stacks
    resource: cfn
    filters:
      - type: value
        key: CreationTime
        value_from:
          url: self
          format: json
          expr: tag:Retention
        op: greater-than
```

iirc there have been other requests to support something like this before, where the value comparison is based on another value on the resource json

**Comment by danieleb0101** [comment]
Ok, so at the minute, if I would like to set the life length of a resource in a tag and let cloud custodian to delete it I cannot do that right?

**Comment by anovis** [comment]
what exactly is your use case. maybe you can use the `mark-for-op` action which creates a tag for future actions. so the first time the action is called it creates a tag for a specific `op` to happen in x future days.  

```
policies:
  - name: delete-old-stacks
    resource: cfn
       filters:
       -   type: value
            key: tag:Retention
            op: greater-than
            value_type: age
            value: 3
    actions:
      - type: mark-for-op
        tag: Retention-Delete
        op: delete
        days: 7
```
