### ISSUE TITLE
validation output improvements

### ISSUE THREAD

**Issue by acdha** [cloud-custodian/cloud-custodian#3777]
I was attempting to validate a large policy file (working around #3695) and found that the default validate output is unhelpful:

```
2019-04-09 10:36:05,815: custodian.commands:ERROR {'tag': 'Warning', 'type': 'mark', 'value': 'Untagged Instance'} is not valid under any of the given schemas

Failed validating u'anyOf' in schema[90][u'allOf'][1][u'properties'][u'actions'][u'items']:
    {u'anyOf': [{u'$ref': u'#/definitions/actions/put-metric'},
                {u'$ref': u'#/definitions/actions/notify'},
                {u'$ref': u'#/definitions/actions/post-finding'},
                {u'$ref': u'#/definitions/actions/invoke-lambda'},
                {u'enum': ['put-metric',
                           u'notify',
                           'post-finding',
                           'invoke-lambda']}]}

On instance[u'actions'][0]:
    {'tag': 'Warning', 'type': 'mark', 'value': 'Untagged Instance'}
```

This would be helpful if it gave something like the resource type, line number in the source file, etc. to help you identify what the problem is short of doing a binary search.

**Comment by kapilt** [comment]
@acdha ! long time.

yeah we do some customizations of the default jsonschema to try and make the output nicer than the default jsonschema  (which is sigificantly worse). generally it ends up going to the most specific dictionary, we can try walking up the policy instance though if we find ourselves on a leaf schema element.

do you have an example policy that triggered this message?

**Comment by acdha** [comment]
Yeah, it's been quite awhile…

Here's a simple test-case:

```yaml
policies:
    - name: tagging-compliance-ec2
      description: Identify resources which lack our accounting tags
      resource: aws.ec2
      filters:
          - 'tag:Environment': absent
          - 'tag:Service': absent
          - or:
                - 'tag:Owner': absent
                - 'tag:ResponsibleParty': absent
                - 'tag:Contact': absent
                - 'tag:Creator': absent
      actions:
          - type: tag
            key: TagPolicyCompliance
            value: This resource should have tags following policy
    - name: tagging-compliance-waf
      description: Identify resources which lack our accounting tags
      resource: aws.waf
      filters:
          - 'tag:Environment': absent
          - 'tag:Service': absent
          - or:
                - 'tag:Owner': absent
                - 'tag:ResponsibleParty': absent
                - 'tag:Contact': absent
                - 'tag:Creator': absent
      actions:
          - type: tag
            key: TagPolicyCompliance
            value: This resource should have tags following policy
```

```
2019-04-09 13:17:10,102: custodian.commands:ERROR Configuration invalid: test.yaml
2019-04-09 13:17:10,103: custodian.commands:ERROR {'type': 'tag', 'key': 'TagPolicyCompliance', 'value': 'This resource should have tags following policy'} is not valid under any of the given schemas

Failed validating u'anyOf' in schema[88][u'allOf'][1][u'properties'][u'actions'][u'items']:
    {u'anyOf': [{u'$ref': u'#/definitions/actions/put-metric'},
                {u'$ref': u'#/definitions/actions/notify'},
                {u'$ref': u'#/definitions/actions/post-finding'},
                {u'$ref': u'#/definitions/actions/invoke-lambda'},
                {u'enum': ['put-metric',
                           u'notify',
                           'post-finding',
                           'invoke-lambda']}]}

On instance[u'actions'][0]:
    {'key': 'TagPolicyCompliance',
     'type': 'tag',
     'value': 'This resource should have tags following policy'}
2019-04-09 13:17:10,103: custodian.commands:ERROR tagging-compliance
```

I should note that I originally found that list to be longer because I was using the `mark` action which seems to be common to most of the examples but far more resources support `tag`, so at first it looked like things like S3 didn't support tagging since I'd started with the list in https://gist.github.com/jtroberts83/56c1abe81e273f495c6754020409b480 while working on https://gist.github.com/acdha/d0b4d07e581d6c03b8b615346f98d882.

**Comment by kapilt** [comment]
yeah.. mark is a deprecated alias for tag, which we stopped adding as redundant, but we haven't gone back through to remove extant due to compatibility concerns with extant policies, till we have a better deprecation framework in place.

two comments on the tag policy setup, i'd recommend either using yaml anchors and alias to avoid the repetition, or alternatively generating the policy set (ruamel supports anchor/ref writes incidentally), and `custodian schema can` output json

**Comment by acdha** [comment]
Oh, yes, in my non-toy example it's just a reference — I was happy to see that PyYAML added that automatically:

```yaml
policies:
- actions: &id001
  - key: TagPolicyCompliance
    type: tag
    value: This resource should have tags following policy
  description: Identify resources which lack our accounting tags
  filters: &id002
  - tag:Environment: absent
  - tag:Service: absent
  - or:
    - tag:Owner: absent
    - tag:ResponsibleParty: absent
    - tag:Contact: absent
    - tag:Creator: absent
  name: tagging-compliance-acm-certificate
  resource: aws.acm-certificate
- actions: *id001
  description: Identify resources which lack our accounting tags
  filters: *id002
  name: tagging-compliance-ami
  resource: aws.ami
- actions: *id001
  description: Identify resources which lack our accounting tags
  filters: *id002
  name: tagging-compliance-app-elb
  resource: aws.app-elb
…
```

The main TODO point I had was using the schema definition to output all resource types which support the tag action but I had to switch projects.
