### ISSUE TITLE
Lambda to copy tags from ec2 to ebs volume fails on DescribeInstances operation but does not fail lambda

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3786]
I was missing the `ec2:DescribeInstances` iam permission but noticed that the Lambda, when I tested it, said that it succeeded even though it failed.

policy

```yaml
policies:
- name: copy-tags-from-ec2-to-ebs-volume
  description: |
    Copy EC2 instance tags to EBS volumes
  resource: ebs
  mode:
    type: periodic
    schedule: "rate(1 day)"
    role: copy-tags-from-ec2-to-vols-to-snaps-role
  filters:
    - type: value
      key: "Attachments[].Device"
      value: not-null
  actions:
    - type: copy-instance-tags
      tags:
        - Name
```

Role has the following policy

```terraform
data "aws_iam_policy_document" "inline-copy-tags-from-ec2-to-vols-to-snaps-policy" {
  statement = {
    sid = "AllowCustodianToCopyTagsFromEC2ToVolsToSnaps"

    effect = "Allow"

    actions = [
      "ec2:CreateTags",
      "ec2:DescribeSnapshots",
      "ec2:DescribeTags",
      "ec2:DescribeVolumes",
    ]

    resources = ["*"]
  }
}
```
