### ISSUE TITLE
Cannot ec2.actions.copy-tags Name tag to ebs snapshot: Duplicate tag key 'Name' specified

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3792]
This policy

```yaml
policies:
- name: ec2-daily-backup
  resource: ec2
  description: |
    Creates a snapshot of every EBS volume daily when
    custodian runs its full scan
  filters:
    - type: value
      key: "[length(Tags)][0]"
      op: lte
      value: 2
  actions:
    - type: snapshot
      copy-tags:
        - Name
        - role
```

Returns this error

```bash
ClientError: An error occurred (InvalidParameterValue) when calling the CreateSnapshot operation: Duplicate tag key 'Name' specified.
```
