### ISSUE TITLE
Can't filter log-group using creationTime age

### ISSUE THREAD

**Issue by sshvetsov** [cloud-custodian/cloud-custodian#3803]
I'm trying, but failing to filter log groups that were created more than 30 days ago using the following filter:

```
policies:
- name: OldLogGroups
  resource: log-group
  filters:
  - type: value
    key: creationTime
    op: gt
    value_type: age
    value: 30
```

According to [AWS docs](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_LogGroup.html), the property `creationTime` stores the creation time of the log group, expressed as the number of milliseconds after Jan 1, 1970 00:00:00 UTC.

I understand 'age' value_type already supports standard unix epoch expressed in seconds, but not milliseconds (#2051).

Support for date/time values expressed in milliseconds or adding a new filter like `log-group-age` would allow to cleanup old log groups that have been created certain time ago and either have 0 stored bytes or have not had any writes for a while.

custodian version: 0.8.42.1
