### ISSUE TITLE
RDS Policy wrong output when filter specific Postgres version

### ISSUE THREAD

**Issue by HieronyM** [cloud-custodian/cloud-custodian#3804]
I tried to filter RDS Postgres instance with specific version, I want to filter RDS Postgres instance that not in version 9.4.20, 9.5.15, 9.6.11, and 10.6 using the following filter:

```
policies:
 - name: list_specific-postgres-rds
   resource: rds
   filters:
     - type: value
       key: "Engine"
       op: equal
       value: postgres
     - type: value
       key: "EngineVersion"
       op: not-in
       value: [9.4.20, 9.5.15, 9.6.11, 10.6]
```

The problem is **custodian output still show RDS Postgres version 10.6**.
I'm pretty sure the filter that I'm using is correct, I'm using **custodian version 0.8.42.1**

Thank you.
