### ISSUE TITLE
proposal - population-delta filter

### ISSUE THREAD

**Issue by thisisshi** [cloud-custodian/cloud-custodian#3813]
While max-resources and max-resources-percent can act as safeties/short circuits on policy exec, if a policy begins to suddenly filter many more resources that previous historical counts, that can be a sign of a few issues,

e.g.

1. the policy was updated in such a way that the new policy is now incorrectly identifying resources incorrectly
2. An update to Cloud Custodian modified behavior of extant filters
3. A user has mass modified resources in such a way that would cause the resources to be targeted by an extant policy
4. etc.

In the case of the three examples, a large delta in a historical population vs the extant should be cause for alarm and demand human intervention. If all of the sudden a policy that was previously targeting 0 resources began targeting 50 it's probably safer for a human operator to step and try to determine if the change in behavior is expected, especially if destructive or mutating actions are involved.

The proposed syntax for such a feature would be as follows:

```yaml
policies:
  - name: population-delta-example
    resource: ec2
    max-resources-percent: 10
    filters:
      - type: instance-age
        op: ge
        days: 30
      - type: population-delta
        max-delta: # following in line with max-resources, we give users the option of specifying a count, percent, or a combination of the two
          count: 50
          percent: 10
          op: or
    actions:
      - type: stop
```

In this example, perhaps it is an agreed upon operational choice to recycle hosts every 30 days and to stop hosts that are not kept up to date. In the case that a large number of ec2 instances hit their 30th day at the same time but not more than the 10% designated in max-resources-percent, this filter would be able to stop execution. Reasons for this type of behavior may include the introduction of an unexpected change freeze or perhaps the operating team in charge of the resources was disbanded, leaving no one available to update the instances.

This would not replace max-resources, but would be able to act as an additional safety net with some additional intelligence to note when policy behavior is somehow outside of the expected historical behavior.
