### ISSUE TITLE
iam-policy - Filter for AWS and Customer-managed policies

### ISSUE THREAD

**Issue by jonotto** [cloud-custodian/cloud-custodian#3816]
Is there any way to specify the `Scope` for `iam-policy` to be `All|AWS|Local` via filter? I'm trying to identify unused customer-managed IAM policies (`Scope: Local`). It appears that it is supported as a server-side query (c7n code below) but not as a filter.

```
class PolicyQueryParser(QueryParser):

    QuerySchema = {
        'Scope': ('All', 'AWS', 'Local'),
        'PolicyUsageFilter': ('PermissionsPolicy', 'PermissionsBoundary'),
        'PathPrefix': six.string_types,
        'OnlyAttached': bool
    }
    multi_value = False
    value_key = 'Value'
```

**Comment by kapilt** [comment]
for client side filter on scope, you have to use an Arn filter. Ie to grab aws scoped  policies 

```yaml
type: value
key: Arn
op: contains
value: "iam::aws:policy/"
```

alternatively to grab local scope policies

```yaml
type: value
key: Arn
op: contains
value: "iam::{account_id}:policy/"
```

for server side filtering you do

```
policies:
  - name: iam-scope
    resource: iam-policy
    query:
      - Name: Scope
        Value: Local
```

if your testing locally don't forget to --cache-period=0 to disable client side cache when modifying.
