### ISSUE TITLE
AWS RDS set-snapshot-copy-tags  'dict' object is not callable

### ISSUE THREAD

**Issue by jterlecki** [cloud-custodian/cloud-custodian#3880]
When I execute this policy

```
- name: enable-rds-snapshot-tags
  resource: aws.rds
  actions:
    - type: set-snapshot-copy-tags
      enable: True
```
I get the following error:

2019-04-25 09:02:53,231: custodian.policy:INFO policy: enable-rds-snapshot-tags resource:aws.rds region:ca-central-1 count:1 time:0.54
2019-04-25 09:02:53,686: custodian.actions:ERROR Exception updating rds CopyTagsToSnapshot
 'dict' object is not callable
2019-04-25 09:02:53,688: custodian.policy:INFO policy: enable-rds-snapshot-tags action: copysnapshottags resources: 1 execution_time: 0.46
