### ISSUE TITLE
c7n policy incorrectly handles route53 and regions

### ISSUE THREAD

**Issue by jterlecki** [cloud-custodian/cloud-custodian#3892]
route53 is a global AWS service and should not need a region to be set.

`2019-04-26 13:39:10,158: c7n.policies:WARNING policy:tag-r53domain-compliance-name resources:aws.r53domain not available in region:ca-central-1`

**Comment by kapilt** [comment]
route53 is compromised of several services (dns, resolver, registrar) some of which do have regional endpoints per
https://docs.aws.amazon.com/general/latest/gr/rande.html

route53 dns services are a global endpoint.

**Comment by jterlecki** [comment]
I have just tried that and it did not work for me

```
- name: tag-r53domain-compliance-name
  resource: aws.r53domain
  region: us-east-1
  description: |
    Tag resources that does not meet tag compliance policies (name)
  filters:
    - "tag:Name": absent
  actions:
    - type: tag
      tag: Name
      value: absent
```

`custodian run -s out --profile XXX --cache-period=0  ./tr53.yml`
2019-04-29 09:33:02,113: c7n.policies:WARNING policy:tag-r53domain-compliance-name resources:aws.r53domain not available in region:ca-central-1

`custodian run -s out --profile XXX --cache-period=0 -r ca-east-1 ./tr53.yml`
2019-04-29 09:34:21,781: c7n.policies:WARNING policy:tag-r53domain-compliance-name resources:aws.r53domain not available in region:ca-east-1

`custodian run -s out --profile XXX --cache-period=0 -r us-east-1 ./tr53.yml`
2019-04-29 09:32:13,963: custodian.policy:INFO policy: tag-r53domain-compliance-name resource:aws.r53domain region:us-east-1 **count:0** time:0.13

I confirm that the AWS account contains 2 hosted zones and that the profile used has the proper rights to see and modify the zones.

**Comment by kapilt** [comment]
so two things, first we filter services by region, before we do the region pin, which is during policy execution.

second, wrt to the policy, 'absent' is a magical value that denotes the key isn't present, if you've set the value to the literal string 'absent' per your action, it won't match again on the filter.

**Comment by jterlecki** [comment]
I switched my value to `missing` but still get the same result.  If I put on the command line region ca-central-1 or don`t specify the region, it gives the warning.  If I put us-east-1, it has a count of 0.  I can clearly see the 2 zones in https://resources.console.aws.amazon.com/r/tags, without any tags.

```
policies:
- name: tag-r53domain-compliance-centrecout
  resource: aws.r53domain
  region: us-east-1
  description: |
    Tag resources that does not meet tag compliance policies (centrecout)
  filters:
    - "tag:centrecout": absent
  actions:
    - type: tag
      tag: centrecout
      value: missing
```
