### ISSUE TITLE
request: update ami based on an ami tag in launch-config / launch-template-version

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#3910]
We have monthly new AMIs that need to be updated across all of our launch configs (soon to be launch templates) and to do so, we have a terraform data source that grabs the latest one of our amis based on a regular expression. Unfortunately, we have to update each of our launch configs separately and this can be 100s of terraform runs to get all of our auto scaling groups in compliance.

With launch templates, we can place a tag with the appropriate AMI tag to look for. For example, our launch template can have the tag `AMI_regex=company-golden-.*` and `AMI_version=latest`. Then the cloudcustodian policy can

1. iterate over all of the launch templates where `AMI_regex` tag is present
2. search for that AMI
3. check if that AMI is in that template
4. if not, revise it and continue

With launch configs, it's more difficult since configs don't allow tagging. We could put those above tags on the ASG themselves, iterate through the ASGs to get the launch configs, then follow the steps from 2 onwards

**Comment by kapilt** [comment]
thanks for updating with a policy sketch, was about to ask about that. re filter i was thinking ami age seems to match up on the requirements. 


```yaml
policies:
   - name: asg-ami-update
      resource: asg
      filters:
        - type: image
           key: CreationDate
           value_type: age
           op: greater-than
           value: 35
```

**Comment by nitrocode** [comment]
Very nice! I updated the ticket with that filter. Do you think this is a good way forward? I was going to take a crack at a custom lambda but if you approve of this, I'd like to start coding. Unless you have any additional suggestions?

**Comment by kapilt** [comment]
where's the version string / matching coming from.. the tag? is the tag being hot swapped out of band to reflect the latest ami?

for reference do you have an example of the terraform ami data source you could post
https://www.terraform.io/docs/providers/aws/d/ami_ids.html

**Comment by nitrocode** [comment]
So we have a mixture of service packed AMIs and one golden AMI.

Many of our services use our golden AMI so those could just use the regular expression without the use of the tags.

```
data "aws_ami" "golden" {
  most_recent = true

  filter = {
    name   = "tag:${local.env}"
    values = ["current"]
  }

  filter {
    name   = "name"
    values = ["golden-build-*"]
  }

  owners = ["${module.global.aws_account_id["build"]}"]
}
```

Our few packed services however will not have a clear regular expression and instead will grab the latest AMI based on the service and version.

```
data "aws_ami" "packed" {
  most_recent = true

  filter {
    name   = "project"
    values = ["${local.service_name} Endpoint"]
  }

  owners = ["${module.global.aws_account_id["build"]}"]
}
```

**Comment by kapilt** [comment]
thanks for the context, so those golden amis are typically hosted in different accounts as well? we'll need to include owners as well in the filter to accomodate that (default to `self`)

**Comment by nitrocode** [comment]
@kapilt wouldn't the `owners` be an attribute for the action `update-ami` ?

e.g. 

```
policies:
- name: launch-configs-update-ami
  resource: aws.asg # or aws.launch-configs?
  filters:
    - type: image
      key: CreationDate
      value_type: age
      op: greater-than
      value: 35
  actions:
    - type: update-ami
      ami-search:
        - regex: company-golden.*
        - tag:AMI_version: latest
        - owner: 23409283042308
```
