### ISSUE TITLE
ECS Resource empty tag filter not working

### ISSUE THREAD

**Issue by stewmi** [cloud-custodian/cloud-custodian#3944]
Policy that looks for empty tags on ECS cluster is running despite tags being set.  I think it could be related to DescribeCluster not returning tags by default possibly?

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.describe_clusters

When the below policy runs,  it will send an email even though the cluster has been tagged.

Any help would be greatly appreciated.

```
vars:
  notify-var: &notify-var
    - type: notify
      template: default.html
      template_format: 'html'
      priority_header: '1'
      to:
        - __TO_Email_PLACEHOLDER_DO_NOT_REMOVE_OR_EDIT__
        - resource-owner
      transport:
        type: sqs
        queue: __Queue_URL_PLACEHOLDER_DO_NOT_REMOVE_OR_EDIT__
    
  mode-var: &mode-var
    type: periodic
    role: __Custodian_Role_ARN_PLACEHOLDER_DO_NOT_REMOVE_OR_EDIT__
    schedule: "cron(0 12 ? * * *)" 
    # Cron to run at 7 AM EST or 12 PM GMT 

policies:
  - name: ecs-tag-compliance
    description: |
      Detect the untagged ECS resource and send notification on a schedule mode
    resource: ecs
    mode:
      <<: *mode-var   
    filters:
      - or:
        - "tag:PrimaryOwner": empty
        - "tag:SecondaryOwner": empty
        - "tag:CostCenterID": empty
        - "tag:Name": empty
    actions:    
      - <<: *notify-var
        subject: "Policy Violation detected in AWS Account [ {{ account }} ] due to ECS tagging compliance"
        violation_desc: "The following ECS resource(s) were detected as violating the policy against creating resource without tag-CostCenterID/PrimaryOwner/SecondaryOwner/Name"
        action_desc: "Notification to OwnerEmail"
```
