### ISSUE TITLE
How to tag Lambda functions created from CloudCustodian

### ISSUE THREAD

**Issue by techsami** [cloud-custodian/cloud-custodian#3966]
Please suggest how to tag Lambda functions created by CloudCustodian

**Comment by thisisshi** [comment]
```yaml
mode:
  type: cloudtrail
  events:
    - CreateBucket
  tags:
    Application: Custodian
    CreatedBy: CloudCustodian
```
