### ISSUE TITLE
debugging jsonschema anyOf

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#3967]
I have been playing around with jsonschema to figure out how we could better debug and output what is being matched for anyOf conditions. 
For example: 
```
policies:
  - name: my-first-policy
    resource: ec2
```
returns just ```{'$ref': '#/definitions/resources/aws.ec2/policy'}```

however this policy:
```
policies:
  - name: my-first-policy
    resource: ec2
    filters:
      - type: value
        key: "VpcAttachments[0].State"
        op: 'eq'
        value: 'detached'
```
returns a list of generic value filters.

```
{'$ref': '#/definitions/resources/aws.shield-protection/filters/value'}
{'$ref': '#/definitions/resources/aws.shield-attack/filters/value'}
{'$ref': '#/definitions/resources/aws.app-elb/filters/target-group'}
{'$ref': '#/definitions/resources/aws.app-elb-target-group/filters/value'}
{'$ref': '#/definitions/resources/aws.ec2/filters/value'}
{'$ref': '#/definitions/resources/aws.ec2/policy'}
...
```

This seems to be because jsonschema goes through every branching possibility and these generic filter/values are being instantiated in the filter_registry. so all resources will be checked against. https://github.com/cloud-custodian/cloud-custodian/blob/334abb7c3d7caf1b240ba8cd10cf5d3be3fbdefb/c7n/filters/core.py#L120 

not sure what the best way to solve for this is. one idea is to include logic to remove these extra items before displaying results to the use.
