### ISSUE TITLE
DatabaseConnections Metric filter randomly matching active databases.

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#4014]
I'm using the filters below, and it will periodically (maybe 5% of runs), match on actively used databases.     Any thoughts on this? 

```yaml
filters:
  - type: metrics
    name: DatabaseConnections
    days: 30
    value: 0
    op: equal
    statistics: Sum
  - type: value
    value_type: age
    key: InstanceCreateTime
    value: 29
    op: greater-than
  - "tag:CustodianDeleteThisRDSDatabaseOn": absent 
```
Here is the run log with no changes to the policy, randomly matching on actively used databases:

```
2019-05-13 15:24:46,912 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.01
2019-05-13 15:28:29,274 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.26
2019-05-13 15:31:03,246 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:6.55
2019-05-13 15:34:24,437 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:14 time:5.85
2019-05-13 15:36:44,139 - custodian.policy - INFO - policy: rds-stale-databases resource:rds region:us-east-1 count:23 time:6.24
```

**Comment by kapilt** [comment]
What version of custodian? This is partial content on the policy, is that all the filters on the original? and the resource here is `rds`?

I just re-reviewed the code here, i'm not seeing anything that would be odd here, its a straight passthrough basically, and if we get no results from the api we'll skip/omit the resource from the filter. I'll see if i can reproduce.

**Comment by wallabyies** [comment]
Thanks!  Here is the version we're using:

c7n:0.8.43.1

Here is the full policy, I'm only running with dryrun from the command line.

```yaml
policies:
  - name: rds-stale-databases
    resource: rds
    filters:
      # Find databases that have had no connections made over the past 30 days.
      - type: metrics
        name: DatabaseConnections
        days: 30
        value: 0
        op: equal
        statistics: Sum
      # Only match on databases >= 30 days old.
      - type: value
        value_type: age
        key: InstanceCreateTime
        value: 29
        op: greater-than
      # Only match on databases that do not have delete date already
      - "tag:CustodianDeleteThisRDSDatabaseOn": absent          
    actions:
       # Tag stale to shutdown.   
       - type: tag
         key: Scheduled
         value: scheduled-stale
       # Tag informative message
       - type: tag
         key: CloudCustodianLastEnforcement
         value: "rds-stale-databases - No connections made in 30 days.   1) Please delete or archive database."        
       # Tag with date to delete, 30 days in future
       - type: tag
         key: CustodianDeleteThisRDSDatabaseOn
         value: "{now:+30d%Y-%m-%d}"
       # Need to confirm behavior of this action, may need to revise.
       - type: mark-for-op
         tag: CustodianDeleteRDSOn
         msg: "Unused RDS Database for >= 60 days: {op}@{action_date}"
         op: notify
         days: 30
```
