### ISSUE TITLE
is there a way to exclude a specific instanceid in AWS

### ISSUE THREAD

**Issue by jterlecki** [cloud-custodian/cloud-custodian#4057]
Is there a way to exclude a specific instanceid or resource id in AWS from a given policy (other than with a tag?)

**Comment by thisisshi** [comment]
```yaml
policies:
  - name: not-this-instance
    resource: aws.ec2
    filters:
      - not:
        - InstanceId: i-xxxxxxxxx
```
