### ISSUE TITLE
Security Group filters issue

### ISSUE THREAD

**Issue by shitulg** [cloud-custodian/cloud-custodian#4066]
Hi Team,

I need to filter out  Security Groups that has any inbound rule that allows connectivity , for CIDR range "0.0.0.0/0" , for any Ports other than [ 80,443,25 ] for this I used two approaches but i guess , both are not working as expected. Following are the two approaches that I used :

1. I tried to do this through the  “OnlyPorts” filter , which is a negative assertion match, it matches when a permission includes ports outside of the specified set.

So ideally it should filter the resources which satisfy both the conditions i.e. the CIDR range should be “0.0.0.0/0” and the port should not be within the set [80,443,25].

```yaml
filters:
      - and:
        - type: ingress
          Cidr:
              value: "0.0.0.0/0"
        - type: ingress
          OnlyPorts: [80,443,25]
```

But it is not filtering the correct results , it fetches any rule that has CIDR range specified as "0.0.0.0/0" , whether the PORT is within the set [80,443,25] or not and also any rule that has PORTS as 80,443,25.

Not sure , but it seems as if the filter is not working on the combination of CIDR and Ports instead filtering these separately.

2. In the second approach , I just tried to filter the Inbound rules that have CIDR range as "0.0.0.0/0" and Ports NOT in 80,443,25. below filters for the same.

```
filters:
  - type: ingress
    Cidr:
        value: "0.0.0.0/0"
  - not:
    - type: ingress
      Ports: [80, 443, 25]
```

But in the similar fashion as the above it is also filtering incorrect resources. It filters the resources if only invalid port are present , but fails if any of the Ports (80,443,25) is present.

Kindly help me with this , also let me know in case any doubts in the above.

Thanks.

**Comment by kapilt** [comment]
the correct way to express this is as a single ingress filter

```yaml
type: ingress
Cidr:
   value: "0.0.0.0/0"
OnlyPorts: [80, 443, 25]
```

and/or semantics apply around filter blocks apply to the resources for the policies. in this case your evaluating rules within a group, ie its effectively a sub resource, so multiple filters that partially describe a rule effectively have `or` semantics when looking at it from the perspective of a rule. Using a single ingress filter that exactly describes a concrete rule your looking for resolves, and then combine ingress filters with or/ands when looking for multiple types of concrete rules.
