### ISSUE TITLE
Custodian validate fails with variables

### ISSUE THREAD

**Issue by dvianello** [cloud-custodian/cloud-custodian#4085]
Validating policies containing variables with `custodian validate` currently causes validation errors. 

For example, the policy
```
  - name: ec2-offhours-stop
    resource: ec2
    description: |
      Turn off EC2 instances after working hours
    filters:
      - "tag:custodian-test": present
      - "tag:aws:elasticmapreduce:instance-group-role": absent
      - "tag:aws:autoscaling:groupName": absent
      - *offhours_tag
      - type: offhour
        default_tz: "{timezone}"
        opt-out: true
        offhour: *offhour
      - type: instance-age
        hours: 1
    actions:
      - stop
``` 
fails validation with the following error:
```
2019-05-30 12:01:21,408: custodian.commands:ERROR Configuration invalid: policies/offhours.yml
2019-05-30 12:01:21,408: custodian.commands:ERROR Policy: ec2-offhours-stop is invalid: Invalid timezone specified {timezone}
```

This currently implies that policies using variables meant to be populated by `c7n-org` can't be validated successfully. In our case, this breaks our CI/CD jobs and we'd need to put a workaround in place.
