### ISSUE TITLE
Certifi python module missing when deploying cloudtrail lambda functions

### ISSUE THREAD

**Issue by xgarcias** [cloud-custodian/cloud-custodian#4105]
The following error happens when the lambda function is triggered

`[ERROR] Runtime.ImportModuleError: Unable to import module 'custodian_policy': No module named 'certifi'`

As a workaround, I had to add the *certifi* package to the policy files.

```
policies:
  - name: my-policy
    description: my description
    resource: my-resource
    mode:
      type: cloudtrail
      packages:
        - botocore
        - boto3
        - urllib3
        - certifi
```

**Comment by kapilt** [comment]
what's an example policy that triggers?

**Comment by xgarcias** [comment]
The following policy has been working for months, until today. I have redacted some parts because it contained sensitive information. I hope it is not a problem.

I redeployed the lambda function because I didn't want to alert on changes made by a given IAM role. See the filter.

`c7n-org run -c config.yaml -u policy.yml  -s /tmp/`

```
policies:
  - name: ec2-changes-security-groups
    description: |
      Changes in security groups
    resource: iam-role
    mode:
      type: cloudtrail
      packages:
        - botocore
        - boto3
        - urllib3
      member-role: REDACTED
      role: REDACTED
      events:
        - source: ec2.amazonaws.com
          event: AuthorizeSecurityGroupIngress
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
        - source: ec2.amazonaws.com
          event: AuthorizeSecurityGroupEgress
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
        - source: ec2.amazonaws.com
          event: RevokeSecurityGroupIngress
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
        - source: ec2.amazonaws.com
          event: RevokeSecurityGroupEgress
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
        - source: ec2.amazonaws.com
          event: CreateSecurityGroup
          ids: "userIdentity.sessionContext.sessionIssuer.userName"
    filters:
      - not:
        - type: event
          key: "detail.userIdentity.sessionContext.sessionIssuer.userName"
          op: regex-case
          value: '^ServiceRoleForAmazonEKS-.*'
    actions:
      - type: notify
        to: ['REDACTED']
        template: default
        transport:
          type: sqs
          queue: REDACTED
```

Dockerfile running c7n-org
```
FROM python:3.7

RUN git clone https://github.com/cloud-custodian/cloud-custodian.git /src

WORKDIR /src
RUN pip3 install .

WORKDIR /src/tools/c7n_org
RUN pip3 install .

# Setup for EntryPoint
ENV LC_ALL="C.UTF-8" LANG="C.UTF-8"
#VOLUME ["/var/log/cloud-custodian", "/etc/cloud-custodian"]
#ENTRYPOINT ["/usr/local/bin/custodian"]
WORKDIR /custodian

ADD  run.sh .
CMD ["/custodian/run.sh"]
```
