### ISSUE TITLE
EC2: Populate the value of a new tag with an existing tag value

### ISSUE THREAD

**Issue by JayBachir** [cloud-custodian/cloud-custodian#4119]
Hi All, 
I am trying to create a new tag for a set of filtered EC2 instances, then populate the new tag value with the value of an existing tag. In other words, copying the value of one tag to another. 
I tried below, but it is treated as as a String rather then getting the value of the specified tag.
```
policies:
  - name: copy tag value
    resource: ec2
    filters:
      - 'tag:NewTagKey': absent
    mode:
      execution-options:
        metrics_enabled: true
      type: periodic
      schedule: "rate(5 minutes)"
      role: arn:aws:iam::{account_id}:role/role
      timeout: 300
    actions: 
      - type: tag
        key: NewTagKey
        value: 'tag:ExistingTagKey' or ExistingTagValue
```
