### ISSUE TITLE
How do you create custom policies?

### ISSUE THREAD

**Issue by dineshdh** [cloud-custodian/cloud-custodian#4147]
I have a requirement to create a policy which splits the value of an AWS tag and then converts one of its' values to a datetime, works out the duration from that date till now and perform an action if the duration is more than x number of days. What is the best way to achieve this?

Ideally I would like to write my own python filter and reference it somehow without having to recompile the custodian binary

**Comment by thisisshi** [comment]
There are a couple new features coming in a new release that should allow for this functionality: 

value_regex: https://github.com/cloud-custodian/cloud-custodian/pull/4019

date value type: https://github.com/cloud-custodian/cloud-custodian/pull/4052

basic gist is, the value_regex will allow you to specify a part of the value to extract and then you can use the date value_type to do additional comparisons:

example:
```yaml
filters:
    - type: value
      key: "tag:OurCustomKey"
      value_type: expiration
      regex_capture_expression: ".*expiry=([0-9]{4}-[0-9]{2}-[0-9]{2}).*"
      op: less-than
      value: 0
```
