### ISSUE TITLE
EC2 Instance Not Stopping After Filter Applied

### ISSUE THREAD

**Issue by JayBachir** [cloud-custodian/cloud-custodian#4191]
I have the below policy that enforces tagging on newly launched instances and supposed to stop the instance at launch if a certain tag does not exist. When looking at the execution logs, I see that the appropriate instances are being filtered, but when the policy tries to apply the stop action on the instance it displays "Stopping 0 of 1" 
```
 - name: ec2-enforce-patch-group-tagging-compliance-1
    description: "Detect, Stop, Terminate instances created without Patch Group tag\n"
    resource: ec2
    filters:
      - 'tag:Patch Group': absent
    mode:
      execution-options:
        metrics_enabled: true
      type: cloudtrail
      events:
       - source: ec2.amazonaws.com
         event: RunInstances
         ids: "responseElements.instancesSet.items[].instanceId"
      role: arn:aws:iam::{account_id}:role/CloudCustodianRole
    actions:
      - stop
      - type: notify
        template: default.html
        violation_desc: "desc"
        priority_header: '1'
        subject: 'subject'
        action-desc: 'action desc'
        to:
          - resource-ownerm
        transport:
          type: sqs
          region: '{region}'
          queue: 'https://sqs.{region}.amazonaws.com/{account_id}/CloudCustodianMailerQueue' 
      - type: notify
        template: default.html
        to:
          - 'cloudwatch://'
        transport:
          type: sqs
          region: '{region}'
          queue: 'https://sqs.{region}.amazonaws.com/{account_id}/CloudCustodianLoggerQueue'
```

Lambda function logs: 
![image](https://user-images.githubusercontent.com/26499471/59701889-8b685980-91c4-11e9-8ca3-f0ab2b7a400a.png)
