### ISSUE TITLE
Detaching policies returned via iam-role check-permissions filter

### ISSUE THREAD

**Issue by MrDweebus** [cloud-custodian/cloud-custodian#4205]
Is there a way to detach a policy if the ARN is unknown via the set-policy action type? Currently, we're running into a weird loop trying to find/detach/delete star:star policies on IAM roles/groups. 
Given a filter like:
```
name: aws-cis-1-22-role-policy-removal
    description: Remove policies that are attached to roles that allow *.* permissions.
    region: us-east-1
    resource: iam-role
    filters:
      - type: check-permissions
        match: allowed
        match-operator: and
        actions:
          - "Action:*"
          - "Resource:*"
    actions:
      - type: set-policy
        state: detached
        arn: arn:aws:iam::aws:policy/AdministratorAccess
```
This will detach the AdministratorAccess AWS-managed policy, but if we find a custom policy that uses star:star, we can't determine the ARN to detach it. 

We've also written a filter to delete the policies with star:star access, but it can't delete policies that are currently attached to a role/group. Is this simply something we will have to do with an external Lambda call?
