### ISSUE TITLE
orgaccounts.py (from c7n-org) regions flag puts *id001 instead of correct value

### ISSUE THREAD

**Issue by jterlecki** [cloud-custodian/cloud-custodian#4210]
When I try to add regions as an argument with the **orgaccounts.py** script, it incorrectly puts the region with ***id001** as a value.

`python3 ./tools/c7n_org/scripts/orgaccounts.py --active true --regions ca-central-1 -f accounts.yml`

Results: 
```
- account_id: 'XXXXXXXXXXXXXXXX'
  email: email@address.com
  name: accountname
  regions: *id001
  role: arn:aws:iam::XXXXXXXXXXXXXXXX:role/OrganizationAccountAccessRole
  tags:
  - path:/OU
```
Expected: 
```
- account_id: 'XXXXXXXXXXXXXXXX'
  email: email@address.com
  name: accountname
  region:
  - ca-central-1
  role: arn:aws:iam::XXXXXXXXXXXXXXXX:role/OrganizationAccountAccessRole
  tags:
  - path:/OU
```
