### ISSUE TITLE
azure - resource cost filter

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4215]
Filter based on the resource costs

E.g. filter resources based on the cost in last 3 days.
We need to evaluate API before we make final decision on filter design
```
filters:
  - type: cost
    days: 3
    op: gt
    price: 100
```
