### ISSUE TITLE
[SecurityHub] Findings format seems to require a 'Description' field that is not  supplied

### ISSUE THREAD

**Issue by lanejlanejCH** [cloud-custodian/cloud-custodian#4234]
The SecurityHub findings format seems to have changed, such that it has a requirement that a 'Description' field should be provided which Cloud Custodian doesn't honour. 

'FailedFindings': [{'Id': 'eu-west-1/627886280200/a4c96f76077a6a98477f63fbd679d331/e2e53110f710e5e82ae9e7c7d174d6f9', 'ErrorCode': 'InvalidInput', 'ErrorMessage': "Finding does not adhere to Amazon Finding Format. data should have required property 'Description'."}]}

**Comment by kapilt** [comment]
looks they just went GA and did some minor incompatible api change along the way (description required). We'll need to cut a new release as well. note you can add a `description` field to your `policy` (not action) and it will be used for the description field. it looks we just need to add description to schema, and maybe add a non null default (policy name).

**Comment by kapilt** [comment]
work around example

```
policies:
  - name: my-pet-hunt
     resource: aws.ec2
     description: "this will be used for finding description"
     actions:
        - type: post-finding
          severity_normalized: 6
          types:
            - "Software and Configuration Checks/Industry and Regulatory Standards/NIST CSF Controls (USA)"
```
