### ISSUE TITLE
Security Group Type Error Issue

### ISSUE THREAD

**Issue by hivehome** [cloud-custodian/cloud-custodian#4261]
There seems to be a type comparison issue on the new (0.8.44.1) AWS Security Group Filters; ToPort, FromPort:

Policy:
```
filters:
   - Cidr:
        value:
        - 0.0.0.0/0
        - ::/0
      FromPort: 0
      ToPort: 65535
      match-operator: in
      type: ingress
```

Error Message:
```[ERROR] TypeError: '>=' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 910, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 520, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 232, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 460, in resources
    resources = self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 109, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/core.py", line 259, in process
    return self.process_set(resources, event)
  File "/var/task/c7n/filters/core.py", line 275, in process_set
    r[resource_type.id] for r in f.process(resources, event)])
  File "/var/task/c7n/resources/vpc.py", line 991, in process
    return super(SGPermission, self).process(resources, event)
  File "/var/task/c7n/filters/core.py", line 197, in process
    return list(filter(self, resources))
  File "/var/task/c7n/resources/vpc.py", line 1106, in __call__
    perm_matches['ports'] = self.process_ports(perm)
  File "/var/task/c7n/resources/vpc.py", line 997, in process_ports
    if port >= perm['FromPort'] and port <= perm['ToPort']:```

**Comment by kapilt** [comment]
The actual exception value is missing in this bug report, this is just the traceback. its also helpful to post complete policies or at least all the filters. fwiw the posted filter here is invalid in that match-operator valid values are  `and` and `or`. i'd suggest making a complete policy example that exhibits and posting here.

also doing Cidr value as an array with ipv4 and ipv6 is also not meaningful. Cidr only targets ipv4, CidrV6 targets ipv6, and using an array value is only useful if your specifying a comparison operator along with `value`. the top level match-operator is for comparison between attributes. ie your looking for, also you can drop the ports comparison afaics, your looking for any port usage allowed from any wild card cidr on either v4 or v6.

```
type: ingress
match-operator: or
Cidr:
    value: "0.0.0.0/0"
CidrV6:
    value: "::/0"
```

**Comment by hivehome** [comment]
I'm trying to match if a port range is used, this example 0-65535 but equally 1024-1030 would be another example.

Regarding the match-operator you're quite right and I have typo'd that in the policy
The updated full policy is:
```DEPLOY_STATUS: False
name: security-group-open-to-world-ports-all
resource: security-group
filters:
  - or:
    - type: ingress
      Ports: "-1"
      Cidr:
        value: "0.0.0.0/0"
      CidrV6:
        value: "::/0"
      match-operator: eq
    - type: ingress
      FromPort: 0
      ToPort: 65535
      Cidr:
        value: "0.0.0.0/0"
      CidrV6:
        value: "::/0"
      match-operator: or
actions:
  - type: post-finding
    title: security-group-open-to-world-ports-all
    types:
      - "Software and Configuration Checks/AWS Security Best Practices"
    compliance_status: "FAILED"
    recommendation: "This security group has Ingress All Traffic open to the Internet."```

**Comment by kapilt** [comment]
i'm actually trying to figure out why that validates at all

**Comment by kapilt** [comment]
i think i found a significant issue with our schema validation and the use of 'or' and 'and' blocks... going to open a file a separate issue for it.

**Comment by hivehome** [comment]
Thanks @kapilt That explains quite a bit of the odd behaviour. Also apologies I've clearly gone mad, all my other policies are using and/or and for some reason this one I keep sticking `eq` in :facepalm:.

Briefly regarding `op` it's not valid with the security-group resource filter:
``` 
Error on policy:security-group-open-to-world-ports-all resource:security-group
Additional properties are not allowed ('op' was unexpected)
```

The Type issue is resolved.
This policy is triggering on All Traffic, and All TCP/UDP ports as expected.
```
DEPLOY_STATUS: True
name: security-group-open-to-world-ports-all
description: security-group-open-to-world-ports-all
resource: security-group
filters:
  - or:
# Match All TCP
    - type: ingress
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      Cidr:
        value: "0.0.0.0/0"
      match-operator: and
    - type: ingress
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrV6:
        value: "::/0"
      match-operator: and
# Match All UDP
    - type: ingress
      IpProtocol: udp
      FromPort: 0
      ToPort: 65535
      Cidr:
        value: "0.0.0.0/0"
      match-operator: and
    - type: ingress
      IpProtocol: udp
      FromPort: 0
      ToPort: 65535
      CidrV6:
        value: "::/0"
      match-operator: and
# These match when SG "Traffic All" rules are used
    - type: ingress
      Cidr:
        value: "0.0.0.0/0"
      IpProtocol: '-1'
      match-operator: and
    - type: ingress
      CidrV6:
        value: "::/0"
      IpProtocol: '-1'
      match-operator: and
actions:
  - type: post-finding
    title: security-group-open-to-world-ports-all
    types:
      - "Software and Configuration Checks/AWS Security Best Practices"
    compliance_status: "FAILED"
    recommendation: "This security group has Ingress All Traffic open to the Internet. Restrict to known IPs and required Ports only."
```
