### ISSUE TITLE
Cloudwatch logs expiry for policy lambdas to be configurable

### ISSUE THREAD

**Issue by lanejlanejCH** [cloud-custodian/cloud-custodian#4276]
Currently when CC creates policy lambdas they have cloudwatch logs associated with them that have no expiry date.  Would it be possible to add a feature such that cloudwatch log expiry length could be a configurable parameter, and set via cloudwatch immediately after lambda is deployed?

**Comment by kapilt** [comment]
the preferred and easiest option is to deploy a custodian policy that sets retention across cloud watch logs. ie use the tool to govern and manage itself among other resources of that type (cloud watch logs group).

```yaml
policies:
 - name: custodian-log-retention
   resource: aws.log-group
   filters:
    - type: value
      key: logGroupName
      op: regex
      value: "^/aws/lambda/custodian-"
    - retentionInDays: absent
   actions:
    - type: retention
      days: 90
```
