### ISSUE TITLE
Question - The policy start functionality does not work for CT based policies ?

### ISSUE THREAD

**Issue by kumarsiyer** [cloud-custodian/cloud-custodian#4278]
I had a below example policy to notify users and the policy start date is July1st. However it started notifying users even before the start date. 

policy example 

```
  - name: ec2-notify
    resource: ec2
    start: 07/01/2019    
    mode:
      type: cloudtrail
      events:
        - RunInstances
```
