### ISSUE TITLE
`tag` action type not working?

### ISSUE THREAD

**Issue by dustnic** [cloud-custodian/cloud-custodian#4326]
I am trying to create a simple policy that tags an instance according to some criteria.
Got the inspiration from here: https://cloudcustodian.io/docs/aws/examples/tagcompliance.html

```
policies:
- name: ec2-tag-delete-allowed
  resource: ec2
  description: |
    Notify Slack if any EC2 resource does not have the DeleteAllowed tag and add it (value=True)
  filters:
    - "tag:DeleteAllowed": absent
    - type: value
      key: State.Name
      value: terminated
      op: ne
  actions:
    - type: tag
      key: DeleteAllowed
      value: True
    - type: notify
      slack_template: slack-notification-template
      to:
        - {{ slack_hook_url }}
      transport:
        type: sqs
        queue: {{ sqs_queue_url }}
      violation_desc: "EC2 resources do not have the DeleteAllowed tag"
      violation_gravity: "danger"
      action_desc: "Notify and tag resources with DeleteAllowed=True"
```

However, I'm getting an error when running it.

```
[AWS CodeBuild Plugin] {'type': 'tag', 'key': 'DeleteAllowed', 'value': True} is not valid under any of the given schemas
[AWS CodeBuild Plugin] 
[AWS CodeBuild Plugin] Failed validating 'anyOf' in schema[18]['allOf'][1]['properties']['actions']['items']:
[AWS CodeBuild Plugin]     {'anyOf': [{'$ref': '#/definitions/actions/notify'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/auto-tag-user'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/mark-for-op'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/tag-trim'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/mark'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/unmark'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/rename-tag'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/normalize-tag'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/copy-related-tag'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/post-finding'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/start'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/resize'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/stop'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/reboot'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/terminate'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/snapshot'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/modify-security-groups'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/autorecover-alarm'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/set-instance-profile'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/propagate-spot-tags'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/resources/aws.ec2/actions/send-command'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/invoke-lambda'},
[AWS CodeBuild Plugin]                {'$ref': '#/definitions/actions/put-metric'},
```
