### ISSUE TITLE
Allow c7n-org to use some annotation to match accounts with policies

### ISSUE THREAD

**Issue by matias2681** [cloud-custodian/cloud-custodian#4349]
Currently `c7n-org` allows you to add tags to accounts and policies. The behavior seems to be that you have to invoke specifically that tag to run the policy that match it in that account. e.g.
If you have 2 accounts in the config.yml
```YAML
accounts:
  - account_id: 'prod'
    name: prod
    regions:
      - us-east-1
    role: arn:aws:iam::987654321:role/role-cloud-custodian
  - account_id: 'sandbox'
    name: sandbox
    regions:
      - us-east-1
    role: arn:aws:iam::123456789:role/role-cloud-custodian
    tags:
      - myTag
```
Let's supposed that you have this policies in place:
```YAML
policies:
  - name: sandbox_noncompliance_ec2
    resource: ec2
    tags:
      - myTag
    filters:
      *sandbox_tag_noncompliance_filter
    actions:
      - terminate

  - name: noncompliance_ec2
    resource: ec2
    filters:
      *tag_noncompliance_filter
```
To run the policies that have the `myTag` tag you have to do.
```
c7n-org run -c /opt/accounts/config.yml -u /opt/policies/tag_noncompliance.yml -s /opt/output -l myTag --dryrun
```
If you remove the tag parameter `-l myTag` all the policies are run against all the accounts.
## Feature request:
It'd be very useful to have some way to annotate the accounts and the policies so that only the policies that match the annotation that the account has will be run in such account. As a default, if the account is not annotated all the policies without annotation can be run on that account. 

Using the above example with the new feature you won't have to specify the annotation as `c7n-org` will take care of match the annotations between accounts and policies.

The justification for this feature is that it is quite common to be more aggressive in different environments like sandbox or dev but more protective in others like prod. It's worth to mention that it's currently possible to do this with `c7n-org` using tags but it requires to have the tags in a script and the redundancy of that information seems error-prone and it'd be better to have it as a `c7n-org` functionality that could add value to the community.
