### ISSUE TITLE
aws elb healthcheck-protocol-mismatch

### ISSUE THREAD

**Issue by hivehome** [cloud-custodian/cloud-custodian#4371]
This policy does not appear to work, it is triggering for all ELBs even when the protocols do match.
Can you advise if this is a policy issue, please?
```
DEPLOY_STATUS: True
name: elb-healthcheck-protocol-mismatch
comment: |
  If ELB healthcheck protocol doesn't match open port on target report
resource: elb
description: "elb-healthcheck-protocol-mismatch"
filters:
  - type: healthcheck-protocol-mismatch
actions:
  - type: post-finding
    types:
      - "Software and Configuration Checks/AWS Security Best Practices"
    compliance_status: "FAILED"
    recommendation: "ELB instance has healthcheck protocol mismatch"
```
