### ISSUE TITLE
Azure - functions docs inline json

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4383]
I noticed we show this in our docs
```
      mode:
        type: azure-event-grid
        events: [{
            resourceProvider: 'Microsoft.KeyVault/vaults',
            event: 'write'
          }]
```
Weird to just drop JSON in, that should probably be YAML (and we could demo the shortcut aliases too):
 
```
      mode:
        type: azure-event-grid
        events:
           - resourceProvider: Microsoft.KeyVault/vaults
             event: write
```

https://cloudcustodian.io/docs/azure/advanced/azurefunctions.html#azure-azurefunctions
