### ISSUE TITLE
Access - event-owner or - resource-owner or  auto-tag-user values for mailer.html.j2?

### ISSUE THREAD

**Issue by jcare23** [cloud-custodian/cloud-custodian#4422]
I have a scenario where I would like to add the - event-owner or - resource-owner or auto-tag-user values into my email and slack templates.  If not, is there a way to get the auto-tag-user value or get the value of a tag?  I don't own the email domain and can't add every user since they need to validate through SES (AWS).  My goal is to send an email and slack message to a mailing list and slack channel with a list of resources that includes the resource owner for each item in the list.  I have everything set up but a way to get access to the owner values.

**Comment by Naveenraaj** [comment]
Hi @jcare23 , 

Note: Little late response, please ignore if you have already sorted it out.

1. Following example should match your use case in the issue,
[Auto-tag user who created an EC2 instance]( https://cloudcustodian.io/docs/aws/examples/ec2-auto-tag-user.html) 
2. Add contact_tags( in above example it is CreatorName) in your c7n-mailer/mailer.py config , [example ](https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_mailer/example.yml)

Note: don't forget to run : c7n-mailer --config mailer.yml --update-lambda , that will update the contact_tags to your lambda or create a new lambda

3.The run the below policy with the account, through which the mailer.py was ran

```
policies:
- name: ec2-auto-tag-user
  resource: ec2
  actions:
    - type: notify
      template: default.html
      priority_header: 1
      subject: "Hi there from Custodian, your list of EC2 instance below"
      to:
       - resource-owner 
      transport:
        type: sqs
        queue: <your-sqs URL>
        region: us-east-1
```


This would use resource-owner in the 'to:' field to gather the tags that were defined in mailer.py , which is CreatorName in our case

Hope this helps.
