### ISSUE TITLE
Security Group filtering with OnlyPorts when the rule has a range

### ISSUE THREAD

**Issue by caversa** [cloud-custodian/cloud-custodian#4428]
I have a policy that currently is taking advantage of the OnlyPorts functionality.  This works great, but I have run into an issue when the rule includes a range, and looking at the code I do not think it can handle this currently.

My exceptions are the typical ones - 443, 80, etc.  But then I have a rule with a range of 8000 - 8002 that should also be an exception.  If I list each port in the range ( 8000,8001,8002) it doesn't work.  I've tried to make a separate or condition with a FromPort and ToPort section for this one range case, but my attempts have also failed to get it to work correctly, because it need the inverse results.  Any suggestions?

Thanks,
Carrie

```
    - type: ingress
      Cidr:
          value: "0.0.0.0/0"
      OnlyPorts: [80,443,8000,8001,8002]
```
