### ISSUE TITLE
S3 - Find buckets that do not contain a condition in policy

### ISSUE THREAD

**Issue by jakauppila** [cloud-custodian/cloud-custodian#4439]
So I am attempting to define a policy that identifies S3 buckets that are missing a particular statement.

This is the bucket policy currently applied:
```
{
    "Version": "2012-10-17",
    "Id": "BucketPolicy1",
    "Statement": [
        {
            "Sid": "SourceNetwork",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::foobar/*",
            "Condition": {
                "NotIpAddress": {
                    "aws:SourceIp": "10.0.0.0/16"
                }
            }
        }
    ]
}
```

I would anticipate something like this:
```
policies:
  - name: s3-bucket-network-restrictions
    resource: s3
    comments: |
      Notifies on S3 buckets that do not have appropriate network restrictions
    filters:
      - type: missing-statement
        statements:
          - Effect: 'Deny'
            Principal: '*'
            Condition:
              NotIpAddress:
                "aws:SourceIp": "10.0.0.0/16"
      - not:
        - "tag:exception:s3:bucket:network-restrictions": not-null
```

But it looks like the only documented filter is `missing-policy-statement` which from what I can tell can only look at the SID?

Is there any way to achieve what I'm looking to do right now?

**Comment by kapilt** [comment]
feels like we should extend missing-statement to support this sort of filter, perhaps even rename as policy-statement and use across resources with embedded iam policies.

**Comment by audioboxer217** [comment]
I have a client with a need for this functionality. Was there ever any update on this ticket?

**Comment by audioboxer217** [comment]
Update for anyone with a similar situation that ends up here.  After editing my last comment about finding the inverse of what I needed I decided to play around with the `not` filter to achieve what I wanted.  So far, this seems to be working well:

```yaml
policies:
- name: enforce-bucket-tls-1_2
  resource: aws.s3
  filters:
  - not:
    - type: has-statement
      statements:
      - Effect: Deny
        Principal: "*"
        Action: "s3:*"
        Resource:
        - arn:aws:s3:::{bucket_name}/*
        - arn:aws:s3:::{bucket_name}
        Condition:
          NumericLessThan:
            s3:TlsVersion: "1.2"
  actions:
  - Sid: EnforceTLSversion
    Effect: Deny
    Principal: "*"
    Action: ["s3:*"]
    Resource:
    - arn:aws:s3:::{bucket_name}/*
    - arn:aws:s3:::{bucket_name}
    Condition:
      NumericLessThan:
        s3:TlsVersion: 1.2
```
