### ISSUE TITLE
multiple resource not working 

### ISSUE THREAD

**Issue by shirishshukla** [cloud-custodian/cloud-custodian#4445]
@kapilt , am trying for multiple resources in single call by taking below as reference but not working 
 Ref: https://github.com/cloud-custodian/cloud-custodian/issues/1244

```
policies:
  - name: all_if_lb
    resource: [elb, app-elb]
    description: All internet-facing LB
    filters:
      - Scheme: internet-facing

```

Error:

> On instance['resource']:
>     ['elb', 'app-elb']
>  {'name': 'ELB_IF', 'resource': ['elb', 'app-elb'], 'description': 'Report all ELB with internet-facing schema', 'filters': [{'Scheme': 'internet-facing'}]} is not valid under any of the given schemas
> Failed validating 'anyOf' in schema['properties']['policies']['items']:
>
