### ISSUE TITLE
AWS ASG Invalid filter - Can't use as a periodic Lambda 

### ISSUE THREAD

**Issue by zagaria** [cloud-custodian/cloud-custodian#4446]
Hello.

I want to use policy
```
policies:
  - name: asg-invalid-config
     resource: asg
     filters:
       - invalid
```

but as an AWS Lambda.

When I added `mode` to policy and run `custodian validate policy.yml`, I got `invalid-config makes too many queries to be run in lambda` but for another filters (except invalid) is ok. 

Is it possible to use with AWS ASG for check invalid config? 

Manual run is correct. 

Thanks for answer!

Policy with `mode`:
```
policies:
  - name: asg-invalid-config
    resource: asg
    mode:
       type: periodic
       schedule: "cron(0 12 * * ? *)"
    filters:
      - invalid
```
