### ISSUE TITLE
Exception recommendations

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4478]
We run c7n-org and are wondering how others handle exceptions with their policies.  Sure we can change the accounts.yml file but what is there was an instance and not account exception to deal with.  Is this something we can include in the policy.  Using the below as an example.  Thanks for any thoughts we can share.

```
policies:
  - name: custodian_public_instance_check
    resource: ec2
    filters:
      - type: value
        key: PublicIpAddress
        op: ne
        value: null
    actions:
      - stop
      - type: tag
        key: custodian_public_instance_check
        value: “BISG....Instance stopped due to PublicIpAddress not allowed”
```

**Comment by kapilt** [comment]
You handle exceptions via adding a filter, that filters out the approved exceptions. ie for ec2 by ami, subnet, tag, instance id, security group, etc (note without additional iam considerations, tags are mutable). You can also source value lists from s3 json/csv files (or any url really) with values_from syntax on a value filter.

wrt to account exceptions, you can use account and policy tags to run a subset of policies across a subset of accounts. there's some additional work being done here on conditions for policy execution which will genericize this a bit more to include setting policy execution conditions on account ids etc.

**Comment by martinklie** [comment]
Thanks.  The below works.  Can we please point to where I can find an instance id  example.
policies:
  - name: custodian_public_instance_check
    resource: ec2
    filters:
      - type: value
        key: PublicIpAddress
        op: ne
        value: null
      - "tag:Public": absent
    actions:
      - stop
      - type: tag
        key: custodian_public_instance_check
        value: “BISG....Instance stopped due to PublicIpAddress not allowed”

**Comment by kapilt** [comment]
use triple quotes around policies to get better formatting in github comments

```yaml
type: value
key: InstanceId
value: [i-abc, i-123, i-456]
op: not-in
```
