### ISSUE TITLE
Azure - Resource tagging for App service plans not functioning

### ISSUE THREAD

**Issue by justinhauer** [cloud-custodian/cloud-custodian#4494]
it looks like the action of tagging was removed from app service plans in #4154 - was this intentional? I use the following policy which now does not work: 
```
vars:
  email-notify: &email-notify
  - type: notify
    template: my_default.html
    priority_header: '2'
    to:
      - me@company.com
    transport:
      type: asq
      queue: https://storageQueue

  schedules:
    mode: &azure-12h
      type: azure-periodic
      schedule: 0 0 */12 * * *
      execution-options:
          output_dir: azure://storage_Queue
  tag-sets:
    - contact-missing: &contact-missing
      - tag:OwnerContact: absent
      - tag:OwnerContact: empty
    - env-product-owner-tags: &env-product-owner-tags
      - tag:Environment: empty
      - tag:Product: empty
      - tag:Owner: empty
-policies:
- name: ownercontact-absent-appserviceplan
  mode: *azure-12h
  resource: azure.appserviceplan
  filters:
  - or: *contact-missing
  actions:
  - type: tag
    tags:
      OwnerContact: ''
```
This results in an error of: 
```
c7n.exceptions.PolicyValidationError: Failed to validate policy ownercontact-absent-appserviceplan
 Error on policy:ownercontact-absent-appserviceplan resource:azure.appserviceplan
{'type': 'tag', 'tags': {'OwnerContact': ''}} is not valid under any of the given schemas

Failed validating 'anyOf' in schema[198]['allOf'][1]['properties']['actions']['items']:
    {'anyOf': [{'$ref': '#/definitions/actions/azure.delete'},
               {'$ref': '#/definitions/actions/azure.lock'},
               {'$ref': '#/definitions/actions/azure.logic-app'},
               {'$ref': '#/definitions/actions/azure.notify'},
               {'$ref': '#/definitions/resources/azure.appserviceplan/actions/resize-plan'},
               {'$ref': '#/definitions/actions/azure.webhook'},
               {'enum': ['notify',
                         'webhook',
                         'resize-plan',
                         'logic-app',
                         'lock',
                         'delete']}]}
```
