### ISSUE TITLE
aws - hub-action for ec2 resource failing on snapshot action

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#4501]
Attempt to invoke snapshot failing with error "AttributeError: 'EC2' object has no attribute 'create_snapshots' "

Full cloudwatch log at https://gist.github.com/4fddbc43d3965bade34df5590d1b0edb

Policy was very close to the example at https://cloudcustodian.io/docs/aws/topics/securityhub.html, except the "name: null" was not used due to getting an error on the null.

Actual policy
```
policies:
  - name: DenySnapStop
    resource: ec2
    description: Deny all access by removing Instance Profile, Snapshop the volumes, and Stop the Instance
    mode:
        type: hub-action
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        # packages: [botocore, boto3, urllib3]
    actions:
        # Deny All Access
      - type: set-instance-profile
        #name: 
        # snapshot the disk for forensics
      - type: snapshot
        copy-tags: [Name]
        # stop the instance
      - stop
```
