### ISSUE TITLE
Security group and network acl limitation

### ISSUE THREAD

**Issue by ryanash999** [cloud-custodian/cloud-custodian#4542]
version = 0.8.41.0

**Goal**: Identify network-acl which DO NOT have a deny statement similar to this:

```
    "Entries": [
      {
        "CidrBlock": "0.0.0.0/0",
        "Egress": false,
        "PortRange": {
          "From": 22,
          "To": 22
        },
```
Attempted policy:
```
policies:
  - name: network-acl
    description: network-acl
    resource: aws.network-acl
    filters:
      - not:
        - and:
          - type: value
            key: Entries[].RuleAction
            op: in
            value: deny
            value_type: swap
          - type: value
            key: Entries[].Egress
            op: in
            value: false
            value_type: swap
          - type: value
            key: Entries[].PortRange.From
            op: in
            value: 22
            value_type: swap
          - type: value
            key: Entries[].PortRange.To
            op: in
            value: 22
            value_type: swap
          - type: value
            key: Entries[].CidrBlock
            op: in
            value: 0.0.0.0/0
            value_type: swap
```

**Result:**  The filters are all being applied across the whole network-acl Entities list and thus I am matching on any NACL which matches but it isn't matching a single entity, rather various NACL rules

Question/Issue: I cannot create policies which find NACLS which include, or do not include, a given rule.  This same issues applies when trying to look at security groups.  

If there is a different way to format this policy and get the expect results, please let me know.
