### ISSUE TITLE
account-service-limits hits CaseCreationLimitExceeded if 

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#4569]
Policy

```
policies:
  - name: account-service-limits
    resource: account
    mode:
      type: periodic
      schedule: "cron(0 5 * * ? *)" # daily at 5 AM UTC
      role: ${role_arn}
      tags:
        owner: ops
        role: cloudcustodian
    filters:
      - type: service-limit
        threshold: 50
    actions:
      - type: request-limit-increase
        percent-increase: 25
      - type: notify
        template: default
        subject: Account service limit increased
        to:
          - ops@company.com
        transport:
          type: sqs
          ...
```

Exception

```
{
  "errorMessage": "An error occurred (CaseCreationLimitExceeded) when calling the CreateCase operation: You have exceeded your limit of 10 cases per hour.",
  "errorType": "CaseCreationLimitExceeded",
  "stackTrace": [
```

Since this hit an exception, it never sent a message to SQS to notify slack or email.
