### ISSUE TITLE
AvailableIpAddressCount subnet filter throws array error 

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#4570]
```
policies:
  - name: subnet-available-ips
    resource: subnet
    filters:
      - type: value
        value: 500
        key: AvailableIpAddressCount
        op: lte
```

```
$ custodian run --cache-period=0 --region eu-west-1 alert-on-low-subnets.yml
 u'array'},
                                 u'tags': {u'type': u'object'},
                                 u'timeout': {u'type': u'number'},
                                 u'tracing_config': {u'type': u'object'},
                                 u'type': {u'enum': [u'asg-instance-state']}},
                 u'required': [u'type'],
                 u'type': u'object'},
                {u'additionalProperties': False,
                 u'properties': {u'concurrency': {u'type': u'integer'},
                                 u'dead_letter_config': {u'type': u'object'},
                                 u'environment': {u'type': u'object'},
                                 u'execution-options': {u'type': u'object'},
                                 u'function-prefix': {u'type': u'string'},
                                 u'kms_key_arn': {u'type': u'string'},
                                 u'layers': {u'items': {u'type': u'string'},
                                             u'type': u'array'},
                                 u'member-role': {u'type': u'string'},
                                 u'memory': {u'type': u'number'},
                                 u'packages': {u'items': {u'type': u'string'},
```
