### ISSUE TITLE
Azure - resourcegroup - Cost reporting

### ISSUE THREAD

**Issue by jomalsan** [cloud-custodian/cloud-custodian#4597]
The cost filter on Azure Resource Groups is returning different groups depending on the time filter in an unexpected manner. If a resource group meets the cost threshold for "WeekToDate", I would also expected it to be returned in "MonthToDate" and "TheLastMonth" as it is in the Azure Portal.

Example of resources returned by week to date:
```yaml
policies:
  - name: resource-groups-cost
    resource: azure.resourcegroup
    filters:
      - type: cost
        timeframe: WeekToDate
        op: gt
        value: 1
```

Return:
```json
[
  {
    "id": "/subscriptions/xxxxxxxx/resourceGroups/rg1",
    "name": "rg1",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "location": "westus2",
    "tags": {},
    "type": "Microsoft.Resources/subscriptions/resourceGroups",
    "c7n:cost": {
      "PreTaxCost": 2.07350240249811,
      "Currency": "USD",
      "c7n:MatchedFilters": [
        "PreTaxCost"
      ]
    }
  },
  {
    "id": "/subscriptions/xxxxxxxx/resourceGroups/rg2",
    "name": "rg2",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "location": "westus2",
    "tags": {},
    "type": "Microsoft.Resources/subscriptions/resourceGroups",
    "c7n:cost": {
      "PreTaxCost": 8.6880269008,
      "Currency": "USD",
      "c7n:MatchedFilters": [
        "PreTaxCost"
      ]
    }
  }
]
```

Example using "TheLastMonth":
```yaml
policies:
  - name: resource-groups-cost
    resource: azure.resourcegroup
    filters:
      - type: cost
        timeframe: TheLastMonth
        op: gt
        value: 1
```

Returns:
```json
[
  {
    "id": "/subscriptions/xxxxxxxx/resourceGroups/rg3",
    "name": "rg3",
    "properties": {
      "provisioningState": "Succeeded"
    },
    "location": "westus2",
    "tags": {},
    "type": "Microsoft.Resources/subscriptions/resourceGroups",
    "c7n:cost": {
      "PreTaxCost": 4.890648310180434,
      "Currency": "USD",
      "c7n:MatchedFilters": [
        "PreTaxCost"
      ]
    }
  }
]
```

When doing the call for "TheLastMonth" I would expect that all three of the resource groups would appear in the response.

Further context: At the time of running, rg1 and rg2 were two weeks old

I have not tested the cost functionality on other azure resources
