### ISSUE TITLE
AWS check if IAM instance profile has policy

### ISSUE THREAD

**Issue by aliciasteen** [cloud-custodian/cloud-custodian#4600]
I am working on attached a specific policy to all IAM instance profiles that do not have it but cannot work it out. 

With the iam-role resource you can filter on no-specific-managed-policy but this is not an option on the iam-profile resource. Is there a way you can pass a list of iam-profile role-ids as a filter to the iam-role resource?

My preferred implementation would look something like this:
```
policies:
  - name: role
    resource: iam-profile
    filters:
      - type: used
        state: true
      - type: no-specific-managed-policy
        value: policy
```
or
```
policies:
  - name: role
    resource: iam-role
    filters:
      - type: value
         op: in
         value: iam-profile.Role.RoleName
      - type: no-specific-managed-policy
        value: policy
```
