### ISSUE TITLE
azure - can not provide only 'count' on resize-plan action for app service plan

### ISSUE THREAD

**Issue by erwelch** [cloud-custodian/cloud-custodian#4606]
Current: 
Policy fails if only providing count for resize:
```
            resource: azure.appserviceplan
           actions:
              - type: resize-plan
                size:
                    count: 2
```

Expected:
Policy passes and can resize with only count field.
