### ISSUE TITLE
check-permissions filter fails to match if Resource in IAM policy is anything other than "*"

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#4612]
When a ec2 resource policy includes the fillter:
```
      - type: check-permissions
        match: allowed
        match-operator: or
        actions:
          - s3:GetObject
          - s3:* 
```
it will fail to match if the Resource in the relevant IAM policy is anything other than "*", such as
```
       {

            "Effect": "Allow",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::*/*"
        }
````
