### ISSUE TITLE
Reverse filter results S3 resource

### ISSUE THREAD

**Issue by martinklie** [cloud-custodian/cloud-custodian#4613]
Is there a way to reverse filtered results.  We have the below sharing all buckets with a bucket policy Sid of DenyHttpAny.  What we are looking for is the opposite.  All buckets that do not have the named policy.

policies:
  - name: s3name
    resource: s3
    description: s3 buckets without encryption required
    filters:
      - type: has-statement
        statement_ids:
          - DenyHttpAny

We also came across the same with the below.  The below share results of buckets that are not AES-256 or KMS encrypted at rest.  We were hoping for the opposite

policies:
  - name: s3-bucket-not-encrypted
    resource: s3
    filters:
      - type: no-encryption-statement

Is there a filter we can add that will reverse the results?

**Comment by kapilt** [comment]
we have generic boolean blocks that support nesting ie.

```yaml
filters:
  - not:
       - type: has-statement
          statement_ids:
            DenyHttpAny
```
