### ISSUE TITLE
azure - ensure Event Grid mode works properly with child resources

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4617]
We have ARM and not ARM child resources. 

It looks like non-arm child resources now won't work with event triggered mode at all.

ARM resources work differently as if we run it in Pull mode (different API is used, no `c7n:parent-id` property)

**Comment by erwelch** [comment]
As an update - non-ARM resources are not supported in Event Grid, per: https://docs.microsoft.com/en-us/azure/event-grid/overview

Will add validation logic to prevent users from adding them as the `resource` in event grid mode.

**Comment by stefangordon** [comment]
We have arm child resources as well which are not supported, and should be easy to fix.  Namely storage container.

```
  - name: storage-container-public
    description: |
      Find all storage container with public access
    resource: azure.storage-container
    mode:
      type: container-event
      events: [{
        resourceProvider: 'Microsoft.Storage/storageAccounts/blobServices/containers',
        event: 'write'
        }]
```

**Comment by justinhauer** [comment]
@stefangordon what is the status of this? 

I just deployed the following policy:
```
policies:
  - name: azure-auto-tag-creator-resources
    description: |
      Tag all arm resources of the VMs, VNETs and Storage accounts with the
      'Creator Email' tag; looking up to 10 days prior.
    resource: azure.armresource
    mode:
      type: azure-event-grid
      events: ['VmWrite', 'StorageWrite']
    filters:
      - type: resource-type
        values:
          - Microsoft.Network/virtualNetworks
          - Microsoft.Storage/storageAccounts
          - Microsoft.Compute/virtualMachines
    actions:
     - type: auto-tag-user
       tag: CreatorEmail

```
and tried to test it out by deploying a VM. the Azure function triggered and ran with a 200, but the virtual machine wasn't tagged.

I tried this in non-event mode (just invoking from CLI) and the resource tagged successfully.

**Comment by stefangordon** [comment]
What custodian version are you running @justinhauer? 

I'd expect #5446 to have made event/pull modes work the same.

It was released ~6 days ago in 0.9.1.0.

**Comment by justinhauer** [comment]
Pulled from source on 4/29 (last thursday)and built a new virtual environment from master branch. If I should pull again and redeploy I will do so.

**Comment by justinhauer** [comment]
@stefangordon the following policy DOES work, leading me to this again its an issue with child resources under azure.armresource:
```
policies:
  - name: azure-auto-tag-creator-vm
    description: |
      Tag all arm resources of the VMs, VNETs and Storage accounts with the
      'Creator Email' tag; looking up to 10 days prior.
    resource: azure.vm
    mode:
      type: azure-event-grid
      events:
        - resourceProvider: Microsoft.Compute/virtualMachines
          event: write
    filters:
      - "tag:CreatorEmail": null

    actions:
     - type: auto-tag-user
       tag: CreatorEmail
```
