### ISSUE TITLE
azure - value filter - add support for storage blob using value_from option  

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4629]
Currently, we have support for using a `value_from` option targeting a URL or an S3 bucket. Let's add support for Azure Blob Store.

### Acceptance Criteria
We can use azure blob as a source to fetch data from for value filters.
ex: 
```
      values_from:
         url: azure://cc.blob.core.windows.net/data.json
         format: json
         expr: approved_list[].ip_address
```
