### ISSUE TITLE
VPC set-flow-log PolicyValidationError When Sending to S3

### ISSUE THREAD

**Issue by orlando-jamie** [cloud-custodian/cloud-custodian#4641]
Trying to run the following policy to configure VPC flow logs across all VPCs to the same bucket. However, it fails with 

c7n.exceptions.PolicyValidationError: DeliverLogsPermissionArn required when creating flow-logs on ....

However, according to the awscli documentation, DeliverLogsPermissionArn is not to be set when delivering to S3. Seems that it is a bug for c7n to fail the validation here. 

https://docs.aws.amazon.com/cli/latest/reference/ec2/create-flow-logs.html

```
{'type': 'set-flow-log', 'LogDestinationType': 's3', 'LogDestination': 'arn:aws:s3:::my-vpcflowlogs', 'TrafficType': 'ALL'}]}
```

``` yaml
- name: VPC-001-Enable-VPC-Flow
  resource: aws.vpc
  comment: "CIS Amazon Web Services Foundations v1.1.0 (4.3)"
  filters:
    - not:
      - type: flow-logs
        enabled: true
  actions:
    - type: notify
      transport:
        type: sqs
        region: us-east-1
        queue: https://sqs.us-east-1.amazonaws.com/{account_id}/my_custodian_log
    - type: set-flow-log
      LogDestinationType: s3
      LogDestination: arn:aws:s3:::my-vpcflowlogs
      TrafficType: ALL
```
