### ISSUE TITLE
azure - app service plan with metrics filter raise exception

### ISSUE THREAD

**Issue by stefangordon** [cloud-custodian/cloud-custodian#4676]
The metrics filter does not appear to work on App Service Plans.

"Operation return an invalid status code 'Not Found'

```
policies:
  - name: app-service-plan
    resource: azure.appserviceplan
    filters:
      - type: metric
        metric: CpuPercentage
        aggregation: average
        op: gt
        threshold: 0
        timeframe: 168
```
