### ISSUE TITLE
azure - app service plan count doesn't scale up plan

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4734]
Example:

```
policies:
  - name: test-app-plan
    resource: azure.appserviceplan
    actions:
      - type: resize-plan
        size: B1
        count: 2
```

This does scale up the plan to B1, but does not scale out to 2 workers.
