### ISSUE TITLE
not authorized to perform: lambda:GetFunction - explicit deny

### ISSUE THREAD

**Issue by saryx123** [cloud-custodian/cloud-custodian#4736]
Hi there, I seem to have a problem with deploying my first custodian control; 
s3-deny-public-object-acl-realtime fails with an explicit deny.

error log:
```
...
core/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetFunction operation: User: arn:aws:iam::1111111111:user/USERNAME is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:us-east-1:11111111111:function:custodian-s3-deny-public-object-acl-realtime with an explicit deny
```

I've attempted resolving by assigning explicit and resource:* policies, to no effect. I am running as an account administrator (but not root).

The policy i'm trying to apply is (copied it from [here](https://cloudcustodian.io/docs/aws/examples/s3denypublicobjectacls.html))
```
policies:

  - name: s3-deny-public-object-acl-realtime
    resource: s3
    mode:
      type: cloudtrail
      events:
        - CreateBucket
        - source: 's3.amazonaws.com'
          event: PutBucketPolicy
          ids: "requestParameters.bucketName"
      role: arn:aws:iam::{account_id}:role/Cloud_Custodian_Role
      timeout: 200
    description: |
      Appends a bucket policy statement to an s3 bucket when it detects
      a policy change to the bucket or a new bucket is created which
      will deny anyone except some AWS logging services from setting
      s3 objects in the bucket to public-read, public-read-write, or
      any authenticated AWS user.
    actions:
      - type: set-statements
        statements:
          - Sid: "DenyS3PublicObjectACL"
            Effect: "Deny"
            Action: "s3:PutObjectAcl"
            NotPrincipal:
               "AWS":
                   - "arn:aws:iam::111111111111:root"
                   - "arn:aws:iam::111111111111:user/logs"
                   - "arn:aws:iam::111111111111:user/logs"
                   - "arn:aws:iam::111111111111:root"
                   - "arn:aws:iam::111111111111:root"
            Resource:
               - "arn:aws:s3:::{bucket_name}/*"
               - "arn:aws:s3:::{bucket_name}"
            Condition:
              StringEqualsIgnoreCaseIfExists:
                 's3:x-amz-acl':
                     - "public-read"
                     - "public-read-write"
                     - "authenticated-read"
```

Please advise.
