### ISSUE TITLE
Possible to use value of tag for numeric field?

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#4770]
I'm attempting to use the value of a tag (hour-tag) as the value for the hours field in mark-for-op:

```
    actions:
       - type: mark-for-op
         tag: maid_status_24
         op: stop
         hours: "tag:hour-tag"
```

This fails validation.    Can you confirm if this is possible?
