### ISSUE TITLE
config compliance filter supporting wildcards for name matching

### ISSUE THREAD

**Issue by mo-saeed** [cloud-custodian/cloud-custodian#4772]
I have problem creating policy for checking config rules compliance, I have automation with CF stackset which creates a config rules with name like that "StackSet-CheckForS3ServerSideEncr-837664hffy3" the last part of the string is just random string generated for each account now i am trying to use this policy but it doesn't work with regex
```
   - name: s3-security-non-compliant
    resource: s3
    filters:
      - type: config-compliance
        rules:
          - "StackSet-CheckForS3ServerSideEncr-*"
        states: [NON_COMPLIANT]
    actions:
       - <<: *notify-var
```
Any possible ways of achieving this goal ? I am using c7n-org
