### ISSUE TITLE
c7n-aws - Issue with filtering out SG rules by multiple CIDR blocks

### ISSUE THREAD

**Issue by puddleglum1904** [cloud-custodian/cloud-custodian#4834]
I have an check that I am running, that I want to alert me on any security group ingress rules in my AWS account that are over ports 22 or 3389 (SSH/RDP), with the exception of rules that have a source IP/subnet that falls within a list of "approved" CIDR blocks.

Check example A:
```
    resource: security-group
    filters:
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 192.168.0.0/16
        Ports:
          - 22
          - 3389
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 10.0.0.0/8
        Ports:
          - 22
          - 3389
    actions:
      - type: notify
        column_names: GroupName,MatchedIpPermissions
        to:
          - {{ email }}
        transport:
          type: sqs
          queue: {{ sqs_queue_url }}
```

This check works as intended, and sends me an alert with a list of SGs and their associated SSH/RDP ingress rules, excluding any that have a source IP or subnet that falls within either 10.0.0.0/8 or 192.168.0.0/16. 
However, the issue arises if I add another CIDR block via a third ingress filter.

Check example B:
```
    resource: security-group
    filters:
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 192.168.0.0/16
        Ports:
          - 22
          - 3389
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 10.0.0.0/8
        Ports:
          - 22
          - 3389
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 172.16.0.0/16
        Ports:
          - 22
          - 3389
    actions:
      - type: notify
        column_names: GroupName,MatchedIpPermissions
        to:
          - {{ email }}
        transport:
          type: sqs
          queue: {{ sqs_queue_url }}
```

Example B now sends me an alert with all rules originating from IPs/subnets within 172.16.0.0/16, but now includes SG rules that originate from IPs/subnets within 10.0.0.0/8.

I need to find a way to chain together a list of CIDR blocks, and exclude any rules that contain IPs/subnets that are contained within any of these CIDR blocks. Right now, it appears my limit is two CIDR filters.

**Comment by puddleglum1904** [comment]
Tagging @kapilt, since we were discussing this via gitter.

**Comment by kapilt** [comment]
thanks for reporting the issue, traveling for the next few days, but another piece of helpful information would be an sanitized describe output for a security-group that erroneously triggers on example B. 

alot of the confusion around ingress filters is that they operate on any permission in a security-group, not per se chained to the permissions that matched the previous one. enabling an option on the ingress filters to only look at the previously matched may allow for these constructions more easily.

**Comment by puddleglum1904** [comment]
@kapilt So I've been running some additional tests with stripped down SGs, and I don't think it's an issue with 3 or more filters but rather (like you indicated) not taking into consideration previous filter results. 

I started off with just two filters:
```
    filters:
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 192.168.0.0/16
        Ports:
          - 22
          - 3389
    filters:
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 10.0.0.0/8
        Ports:
          - 22
          - 3389
```

I then created two basic SGs:

```
{
    "SecurityGroups": [
        {
            "Description": "test",
            "GroupName": "192.168.0.0/16",
            "IpPermissions": [
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "192.168.48.0/24"
                        }
                    ],
                    "ToPort": 22,
                },
                {
                    "FromPort": 3389,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "192.168.48.0/24"
                        }
                    ],
                    "ToPort": 3389,
                }
            ],
            "OwnerId": "",
            "GroupId": "sg-",
            "VpcId": "vpc-"
        },
        {
            "Description": "test",
            "GroupName": "10.0.0.0/8",
            "IpPermissions": [
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "10.10.0.0/16"
                        }
                    ],
                    "ToPort": 22,
                },
                {
                    "FromPort": 3389,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "10.10.10.0/24"
                        }
                    ],
                    "ToPort": 3389,
                }
            ],
            "OwnerId": "",
            "GroupId": "sg-",
            "VpcId": "vpc-"
        }
    ]
}
```

Running the check, no alerts on either as expected. 

I then added a third filter and third SG:
```
    filters:
      - type: ingress
        Cidr:
          op: not-in
          value_type: cidr
          value: 172.16.0.0/16
        Ports:
          - 22
          - 3389


        {
            "Description": "test",
            "GroupName": "172.16.0.0/16",
            "IpPermissions": [
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "172.16.10.0/24"
                        }
                    ],
                    "ToPort": 22,
                },
                {
                    "FromPort": 3389,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "172.16.10.0/24"
                        }
                    ],
                    "ToPort": 3389,
                }
            ],
            "OwnerId": "",
            "GroupId": "sg-",
            "VpcId": "vpc-"
        }
```

Running the check, and again no alerts on any SGs. (yay) But then the complications come when I start combining rules in these SGs. Added the following rule to my 3rd SG:

```
        {
            "Description": "test",
            "GroupName": "172.16.0.0/16",
            "IpPermissions": [
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "172.16.10.0/24"
                        }
                    ],
                    "ToPort": 22,
                },
                {
                    "FromPort": 3389,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "172.16.10.0/24"
                        }
                    ],
                    "ToPort": 3389,
                },
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "10.10.10.0/24"
                        }
                    ],
                    "ToPort": 22,
                }
            ],
            "OwnerId": "",
            "GroupId": "sg-",
            "VpcId": "vpc-"
        }
```
Ran the check again, and now I receive an alert for the 3rd SG, but only for the 10.10.10.0/24 rule. (which should've been filtered out by the 10.0.0.0/8 filter).
I went back down to two filters (removing the filter for 172.16.0.0/16) and removed the 3rd SG, and modified the second SG with the following rule:
```
        {
            "Description": "test",
            "GroupName": "10.0.0.0/8",
            "IpPermissions": [
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "10.10.0.0/16"
                        }
                    ],
                    "ToPort": 22,
                },
                {
                    "FromPort": 3389,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "10.10.10.0/24"
                        }
                    ],
                    "ToPort": 3389,
                },
                {
                    "FromPort": 22,
                    "IpProtocol": "tcp",
                    "IpRanges": [
                        {
                            "CidrIp": "192.168.0.0/24"
                        }
                    ],
                    "ToPort": 22,
                }
            ],
            "OwnerId": "",
            "GroupId": "sg-",
            "VpcId": "vpc-"
        }
```

Run the check, and I receive an alert for this second SG but only for the 192.168.0.0/24 rule (which should've been filtered out by the first filter).

As a last test, I removed the 10.0.0.0/8 filter from the check and kept the SGs the same. Run the check, and now I get alerted on the second SG but for the 10.x.x.x rules and not for the 192.168.0.0/24 rule, which I would expect. 

So my conclusion so far is that it works completely as needed if I have only one filter, but adding any additional filters will cause it to trigger incorrectly on mismatched rules, even if ALL of the SG rules configured should be filtered out.

**Comment by puddleglum1904** [comment]
As a additional note, I did try adding an `- and:` operator when I was down to two filters but had the same result. (I know the "and" should be implicit, but figured I'd just try it anyway)

**Comment by rams3sh** [comment]
Until this gets fixed , for others who may have this issue, one can solve this using regex foo. Regex route might be little dirty and complex , but it gets the job done.

Posting a sample policy here for an idea , so that it may help others.

Clubbing all the intended IP matches as one complex regex is the key here. If you have multiple CIDRs / IPs with no progressive pattern  , then your regex may look more dirty with each case to be written as `(<pattern_1> | <pattern_2>)` (or) case  .

Sample Policy : 
```yaml
vars: 
    private_ipv4_range_regex: &private_ipv4_range_regex
        "^(10(\\.(25[0-5]|2[0-4][0-9]|1[0-9]{1,2}|[0-9]{1,2})){3}|((172\\.(1[6-9]|2[0-9]|3[01]))|192\\.168)(\\.(25[0-5]|2[0-4][0-9]|1[0-9]{1,2}|[0-9]{1,2})){2})\\/((3[0-2])|((1|2|)[0-9]))$"

    # The below link was a life saver in finding the negative matches of the above private range. This can be used in cases where you know the known good and want to find any thing that does not follow the good's pattern.
    # https://www.kite.com/python/answers/how-to-do-negative-pattern-matching-using-regular-expressions--in-python
    not_private_ipv4_range_regex: &not_private_ipv4_range_regex
        "^(?!^(10(\\.(25[0-5]|2[0-4][0-9]|1[0-9]{1,2}|[0-9]{1,2})){3}|((172\\.(1[6-9]|2[0-9]|3[01]))|192\\.168)(\\.(25[0-5]|2[0-4][0-9]|1[0-9]{1,2}|[0-9]{1,2})){2})\\/((3[0-2])|((1|2|)[0-9]))$)"

policies:
   - name: ec2_securitygroups_with_non-http_ports_exposed_to_public_ips
     resource: security-group
     filters:
        - type: ingress
          OnlyPorts: [ 80,443 ]
          Cidr:
           # Basically matches Public IPs (including 0.0.0.0) 
            value: *not_private_ipv4_range_regex 
            op: regex-case
        - type: ingress
          OnlyPorts: [ 80,443 ]
          # IPV6 exists as a different ingress permission , hence can be handled separately.
          CidrV6:
            value_type: cidr
            value: "fc00::/7"
            op: not-in

```
