### ISSUE TITLE
azure - container host - multiple executions in an hour overwrites log data in blob

### ISSUE THREAD

**Issue by jomalsan** [cloud-custodian/cloud-custodian#4837]
I am running an example policy in a container host that runs every 10 minutes to generate log data:
```yaml
policies:
- name: sample-policy
  description: A sample policy used to test Azure Container Host is Kubernetes
  resource: azure.storage
  mode:
    type: container-periodic
    schedule: "*/10 * * * *"
  filters:
  - type: value
    key: name
    op: eq
    value: cataysa
```

When looking at the logs saved to blob storage, the log files are all created on the hour and then last modified on the 50 minute mark. For example:
```
Blob Name: {sub_id}/sample-policy/2019/09/20/04/metadata.json.gz
Creation Time: 9/19/2019, 9:00:06 PM
Last Modified: 9/19/2019, 9:50:03 PM
```
The logs for the 5 preceding executions have been deleted. Further evaluation is needed to determine if this also happens in Azure Functions mode, and when both Functions and container host are operating in Event Mode
