### ISSUE TITLE
aws - Tagging Launch time of resource

### ISSUE THREAD

**Issue by jkovolski** [cloud-custodian/cloud-custodian#4852]
When using a policy similar to below, the tag 'Launched' will show the value of the date the lambda was deployed not the time the EC2 was created.  It might be interpolating the time when we go to deploy, which means its gets statically rendered into the lambda, instead of being runtime interpreted there.

```
policies:

- name: ec2-auto-tag-launchtime
  resource: ec2
  description: |
    Triggered when a new EC2 Instance is launched. Adds the Launch time
    with the value of the current date and time for Compliance auditing. 
  mode:
    type: cloudtrail
    events:
      - RunInstances
    role: arn:aws:iam::{account_id}:role/CloudCustodianRole
    member-role: arn:aws:iam::{account_id}:role/CloudCustodianRole
  actions:
    - type: tag
      key: Launched
      value: "{now:%Y-%m-%d}"
```
