### ISSUE TITLE
AWS-Custodian does not support resource: iam-identity-providers

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#4871]
I am trying to put some custodian policies around identity providers (AWS) and looks like the resources is not defined for that.

policies:

- name: sec-n-iam-identity-provider-check
  comment: |
    Find IAM Identity Providers other than GOOD.
    This will provide you with the list of all identity providers deployed in all AWS accounts.
    This custodian is used to support and automate the access control domain for security control validation. 
  resource: ?????????????
  filters:
    - type: value
      key: "responseElements.sAMLProviderList[].arn"
      value: GOOD
      op: ne
  mode:
    type: cloudtrail
    events:
      - source: iam.amazonaws.com
        event: ListSAMLProviders
        ids: "responseElements.sAMLProviderList.arn"
    execution-options:
      output_dir: s3://xxxxxxx/xxxxxxxxxx/xxxxxx/xxxxxxx/xxxxxx/{account_id}/
    tags: *sec-tags
  actions:
    - type: notify
      action_desc: |
        Custodian has identified identity-provider other than GOOD 
        Please investigate further with IAM team
      subject: "IAM Security - SAML Identity Provider other than GOOD "
      to: ["slack"]
      transport:
        type: sqs
        queue: c7nMessageQueue
      violation_desc: |
        Custodian has detected another SAML identity provider which is not authorized.
        GOOD is the only authorized SAML identity provider.

**Comment by kapilt** [comment]
fwiw, there's an extant pull request for saml/openid providers as filters on the account.

**Comment by aakifshaikh** [comment]
What filter should I use from aws.account. The below policy is still not working
```
policies:

- name: sec-n-iam-identity-providers-saml-check
  resource: aws.account
  comment: |
    Identify all SAML Identity Providers.
  filters:
    - type: event
      value: abcd
      key: "responseElements.sAMLProviderList.arn"
      op: ne
  mode:
    schedule: "rate(10 minutes)"
    type: periodic
    execution-options:
      output_dir: s3://x/x/x/x/x/x/x
    tags: *sec-tags
  actions:
    - type: notify
      action_desc: |
        Custodian has found SAML identity provider other than ABCD !
      subject: "Identity Provider is not ABCD"
      to: ["slack"]
      transport:
        type: sqs
        queue: c7nMessageQueue
      violation_desc: "SAML Identity Provider is other than ABCD."
```
