### ISSUE TITLE
c7n-mailer not showing Account number (AWS)

### ISSUE THREAD

**Issue by gfog-floqast** [cloud-custodian/cloud-custodian#4887]
Using both Slack and email notifications with c7n-mailer and c7n-org and I am unable to see the Account field getting populated.

My mailer.yml file is as follows:
```
queue_url: https://sqs.us-west-2.amazonaws.com/<aws_account_id>/cloud-custodian
role: arn:aws:iam::<aws_account_id>:role/cloud-custodian
from_address: <email_address_authed_from_ses>
region: us-west-2
```

My policy is as follows:
```
policies:
  - name: delete-users-without-mfa
    description: |
      Notifies on Users who do not have MFA enabled
    resource: aws.iam-user
    mode:
      type: periodic
      schedule: rate(1 day)
      role: cloud-custodian
    filters:
      - type: mfa-device
        value: empty
    actions:
      - type: notify
        slack_template: slack_default   # setting this to just 'slack' will send messages to sqs, but will not get delivered to slack, don't know if that might be a clue
        violation_desc: "Users without MFA Enabled"
        action_desc: "Please enable MFA on these IAM Users"
        template_format: 'html'
        priority_header: '2'
        subject: 'Users without MFA Enabled'
        to:
          - https://hooks.slack.com/services/<slack_webhook>
        owner_absent_contact:
          - <email_address_authed_from_ses>
        transport:
          type: sqs
          queue: "https://sqs.us-west-2.amazonaws.com/{account}/cloud-custodian"

```

My email notifications appear as follows:
```
The following aws.iam-user resources

    <aws_user_names>

in account: 

Matched policy:

actions:
- priority_header: '2'
  subject: testing the c7n mailer
```

And my Slack notification looks as follows:
```
CustodianAPP 4:40 PM
Custodian
Resources
<aws_user_names>
Account
Region
us-west-2
Violation Description
Users without MFA Enabled
Action Description
Please enable MFA on these IAM Users
```

I have tried multiple iterations and with multiple policies and am unable to get the Account to appear. Since we're using this across several accounts it is difficult for us to know which account the alerts are for.

my custodian version is `0.8.45.0` and running Lambda runtime of Python 3.7

**Comment by kapilt** [comment]
do you have the iam account alias for your accounts set? you also didn't show your mailer template so its unclear how your referencing/inserting account into the message. in jinja2 mailer templates {{account}} shows the iam account alias, but that needs to be setup else it will be an empty string. additionally you can use {{account_id}} though that lacks readability.

**Comment by gfog-floqast** [comment]
Thanks for your quick response, I'm just using the default slack template, so not using anything custom for the mailer template.

We do not have account aliases set up for all our accounts so I added the alias and now I'm not getting any alerts. 

In looking at the CW logs I'm seeing the following error: `botocore.exceptions.ClientError: An error occurred (InvalidAddress) when calling the SendMessage operation: The address https://us-west-2.queue.amazonaws.com/ is not valid for this endpoint.`

When I delete the alias the alerts start coming back through again. It's odd that adding the alias would cause the queue url to switch from `https://sqs.us-west-2.amazonaws.com/<aws_account_id>/cloud-custodian` to `https://us-west-2.queue.amazonaws.com/`? I tried updating my queue_url references to match this other format but received the same response.

Looks like it's perhaps related to this aws-cli issue: https://github.com/aws/aws-cli/issues/1715

Apologies for my confusion on this.

**Comment by kapilt** [comment]
you shouldn't have {account} in your queue url, use {account_id} instead or if your using a single queue across accounts just have the verbatim value for queue url.

**Comment by gfog-floqast** [comment]
so the {account} in my transport.queue is actually an account var:
```
accounts:
- account_id: '<aws_account_id>'
  name: FQ1
  regions:
  - us-west-2
  role: arn:aws:iam::<aws_account_id>:role/Ops
  vars:
    account: <aws_account_id>
    environment: env1
    region: us-west-2
  tags:
  - team:TeamName
```

My guess is that I'm attempting to pass a var that is already being declared so it's not accepting my var.

At any rate, updated transport.queue to use {account_id} fixed the issue and I'm now seeing the Account Alias getting populated in my Slack notification. 

Thanks for your help, it's been very...helpful.
