### ISSUE TITLE
invoke-lambda should allow custom parameters to send to the lambda

### ISSUE THREAD

**Issue by YpsiBe** [cloud-custodian/cloud-custodian#4890]
Hello,

First thank you for this wonderful tool ! I have a question regarding the invoke-lambda action. For now, it seems like the only parameters provided to the lambda are the one described in the documentation: 
 - resources / collection of resources
 - policy / policy that is invoke the lambda
 - action / action that is invoking the lambda
 - event / cloud trail event if any
 - version / version of custodian invoking the lambda

While it is fine most of the case, there are use cases where I would need more information. I am using c7n-org and I would need the account ID (or even some variables defined in the accounts.yml) should be passed to the invoked lambda  (i.e. to assume a role in the lambda to take custom actions in the account that matched policy)

I haven't found a way to do it for now. Is there a way to achieve this behavior ? If not, is there a way around it ?

Thank you for your time.

**Comment by kapilt** [comment]
having a parameters mapping on the action that we pass through sounds good.

**Comment by ennkayhub** [comment]
@YpsiBe Were you able to make it work? I want to pass the 'policy name' as a param to the lambda I am trying to invoke.

**Comment by phzietsman** [comment]
The way we pass additional data to the invoked lambda is by using the `vars` on the action:

```yml
  ...
  actions:
    - type: invoke-lambda
      function: "arn:aws:lambda:eu-west-1:123456789012:function:func"
      vars: 
        stuff:
          more_stuff: hello
          more_more_stuff: world
```
