### ISSUE TITLE
AWS ingress filter for UserIdGroupPairs lacks documentation

### ISSUE THREAD

**Issue by iantype** [cloud-custodian/cloud-custodian#4915]
There is no documentation/examples for UserIdGroupPairs using the security-group resource ingress filter. I have tried a number of things with no success.

**Comment by kapilt** [comment]
cloud custodian is a cloud management tool, it does require understanding the underlying cloud infrastructure thats being managed. there are numerous examples for ingress filters in the documentation https://cloudcustodian.io/docs/aws/resources/security-group.html#aws-security-group-filters-ingress but its not exhaustive of all permutations and attributes, because they naturally follow the same usage patterns. 

perhaps a better start would be explaining what your trying to do and how your trying to do.

**Comment by iantype** [comment]
If you create a `-not:` `Cidr:`filter with a list of IPs you can run into issues because it declares nested SGs as not matching that pattern, so I am trying to understand how can I add additional filter similar to `Cidr:`, which the documentation's schema including `UserIdGroupPairs:` made me assume it had similar conveniences:

```- type: ingress
  Ports: [22, 3389]
  Cidr:
    value:
      - "0.0.0.0/0"
      - "::/0"
```

```
- type: ingress
     UserIdGroupPairs:
        value:
          - UserId: "my-account-d"
          -GroupId: "sg-other"
```

I haven't been able to find filter examples with digging into objects with what I think would be a very common usecase, digging out nested SGs on AWS, something like:

```
     - type: value
            key: IpPermissions[].UserIdGroupPairs[].UserId
             value: "my-account-d"
```

Which would get you started, or even:

```
     - type: value
            key: IpPermissions[].UserIdGroupPairs[].UserId
             value: present
```

Since that key should only exist when a nested SG rule exists, otherwise `UserIdGroupPairs` is just empty.

**Comment by iantype** [comment]
One solution that should work is, by way of this doc: https://cloudcustodian.io/docs/filters.html

```
 - type: value
#   the jmespath query against a resources.json for resource type security-group   
#        [].IpPermissions[].UserIdGroupPairs[].UserId
            key: IpPermissions[].UserIdGroupPairs[].UserId
            op: in
            value:
              - my-account-id
              - some-peered-account-id
```

**Comment by jsmith02** [comment]
@kapilt, I have a similar issue I'm running into I'll do my best to describe it below.


- I have Security Groups in AWS that contain Security Group values in the inbound rules section. 
- I am trying to write a policy that will show me all the:

1. Security Groups that match a regex pattern. 
2. Security Groups owned by specific set of values. 
3. Security Groups that are missing a specific set of security groups for their ingress. 

 I have solved 1 and 2, but what I am running into and issue when trying to drill down into UserIdGroupPairs as outlined in the existing documentation. 

I took the output from my dry run and was able to return the correct list of values using the second JMESPath query in the code block below

https://jmespath.org/

```
 - type: value
    key: IpPermissions[].UserIdGroupPairs[].UserId
    op: in
    value:
      - my-account-id
      - some-peered-account-id

#JMESPATHQUERY
 - type: value
    key: [].IpPermissions[].UserIdGroupPairs[].UserId
    op: in
    value:
      - my-account-id
      - some-peered-account-id
```

With Cloud Custodian though, the key evaluation won't allow for the JMES query and the former does not return anything though per the documentation I believe it should. 

The schema provided in Cloud Custodian [docs](https://cloudcustodian.io/docs/aws/resources/security-group.html#aws-security-group-filters-ingress), and yourself indicate that they should follow the same usage pattern. 

However when I attempt to imitate using any of the patterns I find in the docs, using the schema, I'm unable to return a match despite being able to match. 

I think a simple example of how to access values in Security Groups that are not Cidr Blocks would be helpful. 

Will you let me know if that doesn't help clarify?

```
    #my example
    - type: ingress
      Ports: [1521, 5432, 3306, 5444]
      UserIdGroupPairs:
        value:
          - sg-00000000000000000
          - sg-00000000000000000
        op: in
    # Example without ports that also does not return expected value
    - type: ingress
      UserIdGroupPairs:
        value:
          - sg-00000000000000000
          - sg-00000000000000000
        op: in
    - type: ingress
      UserIdGroupPairs:
        value_type: GroupId
        op: in
        value:
          - sg-00000000000000000
          - sg-00000000000000000
    #docs
   	- type: ingress
	  Ports: [22, 3389]
	  Cidr:
	    value:
	      - "0.0.0.0/0"
	      - "::/0"
	    op: in
- type: egress
  Cidr:
    value_type: cidr
    op: in
    value: x.y.z

```


```
properties:
  Cidr: {}
  CidrV6: {}
  Description: {}
  FromPort:
    oneOf:
    - $ref: '#/definitions/filters/value'
    - type: integer
  IpProtocol:
    oneOf:
    - enum:
      - '-1'
      - -1
      - tcp
      - udp
      - icmp
      - icmpv6
    - $ref: '#/definitions/filters/value'
  IpRanges: {}
  OnlyPorts:
    items:
      type: integer
    type: array
  Ports:
    items:
      type: integer
    type: array
  PrefixListIds: {}
  SelfReference:
    type: boolean
  ToPort:
    oneOf:
    - $ref: '#/definitions/filters/value'
    - type: integer
  UserIdGroupPairs: {}
  match-operator:
    enum:
    - or
    - and
    type: string
  type:
    enum:
    - ingress
required:
- type
```
