### ISSUE TITLE
Add support for waiters

### ISSUE THREAD

**Issue by MitchellJeppson** [cloud-custodian/cloud-custodian#4943]
AWS provides the ability to send a request, such as deleting as resource, then wait and block until that request has been finished. AWS calls these 'waiters'. I'm sure Azure and GCP have similar functionality. It would be nice if we could specify this behavior in the policy file.

**Comment by kapilt** [comment]
Why?

**Comment by kapilt** [comment]
Waiters are just client side polling which increases the number of api calls and execution time, it’s unclear that it has any value in a custodian policy. We do use them internal to implementations where needed, but expressing in user policy seems extraneous and with several downsides.

**Comment by MitchellJeppson** [comment]
I'm looking to delete multiple cloudformation stacks. Some of these stacks are dependent on each other so they will fail to delete if their dependent stack is not completely removed before they themselves are deleted.

**Comment by kapilt** [comment]
what's the error you see? cfn stack teardown could be quite lengthy, we can do a topological sort on the dependencies if their part of the stack description though to order them during deletion but thats not waiting on deletion, its just attempting termination in order.

**Comment by MitchellJeppson** [comment]
Using c7n there is no error. When I try to delete 2 resources where one of which depends on the other, both resources are reported as being deleted but in AWS console only one of which resources actually gets deleted. I assume a request is sent for the other but an error is returned to c7n.

**Comment by kapilt** [comment]
cloud formation stack deletes are async to the delete api call, the delete api call completes successfully to custodian , but custodian isn't waiting to verify the stack operation succeeds or not as that it could involve polling for lengthy periods of time.

**Comment by MitchellJeppson** [comment]
So would it be reasonable to implement the 'waiters' functionality in cloud custodian so that users can run actions such as deletion synchronously?

**Comment by kapilt** [comment]
I'm open to it, we'd have to restrict it out from lambda execution modes due to length of teardown exceeding lambda timeout. so this would be some form of ordered (by stack dependency) deletion of cloud formation stacks one by synchronously (or least grouped to dependency barrier), and on failure abort/error from the policy? also could you clarify the use cases/narrative you have around the stack deletion? just trying to ascertain how common/useful this usage would be.

**Comment by mithun** [comment]
@kapilt I have a use-case that can benefit from _waiters_. Here's an example policy:

```yaml
policies:
- name: my-test-policy
  resource: aws.glue-dev-endpoint
  mode:
    type: cloudtrail
    events:
    - source: glue.amazonaws.com
      event: CreateDevEndpoint
      ids: requestParameters.EndpointName
  filters:
  - type: security-config
    key: EncryptionConfiguration.CloudWatchEncryption.CloudWatchEncryptionMode
    op: ne
    value: SSE-KMS
  actions:
  - type: delete
```

The delete-action above fails _sometimes_ because the resource(s) are not _READY_ or in a state that allows for the resource to change/delete.

Ideally, I'd like to be able to write something like:

```yaml
policies:
- name: my-test-policy
  resource: aws.glue-dev-endpoint
  mode:
    type: cloudtrail
    events:
    - source: glue.amazonaws.com
      event: CreateDevEndpoint
      ids: requestParameters.EndpointName
  filters:
  - type: security-config
    key: EncryptionConfiguration.CloudWatchEncryption.CloudWatchEncryptionMode
    op: ne
    value: SSE-KMS
  actions:
  - type: wait
    wait_delay: 20
    wait_max_attempts: 30
    key: Status
    op: in
    value:
    - READY
    - FAILED
  - type: delete
```

IMO, the _wait_ is typically required when we want to take an action on the resource, so it makes sense to make that available as a generic action.

From an implementation perspective, we will need to account for sane defaults on `delay` and `max_attempts` (like most boto3 waiters do). And, like you mentioned above, take into account the lambda maximum execution time.
