### ISSUE TITLE
Filter EC2 instance based on region

### ISSUE THREAD

**Issue by Naveenraaj** [cloud-custodian/cloud-custodian#4944]
Hi,

Thanks in advance,

Can you please let me know, if there is a way to filter EC2 instance based on regions, something similar to,

```
policies:
   - name: my-first-policy
     resource: ec2
     filters:
       - type: value
         key: Region
         value:
            - us-east-1
            - us-west-2
         op: not-in
```

Have been running through the docs and examples, but could not achieve it. 

Note: when the above filter is ran, all the instance in us-east-1 & us-west-2 is matched as a hit for the filter along with all the EC2 instance irrespective of the region. Almost opposite to the expected result.

When i change the op as,
`op: in`

It results as 0(Zero) hits.

Any suggestions are welcome.

**Comment by ndesai15** [comment]
@Naveenraaj , You don't need to pass region in filter. You can pass in when you run your custodian policy with --region. If you don't pass it, by default it takes us-east-1. 

Also, value filter takes in key from a describe call only. More info on this is here: https://cloudcustodian.io/docs/filters.html

**Comment by Naveenraaj** [comment]
@ndesai15 , Thank you for the reply

But I'm looking for a way to run a single policy with --region all , which could filter out instances on all the regions except us-east-1 and us-west-1

**Comment by kapilt** [comment]
you can use region as a variable in your policy

Region is not an attribute of an ec2 instance. You can get an az using Placement.AvailabilityZone and then do a containment check

```
      filters:
        - type: value
          key: Placement.AvailabilityZone
          op: not-in
          value_type: swap
          value: us-east-1
        - type: value
          key: Placement.AvailabilityZone
          op: not-in
          value_type: swap
          value: us-east-2
```

better is not executing the policy in a region you don't care about, there's some work being done on policy conditions in #4466  which would address this use case. in the interim its
