### ISSUE TITLE
Security Group filtering all IPs without security groups with Cloud Custodian

### ISSUE THREAD

**Issue by blfarkas** [cloud-custodian/cloud-custodian#4945]
Hello,

Can you please help me?
I want to try to use cloud custodian with filter function and I want to filter all the IPs added to the ingress for Security Group. So if there is any IP then it should be a match.

I've tried this, but without success (0 matches when SG created with IP).

```
    filters:
      - or:
            - type: value
              key: "SecurityGroups[].IpPermissions[].IpRanges[].CidrIp"
              value: ([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}
              op: regex
              #value_type: cidr

```
I've also tried to search the solution over the internet, but without any luck. Got some hints, but not sufficient.

Thank you in advance.
