### ISSUE TITLE
0.8.45.0 and 0.8.45.1 Releases Break Lambda

### ISSUE THREAD

**Issue by MrDweebus** [cloud-custodian/cloud-custodian#4950]
We're using c7n-org and c7n, and upon updating to 0.8.45.0 the lambdas deployed start to throw an error about a missing CloudWatch prefix. The same error is thrown in 0.8.45.1. Is there a new parameter we need to configure on the policies? For what it's worth, manually pushing a lambda with just c7n and not c7n-org does not throw this error. 

Stack trace:

```
Invalid length for parameter logGroupNamePrefix, value: 0, valid range: 1-inf
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 168, in dispatch_event
    p.push(event, context)
  File "/var/task/c7n/policy.py", line 990, in push
    return mode.run(event, lambda_ctx)
  File "/var/task/c7n/policy.py", line 590, in run
    return PullMode.run(self)
  File "/var/task/c7n/policy.py", line 278, in run
    with self.policy.ctx:
  File "/var/task/c7n/ctx.py", line 89, in __enter__
    self.logs.__enter__()
  File "/var/task/c7n/output.py", line 340, in __enter__
    self.join_log()
  File "/var/task/c7n/output.py", line 349, in join_log
    self.handler = self.get_handler()
  File "/var/task/c7n/resources/aws.py", line 273, in get_handler
    session_factory=lambda x=None: self.ctx.session_factory(region=self.region))
  File "/var/task/c7n/log.py", line 91, in __init__
    logGroupNamePrefix=self.log_group)['logGroups']
  File "/var/task/c7n/utils.py", line 390, in _retry
    return func(*args, **kw)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/var/runtime/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/var/runtime/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
```

**Comment by kapilt** [comment]
whats your command line for invoking?

**Comment by MrDweebus** [comment]
Our command line for the apply is something like 
`c7n-org run --config accounts.yml $REGIONS --tags nonprod --policytags nonprod --output-dir ./output --use $MERGED_POLICIES` where `REGIONS` is just a list of regions applicable and `MERGED_POLICIES` is various files collapsed into one for deployment's sake. We haven't explicitly specified a cloud watch log group anywhere, but version 0.8.44.3 worked just fine. The lambdas are also logging out to a cloudwatch log group the same as before, so I'm unsure of what this error is specifying when saying it's missing the key.

**Comment by kapilt** [comment]
Do you have a sample of one of these policies that’s failing? The trace back looks like a mode: periodic.

**Comment by MrDweebus** [comment]
The policy below is pretty typical for our implementation. The redacted fields are our Slack webhook and the ARN of the IAM role provisioned for the Lambdas.

```yaml
policies:
  - name: s3-bucket-secure-transport
    description: &s3_secure_transport S3 buckets should deny all traffic that doesn't go over HTTPS.
    tags: [nonprod, prod]
    region: us-east-1
    resource: s3
    filters:
      - type: missing-statement
        statement_ids:
          - C7nSecureTransport
    actions:
      - type: set-statements
        statements:
          - Sid: "C7nSecureTransport"
            Effect: "Deny"
            Action: ["s3:GetObject","s3:PutObject"]
            Principal:
              AWS: "*"
            Resource: ["arn:aws:s3:::{bucket_name}/*","arn:aws:s3:::{bucket_name}"]
            Condition:
              Bool:
                "aws:SecureTransport": false
      - type: notify
        violation_desc: *s3_secure_transport
        action_desc: Adding secure transport statement to S3 bucket policy
        to:
          - redacted
        transport:
          type: sqs
          # Quotes + no spaces is required for var substitution.
          queue: "{notify_queue_arn}"
    mode:
      type: periodic
      schedule: "rate(1 day)"
      role: arn:aws:iam::{account_id}:role/redacted
```

**Comment by kapilt** [comment]
i suspect it maybe related to this pr with orgs, though i haven't confirmed yet. 
https://github.com/cloud-custodian/cloud-custodian/pull/4809

**Comment by kapilt** [comment]
is there something customized about your installation? i haven't seen any other reports of issues.

if you downloaded one of these lambdas it would be helpful to see what's in the policy.json file for the execution-options key.

**Comment by MrDweebus** [comment]
We haven't customized anything about Custodian itself, no. Below is a redacted copy of the `config.json` file that was in a lambda throwing the same error as above.

```json
{
  "execution-options": {
    "region": "us-west-2",
    "regions": [],
    "cache": "/root/.cache/c7n-org/redacted-us-west-2.cache",
    "profile": null,
    "account_id": "redacted",
    "assume_role": "arn:aws:iam::redacted:role/pet/pet-cloud-custodian-pipeline-popular-cicada",
    "external_id": null,
    "log_group": null,
    "tracer": "default",
    "metrics_enabled": false,
    "metrics": null,
    "output_dir": "./output/redacted/us-west-2",
    "cache_period": 15,
    "dryrun": false,
    "authorization_file": null
  },
  "policies": [
    {
      "actions": [
        {
          "key": "alias/aws/ebs",
          "state": true,
          "type": "set-ebs-encryption"
        },
        {
          "action_desc": "Turning on default EBS encryption using default encryption key `alias/aws/ebs`.",
          "slack_template": "slack_default",
          "to": [
            "contact",
            "redacted"
          ],
          "transport": {
            "queue": "https://sqs.us-east-1.amazonaws.com/redacted/c7n_mailer20190522205029608700000001",
            "type": "sqs"
          },
          "type": "notify",
          "violation_desc": "Accounts should have the default encryption setting for EBS volumes turned on."
        }
      ],
      "description": "Accounts should have the default encryption setting for EBS volumes turned on.",
      "filters": [
        {
          "state": false,
          "type": "default-ebs-encryption"
        }
      ],
      "mode": {
        "execution-options": {
          "log_group": "/cloud-custodian/"
        },
        "packages": [
          "certifi"
        ],
        "role": "arn:aws:iam::redacted:role/pet/pet-cloud-custodian-lambda-popular-cicada",
        "schedule": "rate(1 day)",
        "type": "periodic",
        "tags": {
          "custodian-info": "mode=periodic:version=0.8.45.0"
        }
      },
      "name": "default-ebs-encryption",
      "resource": "aws.account",
      "tags": [
        "nonprod"
      ]
    }
  ]
}

```

**Comment by MrDweebus** [comment]
> I had this issue too, adding cloudwatch-logs log_group to execution-options fixed it for me

I did notice that there are two places in there where the log_group is defined; I'll try this when I get a chance and report back.

**Comment by MrDweebus** [comment]
We've actually got a script that already explicitly defines a log group in the mode; a policy after it has been updated looks more like this:

```yaml
policies:
  - actions:
      - days: 35
        enforce: exact
        type: retention
      - action_desc: Set retention period to 35 days for any Aurora clusters that are
          set to less than 35 days
        slack_template: slack_default
        to:
          - contact
          - redacted
        transport:
          queue: '{notify_queue_arn}'
          type: sqs
        type: notify
        violation_desc: Set retention period to 35 days for any Aurora clusters that are
          set to less than 35 days
    description: Set retention period to 35 days for any Aurora clusters that are set
      to less than 35 days
    filters:
      - and:
          - key: BackupRetentionPeriod
            op: lt
            type: value
            value: 35
          - key: Engine
            op: contains
            type: value
            value: aurora
    mode:
      execution-options:
        log_group: /cloud-custodian/
      role: arn:aws:iam::{account_id}:role/pet/pet-cloud-custodian-lambda-popular-cicada
      schedule: cron(* */4 * * ? *)
      type: periodic
    name: aurora-max-retention
    resource: rds-cluster
    tags:
      - nonprod
```
