### ISSUE TITLE
Run cloudcustodian based off dry run results

### ISSUE THREAD

**Issue by ryanpodonnell1** [cloud-custodian/cloud-custodian#4953]
## Questions

1. Is there a way to feed back a resources.json file (or similar) with the resources that have policy exceptions to cloudcustodian?

## Use Case
1. Automated process executes a dry of cloud custodian, generates a report of results to a unique fileID
1. Results are approved by someone
1. Automated process executes active (non dry) run of cloud custodian with the approved resources to be remediated from the saved file in step 1.

Step 1:
```bash
c7n-org run -c c7n-org-accounts-config.yml -u cloud-custodian-policy.yml  --dryrun -s affectedresources-{uniqueid}.txt
```
Step 2:
```
APPROVAL
```
Step 3:
```bash
c7n-org run -c c7n-org-accounts-config.yml  --file affectedresources-{uniqueid}.txt
```

## Reasons
1. Would like visibility of resources to be remediated by account owners
1. Would like approval process implemented as part of our cloud custodian workflow especially for production accounts
1. Would like to ensure that only approved resources are affected

**Comment by kapilt** [comment]
Short answer yes there are mechanisms to feedback in.

So one way to achieve the underlying goals, is to have a separate policy for the actual cleanup, and use an additional value filter such that its only operating on resources that have been previously been identified and approved. value_from can pull from url/s3 in json/csv formats and is a common mechanism of integration with external systems.

            
so an example workflow would be 

1. run identify policy, send output to s3 staging location
1. approve through some workflow, and move the file into place.
1. run remediation policy

the remediate policy is with an additional filter that restricts to the outputted resources ids, note that this filter is in addition to the identify filters so you exempt the resource if its now compliant.

an example of the additional filter                                                                                               

```yaml
     type: value
     key: InstanceId                                                                                                                                                
     value_from:                                                                                                                                                            
        url: s3://bucket/xyz/resources.json                                                                                                                                       
        expr: [].InstanceId   
     op: in
```



Also custodian does not dictate devops semantics (uniqueid) as its used in many different environments and for many different use cases. On the cli, you can easily provide such when invoking ie. `-s s3://mybucket/$(uuidgen)`
