### ISSUE TITLE
Cross region RDS snapshot issue with target option group

### ISSUE THREAD

**Issue by shaikhsajid18** [cloud-custodian/cloud-custodian#4955]
Hello All, I am trying to create policy for copying cross region RDS snapshot. But getting below error. 

c7n-org run -c accounts/all-accounts.yml -t name:scmprod --output-dir=../outputs/ -u dr-rds-snapshot.yml -v --debug

2019-10-17 18:41:20,911: c7n_org:DEBUG Running policy:dr-custodian-rds-snapshot-copy account:scmprod-account region:us-east-1
2019-10-17 18:41:21,439: c7n_org:ERROR Exception running policy:dr-custodian-rds-snapshot-copy account:scmprod-account region:us-east-1 error:An error occurred (InvalidParameterValue) when calling the CopyDBSnapshot operation: The snapshot requires a target option group with the following options: [Timezone]
2019-10-17 18:41:21,441: c7n_org:INFO Policy resource counts Counter()

```yml
policies:
- name: dr-custodian-rds-snapshot-copy
  resource: rds-snapshot
  region: us-east-1
  filters:
    - type: value
      key: SnapshotCreateTime
      value_type: age
      value: 3
      op: less-than
  actions:
    - type: region-copy
      target_region: us-east-2
      target_key: arn:aws:kms:us-east-2:XXXXXXXXXXXXXXXXX:key/XXXXXXXXXXXXXXX
      copy_tags: true
```
Version details: 

c7n		0.8.45.1
boto3	1.9.251
botocore	1.12.251

RDS being used is Oracle, we are not using transparent data encryption. 
Please let me know if any additional information is required. Thanks in advance.
