### ISSUE TITLE
aws - set-vpc-flow log support create log group if not exists

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#4972]
For enabling VPC flow-logs through Custodian, If the LogGroup doesn't exist Custodian should create a LogGroup before enabling VPC flow-logs.

**Comment by PratMis** [comment]
@kapilt should this functionality look something like this?
```
  - name: enable-vpc-flow-logs
    resource: vpc
    filters:
      - type: flow-logs
        enabled: false
    actions:
      - type: set-flow-log
        DeliverLogsPermissionArn: "arn:aws:iam::{account_id}:role/X"
        LogGroupName: /flow-log
        CreateGroup: true
```

**Comment by PratMis** [comment]
Or just:
```
  - name: enable-vpc-flow-logs
    resource: vpc
    filters:
      - type: flow-logs
        enabled: false
    actions:
      - type: set-flow-log
        DeliverLogsPermissionArn: "arn:aws:iam::{account_id}:role/X"
        LogGroupName: /flow-log
```
such that it would create LogGroup: /flow-log automatically if it doesn't exist
