### ISSUE TITLE
azure - deleting resource group action message

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#4983]
### Description
When you are deleting a resource group, you get the a message that says the resource group is `unknown`. This is because the resource group doesn't reside in a resource group.

```
policies:
  - name: delete-test-rg
    resource: azure.resourcegroup
    filters:
      - type: value
        key: name
        op: contains
        value_type: normalize
        value: test
    actions:
      - type: delete
```

### Actual
`2019-10-23 15:49:34,792: custodian.azure.AzureBaseAction:INFO Action 'delete' modified 'test-1' in resource group 'unknown'.`

### Expected
potentially...
`2019-10-23 15:49:34,792: custodian.azure.AzureBaseAction:INFO Action 'delete' modified resource group 'test-1''.`
