### ISSUE TITLE
How to glob vars in a policy filter

### ISSUE THREAD

**Issue by snobear** [cloud-custodian/cloud-custodian#4985]
Is there a way to use a glob on a variable list? 

I'm trying the following, and the first two filters work great, but the last one using glob results in a syntax error

```
vars:
  # retired custs
  custids: &custids
    - foo01
    - blah09
    - jatest01
    - jla02
    - yeah
policies:
  - name: gen3-ec2
    resource: aws.ec2
    filters:
      - or:
        - type: value
          key: "tag:cust-id"
          op: in
          value: *custids
        - type: value
          key: "tag:cust_id"
          op: in
          value: *custids
        - type: value
          key: "tag:Name"
          op: glob
          value: *custids*
```

**Result:**

```
(venv) $ custodian run --dryrun --region us-west -s out custodian.yml
2019-10-24 09:50:17,668: custodian.commands:ERROR yaml syntax error loading policy file (custodian.yml) error:
 while scanning an alias
  in "<unicode string>", line 39, column 18:
              value: *custids*
                     ^
expected alphabetic or numeric character, but found '*'
  in "<unicode string>", line 39, column 26:
              value: *custids*
                             ^
2019-10-24 09:50:17,668: custodian.commands:ERROR Found 1 errors.  Exiting.
```

The goal of the last filter is to match where the AWS EC2 Name tag is foo01* or blah09* or jatest01*, etc...

Also tried `value: *custids.*` with the dot, but no luck. Any ideas or is this not possible?

**Comment by snobear** [comment]
I came up with the following which seems to work well:

```
vars:
  # retired custs
  custids: &custids ".*foo01.*|.*blah09.*|.*jatest01.*|.*jla02.*|.*yeah.*"
policies:
  - name: old-ec2
    resource: aws.ec2
    filters:
      - or:
        - type: value
          key: "tag:cust-id"
          op: regex
          value: *custids
        - type: value
          key: "tag:cust_id"
          op: regex
          value: *custids
        - type: value
          key: "tag:Name"
          op: regex
          value: *custids
```

Not as efficient for us as we don't really need the regex for the cust-id/cust_id tags, but performance seems negligible.
