### ISSUE TITLE
aws.redshift-snapshot | Error with tag/untag operation

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#4988]
Sample policy:

```
policies:
  - name: redshift-snapshot-tag
     resource: redshift-snapshot
     filters:
       - "tag:Name": absent
     actions:
       - type: tag
          key: a
          value: b
```
Traceback:
```2019-10-26 17:04:22,326: custodian.commands:ERROR Error while executing policy tag-redshift-snaps, continuing
Traceback (most recent call last):
  File "/cloud-custodian/c7n/commands.py", line 282, in run
    policy()
  File "/cloud-custodian/c7n/policy.py", line 1029, in __call__
    resources = mode.run()
  File "/cloud-custodian/c7n/policy.py", line 320, in run
    results = a.process(resources)
  File "/cloud-custodian/c7n/tags.py", line 429, in process
    self.process_resource_set, self.id_key, resources, tags, self.log)
  File "/cloud-custodian/c7n/tags.py", line 136, in _common_tag_processer
    raise error
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/cloud-custodian/c7n/resources/redshift.py", line 759, in process_resource_set
    client.create_tags(ResourceName=arn, Tags=tags)
  File "/cloud-custodian/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/cloud-custodian/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundFault: An error occurred (ResourceNotFoundFault) when calling the CreateTags operation: Tagging is not supported for this type of resource: 'redshift-snapshot' (the ARN is potentially malformed, please check the ARN documentation for more information)```
