### ISSUE TITLE
How To Limit the Number of Affected Resources

### ISSUE THREAD

**Issue by leoblanc** [cloud-custodian/cloud-custodian#4997]
Hello, first of all, congratulations for this great tool. I'm starting using it (I'm a newbie) and I have a question, please.

I need to create a policy to delete non-compliant EBS snapshots. A "non-compliant" EBS snapshot is a snapshot that doesn't have the 4 required tags (Owner,Project,Expiration,CostCener). Also, I'm not including in the filter EBS snapshots where Project is "project1" or "project2" (I have obfuscated the real project names). This is the resulting policy and it works like a charm:

```
policies:
  - name: delete-noncompliant-snapshots
    resource: ebs-snapshot
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::99999999999:role/cloud-custodian
    comment: Delete EBS Snapshots if at least one required tag is missing (snapshots from project1 and project2 are not considered)
    filters:
      # On this filter we are excluding resources related to project1 and project2
      - type: value
        key: "tag:Project"
        op: not-in
        value: ["project1","project2"]
      # On this filter we are including resources that doesn't have all the mandatory tags
      - or:
        - "tag:Owner": absent
        - "tag:Project": absent
        - "tag:Expiration": absent
        - "tag:CostCenter": absent
    actions:
    #  - type: delete  Disabling deletion during testing
     - type: notify
       [...]
```

As I said, the above policy works like a charm: I'm receiving an email where only EBS snapshots that don't have the required tags are included. Also, EBS snapshots from project1 and project2 are not included. Hundreds of matching EBS snapshots are included. So far so good.

Now, I have a final requirement, and I'm stuck here. We don't want to delete all the matching (filtered) EBS snapshots in one shot. We want to do it gradually (deleting 20 snapshots on each policy execution). I thought that I could use `max-resources` for that purpose, but then I understood that [no actions are executed if the number of resources is greater than the configured value](https://cloudcustodian.io/docs/quickstart/advanced.html#policy-resource-limits). So, if there are 100 matching EBS snapshots, an error will occur and 0 EBS snapshots will be deleted. But, as I said, I want to delete the EBS snapshots, but limiting the number to 20 snapshots on each pass. 

After researching a bit more, it seems like the solution is using the `resource_count` value_type. So, I'm now adding the following new filter:

```
      - type: value
        value_type: resource_count
        op: eq
        value: 20
```

Therefore, the new policies are:

```
   [...]
    filters:
      # On this filter we are excluding resources related to project1 and project2
      - type: value
        key: "tag:Project"
        op: not-in
        value: ["project1","project2"]
      # On this filter we are including resources that doesn't have all the mandatory tags
      - or:
        - "tag:Owner": absent
        - "tag:Project": absent
        - "tag:Expiration": absent
        - "tag:CostCenter": absent
      # On this filter we are limiting the max number of resources (even if there are more resources matched by above filters)
      - type: value
        value_type: resource_count
        op: eq
        value: 20
    actions:
    #  - type: delete  Disabling deletion during testing
     - type: notify
       [...]
```

However, the consequence of adding this new filter is that no EBS snapshot is returned/matched. I guess that this occurs because I'm not configuring the filter in the right way.

How can I achieve the desired results? I mean, limiting the number of deleted EBS snapshots on each execution to 20.

Thank you very much in advance!

**Comment by leoblanc** [comment]
@kapilt Thanks for your message. We want to run our policies as Lambda functions. Our first test Lambda function is executed every hour:

```
policies:
  - name: delete-noncompliant-snapshots
    comment: Delete first 20 EBS Snapshots not related to dcenter and not related to AMIs that doesn't have all the required tags
    resource: ebs-snapshot
    mode:
      type: periodic
      schedule: "rate(1 hour)"
      role: arn:aws:iam::9999999999:role/cloud-custodian
      execution-options:
        log_group: custodian-logs
        output_dir: s3://bucket-name-logs/{account_id}/
    filters:
       [...]
```

We have hundreds of EBS snapshots that should be deleted. But we want to roll out this purging process gradually instead of using a single shot. The customer wants to check that the right EBS snapshots are deleted (we configured c7n-mailer to receive reports, this works really nice). If something goes wrong (we entered a wrong filter) we want to limit the damage. As I said, we are starting using CloudCustodian, so some mistakes could happen :) We have other resources in a similar condition (more rules are coming). 

Also, maybe this kind of limit can also be useful to prevent Lambda timeouts, avoid receiving huge reports, etc 

Thanks again!
