### ISSUE TITLE
aws - asg marked invalid incorrectly

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5001]
Sample policy:
```
- policies:
    - name: filter-invalid-asgs
       resource: asg
       filters:
         - type: invalid
```
Looks like this policy marks valid Asgs, as invalid. On further investigation I found that those instances are spot instances. 
I suspect that the asgs that are running spot instances with launch template, do not return a `LaunchTemplate` top level key with describe_auto_scaling_groups api call. They seem to have LaunchTemplate details under `MixedInstancesPolicy` top level key which does not get checked in the code line shown below. 
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/ec2.py#L1888
Hence, it thinks there are no launch templates attached to the Asg, marking it invalid
