### ISSUE TITLE
Cross account Security Hub remediation

### ISSUE THREAD

**Issue by rodrigocmn** [cloud-custodian/cloud-custodian#5034]
I currently have Security Hub configured in Master/Members mode across the organisation, so all policies deployed via c7n-org send findings to local Security Hub and then are shared with the Master Security hub for aggregation. 

I've been testing Security Hub mode 'hub-action' to create a custom action in the UI as an option to take actions on compliance issues. The problem I'm facing is that lambda functions created by 'hub-action' only work in the account it was created (member accounts) and fail when executed from the Master Account.

For example, I deployed the policy below to my member accounts.

```yaml
policies:
  - name: s3-bucket-encryption-policy-absent
    resource: s3
    comment: |
      Find all s3 buckets that are do not have
      encryption enabled.
    mode:
      type: periodic
      schedule: "rate(12 hours)"
      role: arn:aws:iam::{account_id}:role/cloudcustodian-role
    filters:
      - type: bucket-encryption
        state: False
    actions:
      - type: post-finding
        description: |
          S3 bucket should have default bucket encryption enabled
        severity_normalized: 30
        types:
          - "Software and Configuration Checks/AWS Security Best Practices"
        recommendation: "Enable S3 encryption"
        recommendation_url: "https://docs.aws.amazon.com/AmazonS3/latest/user-guide/default-bucket-encryption.html"
        confidence: 100
        compliance_status: FAILED
```
Then I can see the findings from my master account.

![image](https://user-images.githubusercontent.com/22591995/68317309-ceaf6000-00b2-11ea-8a96-870c52aaa055.png)

Then I deploy the following policy to create a custom action.

```yaml
policies:
  - name: encryption
    resource: aws.s3
    mode:
      type: hub-action
      role: arn:aws:iam::{account_id}:role/cloudcustodian-role
    actions:
      - type: set-bucket-encryption
        crypto: AES256
        enabled: True
```

When I try to execute it, I get the following error:

```
[ERROR]	2019-11-06T16:09:17.11Z	2877acda-6665-403b-8233-c310db938a3c	Message: An error occurred (AccessDenied) when calling the PutBucketEncryption operation: Access Denied Bucket: test-bucket-1
```

I've already checked the IAM roles and they are fine (I've created another lambda function in the master that uses the same IAM Role and access S3 buckets from member accounts).
