### ISSUE TITLE
Auto tag newly created kms keys with user tag

### ISSUE THREAD

**Issue by classickar** [cloud-custodian/cloud-custodian#5036]
I have a policy to auto tag kms keys that are newly created with the user tag, and it is not working. Similar auto tag policies for other services are working. region eu-west-1.

```yaml
policies:                                                                                                          
 - name: kms-auto-tag-user                                                                                         
   resource: kms-key                                                                                               
   description: |                                                                                                  
     Triggered when a new kms key is created.Checks to see if it's missing the User tag. If missing it gets created
     with the value of the User ID                                                                                 
   mode:                                                                                                           
     type: cloudtrail                                                                                              
     role: arn:aws:iam::{account_id}:role/c7n-lambda                                                               
     events:                                                                                                       
       - source: kms.amazonaws.com                                                                                 
         event: CreateKey                                                                                          
         ids: responseElements.keyMetadata.keyId                                                                   
   filters:                                                                                                        
     - "tag:User": empty                                                                                           
   actions:                                                                                                        
   - type: auto-tag-user                                                                                           
     update: true                                                                                                  
     tag: User  
```
