### ISSUE TITLE
Azure: Unable to use values from accounts.yml

### ISSUE THREAD

**Issue by vtomardb** [cloud-custodian/cloud-custodian#5059]
This is how my `accounts.yml` file looks like:

```
subscriptions:
  - name: "personnal"
    subscription_id: "xxxxxxx"
    tags:
      - env:personnal
```

below is from my policy, I am unable to parse values from accounts.yml:

```
    subject: "[Azure Policy] [Subscription: {{  subscription_id }}] VMs not running"
    violation_desc: "VMs not running"
```
