### ISSUE TITLE
Encountering SyntaxError when running c7n-mailer

### ISSUE THREAD

**Issue by aosman-tibco** [cloud-custodian/cloud-custodian#5072]
Hello,

When running the update-lambda command a SyntaxError is encountered:

**Versions**
Cloud Custodian: 0.8.41
c7n-mailer: 0.4.1
Python: 2.7

```
Debug: Executing '/bin/bash -c 'source /home/cloud-custodian/custodian/bin/activate; c7n-mailer --config mailer.yml --update-lambda --templates /home/cloud-custodian/policies/templates && touch .mailer_init''
Notice:  Traceback (most recent call last):
Notice:    File "/home/cloud-custodian/custodian/bin/c7n-mailer", line 7, in <module>
Notice:      from c7n_mailer.cli import main
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/c7n_mailer/cli.py", line 9, in <module>
Notice:      import jsonschema
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/jsonschema/__init__.py", line 31, in <module>
Notice:      import importlib_metadata
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 9, in <module>
Notice:      import zipp
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/zipp.py", line 12, in <module>
Notice:      import more_itertools
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
Notice:      from more_itertools.more import *  # noqa
Notice:    File "/home/cloud-custodian/custodian/lib/python2.7/site-packages/more_itertools/more.py", line 340
Notice:      def _collate(*iterables, key=lambda a: a, reverse=False):
Notice:                                 ^
Notice:  SyntaxError: invalid syntax
```

The contents of mailer.yml are as follows:

```yaml
queue_url: https://sqs.us-west-2.amazonaws.com/01234567890/cloud-custodian-queue
role: arn:aws:iam::01234567890:role/custodian_lambda_role
from_address: custodian@foo.com
region: us-west-2
```
