### ISSUE TITLE
How to filter the IAM users that not exist in resource iam-user

### ISSUE THREAD

**Issue by yufuluo** [cloud-custodian/cloud-custodian#5085]
I would like to apply a policy to delete AWS IAM user access keys that have not been used over 90 days. I understand that cloud custodian gets user information from AWS credential report, which refreshes every 4 hours, and I have a lot of temporary bot users with username starts with "vault-" get created frequently and they will be removed within an hour, so I would like to exclude them in this policy. 

My policy is listed below. However, I still got errors like `An error occurred (NoSuchEntity) when calling the GetUser operation: The user with name vault-k8s_prod-usw2-devops-stable-default-devops1573862407-5884 cannot be found.` when running the policy. 

```
policies:
  - name: iam-user-unused-key
    resource: iam-user
    filters:
      - not:
          - type: value
            key: UserName
            value: vault
            op: contains
      - not:
          - "tag:Custodian": whitelist
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_used_date
        value_type: age
        value: 90
        op: gte
    actions:
      - type: remove-keys
        matched: true
        disable: true
```

What do I do wrong here? Why the filter does not take effect? 

Thanks.
