### ISSUE TITLE
aws.alb - In need of a new filter to identify HTTP->HTTPS redirects as current logic doesn't work for our needs

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5091]
Our customers have been getting on our nerves over the App ELB policy as we can't figure out the right filters to make it allow HTTP to HTTPS redirects as our users often have multiple listeners attached and the current logic is very tricky to narrow down to checking individual listeners at once.
Currently we were trying things along the lines of:
```
  filters:
    - type: value
      value_type: age
      key: CreatedTime
      op: greater-than
      value: .0833
    - type: value
      value_type: date
      key: CreatedTime
      op: greater-than
      value: "2019/10/29"
    - type: listener
      key: Protocol
      value: HTTP
    - not:
       - type: listener
         key: DefaultActions[0].RedirectConfig.Protocol
         op: eq
         value: HTTPS
```

The non-compliant would be a listener with HTTP -> HTTP only, anything with a fixed response, only HTTPS, or HTTP to HTTPS redirect would be valid so yeah if we can just find the bad HTTP listener which does NOT have an HTTPS redirect or a fixed response then that would be what we want

**Comment by jtroberts83** [comment]
@kapilt   I was able to get this to work using the existing codebase with some filter adjustments.  I recently discovered reverse regex can be very powerful with the filter combinations.  Here is the filter set which only allows HTTP -> HTTPS redirects  OR HTTP -> fixed-response message and any other HTTP listener configurations outside those 2 would trigger the actions, in my case to delete the ALB.

Working filters:
```
filters:
    - type: listener
      key: Protocol
      value: HTTP
    - or:
        - type: value
          key: '"c7n:MatchedListeners"[0].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[1].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[2].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[3].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[4].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[5].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[6].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[7].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[8].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[9].DefaultActions[0].RedirectConfig.Protocol'
          op: regex
          value: '^((?!HTTPS).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[0].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[1].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[2].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[3].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[4].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[5].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[6].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[7].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[8].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
        - type: value
          key: '"c7n:MatchedListeners"[9].DefaultActions[0].Type'
          op: regex
          value: '^((?!(fixed-response)|(redirect)).)*$'
```
 
Being that this is working I will close this issue out but I probably need to post this example and some others (even though its ugly) as they work, unless you know how to rewrite these without having so many filters and instead have 1 or 2 which check all array locations.
