### ISSUE TITLE
Action Type Delete is not valid for aws.rest-api

### ISSUE THREAD

**Issue by TimUbbink** [cloud-custodian/cloud-custodian#5092]
Hi there,

It seems that the delete action type is not valid for the aws.rest-api which is documented [here](https://cloudcustodian.io/docs/aws/resources/rest-api.html#aws-rest-api-actions-delete). The error is stating validation failures on all different type of actions too:

```
Failed validating 'anyOf' in schema[10]['allOf'][1]['properties']['actions']['items']:
{'anyOf': [{'$ref': '#/definitions/actions/aws.auto-tag-user'},
{'$ref': '#/definitions/actions/aws.invoke-lambda'},
{'$ref': '#/definitions/actions/aws.invoke-sfn'},
{'$ref': '#/definitions/actions/aws.mark-for-op'},
{'$ref': '#/definitions/actions/aws.notify'},
{'$ref': '#/definitions/actions/aws.post-finding'},
{'$ref': '#/definitions/actions/aws.post-item'},
{'$ref': '#/definitions/actions/aws.put-metric'},
{'$ref': '#/definitions/actions/aws.remove-tag'},
{'$ref': '#/definitions/actions/aws.tag'},
{'$ref': '#/definitions/resources/aws.rest-api/actions/update'},
{'$ref': '#/definitions/actions/aws.webhook'},
{'enum': ['notify',
'webhook',
'update',
'tag',
'auto-tag-user',
'mark-for-op',
'remove-tag',
'invoke-lambda',
'put-metric',
'post-finding',
'invoke-sfn',
'post-item']}]}
```

Is the documentation or API call incorrect?

Greetings,

Tim

**Comment by PratMis** [comment]
Do you mind posting your policy? Thanks

**Comment by TimUbbink** [comment]
Sure,

```
- name: rest-api-delete-marked
    resource: rest-api
    description: Delete any marked aws.rest-api resources if it has been that way for 2 days or more.
    filters:
      - type: marked-for-op
        tag: c7n_missing_owner
        op: delete
    actions:
      - type: delete
      - type: notify
        template: default
        priority_header: '2'
        subject: An AWS resource has been removed
        to:
          - example@email.com
        transport:
          type: sqs
          queue: https://sqs.eu-west-1.amazonaws.com/<account_id>/<queue_name>
```

I'm running 0.8.45.1

Thanks PratMis
