### ISSUE TITLE
Enhancement - Action for posting an SQS message

### ISSUE THREAD

**Issue by thiezn** [cloud-custodian/cloud-custodian#5121]
Hi,

Would it be possible to create a new CloudCustodian action that allows you to post a SQS message?

```yaml
- name: delete-unencrypted-ec2
    resource: ec2
    filters:
      - type: ebs
        key: Encrypted
        value: false
    actions:
      - terminate
      - type: sqs
         data:
             - item1:
                   someValue: 1
             - item2:
                   anotherValue: 2
        to:
             - arn:aws:sqs:us-east-2:444455556666:queue1
```
The items in the data field would be transformed to a string and added to the SQS messageBody. 

The resource information returned by the CloudCustodian policy could perhaps be added to a[ SQS Message attribute](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html), or maybe added using the bracket notation currently used for the mailer, etc in policy definitions like follows:

```yaml
    actions:
      - terminate
      - type: sqs
         data:
             - item1:
                   someValue: "this is my account id {{ account_id }}"
```

Would this be something worth pursuing? It would help a lot with some of the integrations we've build with service management and collaboration (e.g. slack/teams) tooling.

Kind regards,
Thiezn
