### ISSUE TITLE
I would like to associate mulltiple cloud custodian policies with the same event to one AWS Lambda.

### ISSUE THREAD

**Issue by tsarpi1** [cloud-custodian/cloud-custodian#5129]
I have many policies for the same cloudtrail event, RunInstances.
Instead of cloud custodian generating one lambda and one cloudwatch rule for each policy,
can I get it to generate just one LAMBDA and one cloud watch rule.

**Comment by kapilt** [comment]
no thats not supported, policies run independently and generate stats/outputs independent of each other. is there a particular problem your trying to address? (ie. rather than the how). ie what does many mean 5, 10? if you have lots of run instance policies, I'd suggest switching some out to mode config rule or to periodic. or making them less fine grained (ie do x if a, b, c).

**Comment by tsarpi1** [comment]
HI Kapil,

I have 90 rules to update tags on an ec2 instance. I don't like the idea of
90 Lambda's starting up, each time a new EC2 instance starts up.
Looks like I will need to use a custom Lambda and put all the logic in that.

thanks

Tom

**Comment by kapilt** [comment]
I'm not clear why there would be 90 lambda policies to update tags, given there's 50 tags.. ie it might be easier to explain the use case and problem your trying to solve rather than focusing on the how. most tag compliance policies end up in a single policy, with a few other auto-tagging ones as separate.

**Comment by tsarpi1** [comment]
Hi Kapil,

Funny thing its just 2  tags application-owner and application. Many
instances are not tagged correctly, based on 90 rules we clean this up.
The rules are based on other tag values.
Example not use cwe

 name: ec2-enforce-tag-beanstalk-pbscustomerinfo-application
    resource: ec2
    description: |
      Tag compliance report
    filters:
      - and:
        - "tag:technical:application": absent
        - "tag:elasticbeanstalk:environment-name": present
        - type: value
          key: "tag:elasticbeanstalk:environment-name"
          op: regex
          value: ^pbscustomerinfo-.*$
    actions:
      - type: tag
        tag: "technical:application"
        value: "pbscustomerinfo"
      - type: tag
        tag: "technical:application-owner"
        value: "webteam"

**Comment by kapilt** [comment]
fwiw this particular can be simplified, the top level operator for filters is `and` and you can tag multiple values with a single tag action (and one underlying api call).

```yaml
 name: ec2-enforce-tag-beanstalk-pbscustomerinfo-application
    resource: ec2
    description: |
      Tag compliance report
    filters:
        - "tag:technical:application": absent
        - "tag:elasticbeanstalk:environment-name": present
        - type: value
          key: "tag:elasticbeanstalk:environment-name"
          op: regex
          value: ^pbscustomerinfo-.*$
    actions:
      - type: tag
        tags: 
            "technical:application": "pbscustomerinfo"
            "technical:application-owner": "webteam"
```

its an interesting use case, although i'd partly be of mind that part of the remediation would be to notify the application team to fix their devops/provisioning instead of always fixing behind them (config drift). so the policy multiplication here comes because of the many different tag values that are used to determine to the correct tag values for the missing tag. being able to express this in a single policy would need some notion of a mapping that you could reference from within the policy, although not entirely clear how that would work. the suggestion re multiple policies in a single lambda does seem like the most viable option. to introduce that capability i'd think we'd add some sort of group attribute to mode that we'll use to group the relevant lambdas, the auto lambda layer work (not merged) might be relevant here as it also looks at the full collection of policies to enable layer provisioning.

**Comment by tsarpi1** [comment]
thanks very much for the information
regards
Tom

**Comment by mstair** [comment]
Here is my use case, where doing the math on lambda count is adding up. I have about 100 policies I am looking to deploy across about 100 member accounts that I need to apply across many AWS regions. Being able to group policies logically per lambda provision (say by policy resource type like security group rules vs s3 rules vs ebs rules) seems like it might make sense?

**Comment by djgoku** [comment]
@kapilt I know this likely isn't the right place to make the change but let me illustrate how I got a small proof of concept working. Sorry I am not well versed in cloud custodian terms, but here goes.

I am going to use this policy [1] that is deployed to lambda and is saved as `custodian-ami-delete-on-expiresat-tag.json` in the root directory of the lambda instead of `config.json`:

```
policies:

- name: ami-delete-on-expiresat-tag
  resource: ami
  filters:
     - type: value
       value_type: age
       op: gt
       key: tag:ExpiresAt
       value: 0
  actions:
    - type: deregister
```

After changing this `c7n/handler.py`:

```
modified   c7n/handler.py
@@ -135,7 +135,7 @@ def init_config(policy_config):
 init_env_globals()
 
 
-def dispatch_event(event, context):
+def dispatch_event(event, context, config_file="config.json"):
     error = event.get('detail', {}).get('errorCode')
     if error and C7N_SKIP_EVTERR:
         log.debug("Skipping failed operation: %s" % error)
@@ -144,7 +144,7 @@ def dispatch_event(event, context):
     # one time initialization for cold starts.
     global policy_config, policy_data
     if policy_config is None:
-        with open('config.json') as f:
+        with open(config_file) as f:
             policy_data = json.load(f)
         policy_config = init_config(policy_data)
         load_resources(StructureParser().get_resource_types(policy_data))
```

This could allow the `custodian_policy.py`:

```
from c7n import handler

def run(event, context):
    arn = event['resources'][0] // arn:aws:events:us-east-2:########:rule/custodian-ami-delete-on-expiresat-tag
    config_file = f'{arn.split('/')[-1]}.json' // custodian-ami-delete-on-expiresat-tag.json
    return handler.dispatch_event(event, context, config_file)
```

All policies would just get saved to the root of the lambda with `custodian-<policy-name>.json`.

If there is another way this is possible without modifying `c7n/handler.py` that would be even better.

[1] https://github.com/cloud-custodian/cloud-custodian/blob/master/tests/data/test_policies/ami-GOODVALIDATION.yml
