### ISSUE TITLE
How to filter users whose console access is disabled

### ISSUE THREAD

**Issue by kramalin** [cloud-custodian/cloud-custodian#5137]
we want to filter out all users whose console access is disabled and we went through the filters of aws.iam.resources but could not find what we need.

Any direction on this will be really appreciated.

**Comment by kapilt** [comment]
see password_enabled in iam-user resource for the credential report filter, that effectively represents dashboard access.

**Comment by JohnHillegass** [comment]
Kapil is correct, password_enabled is the way to go to when filtering for this. Here is a sample policy in case this was still an issue on your end but also for future reference in case someone has a similar use case.

```yaml
policies:
    - name: user-has-console-access
      resource: iam-user
      filters:
        - type: credential
          key: password_enabled
          value: true
    - name: user-doesnt-have-console-access
      resource: iam-user
      filters:
        - type: credential
          key: password_enabled
          value: false
```
