### ISSUE TITLE
AWS: dynamodb-continuous-backups-status

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#5160]
I am trying to find the dynamoDB tables whose point-in-time-recovery is disabled. Should i select the resource as dynamodb-table or dynamodb-backup and advise if my filters are correct.

```
policies:

- name: sec-n-dynamodb-continuous-backups-status
  resource: aws.dynamodb-table
  comment: |
    Identify DynamoDB tables that does not make use of Point-in-time-Recovery (PITR) feature in order to automatically take continuous backups.
    In order words, continuous backup status is disabled.
  filters:
    - type: value
      key: DescribeContinuousBackups
      op: ne
      value: ENABLED
  mode:
    schedule: "rate(10 minutes)"
    type: periodic
    execution-options:
      output_dir: s3://x/x/x/x/x/x/x/x/x/
  actions:
    - type: notify
      action_desc: |
        Custodian has found the automatic continuous backups to be disabled .
      subject: "DynamoDB Tables - Continuous Backups - DISABLED"
      to: ["slack"]
      transport:
        type: sqs
        queue: c7nMessageQueue
      violation_desc: "DynamoDB tables are not enabled for continuous backups"
```

@aakifshaikh the value filter isn't doing an describe call its. looking at the intrinsic attributes of the table of which continuous backups aren't one, so we would need a new filter I suspect if it requires an api call, please file an issue
