### ISSUE TITLE
AWS S3 - enhance toggle-logging capabilities

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/cloud-custodian#5167]
We're looking at trying to forcefully set the s3 access logs setting on all of our buckets to a standardized bucket and prefix for each of our accounts.  `toggle-logging` currently only sets a logging config if one doesn't exist for the bucket.  I propose that `toggle-logging` should all us to forcefully set a logging config.  Perhaps a new `set-logging` action should be created that does that?  or just add a `force` or `override` attribute that could control this behavior.

With that, however, we need to be able to filter which buckets we should be attempting to set so we don't keep trying to apply the same logging config each time.  While we can use the generic value filters to look at `Logging.TargetBucket` and `Logging.TargetPrefix`, we currently can't compare those to the interpolated variables we might be using inside of `toggle-logging`.

This is what I would propose (functionally) being able to do:
```
policies:
  - name: s3-fix-logging
    resource: s3
    filters:
      - not:
          - "Logging.TargetBucket": "{account_id}-s3-access-logs-{region}"
          - "Logging.TargetPrefix": "{account}/{source_bucket_name}/"
    actions:
      - type: toggle-logging
        override: true
        target_bucket: "{account_id}-s3-access-logs-{region}"
        target_prefix: "{account}/{source_bucket_name}/"
```
Note the use of `{account}` to pull in the account alias name.  I'm thinking that something like this should be implemented as an s3-specific filter like `invalid-logging`:
```
    filters:
      - type: invalid-logging
        target_bucket: "{account_id}-s3-access-logs-{region}"
        target_prefix: "{account}/{source_bucket_name}/"
```
where it specifically looks for a logging config that doesn't match what's given.  This would also allow us to add a `notify` action after to notify folks that their logging config was updated/fixed and they might need to update their cloudformation or terraform configs to match.
