### ISSUE TITLE
MalformedXML when calling the PutBucketLifecycleConfiguration

### ISSUE THREAD

**Issue by theory** [cloud-custodian/cloud-custodian#5183]
I wrote a policy to configure a lifecycle, but get this error:

```
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the PutBucketLifecycleConfiguration operation: The XML you provided was not well-formed or did not validate against our published schema
```

The policy:

``` yaml
policies:
  - name: s3-log-targets
    resource: s3
    filters:
      - type: is-log-target
        # XXX Filter for buckets without a lifecycle expiration rule?
      - type: value
        key: tag:tu:data:classification
        op: ne
        value: public
    actions:
      - type: configure-lifecycle
        rules:
          - ID: retention-policy
            Status: Enabled
            Expiration:
              Days: 30
    mode:
      type: pull
```

This does abide by [the policy in s3.py](/cloud-custodian/cloud-custodian/blob/6514499f367e918241639cb2c6431ff855e4752e/c7n/resources/s3.py#L2646), and looks similar to the policy I found in `resources.json`:

``` json
    "Lifecycle": {
      "Rules": [
        {
          "Expiration": {
            "Days": 30
          },
          "ID": "Log Retention",
          "Filter": {
            "Prefix": ""
          },
          "Status": "Enabled"
        }
      ]
    }
```

Is there a way to get c7n to emit the XML it's sending to the API?

**Comment by theory** [comment]
Ah, fixed by adding the Filter:

```
          - ID: retention-policy
            Status: Enabled
            Prefix: ""
            Expiration:
              Days: 30
```

So maybe the schema needs to require it (or `Filter/Prefix`)?
