### ISSUE TITLE
Filter resources based on dynamic tag name following some pattern.

### ISSUE THREAD

**Issue by abhishekFreshworks** [cloud-custodian/cloud-custodian#5184]
How to filter resources based on dynamic tag name following some pattern? The tag name is say 'custodian-xyz', where xyz changes but 'custodian' is constant. Can we filter based on the tag name using regex like we can apply 'regex' option to 'Values'. Eg:

```
filters:
    - type: value
      key: tag:custodian*
      value: true
      op: regex
```

I have put tag name as 'custodian*' but that does not seem to work. @kapilt can you please guide?
