### ISSUE TITLE
Azure - value_type: age does not seem to work with instance-view filter

### ISSUE THREAD

**Issue by jmwaks** [cloud-custodian/cloud-custodian#5187]
Custodian version: 0.8.45.3
I am writing a policy to stop any azure vm older than 14 days.

```
policies:
    - name: vm-age-limit
      resource: azure.vm
      filters:
        - type: instance-view
          key: statuses[].time
          op: greater-than
          value_type: age
          value: 14
      actions:
        - type: stop
```
Output:
`2019-12-30 13:10:19,420: custodian.policy:INFO policy:vm-age-limit resource:azure.vm region: count:0 time:0.69`
However, this does policy does not have any effect. Is this a bug or am I missing something? 

Thanks.

**Comment by stefangordon** [comment]
Your jmespath query in `key` is returning an array, so the `age` type and `greater-than` operator don't make sense with it. 

If you index to a specific status it will work:

```
policies:
    - name: vm-age-limit
      resource: azure.vm
      filters:
        - type: instance-view
          key: statuses[0].time
          op: greater-than
          value_type: age
          value: 14
```

I'm sure you can get fancy with your JMESPath with things like `key: statuses[?displayStatus == 'Ready'].time | [0]` as well, but I haven't experimented with it.

I'd probably also consider using the `mark for op` action and the `marked for op` filter together to do this.  There is a (more complex) example of it here: https://cloudcustodian.io/docs/azure/examples/resourcegroupsdelayedoperation-general.html
