### ISSUE TITLE
azure - networksecuritygroup - unable to match any resources unless index is specified in the filter

### ISSUE THREAD

**Issue by rsandhu2** [cloud-custodian/cloud-custodian#5188]
I am working on writing a custodian policy to find global inbound rules in azure network security group. There is ingress filter for networksecuritygroup resource but it doesn't allow me to specify sourceAddressPrefix. I tried using the following policy with value type filter to find the security group rule that allow global inbound connections but it doesn't work without specifying an index. Is there a bug or I am missing something?

c7n version: 0.8.45.3

Working example: 
```
policies:
  - name: network-security-group
    resource: azure.networksecuritygroup
    filters:
      - type: ingress
        access: "Allow"
        match: 'any'
      - type: value
        key: properties.securityRules[0].properties.sourceAddressPrefix
        value: '*'
        op: eq
```

Output:
2019-12-30 15:37:36,279: custodian.policy:INFO policy:network-security-group resource:azure.networksecuritygroup region: count:1 time:0.69

Non-working example:

```
policies:
  - name: network-security-group
    resource: azure.networksecuritygroup
    filters:
      - type: ingress
        access: "Allow"
        match: 'any'
      - type: value
        key: properties.securityRules[].properties.sourceAddressPrefix
        value: '*'
        op: eq
```

Output:
2019-12-30 15:37:50,989: custodian.policy:INFO policy:network-security-group resource:azure.networksecuritygroup region: count:0 time:0.52

Network security group ingress rules:
![image](https://user-images.githubusercontent.com/15022621/71600058-69f50c80-2b1b-11ea-8235-1e874d1655ae.png)

**Comment by stefangordon** [comment]
The value filter you are looking for is probably:

```
policies:
  - name: network-security-group
    resource: azure.networksecuritygroup
    filters:
      - type: ingress
        access: "Allow"
        match: 'any'
      - type: value
        key: properties.securityRules[].properties.sourceAddressPrefix
        value_type: swap
        value: '*'
        op: in
```

The query provided in the key is returning an array when you don't provide an indexer, so your operation becomes `in` rather than `eq`.  Additionally the default behavior of `in` would look for `key in value` and you want `value in key` so you add `value_type: swap`.

It takes a while to learn the options in the value filter.  There are some similar examples in its dedicated help page though: https://cloudcustodian.io/docs/filters.html#value-filter
