### ISSUE TITLE
post-finding action missing from aws.config-recorder

### ISSUE THREAD

**Issue by brianpcurran** [cloud-custodian/cloud-custodian#5189]
I couldn't get `account.check-config` working so I decided to use something like this instead, to detect if any Config recorders exist that aren't recording, aren't recording all supported events, or don't include global resource types, or if there are less than 1 Config recorders in the account.

```
- name: cis-2-5-enable-aws-config
    resource: config-recorder
    filters:
      - or:
        - type: value
          key: status.recording
          value: false
        - type: value
          key: recordingGroup.allSupported
          value: false
        - type: value
          key: recordingGroup.includeGlobalResourceTypes
          value: false
        - type: value
          value_type: resource_count
          op: lt
          value: 1
    actions:
      *cis-2-5-action
```

This seems to work fine, but when trying to use the following action I get an error.

```
cis-2-5-action: &cis-2-5-action
    - type: post-finding
      severity_normalized: 80
      types:
        - "Software and Configuration Checks/AWS Security Best Practices/CIS AWS Foundations Benchmark"
      recommendation: "Ensure that AWS Config is enabled in this region and is configured to capture all supported events and global resource types."
      fields:
        CisRules:
          - '2.5'
```

Here is the error on validation.

```
$ custodian run --dryrun -p cis-4-1-to-4-2-no-security-groups-with-port-22-or-port-3389-open -s output cis.yml
2019-12-31 12:02:47,731: custodian.commands:ERROR invalid policy file: cis.yml error: Failed to validate policy cis-2-5-enable-aws-config
 Error on policy:cis-2-5-enable-aws-config resource:config-recorder
{'type': 'post-finding', 'severity_normalized': 80, 'types': ['Software and Configuration Checks/AWS Security Best Practices/CIS AWS Foundations Benchmark'], 'recommendation': 'Ensure that AWS Config is enabled in this region and is confi
gured to capture all supported events and global resource types.', 'fields': {'CisRules': ['2.5']}} is not valid under any of the given schemas

Failed validating 'anyOf' in schema[38]['allOf'][1]['properties']['actions']['items']:
    {'anyOf': [{'$ref': '#/definitions/actions/aws.invoke-lambda'},
               {'$ref': '#/definitions/actions/aws.invoke-sfn'},
               {'$ref': '#/definitions/actions/aws.notify'},
               {'$ref': '#/definitions/actions/aws.post-item'},
               {'$ref': '#/definitions/actions/aws.put-metric'},
               {'$ref': '#/definitions/actions/aws.webhook'},
               {'enum': ['notify',
                         'webhook',
                         'invoke-lambda',
                         'put-metric',
                         'invoke-sfn',
                         'post-item']}]}

On instance['actions'][0]:
    {'fields': {'CisRules': ['2.5']},
     'recommendation': 'Ensure that AWS Config is enabled in this region '
                       'and is configured to capture all supported events '
                       'and global resource types.',
     'severity_normalized': 80,
     'type': 'post-finding',
     'types': ['Software and Configuration Checks/AWS Security Best '
               'Practices/CIS AWS Foundations Benchmark']}
2019-12-31 12:02:47,731: custodian.commands:ERROR Found 1 errors.  Exiting.
```

I'm assuming this is because `post-finding` is not a valid action:

```
$ custodian schema aws.config-recorder.actions
aws.config-recorder:
  actions:
  - invoke-lambda
  - invoke-sfn
  - notify
  - post-item
  - put-metric
  - webhook
```

Is this intentionally missing from `aws.config-recorder`? I thought `post-finding` was a generic/common AWS action so I was surprised to find it missing here. I may try to get `account.check-config` working again instead of using this, but thought I would open an issue anyway.
