### ISSUE TITLE
c7n_mailer: CC causes duplicate emails in the to field

### ISSUE THREAD

**Issue by ajkoehler** [cloud-custodian/cloud-custodian#5211]
When I use the cc: field in my policy it is causing an issue where it also adds the cc email to the to:.

```bash
$ custodian version
0.8.45.3
```

policy:
``` yaml
- name: ec2-old-ami-90
    description: &description_90 EC2 AMIs are older than 90 days.  
    resource: ec2
    tags: [test]
    filters:
      - type: image-age
        days: 90
        op: gte
    actions:
      - type: notify
        template: email_default
        template_format: 'html'
        priority_header: '1'
        subject: "[{{ account }} - {{ region }}] - EC2 AMI > 90 days Old"
        violation_desc: *description_90
        action_desc: EC2 AMI Out of Date Notification
        to:
          - resource-owner
        cc:
         - x@x.com
        owner_absent_contact:
          - x@x.com
```

My mailer has the contact_tags: email_contact to use the custom tag I have on my EC2 instances to email that instead of the default `OwnerContact`
```yaml
contact_tags:
  - "email_contact"
```

When the resource-owner exists:
I receive the email as:
```
to: resource-owner(i.e a@a.com), x@x.com
cc: x@x.com
```

When the resource-owner tag (custom tag) does not exist:
I receive the email as:
```
to: x@x.com, x@x.com
cc: x@x.com
```

I ruled out that the owner_absent_contact was not causing the issue by changing it to y@y.com and that was not added in the first example, but was added in the second example.  The x@x.com was still duplicated in the cc and to, though.
