### ISSUE TITLE
OffHours: ASG terminate stops working

### ISSUE THREAD

**Issue by DevOpsGuy-Al** [cloud-custodian/cloud-custodian#5224]
Hi

We have been using OffHours for the last couple of years without any incident. In October an issue was raised for us to look into, the reporter claimed that OffHours for his ASG was no longer terminating at the time given in the `OffHours` tag and where `OffHoursFlags=terminate`.

We have investigated and tested this issue trying the following:

## Redeploying the ASG
`OffHours=on=(M-F,7);off=(M-F,18);tz=bst`
`OffHoursFlags=terminate`
`OffHoursPrevious is not set `

After redeploy the ASG terminated successfully at the set time at 18:00, however it **failed to terminate again on the 2nd day.**

After the successful termination and then failing to terminate the tags were as follows:
`OffHours=on=(M-F,7);off=(M-F,18);tz=bst`
`OffHoursFlags=terminate`
`OffHoursPrevious=MaxSize=1;DesiredCapacity=1;MinSize=1` 

For ASGs our offhours policys are:

```
- name: a53-offhours-terminate-asg
    description: |
      Terminate autoscaled instances based on values of OffHours tag when
      OffHoursFlags contains "terminate", saving ASG size params in tag
      OffHoursPrevious. Ignore if there is already an OffHoursPrevious tag.
    resource: asg
    filters:
      - and:
        - type: value
          key: "tag:OffHoursFlags"
          op: regex
          value: '(;|^)terminate(;|$)'
        - type: offhour
          tag: OffHours
          opt-out: false
          offhour: 14
          default_tz: gmt
        - or:
          - "tag:OffHoursPrevious": absent
          - "tag:OffHoursPrevious": empty
    actions:
      - type: resize
        min-size: 0
        desired-size: 0
        save-options-tag: OffHoursPrevious
```
```
 - name: a65-offhours-restore-asg
    description: Restore min/desired size of ASGs which were terminated
    resource: asg
    filters:
      - and:
        - "tag:OffHoursPrevious": present
        - "tag:OffHoursPrevious": not-null
        - type: value
          key: "tag:ProductCode"
          op: ni
          value_from:
            url: https://<gitlabURLPath>/holiday-east.txt
            format: txt
        - type: value
          key: "tag:OffHoursFlags"
          op: regex
          value: '(;|^)terminate(;|$)'
        - not:
          - type: value
            key: "tag:OffHoursFlags"
            op: regex
            value: '(;|^)nostart(;|$)'
        - type: onhour
          tag: OffHours
          opt-out: false
          onhour: 14
          default_tz: gmt
          skip-days-from:
            url: https://<gitlabURLPath>/holiday-west.txt
            format: txt
    actions:
      - type: resize
        restore-options-tag: OffHoursPrevious
      # it would be better to *remove* the OffHoursPrevious tag but this currently
      # produces odd behaviour with Terraform so, until Terraform is fixed, we will
      # reinstate the tag with an empty value
      - type: tag
        key: OffHoursPrevious
        value: ""
        propagate: false
```

We have not seen any issue with using suspend, which uses the following policy:
```  
- name: a52-offhours-suspend-asg
    description: |
      Suspend autoscale groups based on values of OffHours tag when OffHoursFlags
      contains "suspend"
    resource: asg
    filters:
      - and:
        - type: value
          key: "tag:OffHoursFlags"
          op: regex
          value: '(;|^)suspend(;|$)'
        - type: offhour
          tag: OffHours
          opt-out: false
          offhour: 14
          default_tz: gmt
    actions:
      - type: suspend
```
```  
- name: a63-offhours-resume-asg
    description: |
      Resume autoscale groups based on values of OffHours tag when OffHoursFlags
      contains "suspend" and don't contains "nostart"
    resource: asg
    filters:
      - and:
        - type: value
          key: "tag:ProductCode"
          op: ni
          value_from:
            url: https://<gitlabURLPath>/holiday-east.txt
            format: txt
        - type: value
          key: "tag:OffHoursFlags"
          op: regex
          value: '(;|^)suspend(;|$)'
        - not:
          - type: value
            key: "tag:OffHoursFlags"
            op: regex
            value: '(;|^)nostart(;|$)'
        - type: onhour
          tag: OffHours
          opt-out: false
          onhour: 14
          default_tz: gmt
          skip-days-from:
            url: https://<gitlabURLPath>/holiday-west.txt
            format: txt
    actions:
      - type: resume
```

1. We have tried testing using dry-run mode on this config, however it does not provide much information (other than resources that are excluded from OffHours).
2. It appears that after a terminate and the ASG is brought back up the `OffHoursPrevious` tag is set, which we think may be causing this issue. 
3. We do not know when ASG terminate stopped working correctly as we have no historical records (logs are lost on redeploy of ASGs). 
4. This only seems to affect ASGs, not standalone EC2 instances

Any assistance with this would be grateful.
