### ISSUE TITLE
present and not absent return different results

### ISSUE THREAD

**Issue by kliseb** [cloud-custodian/cloud-custodian#5241]
Maybe I'm simply misunderstanding what each of these filters do, but I found that `present` and `not absent` return different counts.

# Cloud Custodian version
```
$ custodian version
0.8.45.4
```

# Steps to reproduce
I created 4 users in an aws account, and a policy named `Test`. I attached the Test policy to 1 user. Then I created the following custodian policy:
```
  - name: iam-users-without-test-policy
    resource: aws.iam-user
    description: Number of users without Test policy
    filters:
      - type: policy
        key: PolicyName.Test
        value: absent
```
Now executing the policy:
```
$ custodian run -d --output-dir out play-policies.yml
2020-01-16 14:27:42,757: custodian.policy:INFO policy:iam-users-without-test-policy resource:aws.iam-user region:us-west-2 count:1 time:0.99
```
`count:1`
I'm new to custodian, so I didn't realize that this means I'm expecting that no users will have this Test policy. Fine, let's change the value to `present` instead:
```
  - name: iam-users-without-test-policy
    resource: aws.iam-user
    description: Number of users without Test policy
    filters:
      - type: policy
        key: PolicyName.Test
        value: present
```
Now this is weird. I'm expecting this to be the opposite count. I have 4 users, and 1 user has the Test policy attached, so the count should be 3, right? Let's see:
```
$ custodian run -d --output-dir out play-policies.yml
2020-01-16 14:30:57,735: custodian.policy:INFO policy:iam-users-without-test-policy resource:aws.iam-user region:us-west-2 count:0 time:0.94
```
`count:0`
Well that's weird, the count was actually 0... What if we try changing the custodian policy from `present` to `not absent`?
```
  - name: iam-users-without-test-policy
    resource: aws.iam-user
    description: Number of users without Test policy
    filters:
      - not:
        - type: policy
          key: PolicyName.Test
          value: absent
```
Running this policy:
```
$ custodian run -d --output-dir out play-policies.yml
2020-01-16 14:34:09,843: custodian.policy:INFO policy:iam-users-without-test-policy resource:aws.iam-user region:us-west-2 count:3 time:1.06
```
`count:3`

Ok, so I finally got what I expected. But now I'm really confused because `present` is different from `not absent`. Is this a bug, or am I just not understanding the nuances of custodian?
