### ISSUE TITLE
AWS: iam-role 'RoleLastUsed.LastUsedDate' not working

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5246]
Hi,

I noticed that `RoleLastUsed.LastUsedDate` not working. I think it may be related to old version of awscli. However our policies are running as lambda. So, looking for ways to remediate it.

```
  - name: unused-iam-roles
    resource: iam-role
    region: us-east-2
    tags:
      - security:iam
      - security:unused
    mode: *weekly-mode
    filters:
      - or:
        - "RoleLastUsed.LastUsedDate": absent
        - type: value
          key: RoleLastUsed.LastUsedDate
          value_type: age
          value: 365
          op: greater-than
```
