### ISSUE TITLE
Ability to reference Event in value_from expressions

### ISSUE THREAD

**Issue by mmcenti** [cloud-custodian/cloud-custodian#5264]
I am using the value filter with value_from to retrieve a file from S3. I would like to be able to traverse this file with my jmespath expression substituting in values from the CloudTrail Event. For example: `[0].events[?name == '${event.requestParameters.InstanceID}'] `

This functionality is similar to how you can currently use account_id, region, and now.

Example file returned from S3:
``` json
[
{
    "accountID": "1",
    "events": [{
        "name": "RunInstances",
        "whitelist": {
            "entity": [{
                "value": "user.name",
                "objects": [
                    { "value": "myEC2instanceID", "validUntil": "1575998956" }
                ]
            }]
        }
},{
    "accountID": "2",
    "events": [{
        "name": "PutBucketAcl",
        "whitelist": {
            "entity": [{
                "value": "roleArn",
                "objects": [
                    { "value": "myCoolS3BucketName", "validUntil": "1575998956" }
                ]
            }]
        }
}
]
```

Example: I'd like to be able to have my expression as 
`[?accountID == ${account_id}] | [0].events[?name == '${event.eventName}'] | [0].whitelist.entity[?value == '${event.UserIdentity.Username}'] | [0].objects[?value == '${event.requestParameters.BucketName'] | [0].value`. 

At runtime, the variables would be substituted turning the expression into 
`[?accountID == 1] | [0].events[?name == 'PutBucketAcl'] | [0].whitelist.entity[?value == 'user.name'] | [0].objects[?value == 'myCoolBucketName'] | [0].value`. 

When the updated expression is run it would return `myCoolS3BucketName` which we could then use to do operations with in the value filter.

Policy filter:
``` yaml
- type: value
   key: "requestParamaters.bucketName"
   op: ne
   values_from:
       url: s3://bucket/file.json
       format: json
       expr: "[?accountID == ${account_id}] | [0].events[?name == '${event.eventName}'] | [0].whitelist.entity[?value == '${event.UserIdentity.Username}'] | [0].objects[?value == '${event.requestParameters.BucketName'] | [0].value"
```
