### ISSUE TITLE
ebs-unused volumes delete action: --dry-run is not helpful; value filter gives misleading output

### ISSUE THREAD

**Issue by saishandilya** [cloud-custodian/cloud-custodian#5317]
I am creating a custodian policy for my use case for ebs which should take delete action against the ebs volumes which are in available state which does not have a specific tag(i.e., c7n_keep) and the creation date of the volume is greater than 7 days.

Here is my policy:
```yaml
policies:
  - name: ebs-training-cleanup
    resource: ebs
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - Attachments: []
      - State: available
      - "tag:c7n_keep": absent
      - type: value
        value_type: age
        key: CreationTime
        value: 7
        op: gt      
    actions:
      - delete
```
I noticed when I perform a --dryrun, the count shows 0 while 3 volumes out of 11 does not have tags and among them 2 volumes are having age greater than 7.

Expected output : Must be count 2

output : 
```shell
sai@DESKTOP:/mnt/e/Library/Desktop/work/cloud-custodian/$ custodian run --dryrun --cache-period=0  custodian_policy_delete_ebs.yml -s out --region=us-east-1
2020-02-06 18:34:28,490: custodian.policy:INFO policy:ebs-training-cleanup resource:ebs region:us-east-1 count:0 time:3.28
```
When I tried another test case by removing value filter:

```yaml
policies:
  - name: ebs-training-cleanup
    resource: ebs
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - Attachments: []
      - State: available
      - "tag:c7n_keep": absent
    actions:
      - delete
```

output : 
```shell
sai@DESKTOP:/mnt/e/Library/Desktop/work/cloud-custodian/$ custodian run --dryrun --cache-period=0  custodian_policy_delete_ebs.yml -s out --region=us-east-1
2020-02-06 18:39:49,952: custodian.policy:INFO policy:ebs-training-cleanup resource:ebs region:us-east-1 count:3 time:5.41
```
Not sure why the value filter is not working as expected and when the dry run is performed it is showing mis leading output.

Please help me through this.
