### ISSUE TITLE
gcp - cscc - post finding failing in c7n version 0.8.46.1

### ISSUE THREAD

**Issue by andreww51** [cloud-custodian/cloud-custodian#5336]
c7n version: 0.8.46.1

```yaml
policies:
  - name: buckets
     description: custodian
     resource: gcp.bucket
     actions:
       - type: post-finding
          org-domain: mydomainname.com
          org-id: 1234567891234
          category: mynewcategory
```

Company policy prevents me doing copy/paste, but the stack calls are:
```
c7n/cli.py 374
c7n/commands.py 141
c7n/commands.py 283
c7n/policy.py 1049
c7n/policy.py 320
c7n_gcp/actions/cscc.py 80
c7n_gcp/actions/core.py 73
c7n_gcp/actions/core.py 81
c7n_gcp/actions/core.py 87
c7n_gcp/client 392
<snip> ... </snip>
googleapiclient/http.py 856

googleapiclient.errors.HttpError:
<HttpError 400 when requesting https://securitycentre.googleapis.com/v1beta/organizations/1234567891234/sources/22222/findings?33333=id&alt=json returned "Source property is invalid. All names must start with a letter; contain only letters, numbers and underscores; and be at most 256 characters long">
```

Where orgid, sourceid and findingId are obfuscated here.
