### ISSUE TITLE
mailer - email all members of project

### ISSUE THREAD

**Issue by bhl0424** [cloud-custodian/cloud-custodian#5340]
This is the example in the docs for mailer:
```
policies:
  - name: bad-apples
    resource: asg
    filters:
     - "tag:ASV": absent
    actions:
      - type: notify
        template: default
        template_format: 'html'
        priority_header: '1'
        subject: fix your tags
        to:
          - resource-owner
        owner_absent_contact:
          - foo@example.com
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/80101010101/cloud-custodian-message-relay
```
What would be the best way to replace resource-owner with a custom-tag, and use that custom-tag value to look-up a list of email addresses?

For example:
```
policies:
  - name: bad-apples
    resource: asg
    filters:
     - "tag:ASV": absent
    actions:
      - type: notify
        template: default
        template_format: 'html'
        priority_header: '1'
        subject: fix your tags
        to:
          - project-name
        project_contacts: s3://bucket/project_contacts.yml
        transport:
          type: sqs
          queue: https://sqs.us-east-1.amazonaws.com/80101010101/cloud-custodian-message-relay
```
Let's say the resource has a project-name tag with value "Project-A"

I want to have mailer look up all the people under Project-A in a file and email those people

s3://bucket/project_contacts.yml:
```
Projects:
    Project-A:
      - addrs1@mail.com
      - addrs2@mail.com
      - ...
```
