### ISSUE TITLE
Lambda policy returns empty resources "Resources []" when fetching CloudTrail events (WAF) that contains an array in requestParameters

### ISSUE THREAD

**Issue by tcdev00** [cloud-custodian/cloud-custodian#5365]
I am getting a `Resources []` in the Lambda execution when trying to fetch a WAF CloudTrail event.
The main difference I found between WAF events and other events, is that WAF contains an array "updates" inside `requestParameters`.

Policy:
```
policies:
  - name: waf-updateipset
    resource: waf
    region: us-east-1
    mode:
      type: cloudtrail
      role: "arn:aws:iam::{account_id}:role/rolethatworks"
      events:
        - source: waf.amazonaws.com
          event: UpdateIPSet
          ids: 'requestParameters.iPSetId'
```

CloudTrail event:
```
    "eventTime": "date",
    "eventSource": "waf.amazonaws.com",
    "eventName": "UpdateIPSet",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "241.241.241.241/32",
    "userAgent": "console.amazonaws.com",
    "requestParameters": {
        "updates": [
            {
                "iPSetDescriptor": {
                    "type": "IPV4",
                    "value": "241.241.241.241/32"
                },
                "action": "DELETE"
            }
        ],
        "changeToken": "999j3e49-eg4e-1949-hqf2-44eh3d99w4g3",
        "iPSetId": "34107265-94le-7foe-y85s-w91f20r1i944"
    },
    "responseElements": {
...
```

Lambda output: (Unexpected behavior)
```
[INFO]  date  456asdf5-asdf-435d-das5-4ds8hj83yu0f  Found resource ids:['34107265-94le-7foe-y85s-w91f20r1i944']

[INFO]  date  456asdf5-asdf-435d-das5-4ds8hj83yu0f  Resources []
```

I have found in gitter a person who also has this same problem with another resource which CloudTrail event also contains an array in the `requestParameters`. In his case he tries to fetch for `ChangeResourceRecordSets` and gets also a `Resources []`. This is not my case but we both got into the same dead end, for what I suspect that the array can be the cause.

**If this is expected, how we should approach this?**

**The expected behavior:**
Get resources `iPSetDescriptor` and `action` inside the `Resources` output.

**Actual behavior**
Resources array is empty: `Resources []`
