### ISSUE TITLE
rds-unused volumes delete action: create single policy to delete both deletion termination enable and disabled Instances.

### ISSUE THREAD

**Issue by saishandilya** [cloud-custodian/cloud-custodian#5370]
I am creating a custodian policy for my use case for rds which should take delete action against the rds instances which are in available state which does not have a specific tag(i.e., c7n_keep) and the creation date of the instance is greater than 7 days.

When I tried to run the custodian on every saturday.

Here is my policy:
policies:
  - name: rds-training-cleanup
    resource: rds
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - "tag:c7n_keep": absent
      - type: value
        value_type: age
        key: InstanceCreateTime
        value: 7
        op: gt
    actions:
      - delete

I noticed when I perform a deployment it did not delete all the rds instances.When I checked the logs I can see the error:
[ERROR]	2020-02-15T23:59:07.223Z	ff0193ec-1d5e-4b89-9bac-20de86dc5124	Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 254, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/rds.py", line 601, in process
    client.delete_db_instance(**params)
  File "/var/runtime/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidParameterCombination) when calling the DeleteDBInstance operation: Cannot delete protected DB Instance, please disable deletion protection and try again.

Some of the RDS Instance are deletion protection enabled.So it is not able to delete them.
When I check the custodian policies for RDS,there is a policy with deletion protection filter and the action is modify-db .

I have created another policy:
policies:
  - name: rds-training-cleanup
    resource: rds
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - "tag:c7n_keep": absent
      - type: value
        value_type: age
        key: InstanceCreateTime
        value: 7
        op: gt
      - DeletionProtection: true
    actions:
      - type: modify-db
        update:
          - property: 'DeletionProtection'
            value: false
        immediate: true
      - type: delete
        skip-snapshot: false

But it is work only for the deletion protection enabled and action is taken against that rds instances only.

I am trying for a custodian policy which can take deletion action against all the instances which does not have c7n_keep tag,whether they are deletion protection is enabled or disabled and which are older than 7 days.
For this I have created another policy:
policies:
  - name: disable-rds-deletion-protection
    resource: rds
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - DeletionProtection: true
    actions:
      - type: modify-db
        update:
          - property: 'DeletionProtection'
            value: false
        immediate: true

  - name: rds-delete
    resource: rds
    mode:
      type: periodic
      schedule: "cron(59 23 ? * SAT *)"
      role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
    filters:
      - "tag:c7n_keep": absent
      - type: value
        value_type: age
        key: InstanceCreateTime
        value: 7
        op: gt
    actions:
      - type: delete
        skip-snapshot: false

Instead of two policies is there any possible way to use one policy to work with my use case.

Please help me through this.

**Comment by PratMis** [comment]
You can try removing  `DeletionProtection: true` from your policy. Something like this:
```
name: rds-training-cleanup
resource: rds
mode:
  type: periodic
  schedule: "cron(59 23 ? * SAT *)"
role: arn:aws:iam::XXXXXXXXXXXXX:role/Custodian-Cleanup-Role
filters:
  - "tag:c7n_keep": absent
  - type: value
     value_type: age
     key: InstanceCreateTime
     value: 7
     op: gt
actions:
  - type: modify-db
    update:
      property: 'DeletionProtection'
      value: false
      immediate: true
  - type: delete
    skip-snapshot: false
```
Custodian wouldn't take any action on the resources that have `DeleteProtection: false` already!

**Comment by saishandilya** [comment]
@PratMis thanks for the suggestion,I have tried that and it is working fine.I am able to update the rds instances with deletion protection and delete the instances without tags greater than 7 days.

I just observed one thing with aurora databases,It is just deleting the instances inside the cluster not the cluster and turned the cluster to 0 instances.

Similar to the above thing as you suggested.Is there any possible way to work around with my use case instead of again using another policy with rds-cluster.

Can we use the same policy with rds-cluster changes so that we can use one policy to work with both instances and clusters.

**Comment by PratMis** [comment]
There's a separate resource type to support `rds-cluster`. You can view the schema using `custodian schema aws.rds-cluster`. 
Sample policy:
```

            policies:
              - name: disable-db-cluster-deletion-protection
                resource: rds-cluster
                filters:
                  - DeletionProtection: true
                  - PubliclyAccessible: true
                actions:
                  - type: modify-db-cluster
                    attributes:
                        CopyTagsToSnapshot: true
                        DeletionProtection: false
```
