### ISSUE TITLE
Can I use one policy with one specific account using c7n-org?

### ISSUE THREAD

**Issue by ismferd** [cloud-custodian/cloud-custodian#5398]
I'm using  c7n-org to deploy several policies in several AWS accounts, so I'm getting a use case where a policy will apply just to one account. 

I see `-p POLICY_FILTERS, --policies POLICY_FILTER` but I didn't find examples to watch how it work.

Do you know what I mean?

**Comment by kapilt** [comment]
afaicr, its `-a account_name -p policy_name` to do one policy on one account.

**Comment by ismferd** [comment]
So then having this policy:
```
policies:
  - name: gov-copy-instance-tags
    resource: ebs
    mode:
      type: periodic
      schedule: 'cron(*/15 * * * ? *)'
      role: c7n_cloud_custodian_role
      tags:
        env: cot
        role: cloudcustodian
        service: copy_tags
        owner: governance
        team: infrastructure
    filters:
      - type: value
        key: "Attachments[0].Device"
        value: not-null
    actions:
      - type: copy-instance-tags
        tags:
          - Name
      - type: copy-instance-tags
        tags:
          - Environment
      - type: copy-instance-tags
        tags:
          - context
      - type: copy-instance-tags
        tags:
          - app
```
and this kind of config file:
```
accounts:
- account_id: 'XX'
  name: qa
  regions:
  - us-east-1
  role: arn:aws:iam::XX:role/your_cloud_custodian_role
- account_id: 'XXX'
  name: pro
  regions:
  - us-east-1
  role: arn:aws:iam::XXX:role/your_cloud_custodian_role
```
Can I deploy the policy one only pro account matching tags between policy and account section?
