### ISSUE TITLE
Plug in custom filter logic?

### ISSUE THREAD

**Issue by glb** [cloud-custodian/cloud-custodian#5415]
Is it possible to plug in custom filter logic?

I would like to create a filter that identifies resources that are past the date in a "valid until" tag, much like `marked-for-op` does, but without the extra characters in the tag value that would be required to just re-use `marked-for-op`.

[Sample code](https://github.com/glb/cloud-custodian/commit/050b93b5824232ad01bccadeb6faeab6d061747a)

I'd be willing to contribute this back if there's interest for it, but if there's not I don't particularly want to have a long-lived fork of the whole project, so it would be great if there were a way to register this filter. I'm hoping that there is and I just haven't read the right part of the docs yet.

Sample policy:

```yaml 
      policies:
         - name: ec2-stop-expired
           resource: ec2
           filters:
             - type: valid-until
               # The default tag used is valid_until
               # but that is configurable
               tag: valid_until
               # Another optional tag is skew
               tz: utc
           actions:
             - type: stop
```
