### ISSUE TITLE
[ERROR] InvalidOutputConfig: Invalid c7n.output.tracer: xray

### ISSUE THREAD

**Issue by FireballDWF** [cloud-custodian/cloud-custodian#5430]
**Describe the bug**
Error on invocation of a mode=hub-action policy which has the execution-option of "tracer: xray".

**To Reproduce**
1. Deploy policy.  
2. click the checkbox for any finding in same account
3. Select Actions->Ec2 PostOpsItem
4. Observe Traceback

**Expected behavior**
Expect AWS XRay tracing to be enabled

**Background (please complete the following information):**
 - OS: AmazonLinux2 using Docker file produced in https://github.com/cloud-custodian/cloud-custodian/pull/5429
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.9-dev]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
   - name: PostOpsItem
    description: Posts an Item to Systems Manager OpsCenter
    resource: ec2
    mode:
        type: hub-action
        role: arn:aws:iam::{account_id}:role/CloudCustodian
        member-role: arn:aws:iam::{account_id}:role/CloudCustodianMember
        memory: 128
        packages: [botocore, boto3, urllib3, aws_xray_sdk]
        execution-options:
          tracer: xray
        tags:
          CostCenter: SecurityHubWorkshop
          CreatedBy: CloudCustodian
    actions:
      - type: post-item
        priority: 3
```
 - Traceback: [if applicable, please exclude sensitive/account information]
[ERROR] InvalidOutputConfig: Invalid c7n.output.tracer: xray
Traceback (most recent call last):
  File "/var/task/custodian_policy.py", line 4, in run
    return handler.dispatch_event(event, context)
  File "/var/task/c7n/handler.py", line 172, in dispatch_event
    policies = PolicyCollection.from_data(policy_data, policy_config)
  File "/var/task/c7n/policy.py", line 88, in from_data
    policies = [Policy(p, options, session_factory=sf)
  File "/var/task/c7n/policy.py", line 88, in <listcomp>
    policies = [Policy(p, options, session_factory=sf)
  File "/var/task/c7n/policy.py", line 857, in __init__
    self.ctx = ExecutionContext(self.session_factory, self, self.options)
  File "/var/task/c7n/ctx.py", line 56, in __init__
    self.tracer = tracer_outputs.select(self.options.tracer, self)
  File "/var/task/c7n/output.py", line 64, in select
    raise InvalidOutputConfig("Invalid %s: %s" % (
**Additional context**
Could not find any documentation on this execution option or how to enable x-ray tracing in c7n, so found syntax from line 35 of https://github.com/cloud-custodian/cloud-custodian/blob/master/tests/test_handler.py
