### ISSUE TITLE
IAM filtering potential fix for 'all' operator

### ISSUE THREAD

**Issue by krampton20** [cloud-custodian/cloud-custodian#5443]
Filtering iam-roles for all usage greater than a certain date did not function as I believed it should.  To my understanding this filter should show roles with no usage for the last 5 days, but was showing roles that had been used.

```yaml
resource: iam-role
    filters:
      - type: usage
        match-operator: all
        LastAuthenticated:
          type: value
          value_type: age
          op: greater-than
          value: 5
```

There were 2 changes that enabled this filter to function per my understanding.

c7n/resources/iam.py:469 - Add an additional "and match_operator!= 'all'" to the condition so that this will not fire for 'all' operators that only returned a partial number of true responses.

c7n/filters/core.py:616 - change 0 to "parse_date('1970-01-01 00:00:00.000000+00:00')" so that comparisons to other datetime objects will compare against a pre-cloud date for null values rather than error out for non-comparable types.

**Comment by kapilt** [comment]
fwiw, iam roles have native attributes for last usage date now, you can simply use

```
type: value
key: RoleLastUsed.LastUsedDate
value_type: age
op: greater-than
value: 5
```

regarding usage filter.

iam - I don't see what you mean, a) all doesn't apply to your example your doing a single attribute check, b) the logic here seems fine c) rather than list line numbers that that will be broken in a day,. send a pr or link to a particular line and use actual code.
core - converting nulls to default arbitrary date values is highly implicit, if you want to distinguish be explicit.

please use an bug issue template (versions, valid policy) and supply a representative sample of the usage report of the role in question that you feel like is being matched erroneously.

**Comment by kapilt** [comment]
I think I see what you mean by re the `iam` code ref for match-operator: all, but please note for future bug reports, does not work as I expected without data and versions numbers per the existing bug report template, is a significant time burden to any issue responder to try and reconstruct.

**Comment by kapilt** [comment]
with #5449 as an example of equivalent policies that both return what your looking for using usage filter or role usage attributes. keep in mind usage is setup to answer more detailed questions wrt to specific service usage that go beyond your use case. for your use case, the role usage attributes filtering entail no api calls though, so would be a preferred mechanism.

```yaml
policies:
 -  resource: iam-role
    name: role-check-usage
    filters:
      - or:
         - type: usage
           match-operator: all
           TotalAuthenticatedEntities: 0
         - not:
             - type: usage
               match-operator: any
               TotalAuthenticatedEntities: 1
               LastAuthenticated:
                 type: value
                 value_type: age
                 op: less-than
                 value: 5

 -  resource: iam-role
    name: role-last-used
    filters:
      - or:
          - RoleLastUsed.LastUsedDate: absent
          - type: value
            key: RoleLastUsed.LastUsedDate
            value_type: age
            op: greater-than
            value: 5
```
