### ISSUE TITLE
AWS: S3 confliction operation error

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5460]
**Describe the bug**
When I create a bucket there are two policies with two actions:

1. auto-owner tag:
```
  actions:
  - type: auto-tag-user
    tag: Owner
```

and

2. If not tag mark for deletion
```
    actions:
      - type: mark-for-op
        tag: c7n_s3_untagged
        op: delete
        hours: 12
```

**Background (please complete the following information):**
 - Cloud Provider: [aws]

 - Traceback: [if applicable, please exclude sensitive/account information]

```
An error occurred (OperationAborted) when calling the PutBucketTagging operation: A conflicting conditional operation is currently in progress against this resource. Please try again.
```

The reason is both the policies try to tag the bucket at the same time.

**Comment by kapilt** [comment]
`triggered when an s3 bucket` ..  could you finish that sentence or at have a complete policy example (sanitized no account ids) here?

**Comment by tomarv2** [comment]
1st policy:

```
- name: auto-owner-s3
  resource: s3
  mode:
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/custodian
    events:
    - event: CreateBucket
      ids: requestParameters.bucketName
      source: s3.amazonaws.com
  filters:
  - tag:Owner: absent
  - type: event
    key: detail.userIdentity.principalId
    value: '@tomarv2.com'
    op: contains
  actions:
  - type: auto-tag-user
    tag: Owner
```

2nd policy:

```
- name: mark-untagged-s3
  resource: s3
  mode: 
    type: cloudtrail
    role: arn:aws:iam::{account_id}:role/Custodian
    events:
      - CreateBucket
  filters:
    - "tag:Owner": absent
  actions:
    - type: mark-for-op
      tag: c7n_s3_untagged
      op: delete
      hours: 12
```

**Comment by tomarv2** [comment]
This seems to be have worked:

I looked at the tagging code a bit, if there are multiple tags they will be pushed using one call:

```
        tags = self.data.get('tags')

        if tags is None:
            tags = []
        else:
            tags = [{'Key': k, 'Value': v} for k, v in tags.items()]

        if msg:
            tags.append({'Key': tag, 'Value': msg})
```

This is how I updated the policy, I merged the above two policies into one:

```
  - name: mark-untagged-s3
    resource: s3
    mode: 
      type: cloudtrail
      role: "arn:aws:iam::{account_id}:role/CustodianGuard"
      events:
        - CreateBucket
    filters:
      - "tag:Owner": absent
      - type: event
        key: detail.userIdentity.principalId
        value: '@tomarv2.com'
        op: contains
    actions:
      - type: auto-tag-user
        tag: Owner
      - type: mark-for-op
        tag: c7n_s3_untagged
        op: delete
        hours: 1
```
this will put 2 tags to s3 bucket whenever possible, but the 2nd tag will be removed when I try to do a check if bucket is tagged or not.

```
  - name: untagged-s3-unmark
    resource: s3
    mode: *hourly-mode
    region: us-east-2  
    filters:
      - "tag:Owner": present
      - "tag:c7n_s3_untagged": present
    actions:
      - type: unmark
        tags: ["c7n_s3_untagged"]
      - type: notify
        subject: "[AWS Policy] [Account: {{account_id}}] S3 - Previously Untagged S3 Unmarked!"
        violation_desc: |
            "S3 that previously had no Owner tag is now showing Owner
            tag and it has been unmarked for deletion."
        action_desc: "Actions Taken: S3 have been unmarked. No further action needed"
        to:
          - vtomar@tomarv2.com
        transport:
          type: sns
          topic: "arn:aws:sns:us-east-2:1234567890:mailer-nonprod-us-east-2-notify"
```
