### ISSUE TITLE
AWS.RDS cannot enable enhanced monitoring or performance insights

### ISSUE THREAD

**Issue by mayerg11** [cloud-custodian/cloud-custodian#5484]
**Describe the bug**
I'm trying to run through all of our RDS instances and turn on Enhanced Monitoring and Performance Insights.  It throws an error on each.

**Enhanced Monitoring:**
botocore.exceptions.ClientError: An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0.
--I see nowhere to enter the MonitoringRoleArn

**Performance Insights**
  File "/Users/greg.mayer/custodian/lib/python3.7/site-packages/c7n/resources/rds.py", line 1640, in process
    if r[update['property']] != update['value']:
KeyError: 'EnablePerformanceInsights'

**To Reproduce**
I run the following yaml.  Can comment out whichever you are testing
_custodian run -s . rds-enable-perf-insights.yaml_
```yaml
policies:
  - name: enable-rds-perf-insights
    resource: rds
    filters:
      - PerformanceInsightsEnabled: false
      - tag:Team: aa-gm
    actions:
      - type: modify-db
        update:
          - property: 'PerformanceInsightsKMSKeyId'
            value: (default) aws/rds
          - property: 'EnablePerformanceInsights'
            value: true
          - property: 'MonitoringInterval'
            value: 60
        immediate: true
```

**Expected behavior**
I would expect the necessary actions, MonitoringRoleArn and EnablePerformanceInsights, to be available and to work properly to allow for updating existing RDS DB.

**Background (please complete the following information):**
 - OS: OSX 10.15.2
 - Python Version: Python 3.7.2
 - Custodian Version: 0.8.46.1
 - Tool Version: n/a
 - Cloud Provider: aws
 - Policy: 
admin user
*:*
 - Traceback: [if applicable, please exclude sensitive/account information]

**Additional context**
