### ISSUE TITLE
Azure: 'auto-tag-user' is not showing as valid option

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5527]
**Describe the bug**

```
policies:
  - name: custom-auto-owner-vm
    resource: azure.vm
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.Compute/virtualMachines',
          event: 'write'
        }]
    filters:
      - "tag:Owner": null
    description: |
      Tag all new VMs with the 'Owner Email' tag.
      Note: 'resource-type' filter is not required because the policy is not triggered by other resources.
    actions:
      - type: auto-tag-user
        tag: Owner
```

Output in logs: 

```
Invalid policy file /tmp/tmp99uo512t/resources-autotag.yml Invalid action type auto-tag-user, valid actions ['notify', 'webhook', 'delete', 'logic-app']
Job "Host.update_policies (trigger: interval[0:01:00], next run at: 2020-04-01 05:15:48 UTC)" executed successfully
Running Azure Cloud Custodian Self-Host
```

```
custodian schema azure.vm.actions
azure.vm:
  actions:
  - auto-tag-date
  - auto-tag-user
  - delete
  - lock
  - logic-app
  - mark-for-op
  - notify
  - poweroff
  - restart
  - start
  - stop
  - tag
  - tag-trim
  - untag
  - webhook
```

**Comment by kapilt** [comment]
what version of custodian is this?

**Comment by tomarv2** [comment]
```docker_image                = "cloudcustodian/c7n:0.8.46.1"```

**Comment by logachev** [comment]
@tomarv2 it looks like you're running containerhost, right?

**Comment by tomarv2** [comment]
yes, I am using ACI for deployment. My concern is the event is not getting triggered at all. I tried adding a ```notify section``` just to see where is the issue and even that dint trigger. So, I am guessing something is not working with event is not right.

**Comment by logachev** [comment]
Let me try to run it.. I have a theory on why you see this error and it should be an easy fix.

Also, please note that for containerhost we use separate mode: https://cloudcustodian.io/docs/azure/configuration/containerhosting.html#event-based

It is `container-timer` and `container-event`.. You current policy deploys Azure Function to run the policy.

**Comment by tomarv2** [comment]
this is my policy for auto-tagging:

```
  - name: custom-auto-owner-storage-account
    resource: azure.storage
    mode:
      type: azure-event-grid
      events: [{
          resourceProvider: 'Microsoft.Storage/storageAccounts',
          event: 'write'
        }]
    filters:
      - "tag:Owner": null
    description: |
      Tag all new StorageAccounts with the 'Owner email' tag.
    actions:
      - type: auto-tag-user
        tag: Owner
      - *notify
```

this is my policy if the storage account is made public:

```
policies:
  - name: custom-storage-account-public
    description: |
      Find all storage accounts with public access
    resource: azure.storage
    mode:
      type: container-event
      events: [{
        resourceProvider: 'Microsoft.Storage/storageAccounts',
        event: 'write'
        }]
    filters:
      - type: value
        key: properties.networkAcls.ipRules
        value_type: size
        op: equal
        value: 0
    actions:
      - <<: *notify
        subject: "[Azure Policy] [Subscription: {{ account_id }}] Storage accounts with public access"
        violation_desc: "Storage accounts with public access"
```

2nd one works

If I change `type: azure-event-grid` to `type: container-event` in 1st policy, it does not work as it is not supported.
