### ISSUE TITLE
AWS resources with tag restrictions can't fully use OffHours

### ISSUE THREAD

**Issue by aliciasteen** [cloud-custodian/cloud-custodian#5534]
Hi, I'm setting up a shutdown schedule for RDS and know that RDS tags cannot have the characters needed in them. As a workaround, I am creating a custom policy for RDS with specific values set. The trouble I am facing is the policy I want to implement specifies days to shutdown "off=[(S,1)];on=[(M,6)];tz=it". 

Can the functionality of the Tag be added into the custodian policy.

**Comment by kapilt** [comment]
sounds like being able to specify a  default tag value on offhour/onhour filters would suffice?

**Comment by aliciasteen** [comment]
@aliciasteen yes, being able to specify the default tag value would work, as long as you can still opt-in with the tag. 
Something like
```
 - name: stop-after-hours-rds
    resource: rds
    filters:
      - type: offhour
        opt-out: false
        tag: ShutdownSchedule
        tag-default-schedule: "off=[(S,1)];on=[(M,6)];tz=it".
    actions:
      - stop
```
