### ISSUE TITLE
Azure policy run in all regions

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#5549]
Running c7n in Azure using ACI in us-east-1. How do I run a policy in all the regions?

Here is my policy:

```
policies:
  - name: sql-servers
    resource: azure.sql-server
    mode:
      type: container-periodic
      schedule: '*/5 * * * *'
    filters:
      - type: cost
        timeframe: WeekToDate
        op: gt
        value: 10
    actions:
      - <<: *notify
        subject: "[Azure Policy] [Subscription: {{ account_id }}] MySql server cost is over $10"
```

I was thinking adding `region: all` will make it run in all regions, but getting an error:

```
Skipping policy:sql-servers target-region:all current-region:us-east-1
my policy says:
```

```
  - name: sql-servers
    resource: azure.sql-server
    region: all <--  all regions
```
