### ISSUE TITLE
ec2 tenancy

### ISSUE THREAD

**Issue by Mike-Landers** [cloud-custodian/cloud-custodian#5579]
I want to create a simple ec2 policy which finds all instances with default tenancy. I've tried:

```
policies:
  - name: ec2-tenancy
    resource: aws.ec2
    filters:
      - "tenancy": default
```

I have also tried:
```
policies:
  - name: ec2-tenancy
    resource: aws.ec2
    filters:
      - type: value
        key: tenancy
        value: default
```

This returns count:0 while I'm logged into our aws account as admin, in an account with many ec2 instances with default tenancy. I tried switching the value from default to dedicated and host. count:0 is always returned. Other filters such as tags etc work as expected. @kapilt 

custodian run --dryrun -c ec2-tenancy.yml -s out
2020-04-09 15:24:48,251: custodian.policy:INFO policy:ec2-tenancy resource:aws.ec2 region:us-west-2 count:0 time:1.34

also tangent question- can default tenancy be detected for RDS instances?
