### ISSUE TITLE
aws: ecr.actions.set-lifecycle's countUnit says it is required for countType imageCountMoreThan

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5593]
**Describe the bug**
ecr.actions.set-lifecycle's countUnit says it is required for countType imageCountMoreThan when it should only used when the countType is set to sinceImagePushed.

> The tagPrefixList parameter is only used if tagStatus is tagged. The countUnit parameter is only used if countType is sinceImagePushed. The countNumber parameter is only used if countType is set to imageCountMoreThan. 

Ref: https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html

**To Reproduce**

1. Create policy
2. Run policy

**Expected behavior**
Policy should work without having to set countUnit

**Background (please complete the following information):**
 - OS: OSX 10.15
 - Custodian Version: custodian-cask
 - Policy:
```yaml
policies: 
  - name: ecr-no-lifecycle
    resource: aws.ecr
    filters:
      - type: lifecycle-rule
        state: false
    actions:
      - type: set-lifecycle
        rules:
          - rulePriority: 1
            description: "Cleans up older untagged images"
            selection:
              tagStatus: untagged
              countType: imageCountMoreThan
              # c7n requirement. value is ignored because the type is NOT sinceImagePushed
              # countUnit: days
              countNumber: 5
            action:
              type: expire
```
 - Traceback: [if applicable, please exclude sensitive/account information]
```
✗ custodian-cask run -c test-policies/ecr-no-lifecycle.yml --dryrun -s out --verbose --cache-period 0

Custodian Cask 20190904.1 (cloudcustodian/c7n:latest)
Skipped image pull - Last checked 16 minutes ago.

2020-04-14 17:11:07,137: custodian.commands:ERROR invalid policy file: /home/custodian/ecr-no-lifecycle.yml error: Failed to validate policy ecr-no-lifecycle
 Error on policy:ecr-no-lifecycle resource:ecr
'countUnit' is a required property

Failed validating 'required' in schema[12]['properties']['rules']['items']['properties']['selection']:
    {'addtionalProperties': False,
     'properties': {'countNumber': {'type': 'integer'},
                    'countType': {'enum': ['imageCountMoreThan',
                                           'sinceImagePushed']},
                    'countUnit': {'enum': ['hours', 'days']},
                    'tagPrefixList': {'items': {'type': 'string'},
                                      'type': 'array'},
                    'tagStatus': {'enum': ['tagged', 'untagged', 'any']}},
     'required': ['countType', 'countUnit'],
     'type': 'object'}

On instance['rules'][0]['selection']:
    {'countNumber': 5,
     'countType': 'imageCountMoreThan',
     'tagStatus': 'untagged'}
2020-04-14 17:11:07,137: custodian.commands:ERROR Found 1 errors.  Exiting.
```
 - `custodian version --debug` output

**Additional context**
