### ISSUE TITLE
Retrieving EC2 Instances that are NOT Managed by SSM

### ISSUE THREAD

**Issue by jgaudy** [cloud-custodian/cloud-custodian#5596]
Is there a simple way to retrieve EC2 instances that are NOT managed by SSM? The resource type `ssm-managed-instance` makes it easy to retrieve instances that are managed by SSM, but I haven't found a simple way to retrieve those that are not SSM managed.

**Important Note:** I am looking for a way that does NOT rely on filtering by Config compliance.

**Comment by kapilt** [comment]
try

```
filters:
   - not:
        - type: ssm
           key: InstanceId
           value: present
```
