### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded

### ISSUE THREAD

**Issue by bostrowski13** [cloud-custodian/cloud-custodian#5598]
**Describe the bug**
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded

**To Reproduce**
Run the policy below

**Expected behavior**
Return a list of log groups that haven't been written to in 7 days

**Background (please complete the following information):**
 - OS: Windows
 - Python Version: Python 3.6.5
 - Custodian Version: 0.8.46.1
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: cloudwatch-log-group-stale-log-groups
    resource: log-group
    description: |
      Gets all Cloudwatch Logs Groups that haven't been written to in 7 days
    comments: |
      Gets all Cloudwatch Logs Groups that haven't been written to in 7 days
    mode:
      type: periodic
      role: MY_ROLE
      schedule: "rate(1 day)"
      timeout: 300
    filters:
      - type: last-write
        days: 7
```

**Additional context**
I see this is cited before as fixed, but I also see more improvement coming to retryies and backoff in https://github.com/cloud-custodian/cloud-custodian/pull/5564

I also have this happen on PutRetentionPolicy for log groups as well.
