### ISSUE TITLE
Metrics are not applied for Network load balancers when used in filter

### ISSUE THREAD

**Issue by classickar** [cloud-custodian/cloud-custodian#5611]
**Describe the bug**
Working on a filter criteria by applying the metrics 'ActiveFlowCount' with stats 'Sum' did not give any result.There was no result even with other metrics and statisic combinations.

**To Reproduce**
1. Create a network load Balancers such that it is under utilized.
2. Run the c7n policy provided below
https://gitter.im/cloud-custodian/cloud-custodian?at=5e94c9f1d021c45cc7e33280
**Expected behavior**
A list of NLB must be filtered based on the set filter criteria.
https://gitter.im/cloud-custodian/cloud-custodian?at=5e94c9f1d021c45cc7e33280

**Background (please complete the following information):**
 - OS: amazon 2018.03
 - Python Version: Python 2.7.16
 - Custodian Version: 0.8.46.1
 - Cloud Provider: aws

```yaml
policies: 
resource: app-elb
filters:
 - type: value                                                              
   key: LoadBalancerArn                                                     
   op: contains                                                             
   value: loadbalancer/net                                                  
 - type: metrics                                                            
   name: ActiveFlowCount                                                    
   statistics: Sum                                                          
   days: 14                                                                 
   value: 100
   op: less-than
```
https://gitter.im/cloud-custodian/cloud-custodian?at=5e94c9f1d021c45cc7e33280
