### ISSUE TITLE
rds-subnet-group "unused" filter finding in-use groups (not filtering at all)

### ISSUE THREAD

**Issue by bostrowski13** [cloud-custodian/cloud-custodian#5628]
**Describe the bug**
I'm using the "unused" filter on the "aws.rds-subnet-group" resource and it is not filtering based on the resource being unused.  Specifically, it looks like its not filtering at all and I'm getting a list of all my db subnet groups.  I'm using the policy for "unused" in the resource docs at https://cloudcustodian.io/docs/aws/resources/rds-subnet-group.html.

**To Reproduce**
Run with the filter below

**Expected behavior**
Find unused RDS DB Subnet Groups (or none, if there aren't any)

**Background (please complete the following information):**
 - Python Version: python 3.7.x
 - Custodian Version: e.g. 0.8.46.1
 - Cloud Provider: aws
 - Policy: 
```yaml
policies:
  - name: rds-subnet-group-delete-unused
    resource: rds-subnet-group
    filters:
      - unused
```

**Additional context**
We are using Aurora Serverless RDS Clusters.
Resources are named like: <unique_id>-<env>-dbcluster
Subnet Groups are named like:  <unique_id>-<env>-db-subnet-group
