### ISSUE TITLE
Tag everything: log groups and event rules if specified in mode

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#5644]
**Is your feature request related to a problem? Please describe.**
I'd like to see custodian tag everything it creates. So far I've found that log groups and event rules do not receive these tags.

**Describe the solution you'd like**

It should reuse the tags already defined in `mode`.

```yaml
    mode:
      tags:
        application: cloud-custodian
        env: production
```

This should be for custodian policies as well as the custodian mailer.

**Describe alternatives you've considered**
Tag resources manually

**Additional context**

```bash
aws logs \
  list-tags-log-group \
  --log-group-name "/aws/lambda/cloud-custodian-mailer"
aws events \
  list-tags-for-resource \
  --resource-arn arn:aws:events:us-west-2:1234567890:rule/cloud-custodian-mailer
```

**Comment by kapilt** [comment]
for logs.. at least for lambdas policies, we're not pre-provisioning log groups, they are created on demand atm.

the other resources (cloud watch event targets, etc), are a little more straight forward to handle, where they support tagging.

**Comment by nitrocode** [comment]
@kapilt Could we provision the log groups then? That way we can be explicit rather than implicit and have more control over the infrastructure.

**Comment by kapilt** [comment]
sure, its sw, anything is possible.. but noting that its a more significant level of effort on logging as it will need some refactoring.

**Comment by tjstansell** [comment]
I have custodian policies that set the retention on my custodian log groups ... the same could be done for adding tags.

**Comment by nitrocode** [comment]
> sure, its sw, anything is possible.. but noting that its a more significant level of effort on logging as it will need some refactoring.. contribs welcome 😄

Great! Might be something I can look into.



> I have custodian policies that set the retention on my custodian log groups ... the same could be done for adding tags.

Oh nice workaround. I'd prefer it built into the code base but a workaround may work for now. Would you be willing to share your policies around this?

**Comment by tjstansell** [comment]
We use this ...
```yaml
policies:
  - name: run-set-custodian-lambda-retention
    resource: log-group
    filters:
      - type: value
        key: logGroupName
        op: regex
        value: ^\/aws\/lambda\/custodian\-.*$
      - type: value
        key: "retentionInDays"
        op: not-equal
        value: 14
    actions:
      - type: retention
        days: 14

  - name: run-delete-old-custodian-log-groups
    resource: log-group
    filters:
      - type: value
        key: logGroupName
        op: regex
        value: ^(cloud-custodian|\/aws\/lambda\/custodian\-).*$
      - type: last-write
        days: 2
    actions:
      - delete
```
