### ISSUE TITLE
Azure - Functional Tests need to delete EventGrid subscriptions as part of cleanup

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#5665]
**Describe the bug**
Azure Functional Tests need to delete EventGrid subscriptions as part of the clean-up step.

**Work Around**
Simple manual policy to delete all of the EventGrid subscriptions.
```
policies:
  - name: cleanup-eg-subs
    resource: azure.eventsubscription
    actions:
      - type: delete
```
