### ISSUE TITLE
Flexible runtime interpolation of resource variables 

### ISSUE THREAD

**Issue by egunnar** [cloud-custodian/cloud-custodian#5671]
As a custodian user, I'm trying to run custodian against cloudfront and turn on logging and set the s3 prefix based on the DomainName. It would be nice if something like this worked (note `DomainName` is directly in resources.json) :

  ```
policies:
      - name: test
        resource: distribution
        filters:
           - type: distribution-config
             key: Logging.Enabled
             value: false
             op: eq
        actions:
           - type: set-attributes
              attributes:
               Comment: ""
               Enabled: false
               Logging:
                   Enabled: true
                   IncludeCookies: false
                   Bucket: 'c7n-cloudfront'
                   Prefix: '{DomainName}' 
```

One problem with the above is really flexible variable interpolation may break existing policies. Although unlikely what if someone was already using the literal string {DomainName}? To address this what if there was a top level key in the policy called `interpolate_vars:` set to either true or false (with false being the default). 

I imagine the namespace for the expression in the brackets is the resource the action is running against. The expression would be python.  

Another idea - could/should we make custodian evaluate f-strings?

It looks like this has been discussed here some what https://github.com/cloud-custodian/cloud-custodian/issues/2330.
