### ISSUE TITLE
finding filter interacts strangely with cache

### ISSUE THREAD

**Issue by kiwiz** [cloud-custodian/cloud-custodian#5674]
`--cache-period 0` seems to be required if a c7n policy queries a resource and then subsequently updates that resource (otherwise, the findings are stale).
We run policies every hour and the default cache expiry is 15 minutes - I don't fully understand the interaction here, but disabling the cache definitely seems to fix it.

**To Reproduce**

1. Run the policy with caching
2. Run the policy without caching (`--cache-period 0`)
3. Run the policy with caching

**Current behaviour**

Security Hub results are created on step 1 and updated on step 3

**Expected behavior**

Security Hub results are created once and are not updated.

**Background (please complete the following information):**
 - OS: Amazon Linux 2
 - Python Version: Python 3.7.6
 - Custodian Version: 5d62972c13e823b07db58b802ad5b5d5d7be9065
 - Cloud Provider: AWS
 - Policy:
```yaml
- name: ec2-public-ip-address
  resource: aws.ec2
  filters:
  - type: value
    key: PublicIpAddress
    value: not-null
  - not:
    - type: finding
      query:
        RecordState:
        - Comparison: EQUALS
          Value: ACTIVE
  actions:
  - type: post-finding
    severity_normalized: 50
    description: EC2 instance with public IP address
    types:
    - Software and Configuration Checks/AWS Security Best Practices
```
