### ISSUE TITLE
SecurityHub include public ips for EC2 instances

### ISSUE THREAD

**Issue by allisonis** [cloud-custodian/cloud-custodian#5683]
**Describe the bug**
Currently when reporting a finding for an EC2 instance to the Security, an incorrect resource field is used to populate the detail for the resource as a finding. When creating a finding for a public IP violation, the private IP of the EC2 instance is used as the IPV4 address in the finding, not the public IP address. 

The IP value that is reported is only accessible via the API, it is not populated in the UI. This is the resource object structure where IPV4 address is the private IP assigned to the instance
```
  "Resources": [
    {
      "Type": "",
      "Id": "",
      "Region": "",
      "Tags": {
        "",
        "Name": ""
      },
      "Details": {
        "AwsEc2Instance": {
          "Type": "",
          "ImageId": "",
          "IpV4Addresses": [
            "$PRIVATE IP"
          ],
          "IamInstanceProfileArn": "",
          "VpcId": "",
          "SubnetId": "",
          "LaunchedAt": ""
        }
      }
    }
  ],
```

**To Reproduce**
Create a policy to report on `PublicIP` on EC2 instances that publishes a finding to the SecurityHub service. 

```
 - name: public_ip_check
    resource: aws.ec2
    filters:
      - "PublicIpAddress": present
    actions:
      - type: post-finding
        description: |
          Public IP Address
        severity_normalized: 8
        types:
          - "Software and Configuration Checks/Industry and Regulatory Standards/NIST CSF Controls (USA)"
        recommendation: "Remove Public IP"
        recommendation_url: "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html"
        confidence: 100
        compliance_status: FAILED
```

**Expected behavior**
The IPV4 field in the Security hub finding  should be populated with the violating public IP address for a given EC2 instance.
