### ISSUE TITLE
aws - vpc - generic route table filters

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#5705]
**Is your feature request related to a problem? Please describe.**
It would be nice to have route table filters so that policies can check to see if their subnets are attached to any route tables that have public routes, like 0.0.0.0/0.

**Describe the solution you'd like**
A generic filter/base or set of them that could be reused across resources to many effects like checking for network acls, security groups, igw attachment etc.

**Additional context**
A draft PR has been opened but I am adding an issue here for further discussion and collaboration so we can implement it correctly

https://github.com/cloud-custodian/cloud-custodian/pull/5703

**Comment by JohnHillegass** [comment]
In the proposed filter, we could match like this 

```
        policies:
          - name: glue-endpoint-public-route
            resource: aws.glue-connection
            filters:
                - type: route-table
                  key: RouteTables[].Routes[].DestinationCidrBlock
                  value: 0.0.0.0/0
                  op: contains
```
