### ISSUE TITLE
aws - lambda - not able to read tags

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5719]
**Describe the bug**
We have a policy that looks at tags for `resource: lambda` and makes a decision based off the tag
value. The policy filters 2 resources when run with custodian version 0.8.45.3 and almost 90% (more than 1000) resources when run with 0.9.1 

**To Reproduce**
Was not able to reproduce manually, but when we rolled back to 0.8.45.3, the problem seems to get fixed

**Expected behavior**
Should filter couple of resources as happening in the previous version that we're using(0.8.45.3)

**Background (please complete the following information):**
 - OS: docker python:3.6-bionic
 - Python Version: 3.6
 - Custodian Version: 0.9.1
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
  - name: lambda-tag-check
    resource: lambda
    filters:
      - type: value
        key: "tag:x"
        value_from:
          url: *some-list
          format: json
          expr: abc[*].x
        op: not-in
      - type: value
        key: "tag:y"
        value_from:
          url: *some-list
          format: json
          expr: abc[*].y
        op: not-in
      - not:
          - type: value #ignore custodian lambda functions
            key: "FunctionName"
            value: "^custodian-.*"
            value_type: normalize
            op: regex
```
 - Traceback: no traceback seen
 - `custodian version --debug` output

**Additional context**
Looked at the resources.json file and saw that the `Tag` key is missing for all the filtered resources.I suspect all the lambdas for which tags couldn't be retrieved, are flagged.We're still investigating if its a problem with how we run custodian internally but I think its worth putting it out there.
```[
  {
    "FunctionName": "x",
    "FunctionArn": "y",
    "Runtime": "nodejs10.x",
    "Role": "",
    "Handler": "dist/handler.handle",
    "CodeSize": 23398296,
    "Description": "abc",
    "Timeout": 60,
    "MemorySize": 128,
    "LastModified": "2020-03-30T16:09:40.166+0000",
    "CodeSha256": "xyz",
    "Version": "$LATEST",
    "VpcConfig": {
      "SubnetIds": [
        "subnet-a",
        "subnet-b",
        "subnet-c"
      ],
      "SecurityGroupIds": [
        "sg-a",
        "sg-b",
        "sg-c",
        "sg-d",
        "sg-e"
      ],
      "VpcId": "a"
    },
    "Environment": {
      "Variables": {
        "DEPLOY_ENV": "qa"
      }
    },
    "TracingConfig": {
      "Mode": "PassThrough"
    },
    "RevisionId": "9fe11740-277b-4cb6-9571",
    "c7n:MatchedFilters": [
      "tag:x",
      "tag:y"
    ]
  }]
