### ISSUE TITLE
aws - subnet filter - annotation of matched properties

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#5729]
Hello,

I'm writing an EC2 policy which is matching on a `subnet` filter - and that works well.
Ex:
```
policies:
- name: ec2-subnet
  resource: ec2
  filters:
    - type: subnet
      key: "tag:Name"
      op: regex
      value: "^.*(?-i:my_subnet).*$"
  actions:
    - type: notify
...
```

Now I'd like, in the notification template (a mail), to access the matched resource property (the tag:Name of the subnet, in that example).
However, the current annotation is only giving a hint about the fact that we matched a specific related resource (here : the subnet), and only gives the related resource id - not additional properties of the related resource:
```
...
    "c7n:matched-subnets": [
      "subnet-123456789"
    ]
  },
```

Question: How could I write a policy + a template showing me additional properties of this related resource ?
Ex of a mail:
```
Hello,

Your EC2 instances below have matched:
* i-123456 in subnet-123456789 (Subnet Name: this_is_my_subnet)
* i-234567 in subnet-987654321 (Subnet Name: my_subnet_is_rich)
```

Thanks for any suggestion or workaround.

(If a custodian enhancement is needed, let me know the best way to do it - either in `net_filters.SubnetFilter` ; in `RelatedResourceFilter`, or somewhere else)
