### ISSUE TITLE
copy tags to related snapshots for account owned AMIs

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#5736]
**Describe the bug**
Wanted to tag account owned AMI's using copy-related-tag action.

**To Reproduce**
policies:
 - name: ami-tags
   resource: ami
   description: |
      Copy related snapshot tags to AMI's
    filters:
     - type: value
       key: Name
       value_type: normalize
       value: custodian
       op: contains
   actions:
      - type: copy-related-tag
        resource: ami
        skip_missing: True
        key: "BlockDeviceMappings[].Ebs.SnapshotId"
        tags: '*'

**Expected behavior**
Should copy tags from snapshotId to AMI if the AMI Name contains custodian string.

**Background (please complete the following information):**
 - OS: AMZN LINUX 2
 - Python Version:  python 3.8.2
 - Custodian Version:  0.9.1
 - Cloud Provider:  aws
 - Policy: 

```
policies:
 - name: ami-tags
   resource: ami
   description: |
      Copy related snapshot tags to AMI's on RegisterImage Event.
    filters:
     - type: value
       key: Name
       value_type: normalize
       value: custodian
       op: contains
   actions:
      - type: copy-related-tag
        resource: ebs
        skip_missing: True
        key: "BlockDeviceMappings[].Ebs.SnapshotId"
        tags: '*'

```
 - Traceback: [if applicable, please exclude sensitive/account information]
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/policy.py", line 323, in run
    results = a.process(resources)
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1021, in process
    related_ids = {r[0] for r in related_resources}
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1021, in <setcomp>
    related_ids = {r[0] for r in related_resources}
TypeError: unhashable type: 'list'
2020-05-08 20:36:22,486: custodian.commands:ERROR Error while executing policy snapshot-ami-tags, continuing
Traceback (most recent call last):
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/commands.py", line 281, in run
    policy()
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/policy.py", line 1065, in __call__
    resources = mode.run()
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/policy.py", line 323, in run
    results = a.process(resources)
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1021, in process
    related_ids = {r[0] for r in related_resources}
  File "/home/ec2-user/custodian/lib/python3.8/site-packages/c7n/tags.py", line 1021, in <setcomp>
    related_ids = {r[0] for r in related_resources}
TypeError: unhashable type: 'list'

**Additional context**
