### ISSUE TITLE
aws.s3 - CreationDate is unavailable in cloudtrail policies

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/cloud-custodian#5763]
**Describe the bug**
The `CreationDate` field is not available for s3 cloudtrail policies and therefore cannot include filters depending on the age of the bucket.  Because the data is missing, the filter will not behave as expected and will simply never match.

Filtering based on age `lt` 1 day:
```
[DEBUG]	2020-05-14T15:29:08.869Z	8c3d8f81-3b5b-4d44-81ac-756c81a7dab0 Filtered from 1 to 0 s3
```
Filtering based on age `gt` 1 day:
```
[DEBUG]	2020-05-14T15:30:22.160Z	eac7440b-60ad-487e-987e-cfe5f56501c0 Filtered from 1 to 0 s3
```
This also affects the reporting abilities during notifications... as we cannot report on when the bucket was created.

This looks directly related to #3909

**To Reproduce**
Provision any cloudtrail policy for s3 and try to use the `CreationDate` field.

**Expected behavior**
`CreationDate` should be available during event/lambda policies.

**Background (please complete the following information):**
 - Custodian Version: 0.9.1
 - Policy:
```yaml
policies: 
  - name: test-s3-age
    resource: s3
    mode:
      type: cloudtrail
      events:
        - source: s3.amazonaws.com
          event: PutBucketTagging
          ids: requestParameters.bucketName
      role: *lambda-role
      tags: *lambda-tags
    filters:
      - type: value
        key: CreationDate
        op: gt
        value_type: age
        value: 1
```
