### ISSUE TITLE
DynamoDB Table Not Filtering on SSEDescription Correctly

### ISSUE THREAD

**Issue by bostrowski13** [cloud-custodian/cloud-custodian#5779]
**Describe the bug**
I'm using a periodic check via lambda to try to find DynamoDB Tables that don't have Encryption set up correctly or at all.  When running the policy below, it is still returning policies that are configured as desired.  This could be my misunderstanding of how filtering works.  I've also gone around with several iterations of the filter which seems to consistently not filter as desired.

**To Reproduce**
Run the following policy below.

**Expected behavior**
It filters tables that don't meet the filter.

**Background (please complete the following information):**
 - OS: LInux
 - Python Version: 3.7.x
 - Custodian Version: 0.9.1
 - Cloud Provider: aws
 - Policy: 
```yaml
policies: 
policies:
  - name: dynamodb-table-encryption
    resource: dynamodb-table
    mode:
      type: periodic
      role: my_role
      schedule: "rate(12 hours)"
    filters:
      - and:
        - not:
          - type: value
            key: SSEDescription.KMSMasterKeyArn
            value: empty
        - and:
          - type: value
            key: SSEDescription.Status
            value: "ENABLED"
          - type: value
            key: SSEDescription.SSEType
            value: "KMS"
```
I've also tried this as the filter...
```
    filters:
      - and:
        - not:
          - "SSEDescription.KMSMasterKeyArn": empty
        - or:
          - "SSEDescription.Status": ENABLED
          - "SSEDescription.SSEType": KMS
```

I am also seeing this in the results that are returned via the policy.  I've included snipppets of the resources.json that are returned for an example resource.
```
    "SSEDescription": {
      "Status": "ENABLED",
      "SSEType": "KMS",
      "KMSMasterKeyArn": "MY_ARN"
    },
```

and the matched filters....
```
    "c7n:MatchedFilters": [
      "SSEDescription.Status",
      "SSEDescription.SSEType"
    ]
```

**Additional context**
I realize i might have a few "not" or "and" statements off in the above example, but i've tried what I think is the right combo to no avail.

Is this a bug or am I just missing something?
