### ISSUE TITLE
cache-cluster event:create exist or not?

### ISSUE THREAD

**Issue by umitseremet** [cloud-custodian/cloud-custodian#5785]
Hi,

I want to implement Cloud Custodian for some functionalities, like

- I want to be alerted  if someone creates an Elasticache
```
events:
       - CreateCacheCluster????
```

- and I want auto-tagging for owner after the creation

```
    actions:
      - type: auto-tag-user???
        tag: onwer????
        principal_id_tag: ownerID????
```

Are these functions enabled for Elasticache?
I could not see samples in https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/elasticache.py about them

Thanks...

**Comment by kapilt** [comment]
see the docs re specifying events in full form (source, ids, event names)

https://cloudcustodian.io/docs/aws/policy/lambda.html#cloudtrail-api-calls

auto-tag-user is available for all tangible resources

please refer to the reference docs for a resource for seeing whats available
https://cloudcustodian.io/docs/aws/resources/cache-cluster.html

or using the command line built in help

`custodian schema aws.cache-cluster`

**Comment by umitseremet** [comment]
Hi @kapilt 

I still could not find the event name for "cache-cluster" cloudtrial event name. I can list events and actions via   `custodian schema aws.cache-cluster`, but how can I see cloudtrail-event-types for a specific resource?

```
resource: cache-cluster
    mode:
      role: arn:aws:iam::{account_id}:role/administrator
      type: cloudtrail
      events:
        - RunInstances
```

**Comment by umitseremet** [comment]
I have found  `Createcache-clusterDomain ` inside of that file as an cloudwatch-event in that url
https://github.com/cloud-custodian/cloud-custodian/pull/1768/files#diff-73196164a68e2228ea67149d85fc7c4fR185

but it seems it does not work in my version which is latest one

```
Traceback (most recent call last):
  File "/usr/local/bin/custodian", line 11, in <module>
    load_entry_point('c7n', 'console_scripts', 'custodian')()
  File "/src/c7n/cli.py", line 359, in main
    command(config)
  File "/src/c7n/commands.py", line 60, in _load_policies
    collection = policy_load(options, fp, validate=validate, vars=vars)
  File "/src/c7n/policy.py", line 70, in load
    [p.validate() for p in collection]
  File "/src/c7n/policy.py", line 70, in <listcomp>
    [p.validate() for p in collection]
  File "/src/c7n/policy.py", line 947, in validate
    m.validate()
  File "/src/c7n/policy.py", line 622, in validate
    assert e in CloudWatchEvents.trail_events, "event shortcut not defined: %s" % e
AssertionError: event shortcut not defined: Createcache-clusterDomain
```

**Comment by kapilt** [comment]
see the docs re full form for events, not just the string event name, but ids, sources, events triple.
https://cloudcustodian.io/docs/aws/policy/lambda.html#cloudtrail-api-calls

**Comment by umitseremet** [comment]
I have checked and prepared block below

```
    resource: cache-cluster
    mode:
     type: cloudtrail
     role: arn:aws:iam::{account_id}:role/administrator
     events:
      - ids: requestParameters.replicationGroupId
        source: elasticache.amazonaws.com
        event: CreateReplicationGroup
    actions:
        - type: auto-tag-user
          tag: creator-name
          principal_id_tag: creator-id
```

but I still have not got an autotaggin yet, not sure which part is wrong or absent
