### ISSUE TITLE
copy-related-tag rds-snapshot AssertionError

### ISSUE THREAD

**Issue by gvagithub20** [cloud-custodian/cloud-custodian#5791]
I want to copy related tags from rds instance to rds snapshot, but when running the policy below I get the following error:
AssertionError: Scalar server side filter

 - Custodian Version: 0.9.1
 - Cloud Provider: aws

```yaml
policies:
  - name: Copy-tags-from-rds-to-snapshot
    resource: rds-snapshot
    actions:
      - type: copy-related-tag
        resource: rds
        skip_missing: True
        key: DBInstanceIdentifier
        tags:
          - Environment
```
