### ISSUE TITLE
azure - container-host - c7n.exceptions.InvalidOutputConfig

### ISSUE THREAD

**Issue by bramvdklinkenberg** [cloud-custodian/cloud-custodian#5811]
**Describe the bug**
I followed this [aci tutorial](https://cloudcustodian.io/docs/azure/configuration/acitutorial.html#azure-configuration-acitutorial), but I keep getting the error:
`c7n.exceptions.InvalidOutputConfig: Invalid c7n.output.blob: https://<sa-account-name>.blob.core.windows.net/c7n-aci-logs`

**To Reproduce**
Steps to reproduce the behavior: See [tutorial](https://cloudcustodian.io/docs/azure/configuration/acitutorial.html#azure-configuration-acitutorial)

**Expected behavior**
The aci tutorial to work

**Background (please complete the following information):**
 - OS: N/A
 - Python Version: N/A
 - Custodian Version: latest image tag
 - Tool Version: [if applicable]
 - Cloud Provider: azure
 - Policy: [please exclude any account/sensitive information]
policies:
```
- name: find-c7nstorage
  resource: azure.storage
  mode:
    type: container-periodic
    schedule: "* * * * *"  # Run every minute as an example
  filters:
  - type: value
    key: name
    op: eq
    value: <sa-account-name>
```
policies: 
   - name: find-c7nstorage
      resource: azure storage account
```

 - Traceback: [if applicable, please exclude sensitive/account information]
```
Traceback (most recent call last):
  File "/src/tools/c7n_azure/c7n_azure/container_host/host.py", line 408, in run_policy
    policy.push(event, context)
  File "/src/c7n/policy.py", line 1126, in push
    return mode.run(event, lambda_ctx)
  File "/src/tools/c7n_azure/c7n_azure/container_host/modes.py", line 70, in run
    return PullMode.run(self)
  File "/src/c7n/policy.py", line 282, in run
    with self.policy.ctx:
  File "/src/c7n/ctx.py", line 83, in __enter__
    self.initialize()
  File "/src/c7n/ctx.py", line 57, in initialize
    self.output = blob_outputs.select(self.options.output_dir, self)
  File "/src/c7n/output.py", line 62, in select
    raise InvalidOutputConfig("Invalid %s: %s" % (
c7n.exceptions.InvalidOutputConfig: Invalid c7n.output.blob: https://sa-account-name.blob.core.windows.net/c7n-aci-logs
```
