### ISSUE TITLE
S3 Lifecycle policy erroring out saying filters can only be used on V2 API

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5826]
**Describe the bug**
When running a policy to apply a s3 bucket lifecycle we are getting the following error:
```An error occurred (InvalidRequest) when calling the PutBucketLifecycleConfiguration operation: Filter element can only be used in Lifecycle V2.```

**To Reproduce**
Running a policy with a put lifecycle action triggers the error for us

**Expected behavior**
Expecting the lifecycle to be applied successfully

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]  Ubuntu V20
 - Python Version: [e.g. python 3.8.1]  3.8
 - Custodian Version: [e.g. 0.8.46.1]  0.9.1.0
 - Tool Version: [if applicable] 
 - Cloud Provider: [e.g. gcp, aws, azure] aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
- name: s3-check-lifecycle-status-tag-disabled
  resource: s3
  description: |
     Checks to see if the bucket has lifecycle enabled
     and if not it enables Lifecycle default.
  filters:
    - "tag:c7n_CheckLifeCycle": present
    - "LifeCycle": absent
    - not:
         - "tag:Lifecycle": "false"
  actions:
    - type: configure-lifecycle
      rules:
        - ID: s3-lifecycle
          Status: Enabled
          Filter:
              Prefix: /
          Transitions:
            - Days: 180
              StorageClass: STANDARD_IA
          NoncurrentVersionExpiration:
              NoncurrentDays: 35
    - type: unmark
      tags: ['c7n_CheckLifeCycle']
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output
