### ISSUE TITLE
Using IAM events to trigger Password Policy Changes

### ISSUE THREAD

**Issue by deepaksrinath** [cloud-custodian/cloud-custodian#5828]
I want to update the password policy such that, whenever password policy is updated or deleted, I want my default password policy to be updated.

```
policies:
  - name: password-policy
    resource: account
    mode:
      role: arn:aws:iam::<role_id>:role/blah123
      type: cloudtrail
      events:
        - ConsoleLogin
        - CreateBucket
        - source: iam.amazonaws.com
          event: UpdateAccountPasswordPolicy
          ids: 'userIdentity.arn'
     actions:
         blah
```

But, the actions are only triggered only when I login but does not work when I create a new bucket or update password policy. How should I fix this issue? I believe it has something to do with resource!
