### ISSUE TITLE
S3 Inventory filter conditions fail some operations, don't aggregate "correctly"

### ISSUE THREAD

**Issue by eloucks** [cloud-custodian/cloud-custodian#5831]
**Describe the bug**

1.) Some operations for the inventory filter do not appear to function correctly.
In theory, I would expect the following filters to be equivilent:
```yaml
- not:
  - type: inventory
    key: Id
    value: something
    op: equal  
- type: inventory
  key: Id
  value: something
  op: not-equal
```
These two policies yield very different results. The first will return the list of buckets that do not have an inventory with id = something. The second seems to return only buckets with no inventory configurations (or with access denied). This behavior is consistent even with the addition of `--cache-period 0` to the command.

2.) Policies with multiple filters of type `inventory` do not stack "correctly"
In a given policy, any combination of `inventory` type filters will return all buckets where all of the conditions are true across _any combination of inventories_ for the bucket. **If I wished to filter for S3 buckets with inventory configurations where any two conditions are true, I would be out of luck** (unless I can be assured that every bucket only has a single inventory configuration). This has obvious utility forcing compliance with a set of standards for such configurations.

For example, the following filters return all buckets where one inventory configuration has name testing and any of the configurations where IncludedObjectVersions is Current:
```yaml
- type: inventory
  key: Id
  value: testing
  op: equal
- type: inventory
  key: IncludedObjectVersions
  value: Current
  op: equal
```
It does _not_ return all buckets with an inventory configuration called testing with IncludedObjectVersions = Current.

This is also a problem of ambiguous implementation. If I wanted to filter for buckets with two distinct inventory configurations, the current approach _could_  but would not necessarily work for that. Since inventory configurations are a collection themselves, but they are a filter for S3 resources, the implementation of inventory filters as AND comparator is unclear. 

The current implementation appears to use the logic: `for bucket in buckets return bucket if inventory_filter_property in config for config in configs` which means that seemingly contradictory filters can also work together. For example:
```yaml
- type: inventory
  key: Id
  value: test1
  op: equal
- type: inventory
  key: Id
  value: test2
  op: equal
```
returns all buckets with an inventory configuration called `test1` and one called `test2`. Again, this may be intended behavior, but if it is, some kind of subfilter or multiple key/value pair specifications per filter would be needed for any non-trivial enforcement action.

**To Reproduce**
Execute policies using the filters above against s3 buckets with multiple inventory configurations.

**Expected behavior**
1.) Both filters should behave identically
2.) Inventory filters should operate on the same inventory configuration, or there should be a setting to make multiple inventory filters a group that do so.

**Background (please complete the following information):**
 - OS: OSX 10.15
 - Python Version: 3.7.6
 - Custodian Version: 0.9.2.0 (including post release updates/patches)
 - Cloud Provider: aws
 
```
Custodian:   0.9.2
Python:      3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) 
             [Clang 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='REDACTED', release='19.4.0', version='Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==1.11.1
attrs==19.1.0
boto3==1.13.17
botocore==1.16.17
docutils==0.14
importlib-metadata==1.6.0
jmespath==0.9.4
jsonschema==3.2.0
pyrsistent==0.15.1
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==41.2.0
six==1.15.0
tabulate==0.8.7
urllib3==1.23
zipp==3.1.0
```
