### ISSUE TITLE
c7n-org not tagging Amazon EventBridge Rules in child accounts

### ISSUE THREAD

**Issue by garybaines** [cloud-custodian/cloud-custodian#5833]
**Describe the bug**
c7n-org isn't tagging the events it builds in child accounts with the tags specified in the policies "mode" section.  The lambda's it builds are tagged correctly.

**To Reproduce**
Create a policy with a mode section that has a number of tags, e.g.
```    mode:
      type: periodic
      role: c7n-lambda-role
      schedule: "cron(15 11 * * ? *)"
      tags:
          live: "no"
          builtby: "CloudCustodian"
```
**Expected behavior**
Event rule should be tagged with the above two tags (live and builtby in above example)

**Background (please complete the following information):**
 - OS: [c7n-org run from a docker image python:3.8-slim-buster]
 - Python Version: [python 3.8]
 - Custodian Version: [c7n==0.8.46.1
c7n-mailer==0.5.8
c7n-org==0.5.7]
 - Tool Version: [if applicable]
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]
```yaml
vars:
  tag-filters: &tag-compliance-filters
    - "tag:costcentre": absent
    - "tag:live": absent
    - type: value
      key: "tag:live"
      value: [yes, no]
      op: in

policies:
  - name: ec2-tag-compliance
    description: Find resources without mandatory tags
    resource: ec2
    mode:
      type: periodic
      role: c7n-lambda-role
      schedule: "cron(15 11 * * ? *)"
      tags:
          live: "no"
          builtby: "CloudCustodian"
          email: "redacted"
          costcentre: "XXXX"
          scpProtected: "true"
    comment: |
      Report on total count of non compliant instances
    filters:
      - "tag:aws:autoscaling:groupName": absent
      - "tag:c7n_status": absent
      - or: *tag-compliance-filters
```

**Additional context**
We push out policies to dozens of accounts and need all the Custodian built resources to be tagged for both cost reporting purposes and so they can be protected from accidental or malicious deletion in the spoke accounts via an SCP (Service Control Policy) tag protection policy.  At the moment Custodian is only tagging its lambda's correctly, leaving the Cloud Watch events exposed.
