### ISSUE TITLE
enabling perfromance insight on RDS failing due wrong key in property

### ISSUE THREAD

**Issue by RazaHasan84** [cloud-custodian/cloud-custodian#5861]
**Describe the bug**
response of describe db instance does not have any key "EnablePerformanceInsights" but "PerformanceInsightsEnabled" :
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/rds.py#L1625
Hence, using EnablePerformanceInsights under action fail
          - type: modify-db
              update:
                - property: 'PerformanceInsightsEnabled'
                  value: true
              immediate: true

https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/rds.py#L1655
    if r[update['property']] != update['value']:
KeyError: 'EnablePerformanceInsights'

**To Reproduce**

**Expected behavior**

**Background (please complete the following information):**

```yaml
policies: 
       actions:
            - type: modify-db
              update:
                - property: 'EnablePerformanceInsights'
                  value: true
              immediate: true
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
