### ISSUE TITLE
Rest-API cross-account filter issues - JSONDecodeError: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#5878]
**Describe the bug**
When running just a basic policy against the rest-api resource for cross-account filter we get the error in the below traceback

**To Reproduce**
running a poll mode rest-api cross-account policy

**Expected behavior**
Expecting similar behavior to other cross-account filter policies

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15] Ubuntu v20
 - Python Version: 3.8.1
 - Custodian Version: 0.9.2.0
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: 
```
policies:


- name: rest-public
  resource: rest-api
  filters:
    - type: "cross-account"
      whitelist_from:
         url: "s3://mys3bucket/AccountNumbersWithAWSLogAccts.csv"
         format: csv2dict
```
 - Traceback: 
https://gist.github.com/jtroberts83/4bcbddb38bdc86b66915b1f48de37c4f

 - `custodian version --debug` output
In traceback link above
**Additional context**
