### ISSUE TITLE
How to get resources with a value inside any keys

### ISSUE THREAD

**Issue by diegolima** [cloud-custodian/cloud-custodian#5909]
Hi! I'm trying to write a policy that finds aws vpn connection tunnels that have no tunnels up. When searching for tunnels without any filters the resources.json look like this:

```
[
  {
    (lots of stuff here)
    "VgwTelemetry": [
      {
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2020-06-24T04:33:19+00:00",
        "OutsideIpAddress": "1.1.1.1",
        "Status": "UP",
        "StatusMessage": ""
      },
      {
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2020-06-07T19:41:11+00:00",
        "OutsideIpAddress": "1.1.1.2",
        "Status": "DOWN",
        "StatusMessage": ""
      }
    ]
  }
]
```

Basically what I'm trying to do is filter resources that have no `"Status": "UP"` keys in them. I tried to do something like this:

```
- name: aws-vpnconnection-alltunnelsaredown-find
    description: |
      Find connections with no tunnels up
    resource: aws.vpn-connection
    filters:
      - not:
        - VgwTelemetry.[*].Status: UP
```

But this doesn't seem to work. What is the proper way to do this?

**Comment by kapilt** [comment]
its useful to try out jmespath-terminal package for exploring this locally with the cli

```VgwTelemetry[].Status: DOWN```

**Comment by diegolima** [comment]
> `VgwTelemetry[].Status: DOWN`

I tried with this syntax but it returns no results. This is what the resource looks like now:
```
[
  {
    (lots of stuff here)
    "VgwTelemetry": [
      {
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2020-05-29T00:39:50+00:00",
        "OutsideIpAddress": "34.229.36.242",
        "Status": "DOWN",
        "StatusMessage": ""
      },
      {
        "AcceptedRouteCount": 3,
        "LastStatusChange": "2020-06-07T19:41:11+00:00",
        "OutsideIpAddress": "34.234.168.197",
        "Status": "DOWN",
        "StatusMessage": ""
      }
    ]
  }
]
```

This is my policy:

```
- name: aws-vpnconnection-tunnelisdown-find
    resource: aws.vpn-connection
    description: |
      Find connections with no tunnels up
    filters:
      - VgwTelemetry[].Status: DOWN
```

When I run there are no matches:

```
2020-06-30 19:58:42,451: custodian.policy:INFO policy:aws-vpnconnection-tunnelisdown-find resource:aws.vpn-connection region:us-east-1 count:0 time:0.00
```

**Comment by diegolima** [comment]
After a bit of tinkering this works:

```
- name: aws-vpnconnection-tunnelisdown-find
    resource: aws.vpn-connection
    filters:
      - and:
        - VgwTelemetry[0].Status: DOWN
        - VgwTelemetry[1].Status: DOWN
```

However this isn't really an optimal solution, as I have some other resources that I may need to filter that do not have a fixed number of keys. Is there any better way to do this? just using `- VgwTelemetry[].Status: DOWN` returned no results.

**Comment by kapilt** [comment]
so because the value comes back as an array from expression, comparing to a singleton policy value won't match for equality, you'll need to use the long form of the value filter.

```
- name: aws-vpnconnection-tunnelisdown-find
    resource: aws.vpn-connection
    description: |
      Find connections with no tunnels up
    filters:
      - type: value
         key: VgwTelemetry[].Status
         op: contains
         value: DOWN
```

**Comment by diegolima** [comment]
Hi! Thanks again for the responses, this helped a lot so far. However that doesn't exactly do what I need. The filter returns any connections which have one tunnel down, and not **all** tunnels down. Currently I have a scenario where one of the connections is up and the other is down, and it gets matched by that.

I've made this policy to solve that based on your answer:

```
- name: aws-vpnconnection-connectionisdegraded-find
    description: |
      Find degraded connections (one of the tunnels is down, but not both)
    resource: aws.vpn-connection
    filters:
      - and:
        - type: value
          key: VgwTelemetry[].Status
          op: contains
          value: DOWN
        - and:
          - not:
            - VgwTelemetry[0].Status: DOWN
            - VgwTelemetry[1].Status: DOWN

  - name: aws-vpnconnection-connectionisdown-find
    description: |
      Find connections where both tunnels are down
    resource: aws.vpn-connection
    filters:
      - and:
        - VgwTelemetry[0].Status: DOWN
        - VgwTelemetry[1].Status: DOWN
```

Again this is not really optimal since I have a case with another resource (azure loadbalancer) where there may be an arbitrary number of backendAddressPools and any of them may contain instances. I've made a very dirty workaround in that case:

```
- name: az-loadbalancer-withoutinstances-find
    resource: azure.loadbalancer
    description: |
      Find load balancer whose backend address pools contain no instances. This will cause false detections if there are > 10 address pools  and there are instances on the 11th+ pools
    filters:
      - or:
        - properties.backendAddressPools: []
        - and:
          - properties.backendAddressPools[0].properties.backendIPConfigurations:
          - properties.backendAddressPools[1].properties.backendIPConfigurations:
          - properties.backendAddressPools[2].properties.backendIPConfigurations:
          - properties.backendAddressPools[3].properties.backendIPConfigurations:
          - properties.backendAddressPools[4].properties.backendIPConfigurations:
          - properties.backendAddressPools[5].properties.backendIPConfigurations:
          - properties.backendAddressPools[6].properties.backendIPConfigurations:
          - properties.backendAddressPools[7].properties.backendIPConfigurations:
          - properties.backendAddressPools[8].properties.backendIPConfigurations:
          - properties.backendAddressPools[9].properties.backendIPConfigurations:
```

**Comment by tjstansell** [comment]
You should play around with the jmespath expressions more ... they're very powerful ... as you could use the following to find cases where all tunnels are down: 
```
length(VgwTelemetry[?Status==`DOWN`]) == length(VgwTelemetry[])
```
or similarly, some but not all are down:
```
length(VgwTelemetry[?Status==`DOWN`]) < length(VgwTelemetry[])
```
This just returns `true` or `false`, so you would just match against that:
```yaml
- name: all-tunnels-down
  resource: aws.vpn-connection
  filters:
    - type: value
      key: "length(VgwTelemetry[?Status==`DOWN`]) == length(VgwTelemetry[])"
      op: eq
      value: true
```
