### ISSUE TITLE
mark(ed)-for-op: Why validate?

### ISSUE THREAD

**Issue by bdwyertech** [cloud-custodian/cloud-custodian#5917]
Curious, as to input from others -- why do we validate that the op verb is a valid action for a resource?  We allow use of a custom tag, even message, but why not custom 'op' action?

I'd like to be able to do the following:
```yml
actions:
      - type: mark-for-op
        tag: c7n:ami-update
        op: second-warning
        days: 2
```

Instead, I have to resort to using a generic `:op` action, e.g.

```yml
actions:
      - type: mark-for-op
        tag: c7n:ami-update
        op: mark
        days: 2
        message: "Marked for forced AMI Update: mark@{action_date}"
```

The real question here is what is the value of validating the op against the target resource?  Does anyone else agree we should just turn this off, or should we add a `custom` boolean to the schemas respectively?
