### ISSUE TITLE
Provide filter result for regex over the list, when key  used for type value returns list.

### ISSUE THREAD

**Issue by 12Manoz** [cloud-custodian/cloud-custodian#5919]
Currently regex can be used only for string. But when we have key returning list, we will like to filter the results based on regex for the list. 

Use case: filter name and value of environment variables for container definition. Key returns list, we will like to filter policies based on matching regex, when evaluated key returns list 

Policy example:

```
policies:
  - name: ecs-task-definitions-complaince
    resource: aws.ecs-task-definition
    filters:
      - type: value 
        key: containerDefinitions[].environment[].value
        value: .*maven.*
        op: regex
```
Policy resources sample which needs to be filtered:
```
"containerDefinitions": [
      {
        "environment": [
          {
            "name": "SERVICE_NAME",
            "value": "xx-maven-xx000"
          },
          {
            "name": "ENVIRONMENT_NAME",
            "value": "dev"
          },
          {
            "name": "manage_beta_alb",
            "value": "False"
          },
         ...............
```

**Comment by JohnHillegass** [comment]
Hey @12Manoz, would something like this work?

```yaml
policies:
    - name: test-ecs-env-vars
      resource: ecs-task-definition
      filters:
        - type: value
          key: join(',', containerDefinitions[].environment[].value)
          value: '(^|,).*maven.*(.|$)'
          op: regex
```
