### ISSUE TITLE
Filtering S3 Bucket Location.LocationConstraint for us-east-1

### ISSUE THREAD

**Issue by jcderose** [cloud-custodian/cloud-custodian#5925]
Howdy! I want to run a simple "custodian run" command against untagged S3 resources in all AWS regions, but filter on the buckets that actually exist in that particular region. (e.g. when I `run` in us-east-1, I only want to work with untagged S3 resources that live in us-east-1; when I `run` in us-east-2, I only want to work with untagged S3 resources that live in us-east-2; etc.) I can get this filter to work for all regions *except* us-east-1 and need help building a filter string that works for all regions, including us-east-1. What would an appropriate policy filter look like that says `show me any resources where "tag:Name" is absent and the bucket's Location.LocationConstraint value is the current region "{region}" (e.g. us-east-1, us-east-2, us-west-1, us-west-2, etc.)`?

Here's the command I'm running:
```
custodian run -v -s /home/custodian/output --region=all -u /home/custodian/policy.yml
```

My policy file that works for all regions *except* us-east-1 is this:
```
policies:
  - name: s3-untagged
    resource: aws.s3
    filters:
      - "tag:Name": absent
      - Location.LocationConstraint: "{region}"
```

[With Kapil's help on gitter](https://gitter.im/cloud-custodian/cloud-custodian?at=5ef24a53a813c72dcf065b3d) (thank you, Kapil!) I know that us-east-1 is a bit special - it shows up as `null` instead of `us-east-1` in custodian's output.

I tried this policy file:
```
policies:
  - name: s3-untagged
    resource: aws.s3
    filters:
      - "tag:Name": absent
      - or:
        - Location.LocationConstraint: "{region}"
        - Location.LocationConstraint: null
```
But that defeats the purpose of the Location.LocationConstraint filter I was working towards (e.g. it returns every bucket for every region, rather than only the buckets that exist in the particular region I'm iterating over).

I tried this policy file:
```
    resource: aws.s3
    filters:
      - "tag:Name": absent
      - or:
        - Location.LocationConstraint: "{region}"
        - and:
          - type: value
            key: region
            value: "us-east-1"
            op: equal
          - Location.LocationConstraint: null
```
But that doesn't return any results for us-east-1. (I assume something in my `and` filter is incorrect.)

Based on the [JMESPath tutorials](https://jmespath.org/tutorial.html), I tried this policy file:
```
policies:
  - name: s3-untagged
    resource: aws.s3
    filters:
      - "tag:bucket-name": absent
      - or:
        - Location.LocationConstraint: "{region}"
        - and:
          - Location.LocationConstraint: null
          - [?region=='us-east-1']
```
But that returns the error:
```
2020-07-03 22:00:02,423: c7n_org:WARNING Error running policy in ACCOUNTNAME @ us-east-1 exception: 'list' object has no attribute 'get'
```

I feel like I'm missing something with the JMESPath string but can't figure it out. Any help would be appreciated!

**Comment by kapilt** [comment]
I think what your looking for would be an enhancement to allow the value filter to match against execution variables. so the us-east-1 .. alternatively it would be nice if we can inject a normalized region value into the bucket so this is a bit simpler to express, instead of trying to match the default api value here and special casing us-east-1.

**Comment by jcderose** [comment]
I'm happy to look into this deeper but I'm not familiar with the code. Any suggestions where I would start to add this type of functionality?

**Comment by jcderose** [comment]
@kapilt any suggestions for where I could start to code this type of feature enhancement?

**Comment by ajkerrigan** [comment]
We got a question about this [in Gitter](https://gitter.im/cloud-custodian/cloud-custodian?at=619b73c26104ea63b6abe64d) today. I think the recap is that we can make a filter that "works" today but is pretty awkward because of the way the S3 API reflects us-east-1 (null) and eu-west-1 (EU):

```
filters:
  - type: value
    key: >
      Location | LocationConstraint == 'EU' && 'eu-west-1' || LocationConstraint || 'us-east-1'
    value: "{region}"
```

We already do some location normalization [here](https://github.com/cloud-custodian/cloud-custodian/blob/b461830d47375603ee839c9eedce7bab4e368616/c7n/resources/s3.py#L534-L549) - perhaps we could use that to add a normalized region column like `c7n:BucketRegion` as part of [augment](https://github.com/cloud-custodian/cloud-custodian/blob/b461830d47375603ee839c9eedce7bab4e368616/c7n/resources/s3.py#L79-L86)?
