### ISSUE TITLE
AWS - vpc-endpoint filter for vpc resource

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#5933]
**Is your feature request related to a problem? Please describe.**
Yes, we're trying to filter vpc based on their vpc endpoints. for example filter vpc's that have a s3 vpc endpoint

**Describe the solution you'd like**
I am thinking of creating a related resource filter that filters vpcs based on their vpc endpoints. 

for example 
```
policies:
  - name: s3-vpc-endpoint-enabled
    resource: vpc
    filters:
       - type: vpc-endpoint
          key: ServiceName
          value: com.amazonaws.us-east-1.s3
```

**Additional context**
The goal is to ensure certain vpc's contain certain vpc endpoints
