### ISSUE TITLE
Adding a `has-data` filter for S3 buckets

### ISSUE THREAD

**Issue by kylejohnson514** [cloud-custodian/cloud-custodian#5936]
**Is your feature request related to a problem? Please describe.**
We would like to add functionality to filter S3 buckets based on if they are/are not empty

**Describe the solution you'd like**
This should be a pretty straightforward filter - it could involve iterating through buckets, calling https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2 to check if the bucket contains any files/directories or not, and returning the buckets that do/don't have data within them

**Describe alternatives you've considered**

**Additional context**
I couldn't find an existing filter that supports this. If something _does_ exist to support this already, that'd be great! Otherwise, I can start to work on adding support for it.

Any input/ideas/suggestions would be appreciated! Thanks

**Comment by kapilt** [comment]
use a metrics filter to find empty buckets

**Comment by kylejohnson514** [comment]
For future reference, if anyone is trying to find a solution for this, here are some policy examples:

```
    - name: filter-empty-buckets-s3-metrics
      resource: s3
      filters:
        - not:
          - type: metrics
            name: NumberOfObjects
            statistics: Sum
            value: 0
            op: greater-than
```

```
    - name: filter-nonempty-buckets-s3-metrics
      resource: s3
      filters:
        - type: metrics
          name: NumberOfObjects
          statistics: Sum
          value: 0
          op: greater-than
```

Thanks Kapil!
