### ISSUE TITLE
AWS-Metric filter on log-group is failing

### ISSUE THREAD

**Issue by babitha-mathew-rft** [cloud-custodian/cloud-custodian#5938]
I  am writing a policy to  with  metric  filter on log groups. The  policy is
```
policies:   
    - name: logs-incoming-bytes
      resource: log-group
      comment: |
        Ingested logs size 
      filters:
        - type: metrics
          namespace: AWS/Logs
          name: IncomingBytes          
          value: 0         
          statistics: Sum
```
This is failing with below error,

```
2020-07-09 17:21:54,198: custodian.filters:WARNING CW Retrieval error: 'LogGroupName'
2020-07-09 17:21:54,199: custodian.policy:INFO policy:logs-incoming-bytes resource:log-group region:us-east-1 count:0 time:4.81
```
Please look into this.

Background (please complete the following information):**
 - OS: OSX 10.15.5
 - Python Version: python 3.7.7
 - Custodian Version: 0.8.44.2
 - Tool Version: [if applicable]
 - Cloud Provider: aws
