### ISSUE TITLE
MugC - CreateDBInstance, CreateDBCluster is not valid under any of the given schemas

### ISSUE THREAD

**Issue by mharini** [cloud-custodian/cloud-custodian#5959]
**Describe the bug**
MugC run command gives CreateDBInstance, CreateDBCluster is not valid under any of the given schemas

**To Reproduce**
`    mode:
      type: cloudtrail
      events:
      - source: rds.amazonaws.com
        event: 
        - CreateDBInstance`

**Expected behavior**
CreateDBInstance and CreateDBCluster need to be recognized by mugc.

**Background (please complete the following information):**
 - Policy:
```yaml
policies: 
   - name: rds-policy
      resource: aws.rds
      mode:
      type: cloudtrail
      events:
      - source: rds.amazonaws.com
        event: 
        - CreateDBInstance
```
 - `custodian version --debug`
`Custodian:   0.8.45.2
Python:      3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
             [Clang 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='harinis-mbp', release='18.7.0', version='Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
PYTHONPATH: 
[            '/Library/Frameworks/Python.framework/Versions/3.7/bin',
             '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
             '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
             '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
             '/Users/harinim/Library/Python/3.7/lib/python/site-packages',
             '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages']`

**Additional context**
The same happens with CreateDBCluster event.
