### ISSUE TITLE
`has-statement` doesn't populate matched statements annotation

### ISSUE THREAD

**Issue by victorpcamargo** [cloud-custodian/cloud-custodian#5961]
**Describe the bug**
I'm trying to remove a statement that has a wildcard at principal, but the remove-statements doesn't work.

**To Reproduce**
I've set my c7n policy as you can see below.

````
policies:

- name: s3-fix-wildcard-principal
  resource: s3
  filters:
    - type: has-statement
      statements:
        - Principal: "*"
          Effect: Allow
  actions:
    - type: remove-statements
      statement_ids: matched
````
And this is my bucket policy:

````
{
    "Version": "2012-10-17",
    "Id": "<my_bucket_policy_id>",
    "Statement": [
        {
            "Sid": "<my_statement_id>",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<my_bucket_name>/*"
        }
    ]
}
````
The filter is working well, but the action is not.

```
(custodian) ####:~ victorcamargo$ custodian run -d -s out s3-wildcard-principal.yml 
2020-07-14 19:44:30,893: custodian.policy:INFO policy:s3-fix-wildcard-principal resource:s3 region:us-east-1 count:1 time:4.52
(custodian) ####:~ victorcamargo$ custodian run -s out s3-wildcard-principal.yml 
2020-07-14 19:44:43,655: custodian.policy:INFO policy:s3-fix-wildcard-principal resource:s3 region:us-east-1 count:1 time:0.00
2020-07-14 19:44:43,657: custodian.policy:INFO policy:s3-fix-wildcard-principal action:removepolicystatement resources:1 execution_time:0.00
(custodian) ####:~ victorcamargo$
```
Seems like the action is working, but the bucket policy keeps there and my bucket is till public.

**Expected behavior**
I expected the policy to be removed.

**Background (please complete the following information):**
 - OS: OSX 10.15.5
 - Python Version: python 3.7.6
 - Custodian Version: 0.9.4
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
````
policies:
- name: s3-fix-wildcard-principal
  resource: s3
  filters:
    - type: has-statement
      statements:
        - Principal: "*"
          Effect: Allow
  actions:
    - type: remove-statements
      statement_ids: matched
````
 - Traceback:
```
Custodian:   0.9.3
Python:      3.7.3 (default, Nov 15 2019, 04:04:52) 
             [Clang 11.0.0 (clang-1100.0.33.16)]
Platform:    posix.uname_result(sysname='Darwin', nodename='###########', release='19.5.0', version='Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.11.1
attrs==19.3.0
boto3==1.13.24
botocore==1.16.24
docutils==0.15.2
importlib-metadata==1.6.1
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==40.8.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```

**Comment by tomarv2** [comment]
@victorpcamargo have you checked if the `role` has permissions to delete policy.

**Comment by gerysz** [comment]
Same, here same c7n policy, no error message in lambda log, looks as action was taken, but policy does not change.
The role has permission for all actions on S3.
Does it need any other permission, usually a missing permission causes an error, which is visible in the logs.

**Comment by bc-jcarlson** [comment]
Appears we are having the same issue as well. Logs show the filter is picking up the resource, but the bucket policies stay in place, regardless of the usage of `matched` or `"*"` as the `statement_ids` value. No errors shown w/ debug and verbose logging enabled.

**Comment by nitrocode** [comment]
I think the `has-statement` is not a partial match, it's an exact match.

https://github.com/cloud-custodian/cloud-custodian/blob/0e1bd31bbc13abb12b2f286bc086e441ed453dde/c7n/filters/policystatement.py#L90-L106

So to match this bucket policy

```json
{
    "Version": "2012-10-17",
    "Id": "<my_bucket_policy_id>",
    "Statement": [
        {
            "Sid": "<my_statement_id>",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<my_bucket_name>/*"
        }
    ]
}
```

you'd need this c7n filter (without the `Sid`)

```yaml
  filters:
    - type: has-statement
      statements:
        - Effect: Allow
          Principal: "*"
          Action: "s3:GetObject"
          Resource: "arn:aws:s3:::{bucket_name}/*"
```

---

Proposal: It would be nice to have a `has-partial-statement` where you can do a partial match or even search if an action is allowed so if you were looking for `s3:PutObjectAcl` and the policy allowed `s3:*`, it would match.

e.g. bucket policy

```json
        {
            "Sid": "<my_statement_id>",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::<my_bucket_name>/*"
        }
```

Then you could use something like this and have it find it (This is proposed and so this will not work as of 0.9.31.0)

```yaml
  filters:
    - type: has-partial-statement
      statements:
        - Effect: Allow
          Action: "s3:PutObjectAcl"
```

cc: @kapilt thoughts on this?
