### ISSUE TITLE
"Access denied api:SendMessage" - does error refer to slack or IAM?

### ISSUE THREAD

**Issue by Mike-Landers** [cloud-custodian/cloud-custodian#5966]
I'm trying to set up custodian + c7n-org + c7n-mailer within AWS in order for custodian to run policies + send messages to sqs / receive messages from sqs and forward messages on to a slack channel using a slack webhook.

Currently when I run policies it complains:
c7n_org:WARNING Access denied api:SendMessage ...

My question is if this error is complaining about slack api permissions or AWS IAM permissions (slack api SendMessage vs sqs:SendMessage) @kapilt 

- I've set up and tested c7n-org can run policies. This works.
- I've set up an SQS queue that allows SendMessage at account level from all of our accounts, and ReceiveMessage at account level on the account with the queue.
- I've created a c7n IAM role with ReadOnlyAdmin + sqs:* on the above queue.
- I've allowed the c7n IAM role to be assumed by the IAM role running the c7n host (this works since c7n-org can run policies)
- I've specified the c7n IAM role to be used by all components of c7n
- I've created a c7n policy that makes use of a slack webhook used to send messages to a particular slack channel

```
actions:
      - type: notify
        slack_template: slack
        to:
          - https://hooks.slack.com/services/T0<masked>
        transport:
          type: sqs
          queue: https://sqs.<masked>
```
