### ISSUE TITLE
resource event lifecycle data dictionaries

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#5970]
**Is your feature request related to a problem? Please describe.**
It would be convenient to put together a mapping of cloud trail events along with the event, source, and ids so that it can be better abstracted and more easily be used in a policy. 

**Describe the solution you'd like**
A key on the cloud trail mode called lifecycle that will pull in the event metadata. 

Proposed resource event lifecycle data dictionaries for v1 are:
  - onCreate
  - onUpdate

In later implementations, I could see the addition of:
  - onDelete (in case you want to send an email or something when a resource is deleted)

The mapping could be something simple and look like:

```
{
    "launch-config": {
        "onCreate": {
            "source": "autoscaling.amazonaws.com",
            "event": "CreateLaunchConfiguration",
            "ids": "requestParameters.launchConfigurationName"
        },
        "onUpdate": {
            ...
        }
    }
}
```

For example:

```
  - name: asg-launch-config-public-new-delete
    resource: launch-config
    mode:
      type: cloudtrail
      lifecycle: onCreate
    filters:
      - type: event
        key: detail.requestParameters.associatePublicIpAddress
        value: true
    actions:
      - delete
```
could pull from the mapping and be interpreted during runtime as
```
  - name: asg-launch-config-public-new-delete
    resource: launch-config
    mode:
      type: cloudtrail
      events:
        - source: autoscaling.amazonaws.com
          event: CreateLaunchConfiguration
          ids: requestParameters.launchConfigurationName
    filters:
      - type: event
        key: detail.requestParameters.associatePublicIpAddress
        value: true
    actions:
      - delete
```

**Describe alternatives you've considered**
I have considered doing this in preprocessing or just having a shared mapping for team members to copy-paste from but I think something like this is probably better off being processed in Custodian and should give the community some utility by being able to avoid looking up what the proper event values are when writing cloud trail mode policies. It could also play nicely with the multi-resource policy feature @anovis is working on in https://github.com/cloud-custodian/cloud-custodian/pull/5964. Which from the looks of it would not work with cloudtrail mode right now. With the addition of this feature, it could be expressed like:

```
policies:
  - name: multi-resource-tagging
    resource: ["ec2", "ebs"]
    mode:
      type: cloudtrail
      lifecycle: onUpdate
    filters: 
      - "tag:Tag": absent
    actions:
     - type: tag
       key: Tag
       value: tagged
```
