### ISSUE TITLE
unexpected keyword argument 'function_app_resource_group_name'

### ISSUE THREAD

**Issue by spoloj** [cloud-custodian/cloud-custodian#5973]
**Describe the bug**
c7n-mailer for Azure is reporting 'function_app_resource_group_name' error 

**To Reproduce**
c7n-mailer --config mailer.yaml --update-lambda

**Expected behavior**
mailer functions should be created

**Background (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Python Version: Python 3.7.3
 - Custodian Version: 0.9.4
 - Tool Version: [if applicable]
 - Cloud Provider: Azure
 - Policy: [please exclude any account/sensitive information]
```yaml
- name: storage-container-public
    description: |
        Find all containers with public access enabled
    resource: azure.storage-container
    mode:
      type: azure-periodic
      schedule: '0 5 * * * *'
      provision-options:
        identity:
          type: SystemAssigned
    filters:
      - type: value
        key: properties.publicAccess
        op: not-equal
        value: None 
    actions:
      - type: notify
        to:
          - slack://#custodian
        slack_template: slack_default
        transport:
          type: asq
          queue: https://<removed>/c7-mailer
```
Mailer.yaml
```yaml
queue_url: asq://<>/c7-mailer
slack_token: <>
```
 - Traceback: [if applicable, please exclude sensitive/account information]

Traceback (most recent call last): File "/Users/xxxx/myfolder/custodian/bin/c7n-mailer", line 10, in <module> sys.exit(main()) File "/Users/xxxx/myfolder/custodian/lib/python3.7/site-packages/c7n_mailer/cli.py", line 235, in main azure_deploy.provision(mailer_config) File "/Users/xxxx/myfolder/custodian/lib/python3.7/site-packages/c7n_mailer/azure_mailer/deploy.py", line 137, in provision function_app_name=function_app_name) TypeError: __init__() got an unexpected keyword argument 'function_app_resource_group_name'

 - `custodian version --debug` output

**Additional context**
