### ISSUE TITLE
AWS config source pass supplementaryConfiguration data with resource 

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#5976]
**Is your feature request related to a problem? Please describe.**
Any reason why we do not return `supplementaryConfiguration` along with `configuration` . This would be helpful since this seems to contain tag information on resources which would be useful for further value filters.

https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/query.py#L350

**Describe the solution you'd like**
We can either add it to the resource data by default , or can create an option on the `config` source that will then add it.

for example:

```
policies: 
  - name: sns-test
    resource: aws.sns
    source: config
    supplimentary-config: true
    query:  
      - clause:  "tags.key = 'tag-check'"
```
