### ISSUE TITLE
Improving value_from check from O(n) to O(1) time

### ISSUE THREAD

**Issue by kylejohnson514** [cloud-custodian/cloud-custodian#5982]
**Is your feature request related to a problem? Please describe.**
I'm interested in a quicker, more efficient (O(1)) lookup method when we are running policies that check values from a retrieved file.

Here's an example...

Imagine we have a requirement: all resources need to have an OwnerContact tag with a valid email address.
We have a .json or .txt file of all valid email addresses, and we want to check that the provided OwnerContact tag's value is in our file.

Here's a sample policy file that does this...

```
vars:
  ownercontact-list: &ownercontact-list s3://s3-bucket-name/directory-name/owner_contact_info.txt
  ownercontact-tags-valid-check: &ownercontact-tags-valid-check
    - or:
      - type: value
        key: "tag:OwnerContact"
        value_type: normalize
        op: in
        value_from:
          url: *ownercontact-list
          format: txt
  required-tags-present-check: &required-tags-present-check
    - and:
      - "tag:Team": not-null
      - "tag:OwnerContact": not-null
      - type: value
        key: "tag:Team"
        value: ''
        op: ne
      - type: value
        key: "tag:OwnerContact"
        value: ''
        op: ne
      - and: *ownercontact-tags-valid-check
  required-tags-present: &required-tags-present
    - and:
      - "tag:c7n-tag-compliance": not-null
      - or: *required-tags-present-check
  required-tags-absent: &required-tags-absent
    - not:
      - or: *required-tags-present-check

policies:
  - name: account-lambda-amount
    resource: lambda
    comment: |
      Retrieving the total number of lambdas running in this AWS account...

  - name: lambda-tag-compliance-mark
    resource: lambda
    comment: |
      Mark any lambda functions for deletion if they are missing required tags or have incorrect OwnerContact tags
    filters:
      - "tag:c7n-tag-compliance": absent
      - and: *required-tags-absent
     actions:
       - type: mark-for-op
         tag: "c7n-tag-compliance"
         op: delete
         days: 7

  - name: lambda-tag-compliance-unmark
    resource: lambda
    comment: |
      Unmark any lambda functions marked for deletion if they have fixed the required tags
    filters:
      - "tag:c7n-tag-compliance": not-null
      - or: *required-tags-present
    actions:
      - type: remove-tag
        tags: ["c7n-tag-compliance"]
```

The current implementation parses the `owner_contact_info` list in O(n) time.
In this scenario, our OwnerContact list has about 350k unique values.
Testing this and running in an AWS account with 93 lambdas in `us-east-1` and 67 lambdas in `us-east-2` took the following times...

```
c7n_org:INFO Ran account:aws-account-name region:us-west-2 policy:account-lambda-amount matched:67 time:3.15
c7n_org:INFO Ran account:aws-account-name region:us-east-1 policy:account-lambda-amount matched:93 time:3.84
c7n_org:INFO Ran account:aws-account-name region:us-east-1 policy:lambda-tag-compliance-mark matched:2 time:41.16
c7n_org:INFO Policy resource counts Counter({'account-lambda-amount': 160, 'lambda-tag-compliance-mark': 2, 'lambda-tag-compliance-unmark': 0})
```

After fixing the tags and running this again to unmark the lambdas that are now compliant, I got the following results...

```
c7n_org:INFO Ran account:aws-account-name region:us-west-2 policy:account-lambda-amount matched:67 time:3.11
c7n_org:INFO Ran account:aws-account-name region:us-east-1 policy:account-lambda-amount matched:93 time:4.61
c7n_org:INFO Ran account:aws-account-name region:us-east-1 policy:lambda-tag-compliance-unmark matched:2 time:59.05
c7n_org:INFO Policy resource counts Counter({'account-lambda-amount': 160, 'lambda-tag-compliance-unmark': 2, 'lambda-tag-compliance-mark': 0})
```

**Describe the solution you'd like**
Adding support for Custodian to be able to check an `in` or `value_from` filter to do this lookup from a set in O(1) time rather than parsing a list in O(n) time would be a huge benefit.

**Additional context**
I tested this policy using both owner_contact_info.json and owner_contact_info.txt, and the .txt file ended up being noticeably faster.

I ran this policy in a fairly small AWS account, and my policies only checked the tags of lambda functions.
As we run this in larger accounts with an increased number of resources, and as we extend these policies to check all resources (not just lambdas), the runtime starts to increase significantly.

Any thoughts/input relating to this would be greatly appreciated.
Thanks!
