### ISSUE TITLE
aws - cloudtrail mode support for event-rule-target

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#5984]
**Is your feature request related to a problem? Please describe.**
We're trying to make sure that the event rule targets belong to the whitelisted accounts

**Describe the solution you'd like**
Create a cloudtrail policy to evaluate event rule target using cross-account filter. Currently, event rule target doesn't support cloudtrail mode policies
Ex policy:
```
  - name: eventbridge-target-rule-newchange
    resource: event-rule-target
    mode:
      type: cloudtrail
      events:
        - source: events.amazonaws.com
          event: PutTargets
          ids: requestParameters.targets[].arn
    filters:
      - type: cross-account
        whitelist_from:
          expr: 'accounts_expression'
          url: *accounts-list
```
Traceback:
```
$ custodian validate cw-target.yaml
2020-07-23 16:07:03,748: custodian.commands:ERROR Configuration invalid: cw-target.yaml
2020-07-23 16:07:03,748: custodian.commands:ERROR Policy: eventbridge-target-rule-newchange is invalid: resource:event-rule-target does not support cloudtrail mode policies
```
**Describe alternatives you've considered**
Alternate solution could be pull mode evaluation

**Additional context**
