### ISSUE TITLE
EC2 filter "state-age" not working as expected.     

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#5989]
**Describe the bug**
The ec2 filter **state-age** is not producing accurate results.   It seems to always produce zero results.

**To Reproduce**

1. Create a policy with this filter which returns numerous results as expected:

``` yaml
      - "State.Name": running
```

2. Create a policy with this filter which returns zero results:

``` yaml
      - type: state-age
        op: le
        days: 1
      - "State.Name": running
```

3. Create a policy with this filter which returns zero results:

``` yaml
      - type: state-age
        op: ge
        days: 1
      - "State.Name": running
```

I'd expect the state-age filter to return some results with either step 2 or step 3.      

**Expected behavior**
The filter stage-age to return some results instead of zero every time.

**Background (please complete the following information):**
 - OS: 4.4.0-17763-Microsoft #1217-Microsoft Mon May 05 16:09:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Python Version: 3.6.9
 - Custodian Version: 0.9.4
 - Cloud Provider: aws

**Comment by michael-barker** [comment]
Is there a way to do this that works? I'm also having this same issue.

**Comment by michael-barker** [comment]
I used `LaunchTime` age instead and that appears to accomplish the same thing.

```yaml
      - State.Name: running
      - type: value
        key: LaunchTime
        op: ge
        value_type: age
        value: 1
```
