### ISSUE TITLE
Ability to filter ECS task definitions based on the values stored in environment variables

### ISSUE THREAD

**Issue by kylejohnson514** [cloud-custodian/cloud-custodian#5991]
**Is your feature request related to a problem? Please describe.**
Currently, Custodian's `value` filter allows you to check if an ECS task definition's environment variable exists in the list of the resource's env vars keys. You can also check if a specific value exists in the list of the environment variable values. However, you cannot confirm if an environment variable's key and value are matching specific values. For example, imagine that we want to filter out all ECS Task Definitions that have an environment variable `ECS_AWSVPC_BLOCK_IMDS` equal to `true`.

While we can use the `value` filter on the ecs-task-definition resource to check for `taskDefinition.containerDefinitions.environment.name` contains `ECS_AWSVPC_BLOCK_IMDS`, we cannot 100% reliably perform the second check of `taskDefinition.containerDefinitions.environment.value == true` because these value filter checks will be looking at all containerDefinitions. It would work if there was only one environment variable, but if there is more than one, we have a potential for error. In the example below, a list `contains` operator filter will misfire because the second list contains `true`.. whereas it's not properly confirming that `ECS_AWSVPC_BLOCK_IMDS == true`, just that the first list contains `ECS_AWSVPC_BLOCK_IMDS` and the second list contains `true`. An enhancement to Custodian is needed to be able to check these values more strictly.

For example, given this containerDefinition from an ECS task definition:

```
"containerDefinitions": [{
    "name": "test",
    "image": "test",
    "cpu": 0,
    "portMappings": [],
    "essential": true,
    "entryPoint": [
        "sh"
    ],
    "environment": [
    {
        "name": "ECS_AWSVPC_BLOCK_IMDS",
        "value": "false"
    },
    {
        "name": "OTHER_IMPORTANT_THING",
        "value": "true"
    },
]
}]

```
a JMESPath expression of containerDefinitions[].environment[].name will yield:
```
[
    "ECS_AWSVPC_BLOCK_IMDS",
    "OTHER_IMPORTANT_THING"
]

```
a JMESPath expression of containerDefinitions[].environment[].value will yield
```
 [
      false,
      true
 ]

```
As an example of the existing functionality, this type of policy would return this specific ECS task definition as a match...

```
- name: test-ecs-env-vars
    resource: ecs-task-definition
    filters:
    - and:
        - type: value
        key: containerDefinitions[].environment[].name
        value: "ECS_AWSVPC_BLOCK_IMDS"
        op: contains
        - type: value
        key: containerDefinitions[].environment[].value
        value: "true"
        op: contains
```

when, for our goals/purposes, we wouldn't want it to, because it has `ECS_AWSVPC_BLOCK_IMDS == false` in the actual task definition.

**Describe the solution you'd like**
An additional filter to ECS Task Definitions to check that an environment variable's value matches a specific key value would resolve this.

**Additional context**
When creating an ECS task definition, environment variables are used to determine some of the resource's associated settings. For more info, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html

**Comment by kapilt** [comment]
this seems like an issue of learning how to use jmespath expressions to get to the right environment key

**Comment by kapilt** [comment]
with jmespath you can do conditional key matches for a particular named env var, see https://jmespath.org for examples. there's an example on the home page.

**Comment by kylejohnson514** [comment]
Ahh, got it to work as intended with the following policy (as an example)...

```
- name: test-ecs-env-vars
  resource: ecs-task-definition
  filters:
    - type: value
      key: containerDefinitions[0].environment[?name == 'ECS_AWSVPC_BLOCK_IMDS'].value
      value: "true"
      op: contains
```

Sorry for the unneccessary issue, and thanks for the input!
