### ISSUE TITLE
Feature Request: Add filter type for aws.backup-vault to filter by fields in the access policy

### ISSUE THREAD

**Issue by faizanu** [cloud-custodian/cloud-custodian#6001]
Currently there is no filter for aws.backup-vault resources that implements the API call backup-vault.GetBackupVaultAccessPolicy. We would like to filter backup vaults for fields in the JSON-formatted string in the "Policy" field of the aforementioned API call. 

Policy Example:

```
filters:
  - type: AccessPolicy
    key: Effect
    value: "Deny"
    op: ne
```

**Comment by JohnHillegass** [comment]
@faizanu, a has-statement filter might be able to fo this for you. See https://github.com/cloud-custodian/cloud-custodian/pull/5632 for some ideas. I think initial interest has died off but if the pattern could help solve this problem for you, it is probably worth reviving!

**Comment by kylejohnson514** [comment]
Similarly, if we support a `has-statement` filter, I have a PR opened (see https://github.com/cloud-custodian/cloud-custodian/pull/5684) to allow for `modify-policy` on backup-vault resources.

**Comment by faizanu** [comment]
@JohnHillegass, that pattern looks intuitive. I'll share your approach here:
```
     - name: backup-vault-public-Compliant
        resource: backup-vault
        filters:
          - type: has-statement
            statements:
              - Effect: Deny
                Principal: "*"
                Action: “sqs:*”
                Condition:
                  StringNotEquals:
                    "aws:PrincipalOrgID": *org-id

     - name: backup-vault-public-NotCompliant
        resource: backup-vault
        filters:
          - not:
            - type: has-statement
              statements:
                - Effect: Deny
                   Principal: "*"
                   Action: “sqs:*”
                   Condition:
                   StringNotEquals:
                     "aws:PrincipalOrgID": *org-id
```
