### ISSUE TITLE
Support for disabling AWS IAM user attributes such as MFA , console access etc.. (Not Delete)

### ISSUE THREAD

**Issue by rams3sh** [cloud-custodian/cloud-custodian#6005]
**Is your feature request related to a problem? Please describe.**
I have a problem statement where I am supposed to disable (and not delete)  all attributes of a user who do not belong to a set of authorised users.

**Describe the solution you'd like**
I referred official documentation , I found `delete` but couldn't find disable as an action for the following user attributes :- 
-  console-access
-  mfa-devices
-  ssh-keys
-  signing-certificates
-  service-specific-credentials

A sample expected policy idea to work is given below :- 
```
policies:
      - name: disable-all-access-unless-valid
        resource: iam-user
        filters:
          - type: value
            key: UserName
            op: not-in
            value:
              - valid-user-1
              - valid-user-2
        actions:
          - type: delete
            disable : true  # Would be nice to have this option just like the case of remove-keys
            options:
              - console-access
              - access-keys   # remove-keys has disable: true option to disable access keys but not others
              - mfa-devices
              - ssh-keys
              - signing-certificates
              - service-specific-credentials
```

**Describe alternatives you've considered**
I use a custom script to disable all of the attributes mentioned for a given user.

**Additional context**
None
