### ISSUE TITLE
Support for AWS IAM User Attribute filters for mfa-devices, ssh-keys and service-specific-credentials

### ISSUE THREAD

**Issue by rams3sh** [cloud-custodian/cloud-custodian#6006]
**Is your feature request related to a problem? Please describe.**

Currently I have a problem statement where there is an enterprise-wide policy for having a credential / key /certification rotation for all the IAM entities. This technically extends to anything that aids as a direct credential or acts as second factor authentication (which also qualifies as a credential) or even a certificate.

I referred the documentation but could'nt find filters that could help determine the details / age of AWS IAM user attribute 

- mfa-devices
- ssh-keys
- service-specific-credentials 

based on which an action can be taken.

Note : MFA device technically does not fit into my exact problem statement, but have included it anyway to have a holistic feature request as it also rightfully qualifies as a user attribute.

**Describe the solution you'd like**
As explained above , a sample idea in form of a policy template is given below to give more clarity on what I am trying to achieve through this feature.
```yaml
policies:
  - name: disable_cassandra_service_credentials_older_than_90_days
    resource: iam-user
    filters:
      - type: service-credentials
        key: Status
        value: Active
      - type: service-credentials
        key: ServiceName
        value: cassandra
      - type: service-credentials
        key: CreateDate
        value_type: age
        op: gte
        value: 90
    actions:
        - type: delete
          disable : true # Related to Feature request https://github.com/cloud-custodian/cloud-custodian/issues/6005

  - name: disable_ssh_keys_older_than_90_days
    resource: iam-user
    filters:
      - type: ssh-keys
        key: Status
        value: Active
      - type: ssh-keys
        key: UploadDate
        value_type: age
        op: gte
        value: 90
    actions:
        - type: delete
          disable : true # Related to Feature request https://github.com/cloud-custodian/cloud-custodian/issues/6005

  - name: disable_mfa # Dummy POC policy
    resource: iam-user
    filters:
      - type: mfa-devices
        key : EnableDate
        value_type: age
        op: gte
        value: 90
    actions:
      - type: delete
        disable : true # Related to Feature request https://github.com/cloud-custodian/cloud-custodian/issues/6005
```

**Describe alternatives you've considered**
I have a custom script that I run to complete this task as on date. Planning to move to a schedule based triggered lambda.

**Additional context**
None
