### ISSUE TITLE
aws - ebs - InvalidVolume.NotFound when calling the CreateTags operation

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#6011]
**Describe the bug**

The following exception is thrown

```
An error occurred (InvalidVolume.NotFound) when calling the CreateTags operation
```

**To Reproduce**

**Expected behavior**

**Background (please complete the following information):**
 - OS: lambda
 - Python Version: 3.8.1
 - Custodian Version: 0.9.4.0
 - Tool Version: N/A
 - Cloud Provider: aws
 - Policy:
```yaml
vars:
  mode: &mode
    type: periodic
    schedule: "rate(7 days)"
    role: arn:aws:iam::{account_id}:role/cloud-custodian
    tags:
      application: cloud-custodian
      team: sre
      env: production
    execution-options:
      output_dir: s3://output-bucket/cloud-custodian/output

policies:
- name: ebs-mark-unattached-deletion
  resource: ebs
  description: |
    Mark any unattached EBS volumes for deletion in 30 days.
    Volumes set to not delete on instance termination do have
    valid use cases as data drives, but 99% of the time they
    appear to be just garbage creation.
  mode:
    <<: *mode
  filters:
    - "tag:c7n_ignore": absent
    - "tag:c7n_status": absent
    - Attachments: []
    - type: mark-for-op
      tag: c7n_status
      msg: "Unused. If this resource should stay, add the tag c7n_ignore with a value of why it should exist."
      op: delete
      days: 30
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
The workaround for now has been to pin down cloudcustodian to 0.9.1.0.

**Comment by kapilt** [comment]
do you have the full traceback?

**Comment by nitrocode** [comment]
Yes. I modified the ticket to add it.

**Comment by ajkerrigan** [comment]
This came up [in Gitter](https://gitter.im/cloud-custodian/cloud-custodian?at=618afaf67db1e3753e9023b0) today also, courtesy of @cpitstick-argo :

> We run a lot of spot instances that wink in and out constantly. So sometimes, Cloud Custodian will attempt to tag a resource that doesn't exist, because in between the time it discovered the resource and tried to tag it, the tagging operation fails, so we get a lot of these types of errors:
An error occurred (InvalidVolume.NotFound) when calling the CreateTags operation: The volume 'vol-XXXXXXXXXXXXX' does not exist.

With a similar sample policy:

```
- name: ebs-tag-unattached-volume
  resource: ebs
  description: |
    EBS volume is unattached
  filters:
    - Attachments: []
  actions:
    - type: tag
      key: "cloud-custodian-flagged"
      value: "ebs-volume-is-unattached"
    - type: mark-for-op
      tag: cloud-custodian-action
      op: delete
      hours: 0
```
