### ISSUE TITLE
S3 buckets exception / whitelist

### ISSUE THREAD

**Issue by sreedharkurra** [cloud-custodian/cloud-custodian#6020]
how do we get exception/whitelist of few S3 buckets for custodian dry run and execution? The reason behind is we have few S3 buckets are restricted, So the custodian dry run is failing due to access denied, I'm looking for filter to get exception /whitelist of few buckets.

**Comment by kapilt** [comment]
you can use a filter to construct a valid set.

ie.

```
 - type: value
    key: Name
    op: in
    value:
      - A
      - B
      - C
```

alternatively use value_from to construct the allowed list out of band and stored in s3/url.
