### ISSUE TITLE
Conditional action execution

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#6024]
**Is your feature request related to a problem? Please describe.**
I am looking for conditions on actions, plain and simple :) This helps me solve a problem around only taking certain actions in certain accounts. I.E. in a Dev environment, delete something vs in a Prod environment, isolate it and notify. Traditionally, these small differences have resulted in a multiplication of `policy` by `type of environment` with different actions sometimes winding up with having to write the same thing 4 - 5 times with a small difference on one of the actions. Something like this could help to keep it to just 1 albeit meta-policy in the future.

**Describe the solution you'd like**
I'd like to add a conditions attribute to actions where I could check the `account_id` in a `value_from` and then decide if I'm in a prod environment or not. Another variation of this could be a timed action, i.e. do this thing until 8/8, then after 8/8 do this other thing. It enables some possibilities around dynamic policy interpretation that were not there before.

**Describe alternatives you've considered**

**Additional context**

**Comment by tjstansell** [comment]
This is why we use a jinja framework to build our c7n policies.  Way more granularity/control than trying to build it all into the c7n policies directly :) but i know that's not for everyone...

**Comment by JohnHillegass** [comment]
Jinja doesn't sound like a bad idea! I had played with `k14s/ytt` a while back and conceded Jinja was much easier to work with. In our controls environment, however, we have been trying to avoid the preprocessing steps because of the way things are setup. In some ways, conditions on actions could be a step towards custodian native templating 🎉

**Comment by PoeBlu** [comment]
> This is why we use a jinja framework to build our c7n policies.  Way more granularity/control than trying to build it all into the c7n policies directly :) but i know that's not for everyone...

.... how do you do this I am very interested and don't have the first clue

**Comment by kapilt** [comment]
what sort of conditions are you looking for?

**Comment by JohnHillegass** [comment]
I was thinking something like this, though may refine it now that we are talking about it. The utility would be timed actions without having to tag resources.

```yaml
policies:
  - name: ebs-encryption
     resource: ebs
     filters: 
       - Encrypted: false
     actions:
       - notify
          subject: EBS volumes need to be encrypted. We will start deleting these on 01-01-2021
          conditions:
            - type: value
               key: now
               op: less-than
               value_type: date
               value: "2021-01-01"  
       - delete
          conditions:
            - type: value
               key: now
               op: greater-than
               value_type: date
               value: "2021-01-01"  
       - notify
          subject: Your unencrypted EBS volumes have been deleted
          conditions:
            - type: value
               key: now
               op: greater-than
               value_type: date
               value: "2021-01-01"  
```

**Comment by JohnHillegass** [comment]
Conditions for policy execution also retain their utility in this model as well. For example, a condition for running a policy could be set, then once it starts running there could be a progression to the actions it takes. I admit this might hurt testability but the payoff on policy management overhead (one repo or bucket vs many) and gains in readability to 3rd party reviewers may be worth it.

**Comment by IngussNeilands** [comment]
One more use case could be:

`    filters:
      - or:
        - "tag:tag-v1": absent
        - "tag:tag-v2": absent
        - "tag:tag-v3": absent
    actions:
      - type: tag
        key: tag-v1
        value: "v1"
        conditions:
          - "tag:tag-v1": absent
      - type: tag
        key: tag-v2
        value: "v2"
        conditions:
          - "tag:tag-v2": absent
      - type: tag
        key: tag-v3
        value: "v3"
        conditions:
          - "tag:tag-v3": absent
`

**Comment by vauchok** [comment]
I like the @IngussNeilands 's example.

It'd be perfect to create just one policy for all tags rather than create the own policy for each tag, especially there are 30-50 tags...
Are there any solutions for such case @kapilt ?

Thanks

**Comment by vauchok** [comment]
Hi @kapilt 

Any thoughts about it?

it would be perfect to use just one policy, for instance to check the tags, rather than create the policy for each tag... especially if there are ~50 tags.

Thanks

**Comment by KISStian** [comment]
I agree that that this would be a welcome feature.  The ability to conditionally execute actions based on c7n-org properties/tags would certainly help to limit the number of policies that are needed to accomplish different tasks based on attributes of the target account.

**Comment by rymancl** [comment]
I just wanted to chime in on this to say this would be an amazing feature.

Here is my use case for this.
We'd like to perform actions based on this pseudo-code: 
```
if tag `deployed-by` != `automation`
  send notification via c7n-mailer &
  perform an action to update resource
if tag `deployed-by` == `automation`
  send notification via c7n-mailer
```

If a resource is controlled via automation (ie Terraform), we don't want to modify it in order to prevent drift. We just want to send a notification. 

In a policy, it might look roughly like this (using OP's suggested syntax):
```yaml
  - name: aws-cw-log-group-retention
    resource: aws.log-group
    description: |
      Handles CloudWatch log groups with no expiration set. 
    mode:
      type: periodic
      schedule: cron(0, 23, ?, *, SUN, *)
      role: arn:aws:iam::{account_id}:role/c7n
    filters:
     - retentionInDays: absent
    actions:
       - type: retention
         days: 7  
          conditions:
            - not:
              - type: value
                key: "tag:deployed-by"
                value: "automation"
        - type: notify
          <<: *notify-anchor
```
