### ISSUE TITLE
check-compliance fails to match iam-role because RoleId is not available

### ISSUE THREAD

**Issue by pzbiegiel** [cloud-custodian/cloud-custodian#6025]
The check-compliance filter cannot match IAM roles because compliance results are based on the RoleID.  However, that value, while it is visible in resources.json cannot be matched by the plugin.  

It appears that in the file c7n/resources/iam.py the value of id and name are set to the same value which is the name of the resource. (Line 110).  The value id should really point to RoleId so that is can match in the check-compliance filter code.

This seems to be repeated for other IAM resources which also have unique IDs associated with them.  

To reproduce, you can run the policy:
```
policies:
  - name: match-roles-to-config-rule
    resource: aws.iam-role
    filters:
      - type: config-compliance
        rules:
          - <name of config rule evaluating AWS::IAM::Role>
```
The output shows no matching roles even though they should.
Removing the filter results in all roles being matched.
