### ISSUE TITLE
Checking tag values for AWS resources

### ISSUE THREAD

**Issue by vmdude** [cloud-custodian/cloud-custodian#6026]
We use custodian regarding our compliance checks (mainly tag existence) and we wanted to go further by validating tag values as well.
We didn't find a way through custodian to allow check of tag values.
For instance we got this rule:

```yaml
vars:
  accounts:
    - XXX
  tag-filters: &tag-compliance-filters
        - "tag:application": empty
policies:
- name: ec2-tag-compliance-stop
  mode:
    type: periodic
    role: xxx
    schedule: "rate(5 minutes)"
  resource: ec2
  filters:
    - State.Name: running
    - or: *tag-compliance-filters
  actions:
    - stop
```

This check for existence of several tags. It work as expected, but we wanted to test the tag value to see it it matches the one allowed (which are hosted in a dynamodb table).
Is there a way to do this with custodian ?
Or can custodian call external program that will do the magic and return the result to custodian that it will take action if needed ?
