### ISSUE TITLE
IllegalLocationConstraintException writing logs when c7n_org is used on the ap-east-1 AWS region.

### ISSUE THREAD

**Issue by MichaelDavisTSN** [cloud-custodian/cloud-custodian#6028]
**Describe the bug**
When running c7n-org on the command line with a configuration file that includes the ap-east-1 region, and writing logs to an s3 bucket, the following error results:

2020-08-11 08:00:41,089: c7n_org:ERROR Exception running policy:cc-is-running account:<account name removed> region:ap-east-1 error:Failed to upload /tmp/tmp3jsyt81s/custodian-run.log.gz to tyson-cclogs/logs/out/<account name removed>/ap-east-1/cc-is-running/2020/08/11/13/custodian-run.log.gz: An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

**To Reproduce**
Run c7n-org (command line) on resources in the ap-east-1 region, writing logs to an s3 bucket (any region) with -s.

**Expected behavior**
Logs written to the specified bucket, regardless of the region being scanned.

**Background (please complete the following information):**
 - OS: Amazon Linux 2
 - Python Version: 3.7.8
 - Custodian Version: 0.9.4
 - Tool Version: c7n-org 0.6.3
 - Cloud Provider: aws
 - Policy: 
```yaml
policies:

- name: cc-is-running
  resource: ec2
  description: |
    Making sure CC is running by sending a positive result every hour.
  filters:
    - or:
      - "tag:Owner": "<email address removed>"
      - "tag:Owner": "<email address removed>"


  actions:
    - type: notify
      template: md-test.html
      subject: "CC is Running"
      violation_desc: "Mailer test from <hostname removed> successful."
      action_desc: "This is the action description."
      to:
        - michael.davis2@tyson.com
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/<account ID removed>/Cloud-Custodian-Mailer
        region: us-east-1
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

Custodian:   0.9.4
Python:      3.7.8 (default, Jul 24 2020, 20:26:49)
             [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)]
Platform:    posix.uname_result(sysname='Linux', nodename='awslpcc1', release='4.14.181-140.257.amzn2.x86_64', version='#1 SMP Wed May 27 02:17:36 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.26
botocore==1.17.26
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==41.2.0
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.1.0

**Additional context**
Possibly related:
https://github.com/aws/aws-cli/issues/4445
https://github.com/boto/boto3/issues/2098
-Same behavior occurs running 'aws s3api put-object to a bucket in ap-east-1 from an instance in ap-east-1
-So perhaps a workaround to a boto3 problem is needed somewhere in CC

**Comment by kapilt** [comment]
thanks for the additional context with those upstream issues refs thats useful.

**Comment by kapilt** [comment]
could you also confirm that you have opt-ed in to the ap-southeast-1 region, ie that its active in your account?

**Comment by MichaelDavisTSN** [comment]
It's ap-east-1, and yes. We even have resources there.

**Comment by MichaelDavisTSN** [comment]
Ok, another problem with ap-east-1 that may be related:
/usr/bin/c7n-org run -c /opt/cloud-custodian/etc/c7n_org_config/individual_accounts/entappsnonprod-devrole.yml -s s3://tyson-cclogs/logs/out/ --metrics -u /opt/cloud-custodian/policies/ec2-tag-compliance-host.yml
Output of command:
2021-01-25 11:04:52,626: c7n_org:ERROR Exception running policy:ec2-tag-compliance-host-untag account:entappsnonprod region:ap-east-1 error:An error occurred (InvalidClientTokenId) when calling the PutMetricData operation: The security token included in the request is invalid
2021-01-25 11:04:54,469: c7n_org:ERROR Exception running policy:ec2-tag-compliance-host account:entappsnonprod region:ap-east-1 error:An error occurred (InvalidClientTokenId) when calling the PutMetricData operation: The security token included in the request is invalid

The instance profile has cloudwatch:*

**Comment by vauchok** [comment]
Hi @kapilt 

The same issue with **eu-south-1**:

`2021-10-05 14:58:47,792: c7n_org:ERROR Exception running policy:vpc-tags account:xxxxxxxxxxx region:eu-south-1 error:Failed to upload /tmp/tmp6rn9r_m8/custodian-run.log.gz to c7n-logging/xxxxxxxxxxx/eu-south-1/vpc-tags/2021/10/05/14/custodian-run.log.gz: An error occurred (IllegalLocationConstraintException) when calling the PutObject operation: The eu-central-1 location constraint is incompatible for the region specific endpoint this request was sent to.`

The bucket was created in **eu-central-1**

Thanks

**Comment by vauchok** [comment]
It would help:
[comment](https://github.com/boto/boto3/issues/3015#issuecomment-929675187)

**Comment by wishamj** [comment]
It's worth mentioning that utilizing S3 bucket value lookups for filter lists can also result in the same issue, but for 'GetObject' as opposed to 'PutObject' - exact same error message otherwise.

Sample for clarity:
```
  filters:
    - type: value
      key: "tag:acceptedvalues"
      op: in
      value_from:
        url: s3://s3bucket/acceptedvalues.txt
        format: txt
```

2022-01-27 12:07:18,342: c7n_org:ERROR Exception running policy:ec2-tags account:aws_account region:ap-east-1 error:An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

Again, this works fine for all other regions attempting to utilize C7N PutObject (c7n-org log uploads to S3 bucket) or GetObject functions (exact same above policy, but in us-east-1, etc).
