### ISSUE TITLE
c7n-mailer - default slack_template incorrectly parsing resources

### ISSUE THREAD

**Issue by alextodicescu** [cloud-custodian/cloud-custodian#6036]
I'm trying to send a Slack message to alert on cross-account permissions for aws kms keys. I can't figure out why the `resources` passed in the slack message are too verbose, including more details than just the resource ids

**mailer.yml**
```
---
queue_url: <queue>
role: arn:aws:iam::<account>:role/<role>
region: <region>
from_address: <from>
ses_region: <region>
memory: 1024
runtime: python3.8
debug: true
timeout: 300
lambda_tags:
  Owner: <owner_tag>
  Service: <service_tag>
```

**policy**
```
---
policies:
  - name: kms-cross-account
    resource: kms-key
    description: Notify if cross-account access is granted to KMS keys
    mode:
      type: cloudtrail
      tags: 
        Owner: <owner_tag>
        Service: <service_tag>
      events:
        - source: kms.amazonaws.com
          event: CreateKey
          ids: responseElements.keyMetadata.arn
        - source: kms.amazonaws.com
          event: PutKeyPolicy
          ids: resources[].ARN
      role: arn:aws:iam::<account>:role/<role>
    filters:
        - type: cross-account
    actions:
      - type: notify
        to:
          - <slack_webhook>
        violation_desc: "Found a KMS key allowing cross-account access"
        action_desc: "INFO: No Action Taken"
        transport:
          type: sqs
          region: <region>
          queue: <mailer_queue>
```

Testing with a kms.PutKeyPolicy, the custodian policy picks up the cross-account KMS policy changes correctly
```
...
[INFO]	2020-08-13T11:45:59.843Z	Found resource ids:['arn:aws:kms:<region>:<account>:key/1111111-2222-33333-4444-55555555']
[INFO]	2020-08-13T11:46:00.182Z	Resources [{'KeyId': '1111111-2222-33333-4444-55555555', 'KeyArn': 'arn:aws:kms:<region>:<account>:key/1111111-2222-33333-4444-55555555, 'AWSAccountId': '<account>', 'Arn': 'arn:aws:kms:<region>:<account>:key/1111111-2222-33333-4444-55555555', 'CreationDate': datetime.datetime(2020, 8, 12, 18, 12, 45, 747000, tzinfo=tzlocal()), 'Enabled': True, 'Description': '', 'KeyUsage': 'ENCRYPT_DECRYPT', 'KeyState': 'Enabled', 'Origin': 'AWS_KMS', 'KeyManager': 'CUSTOMER', 'CustomerMasterKeySpec': 'SYMMETRIC_DEFAULT', 'EncryptionAlgorithms': ['SYMMETRIC_DEFAULT'], 'Tags': []}]
...
```

However the payload sent to slack will contain a very verbose resource section
eg
```
{
 "KeyId": "1111111-2222-33333-4444-55555555",
 "KeyArn": "arn:aws:kms:<region>:<account>:key/1111111-2222-33333-4444-55555555",
 "AWSAccountId": <account>,
 "Arn": "arn:aws:kms:<region>:<account>:key/1111111-2222-33333-4444-55555555",
 "CreationDate": "2020-08-12T18:12:45.747000+00:00",
 "Enabled": true,
 "Description": "",
 "KeyUsage": "ENCRYPT_DECRYPT",
 "KeyState": "Enabled",
 "Origin": "AWS_KMS",
 "KeyManager": "CUSTOMER",
 "CustomerMasterKeySpec": "SYMMETRIC_DEFAULT",
 "EncryptionAlgorithms": [
   "SYMMETRIC_DEFAULT"
 ],
 "Tags": [],
 "Policy": "{
 "Version" : "2012-10-17",
...
...
```

I've tested a little with custom slack_templates, but I wasn't able to get a valid slack payload so far
https://github.com/cloud-custodian/cloud-custodian/blob/master/tools/c7n_mailer/c7n_mailer/msg-templates/slack_default.j2

Before I test some more with custom slack_templates, is there anything that stands out that I'm doing wrong in the above **kms-cross-account** policy?
