### ISSUE TITLE
Should the tag action default to using UTC?

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#6037]
I have been playing around with tagging something with a timestamp and then using a value filter to see if it is 15 minutes after the timestamp. When running the below policy, it tags the resource in UTC so `timestamp = now + 4 hrs`
```
policies:
    - name: tz-test
      resource: aws.dynamodb-table
      actions:
        - type: tag
          key: timestamp
          value: "{now}"
```
I have found though that followup filters like the one below actually end up failing because the age filter is converting the timestamp to UTC again on the pull so it effectively ends up processing as `timestamp + 4 hours` or 8 hours from now
```
policies:
    - name: tz-15mins-after
      resource: aws.dynamodb-table
      filters:
        - type: value
           key: "tag:timestamp"
           value_type: age
           value: 0.0104167 # 15 minutes, for tag lag
           op: gte
```
If I do the initial tag with the postfix of UTC, this works as expected but wondering if that explicit UTC marking is the right way to handle this. It seems that the conversion to UTC when using `{now}` is already there on the tag but in the filter, it essentially gets double converted. 
```
    - name: tz-test
      resource: aws.dynamodb-table
      actions:
        - type: tag
          key: timestamp
          value: "{now} UTC"
```
