### ISSUE TITLE
IAM role termination issue.

### ISSUE THREAD

**Issue by sl805** [cloud-custodian/cloud-custodian#6044]
**Describe the bug**
Situation occurs when Claud-Custodian attempts to delete an IAM role created via AWS Console and leads to following error: 

`An error occurred (DeleteConflict) when calling the DeleteInstanceProfile operation: Cannot delete entity, must remove roles from instance profile first.`

Aforementioned error happens because when created via console AWS automatically creates IAM Profile with name identical to IAM role and adds it to an instance-profile. Association which occurs because of this, creates a dependency and blocks both IAM profile and role termination unless role is explicitly removed from profile.

**To Reproduce**
1. Create an IAM role via AWS Console.
2. Create Cloud-Custodian policy to delete this role using `delete` action

**Expected behavior**
1. Cloud-Custodian finds IAM role which has to be deleted
2. Cloud-Custodian checks if there's a profile with a name identical to this role
3. Cloud-Custodian removes role from IAM Profile.
4. Cloud-Custodian terminates IAM Profile.
5. Cloud-Custodian terminates IAM Role.

**Background (please complete the following information):**
 - OS: AmazonLinux 2018.03
 - Python Version:  python 3.8.1
 - Custodian Version: 0.9.4.0
 - Cloud Provider: aws
 - Policy: 
```yaml
policies: 
  - name: ec2-remove-admin-profile
    resource: ec2
    filters:
      - type: check-permissions
        match: allowed
        actions:
          - ec2:*
    actions:
      - type: set-instance-profile
        name: ''

  - name: delete-iam-administrator-role
    resource: iam-role
    filters:
      - type: has-specific-managed-policy
        value: AdministratorAccess
      - type: value
        key: RoleName
        op: ni
        value: [DevOps, QA]
    actions:
      - type: set-policy
        state: detached
        arn: "arn:aws:iam::aws:policy/AdministratorAccess"
      - delete
```
 - Traceback: 
`An error occurred (DeleteConflict) when calling the DeleteRole operation: Cannot delete entity, must remove roles from instance profile first`

`An error occurred (DeleteConflict) when calling the DeleteInstanceProfile operation: Cannot delete entity, must remove roles from instance profile first.`

 - `custodian version --debug` output
```bash
Custodian:   0.9.4
Python:      3.6.8 (default, Aug  2 2019, 17:42:44)          
Platform:    posix.uname_result(sysname='Linux', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.11.1
attrs==19.3.0
boto3==1.14.35
botocore==1.17.35
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==40.6.2
six==1.15.0
tabulate==0.8.7
urllib3==1.25.9
zipp==3.1.0
```

**Comment by kapilt** [comment]
so I think we should add this as another force option, which currently does some policy detachment, to also include profile cleanup.

**Comment by sl805** [comment]
@kapilt Hi thanks for your response.

> we'll need to validate what happens to the instances with extant refs to the profile.

To my understanding if we have a policy similar to one below executed before profile termination ec2-instances should not be affected with whatever happens next  with role or a profile or both.

```yaml
- name: ec2-remove-admin-profile
    resource: ec2
    filters:
      - type: check-permissions
        match: allowed
        actions:
          - ec2:*
    actions:
      - type: set-instance-profile
        name: default
```

> so I think we should add this as another force option, which currently does some policy detachment, to also include profile cleanup. 
 something like `delete_ec2_profile: true` might work if it will check if there's an instance-profile with a name equal to IAM role name we're trying to delete. If such role was found, perhaps we should do a request similar to shown below before profile termination attempt:
```python
client.remove_role_from_instance_profile(
    InstanceProfileName=<IAM-ROLE-NAME>,
    RoleName=<IAM-ROLE-NAME>
)
```

Regards.
