### ISSUE TITLE
SNS Transport Delivering Empty Message

### ISSUE THREAD

**Issue by avishayil** [cloud-custodian/cloud-custodian#6046]
I'm trying to utilize SNS transport in order to deliver messages from several accounts to SNS topic that is located in a designated account. A SQS queue is subscribed to the SNS topic.

I was hoping to use c7n-notify with c7n-mailer to deliver those messages to the SQS queue through the SNS topic but without success. The c7n-mailer is configured to pull messages from the SQS queue and send them using SES.

````
queue_url: https://sqs.us-east-1.amazonaws.com/{centralized_account}/CustodianMailerQueue
role: arn:aws:iam::{centralized_account}:role/CustodianMailer
from_address: email@domain.com
ses_region: us-east-1
````

In my policy I included the following configuration:
````
      - type: notify
        template: default.html
        priority_header: '2'
        subject: S3 Disable Public Block Event Detected
        violation_desc: "S3 Bucket Where Disable Public Block Event Detected:"
        action_desc: |
          "Actions Taken: The Violating S3 Allow Publick Block Rule Has Been Removed."
        to:
          - event-owner
        transport:
          type: sns
          topic: arn:aws:sns:us-east-1:{centralized_account}:CustodianMailerTopic
````

But when i'm looking at the custodian policy lambda log I can see the following:
````
[INFO]	2020-08-18T19:56:52.440Z	c635a52c-a1cb-4596-88c6-6bd7888a077b	sent message:None policy:s3-public-block-enable-all-event template:default.html count:1
--
````

Any idea why is the message empty? Of course that this configuration is not delivering any messages at the end, and I can't see any messages reaching the SQS queue.

What am I doing wrong?
