### ISSUE TITLE
Filter gke-clusters by labels

### ISSUE THREAD

**Issue by dbarranco** [cloud-custodian/cloud-custodian#6053]
Hello folks!

I am working on adding support for the "delete" operation for the `gcp.gke-cluster` resource and before starting coding the _delete_ function I did some tests to filter GKE clusters in one of my Google Cloud Projects.

All of the clusters I'm interested in contain the following Google Cloud labels:

![Screenshot 2020-08-20 at 17 02 52](https://user-images.githubusercontent.com/9199512/90789290-0a947880-e307-11ea-98ea-569bd93c75f4.png)

But when I try to filter some of them by adding policies like:

```
policies:
- name: bkpr-delete-gke-clusters
  resource: gcp.gke-cluster
  comment: |
    Clean-up temporary R53 hosted zones created by Jenkins-BKPR
    for its continuous integration tests
  filters:
    - 'tag:created_by': 'jenkins-bkpr'
```

I see that none of them got filtered.
I also have tried with some variations, like:

```
  filters:
    - type: value
      key: Name
      op: eq
      value: "<. . .>"
```

or 

```
  filters:
    - type: value
      label: 'created_by'
      op: eq
      value: 'jenkins-bkpr'
```

But still, it doesn't work.
Am I missing something here?

Thanks in advance.
