### ISSUE TITLE
aws - cloudhsm classic not available anymore

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#6059]
**Describe the bug**
Looks like AWS has decommissioned `cloudhsm` apis

 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
  - name: alarm-tag
    resource: hsm-client
```
```yaml
policies: 
  - name: alarm-tag
    resource: hsm
```
```yaml
policies: 
  - name: alarm-tag
    resource: hsm-hapg
```

 - Traceback: [if applicable, please exclude sensitive/account information]
```
botocore.errorfactory.CloudHsmServiceException: An error occurred (CloudHsmServiceException) when calling the ListLunaClients operation: This service is unavailable.  Please see https://aws.amazon.com/cloudhsm/faqs-classic/
```
```
botocore.errorfactory.CloudHsmServiceException: An error occurred (CloudHsmServiceException) when calling the ListHsms operation: This service is unavailable.  Please see https://aws.amazon.com/cloudhsm/faqs-classic/
```
```
botocore.errorfactory.CloudHsmServiceException: An error occurred (CloudHsmServiceException) when calling the ListHapgs operation: This service is unavailable.  Please see https://aws.amazon.com/cloudhsm/faqs-classic/
```
