### ISSUE TITLE
GCP - Find firewall ingress rules allowing public acces to SSH

### ISSUE THREAD

**Issue by LiMiToDriGe** [cloud-custodian/cloud-custodian#6064]
I'm attemping to write a policy that will return me all firewall ingress rules allowing public access to ssh.

here is the policy I wrote:

```yaml
policies:
        - name: test_policy_firewall
          resource: gcp.firewall
          filters:
                  - and:
                          - type: value
                            key: direction
                            value: INGRESS
                          - type: value
                            key: sourceRanges
                            value_type: swap
                            op: in 
                            value: 0.0.0.0/0
                          - type: value
                            key: allowed.ports
                            value_type: swap
                            op: in
                            value: 22
```
The issue is in the last filter, without, the policy works fine and return me all ingress rules with source range 0.0.0.0/0 but I need to filter more to have only rules with ssh. I tried several thing but nothing work.

**Comment by LiMiToDriGe** [comment]
```yaml
policies:
        - name: Firewall_Ingress_rule_allowing_public_access_ssh
          resource: gcp.firewall
          filters:
                  - and:
                          - type: value
                            key: direction
                            value: INGRESS
                          - type: value
                            key: sourceRanges
                            value_type: swap
                            op: in
                            value: 0.0.0.0/0
                          - type: value
                            key: allowed[].ports[]
                            value_type: swap
                            op: in
                            value: "22"
```
