### ISSUE TITLE
ebs type filter on an ec2 volume does not evaluate encryption correctly on attachment of additional volume

### ISSUE THREAD

**Issue by Bunnikins** [cloud-custodian/cloud-custodian#6079]
**Describe the bug**
I have created a custodian rule that triggers on the launch of an EC2 instance or attachment of an EBS volume to an existing EC2 instance (confirmed from Lambda logs as triggering on both events). The rule is configured to detect instances with an EBS volume attached that is not encrypted with a valid KMS Key. The event triggers successfully on launch of EC2 instances and successfully detects an unencrypted root volume. It also triggers on adding a new, unencrypted EBS volume to an existing instance with an encrypted root volume. However, reviewing Lambda logs shows that in the case of adding the second, unencrypted volume, the rule is triggered and evaluates, but filters out the resource with the unencrypted volume attached.

**To Reproduce**
- Create custodian role as follows:

```yaml
- policies
  - name: detect-unencrypted-ec2-instances
    resource: ec2
    mode:
      type: cloudtrail
      delay: 30
      events:
        - RunInstances
        - source: 'ec2.amazonaws.com'
          ids: 'responseElements.instanceId'
          event: AttachVolume
    filters:
    - not:
      - and:
        - type: ebs
          key: Encrypted
          value: true
        - type: ebs
          key: KmsKeyId
          op: regex
          value: ^arn:aws:kms:.*$
    actions:
      - type: post-finding
```
- Create EC2 instance with KMS-encrypted root volume.
- Create unencrypted EBS volume
- Attach unencrypted EBS volume to EC2 instance with KMS-encrypted root volume
- Verify that rule has triggered and evaluated, and that the evaluation identified both attached ebs volumes but the addition of the unencrypted EBS volume has not caused a match

**Expected behavior**
On addition of an unencrypted EBS volume to the existing EC2 instance, I expected the above rule to trigger (it did), evaluate the instance to which the volume had been attached (it did), the evaluation to 'see' both volumes attached to the instance (it did) and then for the filter to match the unencrypted volume (it filtered it out) and post a finding (which didn't happen because it filtered out).

**Background (please complete the following information):**
 - OS: Gitlab runner with docker container cloudcustodian/c7n-org:0.9.3.0
 - Python Version: Gitlab runner with docker container cloudcustodian/c7n-org:0.9.3.0
 - Custodian Version: Gitlab runner with docker container cloudcustodian/c7n-org:0.9.3.0
 - Tool Version: Gitlab runner with docker container cloudcustodian/c7n-org:0.9.3.0
 - Cloud Provider: AWS
 - Policy: 
```yaml
```
- policies
  - name: detect-unencrypted-ec2-instances
    resource: ec2
    mode:
      type: cloudtrail
      delay: 30
      events:
        - RunInstances
        - source: 'ec2.amazonaws.com'
          ids: 'responseElements.instanceId'
          event: AttachVolume
    filters:
    - not:
      - and:
        - type: ebs
          key: Encrypted
          value: true
        - type: ebs
          key: KmsKeyId
          op: regex
          value: ^arn:aws:kms:.*$
    actions:
      - type: post-finding
```
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
