### ISSUE TITLE
batchimportfindings

### ISSUE THREAD

**Issue by davidclin** [cloud-custodian/cloud-custodian#6090]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
