### ISSUE TITLE
"custodian report" behavior when multiple policies match a resource

### ISSUE THREAD

**Issue by christophetd** [cloud-custodian/cloud-custodian#6103]
I would have expected that `custodian report` reports multiple time the same resource when it matches multiple policies.

For instance, I have the following policy:

```yaml
policies:
- name: s3-bucket-open-to-the-world
  resource: aws.s3
  filters:
  - type: global-grants

- name: s3-bucket-without-public-access-block
  resource: aws.s3
  filters:
  - or:
    - type: check-public-block
      BlockPublicAcls: false
    - type: check-public-block
      BlockPublicPolicy: false
    - type: check-public-block
      IgnorePublicAcls: false
    - type: check-public-block
      RestrictPublicBuckets: false
```
Observations:
- If I create a world-readable S3 bucket, the output of `custodian report` only shows that the policy `s3-bucket-without-public-access-block` matches

- If I invert the order of the two policies, the output now shows `s3-bucket-open-to-the-world`

Question: Is it possible to have cloud custodian output all the policies that a resource matches? Currently, it seems to output the last matching one it finds in the policy file
