### ISSUE TITLE
Default days for mark-for-op is zero not four as documented.

### ISSUE THREAD

**Issue by howbazaar** [cloud-custodian/cloud-custodian#6106]
**Describe the bug**
The tag generated in mark-for-op with minimal specified args incorrectly marks as today.

**To Reproduce**
Create an ec2 machine with tag 'Custodian' = 'test'
Run the policy:
```
policies:
  - name: check-mark-for-op
    resource: aws.ec2
    filters:
      - "tag:Custodian": present
    actions:
      - type: mark-for-op
        op: stop
```
Tag created was `Resource does not meet policy: stop@2020/09/07`

**Expected behavior**
Expected tag to be `Resource does not meet policy: stop@2020/09/11`

**Background (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.8.2
 - Custodian Version: master (0.9.6)
 - Cloud Provider: aws
