### ISSUE TITLE
Azure: diagnostic-settings Value:False doesnot work

### ISSUE THREAD

**Issue by rachgupt** [cloud-custodian/cloud-custodian#6129]
**Describe the bug**
The filter diagnostic-settings seems to only work for value type True. For example if there are 2 public ip and one has diagnostic enabled. Then it will list that if we filter value filter true. But we need the ones where diagnostic is not enabled in a real scenario. This seems to be true for most products i tested.

**To Reproduce**
    policies:
      - name: az-publicip-with-logs-enabled
        resource: azure.publicip
        filters:
          - type: diagnostic-settings
            key: logs[?category == 'DDoSProtectionNotifications'][].enabled
            value: False
            op: in
            value_type: swap

If i replace value: True, then it filters the ones where diagnostic is enabled.

**Expected behavior**
When we filter value: False, it should list all non compliant resources. Instead it doesn't return anything.

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]: Description:    Ubuntu 18.04.5 LTS
 - Python Version: [e.g. python 3.8.1]: Python 3.6.9
 - Custodian Version: [e.g. 0.8.46.1]: 0.9.4
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]: Azure
 - Policy: [please exclude any account/sensitive information]
```yaml
    policies:
      - name: az-publicip-with-logs-enabled
        resource: azure.publicip
        filters:
          - type: diagnostic-settings
            key: logs[?category == 'DDoSProtectionNotifications'][].enabled
            value: False
            op: in
            value_type: swap

```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output
```
custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.4
Python:      3.6.9 (default, Jul 17 2020, 12:50:27)
             [GCC 8.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='custodian1', release='5.4.0-1023-azure', version='#23~18.04.1-Ubuntu SMP Thu Aug 20 14:46:48 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed:

PyJWT==1.7.1
adal==1.2.4
antlr4-python3-runtime==4.8
applicationinsights==0.11.9
apscheduler==3.6.3
argcomplete==1.12.0
attrs==19.3.0
azure-cli-core==2.0.81
azure-cli-nspkg==3.0.4
azure-cli-telemetry==1.0.4
azure-common==1.1.25
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.3.0
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.6.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.1.7
boto3==1.14.31
botocore==1.17.31
c7n==0.9.5
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
click==7.1.2
colorama==0.4.3
cryptography==3.0
distlib==0.3.1
docutils==0.15.2
humanfriendly==4.18
idna==2.10
importlib-metadata==1.7.0
importlib-resources==3.0.0
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.4.1
jsonschema==3.2.0
knack==0.6.3
msrest==0.6.18
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.1
portalocker==1.7.1
pycparser==2.20
pygments==2.6.1
pynacl==1.4.0
pyopenssl==19.1.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
s3transfer==0.3.3
setuptools==39.0.1
six==1.15.0
tabulate==0.8.7
tzlocal==2.1
urllib3==1.25.10
wheel==0.30.0
zipp==3.1.0

```

**Additional context**

**Comment by h-dub** [comment]
confirmed this is a defect
investigating a resolution

**Comment by kapilt** [comment]
closed in #6308

**Comment by h-dub** [comment]
Here is the policy used for validation. Both the absent and false cases need to be covered.
```
policies:
  - name: az-publicip-without-ddosnotify
    resource: azure.publicip
    filters:
      - or:
        - type: diagnostic-settings
          key: logs[?category == 'DDoSProtectionNotifications'][].enabled
          value: absent
        - type: diagnostic-settings
          key: logs[?category == 'DDoSProtectionNotifications'][].enabled
          value: False
          op: in
          value_type: swap
```
