### ISSUE TITLE
Auto tag for CreateDBCluster is trying to identify DescribeDBInstances rather than cluster

### ISSUE THREAD

**Issue by mharini** [cloud-custodian/cloud-custodian#6137]
Policy:

```
- name: tag-compliance-aurora
    resource: aws.rds
    comment: |
      Add tag for RDS at creation
    mode:
      type: cloudtrail
      events:
      - source: rds.amazonaws.com
        event: CreateDBCluster
        ids: requestParameters.dBClusterIdentifier
    actions:
      - type: tag
        key: backup_resource
        value: rds
```

Logs:

```Found resource ids:['auto-tag-serverless-test']```

```event ids not resolved: ['auto-tag-serverless-test'] error:An error occurred (DBInstanceNotFound) when calling the DescribeDBInstances operation: DBInstance auto-tag-serverless-test not found.```
