### ISSUE TITLE
Not able to enable perfromance insight on AWS RDS

### ISSUE THREAD

**Issue by RazaHasan84** [cloud-custodian/cloud-custodian#6146]
**Describe the bug**
enabling performance insight is failing with key error KeyError: 'EnablePerformanceInsights', although its a valid parameter as per schema of action "modify-db" [validated by running command :custodian schema rds.actions.modify-db] 
**To Reproduce**
Steps to reproduce the behavior: Here is the filter and action of my policy 
       filters:
             - DBInstanceStatus: available
             - PerformanceInsightsEnabled: False
       actions:
            - type: modify-db
              update:
                - property: 'EnablePerformanceInsights'
                  value: true
              immediate: true

ERROR : 
2020-09-22 20:32:45,890: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
.
rds.py", line 1640, in process
    if r[update['property']] != update['value']:
KeyError: 'EnablePerformanceInsights'

**Expected behavior**
- Should enable performance insight 

**Background (please complete the following information):**
 - OS: MAC 
 - Python Version: Python 3.7.7
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: N/A
 - Cloud Provider: [aws ]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: rds-enable-performanceinsights
      resource: rds
       filters:
             - DBInstanceStatus: available
             - PerformanceInsightsEnabled: False
       actions:
            - type: modify-db
              update:
                - property: 'EnablePerformanceInsights'
                  value: true
              immediate: true
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
