### ISSUE TITLE
possible to copy-related-tag from AMI to ebs-snapshot?

### ISSUE THREAD

**Issue by JonGilmore** [cloud-custodian/cloud-custodian#6147]
Is it possible to use `copy-related-tag` to copy all tags from AMIs to their associated ebs-snapshot's? I feel like it _might_ be possible because when I lookup `ebs-snapshot` and `ami`'s in my accounts, they both have an associated `SnapshotId`. Here's an example policy that I have attempted so far:

```
policies:
  - name: tag-snapshot-from-ami
    resource: ebs-snapshot
    actions:
      - type: copy-related-tag
        resource: ami
        skip_missing: True
        key: "ImageId"
        tags: "*"
```
