### ISSUE TITLE
aws - service catalog portfolios public sharing

### ISSUE THREAD

**Issue by PratMis** [cloud-custodian/cloud-custodian#6148]
**Is your feature request related to a problem? Please describe.**
We want to make sure that service catalog portfolio is not shared with external accounts.

**Describe the solution you'd like**
1. In servicecatalog.py create a `resource: catalog-portfolio`
2. Create a `cross-account` filter for `resource: catalog-portfolio`. The filter would use list_portfolio_access api(https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/servicecatalog.html#ServiceCatalog.Client.list_portfolio_access) which returns a list of account id.
3. The returned list of account_id would be matched with whitelisted (whitelist and whitelist_from) accounts in the policy

Sample Policy:
```
policies:
  - name: portfolio-cross-account
    resource: catalog-portfolio
    filters:
      - type: cross-account
        whitelist_from:
          expr: "abc.*.accountnumber"
          url: *accounts_url
```

**Describe alternatives you've considered**

**Additional context**
Currently portfolios can only be shared with its own ORGANIZATION or ORGANIZATIONAL_UNIT which should not be a risk imo. But it can be shared with external accounts, hence the feature request
