### ISSUE TITLE
S3 CloudWatch Metrics

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#6151]
**Describe the bug**
I've a S3 metrics policy with filters for all storage types. I'm getting only metrics for StorageType: StandardStorage , but not for all. 

**To Reproduce**
policies:
        - name: s3-metrics
          resource: s3
          filters:
             - or:
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardStorage
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardIAStorage
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardIASizeOverhead
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                            StorageType: StandardIAObjectOverhead
                    period: 300
                    days: 2
                    value: 0
                    op: gt

**Expected behavior**
Should return all metric values

**Background (please complete the following information):**
 - OS: [Amazon linux 2]
 - Python Version: [python 3.8.1]
 - Custodian Version: [ 0.9.5]
 - Tool Version: [if applicable]
 - Cloud Provider: [aws]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
        - name: s3-metrics
          resource: s3
          filters:
             - or:
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardStorage
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardIAStorage
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                             StorageType: StandardIASizeOverhead
                    period: 300
                    days: 2
                    value: 0
                    op: gt
                    statistics: Average
                  - type: metrics
                    name: BucketSizeBytes
                    namespace: 'AWS/S3'
                    dimensions:
                            StorageType: StandardIAObjectOverhead
                    period: 300
                    days: 2
                    value: 0
                    op: gt
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
Custodian using get_metric_statistics, were it's returning only 1 metric information. Looks like need to change the API to get_metric_data
