### ISSUE TITLE
Enhancement Req - Filter glue-jobs with glue connection type network

### ISSUE THREAD

**Issue by kumarsiyer** [cloud-custodian/cloud-custodian#6170]
We wanted to enforce all glue-jobs to run on a vpc. The only way to achieve this now is by attaching a glue-connection of type network.

Currently custodian can list only connection names, the proposed solution is to filter glue-jobs with connection type as network. The policy might look like below : 

```
  - name: glue-job-enforce-vpc
    resource: glue-job
    filters:
      - type: glue-connecion
        key: ConnectionType
        value: NETWORK
```
