### ISSUE TITLE
aws.ec2 - copy-related-tag from ami resource

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#6173]
**Is your feature request related to a problem? Please describe.**
I'd like to tag my EC2 instances with their respective tags coming from the ImageId resource each EC2 contains 

**Describe the solution you'd like**
I want to use the `copy-related-tag` action to copy specific tags from the AMI to the EC2 that use that AMI

**Describe alternatives you've considered**

**Additional context**

```yaml
policies:
- name: ec2-copy-tag-from-ami
  resource: ec2
  description: |
    Copy related tags from AMI to EC2
  filters:
    - "tag:team": "sre"
  actions:
    - type: copy-related-tag
      resource: ami
      key: "ImageId"
      tags: "*"
```

@jtroberts83
