### ISSUE TITLE
[ERROR] KeyError: ‘QueueUrl’ : SQS Tag Compliance Policy with Config Mode Failing 

### ISSUE THREAD

**Issue by gulati-diksha** [cloud-custodian/cloud-custodian#6176]
**Describe the bug**
-> After deploying the SQS Tag Compliance policy with config-rule mode in the AWS environment, I am encountering an error listed below:
 
[ERROR] KeyError: ‘QueueUrl’
Traceback (most recent call last):
File “/var/task/custodian_policy.py”, line 4, in run
return handler.dispatch_event(event, context)
File “/var/task/c7n/handler.py”, line 166, in dispatch_event
p.push(event, context)
File “/var/task/c7n/policy.py”, line 1134, in push
return mode.run(event, lambda_ctx)
File “/var/task/c7n/policy.py”, line 850, in run
resources = super(ConfigRuleMode, self).run(event, lambda_context)
File “/var/task/c7n/policy.py”, line 438, in run
resources = self.policy.resource_manager.filter_resources(
File “/var/task/c7n/manager.py”, line 111, in filter_resources
resources = f.process(resources, event)
File “/var/task/c7n/filters/core.py”, line 342, in process
sweeper = AnnotationSweeper(self.get_resource_type_id(), resources)
File “/var/task/c7n/filters/core.py”, line 400, in init
ra_map[r[id_key]] = {k: v for k, v in r.items() if k.startswith(‘c7n’)}

The config rule created through this policy shows "No resources in scope"
The issue seems to be related to SQS package managing the or+and filters, that doesn’t support the filter conditions properly, as when I am trying single level filters, it is working as expected.

Single level filter example:
```
- tag:tag1: absent
- tag:tag2: absent
- tag:tag3: absent
- tag:tag4: absent
```
When I take this policy and switch out the resource from SQS to Lambda, it functions properly. Same for EC2 or S3 resource. 

-> The similar issue is coming for codebuild tag compliance policy:

[ERROR] 2020-10-05T18:24:53.771Z ac1cd816-893b-4b4a-a723-e1be2bce7a68 error during policy execution
Traceback (most recent call last):
File "/var/task/c7n/handler.py", line 166, in dispatch_event
p.push(event, context)
File "/var/task/c7n/policy.py", line 1134, in push
return mode.run(event, lambda_ctx)
File "/var/task/c7n/policy.py", line 850, in run
resources = super(ConfigRuleMode, self).run(event, lambda_context)
File "/var/task/c7n/policy.py", line 438, in run
resources = self.policy.resource_manager.filter_resources(
File "/var/task/c7n/manager.py", line 111, in filter_resources
resources = f.process(resources, event)
File "/var/task/c7n/filters/core.py", line 318, in process
return self.process_set(resources, event)
File "/var/task/c7n/filters/core.py", line 330, in process_set
resource_map = {r[rtype_id]: r for r in resources}
File "/var/task/c7n/filters/core.py", line 330, in <dictcomp>
resource_map = {r[rtype_id]: r for r in resources}
KeyError: 'name'

**To Reproduce**
Deploy the policies in your account and check your config rule and cloudformation logs.

Note: Change the account number and role name.

**Expected behavior**
On successful execution of the policy, the config rule should flag the SQS queues with missing required tags as Non-compliant resource.

**Background (please complete the following information):**
 - Python Version: 3.8.5
 - Custodian Version: 0.9.6
 - Tool Version: [if applicable]
 - Cloud Provider: AWS
 - Policy: 
```
---
policies:
  - name: d-sqs-queue-tags
    resource: aws.sqs
    description: >
      Type: Config Rule|
      Compliance: Tags missing
    mode:
      type: config-rule
      tags:
        RolePrefix: sqsDetective
      role: "arn:aws:iam::acc_number:role/role_name"
    filters:
      - and:
          - or:
              - tag:Detail: absent
              - tag:ApplicationIDName: absent
          - tag:__ExTags: absent
    actions:
      - type: notify
        Message: SQS Tags Missing
        Subject: SQS NonCompliant
        to:
          - arn:aws:sns:us-east-1:acc_number:topic_name
        transport:
          topic: topic_name
          type: sns
```
CODEBUILD POLICY:
```
---

policies:
  - name: d-codebuild-missing-tags-2
    resource: aws.codebuild
    description: "Type: Config Rule. Compliance: Tags Missing."
    mode:
      type: config-rule
      role: "arn:aws:iam::<acc_number>:role/<role_name>"
      timeout: 200
    filters:
      - and:
          - or:
              - tag:abc: absent
              - tag:xyz: absent
              - tag:name: absent
          - tag:__def: absent
    actions:
      - type: notify
        Message: Required Tags Missing
        Subject: CodeBuild NonCompliant
        to:
          - <topic_arn>
        transport:
          topic: <topic_name>
          type: sns
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
