### ISSUE TITLE
aws - Route53 - mode config-poll-rule bug

### ISSUE THREAD

**Issue by jcwang84** [cloud-custodian/cloud-custodian#6197]
**Describe the bug**
Lambda trackback error

[ERROR]	2020-10-09T10:07:28.604Z	e8256a98-18aa-4c19-a9f1-da1e3f32c93d	error during policy executionTraceback (most recent call last):  File "/var/task/c7n/handler.py", line 166, in dispatch_event    p.push(event, context)  File "/var/task/c7n/policy.py", line 1134, in push    return mode.run(event, lambda_ctx)  File "/var/task/c7n/policy.py", line 434, in run    resources = self.resolve_resources(event)  File "/var/task/c7n/policy.py", line 629, in resolve_resources    return super().resolve_resources(event)  File "/var/task/c7n/policy.py", line 406, in resolve_resources    resource_ids = CloudWatchEvents.get_ids(event, mode)  File "/var/task/c7n/cwe.py", line 146, in get_ids    resource_ids = cls.get_trail_ids(event, mode)  File "/var/task/c7n/cwe.py", line 110, in get_trail_ids    event_name = event['detail']['eventName']KeyError: 'detail'
--

**To Reproduce**
config-poll-rule for route53 after deploying as AWS config rule

**Expected behavior**
give compliance and none compliance resources

**Background (please complete the following information):**
 - Python Version: lambda 3.8
 - Custodian Version: 0.9.6
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
---

policies:
  - name: d-healthcheck-required-tags
    resource: aws.healthcheck
    description: >
      Compliance: route53 HealthCheck required tags missing|
      Remediation: Tag it as NonCompliant
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
      tags:
        RolePrefix: route53Detective
    filters:
      - and:
          - or:
              - tag:CostCenter: absent
              - tag:RSMs: absent
              - tag:ApplicationIDName: absent
          - tag:__Exception-R53HealthCheckTags: absent
```

```yaml
---

policies:
  - name: d-hostedzone-logging
    resource: aws.hostedzone
    description: >
      Compliance: route53 HostedZone query logging disabled|
      Remediation: Enable Logging
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
      tags:
        RolePrefix: route53Detective
    filters:
      - and:
          - type: query-logging-enabled
            state: false
          - tag:__Exception-R53HostedZonesLogging: absent
```
 - Traceback: [[ERROR]	2020-10-09T10:07:28.604Z	error during policy executionTraceback (most recent call last):  File "/var/task/c7n/handler.py", line 166, in dispatch_event    p.push(event, context)  File "/var/task/c7n/policy.py", line 1134, in push    return mode.run(event, lambda_ctx)  File "/var/task/c7n/policy.py", line 434, in run    resources = self.resolve_resources(event)  File "/var/task/c7n/policy.py", line 629, in resolve_resources    return super().resolve_resources(event)  File "/var/task/c7n/policy.py", line 406, in resolve_resources    resource_ids = CloudWatchEvents.get_ids(event, mode)  File "/var/task/c7n/cwe.py", line 146, in get_ids    resource_ids = cls.get_trail_ids(event, mode)  File "/var/task/c7n/cwe.py", line 110, in get_trail_ids    event_name = event['detail']['eventName']KeyError: 'detail']
 - `custodian version --debug` output

**Additional context**
