### ISSUE TITLE
 'DescribeKey' object has no attribute 'log'

### ISSUE THREAD

**Issue by rikkuness** [cloud-custodian/cloud-custodian#6198]
**Describe the bug**
Using a KMS type resource, where access to the KMS key is denied, a log call is made that seems to not be present.

**To Reproduce**
Run a policy against an AWS KMS resource where the IAM role used does not have access to the resource.

**Background (please complete the following information):**
 - OS: Lambda (Linux)
 - Python Version: 3.x
 - Custodian Version: 0.9.6
 - Cloud Provider: aws
 - Policy: 
```yaml
policies: 
  - name: kms-key-rotation
    resource: kms-key
    filters:
      - type: key-rotation-status
        key: KeyRotationEnabled
        value: false
```

```
Exception running policy:kms-key-rotation account:<redacted> region:eu-west-1 error:'DescribeKey' object has no attribute 'log'
```

**Additional context**
I think the issue is perhaps calling `self.log` where `DescribeKey` or parent `DescribeSource` does not contain that method https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/kms.py#L73-L75
