### ISSUE TITLE
Not able to postfinding to AWS  Security Hub

### ISSUE THREAD

**Issue by XuejiaoZhang** [cloud-custodian/cloud-custodian#6207]
**Describe the bug**
Not able to postfinding to AWS Security Hub using postfinding action  in the policy file

**To Reproduce**
on AWS Cloud9, run
$ custodian run -s out policy.yml

**Expected behavior**
able to postfinding to AWS  Security Hub

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15] $ uname -r 4.14.193-113.317.amzn1.x86_64
 - Python Version: [e.g. python 3.8.1]  Python 3.6.12
 - Custodian Version: [e.g. 0.8.46.1]  0.9.6
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure] aws
 - Policy: [please exclude any account/sensitive information]
```
policies:
    - name: ec2-tag-compliance
      resource: ec2
      description: | 
        Find all non-compliant tag instances for stopage in 1 day.
      mode:
        type: config-rule
        role: arn:aws:iam::xxx:role/xxx
      filters:
        - "tag:Custodian": present
        - "tag: maid_status": absent
        # - or:
        #     - "tag:App": absent
      actions:
        - type: post-finding
          severity_normalized: 30
          compliance_status: WARNING
          types:
            - "Software and Configuration Checks/AWS Security Best Practices"
        - type: mark-for-op
          op: stop
          days: 1 
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output
```
$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.6
Python:      3.6.12 (default, Aug 31 2020, 18:56:18) 
             [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-172-31-32-193', release='4.14.193-113.317.amzn1.x86_64', version='#1 SMP Thu Sep 3 19:08:08 UTC 2020', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.1
attrs==20.2.0
boto3==1.15.8
botocore==1.18.8
importlib-metadata==2.0.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==40.6.2
six==1.15.0
tabulate==0.8.7
urllib3==1.25.10
zipp==3.2.0
```

**Additional context**

Cloudwatch Logs of Lambda:
```
[ERROR]	2020-10-13T09:26:42.230Z	c63ddcbd-42cd-4a58-b7c3-78c0ec5871d9	Error while executing policyTraceback (most recent call last):  File "/var/task/c7n/policy.py", line 480, in run_resource_set    results = action.process(resources)  File "/var/task/c7n/resources/securityhub.py", line 409, in process    finding = self.get_finding(  File "/var/task/c7n/resources/securityhub.py", line 531, in get_finding    finding_resources.append(self.format_resource(r))  File "/var/task/c7n/resources/ec2.py", line 1145, in format_resource    "LaunchedAt": r["LaunchTime"].isoformat()AttributeError: 'str' object has no attribute 'isoformat' | [ERROR] 2020-10-13T09:26:42.230Z c63ddcbd-42cd-4a58-b7c3-78c0ec5871d9 Error while executing policy Traceback (most recent call last): File "/var/task/c7n/policy.py", line 480, in run_resource_set results = action.process(resources) File "/var/task/c7n/resources/securityhub.py", line 409, in process finding = self.get_finding( File "/var/task/c7n/resources/securityhub.py", line 531, in get_finding finding_resources.append(self.format_resource(r)) File "/var/task/c7n/resources/ec2.py", line 1145, in format_resource "LaunchedAt": r["LaunchTime"].isoformat() AttributeError: 'str' object has no attribute 'isoformat'
-- | --

```
