### ISSUE TITLE
value_from dynamo query

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#6210]
Currently `value_from` supports http requests and s3 buckets, but this can cause problems with large files. it would be nice to have the option to store these large files in dynamo and to be able to query it using value_from.

for example

```

policies:
  - name: vpc-with-dynamodb-value-from
    resource: vpc
    filters:
      - type: value
        key: 'tag:Name'
        value_from:
          url: 'dynamodb:us-east-1:644160558196:table/test'
          format: json
          query: 
            KeyConditionExpression: '#n2 = :v1'
            FilterExpression: 'contains(#n0.#n1, :v0)'
            ExpressionAttributeNames: {'#n0': 'exceptions', '#n1': 'exception1', '#n2': 'test'}
            ExpressionAttributeValues: {':v0': 'testing-vpc', ':v1': '1111111111' }
          expr: '[0].exceptions.exception1'
        op: in

```
