### ISSUE TITLE
Issue with KMS policy filtering down to 0 results

### ISSUE THREAD

**Issue by Sykes-P** [cloud-custodian/cloud-custodian#6215]
Using the custodian documentation I've written a policy to find keys not on rotation and enable rotation on them.  It was working until it would find a key that was marked for deletion and the lambda would terminate with an error.  I added a filter to only look for keys that are enabled.  The problem is the policy finds the keys and returns that it found the correct number of keys (a manual query confirms this) but for some reason it's filtering down to 0.

| [DEBUG] 2020-10-14T17:24:00.13Z  Filtered from 117 to 0 key. -- | --

Here is the filter + action I'm using:

```yaml
    filters:
      - and:
        - type: value
          key: Keystate
          value: Enabled
          op: eq
        - type: key-rotation-status
          key: KeyRotationEnabled
          value: False
          op: eq
    actions:
        - type: set-rotation
          state: True
          action_desc: |
           "Actions Taken: Enabled key rotation status"
```

Any help is appreciated on this.
