### ISSUE TITLE
ECS policy is not working as expected

### ISSUE THREAD

**Issue by VishalGupta04** [cloud-custodian/cloud-custodian#6226]
Hello,

I have following ECS policy, which is not giving expected output:
```
  - name: PCE-MEDIUM-ecs-task-resource-limits-check
    resource: ecs-task-definition
    description: |
      ensure ECS Task definition includes hard resource limits
    mode:
      type: config-poll-rule
      role: XXXX
      schedule: TwentyFour_Hours
      tags:
        application_id: XXXX
    filters:
        - type: value
          key: "containerDefinitions[].memory"
          value: present
```

When I run the above policy, it gives me task definitions with memory in it too.

Here is sample task definition which is visible after this filter:
```
[
  {
    "taskDefinitionArn": "XXXX",
    "containerDefinitions": [
      {
        "name": "XXXX",
        "image": "XXXX",
        "repositoryCredentials": {
          "credentialsParameter": "XXXX"
        },
        "cpu": 0,
        "portMappings": [],
        "essential": true,
        "environment": [],
        "mountPoints": [],
        "volumesFrom": [],
        "logConfiguration": {
          "logDriver": "awslogs",
          "options": {
            "awslogs-group": "/ecs/XXXX",
            "awslogs-region": "us-east-1",
            "awslogs-stream-prefix": "ecs"
          }
        }
      }
    ],
    "family": "XXXX",
    "taskRoleArn": "XXXX",
    "executionRoleArn": "XXXX",
    "networkMode": "awsvpc",
    "revision": 2,
    "volumes": [],
    "status": "ACTIVE",
    "requiresAttributes": [
      {
        "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
      },
      {
        "name": "ecs.capability.execution-role-awslogs"
      },
      {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
      },
      {
        "name": "ecs.capability.private-registry-authentication.secretsmanager"
      },
      {
        "name": "com.amazonaws.ecs.capability.task-iam-role"
      },
      {
        "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
      },
      {
        "name": "ecs.capability.task-eni"
      }
    ],
    "placementConstraints": [],
    "compatibilities": [
      "EC2",
      "FARGATE"
    ],
    "requiresCompatibilities": [
      "FARGATE"
    ],
    "cpu": "512",
    "memory": "1024",
    "Tags": []
  }
]
```

**Comment by jtroberts83** [comment]
@VishalGupta04  What version of Custodian are you running?  I believe several config rule enhancements were made in the latest version released last week which *might fix your issue

**Comment by VishalGupta04** [comment]
I am using version 0.9.6, please confirm if this is a known bug in the version I am using.

**Comment by jtroberts83** [comment]
@VishalGupta04  Looking closer at your output it is correct per your filter.  Your filter is checking within the containerDefinitions list for any memory fields and if there are none present then it matches.  You might need to pretty format the json output to see this clearly but cpu and memory are listed for the task definition at the root level of the returned object.  So per your policy the output is correct and is working as it should.

**Comment by VishalGupta04** [comment]
@jtroberts83 I have corrected the format of policy and output. The output is not correct because policy filter key is "containerDefinitions[].memory" and value is "present" and it's showing me output which does not have memory present.

**Comment by VishalGupta04** [comment]
@jtroberts83 any update on this?

**Comment by jtroberts83** [comment]
@VishalGupta04   can you try this and see if it works:
```
- name: PCE-MEDIUM-ecs-task-resource-limits-check
    resource: ecs-task-definition
    description: |
      ensure ECS Task definition includes hard resource limits
    mode:
      type: config-poll-rule
      role: XXXX
      schedule: TwentyFour_Hours
      tags:
        application_id: XXXX
    filters:
     - or:
        - type: value
          key: "containerDefinitions[0].memory"
          value: present
        - type: value
          key: "containerDefinitions[1].memory"
          value: present
        - type: value
          key: "containerDefinitions[2].memory"
          value: present
        - type: value
          key: "containerDefinitions[3].memory"
          value: present
        - type: value
          key: "containerDefinitions[4].memory"
          value: present
```

**Comment by VishalGupta04** [comment]
Hi @jtroberts83,

Thanks for your response.

I tried:
```
- type: value
          key: "containerDefinitions[1].memory"
          value: present
```
and it worked. 
My concern is, as this is an array how do we mention this filter generically (without hardcoding 0, 1, 2)?

**Comment by jtroberts83** [comment]
@VishalGupta04 Being that the returned data for containerDefinitions is a list you will want to try and use the op: in and possibly the value_type: swap.  You can see some examples here in the docs - https://cloudcustodian.io/docs/filters.html

**Comment by VishalGupta04** [comment]
I want to ensure that each ECS task container definition should have hard limits set for CPU/Memory. If I use op: in that will not guarantee that all task container definitions have hard limits set.

**Comment by jtroberts83** [comment]
Oh I see, let me think about that some and see if I can come up with something.  Thinking a negative regex for the value but will see if I can get an example put together for you later.  I need to go and cook dinner for my family right now but will be back on later

**Comment by VishalGupta04** [comment]
This is what I have so far but this will not work if I have more than one container definitions for a task:
```
policies:
  #Ensure task definition includes hard resource limits per user (ulimit) and container (prlimit) to prevent unlimited resource consumption
  - name: PCE-MEDIUM-ecs-task-resource-limits-check
    resource: ecs-task-definition
    description: |
      ensure ECS Task definition includes hard resource limits
    mode:
      type: config-poll-rule
      role: XXXX
      schedule: TwentyFour_Hours
      tags:
        application_id: XXXX
    filters:
      - or:
        - type: value
          key: "containerDefinitions[0].cpu"
          value: present
        - type: value
          key: "containerDefinitions[0].memory"
          value: absent
        - type: value
          key: cpu
          value: absent
        - type: value
          key: memory
          value: absent
```

**Comment by jtroberts83** [comment]
@VishalGupta04   I don't have any ECS resources to test against but can you try something like this and let me know if it works for you:

```
  filters:
      - or:
        - type: value
          key: containerDefinitions[*].cpu
          value: absent
          op: in
          value_type: swap
        - type: value
          key: containerDefinitions[*].memory
          value: absent
          op: in
          value_type: swap
```

**Comment by VishalGupta04** [comment]
I put following and got no output:
```
filters:
      - or:
        - type: value
          key: "containerDefinitions[*].cpu"
          value: absent
          op: in
          value_type: swap
        - type: value
          key: "containerDefinitions[*].memory"
          value: absent
          op: in
          value_type: swap
        - type: value
          key: cpu
          value: absent
        - type: value
          key: memory
          value: absent
```
This filter is definition isn't giving correct output.

**Comment by jtroberts83** [comment]
@VishalGupta04 One last test, take the asterisks out and try it again like this:
```

filters:
      - or:
        - type: value
          key: "containerDefinitions[].cpu"
          value: absent
          op: in
          value_type: swap
        - type: value
          key: "containerDefinitions[].memory"
          value: absent
          op: in
          value_type: swap
        - type: value
          key: cpu
          value: absent
        - type: value
          key: memory
          value: absent
```
