### ISSUE TITLE
Add 'mark-for-op' and 'marked-for-op' to IAM role

### ISSUE THREAD

**Issue by fussybeaver** [cloud-custodian/cloud-custodian#6229]
We would like to mark / tag IAM roles for removal after a threshold period, using a policy similar to:

```yaml
- name: iam-role-unused-mark
  resource: aws.iam-role
  filters:
    - "tag:maid_status": absent
    - type: used
      state: false
    - type: usage
      match-operator: all
      LastAuthenticated: null
  actions:
    - type: mark-for-op
      tag: maid_status
      op: delete
```

This is possible by registering the respective actions to the IAM role action and filter registries: https://github.com/FundingCircle/cloud-custodian/blob/27b32aa44b75077deb54e1857e39dffbdf26904e/c7n/resources/iam.py#L291-L292
