### ISSUE TITLE
Security hub does not resolve the resource types for rds, rds-cluster, dynamodb and redshift and publish Resource type = Others

### ISSUE THREAD

**Issue by amitsehgal** [cloud-custodian/cloud-custodian#6237]
**Describe the bug**
I have post finding to security hub for rds-cluster, dynamodb, redshift and hub UI shows resource type as others
**To Reproduce**

Add postfinding action into a resource type listed above and observe resource_type in security hub UI

**Expected behavior**
It should publish the correct resource types

**Background (please complete the following information):**
 - OS: Linus
 - Python Version: [3.8.1]
 - Custodian Version: [0.9.7]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
vars:
    post-finding-failed: &post-finding-failed  
    type: post-finding
    description: |
        mandatory tags are required on S3.
    title: "custodian-s3-mandatory-tags-missing"
    severity_normalized: 70
    types:
      - "Software and Configuration Checks/AWS Security Best Practices"
    recommendation: "recommendation"
    recommendation_url: "URL"
    compliance_status: FAILED
    severity_label: HIGH
policies: 
  - name: rds-cluster-mandatory-tag-check-test
    resource: rds-cluster
    description: |
       The policy checks the rds-cluster required tags
    mode:
      schedule: "rate(15 minutes)"
      type: periodic
      role: arn:aws:iam::{account_id}:role/rolename
    filters:
      - Status: available
      - or: *filters-absent
      - "tag:maid_status": absent
    actions:
      - <<: *post-finding-failed
        title: "rds-cluster-mandatory-tags-missing"
        description: "tags are required on rds-cluster"
 
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
