### ISSUE TITLE
aws - step functions resources need tags pulled

### ISSUE THREAD

**Issue by SwatiKulkarni709** [cloud-custodian/cloud-custodian#6241]
**Describe the bug**
AWS Custodian Policy for StepFunction does not work with config-poll-rule. There is no error message in the Logs, but the policy does not give expected result.
When tested in our AWS account, Config rule must return 19 Non-Compliant and 1 as Compliant. But it says all 20 as Non-Compliant.
Attached the log file and a sample cloudformation template.

**To Reproduce**
Deploy the policy in your account and check your config rule for stepfunction:

**Expected behavior**
On successful execution of the policy, the config rule should flag the StepFunction with missing required tags as Non-compliant resource.

**Background (please complete the following information):**
 - Python Version:  python 3.8.5
 - Custodian Version: 0.9.7
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]

---
```
policies:
  - name: d-stepfunction-required-tags
    resource: aws.step-machine
    description: "Type: Config Rule. Compliance: Tag Validation."
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
    filters:
      - and:
          - or:
              - tag:CostCenter: absent
              - tag:RSMs: absent
              - tag:ApplicationIDName: absent
          - tag:__Exception-StepFunctionTags: absent
```
---
**Additional context**
[step_function_logs.txt](https://github.com/cloud-custodian/cloud-custodian/files/5495769/step_function_logs.txt)
[step_test.txt](https://github.com/cloud-custodian/cloud-custodian/files/5495823/step_test.txt)

**Comment by kapilt** [comment]
out of curiosity, could you clarify what value using  `config-poll` mode provides, its seems quite limited in functionality or utility, also your `and` clause is superflous

**Comment by SwatiKulkarni709** [comment]
Hi @kapilt Thanks for getting back. AWS config rule does not support the StepFunction resource. Hence I used the config-poll-rule to create a custom config rule.
The config rule gets created but tags all the resources as Compliant.

But when I test the same policy on the command line using the custodian run -s out test.yaml it seems to give the correct number of non-compliant resources.

about the ```and yeah, I can remove that. 

please let me know if you need any further details.

**Comment by SwatiKulkarni709** [comment]
Hi @kapilt, do you have an update on the above bug? Thanks.

**Comment by gulati-diksha** [comment]
> Hi @kapilt Thanks for getting back. AWS config rule does not support the StepFunction resource. Hence I used the config-poll-rule to create a custom config rule.
> The config rule gets created but tags all the resources as Compliant.
> 
> But when I test the same policy on the command line using the custodian run -s out test.yaml it seems to give the correct number of non-compliant resources.
> 
> about the and yeah, I can remove that.
> 
> please let me know if you need any further details.

Note: There is a correction- All resources are marked as 'non-compliant' resources when the config rule gets created.

**Comment by gulati-diksha** [comment]
Here are the logs and policy for only 1 filter.

policy:

```
---
 
policies:
  - name: d-stepfunction-required-tags
    resource: aws.step-machine
    description: "Type: Config Rule. Compliance: Tag Validation."
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
    filters:
      - tag:ApplicationIDName: absent
 
```

Logs: 
[StepFunctionwith1FilterPolicyLogs.docx](https://github.com/cloud-custodian/cloud-custodian/files/5513435/StepFunctionwith1FilterPolicyLogs.docx)
