### ISSUE TITLE
Enable variables for use in the accounts.yml config file for c7n-org

### ISSUE THREAD

**Issue by seemonicago** [cloud-custodian/cloud-custodian#6244]
**Is your feature request related to a problem? Please describe.**
I'd like a way to be able to specify variables in the accounts.yml file when leveraging c7n-org. This would allow for easier manipulation of the accounts.yml file and more reusability.

**Describe the solution you'd like**
I'd like to be able to declare a variable at the top of the accounts.yml file, then reference it in the definition of the paramters. For example: set a `environment_type=dev` then include a reference to that variable in the vars section of all related accounts that require it. 

**Describe alternatives you've considered**
Generating a bash script to manipulate the accounts.yml file.

**Additional context**
These variables could be used on the vars section of an account, or in other fields like the role. For example, there could be a set of roles that has a prefix that varies based on environment or another factor. Allowing some variables at the account definition layer would enable quicker changes and better management than manipulating large sets of policies.

**Comment by anovis** [comment]
would something like #5957 be helpful or are you looking at just being able to reference and inject variables within the same yml file

**Comment by kapilt** [comment]
seems more related to the builtin capabiltiies of the accounts.yml file which already supports definining per account variables that are usable in policies.

**Comment by seemonicago** [comment]
I view the finished product like this:
```
## cat accounts.yml
top-level-vars:
  role_name:CustodianExecutionChild
  sender: foobar@foobar.com
  receiver-dev:
  receiver-ops
  receiver-blue: 

accounts:
- account_id: '#############'
  name: foo-bar-dev
  regions:
  - us-east-1
  role: arn:aws:iam::${account_id}:role/${role_name}
  vars:
    sender_address: ${sender_address}
    receiver_address: ${receiver_dev}
- account_id: '#############'
  name: fizz-buzz-ops
  regions:
  - us-east-1
  role: arn:aws:iam::${account_id}:role/${role_name}
  vars:
    sender_address: ${sender_address}
    receiver_address: ${receiver_ops}
- account_id: '#############'
  name: foo-blue-a
  regions:
  - us-east-1
  role: arn:aws:iam::${account_id}:role/${role_name}
  vars:
    sender_address: ${sender_address}
    receiver_address: ${receiver_blue}
- account_id: '#############'
  name: foo-blue-b
  regions:
  - us-east-1
  role: arn:aws:iam::${account_id}:role/${role_name}
  vars:
    sender_address: ${sender_address}
    receiver_address: ${receiver_blue}
```
