### ISSUE TITLE
S3 filters with 'or' with custodian.filters:ERROR Message: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by jmwaks** [cloud-custodian/cloud-custodian#6259]
**Describe the bug**
Running the policy below to check for bucket encryption with or fails with the following errors.
```
2020-10-30 10:54:20,317: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: {bucket_name}
```

**To Reproduce**
Run ``` run --dryrun -s out s3_test.yml```

**Expected behavior**
Policy should filter buckets appropriately and filter unencrypted s3 buckets

**Background:**
 - OS: [e.g. OSX 10.15.7]
 - Python Version: [python 3.8.2]
 - Custodian Version: [0.9.7]
 - Cloud Provider: aws
 - Policy: 
```yaml
policies:
  - name: s3-test
    resource: s3
    filters:
      - or:
        - type: bucket-encryption
          state: False
        - type: bucket-encryption
          state: True
          crypto: aws:kms
          key: alias/aws/s3
        - type: bucket-encryption
          state: True
          crypto: AES256
```
 - Traceback: 
```
2020-10-30 10:54:20,887: custodian.filters:ERROR Message: 'list' object has no attribute 'get' Bucket: {bucket_name}
```
 - `custodian version --debug`
```
Custodian:   0.9.7
Python:      3.8.2 (default, Aug 25 2020, 09:23:57) 
             [Clang 12.0.0 (clang-1200.0.32.2)]
Platform:    posix.uname_result(sysname='Darwin', nodename='FVFYH1FGJK7M', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.31
botocore==1.17.31
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.0
setuptools==41.2.0
six==1.14.0
tabulate==0.8.7
urllib3==1.24.3
zipp==3.1.0

```

**Additional context**
Tested this policy in 0.8.33.0 and it worked as expected
This issue is related to #6083 found on 0.9.5
