### ISSUE TITLE
RDS tagging compliance 

### ISSUE THREAD

**Issue by mashhour-carpedata** [cloud-custodian/cloud-custodian#6274]
I am writing a policy to check that the required tags have been applied to RDS instances and clusters. I have noticed that the policy is not able to find the missing tags on RDS that have a role = serverless. 

do you know if there is a way to make the policy scan the RDS serverless?

here is my policy:

```
 policies:
  - name: rds-tag-compliance
    resource: rds
    comment: |
      Report on the total count of noncompliant s3 bucket
    filters:
      - type: value
        key: Engine
        value: aurora
        op: eq
      - or:
          - "tag:Name": absent
          - "tag:project": absent
          - "tag:env_type": absent
          - "tag:environment": absent
    actions:
      - type: notify
        priority_header: 1
        violation_desc: "missing the billing tags"
        to:
          - https://hooks.slack.com/services/xxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxxxxxxxxxxx
        transport:
          type: sqs
          queue: https://sqs.us-west-2.amazonaws.com/xxxxxxxxxxx/xxxxxxxxxx
```
