### ISSUE TITLE
Allow custom periods to be used with CPU utilization filters

### ISSUE THREAD

**Issue by esaari1** [cloud-custodian/cloud-custodian#6301]
I want to be able to write a policy for EC2 or RDS instances that filters on max CPU utilization that will return max values for every day over a 2 week period. At the moment I cannot do this since the filter function always looks at the first data point returned by the get_metric_statistics() call. Thus I cannot use the period value in my metric filter since the max value will not always be the first item returned by AWS.

I wrote a new function to test out looping over all the data points to return min, max, or average depending on the filter type.

```
def metricsValue(self, metrics):
    if len(metrics) == 0:
        return 0
    if self.statistics == 'Maximum':
        return max(metrics, key=lambda x: x[self.statistics])[self.statistics]
    elif self.statistics == 'Minimum':
        return min(metrics, key=lambda x: x[self.statistics])[self.statistics]
    elif self.statistics == 'Average':
        total = reduce(lambda a, b: a[self.statistics] + b[self.statistics], metrics)[self.statistics]
        return total / len(metrics)

    # default case
    return metrics[0][self.statistics]
```

I call this from process_resource_set(). I replaced the line 

`elif self.op(collected_metrics[key][0][self.statistics], self.value):`

with this

`elif self.op(self.metricsValue(collected_metrics[key]), self.value):`

With this change I could have a policy like this:

```
---
policies:
  - name: rds-instances-max-cpu-utilization-between-30-and-40
    resource: aws.rds
    filters:
      - DBInstanceStatus: available
      - type: value
        value_type: age
        key: InstanceCreateTime
        value: 14
        op: gte
      - type: metrics
        name: CPUUtilization
        statistics: Maximum
        value: 40
        op: lte
        days: 14
        missing-value: 0
        period: 86400
      - type: metrics
        name: CPUUtilization
        statistics: Maximum
        value: 30
        op: gt
        days: 14
        missing-value: 0
```

This will return all data points for all RDS instances where the max value was between 30% and 40% at any point during the last 2 weeks. I will get a data point for each day, even the ones that are outside the range which meets my needs.I can do the same with average and minimum data points.
