### ISSUE TITLE
How to consolidate metrics and logs in a single account - with c7n_org ?

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#6309]
I'm using `c7n_org` to deploy custodian policies as Lambdas in multiple accounts.
(`c7n_org` is executed from a specific role `role_A` in account `account_A` ; and deploys the policies in ~20 accounts. Each policy has a `role:` defined in it `mode:` block, and this role references the `{account_id}` variable set by `c7n_org`)

I'd like to consolidate metrics and logs in a single "master" account.

The [documentation](https://cloudcustodian.io/docs/aws/usage.html#metrics) hints to such a use case, using the syntax `log_group: aws://master/....` and `metrics: aws://master/...` in `mode.execution-options` ; however it does not seems to be exactly what I thought it would be:
* There is no way to define who this master account is
* From trial and errors it seems that the logs (for example) are created in the current execution account of the Lambda (i.e. as if the Lambda uses the `{account_id}` variable set in `execution-options` by `c7n_org`)
* I tried to play with a [few parameters](https://cloudcustodian.io/docs/aws/lambda.html?#execution-options) of `execution-options` with no success
* It seems that I do not understand the difference introduced by this `master` syntax

For the moment being I'm not able to consolidate metrics and logs as expected.

Example policy (NB: NOT WORKING):
```yaml
policies:
- name: c7n-test-consolidation
  resource: ec2
  mode:
    type: periodic
    schedule: "cron(* * ? * MON-FRI *)"
    role: arn:aws:iam::{account_id}:role/MyLambdaRole
    execution-options:
      metrics_enabled: true
      log_group: aws://master/MyLogGroupName?&region=eu-west-1
      metrics: aws://master/?namespace=MyNameSpace&region=eu-west-1
  filters:
    ...
```

Is there a way to consolidate logs and metrics when using `c7n_org` and Lambda mode ?

Thanks in advance.
