### ISSUE TITLE
Policy To Tag AWS S3 Buckets With Their Own Names

### ISSUE THREAD

**Issue by johnsmith-coder** [cloud-custodian/cloud-custodian#6313]
I like to view the cost of a lot services in AWS Cost Explorer by grouping by the Name tag. The Name tag is the default way to see lots of services by name in the AWS Console and therefore I have specified the Name tag as a Cost Allocation Tag in the AWS Billing page. If I manually add a Name tag to all my S3 buckets and give the tag value the name of the S3 bucket then I can see the cost for each S3 bucket which is very useful. I recently moved company and they have a lot of S3 buckets and I would like some way to automate the tagging of all these S3 buckets with their own names.

I would like to use a Cloud Custodian policy like this:
```
policies:
# Tag S3 buckets with their own names
- name: s3-bucket-tagger
  resource: s3
  description: Tag S3 buckets with their own name, eg Name=my-s3-bucket
  filters:
    - "tag:Name": absent
  actions:
    - type: tag
      key: "Name"
      value: "{source_bucket_name}"
```
The policy almost works as it, but it appears that CC doesn't currently support passing in the S3 bucket's own name eg with the "{source_bucket_name}" identifier into the tag value. If I set the value to 'Fred' then the policy will work but then all the S3 buckets will have a Name tag with value 'Fred' which is no good.
