### ISSUE TITLE
S3 : bucket-encryption with crypto set to 'aws:kms' fails when key is set to the AWS managed key (alias/aws/s3)

### ISSUE THREAD

**Issue by jmwaks** [cloud-custodian/cloud-custodian#6321]
**Describe the bug**
Bucket-encryption with crypto set to 'aws:kms' fails when key is set to the AWS managed key (alias/aws/s3)

**To Reproduce**
1. Create an S3 bucket and enable server-side encryption and set it to AWS managed key (aws/s3) 
2. Deploy the policy below

```yaml
policies:
  - name: s3-test
    resource: s3
    filters:
      - type: bucket-encryption
         state: True
         crypto: aws:kms
         key: alias/aws/s3
```

**Expected behavior**
1. The S3 bucket should be filtered

**Background (please complete the following information):**
 **Background:**
 - OS: [e.g. OSX 10.15.7]
 - Python Version: [python 3.8.2]
 - Custodian Version: [0.9.5]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: s3-test
    resource: s3
    filters:
      - type: bucket-encryption
         state: True
         crypto: aws:kms
         key: alias/aws/s3
```
 - `custodian version --debug` output

```
Custodian:   0.9.7
Python:      3.8.2 (default, Aug 25 2020, 09:23:57) 
             [Clang 12.0.0 (clang-1200.0.32.2)]
Platform:    posix.uname_result(sysname='Darwin', nodename='FVFYH1FGJK7M', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.0
attrs==19.3.0
boto3==1.14.31
botocore==1.17.31
docutils==0.15.2
importlib-metadata==1.7.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.0
setuptools==41.2.0
six==1.14.0
tabulate==0.8.7
urllib3==1.24.3
zipp==3.1.0

```

**Additional context**

This is issue is happening because get bucket-encryption call returns KMSMasterKeyID containing the alias when the aws managed key is used 
```
aws s3api get-bucket-encryption --bucket test-bucket-XXXXX
{
    "ServerSideEncryptionConfiguration": {
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "aws:kms",
                    "KMSMasterKeyID": "arn:aws:kms:us-west-2:XXXXXXXXXXXX:alias/aws/s3"
                }
            }
        ]
    }
}
```
