### ISSUE TITLE
c7n report for resource 'log-group' missing tags in 0.9.8

### ISSUE THREAD

**Issue by ilya-bogdanov** [cloud-custodian/cloud-custodian#6331]
policy:
```
policies:
  - name: report-resources
    resource: log-group
    comment: |
      Reports on log-group for account
    filters:
    - not:
      - "tag:custodian:skip": "True"
```
reports with c7n==0.9.2
```
  {
    "logGroupName": "some_name",
    "creationTime": 1585573052081,
    "retentionInDays": 90,
    "metricFilterCount": 0,
    "arn": "some_arn",
    "storedBytes": 0,
    "Tags": []  # here comes list of tags for the log-group
  },
```
from c7n==0.9.8 json element, holding list of tags for the log group is missing for each element in report file
