### ISSUE TITLE
AWS - aws.rest-api and aws.distribution filters are not being interpreted

### ISSUE THREAD

**Issue by karankos** [cloud-custodian/cloud-custodian#6346]
Filtering is not working for aws.distribution and aws.rest-api resources when trying to apply filters for TLS version.

For `aws.distribution` the distribution-config type of filter has been used
For `aws.rest-api` the general value and event types of filter have been used as the filter docs for that resource does not have explicit filters.

```yaml
resource: aws.distribution
     filters:
      - type: distribution-config
        key: viewerCertificate.minimumProtocolVersion
        op: not-equal
        value: TLSv1.2
      - type: distribution-config
        key: OriginSslProtocols
        op: not-equal
        value: TLSv1.2
```

```yaml
resource: aws.rest-api
    filters: 
      - type: event
        key: securityPolicy
        op: ne
        value: TLS_1_2
      - type: value
        key: detail.responseElements.securityPolicy
        value: TLS_1_0
```

Any combination tried, the output result remains the same:

```
[INFO]	2020-12-09T12:41:17.743Z	fcd9f7b6-d0bb-4bad-966e-87c4308d145a	Resources []
```

Which should at least return an indication that the filter is going to be applied and then return the number of matches against the filters.

**Comment by kapilt** [comment]
you've only posted a partial policy and the issue here has nothing todo with the filters, it looks like you have incorrect ids expressions in your event mode.

**Comment by karankos** [comment]
Hi @kapilt thanks for you response.

The event mode triggers upon an existing event. 
Well in my case, I am testing the CreateDistribution for cloudfront.

I can see that event works fine as I get the corresponding log 'Found resource ids: [<list of resources>]
After that log I should be getting something like "Filtering resources using X filters" and so on...
Well this does not happen at all here and I have tested numerous different event ids. 

I even tested the example from the documentation (link in op) and nothing changed.
It would be nice if someone could reproduce:

```yaml
events:
      - source: cloudfront.amazonaws.com
        event: CreateDistribution
        delay: 5
        ids: requestParameters.distributionConfig.logging
```

```yaml
policies:
  - name: logging-enabled
    resource: aws.distribution
    filters:
      - type: distribution-config
        key: Logging.Enabled
        value: False
```
