### ISSUE TITLE
Add remove-statements action to rds-snapshot and rds-cluster-snapshot resources

### ISSUE THREAD

**Issue by matt-hutchins** [cloud-custodian/cloud-custodian#6350]
**Is your feature request related to a problem? Please describe.**
Without the ability to remove cross-account permissions a developer trying to apply mass update snapshot permissions could lead to inadvertent deletion of snapshots leading  to data loss, and also to data retention compliance issues.

**Describe the solution you'd like**
As a Cloud Custodian user I would like to have the ability to remove invalid cross-account permissions from RDS DB snapshots and RDS DB Cluster snapshots. This would allow remediation of permissions issues without having to delete the snapshots.

**Describe alternatives you've considered**
The alternative would be deleting snapshots with cross-account permissions or notifying developers that their snapshots are non-compliant.

**Additional context**
Would like to model after remove-statements as they work for SNS:
:example:
```
.. code-block:: yaml

       policies:
          - name: remove-sns-cross-account
            resource: sns
            filters:
              - type: cross-account
            actions:
              - type: remove-statements
                statement_ids: matched
```
