### ISSUE TITLE
Custodian policies that call GenerateCredentialReport api hit throttling limits intermittently.

### ISSUE THREAD

**Issue by wallabyies** [cloud-custodian/cloud-custodian#6351]
**Describe the bug**
Custodian policies that check iam-user or account resources regularly error with:

 **"An error occurred (Throttling) when calling the GenerateCredentialReport operation"**

**To Reproduce**
Create Custodian policy to check iam-user or account resources.     The problem occurs in multiple accounts on a regular basis, although not 100% of the time.    

Here are some examples that reproduce the error:

```yaml
  - name: cis-iam-user-needs-mfa
    resource: iam-user
    comment: "CIS Amazon Web Services Foundations v1.1.0 (1.2)"
    region: us-east-1
    filters:
      - type: credential
        key: password_enabled
        value: true
      - type: credential
        key: mfa_active
        value: false
```

And another:
```yaml
  - name: cis-root-must-use-mfa
    resource: account
    comment: "CIS Amazon Web Services Foundations v1.1.0 (1.13)"
    region: us-east-1
    filters:
      - type: credential
        key: mfa_active
        value: false
```

**Expected behavior**
I would expect not to receive throttling errors when Custodian calls the GenerateCredentialReport api.   

Per AWS Support:

_Unfortunately, there is no documented API call limit for IAM, and  at this time, there is no way to request a modification of that limit. This IAM API rate limit is dynamic and the dynamic nature of this limit is only to ensure protection against denial-of-service attacks that target AWS infrastructure.  So, we are a little restricted to API limitations request or information that can be provided. At the same time, API throttling can be changed without any notifications, therefore we can't provide a certain number on our documents or change the limits._ 

_Our recommendation in such scenarios is to implement exponential backoff strategy. Using such a strategy ensures that your application doesn't retry API requests at a high rate. You can do this by using care when polling and by using exponential back off retries as per ref [1] and [2]. This will help you to make your script more robust. If you are making API calls via the AWS SDK, automatic retry logic is already implemented._

**Background (please complete the following information):**
 - OS: Deployed as type periodic into AWS.
 - Python Version: 3.8
 - Custodian Version: 0.9.7.0
 - Tool Version: [if applicable]
 - Cloud Provider: AWS
 - Policy: Included above

 - Traceback: 

```
error during policy executionTraceback (most recent call last):  
File \"/var/task/c7n/handler.py\", line 166, in dispatch_event    p.push(event, context)  
File \"/var/task/c7n/policy.py\", line 1138, in push    return mode.run(event, lambda_ctx)  
File \"/var/task/c7n/policy.py\", line 526, in run    return PullMode.run(self)  
File \"/var/task/c7n/policy.py\", line 285, in run    resources = self.policy.resource_manager.resources() 
 File \"/var/task/c7n/resources/account.py\", line 76, in resources    return self.filter_resources([get_account(self.session_factory, self.config)])  File \"/var/task/c7n/manager.py\", line 112, in filter_resources    resources = f.process(resources, event) 
 File \"/var/task/c7n/resources/account.py\", line 87, in process    report = self.get_credential_report()
  File \"/var/task/c7n/resources/iam.py\", line 1444, in get_credential_report    data = self.fetch_credential_report()  
File \"/var/task/c7n/resources/iam.py\", line 1497, in fetch_credential_report    client.generate_credential_report() 
 File \"/var/runtime/botocore/client.py\", line 357, in _api_call    return self._make_api_call(operation_name, kwargs)  
File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call    raise error_class(parsed_response, operation_name)botocore.exceptions.ClientError: An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded
```

**Additional context**
