### ISSUE TITLE
AWS RDS - Ignores Filter by Tag Absent

### ISSUE THREAD

**Issue by elliott-weston-cko** [cloud-custodian/cloud-custodian#6358]
**Describe the bug**
Using version 0.9.9 of cloud-custodian, rds instances appear to filters for tags that are marked as absent.

**To Reproduce**
Deploy a policy for rds that checks for the absence of a tag.

**Expected behavior**
The policy correctly filters resources that do not have the defined tag

**Background (please complete the following information):**
 - OS: OSX 10.15.7
 - Python Version: python 3.8 (AWS Lambda Runtime)
 - Custodian Version: 0.9.9
 - Tool Version: N/A - But I am using the policygenerator.py script to manage policies via CloudFormation
 - Cloud Provider: aws
 - Policy:
```yaml
vars:
  required-tags: &required-tags-filter
    - "tag:Team": absent
    - "tag:Environment": absent

  c7n-role: &c7n-role
    role: "arn:aws:iam::{account_id}:role/my-role"

policies:
- name: rds-tag-compliance-periodic
  resource: rds
  mode:
    <<: *c7n-role
    type: periodic
    schedule: rate(15 minutes)
  filters:
    - "tag:c7n-tag-compliance": absent
    - or: *required-tags-filter
  actions:
    - type: mark-for-op
      tag: c7n-tag-compliance
      op: delete
      days: 7
```
 - Traceback:
Initial Run (when c7n-tag-compliance hasn't been set):
```

[DEBUG]	2020-12-16T10:29:40.45Z	b1cc4bf9-4979-4391-9bc3-0d3b6afb40c9	Running policy:rds-tag-compliance-periodic resource:rds region:eu-west-1 c7n:0.9.9
[DEBUG]	2020-12-16T10:29:40.367Z	b1cc4bf9-4979-4391-9bc3-0d3b6afb40c9	Filtered from 5 to 5 rds
[INFO]	2020-12-16T10:29:40.385Z	b1cc4bf9-4979-4391-9bc3-0d3b6afb40c9	policy:rds-tag-compliance-periodic resource:rds region:eu-west-1 count:5 time:0.32
[INFO]	2020-12-16T10:29:41.12Z	b1cc4bf9-4979-4391-9bc3-0d3b6afb40c9	Tagging 5 resources for delete on 2020/12/23
[INFO]	2020-12-16T10:29:41.133Z	b1cc4bf9-4979-4391-9bc3-0d3b6afb40c9	policy:rds-tag-compliance-periodic action:universaltagdelayedaction resources:5 execution_time:0.12
```

Subsequent Run (where instances now have tag c7n-tag-compliance):
```
[DEBUG]	2020-12-16T10:45:31.105Z	6b36086f-a084-4f9c-b7b0-6ac4515c667c	Running policy:rds-tag-compliance-periodic resource:rds region:eu-west-1 c7n:0.9.9
[DEBUG]	2020-12-16T10:45:31.294Z	6b36086f-a084-4f9c-b7b0-6ac4515c667c	Filtered from 5 to 5 rds
[INFO]	2020-12-16T10:45:31.303Z	6b36086f-a084-4f9c-b7b0-6ac4515c667c	policy:rds-tag-compliance-periodic resource:rds region:eu-west-1 count:5 time:0.20
[INFO]	2020-12-16T10:45:31.794Z	6b36086f-a084-4f9c-b7b0-6ac4515c667c	Tagging 5 resources for delete on 2020/12/23
[INFO]	2020-12-16T10:45:31.907Z	6b36086f-a084-4f9c-b7b0-6ac4515c667c	policy:rds-tag-compliance-periodic action:universaltagdelayedaction resources:5 execution_time:0.11
```
 
**Additional context**
I have also attempted to use the following policy:
```yaml
- name: rds-tag-compliance-periodic
  resource: rds
  mode:
    <<: *c7n-role
    type: periodic
    schedule: rate(15 minutes)
  filters:
    - not:
      - type: marked-for-op
        tag: c7n-tag-compliance
        op: delete
    - or: *required-tags-filter
  actions:
    - type: mark-for-op
      tag: c7n-tag-compliance
      op: delete
      days: 7
```
Which also will trigger a re-apply of the action.

I have also tested this behaviour against another type of resource (SQS queue), using an identical policy to the rds ones, but only with the resource name changed:
```yaml
vars:
  required-tags: &required-tags-filter
    - "tag:Team": absent
    - "tag:Environment": absent

  c7n-role: &c7n-role
    role: "arn:aws:iam::{account_id}:role/my-role"

policies:
- name: sqs-tag-compliance-periodic
  resource: sqs
  mode:
    <<: *c7n-role
    type: periodic
    schedule: rate(15 minutes)
  filters:
    - "tag:c7n-tag-compliance": absent
    - or: *required-tags-filter
  actions:
    - type: mark-for-op
      tag: c7n-tag-compliance
      op: delete
      days: 7
```
Which correctly filters resources after the resource has been tagged with the `c7n-tag-compliance` tag.

**Comment by elliott-weston-cko** [comment]
Further investigation:

Cloud-custodian behaves as expected when rolled back to version 0.9.8, which suggests that its related to the change to RDS tag processing introduced in 0.9.9 
https://github.com/cloud-custodian/cloud-custodian/pull/6332
```
[DEBUG] 2020-12-16T14:14:39.911Z 64e1ec31-4331-4195-b5d7-a29fc7ce09cd Running policy:rds-tag-compliance-periodic resource:rds region:eu-west-1 c7n:0.9.8
[DEBUG] 2020-12-16T14:14:40.382Z 64e1ec31-4331-4195-b5d7-a29fc7ce09cd Filtered from 5 to 0 rds
```

(Rollback was tested with the first policy I documented in the initial description):
```yaml
vars:
  required-tags: &required-tags-filter
    - "tag:Team": absent
    - "tag:Environment": absent

  c7n-role: &c7n-role
    role: "arn:aws:iam::{account_id}:role/my-role"

policies:
- name: rds-tag-compliance-periodic
  resource: rds
  mode:
    <<: *c7n-role
    type: periodic
    schedule: rate(15 minutes)
  filters:
    - "tag:c7n-tag-compliance": absent
    - or: *required-tags-filter
  actions:
    - type: mark-for-op
      tag: c7n-tag-compliance
      op: delete
      days: 7
```

**Comment by ajkerrigan** [comment]
Thanks for the detailed report - I'll look into this.

**Comment by kapilt** [comment]
it might we need an updated sdk for the tags in rds describes, though it passed functional tests so its a little strange. @elliott-weston-cko can you confirm which version of boto/botocore you had with 0.9.9 ? ie output of `pip freeze | grep boto`

**Comment by kapilt** [comment]
it might we need an updated sdk for the tags in rds describes, though it passed functional tests so its a little strange. @elliott-weston-cko can you confirm which version of boto/botocore you had with 0.9.9 ? pip

**Comment by kapilt** [comment]
if you add 

```
  mode:
    <<: *c7n-role
    type: periodic
    packages:
      - botocore
    schedule: rate(15 minutes)
```

it should resolve.
