### ISSUE TITLE
ECR lifecycle-rule filter

### ISSUE THREAD

**Issue by guptavishal4** [cloud-custodian/cloud-custodian#6378]
Hello,

I have following policy to identify ECR repositories with image(s) missing tags. I tried different combinations for value, operator and selection.tagStatus but not getting expected results. Please help me out with this: 

```
policies:
  - name: <policy_name>
    resource: ecr
    description: |
      <description>
    mode:
      type: config-poll-rule
      role: role_xxxx
      schedule: TwentyFour_Hours
    filters:
       - type: lifecycle-rule
         state: False
         match:
          - selection.tagStatus: untagged
          - action.type: expire
          - type: value
            key: selection.countNumber
            value: 0
            op: gt
```
