### ISSUE TITLE
Compare AWS bucket tags with bucket name returned 0 result

### ISSUE THREAD

**Issue by KVInventoR** [cloud-custodian/cloud-custodian#6391]
I have a simple policy and would like to get list of all s3 buckets where tags:Name is equal to bucket name
But this policy returned for me 0 results:

2021-01-11 17:41:52,536: custodian.policy:INFO policy:s3-tags-check resource:s3 region:us-west-2 count:0 time:88.95

`policies:
  - name: s3-tags-check
    resource: s3
    description: |
      Report on S3 buckets that do not meet tag compliance policies
    filters:
      - type: value
        key: tag:Name
        op: in
        value_type: swap
        value: Name`

**Comment by ajkerrigan** [comment]
From the gitter discussion around this request it seems like a useful enhancement :+1: . In the meantime though, you can perform this sort of check today though it's admittedly awkward:

```
policies:
  - name: s3-name-tag-check
    resource: s3
    filters:
      - type: value
        key: "Name == (Tags[?Key == 'Name'][].Value | @[0])"
        value: false
```
