### ISSUE TITLE
Is it possible to write a policy that will audit results of a query?

### ISSUE THREAD

**Issue by windowsrefund** [cloud-custodian/cloud-custodian#6400]
For example, I'd like to check tag compliance against all ec2 instances where a tag matches a value. Workflow would look something like:

1. Generate a list of all things that match a condition (e.g. Tag foo has a value of bar)
2. For each item in the previously generated list, test compliance

**Comment by kapilt** [comment]
what your describing is just using multiple filters in a policy, albeit its unclear what you mean by test-compliance, as an example

```yaml
name: check-stuff
resource: aws.ec2
filters: 
  -  "tag:foo": bar
  - ssm-compliance
```

**Comment by windowsrefund** [comment]
That would test all the things. I'd be more interested in gathering a subset of things to be tested. In psuedo code, it'd be something like `test foo where test bar`

That way, only the results of the final tests against foo would be available. Those tests would have been run on only endpoints that passed the bar test

**Comment by kapilt** [comment]
just have two separate policies if you want both results, if you execute in poll mode, the resource fetching will be cached between the two policies.

**Comment by windowsrefund** [comment]
Glad to know a path exists and hoping you'd provide an example or additional clarification? Not sure what "poll mode" is and see nothing in the help. My apologies if I'm overlooking something obvious.

**Comment by kapilt** [comment]
your saying you want to a full set of tag: foo == bar and a subset of that which has an additional filter.

```yaml
policies:
 - name: check-tag
   resource: aws.ec2
   filters: 
    -  "tag:foo": bar
 - name: check-compliance
   resource: aws.ec2
   filters: 
    -  "tag:foo": bar
    - ssm-compliance
```

you'll get outputs of both, this stuff is covered typically by trying out the tool, incidentally chat might be a better forum for these sorts of getting started questions in addition to the docs.
