### ISSUE TITLE
CloudFront policies working locally but not in AWS console

### ISSUE THREAD

**Issue by guptavishal4** [cloud-custodian/cloud-custodian#6422]
**Describe the bug**
CloudFront policies (filter type: value) are producing correct results in local dry run but when deployed to AWS, show all resources in either compliant or non-compliant bucket only.

**To Reproduce**
Use this sample policy and try deploying on AWS and see results:
```
policies:
  # Ensure the distribution setting PriceClass is set to 100
  - name: XXXX
    resource: aws.distribution
    description: 
      Ensure the distribution setting PriceClass is set to 100
    mode:
      type: config-rule
      role: XXXX
    filters:
      - type: value
        key: "PriceClass"
        value: "PriceClass_100"
        op: ne
```

**Expected behavior**
- Results on AWS Config console should match with local custodian dry run against the same environment
- All compliant resources should be put in compliant and non-compliant in Non-compliant category. But for CloudFront it shows all the resources (compliant and non-compliant) in one of the categories only.
