### ISSUE TITLE
IAM policies don't produce expected results

### ISSUE THREAD

**Issue by guptavishal4** [cloud-custodian/cloud-custodian#6423]
**Describe the bug**
Created policies to identify IAM users/roles that were not used in past 90 days. Here is what we have observed:
- IAM User and Role policies produce correct result in local custodian dry run
- In AWS, IAM User policy produces correct results but IAM Role policy does not

**To Reproduce**
- Create policies mentioned below
- Execute custodian dry run (custodian run --dryrun --profile <iam_role> -s output --cache-period 0 <policy_file.yaml>)
- Deploy these policies to AWS and see results
```
policies:
  - name: XXXX
    resource: iam-role
    description: |
      Noncompliant if IAM role is not used for more than 90 days 
    mode:
      type: config-rule
      role: XXXX
    filters:
      - or:
        - type: value
          key: RoleLastUsed.LastUsedDate
          op: gt
          value: 90
          value_type: age
        - and:
          - type: value
            key: RoleLastUsed.LastUsedDate
            value: absent
          - type: value
            key: CreateDate
            op: gt
            value: 90
            value_type: age
```
```
policies:
  - name: XXXX
    resource: iam-user
    description: |
      Noncompliant if IAM user is not used for more than 90 days 
    mode:
      type: config-rule
      role: XXXX
    filters:
      - or:
        - type: value
          key: UserLastUsed.LastUsedDate
          op: gt
          value: 90
          value_type: age
        - and:
          - type: value
            key: UserLastUsed.LastUsedDate
            value: absent
          - type: value
            key: CreateDate
            op: gt
            value: 90
            value_type: age
```

**Expected behavior**
- Results on AWS should match with local dry run

**Comment by guptavishal4** [comment]
Please let me know the additional details you need?

**Comment by rams3sh** [comment]
Roles do have the `RolesLastUsed`  as one of the keys , where the logic you have mentioned of using `RoleLastUsed.LastUsedDate` will work. 

However, you do not have a similar key for User called `UserLastUsed`.  Hence the user policy would not / should not work in either case (both in lambda mode and CLI mode). I am little surprised on how the user one works in local for you.

The base meta data of users and roles that Custodian provides is received / updated through `GetUser` and `GetRole`. You can check the data given by AWS in both of this calls this in these references:-

`GetUser` - https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetUser.html

`GetRole` - https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetRole.html

Note: Check the Response object to get an idea on what you can filter and get.


If you are looking for user last used , you may want to use a combination of Console last logged in , access keys last used and take the maximum of both and check the difference with current date to arrive at the net lastused date age. Below sample policy can help you :- 

```
policies:
  - name: iam_user_unused
    description: |
      Detect IAM Users used beyond 90 days.
    resource: iam-user
    filters:
      - type: credential
        key: user
        value: present
      - type: value
        # Use creation time is taken to compensate for cases where there was no usages. 
        key: "\"c7n:credential-report\".[ \"user_creation_time\", \"password_last_used\", \"access_keys\"[0].\"last_used_date\",  \"access_keys\"[1].\"last_used_date\"].max([])"
        value_type: age
        op: gte
        value: 90
```
