### ISSUE TITLE
Azure: network interface policy question

### ISSUE THREAD

**Issue by tomarv2** [cloud-custodian/cloud-custodian#6427]
Trying to setup a policy that will list all Network Interfaces with public IP and no NSG:

Network interface has public IP and NSG attached:

<img width="1109" alt="Screen Shot 2021-02-02 at 9 36 23 PM" src="https://user-images.githubusercontent.com/11890959/106703569-54b0a400-659f-11eb-8fa9-91b30e24ff31.png">

Network interface has public IP and no NSG attached:

<img width="1121" alt="Screen Shot 2021-02-02 at 9 35 53 PM" src="https://user-images.githubusercontent.com/11890959/106703615-727e0900-659f-11eb-852a-af9d10c905b3.png">

Looking for some pointers, I was thinking effective network route would work. Not sure what I should be looking at and nothing from resource.json output.

**Comment by kapilt** [comment]
@stefangordon @erwelch this got raised in gitter earlier today fwiw

**Comment by stefangordon** [comment]
Hey @tomarv2 you are probably looking for something like this:

```
policies:
    - name: public-ip-without-nsg
      resource: azure.networkinterface
      filters:
        - type: value
          key: properties.networkSecurityGroup.id
          value: null
        - type: value
          key: 'properties.ipConfigurations[].properties.publicIPAddress.id'
          value: not-null
```

Note that it is also possible to do this from a Virtual Machine enumeration using the custom `network-interface` value filter which does the child resource lookup for you.  Example at https://cloudcustodian.io/docs/azure/examples/virtualmachineswithpublicip-compute-networking.html
