### ISSUE TITLE
Proposal to add a command line option to output required permissions for the given policy to run

### ISSUE THREAD

**Issue by rams3sh** [cloud-custodian/cloud-custodian#6487]
**Is your feature request related to a problem? Please describe.**
Currently when we have to deploy a policy , we may have to look across the official custodian documentation to derive the least permission required for the policy to run. 
It would be better to have a cli option to pass the policy as input and the cli can provide the set of actions or even a sample mock AWS permission policy itself required for each custodian policy within a given yaml file.

It just reduces one additional step for looking into the documentation and gathering the required permissions.
**Describe the solution you'd like**
For an example below policy :- 
```yaml
policies:
  - name: role-unused
    resource: iam-role    # iam:GetRole, iam:ListRoles
    filters:
      - type: value
        key: "[RoleLastUsed.LastUsedDate, CreateDate].max([])"  
        value_type: age
        op: gte
        value: 90
   actions:
     - delete      # iam:DeleteRole
     

  - name: user-unused
    resource: iam-user    # iam:GetUser, iam:ListUsers
    filters:
      - type: credential  # iam:GenerateCredentialReport,  iam:GetCredentialReport
        key: user
        value: present
      - type: value
        # Use creation time is taken to compensate for cases where there was no usages. 
        key: "\"c7n:credential-report\".[ \"user_creation_time\", \"password_last_used\", \"access_keys\"[0].\"last_used_date\",  \"access_keys\"[1].\"last_used_date\"].max([])"
        value_type: age
        op: gte
        value: 90
   actions:
     - delete     # iam:DeleteUser
```

if we have an option `generate_policy` or something similar , it is expected to give the below output :-  
```bash
rams3sh@test:~/Garage$ custodian generate_policy iam_unused.yaml 

1. role-unused
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:ListRoles",
                "iam:GetRole",
                "iam:DeleteRole"
            ],
            "Resource": "*"
        }
    ]
}

2. user-unused
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:ListUsers",
                "iam:GetUser",
                "iam:GenerateCredentialReport",
                "iam:GetCredentialReport"
            ],
            "Resource": "*"
        }
    ]
}


```

**Describe alternatives you've considered**
Currently I refer to documentation for each filter / action / resource 's permission used in the policy and consolidate then to arrvie at the policy.

**Additional context**
None
