### ISSUE TITLE
transit-attachment

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#6493]
**Describe the bug**
 In custodian schema, I see aws.transit-attachment.filters.event, but when I ran the custodian policy in the cloudtrial mode, it says resource:aws.transit-attachment does not support cloudtrail mode policies.

**To Reproduce**

**Expected behavior**
aws.transit-attachment is a child resource of aws.transit-gateway, and child resources have to explicitly opt into cloudtrail mode.

**Background (please complete the following information):**
 - OS: AMZNlinuz2
 - Python Version: python 3.8.1
  - Custodian Version: 0.9.10
 - Tool Version: [if applicable]
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: transitgateway-attachments
    resource: aws.transit-attachment
    description: Notify when some attaches transitgateway.
    mode:
      type: cloudtrail
      role: CustodianLambdaExecutionRole
      memory: 256
      timeout: 180
      runtime: python3.8
      events:
        - source: ec2.amazonaws.com
          event: CreateTransitGatewayVpcAttachment
          ids: requestParameters.CreateTransitGatewayVpcAttachmentRequest.TransitGatewayId 
    filters:
      - or:
        - not:
          - type: event
            key: requestParameters.CreateTransitGatewayVpcAttachmentRequest.TagSpecifications.Tag[].Contact
            value: 'test'
            op: contains
          - type: event
            key: requestParameters.CreateTransitGatewayVpcAttachmentRequest.TagSpecifications.Tag[].Project
            op: ne
            value: Infrastructure
            value_type: normalize
    actions:
      - type: notify
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
