### ISSUE TITLE
EC2 MetadataOptions documentation

### ISSUE THREAD

**Issue by ryanash999** [cloud-custodian/cloud-custodian#6494]
**Describe the bug**
Documentation indicates the key is "MetadataOptions.HttpsToken" but it is actually "MetadataOptions.HttpTokens"

**To Reproduce**
custodian run with simple policy:

```
policies:
  - name: ec2-metadata
    resource: aws.ec2
    description: "foo"
    filters:
      - State.Name: running
      - MetadataOptions.HttpTokens: optional
      - MetadataOptions.HttpEndpoint: enabled
```

**Expected behavior**
Update documentation

https://cloudcustodian.io/docs/aws/resources/ec2.html?highlight=metadataoptions#aws-ec2-actions-set-metadata-access
