### ISSUE TITLE
Event Pattern is not valid, PHD all events

### ISSUE THREAD

**Issue by s3than** [cloud-custodian/cloud-custodian#6507]
**Describe the bug**

```
botocore.errorfactory.InvalidEventPatternException: An error occurred (InvalidEventPatternException) when calling the PutRule operation: Event pattern is not valid. Reason: Empty objects are not allowed at [Source: (String)"{"source": ["aws.health"], "detail": {}}"; line: 1, column: 40]
```

**To Reproduce**

Create a PHD alert for all events

**Expected behavior**
No Error

**Background (please complete the following information):**
  - Custodian Version: [e.g. 0.9.10.]
 
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: phd-alerts
    resource: account
    comment: PHD alerts
    mode:
      type: phd
      role: xxxxx
    description: Any PHD alert
```
**Additional context**

https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/mu.py#L1074

The empty object at the above line causes the boto3 error
