### ISSUE TITLE
when fetching the SQS details along with createdtimestamp, we are getting unix time format

### ISSUE THREAD

**Issue by surendarkaniops** [cloud-custodian/cloud-custodian#6514]
**Describe the bug**
whenever we are fetch the details of SQS in AWS, we are getting UNIX timeformat in createdtimestamp. The same datetime format (UNIX format or epoch ) reflected in j2 template, so users facing difficulty.

**To Reproduce**
write the policy to list the SQS topics  and notify to users
See the createdtimestamp in resources.json file 
use J2 template to notify 

**Expected behavior**

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure] AWS
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
        - name: sqs-notify
          resource: sqs
          filters:
                  - type: value
                    key: "KmsMasterKeyId"
                    value: null
                    op: eq
                    value_type: normalize
                    sort-by: "date"
output"
QueueArn": "",
    "ApproximateNumberOfMessages": "0",
    "ApproximateNumberOfMessagesNotVisible": "0",
    "ApproximateNumberOfMessagesDelayed": "0",
    **"CreatedTimestamp": "1598367430",
    "LastModifiedTimestamp": "1598367430"**,
    "VisibilityTimeout": "30",
    "MaximumMessageSize": "262144",
    "MessageRetentionPeriod": "120",
    "DelaySeconds": "0",
    "ReceiveMessageWaitTimeSeconds": "0",
    "QueueUrl": "t",
    "Tags": [],
    "c7n:MatchedFilters": [
      "KmsMasterKeyId"
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
