### ISSUE TITLE
Azure: Filter Configuration - Need Examples

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6526]
I just came across this filter called CONFIGURATION. I am not sure how to use it. There's no example within the documentation or Github. I am excited to see its potential use- does it refer to the "settings/configurations" for the supported resources. If that's the case, can you please give some examples (let's say- storage account- how can we find all those configurations then?)

https://cloudcustodian.io/docs/azure/resources/azure-common-filters.html#azure-common-filters-configuration

Can you please share with me a repo where you may have written a lot of azure policies?

**Comment by aakifshaikh** [comment]
Looks like I am using the correct resource type, filter, and action and the custodian is still failing the validation. I am having the same issue with **storageaccount-TLS-not-latest-version.yml**

```
2021-03-12 12:40:48,078: custodian.commands:ERROR Configuration invalid: sec-n-storageaccount-TLS-not-latest-version.yml
2021-03-12 12:40:48,079: custodian.commands:ERROR {'name': 'sec-n-storageaccount-TLS-not-latest-version', 'resource': 'azure.storage', 'description': 'Find all storage accounts which are not using the latest TLS version (v1.2).\nThis policy is running every.\n', 'filters': [{'type': 'configuration', 'key': 'minimumTlsVersion', 'op': 'ne', 'value': '1.2'}], 'mode': {'type': 'azure-periodic', 'schedule': '0 */10 * * * *', 'provision-options': {'identity': {'type': 'UserAssigned', 'id': '000xxxxxxx'}}, 'execution-options': {'output_dir': 'azure://cloudcusxxxxxxxxxxe}/{now:%Y/%m/%d/%H/}'}}, 'actions': [{'type': 'logic-app', 'resource-group': 'cloud-custodian', 'logic-app-name': 'custodianxxxxxx', 'batch': False, 'body': '{ PolicyName: policy.name, PolicyDescription: policy.description, Resource: resource.\n    {\n    Name: name,\n    Location: location,\n    Owner: tags.owner,\n    VmSize: properties.hardwareProfile.vmSize\n    }\n}'}]} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/azure.storage/policy'}]}

On instance['policies'][0]:
    {'actions': [{'batch': False,
                  'body': '{ PolicyName: policy.name, PolicyDescription: '
                          'policy.description, Resource: resource.\n'
                          '    {\n'
                          '    Name: name,\n'
                          '    Location: location,\n'
                          '    Owner: tags.owner,\n'
                          '    VmSize: properties.hardwareProfile.vmSize\n'
                          '    }\n'
                          '}',
                  'logic-app-name': 'custodianxxxx',
                  'resource-group': 'cloudxxxx',
                  'type': 'logic-app'}],
     'description': 'Find all storage accounts which are not using the '
                    'latest TLS version (v1.2).\n'
                    'This policy is running every.\n',
     'filters': [{'key': 'minimumTlsVersion',
                  'op': 'ne',
                  'type': 'configuration',
                  'value': '1.2'}],
     'mode': {'execution-options': {'output_dir': 'azure://cloudcuxxxxxxxxxxxxxxxY/%m/%d/%H/}'},
              'provision-options': {'identity': {'id': '000xxxxxx',
                                                 'type': 'UserAxxxed'}},
              'schedule': '0 */10 * * * *',
              'type': 'azure-periodic'},
     'name': 'sec-n-storageaccount-TLS-not-latest-version',
     'resource': 'azure.storage'}
2021-03-12 12:40:48,079: custodian.commands:ERROR 'configuration' is not one of ['cost']

Failed validating 'enum' in schema[0]['properties']['type']:
    {'enum': ['cost']}

On instance['type']:
    'configuration'

```
**Issue with require-secure-transfer - storageaccount**

```
(custodian) xxxx@XYZ cloud-custodian % custodian validate sec-n-blob-secure-transfer-not-enabled.yml
2021-03-12 12:39:45,865: root:ERROR specific_error failed, traceback, followed by fallback
Traceback (most recent call last):
  File "/Users/xxxxxxxxxcloud-custodian/c7n/schema.py", line 50, in validate
    resp = policy_error_scope(specific_error(errors[0]), data)
  File "/Usersxxxxxxxx/cloud-custodian/c7n/schema.py", line 122, in specific_error
    return specific_error(e)
  File "/Users/xxxxxxxxx/cloud-custodian/c7n/schema.py", line 132, in specific_error
    elif 'type' in v and t in v['properties']['type']['enum']:
KeyError: 'type'
2021-03-12 12:39:45,867: custodian.commands:ERROR Configuration invalid: sec-n-blob-secure-transfer-not-enabled.yml
2021-03-12 12:39:45,868: custodian.commands:ERROR {'name': 'sec-n-blob-secure-transfer-not-enabled', 'resource': 'azure.storage', 'description': 'Find all Storage Accounts where secure transfer has not been turned ON. \nThis policy runs every day at 9:30AM to check for the orphaned resources.\n', 'filters': [{'type': 'require-secure-transfer', 'value': False}], 'mode': {'type': 'azure-periodic', 'schedule': '0 */10 * * * *', 'provision-options': {'identity': {'type': 'UserAxxxxxxxed', 'id': '123xxxxxxxx'}}, 'execution-options': {'output_dir': 'azure://cloudcusxxxxxxxxxxm/%d/%H/}'}}, 'actions': [{'type': 'logic-app', 'resource-group': 'cloud-custodian', 'logic-app-name': 'custodianxxxx', 'batch': False, 'body': '{ PolicyName: policy.name, PolicyDescription: policy.description, Resource: resource.\n    {\n    Name: name,\n    Location: location,\n    Owner: tags.owner,\n    VmSize: properties.hardwareProfile.vmSize\n    }\n}'}]} is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['policies']['items']:
    {'anyOf': [{'$ref': '#/definitions/resources/azure.storage/policy'}]}

On instance['policies'][0]:
    {'actions': [{'batch': False,
                  'body': '{ PolicyName: policy.name, PolicyDescription: '
                          'policy.description, Resource: resource.\n'
                          '    {\n'
                          '    Name: name,\n'
                          '    Location: location,\n'
                          '    Owner: tags.owner,\n'
                          '    VmSize: properties.hardwareProfile.vmSize\n'
                          '    }\n'
                          '}',
                  'logic-app-name': 'custodianxxxxxxx',
                  'resource-group': 'cloudxxxxxx',
                  'type': 'logic-app'}],
     'description': 'Find all Storage Accounts where secure transfer has '
                    'not been turned ON. \n'
                    'This policy runs every day at 9:30AM to check for the '
                    'orphaned resources.\n',
     'filters': [{'type': 'require-secure-transfer', 'value': False}],
     'mode': {'execution-options': {'output_dir': 'azure://cloudcustodixxxxxxxxxxxm/%d/%H/}'},
              'provision-options': {'identity': {'id': 'xxxxx',
                                                 'type': 'UserAsxxxxxd'}},
              'schedule': '0 */10 * * * *',
              'type': 'azure-periodic'},
     'name': 'sec-n-blob-secure-transfer-not-enabled',
     'resource': 'azure.storage'}
2021-03-12 12:39:45,868: custodian.commands:ERROR 'require-secure-transfer' is not one of ['cost']

Failed validating 'enum' in schema[0]['properties']['type']:
    {'enum': ['cost']}

On instance['type']:
    'require-secure-transfer'

```

**Comment by stefangordon** [comment]
Hey @aakifshaikh - This appears to be an automated documentation generation bug.  Several of the filters listed in "common filters" there aren't really common.  I'm investigating it now.

The `configuration` filter is a special case of the generic `value` filter designed for use with the `webapp` resource.  It allows you to filter on the web app configuration.

You can verify what actions and filters are available for a given resource using this syntax at the command line:

```
custodian schema azure.storage
```

If you are trying to verify the HTTPS/TLS requirement for storage then you probably want this:

```
policies:
  - name: storage-https
    resource: azure.storage
    filters:
    - type: value
      key: properties.supportsHttpsTrafficOnly
      op: ne
      value: true
```

**Comment by aakifshaikh** [comment]
Having a difficult time with the below policies- I am able to validate and deploy successfully. But I am not able to get the result that I needed- even though there are non-compliant items. Can you please confirm if those policies are right?

```
- name: sec-n-webapp-authentication-service-not-enforced
  resource: azure.webapp
  description: |
    Find all Azure Application Services - Web Applications that are NOT configured to use Service Authentication.
  filters:
    - type: configuration
      key: enabled
      op: equal
      value: false
```
```
- name: sec-n-webapp-alwayson-not-enabled
  resource: azure.webapp
  description: |
    Find all Azure App Services Web Applications where AlwaysOn has not been turned ON .
    Ensure that your Microsoft Azure App Services web applications have Always On feature enabled in order to prevent applications from being 
    idled out due to inactivity. Always On keeps your websites/web applications loaded even when there's no traffic.
    False = AlwaysOn is disabled True = AlwaysOn is enabled.
  filters:
    - type: configuration
      key: AlwaysOn
      op: eq
      value: false
```
```
- name: sec-n-storage-tls-not-latest-version
  resource: azure.storage
  description: |
    Find all storage accounts which are not using the latest TLS version (v1.2).
    This policy is running every XX hours.
  filters:
    - type: value
      key: properties.minimumTlsVersion
      value: '1.2'
      op: ne
```

**Comment by aakifshaikh** [comment]
Still not able to understand where should i find the key- in this case properties.sslenforcement and properties.state.
`
policies:

- name: sec-n-sqlserver-encryption-in-transit-not-enabled
  resource: azure.sqlserver
  description: |
    Find all SQL Servers where encryption has NOT been enabled for in-transit.
    When working with production data, it is strongly recommended to enable in-transit encryption by enforcing Secure Sockets Layer (SSL) connections between MySQL 
    database servers and client applications. This will protect your data against Man-In-the-Middle (MITM) attacks and fulfill compliance requirements for 
    in-transit encryption within your organization.
    This policy runs every Sunday at 10:00AM UTC (CST time: 4:00AM).
  filters:
    - type: value
      key: properties.sslEnforcement
      op: eq
      value: Disabled
`

`
policies:

- name: sec-n-sqlserver-auditing-not-enabled
  resource: azure.sqlserver
  description: |
    Find all SQL Servers without any firewall rules defined. 
    Ensure that the "Auditing" feature is enabled within your Microsoft Azure SQL server configuration settings in order to monitor your SQL databases 
    for security, compliance and troubleshooting purposes. Once enabled, the SQL database auditing starts recording database events and writes them to 
    an audit log created within your Azure Storage account, OMS workspace or Event Hub. The logging data recorded can be extremely useful for 
    maintaining security and regulatory compliance, understand database activity and trends, and gain insight into anomalies that could indicate 
    potential security violations.
    This policy runs every Sunday at 9:55AM UTC (CST time: 3:55AM).
  filters:
    - type: value
      key: properties.state
      op: eq
      value: Disabled
`

**Comment by aakifshaikh** [comment]
@stefangordon - can you please check my filter - where I am trying to find if MFA is enabled for privileged users-
```
- name: az-cis-identity-mfa-not-enabled-privileged-users
  resource: azure.roleassignment
  description: |
    Find all Privileged users for whom MFA is NOT enabled.
    Enable multi-factor authentication for all user credentials who have write access to Azure resources. These include roles like
    Service Co-Administrators, Subscription Owners, and Contributors.
    This policy runs every Sunday at 8:55AM UTC (CST time: 2:55AM).
  filters:
    - type: value
      key: properties.roleName
      op: eq
      value: ['Owner','Contributors', 'admin']
    - type: value
      key: Microsoft.Online.Administration.StrongAuthenticationRequirement
      op: ne
      value: Enabled
```
