### ISSUE TITLE
c7n-mailer  RequestsDependencyWarning

### ISSUE THREAD

**Issue by baptiste-s** [cloud-custodian/cloud-custodian#6537]
**Describe the bug**
I installed custodian and c7n-mailer. wrote a policy to notify to my sqs queue. Looking at the logs of the mailer lambda fonction : 

`/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version! | /var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!`

**Expected behavior**
I should get a mail

**Background:**

 - Custodian Version: latest
 - Tool Version: c7n-org latest
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: mailer-test
    resource: sqs
    filters:
     - "tag:MailerTest": absent
    actions:
      - type: notify
        template: default
        priority_header: '2'
        subject: testing mailer
        to:
          - XXXXXX@XXXXX.com
        transport:
          type: sqs
          queue: https://sqs.eu-west-1.amazonaws.com/XXXXXX/Custodian-mailer
```

`/var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version! | /var/runtime/botocore/vendored/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!`
 

```
 Custodian:   0.9.10
Python:      3.6.8 (default, Aug 18 2020, 08:33:21)
             [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-*******.eu-west-1.compute.internal', release='4.18.0-240.15.1.el8_3.x86_64', version='#1 SMP Wed Feb 3 03:12:15 EST 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.2
attrs==20.3.0
boto3==1.16.42
botocore==1.19.42
importlib-metadata==3.3.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.3.3
setuptools==54.1.2
six==1.15.0
tabulate==0.8.7
typing-extensions==3.7.4.3
urllib3==1.26.2
zipp==3.4.0
```

Thank you for your help
