### ISSUE TITLE
Azure - API connection Support

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6538]
**Is your feature request related to a problem? Please describe.**
From the cloud custodian documentation, it looks like API-management is supported by Cloud Custodian and not API-Connection. I want to write a custodian policy for the following purposes-
1) Identify all API-Connections
2) Find missing Tags for API-Connections

**Describe the solution you'd like**
We want Cloud Custodian to Support resource named - "API Connections"

**Describe alternatives you've considered**
No Alternative at this time

**Additional context**
Need Visibility into this resource type- azure.api-connection

**Comment by kapilt** [comment]
do you have any interest in contributing this functionality ?

**Comment by stefangordon** [comment]
I believe this is referring to Microsoft.Web/Connections.   We do not have this resource type implemented.

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/connections

If you are just interested in tags you _might_ be able to do it with the generic resource today, add your tag filter to the below example.

In general `azure.armresource` is best used only in event policies due to the potential size of the full resource enumeration, so this isn't a good long term solution.

```
policies:
  - name: all-resources
    resource: azure.armresource
    filters:
      - type: resource-type
        values:
          - Microsoft.Web/Connections
```
