### ISSUE TITLE
aws.asg - allow setting MaxInstanceLifetime

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/cloud-custodian#6549]
**Is your feature request related to a problem? Please describe.**
I'd like to set the [MaxInstanceLifetime](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html) of ASGs.

**Describe the solution you'd like**
We should add a generic ASG action that allows us to update whatever ASG settings are needed.

**Describe alternatives you've considered**
Could create a specific action for this one setting, but that seems short-sighted.

**Additional context**
I'd propose we allow something like this (looking at what [`update_auto_scaling_groups`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/autoscaling.html#AutoScaling.Client.update_auto_scaling_group) supports):
```
name: set-asg-instance-lifetime
resource: aws.asg
filter:
  - MaxInstanceLifetime: empty
action:
  - type: update
    max-instance-lifetime: 604800  # (7 days)
```
There are probably only a handful of ASG settings that _should_ be allowed to get updated here, but it's probably more than 1, so it seems useful to allow several in one action.  I could see allowing any of the following:
```
  - type: update
    default-cooldown: 600
    max-instance-lifetime: 604800
    new-instances-protected-from-scale-in: true
    capacity-rebalance: true
```
