### ISSUE TITLE
azure - sqldatabase - add more filters

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6550]
**Is your feature request related to a problem? Please describe.**
custodian unable to filter azure sqldatabases with properties like transparentDataEncryption, dataMaskingPolicies, vulnerabilityAssessments, auditingSettings etc.

**Describe the solution you'd like**
enhance azure.sqldatabase resource to filter with foresaid options.

**Describe alternatives you've considered**
Alternative solution to use Azure CLI to directly filter resources without using custodian

**Comment by stefangordon** [comment]
Similar to #6551 - these settings have been implemented by the SQL team as dedicated ARM resources rather than properties so we'll need to add support for these child resources.

For example:
https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/2014-04-01/servers/databases/transparentdataencryption?tabs=json

**Comment by stefangordon** [comment]
Transparent Data included in #6640

**Comment by stefangordon** [comment]
Vulnerability assessments implemented at `sql-server` scope in #6651

**Comment by stefangordon** [comment]
Support for this new filter is now merged:

```
        policies:
          - name: sql-database-masking
            resource: azure.sql-database
            filters:
              - type: data-masking-policy
                enabled: false
 ```
