### ISSUE TITLE
GCP - SCC mode

### ISSUE THREAD

**Issue by anovis** [cloud-custodian/cloud-custodian#6555]
We are looking at adding support for a new mode for security command center (gcp-scc). This would allow policies to be triggered from scc findings and take actions such as notify or modify.

Currently scc allows for findings to be [pushed to a pubsub topic](https://cloud.google.com/security-command-center/docs/how-to-notifications). SCC mode could then create pubsub subscriptions based off of that topic that trigger the policies in cloud functions. Since there would only be one topic, cloudfunctions could be triggered correctly via [pubsub subscription filters](https://cloud.google.com/pubsub/docs/filtering#filtering_syntax). 

for example a policy could trigger a notification based on a firewall finding and disable the firewall rule

```
  - name: scc-alert-firewall-rules
    resource: gcp.firewall
    mode:
      type: gcp-scc
      topic: "scc-findings-topic"
    actions:
      - notify: ...
      - type: modify
        enabled: false
```    

Work that would need to be done.

* Map the finding resource to the correct custodian resource.
* Create subscription filters based on the finding resource.
* Make a get call on the resource identified in the finding to allow for further filtering and complete resource information to the actions. 

i am happy to submit a pr for this, but wanted to get your thoughts on this before diving too deep.
