### ISSUE TITLE
Custodian Lambda Memory change.

### ISSUE THREAD

**Issue by pendyalal** [cloud-custodian/cloud-custodian#6565]
**Describe the bug**
When I first deployed custodian policy, I've set a lambda memory to 128 mb. Now I want to change it to a 256mb.

**To Reproduce**
```yaml
- name: rds-unset-publiclyaccessible
  resource: rds
  mode:
    type: periodic
    schedule: "cron(0 */4 ? * * *)"
    role: LambdaExecutionRole
    memory: 160
    timeout: 120
  filters:
       - PubliclyAccessible: true
  actions:
      - type: set-public-access
        state: false
```
After changing the memory to 256 in the policy and running the custodian run command, expected memory should be 256.

**Expected behavior**
Lambda Configuration Memory should be 256

**Background (please complete the following information):**
 - OS: Amazon Linux2
 - Python Version:  python 3.8.1
 - Custodian Version: 0.9.10
 - Tool Version: [if applicable]
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
- name: rds-unset-publiclyaccessible
  resource: rds
  mode:
    type: periodic
    schedule: "cron(0 */4 ? * * *)"
    role: CustodianLambdaExecutionRole
    memory: 256
    timeout: 120
  filters:
       - PubliclyAccessible: true
  actions:
      - type: set-public-access
        state: false

```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output
 No Errors/debug output

**Additional context**
