### ISSUE TITLE
How to get a list of public EBS snapshots?

### ISSUE THREAD

**Issue by jcyriac-synamedia** [cloud-custodian/cloud-custodian#6567]
I'm trying to get a list of public EBS snapshots to do a compliance check. 

The aws cli command is -  
```
aws ec2 describe-snapshots --owner-ids self --restorable-by-user-ids all
```

Is there a way to add these parameters as a filter?

The following doesn't work as RestorableByUserIds is not an attribute
```
policies:
  - name: ebs-snapshot-public-restorable-check
    resource: ebs-snapshot
    filters:
      - type: value
        key: RestorableByUserIds
        value: "all"     
```

I'm creating a policy to replace one AWS config rule. This is the rule - https://docs.aws.amazon.com/config/latest/developerguide/ebs-snapshot-public-restorable-check.html
Thanks in advance

**Comment by ajkerrigan** [comment]
Thanks for the report. Intuition suggests that the following policy should catch public snapshots, because `everyone_only` catches public/wildcard IAM permissions in other resources:

```
policies:
  - name: ebs-public-snapshots
    resource: ebs-snapshot
    filters:
      - type: cross-account
        everyone_only: true
```

But because EBS (and RDS) snapshot permissions are handled via attributes rather than IAM policies, that doesn't work. I'm tempted to think of this as a bug or feature request for the EBS & RDS snapshot `cross-account` filters. In the meantime, one workaround would be a policy like this:

```
policies:
  - name: ebs-public-snapshots
    resource: ebs-snapshot
    filters:
      - type: cross-account
      - type: value
        key: "c7n:CrossAccountViolations"
        op: in
        value: all
        value_type: swap
```
The first filter finds any shared snapshots and records them in a `c7n:CrossAccountViolations` annotation on the resource. The second filter sees if `all` is in the violation list. It's not as neat and tidy, but it does work.
