### ISSUE TITLE
How to fetch the unencrypted buckets cloud trail CreateBucket events

### ISSUE THREAD

**Issue by surendarkaniops** [cloud-custodian/cloud-custodian#6576]
A clear and concise description of what your trying to do, as well as the underlying use case.
---------------------------------------------------------------------------------------------------------
I want to auto remediate the unencrypted AWS s3 buckets based on the event properties except "eventSource": "s3.amazonaws.com",

brief explanation:
1. I want to filter the S3 buckets which are 
filters:
        - type: bucket-encryption
          state: False
2. I want to get output from the above policy and find the  CreateBucket event for the buckets, and filter without "eventSource": "s3.amazonaws.com", (i.e filtering the AWS services created buckets)
3. finally enable the encryption

Please include any sample policy [sanitized ~ no sensitive info or account ids] to indicitate
what you've tried so far.

**Comment by aakifshaikh** [comment]
Use this policy for your purposes- You can check S3 Actions to take different actions. In the below policy we have taken delete actions.
```
policies:

- name: s3-delete-unencrypted-on-creation
  comment: "Delete unencrypted s3 bucket on creation."
  resource: s3
  filters:
    - type: bucket-encryption
      state: False
  mode:
    type: cloudtrail
    execution-options:
      output_dir: s3://BUCKETNAME/CustodianLogs/{account_id}/
    events:
      - CreateBucket
  actions:
    - delete
  ```
