### ISSUE TITLE
how to put condition to remediate the S3 buckets 

### ISSUE THREAD

**Issue by surendarkaniops** [cloud-custodian/cloud-custodian#6581]
A clear and concise description of what your trying to do, as well as the underlying use case.
-----------------------------------------------------------------------------------------------------
1. I want to filter the existing and upcoming  S3 buckets based on the **encryption** and **event source** (cloud trail event ) 
2. if not encrypted and event source is **not "s3.amazonaws.com"** should be autoremidate 
3. if not encrypted and event source **is "s3.amazonaws.com"** should be notify only 
4. if encrypted, no need to anything.

can anyone please help me in this.

Please include any sample policy [sanitized ~ no sensitive info or account ids] to indicitate
what you've tried so far.

**Comment by thisisshi** [comment]
can you describe what you mean by event source is not s3.amazonaws.com? any api actions on buckets will always have s3.amazonaws.com as the eventSource

**Comment by surendarkaniops** [comment]
Hi,
I mean to say, if the CreateBucket cloudtrail event has "s3.amazonaws.com" as eventsource (also if the bucket is not encrypted) , we don't need to take action on this only to notify.

if eventsource is something else, we should take action on it.

**Comment by thisisshi** [comment]
eventSource should always be s3.amazonaws.com do you have an example otherwise? btw the `event` filter exists to filter on event metadata, e.g.

```yaml
policies:
  - name: foo
    resource: aws.s3
    mode:
      type: cloudtrail
      role: custodian
      events:
        - CreateBucket
    filters:
      - type: event
        key: eventSource
        value: s3.amazonaws.com
```
