### ISSUE TITLE
Filter for root account password age

### ISSUE THREAD

**Issue by mihirvijdeshpande** [cloud-custodian/cloud-custodian#6589]
I have a use case where I need to find if the root account password has been changed in the last x days.
I found the password_last_changed does not work with the root account (returns N/A ).

Here's another filter I tried:
```
 filters:
     - type: value
       key: creationDate
       value_type: age
       value: 45
       op: gt
```

The above filter also does not seem to work... is there another way to achieve this?
