### ISSUE TITLE
Add aws.securityhub resource type

### ISSUE THREAD

**Issue by myoung34** [cloud-custodian/cloud-custodian#6602]
**Is your feature request related to a problem? Please describe.**

The problem is that in a multi-account organization Id like to run checks to make sure securityhub is configured correctly. * * Checking/Enabling integrations
* Deleting/checking custom actions (created by infra or the `hub-action`)

**Describe the solution you'd like**

Something like

```
policies:
  - name: check-integration
    resource: aws.securityhub
    filters:
      - type: subscription
        key: productArn
        value: arn:aws:securityhub:us-east-1:{account_id}:product-subscription/cloud-custodian/cloud-custodian
    actions:
      - type: enable-subscription
        key: productArn
        value: arn:aws:securityhub:us-east-1:{account_id}:product-subscription/cloud-custodian/cloud-custodian
``` 

**Describe alternatives you've considered**
There's currently no good way to sanity check this

**Additional context**

Right now if you enable an integration (subscription) its only for that account. Even if you did it to the delegated master. So if you dont do this to all current accounts and use c7n-org you'll get [the same error message here](https://github.com/cloud-custodian/cloud-custodian/issues/5034)

Id like to be able to run this across the board so that even new accounts get enabled as well as previous accounts.
