### ISSUE TITLE
AWS config - alb-http-to-https-redirection-check

### ISSUE THREAD

**Issue by koolwithk** [cloud-custodian/cloud-custodian#6611]
I'm trying to create custom cloudcustodian rule for aws config [alb-http-to-https-redirection-check](https://docs.aws.amazon.com/config/latest/developerguide/alb-http-to-https-redirection-check.html) but I'm not able to find list of keys that are available in app-elb. 

I'm currently looking at https://cloudcustodian.io/docs/aws/resources/app-elb.html#aws-app-elb-filters-listener but i see only 2 keys that are shown in the example(`Protocol, SslPolicy`)

Could you please let me know from where i can get the list of `Key` that are exposed by `type: listner`? 

```
policies:
  - name: ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK
    resource: app-elb
    filters:
      - type: listener
        key: ${ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK} ?
        value: ${True} ?
```

**Comment by ajkerrigan** [comment]
The `listener` filter has access to the keys that come back in a [describe_listeners](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/elbv2.html#ElasticLoadBalancingv2.Client.describe_listeners) response. That includes `DefaultActions` which is where you'd be looking for redirect info. Something like this could work but probably needs some refinement:

```
policies:
  - name: alb-https-redirect-check
    resource: app-elb
    filters:
      - type: listener
        key: Protocol
        value: HTTP
      - type: listener
        matched: true
        key: 'DefaultActions[].RedirectConfig.Protocol'
        value: [HTTPS]
        op: ne
```
