### ISSUE TITLE
how to whitelist any s3 bucket policy statement that contains any condition

### ISSUE THREAD

**Issue by cleo2525** [cloud-custodian/cloud-custodian#6619]
I am trying to create an s3 bucket policy filter to find bucket policies with certain actions and public access. I am running across a lot of false positives because many of our bucket policies contain conditions, which mitigate the public access.  I want to skip any bucket policy statement that contains any condition. I tried to use the 'whitelist_conditions' option as follows, but it's not working, the filter still matches on policy statements that contain a "StringEquals" condition. Any help would be greatly appreciated.

policies:
  - name: public-access-policy-s3-mark
    resource: s3
    filters:
      - type: check-public-block
      - type: cross-account
        everyone_only: true
        actions: ["s3:GetObject","s3:GetBucketAcl","s3:GetBucketPolicy","s3:ListBucket","s3:ListAllMyBuckets","s3:Get*","s3:List*"]
        whitelist_conditions: ["StringEquals"]

**Comment by ajkerrigan** [comment]
Carrying over some context from gitter, we discussed how the `whitelist_conditions` parameter works. If you have a bucket policy like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "OrgReadAccess",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::devprivbucket-#######",
                "arn:aws:s3:::devprivbucket-#######/*"
            ],
            "Condition": {
                "StringEquals": {
                    "aws:PrincipalOrgID": "o-##########"
                }
            }
        }
    ]
}
```

A custodian policy like this should skip it:

```
policies:
  - name: s3-filter-test
    resource: s3
    filters:
      - type: cross-account
        whitelist_conditions:
          - "aws:principalorgid"
```

_`whitelist_orgids` serves this particular example case better but doesn't cover all of your use cases._

Are you trying that sort of policy today, and it's still matching more buckets than it should? If so, please share some more information so we can get to the bottom of it:

- Custodian version
- Your full custodian policy (sanitized)
- The full bucket policy (sanitized)
- Log output from the policy run, ideally with `--verbose`

Thank you!

**Comment by cleo2525** [comment]
Thank you for your help on this.  I tested again and the following does work to whitelist the condition, if the condition is exactly  {"StringEquals": {"aws:PrincipalOrgID": "o-##########"}}

```
policies:
  - name: s3-filter-test
    resource: s3
    filters:
      - type: cross-account
        whitelist_conditions:
          - "aws:principalorgid"
```

 Unfortunately a lot of our conditions are like this. Do you have a list of condition terms that are accepted by the 'whitelist_conditions' option?
  
{"ForAnyValue:StringEquals": {"aws:PrincipalOrgID": ["o-##########", "o-##########" ] }}
{"ForAnyValue:StringLike":{"aws:PrincipalOrgPaths":"o-##########/*"}}
{"StringLike":{"aws:Referer":["*.example.com*","http://my.otherexample.com"]}}
{"IpAddress":{"aws:SourceIp":"###.###.###.###/32"}}

**Comment by cleo2525** [comment]
I also found I can add the following value filter to my c7n policy, however this doesn't take into account if you have more than one statement in a bucket policy.  It will cause the filter to skip the bucket if **any** statement in the bucket policy has "Condition" in it.  Do you know if there's a way to count the number of statements in a bucket policy?  If so, I could maybe setup different c7n policies if the bucket policy has only one statement vs if it has multiple statements.

```
      - not:
        - type: value
          key: Policy
          op: contains
          value: "Condition"
```

**Comment by ajkerrigan** [comment]
Thanks for the context, the behavior makes sense now!

> Do you have a list of condition terms that are accepted by the 'whitelist_conditions' option?

To cover all angles you'd probably need to include all the possible [S3 condition keys](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html#amazons3-policy-keys) along with the [global condition keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html). That way seems likely to lead to overkill or tedious whack-a-mole.

> Do you know if there's a way to count the number of statements in a bucket policy? If so, I could maybe setup different c7n policies if the bucket policy has only one statement vs if it has multiple statements.

I'm not aware of that exactly, but there is something along similar lines that may be useful. The problem with trying to deep match against `Policy` is that it's a JSON-encoded string. However, the `cross-account` filter parses the policy and records any violations in a `CrossAccountViolations` key. So you _could_ do something like this:

```
filters:
  - type: cross-account
  - type: value
    key: "length(CrossAccountViolations[]) == length(CrossAccountViolations[].Condition)"
    value: false
```

Which says "First, find any policies that grant cross-account access. Then, skip a bucket if every offending policy has a condition key. Seems worth a shot.

**Comment by cleo2525** [comment]
TYVM! Comparing the CrossAccountViolations length works great. That filters out all statements with a condition. 

The only condition we are using that I'd like to detect is the "aws:Referer" condition.  I went through the JMESPath docs and thought maybe I could do something like this, but it's not working.

```
    filters:
      - type: cross-account
        everyone_only: true
      - type: value
        key: "contains('CrossAccountViolations[].Condition', 'aws:Referer')"
        value: true
 ```
 
The resources.json file populates the CrossAccountViolations like this.

```
"CrossAccountViolations": [
    {
      "Sid": "Referers",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::somebucketname/path/*",
      "Condition": {
        "StringLike": {
          "aws:Referer": [
            "*.example.com*",
            "http://my.example.com:8080/",
          ]
        }
      }
    }
  ]
  ```

**Comment by ajkerrigan** [comment]
Yeah, the jmespath filters can get a bit tricky there. The cleanest way I can think to handle that from custodian is:

```
- type: value
  key: 'CrossAccountViolations[].Condition.*."aws:Referer"[]'
  value: not-null
```

Which is not especially pretty but should still work. There's some friendlier policy filtering in the works (see #6003) but it seems like with the specific combinations you're looking for you may still need the deep jmespath filters.

**Comment by cleo2525** [comment]
Thank you so much for your help!  This worked perfectly.  I ended up with two policies, one that excludes statements with any condition and one that specifically looks for the referrer condition.  Now I just need to figure out how to attach or embed the bucket policy in the notification email I am sending as part of my actions.

```
policies:
  - name: public-access-s3-bucket-policy-mark
    resource: s3
    description: locate bucket with public read access bucket policy, excludes policies with conditions
    filters:
      - "tag:c7n_public_access_exception": absent
      - "tag:c7n_public_access_bucket_policy": absent
      - type: check-public-block
      - type: cross-account
        everyone_only: true
        actions: ["s3:GetObject","s3:GetBucketAcl","s3:GetBucketPolicy","s3:ListBucket","s3:ListAllMyBuckets","s3:Get*","s3:List*"]
      - type: value
        key: "length(CrossAccountViolations[]) == length(CrossAccountViolations[].Condition)"
        value: false

  - name: public-access-s3-bucket-policy-referer-mark
    resource: s3
    description: locate bucket with public read access bucket policy, excludes policies with conditions, except aws:referer
    filters:
      - "tag:c7n_public_access_exception": absent
      - "tag:c7n_public_access_bucket_policy": absent
      - type: check-public-block
      - type: cross-account
        everyone_only: true
        actions: ["s3:GetObject","s3:GetBucketAcl","s3:GetBucketPolicy","s3:ListBucket","s3:ListAllMyBuckets","s3:Get*","s3:List*"]
      - type: value
        key: 'CrossAccountViolations[].Condition.*."aws:Referer"[]'
        value: not-null
```
