### ISSUE TITLE
azure keyvault policy to find softdelete enabled or not

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6627]
**Describe the bug**
Custodian policy returning Keyvault with Soft Delete and Purge Protection enabled, even though the policy meant to find vaults without Soft Delete and Purge Protection enabled.

**To Reproduce**
Create Key Vault in Azure with Soft Delete and Purge Protection enabled. And write policy to find **enablePurgeProtection** and  **enableSoftDelete** properties value equal to **false**

**Expected behavior**
Its expected to return Keyvaults having **enablePurgeProtection** and  **enableSoftDelete** properties value as **false**

**Background (please complete the following information):**
 - OS: Ubuntu 18.04 TLS
 - Python Version:  3.6.9
 - Custodian Version: 0.9.11
 - Tool Version: [if applicable]
 - Cloud Provider: Azure
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: az-keyvault-softdelete-disabled
    resource: azure.keyvault
    filters:
       - or:
         - type: value
           key: properties.enablePurgeProtection
           op: equal
           value: null
         - type: value
           key: properties.enablePurgeProtection
           op: equal
           value: false
         - type: value
           key: properties.enableSoftDelete
           op: equal
           value: null
         - type: value
           key: properties.enableSoftDelete
           op: equal
           value: false
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

Custodian:   0.9.11
Python:      3.6.9 (default, Jan 26 2021, 15:33:00)
             [GCC 8.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='vm01', release='5.4.0-1044-azure', version='#46~18.04.1-Ubuntu SMP Fri Mar 26 23:39:16 UTC 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed:

PyJWT==1.7.1
adal==1.2.7
applicationinsights==0.11.9
apscheduler==3.7.0
argcomplete==1.12.2
attrs==20.3.0
azure-cli-core==2.22.0
azure-cli-telemetry==1.0.6
azure-common==1.1.27
azure-core==1.13.0
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.7.0
azure-graphrbac==0.61.1
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.1.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-authorization==0.60.0
azure-mgmt-batch==7.0.0
azure-mgmt-cdn==4.0.0
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-compute==10.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==8.3.0
azure-mgmt-core==1.2.2
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==3.0.0
azure-mgmt-eventgrid==2.2.0
azure-mgmt-eventhub==3.1.0
azure-mgmt-hdinsight==1.7.0
azure-mgmt-iothub==0.10.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-logic==3.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-monitor==0.7.0
azure-mgmt-network==9.0.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-redis==6.0.0
azure-mgmt-resource==6.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-sql==0.16.0
azure-mgmt-storage==7.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-web==0.44.0
azure-nspkg==3.0.2
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-queue==2.1.0
bcrypt==3.2.0
boto3==1.17.33
botocore==1.20.33
c7n==0.9.11
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
cryptography==3.3.2
distlib==0.3.1
humanfriendly==9.1
idna==2.10
importlib-metadata==3.7.3
importlib-resources==5.1.2
isodate==0.6.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
knack==0.8.1
msal==1.11.0
msrest==0.6.21
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.1.0
paramiko==2.7.2
pkginfo==1.7.0
portalocker==1.7.1
psutil==5.8.0
pycparser==2.20
pygments==2.8.1
pynacl==1.4.0
pyopenssl==20.0.1
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
pyyaml==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.3.6
setuptools==56.0.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.4
zipp==3.4.1

**Additional context**

Azure CLI returns the output showing Soft Delete and Purge Protection enabled
```
az keyvault show --name <keyvault name>

	**"enablePurgeProtection": true,**
	"enableRbacAuthorization": null,
	**"enableSoftDelete": true,**
	"enabledForDeployment": false,
	"enabledForDiskEncryption": true,
	"enabledForTemplateDeployment": false,
```

**Comment by stefangordon** [comment]
For Key Vault I'll recommend using the new resource graph data source.   The Key Vault ARM API's do not return the fields you want in their enumeration, but the resource graph source does.

Try this:

```
policies:
  - name: keyvault-resource-graph
    source: resource-graph
    resource: azure.keyvault
```

You'll see a warning about the source being a preview - but I am removing that warning today as the graph API is now the default for the Azure Portal.
