### ISSUE TITLE
Update Docs For GCP Mode - Periodic

### ISSUE THREAD

**Issue by rahulvinodsharma** [cloud-custodian/cloud-custodian#6673]
https://cloudcustodian.io/docs/gcp/gcp-modes.html#gcp-modes 

In GCP-Periodic Schema `trigger-type` should be  `target-type`

Working Example.

```
  resource: gcp.sql-instance
  mode:
    type: gcp-periodic
    service-account: 'custodian-tests@ts-test.iam.gserviceaccount.com'
    schedule: '0 * * * *'
    target-type: pubsub
```
