### ISSUE TITLE
Retrieve SG config through use of match-resource

### ISSUE THREAD

**Issue by neilharris123** [cloud-custodian/cloud-custodian#6677]
I've been trying to find out how to correctly use the `match-resource` parameter. 

I have not found anything in the official documentation, only third party sources. From reading them, from what I understand, it can be used to reference the security-group keys of a primary policy resource (for example app-elb). 

So for example, if I defined the following policy which uses primary resource aws.app-elb, by using `match-resource` on the security-group filter, I would be able to specify keys from the security-group JSON object such as `ToPort`.

```
policies:
  - name: "test-sg-data"
    description: "ALB with tag environment=pre should not be public"
    resource: aws.app-elb
    filters:
      - type: security-group
        match-resource: true
        key: ToPort
        value: 5439
```

From my tests, this does not work, and policy returns all ELBs regardless of which port number I use.

My question is, is this the intended use-case for `match-resource`? 
How can I reference keys/values from the security group of the app-elb?

I realise I could use resource `aws.secuirty-group` instead of aws.app-elb as the primary resource in this policy, but the policy I want to write will include a combination of `aws.app-elb` and `aws.security-group` values, so that would not be suitable.

**Comment by ajkerrigan** [comment]
Hi there, you don't need `match-resource` for this - the `security-group` filter matches against security group details by default. That port information is deeper in the response though, as part of a list. So your policy would need a few tweaks:

```
    filters:
      - type: security-group
        key: IpPermissions[].ToPort
        op: in
        value_type: swap
        value: 5439
```

> I realise I could use resource aws.secuirty-group instead of aws.app-elb as the primary resource in this policy, but the policy I want to write will include a combination of aws.app-elb and aws.security-group values, so that would not be suitable.

Fair point. The `aws.security-group` [ingress](https://cloudcustodian.io/docs/aws/resources/security-group.html#aws-security-group-filters-ingress) filter is friendlier and more capable, but you're right that it means extra/separate work to get the relationship info.

> I've been trying to find out how to correctly use the `match-resource` parameter.

The `match-resource` filter would let you check to see if a given security group attribute matched the same attribute on the ELB. For example, you might define an Application tag for your ELBs and security groups. You could use `match-resource: true` and `key: tag:Application` to confirm that the ELB and security group both had the same value for the Application tag.
