### ISSUE TITLE
The iam.iam-policy is not obeying tag absence filters

### ISSUE THREAD

**Issue by trastle** [cloud-custodian/cloud-custodian#6679]
**Describe the bug**

The AWS Resource iam.iam-policy is not obeying tag filters

**To Reproduce**

1. Create an IAM Policy which has three tags 'Alpha', 'Bravo' and 'Charlie'

2. Create a Cloud Custodian Policy to find IAM Policies missing AWS Tags:

```
policies:
  - name: tag-noncompliance-aws-iam-policy
    mode: 
      type: pull
    resource: aws.iam-policy
    filters:
      - or:
          - "tag:Alpha": absent
          - "tag:Bravo": absent
          - "tag:Charlie": absent
```

3. Run the policy and observe that tagged resources are returned when they do not match any absent tag filter.

**Expected behavior**

The tagged policies should not be returned as they have all of the tags which we are filtering on being absent.

**Background (please complete the following information):**
 - OS: OSX 10.15.7
 - Python Version: 3.7.6
 - Custodian Version: 0.9.11
 - Tool Version: N/A
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: tag-noncompliance-aws-iam-policy
    mode: 
      type: pull
    resource: aws.iam-policy
    filters:
      - or:
          - "tag:Alpha": absent
          - "tag:Bravo": absent
          - "tag:Charlie": absent
```
 - Traceback: N/A No error.
 - `custodian version --debug` output

```
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.11
Python:      3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50)
             [Clang 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='TASTLE-M-72NB', release='19.6.0', version='Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.2
attrs==20.3.0
boto3==1.17.33
botocore==1.20.33
importlib-metadata==3.7.3
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.3.6
setuptools==41.2.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
urllib3==1.26.4
zipp==3.4.1
```

**Additional context**

I suspect that the tags on the IAM Policy are not being loaded at all. This is why the policy filtering on them being absent always matches. It always matches because no tags are present.

**Comment by trastle** [comment]
Following up on this. With some pointers on how tags are handled within c7n I could work on a PR to implement this. Any pointers on a good place to start?

**Comment by trastle** [comment]
I did some more digging on this, I believe the AWS IAM Policy is a candidate for supporting `universal_augment`

As defined here: 
https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/tags.py#L67-L99 

IAM::ManagedPolicy supports `Tag-based Groups` which seems to be enough to make this work nicely.

Thus importing universal_augment in `iam.py` and adding the `universal_augment` to `DescribePolicy`

```
    augment = universal_augment
```

Is enough to get the tags loaded correctly onto the Policy objects enabling filtering by tags.

This seems like a fairly simple fix, are there any side effects I should know about before proposing a PR?

**Comment by ajkerrigan** [comment]
That did sound like a nice way to handle this @trastle ! Although from some testing it looks like we can _set_ policy tags through the Resource Groups Tagging API but not _retrieve_ them. (The [GetResources](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html) call does not seem to support IAM policies.)

So I'd say if my tests were flawed and this actually works, awesome - your approach seems good :). More commonly we'd set `augment = universal_augment` at the resource manager ([example](https://github.com/cloud-custodian/cloud-custodian/blob/1ff9521fad16709e4ca10bed55187e815746aa51/c7n/resources/cw.py#L102-L102)) so it applies to both Describe and Config sources, but the approach sounds right on.

If we can't use the bulk tagging API things get a bit more dicey. Another way to get tagging info would be to add a `detail_spec` like some of the other IAM resources have. But there are a _lot_ of managed policies provided by default, so this could lead to a ton of extra API calls unless we're careful.

**Comment by trastle** [comment]
Thanks for the reply @ajkerrigan

It took me a while to get back to this to implement your suggestion but changing the resource manager seems to work a treat for me.

I have the following policy I am running to test this:

```
policies:
  - name: tag-noncompliance-aws-iam-policy
    resource: aws.iam-policy
    filters:
      - and:
        - or:
            - "tag:Alpha": absent
            - "tag:Bravo": absent
            - "tag:Charlie": absent
        # Not a default, AWS Managed IAM Policy
        - not:
          - type: value
            key: Arn
            op: regex
            value: '^arn:aws:iam::aws:policy.*$'
```

Taking an extract from the resources.json using the current `master` code I see:

```
  {
    "PolicyName": "<redacted>",
    "PolicyId": "ANPAV3HL6OCMGI7J7GG7S",
    "Arn": "<redacted>",
    "Path": "/",
    "DefaultVersionId": "v1",
    "AttachmentCount": 1,
    "PermissionsBoundaryUsageCount": 0,
    "IsAttachable": true,
    "CreateDate": "2020-11-10T07:22:24+00:00",
    "UpdateDate": "2020-11-10T07:22:24+00:00",
    "c7n:MatchedFilters": [
      "tag:Foo",
      "tag:Bar"
    ]
  },
  {
    "PolicyName": "<redacted>",
    "PolicyId": "ANPAV3HL6OCMMIKPL22YB",
    "Arn": "<redacted>",
    "Path": "/",
    "DefaultVersionId": "v1",
    "AttachmentCount": 4,
    "PermissionsBoundaryUsageCount": 0,
    "IsAttachable": true,
    "CreateDate": "2020-11-10T07:17:22+00:00",
    "UpdateDate": "2020-11-10T07:17:22+00:00",
    "c7n:MatchedFilters": [
      "tag:Foo",
      "tag:Bar"
    ]
  },
  ```
With the modification suggested above (https://github.com/cloud-custodian/cloud-custodian/compare/master...trastle:CC-6679-policytags?expand=1) I see:

```
  {
    "PolicyName": "<redacted>",
    "PolicyId": "ANPAV3HL6OCMGI7J7GG7S",
    "Arn": "<redacted>",
    "Path": "/",
    "DefaultVersionId": "v1",
    "AttachmentCount": 1,
    "PermissionsBoundaryUsageCount": 0,
    "IsAttachable": true,
    "CreateDate": "2020-11-10T07:22:24+00:00",
    "UpdateDate": "2020-11-10T07:22:24+00:00",
    "Tags": [],
    "c7n:MatchedFilters": [
      "tag:Foo",
      "tag:Bar"
    ]
  },
  {
    "PolicyName": "<redacted>",
    "PolicyId": "ANPAV3HL6OCMMIKPL22YB",
    "Arn": "<redacted>",
    "Path": "/",
    "DefaultVersionId": "v1",
    "AttachmentCount": 4,
    "PermissionsBoundaryUsageCount": 0,
    "IsAttachable": true,
    "CreateDate": "2020-11-10T07:17:22+00:00",
    "UpdateDate": "2020-11-10T07:17:22+00:00",
    "Tags": [
      {
        "Key": "Environment",
        "Value": "NonProd"
      },
      {
        "Key": "DataTaxonomy",
        "Value": "Operations Data"
      }
    ],
    "c7n:MatchedFilters": [
      "tag:Foo",
      "tag:Bar"
    ]
  },
```
  
I have not tested applying tags. I'm also not sure if the above test is the right way to test loading. But I am happy to try other things also.

For reference my virtualenv for this test is as follows: 

```
Package            Version
------------------ -------
argcomplete        1.12.2
attrs              20.3.0
boto3              1.17.33
botocore           1.20.33
c7n                0.9.12
importlib-metadata 3.7.3
jmespath           0.10.0
jsonpickle         1.3
jsonschema         3.2.0
pip                19.2.3
pyrsistent         0.17.3
python-dateutil    2.8.1
PyYAML             5.4.1
s3transfer         0.3.6
setuptools         41.2.0
six                1.15.0
tabulate           0.8.9
typing-extensions  3.7.4.3
urllib3            1.26.4
zipp               3.4.1
```
In the above `c7n` is pip installed from this repo.
