### ISSUE TITLE
c7n-org: notifications are missing account name

### ISSUE THREAD

**Issue by rvandegrift** [cloud-custodian/cloud-custodian#6692]
**Describe the bug**
I'm trying to use `c7n-org` to run custodian against numerous accounts.  I'm also using `c7n-mailer` to delivery notifications to slack.  The messages come through with a blank `Account` section.

My c7n-org config looks roughly like this:
```yaml
accounts:
- account_id: '123456789012'
  name: my-account
  regions:
  - all
  role: arn:aws:iam::123456789012:role/my-role
```

The messages being published to SQS looks like this:
```json
{
  "account_id": "123456789012",
  "account": "",
  ...
}
```

I'd expect `"my-account"` to show up in the `account` field.

**To Reproduce**
1. setup c7n-org and c7n-mailer
2. configure c7n-org as above
3. run a policy that sends a notification

**Expected behavior**
The account name should be passed through from the c7n-org config.

**Background (please complete the following information):**
I'm using the docker image `cloudcustodian/c7n:0.9.11.0`
