### ISSUE TITLE
AWS API Gateway rest-api metric filters do not work properly

### ISSUE THREAD

**Issue by rmorris1218** [cloud-custodian/cloud-custodian#6725]
**Describe the bug**
It looks like there is a bug related to the metric filters for `aws.rest-api` resources, specifically around the dimensions being incorrect.

**To Reproduce**
```bash
$ c7n-org run --dryrun -c accounts.yml -s output -u policies/api-gateway/policies.yml
Exception running policy:unused-api-gateways account:test-account region:us-east-1 error:'apigateway'
```
Given the follow policy:
```yaml
policies:
  - name: unused-api-gateways
    resource: rest-api
    filters:
      - type: metrics
        name: Count
        statistics: Sum
        days: 7
        period: 86400
        value: 5
        op: less-than
        missing-value: 0
```

**Expected behavior**
```bash
$ c7n-org run --dryrun -c accounts.yml -s output -u policies/api-gateway/policies.yml --debug
2021-06-01 17:07:47,460: c7n_org:INFO Ran account:test-account region:us-east-1 policy:unused-api-gateways matched:2 time:1.14
```

**Background (please complete the following information):**
 - OS: OS X
 - Python Version: Python 3.9
 - Custodian Version: 0.9.10.0
 - Cloud Provider: aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies:
  - name: unused-api-gateways
    resource: rest-api
    filters:
      - type: metrics
        name: Count
        statistics: Sum
        days: 7
        period: 86400
        value: 5
        op: less-than
        missing-value: 0
```
 - Traceback: `custodian.filters:WARNING CW Retrieval error: 'apigateway'`

**Additional context**
I already patched this and got it working on my local install, I will submit a follow up PR for review.
