### ISSUE TITLE
iam-user remove-keys action when matching on age can remove incorrect keys

### ISSUE THREAD

**Issue by stevesworkgithub** [cloud-custodian/cloud-custodian#6732]
**Describe the bug**
The action section in a policy to delete or disable iam-user keypairs based on age allows a secondary filter based on age to be used which no longer work safely as of 0.9.11

**To Reproduce**
Running the following policy against a live account could cause live keypairs to be disabled, therefore please do not run this against a live account.

The following policy will cause keys which are still in use to be disabled on the accounts we have tested:
```
policies:

  - name: iam-active-keys-90-days
    region: eu-west-2
    resource: iam-user
    mode:
      type: periodic
      schedule: "cron(0 06 ? * MON-FRI *)"
      role: custodian-keypwiper-delete-role
    filters:
      - type: credential
        key: access_keys.last_used_date
        value_type: age
        value: 730
        op: greater-than
    actions:
      - type: remove-keys
        disable: true
        age: 730
```

The last line was re-introduced to a policy which should have been:

```
        matched: true
```
causing keys which had been used the same day to be disabled.

**Expected behavior**
Changes made in https://github.com/cloud-custodian/cloud-custodian/issues/6419 appear to have taken a safety check off of the code, but what I'd now expect is that the "age:" key should no longer be a valid setting, as the "matched:" key now works as intended.

**Background (please complete the following information):**
Given the nature of the issue, I can't run this locally, so I'll fill in what we have from the created lambdas
 - OS: AWS Lambda
 - Python Version: 3.8.1
 - Custodian Version: 0.9.11
 - Tool Version: na
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information] (See above)

**Additional context**
The documentation https://cloudcustodian.io/docs/aws/resources/iam-user.html shows the age method of matching inside the action, so I believe the documentation also needs to be updated.

Thanks very much.
