### ISSUE TITLE
Variable interpolation only works on strings

### ISSUE THREAD

**Issue by archoversight** [cloud-custodian/cloud-custodian#6734]
**Describe the bug**

I have a c7n-org setup that has a variable that defines the grace period for the deletion of resources (EBS in this example). That variable is passed through as an string to the interpolation to make sure that yaml doesn't attempt to convert it, however that breaks the `op` action

**To Reproduce**

`ebs-delete-policy.yml`

```
---
policies:
  - name: ebs-mark-unattached-deletion
    resource: ebs
    comments: |
      Mark any unattached EBS volumes for deletion in 30 days.
      Volumes set to not delete on instance termination do have
      valid use cases as data drives, but 99% of the time they
      appear to be just garbage creation.
    filters:
      - Attachments: []
      - tag:Status: absent
    actions:
      - type: mark-for-op
        op: delete
        days: "{deletion_grace_days}"
        tag: Status

  - name: ebs-unmark-attached-deletion
    resource: ebs
    comments: |
      Unmark any attached EBS volumes that were scheduled for deletion
      if they are currently attached
    filters:
      - type: value
        key: Attachments[0].Device
        value: not-null
      - tag:Status: not-null
    actions:
      - type: unmark
        tags: [Status]

  - name: ebs-delete-marked
    resource: ebs
    comments: |
      Delete any attached EBS volumes that were scheduled for deletion
    filters:
      - type: marked-for-op
        tag: Status
        op: delete
    actions:
      - delete
...
```

`accounts.yml`:

```
accounts:
  - account_id: '999999999999'
    name: account1
    role: arn:aws:iam::999999999999:role/global/cloud-custodian
    regions: [all]
    vars:
        deletion_grace_days: 30
```

Fails with error:

```
c7n_org:ERROR Exception running policy:ebs-mark-unattached-deletion account:account1 region:us-east-2 error:unsupported type for timedelta days component: str
```

**Expected behavior**

I expect that I can user variable interpolation even for items that expect integers.

**Background (please complete the following information):**
 - OS: RHEL 8.2
 - Python Version: Python 3.8.0
 - Custodian Version: 
   ```
   c7n==0.9.11
   c7n-org==0.6.10
   ```
 - Tool Version: [if applicable]
 - Cloud Provider: aws

```
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.11
Python:      3.8.0 (default, Mar  9 2020, 18:02:46)
             [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-10-144-29-109', release='4.18.0-193.51.1.el8_2.x86_64', version='#1 SMP Thu Apr 8 13:59:36 EDT 2021', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==1.12.2
attrs==20.3.0
boto3==1.17.33
botocore==1.20.33
importlib-metadata==3.7.3
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.17.3
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.3.6
setuptools==41.6.0
six==1.15.0
tabulate==0.8.9
typing-extensions==3.7.4.3
urllib3==1.26.4
zipp==3.4.1
```
