### ISSUE TITLE
azure add caching for diagnostics-filter

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6745]
**Is your feature request related to a problem? Please describe.**
Currently **diagnostics-filter** making multiple calls to get monitoring details of a resource and it's impacting execution time if policy contains multiple filters.

**Describe the solution you'd like**
Add caching to **diagnostics-filter**  to avoid multiple calls to same resource to check monitoring details.

**Describe alternatives you've considered**
NA

**Additional context**
Here is the sample policy
```
policies:
  - name: az-publicip-with-logging-disabled
    description:  Find publicip without logging enabled
    resource: azure.publicip
    filters:
      - or:
        - type: diagnostic-settings
          key: logs[?category == 'DDoSProtectionNotifications'][].enabled
          value: absent    
        - type: diagnostic-settings
          key: logs[?category == 'DDoSProtectionNotifications'][].enabled
          value: False
          op: in
          value_type: swap
        - type: diagnostic-settings
          key: logs[?category == 'DDoSMitigationFlowLogs'][].enabled
          value: absent    
        - type: diagnostic-settings
          key: logs[?category == 'DDoSMitigationFlowLogs'][].enabled
          value: False
          op: in
          value_type: swap
        - type: diagnostic-settings
          key: logs[?category == 'DDoSMitigationReports'][].enabled
          value: absent    
        - type: diagnostic-settings
          key: logs[?category == 'DDoSMitigationReports'][].enabled
          value: False
          op: in
          value_type: swap
```
