### ISSUE TITLE
Add GCP IAM Policy Filter

### ISSUE THREAD

**Issue by aq17** [cloud-custodian/cloud-custodian#6770]
**Is your feature request related to a problem? Please describe.**
The ability to filter GCP resources based on their individually attached IAM policies is missing. Many security benchmarks, such as those proposed by the Center for Internet Security (CIS), focus on enforcing the principle of least privilege and ensuring that access to resources is properly defined and maintained. The IAM policy filter will allow future Cloud Custodian users to easily enforce these benchmarks for any GCP resource with the `getIamPolicy` method.

**Describe the solution you'd like**
We created one base class, IamPolicyFilter, that makes the API call to retrieve the Policy object and stores it in the resource with the key “IamPolicy”. Any GCP resource that wishes to implement this filter only has to override the method _verb_arguments which returns a dictionary containing the required path parameters.

**Describe alternatives you've considered**
```
- name: gcp-cis-2-1
    description: |
      It is recommended that Cloud Audit Logging is configured to track all admin activities and read, write access to user data.
    resource: gcp.project
    filters:
      - or:
        - not:
          - type: iam-policy
            key: "bindings.auditConfigs.auditLogConfigs[*].logType"
            op: contains
            value: "DATA_WRITE"
        - not:
          - type: iam-policy
            key: "bindings.auditConfigs.auditLogConfigs[*].logType"
            op: contains
            value: "DATA_READ"
```

**Additional context**
This feature was developed to implement certain benchmarks in the CIS Google Cloud Platform Foundation Benchmarks v1.2.0
