### ISSUE TITLE
Filter for IAM Users without SSH keys

### ISSUE THREAD

**Issue by markliederbach** [cloud-custodian/cloud-custodian#6777]
**Is your feature request related to a problem? Please describe.**
It's currently possible to filter IAM Users matching keys on the `ssh-key` filter type. This works great when you are targeting users that _have_ SSH keys. However, I have a use case in which I'd like to target IAM Users who **do not** have any SSH keys.

As a comparison, this is possible with Access Keys thanks to the `credential` filter type by doing the following:
```yaml
filters:
  - type: credential
     key: access_keys
     value_type: size
     value: 0
```

But this is not possible with `ssh-key` because it requires a `key` from the matched list of SSH keys returned from `ListPublicSSHKeys`. Meaning that you cannot find users with **no** SSH keys.

**Describe the solution you'd like**
I'd like to be able to filter users by the number of SSH keys by doing something like this:
```yaml
filters:
  - type: ssh-key
    value_type: size
    value: 0
```

**Comment by markliederbach** [comment]
You can do something _close_ to this by filtering out users with `Active` SSH keys
```yaml
filters:
  - not:
       - type: ssh-key
          key: Status
          value: Active
```

However, this doesn't account for the use case of filtering out users with _any_ SSH keys (active or not).

**Comment by thisisshi** [comment]
You can resolve this by adding an additional boolean `or` filter after the `not` like so:

```yaml
policies:
  - name: filter-any-iam-user-with-ssh-keys
    resource: aws.iam-user
    filters:
      - not:
        - or:
          - type: ssh-key
            key: Status
            value: Active
          - type: ssh-key
            key: Status
            value: Inactive
```
