### ISSUE TITLE
AWS aws.rest-stage does not support cloudtrail mode request

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#6787]
**Is your feature request related to a problem? Please describe.**
We are writing an auto-tag-user policy for rest-stage for on-creation and we are getting this error message.
`2021-07-02 14:13:18,836: custodian.commands:ERROR Policy: misc-na-rest-stage-auto-tag is invalid: resource:aws.rest-stage does not support cloudtrail mode policies`

I am on the latest custodian version 0.9.12.0

```
- name: aws-rest-stage-auto-tag
  resource: aws.rest-stage
  comments: |
    Find APIGateway Rest Stage that has not been tagged with mandatory owner tag on-creation.
  filters:
    - "tag:owner": absent
  mode:
    type: cloudtrail
    events:
      - source: apigateway.amazonaws.com
        event: CreateStage
        ids: responseElements.stageName
    execution-options:
      output_dir: s3:/x/x/x/x/x/x/x
    tags: *sec-tags
    runtime: python3.8
  actions:
    - type: auto-tag-user
      tag: owner
```
