### ISSUE TITLE
azure add caching for storage-diagnostic-settings filter

### ISSUE THREAD

**Issue by lkakarla** [cloud-custodian/cloud-custodian#6789]
**Is your feature request related to a problem? Please describe.**
Currently **storage-diagnostic-settings** filter taking longer time to execute and it's impacting execution time if policy contains multiple filters.

**Describe the solution you'd like**
Add **caching** to storage-diagnostic-settings filter to avoid multiple calls to same resource to check monitoring details.

**Describe alternatives you've considered**
NA

**Additional context**
Here is the sample policy

```
policies:
  - name: az-storage-accounts-with-write-logging-disabled
    description: Find all storage accounts that have a 'write' logging setting disabled.
    resource: azure.storage
    filters:
      - or:
        - type: storage-diagnostic-settings
          storage-type: blob
          key: logging.write
          op: eq
          value: False
        - type: storage-diagnostic-settings
          storage-type: queue
          key: logging.write
          op: eq
          value: False
        - type: storage-diagnostic-settings
          storage-type: table
          key: logging.write
          op: eq
          value: False
```
