### ISSUE TITLE
Why can't i send mail after some hours or days ?

### ISSUE THREAD

**Issue by ahmedTouati** [cloud-custodian/cloud-custodian#6800]
**Describe the bug**
I configured a policy to only send mail after RDS DatabaseConnection metric has been null for a couple of days and if that metric changed before the specified period the mail should be neglected, but as I can see I receive that mail after some minutes, I added days property but nothing changed :

```
actions:
    #- type: mark-for-op
    #  op: stop
    - type: notify
      template: default.html
      priority_header: 1
      subject: "RDS - Unused Database"
      violation_desc: "RDS Instance has had no connections in the last 1 day and is unused:"
      action_desc: |
          "RDS Instance has had no connections in the last 1 day"
      to:
        - abcd@domaine.com
      transport:
          type: sqs
          queue: https://sqs.us-west-1.amazonaws.com/123456789/test_queue
          region: us-west-1
      days: 1
```

**To Reproduce**

**Expected behavior**
That i receive the mail after the number of days i specified

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. gcp, aws, azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: check-buckets
      resource: aws.s3
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
