### ISSUE TITLE
Should i run c7n commad regularly on delayed action policies ?

### ISSUE THREAD

**Issue by ahmedTouati** [cloud-custodian/cloud-custodian#6805]
I created this policy which marks a specific ebs for a notify action after one hour, and unmark it if it gets attached before one hour
my question is should I run this policy once and I will automatically notify me after one hour or untag the volume if become attached, or I have to run it regularly?

```
policies:

- name: ebs-mark-unattached
  resource: ebs
  comments: |
    Mark any unattached EBS volumes for deletion in 30 days.
    Volumes set to not delete on instance termination do have
    valid use cases as data drives, but 99% of the time they
    appear to be just garbage creation.
  filters:
    - type: value
      key: VolumeId  
      value: "vol-123456789"
  actions:
    - type: mark-for-op
      op: notify
      hours: 1
- name: ebs-umark-attached
  resource: ebs
  description: |
    Remove the deletion tag from any resource group which now contain resources
    so it doesn't get deleted by the following policy
  filters:
    - type: value
      key: VolumeId  
      value: "vol-123456789"
    - type: value
      key: "Attachments[0].Device"
      value: not-null
    - "tag:maid_status": not-null
  actions:
    - type: untag
      tags: ['maid_status']

- name: ebs-unattached-notify-before-one-day
  resource: ebs
  description: |
    Notify the resources owner on any unattached EBS.
  filters:
    - type: marked-for-op
      op: notify
  actions:
    - type: notify
      template: default.html
      priority_header: 1
      subject: "EBS - Unattached ebs volumes(s) - [in Region {{ region }}]"
      violation_desc: "EBS volume(s) has not been attached in the last 1 day:"
      action_desc: |
          "EBS volume(s) has not been attached in the last 1 day"
      to:
        - a.b@c.d
      transport:
          type: sqs
          queue: https://sqs.us-west-1.amazonaws.com/123456789/abcd
          region: us-west-1

```
