### ISSUE TITLE
sanity check policy to cleanup AMIs

### ISSUE THREAD

**Issue by JonGilmore** [cloud-custodian/cloud-custodian#6818]
We have _a lot_ of AMIs in a central account that are shared cross-account with our other various AWS accounts. Knowing that c7n doesn't support checking cross account if these AMIs are in use, we use a separate policy/process to pull a list of all of our AMIs that are in use (looking at ec2 instances and launch configs) and dump those into a file called `amis.txt`. From there, we plan to run the following policy to actually deregister these, but we'd like to get another set of eyes on this to sanity check this prior to pulling the trigger.
Here are some assumptions: 
1. all AMIs have an `app` tag, this is how we distinguish the different microservices from eachother
2. we want to explicitly ignore certain services (in this example, `app1`, `app2`, `app3`)
3. we don't want this policy to take action on AMIs that are under a year old
4. we want to keep the 15 latest AMIs for each `tag:app` - doing this with the reduce filter currently

Here's the policy that we've come up with so far:
```
policies:
  - name: ami-app-cleanup
    resource: ami
    max-resources-percent: 5
    filters:
      - "tag:app": present # ensure images have the `app` tag
      - type: unused # doesnt check cross-account, but in place as an additional safety
        value: true
      - type: image-age # only handle images older than 365 days
        days: 365
      - not:
          - "tag:app": "base"
      - not: # no snapshots, those are dealt with elsewhere
          - "tag:releaseStatus": "snapshot"
      - type: value # remove results with app1 in the app tag
        key: "tag:app"
        op: regex
        value: "^((?!app1).)*$"
      - type: value # remove results with app2 in the app tag
        key: "tag:app"
        op: regex
        value: "^((?!app2).)*$"
      - type: value # remove results with app3 in the app tag
        key: "tag:app"
        op: regex
        value: "^((?!app3).)*$"
      # `amis.txt` is a list of all AMIs in use, across all of our accounts/regions
      - type: value
        key: ImageId
        op: ni
        value_from:
          url: file:amis.txt
          format: txt
      # reduce filter groups by `app` tag and reduces the filtered
      ## ami's and gets rid of the 15 newest (so action will only happen on the oldest ones)
      - type: reduce
        sort-by: "CreationDate"
        group-by: "tag:app"
        order: desc
        discard: 15
    actions:
      - type: deregister
        delete-snapshots: true
```

We welcome any/all feedback on this, I'm happy to contribute this back to docs and such as well if it makes sense as I've seen this question come up a number of times. 
Thanks!
