### ISSUE TITLE
policy resource: ec2 filters type: health-event fails when instances >99

### ISSUE THREAD

**Issue by IngussNeilands** [cloud-custodian/cloud-custodian#6822]
Hi, 
We are trying to run ec2 health-event policy in account with more than 100 instances 
```
policies:
  - name: health-event-ec2
    resource: ec2
    filters:
      - type: health-event
```

and we are getting this error:

`c7n_org:ERROR Exception running policy:health-event-ec2 account:some-account region:us-west-1 error:An error occurred (ValidationException) when calling the DescribeEvents operation: 1 validation error detected: Value ... at 'filter.entityValues' failed to satisfy constraint: Member must have length less than or equal to 99`
