### ISSUE TITLE
AWS: Lambda Layer + Cross-Account filter

### ISSUE THREAD

**Issue by mchon89** [cloud-custodian/cloud-custodian#6824]
the bug:
`botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetLayerVersionPolicy operation: No policy is associated with the given resource`

it looks like custodian is not able to make a GetLayerVersionPolicy API call. 

**Background (please complete the following information):**
 - OS: Mac OS Catalina
 - Python Version: 3.7.3
 - Custodian Version: 0.9.10
 - Cloud Provider: aws
```yaml
policies: 
   - name: lambda-layer-cross-account
      resource: aws.lambda-layer
      filters:
      - type: cross-account
```
