### ISSUE TITLE
how to add delay in cloudtrail mode

### ISSUE THREAD

**Issue by General-Abdul-HBO** [cloud-custodian/cloud-custodian#6826]
Hello, i am trying to add the delay in cloud custodian  in cloudtrail mode for s3 buckets. basically my script is suppose to block public access to any bucket that was created with out a tag name "public" and also prevents any one from making changes to that bucket. the buckets a created from a terraform script. by the time terraform tags the created bucket the custodian script already ran and prevents terraform from tagging the bucket which in turn breaks my pipeline. i have searched high and low to see how to delay the custodian script but to no avail. PS i am aware for cron and it may be the last last resort.
i  tried to use the delay type that i believe was added to custodian but it doesnt work or maybe i am using it the wrong way

```
- name: sec-s3-public-access-block
  description: |
    prevents creating or updating of S3 Bucket Public Access without public tag
  resource: aws.s3
  mode:
    role: arn:aws:iam::{account_id}:role/Service-Lambda-Custodian-S3
    type: cloudtrail
    delay:  
      description: sleep for delay seconds before processing an event
      type: integer
 ```

but when i run the custodian validate command i get this error

2021-07-27 11:35:26,978: custodian.commands:ERROR Configuration invalid: sec-s3-public-access-block.yml
2021-07-27 11:35:26,979: custodian.commands:ERROR Error on policy:sec-s3-public-access-block resource:aws.s3
{'description': 'sleep for delay seconds before processing an event', 'type': 'integer'} is not of type 'integer'

Failed validating 'type' in schema[3]['properties']['delay']:
    {'description': 'sleep for delay seconds before processing an event',
     'type': 'integer'}

On instance['delay']:
    {'description': 'sleep for delay seconds before processing an event',
     'type': 'integer'}
2021-07-27 11:35:26,979: custodian.commands:ERROR sec-s3-public-access-block

PS also can you also point me in the right right direction of setting up aws config mode for s3 in custodian i may want to try that to see if that can be used instead of cloudtrail.

Thanks
