### ISSUE TITLE
Filtering using regex and an asterisk(*) as the value does not work properly

### ISSUE THREAD

**Issue by 253asap** [cloud-custodian/cloud-custodian#6855]
**Describe the bug**
Filtering with asterisk to find policies with asterisk's in them does not work.

**To Reproduce**
1. Create a new cloud custodian policy with these settings from the yaml below and deploy
2. Create a role and deploy a role with the assume_role_policy of the policy below
3. Check if filter was successful

**Expected behavior**
Filter should work and filter out the policy with an asterisk. Log should look like so: Filter #1 applied 1->1 filter

**Background (please complete the following information):**
 - Python Version: Python 3.6
 - Custodian Version: 0.9.5
 - Cloud Provider: AWS
 - Policy: {
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          "AWS":["arn:aws:iam::1234567890:root","*"]
        }
      },
    ]
  }
```yaml
policies:
  - name: 
    description: 
    resource: iam-role
    mode:
      type: cloudtrail
      delay: 2
      events:
        - source: iam.amazonaws.com
          event: CreateRole
          ids: "requestParameters.roleName"
        - source: iam.amazonaws.com
          event: UpdateAssumeRolePolicy
          ids: "requestParameters.roleName"
    filters:
      - or:
        - type: value
          key: "AssumeRolePolicyDocument.Statement[].Principal.AWS"
          op: regex
          value: '\*'
        - type: value
          key: "AssumeRolePolicyDocument.Statement[].Principal.AWS[]"
          op: regex
          value: '\*'
```

**Additional context**
I have also attempted this with the value as '(\\\*)' to no avail as well. One thing I've noticed is after I deploy the custodian policy the value section inside the filters change from '\\\*' to '\\\\\*' . I'm under the impression that searching for the * symbol with regex is as simple as \\\* but cloud custodian does not appear to be filtering the resource.
Have also tried with the principal as this.
        Principal = {
          "AWS": "*"
        }

**Comment by ajkerrigan** [comment]
Hi @253asap - with that jmespath expression you'll get back a flat list of principals. Since you're matching against a list rather than a string, a `regex` match isn't going to be useful. There are some alternatives though. You could use the `in` operator to see if an asterisk is in that principal list:

```
- type: value
  key: "AssumeRolePolicyDocument.Statement[].Principal.AWS[]"
  op: in
  value: "*"
  value_type: swap
```
(Note that you need `value_type: swap` because the evaluation logic goes "is `key` in `value`?" and here we want to reverse that)

Another option is to use a list as your `value` and see if it overlaps with the principal list:

```
- type: value
  key: "AssumeRolePolicyDocument.Statement[].Principal.AWS[]"
  op: intersect
  value: ["*"]
```

Because it addresses the spirit of your policy, the [cross-account](https://cloudcustodian.io/docs/aws/resources/iam-role.html#aws-iam-role-filters-cross-account) filter is also worth a mention. That would let you match roles that grant assume rights to accounts  outside a safe list that you define.

**Comment by 253asap** [comment]
Do you perhaps know why I am unable to filter for the asterisk with regex when the principal.AWS isnt a list like so:
```
{
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          "AWS": "*"
        }
      },
    ]
  }
```

Based on your answer the custodian policy should filter the above resource, but it doesn't. Unless I'm not understanding it completely.
```
    filters:
      - or:
        - type: value
          key: "AssumeRolePolicyDocument.Statement[].Principal.AWS"
          op: regex
          value: '\*'
```
