### ISSUE TITLE
[ERROR} ClientError: An error occurred (Throttling) when calling the SimulateCustomPolicy operation (reached max retries: 4): Rate exceeded

### ISSUE THREAD

**Issue by AWSCloud21** [cloud-custodian/cloud-custodian#6867]
**Describe the bug**
Getting the below error when running a periodic IAM policy for resource iam-policy.

[ERROR} ClientError: An error occurred (Throttling) when calling the SimulateCustomPolicy operation (reached max retries: 4): Rate exceeded

**To Reproduce**
Have the policy set to run periodically. This could be once daily (24 hrs) or hourly etc. 

**Expected behavior**
Expected behavior is to have Custodian loop through all the iam policies and delete the overly permissive ones. 

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15]
 - Python Version: [e.g. python 3.8.1]
 - Custodian Version: [e.g. 0.8.46.1]
 - Tool Version: [if applicable]
 - Cloud Provider: [ aws]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: ManagedPolicyAllowAll
      resource: iam-policy
      filters:
         - type: check-permissions
           match: allowed
           actions: 
               - "iam:*"
         - type: has-allow-all
     actions:
         - delete
```
 - Traceback: [if applicable, please exclude sensitive/account information]
 - `custodian version --debug` output

**Additional context**
This error only seems to occur when the policy is running periodically. This means that if the same policy is run in CloudTrail mode then there is no issue. All newly created overly permissive policies are deleted on creation. However, when the policy is set to run periodically to remove policies already in place, the error above occurs.
