### ISSUE TITLE
creating a tag value from a csv

### ISSUE THREAD

**Issue by cleo2525** [cloud-custodian/cloud-custodian#6893]
### Describe the feature

I think it would be useful to add "value_from" support for the "tag" action. For example, if I have a csv in an S3 bucket and I want to create a new tag on a resource, but I want to match on one of the resources keys and pull the tag's value from one of the csv columns. 

Like, if I was looking for Lambda functions with deprecated runtimes and I wanted to tag them with their EOL date.

```
policies:
  - name: lambda-deprecated
    resource: aws.lambda
    filters:
      - type: value
        key: "Runtime"
        op: in
        value_from:
          url: s3://my-bucket-name/lambda-deprecated-runtimes.csv
          format: csv2dict
          expr: Identifier
    action:
      - type: tag
        tag: "deprecated_lambda_runtime_date"
        value_from:
          url: s3://my-bucket-name/lambda-deprecated-runtimes.csv
          format: csv2dict
          match_key: "Runtime"
          expr: "End of support phase 2 start"
```
