### ISSUE TITLE
Flow Logs - Shared VPC

### ISSUE THREAD

**Issue by scottstaffiere** [cloud-custodian/cloud-custodian#6936]
Hi - we are using Cloud Custodian and have a check for missing flow logs as shown below
```
policies:
  - name: vpc-no-flow
    resource: aws.vpc
    description: |
      Identify VPCs with flow logging disabled
    filters:
      - type: flow-logs
        enabled: false
```

I have found that this triggers on a VPC that is shared through Resource Access Manager.  For example, Account 111111111111 shares Subnet A in VPC A to Account 999999999999.  When I look at Account 111111111111, the flow log check passes because it is configured.  When I run it in 999999999999, it does not show up, and is logged as a failure.

If you look in the console in 999999999999, you can see (shared) in the Owner ID column, and the VPC Flow Logs tab doesn't even show up.  

An ideal case for this would be to only run this where the VPC owner is equal to the Account the check is running in.
