### ISSUE TITLE
aws - validate custodian lambdas with latest lambda state changes

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#6945]
### Describe the feature

https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/

its a bit unclear what the impact is for us, but we should be testing this actively.

Looks like we missed the opt in testing period, as this is fully active since october. 

[update] looks like full roll out was delayed till dec 6th.

**Comment by TomJKing** [comment]
Apologies. I've raised this as an issue aswell, as encountered a problem with this change and deploying CloudCustodian lambdas: https://github.com/cloud-custodian/cloud-custodian/issues/6968

I've also raised a PR with a proposed resolution: https://github.com/cloud-custodian/cloud-custodian/pull/6969

**Comment by kapilt** [comment]
@TomJKing thanks for flagging this when i first became aware it sounded like it was already active (sept) and no users were flagging it.  It sounds like they delayed the roll out and we need to be a bit more pro-active. I’m going to delay the next release (originally planned for today), till we can get this sorted, as we’re unlikely to have another release before the switch over date (now dec).

**Comment by PratMis** [comment]
Hello, as per AWS all lambda function will now go through a lifecycle. On function create/update, it will go into a pending state and any subsequent api call(when the function is in pending state) will fail. We make a get_function api call right after create/update api call which is what is causing it to fail I suspect

**Comment by kapilt** [comment]
related #6969

**Comment by kapilt** [comment]
so i have a few lambda policies per this config file

```
policies: 
   - name: ec2-periodic-check
     resource: aws.ec2
     description: "aws:states:opt-in"
     mode: 
       type: periodic
       schedule: rate(1 hour)
       role: assetdb-functional
 
   - name: ec2-rule-check
     resource: aws.ec2
     description: "aws:states:opt-in"
     mode: 
       type: config-rule
       role: assetdb-functional


   - name: ec2-run-check
     resource: aws.ec2
     description: "aws:states:opt-in"
     mode: 
       type: cloudtrail
       events: [RunInstances]
       role: assetdb-functional
```

i'm using the explicit opt in syntax, i can provision and deprovision these fine custodian and mugc without the pr changes (us-east-1).

**Comment by kapilt** [comment]
performing an update though and i can trigger the exception

```
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the UpdateFunctionConfiguration operation: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-2:11222333445566:function:custodian-ec2-run-check
2021-11-07 12:05:31,453: custodian.commands:ERROR The following policies had errors while executing

```

**Comment by kapilt** [comment]
removal seems to proceed regardless of status, ie. mugc unaffected, afaict.

**Comment by kapilt** [comment]
there are some other issues per testing, in that our permission modification on the lambda for its an event source can generate a conflict as well, and we have been historically catching those :/ which in this context we don't want to be doing.

**Comment by PratMis** [comment]
> so i have a few lambda policies per this config file
> 
> ```
> policies: 
>    - name: ec2-periodic-check
>      resource: aws.ec2
>      description: "aws:states:opt-in"
>      mode: 
>        type: periodic
>        schedule: rate(1 hour)
>        role: test-functional
>  
>    - name: ec2-rule-check
>      resource: aws.ec2
>      description: "aws:states:opt-in"
>      mode: 
>        type: config-rule
>        role: test-functional
> 
> 
>    - name: ec2-run-check
>      resource: aws.ec2
>      description: "aws:states:opt-in"
>      mode: 
>        type: cloudtrail
>        events: [RunInstances]
>        role: test-functional
> ```
> 
> i'm using the explicit opt in syntax via description which translates to lambda description, i can provision and deprovision these fine custodian and mugc without the pr changes (us-east-1).

Yep, I could also verify this. No issues. I also added tags and concurrency to the policies and they went through successfully. 
```
   - name: ec2-rule-check
     resource: aws.ec2
     description: "aws:states:opt-in"
     mode:
       type: config-rule
       concurrency: 100
       role: CloudCustodianRole
       tags:
         OwnerContact: xyz@capitalone.com
```
The behavior is not consistent with what's mentioned in the doc you posted above. I can try to get some more clarification from our TAM.
