### ISSUE TITLE
Feature to mark EBS volumes with no AttachVolume event in cloud trail history

### ISSUE THREAD

**Issue by vaibhav-ak** [cloud-custodian/cloud-custodian#6967]
### Describe the feature

Hi Team , 

I wanted to know if such a feature exists today firstly.  Checking cloud trails events(lookup events) provides very valuable information about a resource's history that we would like to refer to and take actions on. 

As an example, 
" Mark/Delete EBS volumes which have no AttachVolume in cloud trial in the last 30 days "

```
  - name: ebs-stage-mark-available-volumes
    resource: ebs
    filters:
      - and:
        - "tag:maid_status": absent
        - type: cloudTrailEvents
           key: AttachVolume
           value: present
```
