### ISSUE TITLE
AWS: ASG.auto-tag-user adds one unwanted tag

### ISSUE THREAD

**Issue by llange** [cloud-custodian/cloud-custodian#6995]
### Describe the bug

When I use the `auto-tag-user` action on an ASG, it (corrrectly) tags the ASG with the 2 proper tags (`user` and `principal_id_tag`), BUT adds 1 extra tag (`maid_status`: `AutoScaleGroup does not meet policy guidelines`).

E.g.: (from CloudTrail)
```
...
    "requestParameters": {
        "tags": [
            {
                "propagateAtLaunch": false,
                "key": "maid_status",
                "value": "AutoScaleGroup does not meet policy guidelines",
                "resourceType": "auto-scaling-group",
                "resourceId": "awseb-e-xxxxxxxxxxxx-stack-AWSEBAutoScalingGroup-XXXXXXXXXXX"
            },
            {
                "propagateAtLaunch": false,
                "key": "CreatorName",
                "value": "XXX",
                "resourceType": "auto-scaling-group",
                "resourceId": "awseb-e-xxxxxxxxxxxx-stack-AWSEBAutoScalingGroup-XXXXXXXXXXX"
            },
            {
                "propagateAtLaunch": false,
                "key": "CreatorId",
                "value": "AROAXXXXXXXXXXXXXX",
                "resourceType": "auto-scaling-group",
                "resourceId": "awseb-e-xxxxxxxxxxxx-stack-AWSEBAutoScalingGroup-XXXXXXXXXXX"
            }
        ]
    },
...
```

### What did you expect to happen?

I expected only 2 tags to be set (not 3).

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.11
Python:      3.6.10 (default, Feb  3 2020, 15:11:03) 
             [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.12)]
Platform:    posix.uname_result(sysname='Darwin', nodename='Šnek', release='19.6.0', version='Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.2
attrs==19.3.0
boto3==1.17.89
botocore==1.20.89
importlib-metadata==3.7.2
jmespath==0.9.5
jsonpickle==1.3
jsonschema==3.2.0
pyrsistent==0.16.0
python-dateutil==2.8.1
pyyaml==5.3.1
s3transfer==0.4.2
setuptools==40.6.2
six==1.14.0
tabulate==0.8.7
typing-extensions==3.7.4.3
urllib3==1.25.9
zipp==3.1.0
```
```


### Policy

```shell
- name: auto-tag-user-asg
  resource: asg
  mode:
    type: cloudtrail
    events:
      - source: autoscaling.amazonaws.com
        event: CreateAutoScalingGroup
        ids: requestParameters.autoScalingGroupName
      - source: autoscaling.amazonaws.com
        event: UpdateAutoScalingGroup
        ids: requestParameters.autoScalingGroupName
    role: arn:aws:iam::{account_id}:role/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    execution-options:
      metrics_enabled: true
  filters:
    - "tag:CreatorName": absent
  actions:
    - type: auto-tag-user
      tag: CreatorName
      principal_id_tag: CreatorId
```

### Extra information or context

I know we're not on the latest version ; but it seems to also be reproducible with master.

# Reproducing the case

When using the [`asg.py` implementation of `auto-tag-user.set_resource_tags`](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/asg.py#L754-L758), we can reproduce the issue (3 tags in the tag set):
```
python
Python 3.6.10 (default, Feb  3 2020, 15:11:03)
>>> import c7n
>>> from c7n.resources import asg
>>> new_tags = {}
>>> new_tags['CreatorName']='lla'
>>> new_tags['CreatorId']='lla'
>>> new_tags
{'CreatorName': 'lla', 'CreatorId': 'lla'}
>>> asg.Tag({'tags': new_tags, 'propagate': False}).get_tag_set()
[{'Key': 'maid_status', 'Value': 'AutoScaleGroup does not meet policy guidelines'}, {'Key': 'CreatorName', 'Value': 'lla'}, {'Key': 'CreatorId', 'Value': 'lla'}]
```

When using the [default implementation of `auto-tag-user.set_resource_tags`](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/actions/autotag.py#L143-L146), things work OK (2 x 1 tag in the tag set =  2 tags set (but in 2 different operations)):
```
....
>>> for key, value in new_tags.items():
...     asg.Tag({'key': key, 'value': value}).get_tag_set()
... 
[{'Key': 'CreatorName', 'Value': 'lla'}]
[{'Key': 'CreatorId', 'Value': 'lla'}]
```

The reason seems to be found in [asg.Tag.get_tag_set()](https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/asg.py#L1131-L1143) when there is no `key` in `self.data`, it will nevertheless add a default key / default value ; THEN iterate on `tags`.
