### ISSUE TITLE
Support for GCP Cloud Asset Inventory Execution Mode

### ISSUE THREAD

**Issue by fdeswardt** [cloud-custodian/cloud-custodian#7065]
### Describe the feature

Provide a new GCP execution mode to support Cloud Asset Inventory e.g. `gcp-cai`.  More details about CAI at https://cloud.google.com/asset-inventory/docs/overview.

This will enable running policies in GCP Organizations with massive scale e.g. 80K projects, as regular API endpoints don't scale and suffers from aggressive throttling.

```
policies:

- name: stop-instance-with-public-ip
  description: |
    Stop running compute instances with a public IP address
  resource: gcp.instance
  mode:
    type: gcp-cai
  filters:
    - type: value
      key: status
      value: RUNNING
    - type: value
      key: networkInterfaces[].accessConfigs[?type == `ONE_TO_ONE_NAT`]
      value: not-null
  actions:
    type: stop
```
