### ISSUE TITLE
KMS AliasName required to check with a value from CSV file

### ISSUE THREAD

**Issue by manoharmgit** [cloud-custodian/cloud-custodian#7077]
Hi,

I am having a problem setting up a CC policy for comparing the KMS Alias Name with a value from a CSV file. The problem is the Key AliasNames returns a list with one alias name, and the value_from also returns a list. I need a way to get the alias name or is it possible to iterate through the list to check if the string exists in value_from list.

Here is the code snippet:
filters:
    - not:
      - type: value
        key: "'c7n:AliasName'"
        value_regex: 'AP-TG-([\s\S]*)$'
        op: in
        value_from:
            url: s3://<bucket-name>/listnames.csv
            format: csv2dict

Here in this example, i need to get the AliasName of the KMS key, then find the string AP-TG- within alias, and get the string after AP-TG- and check that String is available in the CSV file list (value_from). For example, the alias name is something like "alias/test-key-AP-TG-12345" and the regex will return 12345 which must be checked in the CSV list.

**Comment by ajkerrigan** [comment]
Hi @manoharmgit - that policy looks like you're on the right track! I ran some tests with a similar policy and it seems to work the way you're looking for. A few points that may help get you closer:

* This sort of lookup typically uses a `type: kms-key` filter rather than `type: value`.
* If you want to look up `12345` in your CSV given a KMS alias like `alias/test-key-AP-TG-12345`, you can try `value_regex: '.*AP-TG-(.*)'` - that will ignore anything before `AP-TG-` and match against what comes after.
* During some local testing, I had to add a `value` key to the filter even though it was overridden by `value_from`. I'll log a separate issue for that, but mentioning it here in case you see something similar.

So your policy may end up looking closer to this:

```yaml
- filters:
  - not:
    - type: kms-key
      key: "'c7n:AliasName'"
      value: placeholder  # (this line may be necessary in the short term)
      value_regex: '.*AP-TG-(.*)'
      op: in
      value_from:
        url: s3:///listnames.csv
        format: csv2dict
```

**Comment by manoharmgit** [comment]
If i use aws.kms instead of aws.kms-key, i get the resources[] empty. and its not finding the AliasName key as the resources object is empty

**Comment by ajkerrigan** [comment]
Ok hard to know where the issue is in that case. It may be helpful to try some simpler policies until you get results, and then add or tweak filters a bit at a time. Like:

Show all KMS aliases:

```yaml
policies:
  - name: aws-kms-aliases
    resource: aws.kms
```

Show all KMS aliases with `AP-TG` in the name:

```yaml
policies:
  - name: aws-kms-aliases
    resource: aws.kms
    filters:
      - type: value
        key: AliasName
        op: contains
        value: AP-TG
```

Show all KMS aliases with `AP-TG` in the name where the text afterward matches a pattern:

```yaml
policies:
  - name: aws-kms-aliases
    resource: aws.kms
    filters:
      - type: value
        key: AliasName
        value_regex: '.*AP-TG-(.*)'
        op: in
        value: '12345'
```

And work your way to the `value_from` goal in steps. Otherwise it's hard to know where the problem is coming from.

**Comment by manoharmgit** [comment]
I have tried as above. here are some more details:

If i use resource: aws.kms-key, abd the mode event is createkey on CMK key creation, i am checking to get details uisng the keyId, and then filter if the alias name as a certain string.
Below is the resource response.

  filters:
    - not:
      - type: value
        key: "AliasNames"
        op: contains
        value: AP-TG

Resources [{'AWSAccountId': '*********', 'KeyId': '***********', 'Arn': 'arn:aws:kms:us-east-1:************:key/**************', 'CreationDate': datetime.datetime(2022, 2, 2, 16, 24, 29, 695000, tzinfo=tzlocal()), 'Enabled': True, 'Description': '', 'KeyUsage': 'ENCRYPT_DECRYPT', 'KeyState': 'Enabled', 'Origin': 'AWS_KMS', 'KeyManager': 'CUSTOMER', 'CustomerMasterKeySpec': 'SYMMETRIC_DEFAULT', 'KeySpec': 'SYMMETRIC_DEFAULT', 'EncryptionAlgorithms': ['SYMMETRIC_DEFAULT'], 'MultiRegion': False, 'AliasNames': ['alias/test-poc6-12345'], 'Tags': []}]

But this condition is always false, even though AliasNames had SP-TG or not. I am guessing that AliasNames is a list and somehow it is not checking the value with in that list

If i use Resource: aws.kms, i get the Resources[] empty.

**Comment by ajkerrigan** [comment]
Ok @manoharmgit - if you want to check for aliases at creation time you can use the `CreateAlias` event. The `CreateKey` event doesn't have alias info, and aliases can be created for keys that have existed for a while. A `mode` block for `CreateAlias` would look like:

```yaml
  mode:
    type: cloudtrail
    events:
      - source: kms.amazonaws.com
        event: CreateAlias
        ids: resources[].ARN
    role: my-custodian-role
```

Where `ids: resources[].ARN` comes from looking at a [sample CreateAlias CloudTrail event](https://docs.aws.amazon.com/kms/latest/developerguide/ct-createalias.html) to see where can find alias ARNs.

With that in place you should be able to see matches with filters like:

```yaml
- type: value
  key: AliasName
  op: contains
  value: 'AP-TG'
```

or, to check for a value after `AP-TG-`:

```yaml
- type: value
  key: AliasName
  value_regex: '.*AP-TG-(.*)'
  op: in
  value:
    - '12345'
```

(Note that we're using `key: AliasName` rather than `key: AliasNames`)
