### ISSUE TITLE
Add ARM-based Lambda function architecture for AWS modes 

### ISSUE THREAD

**Issue by jinkang23** [cloud-custodian/cloud-custodian#7086]
### Describe the feature

AWS recently announced support for ARM-based architecture Lambda functions: [Migrating AWS Lambda functions to Arm-based AWS Graviton2 processors](https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-arm-based-aws-graviton2-processors/)

Considering Cloud Custodian's AWS modes are provisioned via Lambda functions with at least 512MB of memory, frequent executions has a higher cost.   

AWS claims 34% price performance with ARM-based lambda functions, and unless Cloud Custodian has any x86 specific dependencies, adding a config option to AWS modes to allow you to specify the Lambda function architecture may be all that's necessary.  

I would like a new property `function-architecture` added to each [AWS modes](https://cloudcustodian.io/docs/aws/aws-modes.html) to specify either `arm64` or `x86_64` so that the AWS lambda function for AWS mode is provisioned using the architecture I have specified.  Default architecture can be `x86_64` when this property is absent. 

example of `function-architecture` property for AWS mode `ec2-instance-state` 

```yaml
    mode:
      type: ec2-instance-state
      role: my-iam-role
      function-prefix: my-function-prefix
      function-architecture: arm64    # possible values: arm64 | x86_64
      events:
        - running
```
