### ISSUE TITLE
Adding varible to GCP action URL

### ISSUE THREAD

**Issue by harsh4870** [cloud-custodian/cloud-custodian#7096]
### Ask your question

I am trying to get the custodian to enable versioning in GCP for that writing Var in URL is necessary

```
policies:
  - name: bucket-versioning
    description: |
      Check all bucket versionig enabled
    resource: gcp.bucket
    filters:
      - or:
        - type: value
          key: name
          value: c7n-test
    actions:
    - type: webhook
      method: 'PATCH'
      url: https://storage.googleapis.com/storage/v1/b/{name}
      headers:
        static-value: '`Content-type: application/json`'
      body: |-
        {
            "versioning": {
            "enabled": true
          }
        }
```

**Error** 
`2022-02-08 16:53:58,018: custodian.actions:INFO PATCH got response 404 with URL https://storage.googleapis.com/storage/v1/b/{name}`

Looks like the variable not getting introspect, also tried with **resource.name** any help would be helpful. 

```
curl -X PATCH --data-binary @JSON_FILE_NAME \
  -H "Authorization: Bearer OAUTH2_TOKEN" \
  -H "Content-Type: application/json" \
  "https://storage.googleapis.com/storage/v1/b/BUCKET_NAME?fields=versioning"
```

Reference GCP doc : https://cloud.google.com/storage/docs/using-object-versioning#set
