### ISSUE TITLE
using multi item json as value_from in filter

### ISSUE THREAD

**Issue by SteveL1** [cloud-custodian/cloud-custodian#7118]
### Ask your question

I have a json file in the following format:

{
    "SCF001A": [
        {
            "EC2_instances": [
                "*"
            ],
            "AssetID": "1",
            "AccountID": "21312",
            "StartDate": "2021/12/12",
            "EndDate": "2021/12/12",
            "Justification": "Testing Example"
        },
        {
            "EC2_instances": [
                "i-123"
            ],
            "AssetID": "21",
            "AccountID": "12312",
            "StartDate": "2021/12/12",
            "EndDate": "2021/12/12",
            "Justification": "Testing Example"
        }
    ]
}

This is a file that is managed by our InfoSec team for other checks that are run in our organisation and it changes quite frequently.  

I would like to be able use these items as an exceptions in the policy filter.  Is it possible to create multiple "or" filter items that would iterate over the json and exclude matching instances from action?

I hope that makes sense!!!

Any advice would really help me out

Thanks

**Comment by ajkerrigan** [comment]
Hi @SteveL1 - that's a good question. I _think_ I understand what you're asking but let's see!

You should be able to help custodian find the information it needs as long as the structure is predictable - even if the individual resource exclusions change. Based on your sample, it may be helpful to use the `expr` key of a `value` filter to extract a flat list of excluded resource IDs from that JSON file. Some examples might help or raise more questions. So to filter out EC2 instances whose IDs appear in any of those `EC2_instances` arrays, you could use something like:

```yaml
filters:
  - type: value
    key: InstanceId
    op: not-in
    value_from:
      url: s3://your_bucket/ec2_exclusions.json
      expr: "SCF001A[].EC2_instances[]"
```

Where `expr` takes a [JMESPath](https://jmespath.org/) expression, and `"SCF001A[].EC2_instances[]"` yields this from your sample data:

```json
[
  "*",
  "i-123"
]
```

(The playground on the [JMESPath homepage](https://jmespath.org/) is helpful for testing expressions against sample data)

If `SCF001A` was one of multiple keys, you could capture all of them by using `expr: "values(@)[].EC2_instances[]"` instead.

This instance ID check is using plain string matching, so the wildcard (`*`) in that first block wouldn't match anything. If the intention is to exclude _all_ resources for some accounts, you can reference your JSON file from a policy [execution condition](https://cloudcustodian.io/docs/quickstart/advanced.html#conditional-policy-execution). This would avoid running your policy in accounts whose `EC2_instances` exclusion list has a `*` in it:

```yaml
conditions:
  - type: value
    key: account_id
    op: not-in
    value_from:
      url: s3://your_bucket/ec2_exclusions.json
      expr: "values(@)[]|[?contains(EC2_instances, '*')].AccountID[]"
```

I hope some of this is helpful.

**Comment by SteveL1** [comment]
Hi,

Thanks for all the information, have learned a lot from that!

One question though.  If I implement the fields is different conditions, won't we lose some of the control.

What I mean is that we only can only have exceptions where each of the json items match.  In other words, in the above example the exception would be (AssetID="1" and AccountID="21312") or (AssetID="21" and AccountID="12312").

It sounds like this would be too much of a specific requirement?

**Comment by ajkerrigan** [comment]
I might not be following what you're asking. But fine-grained compound conditions are possible, though they do require more complex expressions. For example, you could have a policy with both an execution condition and filter that both target the same file in S3:

```yaml
policies:
  - name: my-ec2-policy
    resource: aws.ec2
    conditions:
      - type: value
        key: account_id
        op: not-in
        value_from:
          url: s3://your_bucket/ec2_exclusions.json
          expr: "values(@)[]|[?contains(EC2_instances, '*')].AccountID[]"
    filters:
      - type: value
        key: InstanceId
        op: not-in
        value_from:
          url: s3://your_bucket/ec2_exclusions.json
          expr: "values(@)[]|[?AccountID=='{account_id}'].EC2_instances[]"
```

And based on your sample JSON, the policy would:

* Skip running entirely in account `21312`
* Run in account `12312` but filter out instance `i-123`
