### ISSUE TITLE
c7n-org for AWS no longer recording account tags and vars to resources.json

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#7136]
### Describe the bug

When executing a policy with c7n-org, it used to record the account specific tags and vars from the accounts.yml config file into the resources.json output file. This is no longer occurring with 0.9.14 and 0.9.15 versions. Not sure what version this broke in.

### What did you expect to happen?

If I have vars or tags listed under an account object in accounts.yml c7n-org accounts config file, it should be writting those tags and vars to each resources.json file for each resource but this is no longer occurring. I need these tags and vars to filter on for policies and for printing out during c7n-org report commands.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.14 and 0.9.15 both have this issue. I'm pretty sure this worked with 0.9.8 version
```

### Policy

```shell
Any aws policy should output the tags and vars
```

### Relevant log/traceback output

```shell
No errors occurring
```

**Comment by kapilt** [comment]
we never recorded account_id to resources.json afaik. each account and region execution is in a separate directory.

we support adding in account/region as columns in report command, ie we can output account ids but that's based on passing in a resource directory and account file which we intersect.

**Comment by fdeswardt** [comment]
@kapilt per our community call this week is it possible to add an enhancement to the `c7n-org report` functionality to reference variables from the config file i.e. accounts.yaml, in the report by referencing them as custom fields e.g.
```
c7n-org report [mandatory params] --field AccountCostCenter=vars:c7n-costcenter
```

Where the entry in the `accounts.yaml` file is as follows:
```
- account_id: '123456789012'
  display_name: my-aws-account
  email: admin@foobar.com
  name: my-aws-account
  org_id: o-vc84v8nnff
  role: arn:aws:iam::123456789012:role/c7nRole
  tags:
  - path:/MY-TEST-ACCOUNTS
  - c7n-environment:dev
  - c7n-contact:very-important-people
  - c7n-cost-center:123456
  vars:
  - c7n-environment:dev
  - c7n-contact:very-important-people
  - c7n-cost-center:123456
```

Is this something we can get in 0.9.16? 😅
