### ISSUE TITLE
How to use weekends-only in off/on hour filter?

### ISSUE THREAD

**Issue by gabfelp** [cloud-custodian/cloud-custodian#7144]
### Ask your question

Hello and thanks again for the tool! 

I made some policies to turn instances on and off at certain times of the day and they worked great! -- I used offhour and onhour filters for this.

Anyway, I was wanting to do something different now: **I'd like to create a policy that turns off an instance at 0:00 on Saturday** (Saturday morning, whatever) and **turns on the instance on Monday morning (0h)**.

I noticed that the "weekends=true" option just makes the policy not run on the weekend, so it couldn't help me in these cases. Perhaps "weekends-only" could be useful in this regard? What would be the best way to do this? Maybe make two separate policies for each case? I really do not know.

I don't know if this would be the case to create a filter for the day of the week (I don't know if something like that already exists?), but knowing where to modify in the code I can help to do that!

Could you help me with this, @ajkerrigan ? 

Thank you!!

### Policy

```shell
policies:
  - name: stop-after-hours-ec2
    resource: ec2
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        ?????
    actions:
      - stop
```

**Comment by ajkerrigan** [comment]
Yes, `weekends-only` seems like it could be helpful for your case. With `weekends-only`, your resources get turned off **Friday** and then back on **Monday**. You might be able to adapt your offhours sample policy like:
```yaml
policies:
  - name: stop-after-hours-ec2
    resource: ec2
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        weekends-only: true
        offhour: 23
    actions:
      - stop
```
Which is forcing people to stop working an hour earlier perhaps, but otherwise seems to follow the spirit of what you're looking for.

And a similar onhour policy would use `onhour: 0`. You'd definitely want to test it first to be sure it was behaving as expected, but it seems promising.

**Comment by gabfelp** [comment]
Oh, that sounds cool!

Just to make sure:
The `weekends-only` on a offhour filter **only executes at Friday**? While the `weekends-only` on a onhour filter **only executes at Monday**?

I'm asking it because this same policy that you create without `weekends-only`, like:
```
--- OFF
policies:
  - name: stop-after-hours-ec2
    resource: ec2
    filters:
      - type: offhour
        opt-out: true
        default_tz: pt
        offhour: 23
    actions:
      - stop
--- ON
policies:
  - name: start-after-hours-ec2
    resource: ec2
    filters:
      - type: onhour
        opt-out: true
        default_tz: pt
        onhour: 0
    actions:
      - start
```
Would start every day at hour 0 and stop every day at hour 23, right ?
I defined the impact of `weekends-only` correctly?

Thanks again, @ajkerrigan
