### ISSUE TITLE
Cloud Custodian c7n_org command fails with TypeError: __init__() missing 1 required positional argument: 'manager'

### ISSUE THREAD

**Issue by chase-replicated** [cloud-custodian/cloud-custodian#7182]
### Describe the bug

Cloud Custodian c7n_org command fails with TypeError: __init__() missing 1 required positional argument: 'manager'
```
❯ c7n-org run --cache-period 0 -c configs/gcp.yml -s out/gcp -u policies/gcp-compute.yml

2022-03-24 11:12:48,480: c7n_org:WARNING Error running policy in <GCP_PROJECT_ID> @ global exception: __init__() missing 1 required positional argument: 'manager'
2022-03-24 11:12:48,601: c7n_org:INFO Policy resource counts Counter()
```

### What did you expect to happen?

Cloud Custodian evaluates policy properly

### Cloud Provider

Google Cloud (GCP)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.15
Python:      3.9.8 (main, Nov 10 2021, 09:21:22) 
             [Clang 13.0.0 (clang-1300.0.29.3)]
Platform:    posix.uname_result(sysname='Darwin', nodename='Chases-MacBook-Pro.local', release='21.3.0', version='Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64', machine='x86_64')
Using venv:  False
Docker: False
Installed: 

argcomplete==2.0.0
attrs==21.4.0
boto3==1.21.9
botocore==1.24.9
c7n==0.9.15
cachetools==5.0.0
certifi==2021.10.8
charset-normalizer==2.0.7
docutils==0.17.1
google-api-core==2.5.0
google-api-python-client==2.39.0
google-auth==2.6.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.1.0
google-cloud-audit-log==0.2.0
google-cloud-core==2.2.2
google-cloud-logging==2.7.0
google-cloud-monitoring==2.9.0
google-cloud-storage==1.44.0
google-crc32c==1.3.0
google-resumable-media==2.3.0
googleapis-common-protos==1.55.0
grpc-google-iam-v1==0.12.3
grpcio==1.44.0
httplib2==0.20.4
idna==3.3
importlib-metadata==4.11.2
importlib-resources==5.4.0
jmespath==0.10.0
jsonschema==4.4.0
packaging==21.3
proto-plus==1.20.3
protobuf==3.19.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.7
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.1
pyyaml==6.0
ratelimiter==1.2.0.post0
requests==2.26.0
retrying==1.3.3
rsa==4.8
s3transfer==0.5.2
six==1.16.0
tabulate==0.8.9
typing-extensions==4.1.1
uritemplate==4.1.1
urllib3==1.26.8
zipp==3.7.0
```

### Policy
```
vars:
  common-filters: &current-datetime
    - type: value
      value_type: expiration
      value: {now}
      key: labels."expires-on"
      op: le

policies:
  - name: 'gcp-unmark-instances-fixed-labels'
    resource: gcp.instance
    filters:
      - labels."owner-email": present
      - labels."expires-on": present
      - or:
          - labels."compliance-stop-after": present
          - labels."compliance-delete-after": present
    actions:
      - type: set-labels
        remove: [compliance-stop-after, compliance-delete-after]

  - name: 'gcp-terminate-expired-instances'
    resource: gcp.instance
    filters:
      - labels."expires-on": current-datetime
      - type: value
        key: labels."expires-on"
        value: 'never'
        op: ne
    actions:
      - delete

  - name: 'gcp-mark-badly-labeled-instances'
    resource: gcp.instance
    filters:
      or:
        - type: value
          key: labels."expires-on"
          op: regex
          value: '^((?!\d{2}-\d{2}-\d{4}($|-\d{2})).)*$'
        - type: value
          key: labels."owner-email"
          op: regex
          value: '^\S*__64__\S*__46__(com|io)$'
    actions:
      - type: mark-for-op
        label: compliance-stop-after
        days: 2


  - name: 'gcp-mark-instance-missing-labels'
    resource: gcp.instance
    filters:
      # This filters out non-k8s instances so we only kill demo k8s instances.
      - metadata.items[?key=='kubeconfig'].key | [0]: absent
      - and:
          - labels."compliance-stop-after": absent
          - labels."compliance-delete-after": absent
      - or:
          - labels."owner-email": absent
          - labels."expires-on": absent
    actions:
      - type: mark-for-op
        label: compliance-stop-after
        op: stop
        days: 2

  - name: 'gcp-stop-marked-instances'
    resource: gcp.instance
    filters:
      - type: marked-for-op
        label: compliance-stop-after
        op: stop
      - labels."compliance-delete-after": absent
      - or:
          - labels."owner-email": absent
          - labels."expires-on": absent
    actions:
      - type: mark-for-op
        label: compliance-delete-after
        op: delete
        days: 2

  - name: 'gcp-terminate-stopped-instances'
    resource: gcp.instance
    filters:
      - status: TERMINATED
      - type: marked-for-op
        label: compliance-delete-after
        op: delete
      - or:
          - labels."owner-email": absent
          - labels."expires-on": absent
    actions:
      - delete
```
### Relevant log/traceback output

```
❯ c7n-org run --cache-period 0 -c configs/gcp.yml -s out/gcp -u policies/gcp-compute.yml

2022-03-24 11:12:48,480: c7n_org:WARNING Error running policy in <GCP_PROJECT_ID> @ global exception: __init__() missing 1 required positional argument: 'manager'
2022-03-24 11:12:48,601: c7n_org:INFO Policy resource counts Counter()
```
