### ISSUE TITLE
support `copy-related-tag` when related resource is not a first-class resource type

### ISSUE THREAD

**Issue by tjstansell** [cloud-custodian/cloud-custodian#7188]
### Describe the feature

I'd like to copy tags from related resources, where the related resource might not be a first-class resource in cloud-custodian.  I should be able to pass it an ARN of a resource and it could query the tags for that resource using the `resourcegroupstaggingapi`.  There's no reason why we need full support for a resource just to query the tags to copy them.  The resource that is getting tags applied to it, however, would likely need full support.

Perhaps there are use-cases where you might want to query the `resourcegroupstaggingapi` directly as a first-class resource, filtering results only by tags or ARN, and then modifying tags.  If this were the case, then `copy-related-tag` could be used as-is with `resourcegroupstaggingapi` as the resource type:
```
  - name: run-ec2-auto-propagate-image-builder-tags
    resource: ec2
    comment: |
      Image builder does not propagate all tags to ec2 instances used to build the
      image.  So, we try to auto-propagate tags from the image builder definition.
    mode:
      type: cloudtrail
      events:
        - RunInstances
      delay: 5
    filters:
      - type: event
        key: detail.sourceIPAddress
        value: imagebuilder.amazonaws.com
      - "tag:Ec2ImageBuilderArn": not-null
    actions:
      - type: copy-related-tag
        resource: resourcegroupstaggingapi      # <-- instead of missing `imagebuilder` resource type
        key: "tag:Ec2ImageBuilderArn"
        tags: '*'
```
