### ISSUE TITLE
encrypt-instance-volumes does not preserve volume tags

### ISSUE THREAD

**Issue by avishayil** [cloud-custodian/cloud-custodian#7206]
### Describe the bug

When I ran the following policy:
````
policies:
  - name: encrypt-unencrypted-ebs-run
    resource: ebs
    filters:
      - Encrypted: false
    actions:
      - type: encrypt-instance-volumes
        key: alias/aws/ebs
````

I expected that the new provisioned EBS volume will inherit it's tags from the previous EBS volume, since we depend some of our logic on the ebs volume tags.

### What did you expect to happen?

I expected the new provisioned encrypted EBS volume to inherit the tags from the unencrypted EBS volume, but there are no tags on the new EBS volume.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.15
Python:      3.8.8 (default, Jan  1 2022, 08:54:04) 
             [Clang 13.0.0 (clang-1300.0.29.30)]
Platform:    posix.uname_result(sysname='Darwin', nodename='NG-AVISHAY-BAR', release='21.4.0', version='Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==21.4.0
boto3==1.21.18
botocore==1.24.18
docutils==0.17.1
importlib-metadata==4.11.3
importlib-resources==5.4.0
jmespath==0.10.0
jsonschema==4.4.0
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.5.2
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.2
urllib3==1.26.8
zipp==3.7.0
```

### Policy

```shell
`
policies:
  - name: encrypt-unencrypted-ebs-run
    resource: ebs
    filters:
      - Encrypted: false
    actions:
      - type: encrypt-instance-volumes
        key: alias/aws/ebs
````
```


### Relevant log/traceback output

_No response_

### Extra information or context

_No response_
