### ISSUE TITLE
Add `deprecated` option to RDS `upgrade-available` filter

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#7208]
### Describe the feature

The [DescribeDBEngineVersions](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBEngineVersions.html) API call supports filtering by status. It would be useful to be able to fine-tune the results of the [upgrade-available filter](https://cloudcustodian.io/docs/aws/resources/rds.html#aws-rds-filters-upgrade-available) so that it only matches instances running on deprecated engine versions.

### Extra information or context

Motivated by a recent [RDS security bulletin](https://aws.amazon.com/security/security-bulletins/AWS-2022-004/).

**Comment by thisisshi** [comment]
what would the interface for this look for? it's not clear to me how i would express this in the existing upgrade-available filter

```yaml
policies:
- name: deprecated-engines-rds
  resource: aws.rds
  filters:
    - type: upgrade-available
      deprecated: true
```

the above policy doesnt seem particularly obvious what the intent is, are we saying we're looking for rds databases that have a upgrade to a deprecated version available? it's probably better expressed as a separate filter imo

**Comment by ajkerrigan** [comment]
Fair point, I wasn't sure about a separate filter myself. I was thinking that something like `deprecated_only: true` would be similar to how we use `everyone_only: true` to fine-tune the `cross-account` filter.

Separate filter works too though, probably clearer and more explicit that way :+1:

**Comment by thisisshi** [comment]
How's this look? a more generic filter on the db engines, could be useful to find instances that have certain valid upgrade targets as well

```yaml
policies:
  - name: find-rds-deprecated
    resource: aws.rds
    filters:
      - type: engine
        key: Status
        value: deprecated
```
