### ISSUE TITLE
mark-for-op support for aws.cfn resource

### ISSUE THREAD

**Issue by cramseyio** [cloud-custodian/cloud-custodian#7240]
### Describe the feature

It does not appear that _mark-for-op_ is currently supported for **aws.cfn** CloudFormation resource. Is it possible to add support for this?

### Extra information or context

I notice when i run `custodian schema aws.cfn` it is not listed in the actions list:

```
aws.cfn:
  actions:
  - auto-tag-user
  - copy-related-tag
  - delete
  - invoke-lambda
  - invoke-sfn
  - notify
  - post-finding
  - post-item
  - put-metric
  - remove-tag
  - set-protection
  - tag
  - webhook
  filters:
  - config-compliance
  - event
  - finding
  - ops-item
  - reduce
  - value
```

The use-case here is for me to be able to report the finding to Security Hub before Custodian deletes the stack. The only other way I can think to do this is to utilize _tag_ and _remove-tag_ actions with delay, along with CloudTrail action for UpdateStack while filtering on that tag. But I would prefer to use _mark-for-op_ instead if possible.

**Comment by cramseyio** [comment]
Here is an example of what I'd like to be able to do:

```
actions:
  - type: mark-for-op
    tag: *markforop_noncompliant_tag
    op: delete
    hours: 0.2
```
