### ISSUE TITLE
Where can I find docs for all types of keys that I can use in my policies? 

### ISSUE THREAD

**Issue by vancentle1996** [cloud-custodian/cloud-custodian#7245]
### Ask your question

I am having trouble looking for docs that show me how to use certain key names in policies.  For example: 

I got the policy below from Jamison Roberts, if I would change the list to include a bunch of S3 bucket names and want to exclude them from my scan, how do I know exactly what key to use? Like would it be:

```
filters:
    - tag:LoadType: absent
    - type: value
      key: "BucketName"
      op: in
      value_from:
         url: s3://somes3bucket/CloudCustodian/AmazonLinuxAMIs.csv
         format: csv2dict
```

Or 

```
filters:
    - tag:LoadType: absent
    - type: value
      key: "bucketname"
      op: in
      value_from:
         url: s3://somes3bucket/CloudCustodian/AmazonLinuxAMIs.csv
         format: csv2dict
```

...etc

### Policy

```shell
- name: ec2-tag-stateless-instance-at-launch
  resource: ec2
  description: |
      This policy is triggered on new ec2 instances. If the instance is missing the LoadType tag AND 
      is using an amazon AMI then it tags the instance with LoadType: stateless
  mode:
    type: cloudtrail
    events:
      - RunInstances
  filters:
    - tag:LoadType: absent
    - type: value
      key: "ImageId"
      op: in
      value_from:
         url: s3://somes3bucket/CloudCustodian/AmazonLinuxAMIs.csv
         format: csv2dict
  actions:
    - type: tag
      key: LoadType
      value: stateless
```
