### ISSUE TITLE
Azure: Not able to see any Functions Within the Function App

### ISSUE THREAD

**Issue by aakifshaikh** [cloud-custodian/cloud-custodian#7271]
### Describe the bug

I have tried deploying 40+ policies to one of our Azure subscriptions. From the terminal, it looks like the custodian policy gets deployed into the azure. But when we check in the azure console > policy > Function is empty.

I have attached the YAML policy and DEBUG messages below-

DEBUG Messages

![Screen Shot 2022-05-19 at 3 13 45 PM](https://user-images.githubusercontent.com/27826591/169397167-def03601-3e76-4f11-8143-1770ad57c44f.png)

Policy#1
```
- name: sec-n-storage-container-static-website-enabled
  resource: azure.storage-container
  description: |
    Find all containers that are configured to host static websites.
    This policy runs every Friday at 10:20 AM UTC (CDT time: 5:20 AM).
  filters:
    - type: value
      key: StaticWebsiteProperties.Enabled
      op: eq
      value: true
  mode:
    type: azure-periodic
    schedule: 0 */15 * * * * ## 0 20 10 * * Fri
    provision-options:
      identity:
        type: UserAssigned
        id: xxxabcxxx
    execution-options:
      output_dir: azure://storageexample.blob.core.windows.net/logs/{policy_name}
```

### What did you expect to happen?

Expect to see the function so that i can browse monitor and check if the policy is working and produces any results

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
freeze | grep c7n
c7n==0.9.16
c7n-azure==0.7.13
c7n-gcp==0.4.15
c7n-mailer==0.6.15
c7n-org==0.6.15
c7n-trailcreator==0.2.15
```

### Policy

```shell
- name: misc-n-webapp-identify-them-all
  resource: azure.webapp
  description: |
    Find all Azure Web Applications in the subscription.
    This policy runs every Friday at 9:55AM UTC (CDT time: 4:55 AM).
  mode:
    type: azure-periodic
    schedule: 0 */10 * * * * ## 0 55 9 * * Fri
    provision-options:
      identity:
        type: UserAssigned
        id: xxxabcxxx
    execution-options:
      output_dir: azure://storageexample.blob.core.windows.net/logs/{policy_name}
```
Policy# 3

```
- name: sec-n-sqldatabase-data-masking-not-enabled
  resource: azure.sqldatabase
  description: |
    Find all SQL databases where data masking is not enabled. 
    Dynamic data masking helps prevent unauthorized access to sensitive data by enabling customers to designate how much of the sensitive data to reveal with minimal impact on the application layer. It’s a policy-based security feature that hides the sensitive data in the result set of a query over designated database fields, while the data in the database is not changed.
    This policy runs every Friday at 10:20 AM UTC (CDT time: 5:20 AM).
  filters:
    - type: data-masking-policy
      enabled: false
  mode:
    type: azure-periodic
    schedule: 0 */15 * * * * ## 0 20 10 * * Fri
    provision-options:
      identity:
        type: UserAssigned
        id: xxxabcxxx
    execution-options:
      output_dir: azure://storageexample.blob.core.windows.net/logs/{policy_name}
```
```


### Relevant log/traceback output

_No response_

### Extra information or context

We had previously raised the same issue (#7160) and it was considered to be resolved in version 0.9.16.0 . However it seems that it is not fixed.
https://github.com/cloud-custodian/cloud-custodian/issues/7160
