### ISSUE TITLE
AWS Lambda - add "Function URL" configuration to meta-data

### ISSUE THREAD

**Issue by CallumHibbert** [cloud-custodian/cloud-custodian#7516]
### Describe the feature

I would like to write a policy to alert on the usage of Function URLs for AWS Lambda.

At the moment CloudCustodian (v0.9.17) does not include any Function URL configuration information in the meta-data/schema for AWS Lambda resources. It would be really useful to have that information added.

Thanks.

**Comment by CallumHibbert** [comment]
A separate filter is fine, probably better.

A delete function URL action would be awesome.

**Comment by kapilt** [comment]
the syntax on the filter is a little interesting, since its an array of function url configs. if we wanted multi attribute matching the syntax on a function url to determine if its valid usage or not, we probably want something more advanced then the standard key / value (single attribute) style filter. perhaps something like

```yaml
policies: 
  - name: function-urls
    resource: aws.lambda
    filters:
      - type: function-url
        attrs:
            AuthType: null
            Cors.AllowOrigins: [http://mydomain.com]
            Cors.AllowedMethods:
               op: contains
               value: POST
 ```
