### ISSUE TITLE
account-service-limits for s3

### ISSUE THREAD

**Issue by bostrowski13** [cloud-custodian/cloud-custodian#7566]
### Describe the feature

I was wondering if s3 could be part of the account-service-limit policy.  Its a global resource and I was surprised to find its not supported....

```
policies:
  - name: account-service-limits
    resource: account
    conditions:
      - region: us-east-1
    filters:
      - type: service-limit
        services:
          - S3
        threshold: 80
```

While I don't have the exact error, it basically said s3 (or S3) isn't supported.
