### ISSUE TITLE
Add Secrets Manager secrets resource

### ISSUE THREAD

**Issue by peterheo** [cloud-custodian/cloud-custodian#7583]
### Describe the feature

I would like to create a new resource type for Secrets Manager secrets resources

**Comment by thisisshi** [comment]
@peterheo there's a secrets manager resource that should suffice:

```yaml
policies:
  - name: secrets
    resource: aws.secrets-manager
```
