### ISSUE TITLE
DocumentDB offHours downtime support

### ISSUE THREAD

**Issue by nigeriabuddy** [cloud-custodian/cloud-custodian#7612]
### Describe the feature

I am with Capital One. We use your downtime feature for cost reduction in our EC2 instances which is very helpful, but it would be a huge help, and cost saver, if we could use this feature for our DocDB instances as well.

**Comment by thisisshi** [comment]
hi there, thanks for the question, document db offhours is already supported in the rds-cluster/rds resources:

```yaml
policies:
  - name: rds
    resource: rds-cluster
    filters:
      - type: offhour
        opt-out: false
        offhour: 20
        default_tz: pt
        tag: offhour
    actions:
      - type: stop
```

If you inspect the resources.json after running the policy you can see the documentdb clusters and instances in the results.
