### ISSUE TITLE
Elasticache metrics

### ISSUE THREAD

**Issue by guijusto90** [cloud-custodian/cloud-custodian#7703]
### Describe the bug

I'm trying to get Elasticache cluster metrics. But, when I use a filter with metrics, the output showing count: 0, 
even using a valid metric for the cluster and with different types of filters.

### What did you expect to happen?

If we use a valid metric filter, display all redis that's match the filters.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.18
Python:      3.8.10 (default, Jun 22 2022, 20:18:18) 
             [GCC 9.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='13618-nb', release='5.15.0-46-generic', version='#49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.1.0
boto3==1.24.44
botocore==1.27.44
docutils==0.17.1
importlib-metadata==4.12.0
importlib-resources==5.9.0
jmespath==1.0.1
jsonschema==4.9.0
pkgutil-resolve-name==1.3.10
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.3.0
urllib3==1.26.11
zipp==3.8.1
```

### Policy

```shell
policies:

  - name: low-utilization-amazon-redis-instances
    comment: Checks if you have any redis with low utilization, based on CPU metrics
    resource: aws.elasticache-group
    filters:
    - type: metrics
      name: CPUUtilization
      days: 30
      period: 86400
      value: 90
      op: less-than
```

### Relevant log/traceback output

```shell
Without metrics filters (yml under if necessary) show all redis on the acc :

---
policies:

  - name: low-utilization-amazon-redis-instances
    comment: Checks if you have any redis with low utilization, based on CPU metrics
    resource: aws.elasticache-group
---

2022-08-29 14:37:14,493: custodian.policy:INFO policy:low-utilization-amazon-ec2-instances resource:aws.elasticache-group region:us-east-1 count:179 time:6.43

With metrics filters:

2022-08-29 14:43:27,823: custodian.policy:INFO policy:low-utilization-amazon-ec2-instances resource:aws.elasticache-group region:us-east-1 count:0 time:26.64
```

### Extra information or context

CPUUtilization if a valid metric, based on AWS Docs:

https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-cloudwatchmetrics.html#managedomains-cloudwatchmetrics-cluster-metrics

https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/CacheMetrics.HostLevel.html

A example with CPUUtilization of redis instance

![watch](https://user-images.githubusercontent.com/36856644/187275070-af7b2c3b-18c8-41da-bbb0-12dce119d66e.png)

**Comment by thisisshi** [comment]
Hi, @guijusto90 seems like you're using the wrong resource type, the only metric available for replication groups is:

<img width="1680" alt="Screen Shot 2022-08-29 at 4 24 09 PM" src="https://user-images.githubusercontent.com/4026535/187315695-67618982-8277-4778-abca-aae1a8eeb991.png">

Instead, try:

```yaml
policies:
  - name: low-utilization-amazon-redis-instances
    comment: Checks if you have any redis with low utilization, based on CPU metrics
    resource: aws.cache-cluster
    filters:
    - type: metrics
      name: CPUUtilization
      days: 30
      period: 86400
      value: 90
      op: less-than
      statistics: Average
```
