### ISSUE TITLE
Still Getting Type Error when using set-s3-public-block

### ISSUE THREAD

**Issue by jwtdrjj** [cloud-custodian/cloud-custodian#7760]
### Describe the bug

`vars:
    notify-lambda: &notify-lambda
      type: invoke-lambda
      function: cloud-governance-custodianProxy

policies:
  - name: Governance-s3-block-public-buckets
    comment: "Remediate and notify when accounts are able to create public buckets"
    resource: aws.account
    conditions:
      - region: us-east-1
    filters:
      - and:
        - "tag:c7n_s3_block_public_bucket_exempt": absent
        - or:
          - not:
            - type: s3-public-block
              key: RestrictPublicBuckets
              value: True
          - not:
            - type: s3-public-block
              key: BlockPublicAcls
              value: True
          - not:
            - type: s3-public-block
              key: BlockPublicPolicy
              value: True
          - not:
            - type: s3-public-block
              key: IgnorePublicAcls
              value: True
    mode:
      schedule: "rate(24 hours)"
      type: periodic
      role: arn:aws:iam::{account_id}:role/iamCustodianRole
      tags:
        Application: Custodian
        CreatedBy: CloudCustodian
      packages: [botocore, boto3, urllib3]
    actions:
      - *notify-lambda
      - type: set-s3-public-block
        BlockPublicAcls: True
        RestrictPublicBuckets: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
`

This is the yaml policy being applied but I get the error below.  I believe I have followed the action schema not sure why I am getting this error.

`2022-09-14 19:19:29,454: custodian.policy:INFO Provisioning policy lambda: s3-block-public-buckets region: us-east-1
--
772 | Traceback (most recent call last):
773 | File "/codebuild/output/src251367118/src/indgcustodian/bin/custodian", line 8, in <module>
774 | sys.exit(main())
775 | File "/codebuild/output/src251367118/src/indgcustodian/lib/python3.9/site-packages/c7n/cli.py", line 363, in main
776 | command(config)
777 | File "/codebuild/output/src251367118/src/indgcustodian/lib/python3.9/site-packages/c7n/commands.py", line 219, in validate
778 | structure.validate(data)
779 | File "/codebuild/output/src251367118/src/indgcustodian/lib/python3.9/site-packages/c7n/structure.py", line 48, in validate
780 | self.validate_policy(p)
781 | File "/codebuild/output/src251367118/src/indgcustodian/lib/python3.9/site-packages/c7n/structure.py", line 78, in validate_policy
782 | for a in p.get('actions', ()):
783 | TypeError: 'NoneType' object is not iterable
`

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)

**Comment by kapilt** [comment]
that reads like a typo / indentation issue in the policy where the actions array isn't properly set under the `actions` key. still the validator should be doing a better job of explaining that.

**Comment by jwtdrjj** [comment]
I don't see the syntax error.  I'll try to upload yaml.

Thanks,

Jacob

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jwtdrjj** [comment]
```
policies:
  - name: Governance-s3-block-public-buckets
    comment: "Remediate and notify when accounts are able to create public buckets"
    resource: account
    conditions:
      - region: us-east-1
    filters:
      - and:
        - "tag:c7n_bucket_exempt": absent
        - or:
          - not:
            - type: s3-public-block
              key: RestrictPublicBuckets
              value: True
          - not:
            - type: s3-public-block
              key: BlockPublicAcls
              value: True
          - not:
            - type: s3-public-block
              key: BlockPublicPolicy
              value: True
          - not:
            - type: s3-public-block
              key: IgnorePublicAcls
              value: True
    mode:
      schedule: "rate(24 hours)"
      type: periodic
      packages:
        - botocore
        - boto3
        - urllib3
      role: arn:aws:iam::{account_id}:role/iamRole
      tags:
        Application: Custodian
        CreatedBy: CloudCustodian
    actions:
      - type: invoke-lambda
        function: custodianProxy
      - type: set-s3-public-block 
        BlockPublicAcls: True
        RestrictPublicBuckets: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
```
