### ISSUE TITLE
SQS Set-Encryption Not Standard

### ISSUE THREAD

**Issue by Adam-Zvolanek** [cloud-custodian/cloud-custodian#7762]
### Describe the bug

When setting encryption via KMS for other services, you can use the default alias: `alias/aws/*service*` . This means for RDS, EBS, Lambda, EFS, S3, and others, when using the set-encryption action and use the traditional default KMS alias key as mentioned above. For SQS, for some reason the correct syntax for the KMS Key is special. I have to type out the key as: `aws/*service*` since it appends the `alias/` portion.

Because of that key string change for SQS, the KmsMasterKeyID in both console and when using API commands, it returns the KeyID instead of the alias. Even though, for human reading, it is the same default alias.

![SNS](https://user-images.githubusercontent.com/113540277/190429766-48f2424f-9043-44f9-a1ed-55f4f58e4f76.jpg)
![SQS](https://user-images.githubusercontent.com/113540277/190429770-a5e2063d-486b-4e61-9ae1-8b0ca2a0f279.jpg)

Working code for the set-encryption action:
```
policies:
  - name: sqs-queue-unencrypted-enforce
    resource: aws.sqs
     ...
     actions:
      - type: set-encryption
        key: aws/sqs
```

However when running filters that check for default KmsMasterKeyId, it flags the SQS policy as it returns a non-aliased KmsMasterKeyId. Likewise on the AWS Console (in SQS Encryption) instead shows the CMK alias key, not the Default KMS Key. 

### What did you expect to happen?

When using an action for SQS written as I would expect it to be written:
```
policies:
  - name: sqs-queue-unencrypted-enforce
    resource: aws.sqs
     ...
     actions:
      - type: set-encryption
        key: alias/aws/sqs
```
This results in the following error, ![BadOutput](https://user-images.githubusercontent.com/113540277/190430119-07892446-ba36-4d56-a533-93b699e5ce47.png)

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian: 0.9.18
Python: 3.7.10
Platform: poxis.uname_result(sysname='Linux', ..., release='4.14.290-217.505.amzn2.x86_64', ..., machine='x86_64')
Using venv: True
Docker: False
Installed:

argcomplete==2.0.0
attrs==22.1.0
boto3==1.24.44
docutils==0.17.1
importlib-metadata==4.12.0
importlib-resource==5.9.0
jmespath==1.0.1
jsonschema==4.9.0
pkgutil-resolve-name==1.3.10
pyrsistent==0.18.1
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
typing-extensions==4.3.0
urllib3==1.26.11
zipp==3.8.1
```

### Policy

```shell
policies:
  - name: sqs-queue-unencrypted-enforce
    resource: aws.sqs
    #filters:
    # - type: value
    #   key: KmsMasterKeyId
    #   value: "alias/aws/sqs"
     actions:
      - type: set-encryption
        key: alias/aws/sqs
```

### Extra information or context

Amazon WorkSpaces does not allow for copy and paste, will happily provide additional information/logs as needed.
