### ISSUE TITLE
IaC Support (Terraform, Crossplane, etc.)

### ISSUE THREAD

**Issue by dschro-1993** [cloud-custodian/cloud-custodian#7771]
### Describe the feature

I am always frustrated when ...Hey guys,
when you first started with the custodian project, have you actually thought about to create a transformer/transpiler for custodian syntax to terraform syntax - to let terraform do the deployment (across various CSPs like AWS, GCP, Azure, etc.) and maintain the state...to simplify any cleanup (instead of mugc, ...), to better detect and remediate drifts, etc.

So something like:
```
policies:
  - name: s3-set-bucket-encryption
    resource: s3
    actions:
      - type: set-bucket-encryption
        crypto: AES256
        enabled: True
```

via `custodian synth policy.yml` into: (similar approach as AWS CDK uses for CloudFormation)

```
resource "aws_iam_role" {...}

resource "aws_lambda_function" "s3-set-bucket-encryption" {
  filename      = "s3-set-bucket-encryption.zip"
  function_name = "s3-set-bucket-encryption"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "custodian.run"
```
