### ISSUE TITLE
Support percentile statistics in CloudWatch metrics filter

### ISSUE THREAD

**Issue by JoshRosen** [cloud-custodian/cloud-custodian#7820]
### Describe the feature

I would like to be able to use percentile statistics (like p99) in the [AWS metrics filter](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html?highlight=metric#metrics).

For example, I want to be able to write a rule like

```yaml
policies:
  - name: ec2-underutilized
    resource: ec2
    filters:
    - type: metrics
      name: CPUUtilization
      statistics: p99
      period: 86400
      days: 7
      value: 1
      op: less-than
```

to find EC2 instances where the 99th percentile CPU usage is less than 1 percent. 

The [CloudWatch:GetMetricStatistics API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html) supports an `ExtendedStatistics` option for requesting percentile statistics, so I think it should be technically possible to support this.
