### ISSUE TITLE
The 'report' command shows results even when no matching resources

### ISSUE THREAD

**Issue by jcmcken** [cloud-custodian/cloud-custodian#7833]
### Describe the bug

When I run the following...

```
$ custodian run --dryrun -s c7n-cache policies.yaml
...snip...
$ custodian report -s c7n-cache policies.yaml --format grid
..shows a few resources..
$ grep matched-keys c7n-cache/*/resources.json
   "c7n:matched-keys": [],
   ...all results look like above...
```

The report grid shows resources. But if I examine the ``resources.json`` for each policy, there are no matching resources (``c7n:matched-keys`` is an empty array in every resource).

### What did you expect to happen?

If there are no matching resources, my understanding is that ``report`` command should show no resources. For example, there are resources I know don't match the policy that are not shown. But the resources that are shown should also not be matching the policy. 

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.18

Python:      3.8.11 ..snip…

Platform:    posix.uname_result(sysname='Linux', …, machine='x86_64')

Using venv:  True

Docker: False

Installed:

 

argcomplete==2.0.0

attrs==22.1.0

boto3==1.24.44

botocore==1.27.44

docutils==0.17.1

importlib-metadata==4.12.0

importlib-resources==5.9.0

jmespath==1.0.1

jsonschema==4.9.0

pkgutil-resolve-name==1.3.10

pyrsistent==0.18.1

python-dateutil==2.8.2

pyyaml==6.0

s3transfer==0.6.0

six==1.16.0

tabulate==0.8.10

typing-extensions==4.3.0

urllib3==1.26.11

zipp==3.8.1
```
```


### Policy

```shell
policies:

- name: iam-stale-keys

  resource: iam-user

  filters:

    - and:

      # last used over a year ago and...

      - type: credential

        key: access_keys.last_used_date

        value_type: age

        value: 360

        op: greater-than

      # key is active

      - type: credential

        key: access_keys.active

        value: true

  actions:

    # deactivate the key

    - type: remove-keys

      disable: true

      matched: true

- name: iam-never-used-keys

  resource: iam-user

  filters:

    - and:

      # key was never used and...

      - type: credential

        key: access_keys.last_used_date

        value: null

      # key was created over 180 days ago and...

      - type: credential

        key: access_keys.last_rotated

        value_type: age

        value: 180

        op: greater-than

      # key is active

      - type: credential

        key: access_keys.active

        value: true

  actions:

    # deactivate the key

    - type: remove-keys

      disable: true

      matched: true
```

### Extra information or context

In the grid output, the CreateDate of the IAM user is listed. It's not clear why this is relevant since the policy should be examining the access key credential report, not the user create date

**Comment by kapilt** [comment]
your looking at c7n:matched-keys.. but its not clear why, all resources in resources.json are those that passed the filter for a particular policy. additionally, your using credential report filters, which have a multi-hour latency to reflect updates from actions https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html "You can generate a credential report as often as once every four hours."

**Comment by jcmcken** [comment]
Apologies, I don't know the internals here. But my observation is that when an access key matches the filters, it shows up in ``c7n:matched-keys``. That's why I mentioned it. This matches the behavior I'm seeing when I run without ``--dryrun`` -- no keys are changed.

Regardless, to your comment about multi-hour latency, no credentials have been modified in at least 12 hours, so the data should be stable (I would assume). Inside ``resources.json``, I can see that no keys match my filters. To give you one example, a user has 2 keys, 1 is inactive, 1 is active -- the active key was last used today. Therefore based on my filters, no keys match (which matches the behavior of ``run`` -- no keys on this user are updated). But yet, this user still shows in the ``report`` output. 

I understand that this might be the expected result. But then I suppose my question/bug turns into a feature request -- how do I list the actual resources that will get updated? In a "principal of least surprise" sense, I assumed ``report`` would show me the actual resources that would be affected. It's fine if that's not the case, but it seems like there should be some command (besides parsing ``resources.json`` by hand) to print out this data for verification purposes.

**Comment by rymancl** [comment]
@kapilt I'm also curious about the `c7n:matched-keys`...

I'm seeing this exact behavior with a normal c7n run (not using `report`). I think it is a bug when the user has two sets of access keys.
Version 0.9.26.0

### Policy

```yaml
policies:
  - name: aws-iam-user-inactive-access-keys
    conditions:
      - region: us-east-1 # global resource
    resource: aws.iam-user
    description: |
      Notifies of and disables IAM access keys found to be unused
    mode:
      type: periodic
      schedule: cron(0, 23, *, *, ?, *) # daily at 23:00 UTC
      role: arn:aws:iam::{account_id}:role/cloud-custodian
      tags: *tags
    filters:
      - type: credential
        key: access_keys.active
        value: true
        op: eq
      - type: credential
        key: access_keys.last_used_date
        value_type: age
        value: 90
        op: gt
    actions:
      - type: remove-keys
        matched: true
        disable: true
      - type: notify
        <<: *slack-notify
```

### resources.json

```json
[
  {
    "Path": "/",
    "UserName": "<redacted>",
    "UserId": "<redacted>",
    "Arn": "arn:aws:iam::<redacted>:user/<redacted>",
    "CreateDate": "2022-08-01T06:03:18+00:00",
    "Tags": [
      {
        "Key": "<redacted>",
        "Value": "<redacted>"
      }
    ],
    "c7n:matched-keys": [],
    "c7n:credential-report": {
      "user": "<redacted>",
      "arn": "arn:aws:iam::<redacted>:user/<redacted>",
      "user_creation_time": "2022-08-01T06:03:18+00:00",
      "password_enabled": false,
      "password_last_used": null,
      "password_last_changed": null,
      "password_next_rotation": null,
      "mfa_active": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2022-09-20T02:35:19+00:00",
          "last_used_date": "2023-05-03T21:07:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "s3"
        },
        {
          "active": false,
          "last_rotated": "2023-01-30T10:07:05+00:00",
          "last_used_date": "2023-01-30T13:49:00+00:00",
          "last_used_region": "us-west-2",
          "last_used_service": "s3",
          "c7n:match-type": "credential"
        }
      ]
    }
  }
]
```

### metadata.json (metrics section)
```json
  "metrics": [
    {
      "MetricName": "ResourceCount",
      "Timestamp": "2023-05-03T23:00:28.976740",
      "Value": 1,
      "Unit": "Count"
    },
```

This triggers a notification every day when the policy runs, despite neither item in `access_keys` matching my filters fully. Nothing in `c7n:matched-keys`. 

![image](https://user-images.githubusercontent.com/3211227/236309594-a403f428-60cf-43fb-ada6-a0dcf1c631cc.png)


If I check CloudTrail for _iam:UpdateAccessKey_ by my cloud-custodian role, there are no events. Makes sense since it isn't doing anything. But why is c7n picking this up as a match?

If I look at historical logs, there is **always** something in `c7n:matched-keys` when this policy runs and properly deactivates a key. Example:
```json
    "c7n:matched-keys": [
      {
        "active": true,
        "last_rotated": "2023-01-30T10:07:05+00:00",
        "last_used_date": "2023-01-30T13:49:00+00:00",
        "last_used_region": "us-west-2",
        "last_used_service": "s3",
        "c7n:match-type": "credential"
      }
    ],
```
Active = true and last used > 90 days = true.

**Comment by rymancl** [comment]
To avoid being spammed every day, I just deleted the one inactive access key for this user. The latest policy run since then shows resources.json as `[]` and the metadata.json count metrics as:
```json
"metrics": [
    {
      "MetricName": "ResourceCount",
      "Timestamp": "2023-05-08T23:00:36.730508",
      "Value": 0,
      "Unit": "Count"
    },
```

**Comment by ilepow34** [comment]
I was able to work around this by using a JMESPath expression to filter on the length of `c7n:matched-keys`

For example:

```
filters:
  - type: credential
    key: access_keys.active
    value: true
    op: eq
  - type: credential
    key: access_keys.last_used_date8
    value: 90
    op: gt
  - type: value
    key: length("c7n:matched-keys")
    value: 1
    op: gte

```
