### ISSUE TITLE
s3-public-block does not work

### ISSUE THREAD

**Issue by jwtdrjj** [cloud-custodian/cloud-custodian#7875]
### Describe the bug

I keep getting this error.  I have even cut and pasted the example for the  code here. https://github.com/cloud-custodian/cloud-custodian/blob/master/c7n/resources/account.py#L1546

I cannot get this to work.   I have re-typed the yaml from scratch.  It appears the actions are empty when it gets to the validate step.    Please do not just mark it closed and say its a yaml problem.  That doesn't help.

It seems to get pasted the filters and required fields just fine. 

```
977 | File "/codebuild/output/src360516657/src/indgcustodian/bin/custodian", line 8, in <module>
978 | sys.exit(main())
979 | File "/codebuild/output/src360516657/src/indgcustodian/lib/python3.9/site-packages/c7n/cli.py", line 363, in main
980 | command(config)
981 | File "/codebuild/output/src360516657/src/indgcustodian/lib/python3.9/site-packages/c7n/commands.py", line 219, in validate
982 | structure.validate(data)
983 | File "/codebuild/output/src360516657/src/indgcustodian/lib/python3.9/site-packages/c7n/structure.py", line 48, in validate
984 | self.validate_policy(p)
985 | File "/codebuild/output/src360516657/src/indgcustodian/lib/python3.9/site-packages/c7n/structure.py", line 78, in validate_policy
986 | for a in p.get('actions', ()):
987 | TypeError: 'NoneType' object is not iterable
```

PublicS3Bucket.yml

`policies:
  - name: s3-block
    comment: "Remediate and notify when accounts are able to create public buckets"
    resource: aws.account
    conditions: 
      - region: us-east-1
    filters:
      - and:
        - "tag:c7n_s3_block_public_bucket_exempt": absent
        - not:
            - type: s3-public-block
              key: RestrictPublicBuckets
              value: true
    actions:
      - type: set-s3-public-block
        RestrictPublicBuckets: true`

### What did you expect to happen?

No error

### Cloud Provider

Amazon Web Services (AWS)

**Comment by PratMis** [comment]
I just test this policy, it works
```
policies:
  - name: restrict-public-buckets
    resource: aws.account
    filters:
      - not:
        - type: s3-public-block
          key: RestrictPublicBuckets
          value: true
    actions:
      - type: set-s3-public-block
        RestrictPublicBuckets: true
```
