### ISSUE TITLE
Filter based on account number and tag

### ISSUE THREAD

**Issue by SteveL1** [cloud-custodian/cloud-custodian#7935]
### Describe the bug

I run the same policies across many accounts but I need to have exceptions coded in the policy.  I need to create a policy that excludes specific tags in specific accounts

the policy i have is 

```

 - not:
     - key: account_id
        op: in
        type: value
        value:
          - 112233445566
          - 223344556677
      - key: tag:Costs
        op: in
        type: value
        value:
        - '1234'

```

So if there's a resource with a 'Costs' tag of 1234 in either account  112233445566 or 223344556677 then the policy doesn't apply.

However this doesn't do what i'm hoping it would do.  Can someone help me out and tell me where i've gone wrong please

### What did you expect to happen?

Exclude defined tag/account_id combinations

### Cloud Provider

Amazon Web Services (AWS)
