### ISSUE TITLE
Secrets Manager - Add delete Secret action

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#8100]
### Describe the feature

I want to be able to delete old secrets that haven't been accessed in over 90 days as a security policy to eliminate risk. There currently is no action for delete but there is a boto3 API for it - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.delete_secret

This would be handy for cleanups

### Extra information or context

```
- name: aws-secrets-delete-unused
  resource: aws.secrets-manager
  description: Deletes Secrets that haven't been accessed in over 90 days.
  filters:
   - type: value
     key: LastAccessedDate
     value_type: age
     op: gt
     value: 90
  actions:
    - type: delete
```
