### ISSUE TITLE
problem with validating policy

### ISSUE THREAD

**Issue by myftiu67** [cloud-custodian/cloud-custodian#8110]
Hi 
I have policy below

```yaml
policies:
  - name: security-group-naming-convention
    resource: aws.security-group
    filters:
      - type: value
        key: GroupName
        value_type: regex
        value: '^(product|environment)-.*'
      - type: value
        key: Description
        value_type: regex
        value: '^(Product|Environment) .*'
    actions:
  - type: notify
    template: default.html
    priority_header: 2
    subject: "All SGs are named after the product/environment they are supporting, with an accurate description."
    violation_desc: "Naming of the SG should have accurate description."
    action_desc: |
        Security group are not correctly named. SGs are named after the product/environment they are supporting. Please update your code. 
    to:
      - resource-owner
    owner_absent_contact:
      - DL-ES-TechOps@...com
    transport:
      type: sns
      region: us-east-1
      topic: arn:aws:sns:us-east-1:765407174376:policy-notification

```

 that is not validating and throwing the error below:

```
(custodian) C:\Dri\Doc\Python\custodian>custodian validate securitygroup_naming.yml
2023-01-03 12:13:26,880: custodian.commands:ERROR Configuration invalid: securitygroup_naming.yml
2023-01-03 12:13:26,880: custodian.commands:ERROR policy missing required keys (name, resource) data:
 {
  "type": "notify",
  "template": "default.html",
  "priority_header": 2,
  "subject": "All SGs are named after the product/environment they are supporting, with an accurate descriptio.",
  "violation_desc": "Naming of the SG should have accurate description",
  "action_desc": "Security group are not correctly named. SGs are named after the product/environment they are supporting. Please update your code.
  "to": [
    "resource-owner"
  ],
  "owner_absent_contact": [
    "DL-ES-TechOps@....com"
  ],
  "transport": {
    "type": "sns",
    "region": "us-east-1",
    "topic": "arn:aws:sns:us-east-1:765407177728:policy-notification"
```

**Comment by thisisshi** [comment]
your actions block needs to be indented, also the `value_type` shouldn't be `regex`, `op` should be.

```yaml
policies:
  - name: security-group-naming-convention
    resource: aws.security-group
    filters:
      - type: value
        key: GroupName
        op: regex
        value: '^(product|environment)-.*'
      - type: value
        key: Description
        op: regex
        value: '^(Product|Environment) .*'
    actions:
      - type: notify
        template: default.html
        priority_header: 2
        subject: "All SGs are named after the product/environment they are supporting, with an accurate description."
        violation_desc: "Naming of the SG should have accurate description."
        action_desc: |
            Security group are not correctly named. SGs are named after the product/environment they are supporting. Please update your code. 
        to:
          - resource-owner
        owner_absent_contact:
          - DL-ES-TechOps@...com
        transport:
          type: sns
          region: us-east-1
          topic: arn:aws:sns:us-east-1:765407174376:policy-notification
```
