### ISSUE TITLE
AWS EMR - Add filter for master-instances

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#8114]
### Describe the feature

As part of a compliance check, I need to verify that EMR Cluster MASTER nodes don't have public IPs set. Currently we cannot see the node (instance) details for EMR clusters but there is a simple API call to list them - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.list_instances
This API call would need to pass in the attribute of InstanceFleetType='MASTER' as our policy needs to check only the master nodes for public IPs that are in the state of "AWAITING_FULFILLMENT" or "RUNNING"

Can you please add a 'master-instances' filter to aws.emr resource which performs the above API call which will return the following instance info:

```
{
    'Instances': [
        {
            'Id': 'string',
            'Ec2InstanceId': 'string',
            'PublicDnsName': 'string',
            'PublicIpAddress': 'string',
            'PrivateDnsName': 'string',
            'PrivateIpAddress': 'string',
            'Status': {
                'State': 'AWAITING_FULFILLMENT'|'PROVISIONING'|'BOOTSTRAPPING'|'RUNNING'|'TERMINATED',
                'StateChangeReason': {
                    'Code': 'INTERNAL_ERROR'|'VALIDATION_ERROR'|'INSTANCE_FAILURE'|'BOOTSTRAP_FAILURE'|'CLUSTER_TERMINATED',
                    'Message': 'string'
                },
                'Timeline': {
                    'CreationDateTime': datetime(2015, 1, 1),
                    'ReadyDateTime': datetime(2015, 1, 1),
                    'EndDateTime': datetime(2015, 1, 1)
                }
            },
            'InstanceGroupId': 'string',
            'InstanceFleetId': 'string',
            'Market': 'ON_DEMAND'|'SPOT',
            'InstanceType': 'string',
            'EbsVolumes': [
                {
                    'Device': 'string',
                    'VolumeId': 'string'
                },
            ]
        },
    ],
    'Marker': 'string'
}
```

### Extra information or context

The policy I would then author for this check would look something like this:

```
- name: aws-emr-nodes-public-ips
  resource: aws.emr
  filters:
    - type: master-instances
      key: PublicIpAddress
      value: present
    - type: master-instances
      key: Status.State
      op: in
      value:
         - AWAITING_FULFILLMENT
         - RUNNING
```

**Comment by ajkerrigan** [comment]
Hmm, I suspect we can target `aws.ec2` instead. As far as I know cluster nodes should have [AWS-managed tags](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-tags.html) like `aws:elasticmapreduce:job-flow-id` so we can add that check to a typical policy that checks for public instances.

**Comment by jtroberts83** [comment]
> Member

Ok that makes sense. How would we determine if an EC2 is in the "AWAITING_FULFILLMENT" status though if just querying EC2?

**Comment by ajkerrigan** [comment]
`AWAITING_FULFILLMENT` means that it's waiting to place/launch instances, in which case we'd expect more instances to launch in the future. That's cool :+1: 

As for filtering by role, we can check to see if the `aws:elasticmapreduce:instance-group-role` tag is set to `MASTER`. It's possible that there's something an instances filter on `aws.emr` could do that we can't do with `aws.ec2`, but so far I think we're covered.

![image](https://user-images.githubusercontent.com/19539955/210888203-db5d9aaf-013c-4557-82d0-896d9368c3f5.png)

**Comment by jtroberts83** [comment]
@ajkerrigan  Thanks I didn't realize the tags indicated the fleet type so that actually should work for this use case. Thanks for the great tips on this! Closing issue as there is a workaround via ec2 filters on EMR tags.

**Comment by jtroberts83** [comment]
Here is the working EC2 policy to check for EMR Master nodes which have a public IP address and are in a running state
```
- name: aws-ec2-emr-master-node-public-ip
  resource: aws.ec2
  filters:
    - 'tag:aws:elasticmapreduce:instance-group-role': "MASTER"
    - "PublicIpAddress": present
    - "State.Name": running
```
