### ISSUE TITLE
AWS Backup - Add Backup Protected Resources

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#8119]
### Describe the feature

I need to see which resource types are being protected by AWS Backups. This is for a compliance policy check. Currently the backup-plan and backup-vault don't have any filters to see which resource types are being protected/auto-backed up by AWS Backup service so this might need to be a seperate resource or a filter built into backup-plan or something. Here is the API to check on what services are protected - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/backup.html#Backup.Client.list_protected_resources

### Extra information or context

Example policy might look something like this to find if EFS is being backed up

```
- name: aws-efs-in-backup-plan
   resource: aws.backup-protected-resources
   filters:
    - "ResourceType": "EFS"
```

**Comment by ajkerrigan** [comment]
This makes sense :+1: . Going to close this issue though and revive #7243 since there's already some history there

**Comment by ajkerrigan** [comment]
After some discussion in and around #7243, it sounds like this issue is trying to ask for something different. #7243 is looking at the resource _types_ assigned to a backup plan as part of its selection (where `get_backup_selection()` is useful). This issue is looking at specific protected resources as reported by the `list_protected_resources()` call.

This might be something we could achieve with a filter, like...

```yaml
- name: aws-efs-in-backup-plan
  resource: aws.efs
  filters:
    - backup-protected
```

Does that sound right or am I still missing something about how this works and how it differs from #7243?

**Comment by thisisshi** [comment]
@jtroberts83 would this be sufficient? https://github.com/cloud-custodian/cloud-custodian/pull/8169

```yaml
policies:
  - name: dynamodb-backups
    resource: aws.dynamodb-table
    filters:
      - type: aws-backups
        op: eq
        value: 0
        value_type: resource_count
```

there's also the `consecutive-aws-backups` filter to check that there are n number of consecutive backups across n hours/
days/weeks/months
