### ISSUE TITLE
AWS Remediatation logs group are encrypted at rest using KMS CMKs

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8138]
### Describe the feature

I am trying to remediate for if encrypt is not set to log group, so it will encrypt log group using KMS CMKs. When I checked aws.kms-key  is not supported to created Customer-managed keys, with policy attached, is there any other way to do this.

**Comment by thisisshi** [comment]
you should be able to check like so:

```
        policies:
            - name: log-group-cmk-managed-key
              resource: aws.log-group
              filters:
                - type: kms-key
                  key: KeyManager
                  value: CUSTOMER
```
