### ISSUE TITLE
AWS SageMaker encryption endpoint configuration should be enabled

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8140]
### Describe the feature

I am able to check verify endpoint-configuration-encryption configuration. 

```
policies:
  - name: sagemaker-endpoint-configuration-encryption
    resource: aws.sagemaker-endpoint-config
    description: "Account {account_id} - SageMaker Endpoint Configuration Encryption Should Be Enabled"
    filters:
        - type: value
          key: KmsKeyId
          value: absent
```

As I am trying to encryption sageMaker endpoint configuration should be enabled but there in actions not supported https://cloudcustodian.io/docs/aws/resources/sagemaker-endpoint.html#actions. Someone help me with this.
