### ISSUE TITLE
AWS SageMaker notebook instance encryption should be enabled

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8141]
### Describe the feature

I am able to check/verify, sagemaker-notebook-encryption using below rule.

```
---
policies:
  - name: a-sagemaker-notebook-encryption
    resource: aws.sagemaker-notebook
    description: Account {account_id} - Sagemaker Notebook Instance Encryption Missing.
    filters:
      - and:
          - KmsKeyId: absent
          - tag:__Exception-SagemakerNotebookEncryption: absent
```

As I am trying to encryption sageMaker Notebook Instance, it should be enabled but there in actions not supported, https://cloudcustodian.io/docs/aws/resources/sagemaker-notebook.html#actions Someone help me with this.
