### ISSUE TITLE
AWS SageMaker Notebook Instances Options for disabled DirectInternetAccess in actions

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8142]
### Describe the feature

As I am trying to disable  DirectInternetAccess for sagemaker notebook instance but there in actions not supported, https://cloudcustodian.io/docs/aws/resources/sagemaker-notebook.html#actions Someone help me with this.

**Comment by thisisshi** [comment]
Hi @pareshcc you can't remove direct internet access on a sagemaker notebook instance after the fact, your only options are to stop and delete the notebook instances. You can detect the creation of notebook instances with the cloudtrail mode though:

```yaml
policies:
  - name: sagemaker-notebook-instance-direct-internet-detect
    resource: aws.sagemaker-notebook
    mode:
      type: cloudtrail
      events:
        - source: sagemaker.amazonaws.com
          ids: ResponseParameters.NotebookInstanceArn
          event: CreateNotebookInstance
    filters:
      - DirectInternetAccess: 'Enabled'
    actions:
      - type: delete
```
