### ISSUE TITLE
AWS Backtrack feature is enabled for your Amazon Aurora rds-cluster

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8145]
### Describe the feature

I want to ensure that backtrack feature is enabled for your Amazon Aurora with MySQL compatibility database clusters in order to backtrack your clusters to a specific time, without using backups.

**Comment by thisisshi** [comment]
if this is a filter you can check using the `BacktrackWindow` key and the value filter. To enable backtrack you should be able to do:

```yaml
        policies:
          - name: modify-backtrack-window-to-72-hours
            resource: rds-cluster
            filters:
              - BacktrackWindow: 0
            actions:
              - type: modify-db-cluster
                attributes:
                    BacktrackWindow: 259200
```
