### ISSUE TITLE
AWS Lambda functions should prohibit public access

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8147]
### Describe the feature

I want to check and remediate, Lambda functions should prohibit public access 

**Check and Remediation:** Need to flow below steps, Can I be able to do using cloud-custodian?

To remediate this issue, you update the resource-based policy to change the publicly accessible Lambda function to a private Lambda function.

To use the AWS CLI to revoke function-use permission from an AWS service or another account

To get the ID of the statement from the output of GetPolicy, from the AWS CLI, run the following:
`aws lambda get-policy —function-name yourfunctionname`
This command returns the Lambda resource-based policy string associated with the publicly accessible Lambda function.

From the policy statement returned by the get-policy command, copy the string value of the Sid field.

From the AWS CLI, run

`aws lambda remove-permission --function-name yourfunctionname —statement-id youridvalue`
To use the Lambda console to restrict access to the Lambda function

Open the [AWS Lambda console](https://console.aws.amazon.com/lambda/).

Navigate to functions and then select your publicly accessible Lambda function.

Under Designer, choose the key icon at the top left. It has the tool-tip View permissions.

Under Function policy, if the policy allows actions for the principal element “*” or {“AWS”: “*”}, it is publicly accessible.

Consider adding the following IAM condition to scope access to your account only.
```

    "Condition": {
  "StringEquals": {
    "AWS:SourceAccount": "<account_id>"
    }
  }
}

```

**Comment by thisisshi** [comment]
you should be able to use the `remove-statements` action:

```yaml
        policies:
          - name: lambda-remove-cross-accounts
            resource: lambda
            filters:
              - type: cross-account
            actions:
              - type: remove-statements
                statement_ids: matched
```
