### ISSUE TITLE
AWS Redshift cluster Need options for enabled encryption in transit

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8149]
### Describe the feature

I want to enabled redshift cluster encryption in transit, I can able to check using below policy but not able to remediate, can someone help me in this.

```
policies:
  - name: redshift-no-ssl
    resource: redshift
    filters:
      - type: param
        key: require_ssl
        value: false
        op: eq
```
