### ISSUE TITLE
 AWs S3 MFA Delete is enabled on S3 buckets

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8164]
### Describe the feature

I want to configure s3 MFA Delete is enabled on S3 buckets, can you guys help me

**Comment by thisisshi** [comment]
You can check if mfa is enabled like so;

```yaml
policies:
  - name: s3-mfa
    resource: s3
    filters:
      - not:
        - Versioning.MFADelete: 'Enabled'
```

You can't enable mfa unless you're using root account credentials which isn't something we're likely to support in custodian
