### ISSUE TITLE
Be able to delete launch template

### ISSUE THREAD

**Issue by farrukh90** [cloud-custodian/cloud-custodian#8202]
### Describe the feature

As you can see below code finds all launch templates 

```
policies:
  - name: old-launch-templates
    resource: aws.launch-template-version
    filters:
      - type: value
        key: CreateTime
        value_type: age
        op: greater-than
        value: 30
      - DefaultVersion: true
    actions:
    - delete
```

However, "delete" action is not working. Is there anyway we could include that? We have a lot of launch templates , but we cant seem to clean them up 

### Extra information or context

n/a

**Comment by kapilt** [comment]
what happens when you run?  ie. cli output with --verbose, this resource is targeting individual versions, if you remove the default filter (which narrows it to a single one). ie its a bit unclear given the policy and the phrasing ("find all", "not working", "clean up") what the goal or issue is. if you want to delete all versions of launch templates older than 30 days, then remove default. generally you also want to validate their not in use as autoscaling groups utilizing can spin (weakly ref'd to version) trying to spin up instances.

**Comment by farrukh90** [comment]
Hi, 
I just want to delete any launch template, or any version of a launch template that is older than 30 days. I was looking for something like this 

```
policies:
  - name: old-launch-templates
    resource: aws.launch-template
    actions:
    - delete
    - 
    ```
I am looking to delete them. As you can see above, I am trying to find 
```
    resource: aws.launch-template
```

Not just the version. Is that possible? Can I remove it
