### ISSUE TITLE
Add support for custom headers in the value_from filter

### ISSUE THREAD

**Issue by SaMnCo** [cloud-custodian/cloud-custodian#8212]
### Describe the feature

The design of the value_from filter lets it load from any open HTTP, HTTPS or S3 URL, provided there is no headers required. 

The goal of the feature request is to allow the use of APIs that are protected by an API Key or require specific headers. 

The value_from filter could look like: 

```
value_from:
    url: https://my.api.com
    headers:
        Authorization: Token
        otherheader: foobar
     format: json
     expr: jmespath_thingy
```

which would result in the headers passed via Request after being combined with the default gzip headers required by C7n, thus allowing to query protected endpoints.

**Comment by thisisshi** [comment]
maybe we can do a env lookup instead? e.g.

```yaml
value_from:
    url: https://my.api.com
    headers:
        Authorization: env:MY_TOKEN
        otherheader: foobar
     format: json
     expr: jmespath_thingy
```
