### ISSUE TITLE
Security groups: Port filtering doesn't filter out "ALL-traffic" conditions 

### ISSUE THREAD

**Issue by khaledfarah** [cloud-custodian/cloud-custodian#8224]
### Describe the bug

I have this policy: 
```
policies:
    - name: security-groups-remediate-ssh
      resource: security-group
      filters:
        - and:
            - type: ingress
              Ports: [22]
              Cidr:
                value: "0.0.0.0/0"
```

As per the [docs](https://cloudcustodian.io/docs/aws/resources/security-group.html), this should *only* return security groups with port 22 open to `0.0.0.0/0`. But in reality, It returns security groups with all ports open as well. 

### What did you expect to happen?

 *only* return security groups with port 22 open to `0.0.0.0/0`.

### Cloud Provider

Amazon Web Services (AWS)
