### ISSUE TITLE
FR: Generic HTTP filter

### ISSUE THREAD

**Issue by myoung34** [cloud-custodian/cloud-custodian#8238]
### Describe the feature

We interact with an API and have a need to run checks. 

Take this example scenario: 

"We want to find out when /alertRules at .items[].lastRunAt is > 2 days ago if the .enabled is true" ie: do something when an active alertRule hasnt run so we can dig in or raise an alarm

Heres what the curl code would look like 
```bash
✗ curl -s -X 'GET' -H 'Content-Type: application/json' \
  'https://redact/tagRules' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer redact' | jq '.items[] | select(.enabled == true) | .lastRunAt'

null
"2023-02-02T19:28:17.297Z"
"2023-02-02T19:34:59.388Z"
"2023-02-02T19:00:00.483Z"
"2023-02-02T19:00:11.111Z"
null

✗ #now is where id alert on null or the DT being > 2 days ago in bash 
```

This would make a good use-case for cloud-custodian without having to build up an entire provider in python (we already maintain a golang client and have no desire to do fork any logic to python and repeat ourselves/edge cases

Id expect that if we allowed a `python.requests` provider we could do:

```yaml
policies:
  - name: tag-rule-not-fired
    resource: http.requests
    mode:
       type: requests.get
       host: https://redact
       path: /tagRules
       headers:
          - 'Authorization: Bearer redact'
          - 'accept: application/json'
          - 'Content-Type: application/json'
       object: '.items[]'
    filters:
      - enabled: true
      - type: value
        key: lastRunAt
        op: less-than
        value_type: age
        value: 2
    actions:
       ...
```
