### ISSUE TITLE
GCP Instance - Add filter for gcp.disk (similar to aws.ec2 and the ebs filter)

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#8261]
### Describe the feature

I need to be able to check all gcp.instance resources to verify their attached disks are encrypted with the proper keys. In order to do this I first need to get a listing of the disks for each gcp.instance and then you have to query each disk to get the encryption info. Adding the disk filter to the gcp.instance would allow us to check if each instance is using properly encrypted disks.

### Extra information or context

Policy might look like this:
```
- name: gcp-instance-disk-default-encryption
  resource: gcp.instance
  filters:
    - type: disk
      key: diskEncryptionKey
      value: empty
 ```
