### ISSUE TITLE
unused filter needed for sns-subscription resource

### ISSUE THREAD

**Issue by stepkirk** [cloud-custodian/cloud-custodian#8316]
### Describe the feature

We just deployed a c7n policy to delete unused sns-topic resources. We are now looking for something similar to clean up the dangling/unused sns-subscriptions left behind. 

It doesn't look like there is an **unused** filter for the sns-subscription resource. Could it be added? 

The **delete** action is already available so we are almost there.

### Extra information or context

policy might look something like this:

```
policies:
  - name: sns-subscription-delete-unused
    description: |
      Delete unused SNS Subscriptions
    resource: sns-subscription
    filters:
      - unused
    actions:
      - delete
```
