### ISSUE TITLE
Generic related resource filter

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#8344]
### Describe the feature

We've got a number of related resource style filters (example: the `aws.ebs` [`volume`](https://github.com/cloud-custodian/cloud-custodian/blob/a9d1aaf709375fd2838e62381c65a1382c260a95/c7n/resources/ebs.py#L368-L397) filter) which specify:

- A related resource type
- An expression to pull related resource IDs from the primary resource
- An annotation key

And perform value filter logic against the results. In the simple case where we can avoid special handling of edge cases (or defer that handling to separate filters), I'm wondering if it'd be valuable to have a generic `related-resource` filter. Rather than ad-hoc PRs like #8336 for example, we might support syntax like:

```yaml
- name: sns-subscription-topic
  resource: aws.sns-subscription
  filters:
    - type: related
      resource: aws.sns
      ids: TopicArn
      annotation: Topic
      value: absent
```

We'd be putting the onus on the policy author to consider edge cases (like cross-account subscriptions in this example), but on the plus side we'd be giving them the power to evaluate resource relationships that we haven't explicitly codified.
