### ISSUE TITLE
c7n-left policy testing

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cloud-custodian#8368]
since c7n-left is primarily client side, we can effectively build a policy testing tool that operates entirely client side for the purposes of evaluationing a policy.

perhaps as a pytest-plugin, that we can front end with c7n-left or just something more bespoke via `c7n-left test policy_dir test_dir`

**Comment by kapilt** [comment]
okay, noodling through on this, here's a straw proposal to get conversations started.

`c7n-left test -p policy-dir`

will default to looking for `tests` in the the policy-dir or explicit passed via separate flag. the test dir will have a separate directory for each policy by policy name. within the directory, we can have multiple terraform files or additional modules/dirs, and a left.test.json or left.test.yaml which contains a pattern match syntax for validating results.

filling in the blanks we might have
```
tests/
    policy-name/
        postive.tf
        positive2.tf
        negative.tf
        negative-some-case.tf
        left.test.yaml
```

the only hardcode file name is `left.test[yaml|json]`. when we go to run this, we get no results on any the files with positive prefix, the negative prefixes should have results. left.test.yaml uses a matching syntax for this purpose. its basically a custodian filter, any file specified must have a match (ie failure can't go silent). 

```yaml
version: 1
negative.tf:
   - resource.__tfmeta: 
        filename": "ec2.tf"
        label: "aws_instance"
        line_end: 42                    
        line_start: 35
        path: "aws_instance.foo"
```


    

given a policy dir, we should infer
