### ISSUE TITLE
Access Key Groupings

### ISSUE THREAD

**Issue by dykemasarah** [cloud-custodian/cloud-custodian#842]
If an IAM account has never been used the "access_keys.last_used_date" will be absent.  I want to disable access keys that have never been used AND the last rotated key is greater than 60 days.  Neither one of the access keys of the IAM account "read-s3" (see below) should violate this policy.  This seems to only happen when two access keys are active.

**Policy should match an access key with the following:**
- Key Active: YES
- Never Been Used: YES
- Access Key Rotated Greater Than 60 Days: YES

**The incorrect access keys that match from the following policy:**
**_"read-s3" Access Key 1:_**
- Key Active: YES
- Never Been Used: YES
- Access Key Rotated Greater Than 60 Days: NO

**_"read-s3" Access Key 2:_**
- Key Active: YES
- Never Been Used: NO
- Access Key Rotated Greater Than 60 Days: YES

I am wondering if it is grouping the access keys (similar to the old bug in the security groups) and pulling and evaluating dates/null values from multiple access keys.

**Policy:**
```
    name: iam_accounts-disable-never_used
    description: |
       Disable IAM accounts that have never been used in the last 60 days
    resource: iam-user
    filters:
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 60
        op: gte
    actions:
      - type: remove-keys
        age: 60
        disable: true
```

**Resources File:**
```
[
  {
    "UserName": "read-s3",
    "c7n:credential-report": {
      "password_next_rotation": null,
      "password_enabled": false,
      "access_keys": [
        {
          "active": true,
          "last_rotated": "2016-12-23T15:55:44+00:00",
          "last_used_date": null,
          "last_used_service": null,
          "last_used_region": null
        },
        {
          "active": true,
          "last_rotated": "2016-09-26T18:39:07+00:00",
          "last_used_region": null,
          "last_used_date": "2017-01-09T23:21:00+00:00",
          "last_used_service": "s3"
        }
      ],
      "user_creation_time": "2016-09-26T18:39:07+00:00",
      "mfa_active": false,
      "arn": "arn:aws:iam::xxxxxxx:user/read-s3",
      "password_last_used": null,
      "password_last_changed": null,
      "user": "security-read-s3"
    },
    "CreateDate": "2016-09-26T18:39:07+00:00",
    "UserId": "xxxxx",
    "Path": "/",
    "Arn": "arn:aws:iam::xxxxxxxx:user/read-s3"
  }
]
```

**Comment by jdubs** [comment]
I'm also having these issues.

**Comment by dykemasarah** [comment]
The issue still persists.  I had an IAM account with two access keys.  I have a specific policy to remove keys after 60 days if never used.  However, when two access keys are active and one has "never been used" and the other has been active for more than 60 days, both keys have an action executed - not just the key with the violation.
`
"access_keys": [
{
"active": true, 
**"last_rotated": "2017-10-03T22:19:40+00:00",** 
"last_used_date": null, 
"last_used_service": null, 
"last_used_region": null
}, 
{
"active": true, 
**"last_rotated": "2017-07-11T19:23:21+00:00",** 
"last_used_region": "us-east-1", 
"last_used_date": "2017-10-03T22:19:00+00:00", 
"last_used_service": "iam"
}
`
`
policy:
  - name: iam_accounts-action-disable-never_used
    description: |
       Disabling IAM accounts that have has not been used
    resource: iam-user
    filters:
      - type: credential
        key: user
        value: *whitelisted_users
        op: not-in
      - type: credential
        key: access_keys.active
        value: true
      - type: credential
        key: access_keys.last_used_date
        value: absent
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 60
        op: gte
      - and:
        - type: credential
          key: access_keys.last_rotated
          value_type: age
          value: 90
          op: lt
    actions:
      - type: remove-keys
        disable: true
`

**Comment by zfLQ2qx2** [comment]
@dykemasarah @kapilt I can confirm that as of 2018-04-30 this is still an issue - when you make a user's keys inactive it impacts both keys, not just the ones that matched the policy criteria. I also opened https://github.com/capitalone/cloud-custodian/issues/2302 because c7n_mailer outputs a list of users who have keys that matched the criteria - accesskeyid isn't passed in the resources so you can't be specific about which keys were impacted (assuming that the first issue was fixed).

**Comment by mateusz** [comment]
Same here - makes it hard to validate/act on AWS CIS Foundations Benchmark 1.3 an 1.4 if you don't want to mess people's others credentials, or want to exclude "Disabled" keys from the policy.

Amazon provides `access_key_1_last_rotated` and `access_key_2_last_rotated` as part of the credentials report. Would be nice if these were exposed as indexed fields so I could get around that problem:

```
    filters:
      - type: credential
        key: access_key1.last_rotated
        value_type: age
        value: 90
        op: greater-than
      - type: credential
        key: access_key1.active
        value: true

# and then second policy covering access_key2.
```

This would work because you can't have more than 2 access keys per account.

**Comment by ebickle** [comment]
I've run into this issue with the type: credential and type: security-group filters all over the place. Cloud Custodian's support for matching on correlated child resources is limited at best.

One potential solution here might be to have a separate resource for access keys. For example, "aws.iam-access-key". There is already a ListAccessKeys API, so it would make some degree of sense to treat them as a separate resource even if they're pulled from the credential report:

```
resource: iam-access-key
filters:
- type: value
  key: active
  value: true
- type: value
   key: last_used_date
   value: 90
   value_type: age
   op: lte
actions:
  - type: disable
```
