### ISSUE TITLE
using has-statement filter to match s3 bucket policy actions doesn't yield desired results

### ISSUE THREAD

**Issue by erdemds** [cloud-custodian/cloud-custodian#8442]
### Describe the bug

I am trying to find a match where an S3 bucket policy has specific actions.

This is the C7N policy:

```
policies:
  - name: s3-test
    resource: s3
    filters:
      - type: has-statement
        statements:
          - Effect: Allow
            Principal: "*"
            Action: ["s3:PutObject","s3:PutObjectAcl"]
```

The S3 bucket policy I am running against:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "statement1",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObjectAcl",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::mytestbucket/*"
        }
    ]
}
```

The policy doesn't find any match unless I swap the list of actions. It seems the order of actions in the C7N policy matters.

The other difficulty I am having is using wildcard doesn't work. The policy below doesn't return any match in C7N.

Use case 1:

```
policies:
  - name: s3-test
    resource: s3
    filters:
      - type: has-statement
        statements:
          - Effect: Allow
            Principal: "*"
            Action: "s3:PutObject"
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "statement1",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:Put*",
            "Resource": "arn:aws:s3:::mytestbucket/*"
        }
    ]
}
```

Use Case 2:

```
policies:
  - name: s3-test
    resource: s3
    filters:
      - type: has-statement
        statements:
          - Effect: Allow
            Principal: "*"
            Action: "s3:Put*"
```

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "statement1",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::mytestbucket/*"
        }
    ]
}
```

The order issue seems to be a bug. The wildcard feature would be necessary since there are many variations of actions. 

Is there another way to match s3 bucket policy actions?

### What did you expect to happen?

A list of actions in the C7N policy finds a match only when the actions are in the exact order in the s3 bucket policy.
Moreover, when it checks against actions, it does a string match without wildcard feature which is not desired as bucket policies support wildcards.

### Cloud Provider

Amazon Web Services (AWS)
