### ISSUE TITLE
onhour should not be required

### ISSUE THREAD

**Issue by amphibithen** [cloud-custodian/cloud-custodian#847]
i don't understand why 'onhour' is required here.  no matter what the number is for onhour, it goes off of the schedule mentioned in the tag.  so onhour is irrelevant and misleading.

```
Failed validating 'required' in schema[11]:
    {'additionalProperties': False,
     'properties': {'debug': {'type': 'boolean'},
                    'default_tz': {'type': 'string'},
                    'onhour': {'maximum': 24,
                               'minimum': 0,
                               'type': 'integer'},
                    'opt-out': {'type': 'boolean'},
                    'tag': {'type': 'string'},
                    'type': {'enum': ['onhour']},
                    'weekends': {'type': 'boolean'},
                    'weekends-only': {'type': 'boolean'}},
     'required': ['onhour', 'default_tz', 'type'],
     'type': 'object'}
```

policy file i am trying to do is below.  it was intended to look at the 'Offhours" tag, pull the on/off/tz, and then act on that, and this job would run periodically (every hour, for example) to determine which nodes to turn on
```
policies:

  - name: ec2-offhours-start
    resource: ec2
    description:
      apply onhours to ec2 in opt-in mode
    filters:
      - type: onhour
        tag: Offhours
    actions:
      - start
```
