### ISSUE TITLE
aws.dynamodb - Add deletion-protection-enabled action

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#8531]
### Describe the feature

I'd like to take advantage of enabling deletion protection for DynamoDBs

Perhaps this would be built into the [`update` action](https://cloudcustodian.io/docs/aws/resources/dynamodb-table.html#update) ?

e.g.

```yaml
policies:
  - name: dynamodb-set-deletion-protection
    resource: aws.dynamodb-table
    actions:
      - type: update
        DeletionProtectionEnabled: true
```

Code reference to `update` action's schema

https://github.com/cloud-custodian/cloud-custodian/blob/7be74ff24fe0a06463eb60cd9c1023b11e6710df/c7n/resources/dynamodb.py#L183-L189

Code reference to `update` action's method of passing in params directly to `update_item`

https://github.com/cloud-custodian/cloud-custodian/blob/7be74ff24fe0a06463eb60cd9c1023b11e6710df/c7n/resources/dynamodb.py#L200-L202

Could be as simple as updating the schema here and adding a test

### Extra information or context

- https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-dynamodb-table-deletion-protection/
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/update_table.html
- https://docs.aws.amazon.com/cli/latest/reference/dynamodb/update-table.html
- Related PR for adding the delete action to dynamodb https://github.com/cloud-custodian/cloud-custodian/pull/773/files
- Related PR for adding deletion protection support https://github.com/cloud-custodian/cloud-custodian/issues/3693
