### ISSUE TITLE
Lambda to S3 client authentication issue in AWS GovCloud

### ISSUE THREAD

**Issue by circa10a** [cloud-custodian/cloud-custodian#8547]
### Describe the bug

Provisioned a cloud custodian lambda in the `us-gov-west-1` govcloud region to place lifecycle rules on buckets when a bucket delete event is triggered via cloudwatch and receive the following error at runtime:

```
An error occurred (InvalidToken) when calling the PutBucketLifecycleConfiguration operation: The provided token is malformed or otherwise invalid.
```

### What did you expect to happen?

I expected the lifecycle rule to be placed on the bucket without an error.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
0.9.26
```

### Policy

```yaml
policies:
  - name: add-lifecycle-policy-on-bucket-delete
    resource: s3
    mode:
      type: cloudtrail
      role: cloud-custodian-role
      execution-options:
        log_group: cloud-custodian
      events:
        - source: s3.amazonaws.com
          event: DeleteBucket
          ids: 'requestParameters.bucketName'
      # Default behavior bails early due to the error code of BucketNotEmpty being present.
      environment:
        Variables:
          C7N_SKIP_ERR_EVENT: 'no'
    actions:
      - type: configure-lifecycle
        rules:
          - ID: empty-bucket
            Status: Enabled
            Filter:
              Prefix: ''
            Expiration:
              Days: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
```

### Relevant log/traceback output

```shell
2023-05-09 18:58:30,601 - ERROR - custodian.actions - error modifying bucket lifecycle: some-bucket
An error occurred (InvalidToken) when calling the PutBucketLifecycleConfiguration operation: The provided token is malformed or otherwise invalid.
```

### Extra information or context

Custodian `config.json`:

```json
{
  "execution-options": {},
  "policies": [
    {
      "name": "add-lifecycle-policy-on-bucket-delete",
      "resource": "s3",
      "region": "us-gov-west-1",
      "mode": {
        "type": "cloudtrail",
        "role": "arn:aws-us-gov:iam::*********:role/cloud-custodian-role",
        "execution-options": {
          "log_group": "cloud-custodian"
        },
        "events": [
          {
            "source": "s3.amazonaws.com",
            "event": "DeleteBucket",
            "ids": "requestParameters.bucketName"
          }
        ],
        "environment": {
          "Variables": {
            "C7N_SKIP_ERR_EVENT": "no"
          }
        },
        "tags": {
          "custodian-info": "mode=cloudtrail:version=0.9.26"
        }
      },
      "actions": [
        {
          "type": "configure-lifecycle",
          "rules": [
            {
              "ID": "empty-bucket",
              "Status": "Enabled",
              "Filter": {
                "Prefix": ""
              },
              "Expiration": {
                "Days": 1
              },
              "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1
              },
              "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 1
              }
            }
          ]
        }
      ]
    }
  ]
}
```
