### ISSUE TITLE
Add support for Compute Optimizer

### ISSUE THREAD

**Issue by sean-zou** [cloud-custodian/cloud-custodian#8653]
### Describe the feature

It would be great if we could use custodian to present optimization opportunities to slack for example

**Comment by calebsyring** [comment]
@ajkerrigan could you clarify what's in mind here and perhaps supply an example policy?

There are several endpoints/resources related to Compute Optimizer: https://docs.aws.amazon.com/compute-optimizer/latest/APIReference/API_Operations_AWS_Compute_Optimizer.html

It's possible we could utilize [GetRecommendationSummaries](https://docs.aws.amazon.com/compute-optimizer/latest/APIReference/API_GetRecommendationSummaries.html) to minimize complexity, but it all depends on the desired use case.

**Comment by ajkerrigan** [comment]
The summary call you mentioned might be useful as an account filter. But the sentiment I've heard from folks who want this is to pick up compute optimizer specific recommendations that wouldn't already be covered by the existing [cost-optimization filter](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#cost-optimization). Using the EC2-specific [get_ec2_instance_recommendations()](https://docs.aws.amazon.com/compute-optimizer/latest/APIReference/API_GetEC2InstanceRecommendations.html) as an example might lead to policies like:

```yaml
policies:
  - name: ec2-optimizations
    resource: aws.ec2
    filters:
      - type: compute-optimizer

  - name: ec2-non-optimized-instances-client-side-filter
    resource: aws.ec2
    filters:
      - type: compute-optimizer
        key: finding
        op: not-equal
        value: OPTIMIZED

  - name: ec2-non-optimized-instances-server-side-filter
    resource: aws.ec2
    filters:
      - type: compute-optimizer
        filters:
          Finding: [Underprovisioned, Overprovisioned]

  - name: ec2-graviton-recommendations
    resource: aws.ec2
    filters:
      - type: compute-optimizer
        recommendation-preferences:
          cpuVendorArchitectures: [AWS_ARM64]
```

EC2 seems like the best starting point, but follow-ups could target other resource-specific recommendations. In this somewhat arbitrary order:

- RDS
- ECS
- Lambda
- AutoScaling Groups
