### ISSUE TITLE
execution-options in cloudtrail mode strips off leading slash in cloudwatch log_group name

### ISSUE THREAD

**Issue by harishachappa** [cloud-custodian/cloud-custodian#8685]
### Describe the bug

I have a cloudtrail mode policy to enforce wafv2 for api gateway resource. 

```yaml
 -  name: sample-periodic-policy
    mode:
      timeout: 200
      type: cloudtrail
      events:
        - source: apigateway.amazonaws.com
          ids: responseElements.deploymentId
          event: CreateStage
        - source: apigateway.amazonaws.com
          ids: responseElements.deploymentId
          event: UpdateStage
      role: arn:aws:iam::012345678912:role/c7n_master
      member-role: arn:aws:iam::987654321098:role/<<<spoke_role>>>
      execution-options:
        metrics_enabled: true
        log_group: /cloud-custodian/mode_cloudtrail/us-east-1
        output_dir: s3://my-awesome-bucket/logs/mode_cloudtrail/us-east-1
    resource: rest-stage
    filters:
      - type: wafv2-enabled
        state: false
    actions:
      - type: set-wafv2
        state: true
        web-acl: my_awesome_acl
```
I see the below log messages in lambda cloud watch log_group.

```
[DEBUG]	2023-06-27T21:11:13.671Z	27e39697-e3cf-4c95-b2ff-87bb81e5c6	Storing output with <CloudWatchLogOutput to group:/cloud-custodian/mode_cloudtrail/us-east-1 stream:sample-periodic-policy>
[DEBUG]	2023-06-27T21:11:16.453Z	27e39697-e3cf-4c95-b2ff-87bb81e5c6f0	Storing output with <LogFile file:///tmp/tmpcqeih0so/custodian-run.log>
```

However the LogGroup name created in target AWS account is `cloud-custodian/mode_cloudtrail/us-east-1` and not `/cloud-custodian/mode_cloudtrail/us-east-1`

I think this line https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/resources/aws.py#L429 is stripping '/' from log_group name

### What did you expect to happen?

I expected log_group to be created with same name as I provided in execution-options

Expecting log_group name as `/cloud-custodian/mode_cloudtrail/us-east-1`

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.27
Python:      3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Platform:   win32
Using venv:  False
Docker: False
Installed:

argcomplete==3.0.8
attrs==23.1.0
boto3==1.26.139
botocore==1.29.139
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.17.3
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.1
six==1.16.0
tabulate==0.9.0
typing-extensions==4.5.0
urllib3==1.26.16
zipp==3.15.0
```

### Policy

```shell
-  name: sample-periodic-policy
    mode:
      timeout: 200
      type: cloudtrail
      events:
        - source: apigateway.amazonaws.com
          ids: responseElements.deploymentId
          event: CreateStage
        - source: apigateway.amazonaws.com
          ids: responseElements.deploymentId
          event: UpdateStage
      role: arn:aws:iam::012345678912:role/c7n_master
      member-role: arn:aws:iam::987654321098:role/<<<spoke_role>>>
      execution-options:
        metrics_enabled: true
        log_group: /cloud-custodian/mode_cloudtrail/us-east-1
        output_dir: s3://my-awesome-bucket/logs/mode_cloudtrail/us-east-1
    resource: rest-stage
    filters:
      - type: wafv2-enabled
        state: false
    actions:
      - type: set-wafv2
        state: true
        web-acl: my_awesome_acl
```
