### ISSUE TITLE
Function works locally but not in GCP

### ISSUE THREAD

**Issue by farrukh90** [cloud-custodian/cloud-custodian#8710]
### Describe the bug

The following code works locally to delete the clusters 3hrs old. However when mode is added it is failing and not executing 
```
policies:
  - name: gcp-delete-testing-gke-clusters
    resource: gcp.gke-cluster
    # mode:
    #   type: gcp-periodic
    #   schedule: "every 30 mins"
    filters:
      - and:
        - type: value
          key: name
          op: regex
          value: "lab-cluster-1"   
        - type: value
          key: createTime
          value_type: age
          value: .125       #### 3 hours (1 being 1 day. (1 day / 24 hours) * 3 hours )
          op: gte
    actions:
      - type: delete

```

### What did you expect to happen?

What might be going wrong? Am I using the wrong policy 

### Cloud Provider

Google Cloud (GCP)
