### ISSUE TITLE
Cancel having an AMI shared with your AWS account

### ISSUE THREAD

**Issue by stepkirk** [cloud-custodian/cloud-custodian#8716]
### Describe the feature

We have a workflow where AMIs are created in one account and then shared to one or more accounts for use.
We are looking for a way to clean up these old AMIs when no longer in use.

We have a policy that let's us deregister AMIs and delete their associated snapshots in the account that created/shared the AMI:

```
- name: ami-deregister-old-not-shared-not-used
    description: |
      Deregister AMIs that are old, NOT shared to other accounts and NOT in-use
    resource: ami
    filters:
      - and:
        - type: image-age
          op: ge
          days: 365
        - not:
          - cross-account
        - unused
        - or:
          - type: image-attribute
            attribute: lastLaunchedTime
            key: "Value"
            value_type: age
            op: gte
            value: 90
          - type: image-attribute
            attribute: lastLaunchedTime
            key: "Value"
            value: null
    actions:
      - type: deregister
        delete-snapshots: true
```

Now we need a policy that we can run in the accounts that AMIs are shared TO. The policy would only consider AMIs that are shared to this account and NOT owned by this account. It would check for similar things like, not used, not launched in X days, etc. It doesn't look like the aws.ami resource will allow me to act on AMIs that are shared with me but not owned by me.
Shared with me is the equivalent to the output of this CLI command: 
```aws ec2 describe-images --executable-users self```

Assuming I COULD filter on shared-with-me AMIs, the action would be equivalent to this CLI command: 
```aws ec2 cancel-image-launch-permission```

The policy might look something like this:

```
- name: ami-cancel-old-shared-with-me-not-used
    description: |
      Cancel launch permissions for AMIs that are old, shared with me and NOT in-use
    resource: ami
    filters:
      - and:
        - type: image-age
          op: ge
          days: 365
        - shared-with-me    <--- missing filter?
        - unused
        - or:
          - type: image-attribute
            attribute: lastLaunchedTime
            key: "Value"
            value_type: age
            op: gte
            value: 90
          - type: image-attribute
            attribute: lastLaunchedTime
            key: "Value"
            value: null
    actions:
      - cancel-launch-permission   <--- missing action?
```

Hopefully that makes sense.

**Comment by kapilt** [comment]
interesting, we could support this via a server side filter (query block in a policy), via executable-user, it looks like the self  value only includes explicitly shared Amis to the account versus all public. I assume thats inclusive of organization level grants.

**Comment by ajkerrigan** [comment]
Yeah this is an interesting idea. I think you're right about the missing action, which does sound useful to have for yanking permissions from the recipient perspective rather than the owner. But for looking at "AMIs shared with me", this may be helpful:

```yaml
policies:
  - name: amis-shared-with-me
    resource: aws.ami
    query:
      - ExecutableUsers: [self]
      - Owners: []
```

An empty list for `Owners` prevents us from automatically filtering for AMIs you own. You're going to see some Amazon-owned AMIs in the results here, but it's not clear that we can avoid that without providing an explicit list of account IDs for `Owners` which is probably more tedious than useful.
