### ISSUE TITLE
RDS `resize` action fails on RDS instances with provisioned IOPS

### ISSUE THREAD

**Issue by ajkerrigan** [cloud-custodian/cloud-custodian#8725]
### Describe the bug

From [Slack](https://cloud-custodian.slack.com/archives/CAL4P6YE6/p1689209705404479):

> Dry run gives one rds correctly. But in non dry run mode it gives below error.

```yaml
policies:
  - name: rds-resize-down
    resource: rds
    filters:
      - type: metrics
        name: FreeStorageSpace
        percent-attr: AllocatedStorage
        attr-multiplier: 1073741824
        value: 90
        op: greater-than
      - DBInstanceIdentifier: test-rds-mysql
    actions:
      - type: resize
        percent: -30
        immediate: true
```

```console
Invalid request: An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops.
```

### What did you expect to happen?

The `resize` action should have some iops-awareness, perhaps:
- Allow the policy to specify iops, or...
- If an instance has a provisioned IOPS value, pass it into the modify call

Implicitly keeping IOPS as-is is _probably_ the simplest way to avoid this bug, and it's not clear that it would be useful to allow fixed or scaling-percentage adjustments at the policy level anyway :thinking: 

### Cloud Provider

Amazon Web Services (AWS)

**Comment by nikunj-badjatya** [comment]
Thank you for filing this issue.
Also, even if the underlying instance does not have IOPS enabled, the policy still fails 

```
policies:
  - name: rds-resize-down
    resource: rds
    filters:
      - DBInstanceIdentifier: rds-mysql
    actions:
      - type: resize
        percent: -30
        immediate: true
```

Dry run:
```
[
  {
    "DBInstanceIdentifier": "rds-mysql",
    "DBInstanceClass": "db.t3.micro",
    "Engine": "mysql",
    "DBInstanceStatus": "available",
    "MasterUsername": "admin",
    "Endpoint": {
      "Address": "rds-mysql.xxx.xxx.rds.amazonaws.com",
      "Port": 3306,
      "HostedZoneId": "xxx"
    },
    "AllocatedStorage": 200,
    "InstanceCreateTime": "2023-01-22T21:20:34.221000+00:00",
    "PreferredBackupWindow": "06:52-07:22",
    "BackupRetentionPeriod": 7,
    "DBSecurityGroups": [],
    "VpcSecurityGroups": [
      {
        "VpcSecurityGroupId": "sg-xxx",
        "Status": "active"
      }
    ],
    "DBParameterGroups": [
      {
        "DBParameterGroupName": "default.mysql8.0",
        "ParameterApplyStatus": "in-sync"
      }
    ],
    "AvailabilityZone": "xxx",
    "DBSubnetGroup": {
      "DBSubnetGroupName": "default-vpc-xxx",
      "DBSubnetGroupDescription": "Created from the RDS Management Console",
      "VpcId": "vpc-xxx",
      "SubnetGroupStatus": "Complete",
      "Subnets": [
        {
          "SubnetIdentifier": "subnet-xxx",
          "SubnetAvailabilityZone": {
            "Name": "xxx"
          },
          "SubnetOutpost": {},
          "SubnetStatus": "Active"
        },
        {
          "SubnetIdentifier": "subnet-xxx",
          "SubnetAvailabilityZone": {
            "Name": "xxx"
          },
          "SubnetOutpost": {},
          "SubnetStatus": "Active"
        },
        {
          "SubnetIdentifier": "subnet-xxx",
          "SubnetAvailabilityZone": {
            "Name": "xxx"
          },
          "SubnetOutpost": {},
          "SubnetStatus": "Active"
        }
      ]
    },
    "PreferredMaintenanceWindow": "xxxx",
    "PendingModifiedValues": {},
    "LatestRestorableTime": "2023-07-15T00:10:00+00:00",
    "MultiAZ": false,
    "EngineVersion": "8.0.28",
    "AutoMinorVersionUpgrade": true,
    "ReadReplicaDBInstanceIdentifiers": [],
    "LicenseModel": "general-public-license",
    "OptionGroupMemberships": [
      {
        "OptionGroupName": "default:mysql-8-0",
        "Status": "in-sync"
      }
    ],
    "PubliclyAccessible": false,
    "StorageType": "gp2",
    "DbInstancePort": 0,
    "StorageEncrypted": true,
    "KmsKeyId": "arn:aws:kms:xxx:xxx:key/xxx",
    "DbiResourceId": "xxx",
    "CACertificateIdentifier": "xxx",
    "DomainMemberships": [],
    "CopyTagsToSnapshot": true,
    "MonitoringInterval": 0,
    "DBInstanceArn": "arn:aws:rds:uxxx:xxx:db:rds-mysql",
    "IAMDatabaseAuthenticationEnabled": false,
    "PerformanceInsightsEnabled": false,
    "DeletionProtection": false,
    "AssociatedRoles": [],
    "CustomerOwnedIpEnabled": false,
    "ActivityStreamStatus": "stopped",
    "BackupTarget": "region",
    "NetworkType": "IPV4",
    "CertificateDetails": {
      "CAIdentifier": "xxx",
      "ValidTill": "xxx"
    },
      {
        "Key": "reviewlowutilization",
        "Value": "true"
      }
    ],
    "c7n:MatchedFilters": [
      "DBInstanceIdentifier"
    ]
  }
]
```

Non dry run error:
`Invalid request: An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: Invalid storage size for engine name mysql and storage type gp2: 140`
