### ISSUE TITLE
the unused filter for aws.security-group needs to ignore default IpPermissions

### ISSUE THREAD

**Issue by cvirtucio** [cloud-custodian/cloud-custodian#8783]
### Describe the bug

A [default security group](https://docs.aws.amazon.com/vpc/latest/userguide/default-security-group.html) has the following IpPermission when the group is created:

```
                {
                    "IpProtocol": "-1",
                    "IpRanges": [],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": [
                        {
                            "GroupId": "sg-<ID number>",
                            "UserId": <account ID>"
                        }
                    ]
                }
```

This is to allow same-account traffic to members of that security group. This poses a problem for us when we try to use the `type: unused` filter for default security groups. When the filter [scans for used groups](https://github.com/cloud-custodian/cloud-custodian/blob/da894ebc7b4a1b829845860378b58e714c6fb53f/c7n/resources/vpc.py#L885-L887), it [uses the get_sg_refs() method as a scanner](https://github.com/cloud-custodian/cloud-custodian/blob/da894ebc7b4a1b829845860378b58e714c6fb53f/c7n/resources/vpc.py#L877), which [iterates through these rules](https://github.com/cloud-custodian/cloud-custodian/blob/da894ebc7b4a1b829845860378b58e714c6fb53f/c7n/resources/vpc.py#L933-L934). If any of these rules [has a UserGroupIdPair at all](https://github.com/cloud-custodian/cloud-custodian/blob/da894ebc7b4a1b829845860378b58e714c6fb53f/c7n/resources/vpc.py#L936C49-L936C49), then the group [will be considered as used](https://github.com/cloud-custodian/cloud-custodian/blob/da894ebc7b4a1b829845860378b58e714c6fb53f/c7n/resources/vpc.py#L937-L938). The filter needs to take such rules into account because it is not necessarily true that a group with these rules (which AWS generates automatically) is used.

### What did you expect to happen?

I expect a policy similar to the following:

```yaml
policies:
  - name: enforce-empty-unused-default-sgs-all-vpcs
    description: ensure that the unused default security groups of all VPCs are empty
    resource: aws.security-group
    filters:
      - type: unused
      - type: value
        key: GroupName
        op: equal
        value: "default"
```

to match all of the security groups named `default` that are unused, regardless of the fact that they have rules automatically generated by AWS.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n==0.9.26
```

### Policy

```shell
policies:
  - name: enforce-empty-unused-default-sgs-all-vpcs
    description: ensure that the unused default security groups of all VPCs are empty
    resource: aws.security-group
    filters:
      - type: unused
      - type: value
        key: GroupName
        op: equal
        value: "default"
```
