### ISSUE TITLE
route53 action to create records for AWS services

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#8789]
### Describe the feature

I am always frustrated when I have to manage aws route53 records using terraform or clickops.

It would be very nice to do something like this

```yaml
policies:
  - name: rds-create-r53-records
    resource: rds
    actions:
      - type: route53
        zone: "example.com"
        record_query: "Name"
        format: "%s.db"
```

It would then use jmespath, search for `record_query`, retrieve the id`, and prefix that to the zone as a record.

e.g. auroradb named `banana` would then get the record `banana.db.example.com`

### Extra information or context

This is similar to `external-dns` in k8s to create r53 records based on annotations.

This would create an `external-dns` for aws services to create r53 records based on policy `action` settings in the yaml and/or tag based overrides.
