### ISSUE TITLE
AWS Lambda - add "Lambda Insights" configuration to meta-data

### ISSUE THREAD

**Issue by CallumHibbert** [cloud-custodian/cloud-custodian#8790]
### Describe the feature

I would like to write a policy to alert on the usage of Lambda Insights for AWS Lambda.

At the moment CloudCustodian (v0.9.29) does not include any Lambda Insights configuration information in the meta-data/schema for AWS Lambda resources. It would be really useful to have that information added.

Thanks.

**Comment by kapilt** [comment]
you can already do this today, insights isn't an explicit configuration for lambda, its a combination of the execution role having the right permissions, and using an extension layer. you can check for the presence of the layer or check the permissions of the execution role with a policy.

**Comment by CallumHibbert** [comment]
For anyone who searches for this, the following filters (searching on the Layer ARNs) work for me:

```
  ...
  resource: aws.lambda
  filters:
  - type: value
    key: Layers[].Arn
    value_type: size
    op: greater-than
    value: 0 # Guard against zero length list for the next filter
  - type: value
    key: join(',', Layers[].Arn) # Join the list into a single string (list must not be zero length)
    op: regex
    value: .*LambdaInsights.* # Regex the concatenated string
  ...
```

The Layer ARNs are documented here:
- ARM: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsARM.html
- x86: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Lambda-Insights-extension-versionsx86-64.html
