### ISSUE TITLE
Unable to pass log_retention_days as integer variable while using log-group resource and passing variable from accounts.yml in c7n-org

### ISSUE THREAD

**Issue by ShivaSharm** [cloud-custodian/cloud-custodian#8794]
### Describe the bug

Using 0.9.29.0 version for custodian, Trying to set up policy using c7n-org to set log retention for log groups and passing retention days as variable from accounts.yml config file:

```yaml
policies:
  - name: cloudwatch-logs-retention
    resource: log-group
    description: |
      Sets a default retention on a cloudwatch log group where a retention is currently unset.
    filters:
      - type: value
        key: retentionInDays
        value: absent
    actions:
      - type: retention
        days: "{cw_log_retention_days}"
```

accounts.yml
```yaml
accounts:
    - account_id: "XXXXXXXXXX"
      name: "account-alias"
      role: arn:aws:iam::XXXXXXXX:role/custodian-role
      vars:
         cw_log_retention_days: 15
```

Error: 

2023-08-01 09:11:53,219: custodian.commands:ERROR             Error on policy:cloudwatch-logs-retention resource:log-group
'{cw_log_retention_days}' is not of type 'integer'

            Failed validating 'type' in schema[12]['properties']['days']:
                {'type': 'integer'}

            On instance['days']:
                '{cw_log_retention_days}'

Does not work even if I try as below in actions for policy, and it is being rendered as None.
actions:
      - type: retention
        days: {cw_log_retention_days}

error:
2023-08-01 09:14:19,885: custodian.commands:ERROR             Error on policy:cloudwatch-logs-retention resource:log-group
{'cw_log_retention_days': None} is not of type 'integer'

            Failed validating 'type' in schema[12]['properties']['days']:
                {'type': 'integer'}

            On instance['days']:
                {'cw_log_retention_days': None}

### What did you expect to happen?

Is there a way to be able to pass an integer variable from accounts.yml without it being rendered as string. I expect we should be able to pass integer values as well for variables.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
/ # custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.29
Python:      3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]
Platform:    posix.uname_result(sysname='Linux', nodename='71ec8abd9250', release='5.10.16.3-microsoft-standard-WSL2', version='#1 SMP Fri Apr 2 22:23:49 UTC 2021', machine='x86_64')
Using venv:  False
Docker: True
Installed:

argcomplete==3.1.1
attrs==23.1.0
boto3==1.28.5
botocore==1.31.5
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.17.3
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0.1
s3transfer==0.6.1
six==1.16.0
tabulate==0.9.0
typing-extensions==4.7.1
urllib3==1.26.16
zipp==3.15.0
```

### Policy

```shell
policies:
  - name: cloudwatch-logs-retention
    resource: log-group
    description: |
      Sets a default retention on a cloudwatch log group where a retention is currently unset.
    filters:
      - type: value
        key: retentionInDays
        value: absent
    actions:
      - type: retention
        days: "{cw_log_retention_days}"


accounts.yml

accounts:
  - account_id: "XXXXXXXXXX"
    name: "account-alias"
    role: arn:aws:iam::XXXXXXXX:role/custodian-role
    vars:
      cw_log_retention_days: 15
```

### Relevant log/traceback output

```shell
2023-08-01 09:11:53,219: custodian.commands:ERROR             Error on policy:cloudwatch-logs-retention resource:log-group
'{cw_log_retention_days}' is not of type 'integer'

            Failed validating 'type' in schema[12]['properties']['days']:
                {'type': 'integer'}

            On instance['days']:
                '{cw_log_retention_days}'
```
