### ISSUE TITLE
{now} does not expand in value_from.url when running in serverless mode

### ISSUE THREAD

**Issue by huynhsontung** [cloud-custodian/cloud-custodian#8873]
### Describe the bug

I have a filter that gets value from an S3 object with a key that contains the current date.

```yaml
value_from:
    format: txt
    url: s3://custodian-integrations/amis/{now:%Y-%m-%d}/preprod.txt
```

Before I could use `{now}` in the S3 URL but after updating to the latest version (c7n==0.9.30), `{now}` doesn't expand anymore and the policy errors out as it can't find the object. This issue only exists in `periodic` mode, `pull` mode expands the URL normally.

### What did you expect to happen?

`{now}` should expand for `value_from.url` in a filter when running in serverless mode.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
c7n==0.9.30
```

### Policy

```shell
name: ami-list-test
resource: ami
filters:
  - type: value
    key: "ImageId"
    op: in
    value_from:
      format: txt
      url: s3://custodian-integrations/amis/{now:%Y-%m-%d}/preprod.txt
mode: &mode
  type: periodic
  schedule: "cron(10 23 ? * 1 *)"
```

### Extra information or context

I am quite certain that the issue originated from #8509. Downgrading to 0.9.26 fixed the issue.

**Comment by kapilt** [comment]
hmm.. that's odd, and worth investigating, the purpose of #8509 was to defer expanding now till server less policy execution, it was previously expanding at provisioning time for the function.

**Comment by fen9li** [comment]
Hey, I’m experiencing the same issue, but in a slightly different scenario.

Everything was working fine before upgrading to version 0.9.47, but after that, my policy stopped rendering {now} dynamically. Here’s the snippet I’m using:

```
- name: tag-unattached-ebs
  resource: ebs
  description: |
    Tag unattached ebs with timestamp
  mode:
     ...
  filters:
    - State: available
    - "tag:maid_status": absent
  actions:
    - type: tag
      key: maid_status
      value: "detached-at-{now}"
```

Previously, {now} would be replaced with the current timestamp, but after 0.9.47 it gets treated as a literal string. Also { now().isoformat() }, no luck - it’s not being evaluated anymore.

Could you please take a look at this as well while you’re already working on this open issue?
