### ISSUE TITLE
[aws.s3]: Allow checking the order using `has-statement` and setting the order using `set-statement`

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#8925]
### Describe the feature

The policy statements are evaluated in order.

Let's say you want to deny s3:PutObjectAcl for all roles outside of the company but an existing s3 bucket policy allows this action for Principals in other accounts. If you use `set-statement` to add a policy, it will add it to the bottom of the policy which means it will not get evaluated.

If we can set the order and set the new statement as index 0, then it will get evaluated first before the existing statements.

```yaml
    actions:
      - type: set-statements
        statements:
          -
            # this is the proposal, perhaps valid values could be a specific index 0, 1, 2 etc or "first" or "last"
            # "last" would be the default if unset
            index: first
            Sid: "DenyRestrictedActionsExceptAFewRoles"
            Effect: "Deny"
            Action:
              - "s3:DeleteBucketPolicy"
              - "s3:PutBucketPolicy"
              - "s3:PutBucketAcl"
              - "s3:PutEncryptionConfiguration"
              - "s3:PutObjectAcl"
            Principal:
              AWS: "*"
            Resource:
              - "arn:aws:s3:::{bucket_name}/*"
              - "arn:aws:s3:::{bucket_name}"
            Condition:
              StringNotLike:
                "aws:PrincipalArn":
                  # List of break glass roles
                  - "arn:aws:iam::{account_id}:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Admin_*"
                  - "arn:aws:iam::{account_id}:role/break-glass-role"
```
