### ISSUE TITLE
When resizing an AWS EC2 instance, type-map should be optional but it actually seems to be required

### ISSUE THREAD

**Issue by timnolan1** [cloud-custodian/cloud-custodian#8941]
### Describe the bug

Given the following policy, I want to resize any non-t3.medium stopped EC2 instances to `t3.medium`:
```
---
tags:
- 'xxxxxxxxxxxxx'  # Account ABC
policies:
  - name: ec2_periodic_underutilized_resize
    resource: ec2
    description: |
      Finds EC2 instances and resizes them
    filters:
      - and:
          - "State.Name": stopped       
          - tag:aws:eks:cluster-name: absent
          - type: value
            op: not-in
            key: InstanceType
            value:
              - t3.medium
      - and:
          - or:
            - type: value
              key: "tag:environment"
              op: not-in
              value:
                - prod
    actions:
      - type: tag
        tags:
          c7n-actioned: "{{now}}"
      - type: resize
        default: t3.medium
```

### What did you expect to happen?

I expected any EC2 instances that are not `t3.medium` and that are in a `stopped` state to be resized to `t3.medium`

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
PyGithub==1.26
attrs==22.2.0
boto3==1.26.109
botocore==1.29.109
c7n-org==0.6.25
c7n==0.9.26
click==8.1.3
cryptography==3.4.8.post1+dr
flake8==3.8.1
invoke==1.6.0
jinja2==3.0.3
markupsafe==2.0.1
mock==4.0.3
pydocstyle==5.0.2
pyrsistent==0.19.3
pytest-coverage==0.0
pytest-pydocstyle==2.0.0
pytest-flake8==1.0.7
pytest==3.8.2
setuptools==57.5.0
sh==1.13.1
six==1.16.0
slacker==0.14.0
slackweb==1.0.5
strictyaml==1.6.1
troposphere==2.7.1
yamllint==1.26.3
```

### Policy

```shell
---
tags:
- 'xxxxxxxxxxxxx'  # Account ABC
policies:
  - name: ec2_periodic_underutilized_resize
    resource: ec2
    description: |
      Finds EC2 instances and resizes them
    filters:
      - and:
          - "State.Name": stopped       
          - tag:aws:eks:cluster-name: absent
          - type: value
            op: not-in
            key: InstanceType
            value:
              - t3.medium
      - and:
          - or:
            - type: value
              key: "tag:environment"
              op: not-in
              value:
                - prod
    actions:
      - type: tag
        tags:
          c7n-actioned: "{{now}}"
      - type: resize
        default: t3.medium
```

### Relevant log/traceback output

```shell
DEBUG]	2023-09-13T18:12:47.863Z	59dc2d2c-8114-4f2e-8bd7-74e86af8f9d0	resizing i-0d43d8573e29eb2f1 t3.small
[ERROR]	2023-09-13T18:12:48.204Z	59dc2d2c-8114-4f2e-8bd7-74e86af8f9d0	Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 365, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/ec2.py", line 1378, in process
    self.process_resource_set(instance_set)
  File "/var/task/c7n/resources/ec2.py", line 1395, in process_resource_set
    new_type = type_map.get(i['InstanceType'], default_type)
AttributeError: 'NoneType' object has no attribute 'get'[ERROR]	2023-09-13T18:12:48.333Z	59dc2d2c-8114-4f2e-8bd7-74e86af8f9d0	Error while executing polic
```

### Extra information or context

However when I add an empty `type-map` to the last line of the policy it works.  According to the [docs](https://cloudcustodian.io/docs/aws/resources/ec2.html#aws-ec2-actions-resize), `type-map` should be optional.  In my case I do not require any overrides.
```
---
tags:
- 'xxxxxxxxxxxxx'  # Account ABC
policies:
  - name: ec2_periodic_underutilized_resize
    resource: ec2
    description: |
      Finds EC2 instances and resizes them
    filters:
      - and:
          - "State.Name": stopped       
          - tag:aws:eks:cluster-name: absent
          - type: value
            op: not-in
            key: InstanceType
            value:
              - t3.medium
      - and:
          - or:
            - type: value
              key: "tag:environment"
              op: not-in
              value:
                - prod
    actions:
      - type: tag
        tags:
          c7n-actioned: "{{now}}"
      - type: resize
        default: t3.medium
        type-map: {}
```
