### ISSUE TITLE
aws.ec2 length(Tags) fails if an EC2 instance has no tags at all

### ISSUE THREAD

**Issue by tatodorov** [cloud-custodian/cloud-custodian#8953]
### Describe the bug

I have the following policy to filter untagged AWS EC2 instances:
```yaml
    - name: aws-ec2-untagged
      resource: aws.ec2
      description: Find untagged EC2 instances
      filters:
        - type: value
          key: "length(Tags)"
          op: eq
          value: 0
          value_type: integer
```
However, when an EC2 instance has no even a single tag, I encounter the following exception:
```bash
c7n_org:ERROR Exception running policy:aws-ec2-untagged account:my-account region:us-east-1 error:In function length(), invalid type for value: (), expected one of: ['string', 'array', 'object'], received: "unknown"
```
Essentially, every time when I have a resource in `resources.json` with `"Tags": []`, I encounter the above exception.

### What did you expect to happen?

My expectation is the function `length(Tags)` to return 0 if Tags is `[]`.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Cloud Custodian 0.9.30.0, but I've tested also with 0.9.31.0.
```

### Policy

```shell
- name: aws-ec2-untagged
      resource: aws.ec2
      description: Find untagged EC2 instances
      filters:
        - type: value
          key: "length(Tags)"
          op: eq
          value: 0
          value_type: integer
```

### Relevant log/traceback output

```shell
c7n_org:ERROR Exception running policy:aws-ec2-untagged account:my-account region:us-east-1 error:In function length(), invalid type for value: (), expected one of: ['string', 'array', 'object'], received: "unknown"
```
