### ISSUE TITLE
Support set-inline-policy for iam roles

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#8987]
### Describe the feature

I am always frustrated when I have to add a policy to every service role. I'd rather not create a managed IAM policy and attach it because then it makes deleting the roles harder since the managed policy has to be removed first prior to deletion. With an inline policy, I can delete the role without deleting the inline policy.

I'd like something like [`set-statement` for `aws.s3`](https://cloudcustodian.io/docs/aws/resources/s3.html#set-statements) but for `aws.iam-role`

```yaml
policies:
  - name: iam-role-with-some-inline-role
    resource: aws.iam-role
    filters:
      # something like this to see if any roles do NOT have this inline policy (untested)
      - not:
        - has-inline-policy
        - type: value
          key: "'c7n:InlinePolicies'"
          value: ssm
          op: in
          value_type: swap
    actions:
      # - type: set-policy
      #   state: attached
      #   arn: arn:aws:iam::123456789012:policy/AmazonSSMManagedInstanceCore
      - type: set-inline-policy
        policy:
          - Sid: "AllowSSM"
            Effect: "Allow"
            Action:
              - "ssmmessages:CreateControlChannel"
              - "ssmmessages:CreateDataChannel"
              - "ssmmessages:OpenControlChannel"
              - "ssmmessages:OpenDataChannel"
              - "ssm:UpdateInstanceInformation"
              - "ssm:ListAssociations"
              - "ec2messages:GetMessages"
            Resource: "*"
          - Sid: "AllowLogs"
            Effect: "Allow"
            Action:
              - "logs:CreateLogStream",
              - "logs:PutLogEvents",
              - "logs:DescribeLogGroups",
              - "logs:DescribeLogStreams"
            Resource: "*"
          - Sid: "AllowS3PutObject"
            Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource: "arn:aws:s3:::some-global-s3-bucket/*"
          - Sid: "AllowS3EncryptionConfig"
            Effect: "Allow"
            Action:
              - "s3:GetEncryptionConfiguration"
            Resource: "*"
          - Sid: "AllowKMSEncrypt"
            Effect: "Allow"
            Action:
              - "kms:GenerateDataKey"
            Resource: "*"
```

### Extra information or context

- Referenced a specific inline policy https://github.com/cloud-custodian/cloud-custodian/pull/2636
