### ISSUE TITLE
Add generic filter support for matching a list item that meets conditions on multiple fields

### ISSUE THREAD

**Issue by danbunnell** [cloud-custodian/cloud-custodian#9004]
## Feature Request

I am using Cloud Custodian for reporting on AWS deployments. I recently needed to write a query to verify that S3 buckets in an account all have a reasonable Lifecycle Expiration Rule applied. I found that I needed to query a List field for any item that matches multiple field conditions at the same time, and I do not find any documentation of support for such a complex List filter.

Can you add support for matching a List item against multiple fields?

## Background Context

For example, to verify that a bucket has a valid Lifecycle Expiration, you need to match that one list item matches the expected value for all of the following fields:
- `Lifecycle.Rules[].Status` == `Enabled`
- `Lifecycle.Rules[].Expiration.Days` <= `<desired expiration>`
- `Lifecycle.Rules[].Filter` == `empty` or `Lifecycle.Rules[].Filter` includes the objects you care about

To help demonstrate why matching a single list item field is insufficient, as was recommended in another issue (#2056
 ), here is an example of what AWS Lifecycle Rules field could look like:

```json
{
    "...": {
        "Lifecycle": {
            "Rules": [
                {
                    "Expiration": {
                        "Days": 10
                    },
                    "ID": "expiration-rule-0",
                    "Filter": {},
                    "Status": "Disabled"
                },
                {
                    "Expiration": {
                        "Days": 30
                    },
                    "ID": "expiration-rule-1",
                    "Filter": {
                        "Prefix": "some-prefix"
                    },
                    "Status": "Enabled"
                },
                {
                    "Expiration": {
                        "Days": 45
                    },
                    "ID": "expiration-rule-2",
                    "Filter": {},
                    "Status": "Enabled"
                }
            ]
        }
    }
}
```

In the above example `Rules[0]` is not valid, as it is not enabled. `Rules[1]` is valid but has a filter for objects so we would need to be careful that it includes the objects that we care about. `Rules[2]` is valid and has no filter, so we would this as the min applied value for Days if `Rules[1]` did not suffice.

This is the full schema documentation for [GetBucketLifecycleConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycleConfiguration.html#API_GetBucketLifecycleConfiguration_ResponseSyntax).

## Workaround 
To help anyone in the meantime before this is addressed, I ended up using a brute force list query assuming only a few Lifecycle Rules would exist on a given bucket. This breaks if the list of rules is longer than I expected. 

Here is a sample policy to check for valid Lifecycle Rules:

```yaml
vars:
  max_valid_expiration: &max_valid_expiration 30 # assume larger expiration is invalid
  applicable_buckets: &applicable_buckets
    - or:
      - type: value
        key: Name
        op: regex
        value: "^my-bucket-prefix" # buckets I care about
      - type: value
        key: Name
        op: regex
        value: "^my-bucket-prefix-2" # other buckets I care about
  has_lifecycle_expiration: &has_lifecycle_expiration
    - or:
      - and:
        - "Lifecycle.Rules[0]": "present"
        - "Lifecycle.Rules[0].Expiration": "present"
        - "Lifecycle.Rules[0].Status": "Enabled"
        - or:
          - "Lifecycle.Rules[0].Filter": "empty"
          - "Lifecycle.Rules[0].Filter.Prefix": "*"
        - type: value
          key: Lifecycle.Rules[0].Expiration.Days
          value: *max_valid_expiration
          op: lte
      - and:
        - "Lifecycle.Rules[1]": "present"
        - "Lifecycle.Rules[1].Expiration": "present"
        - "Lifecycle.Rules[1].Status": "Enabled"
        - or:
          - "Lifecycle.Rules[1].Filter": "empty"
          - "Lifecycle.Rules[1].Filter.Prefix": "*"
        - type: value
          key: Lifecycle.Rules[1].Expiration.Days
          value: *max_valid_expiration
          op: lte
      - and:
        - "Lifecycle.Rules[2]": "present"
        - "Lifecycle.Rules[2].Expiration": "present"
        - "Lifecycle.Rules[2].Status": "Enabled"
        - or:
          - "Lifecycle.Rules[2].Filter": "empty"
          - "Lifecycle.Rules[2].Filter.Prefix": "*"
        - type: value
          key: Lifecycle.Rules[2].Expiration.Days
          value: *max_valid_expiration
          op: lte
policies:
  - name: s3-bucket-has-lifecycle-expiration
    resource: s3
    comment: |
      filters in any applicable bucket with an active
      lifecycle expiration applying to all objects.

      Caveat: may break if more than 3 lifecycle
      policies exist. why: we do not know how to
      filter for any list item matching multiple
      fields, so instead look only at the top N
      by their index.
    filters:
      - and:
        - <<: *applicable_buckets
        - <<: *has_lifecycle_expiration
  - name: s3-bucket-missing-lifecycle-expiration
    resource: s3
    comment: |
      filters in any applicable bucket that does not
      have an active lifecycle expiration rule.
    filters:
      - and:
        - <<: *applicable_buckets
        - not:
          - <<: *has_lifecycle_expiration
```

**Comment by ajkerrigan** [comment]
Hi @danbunnell - this sounds like exactly the sort of use case that the [list-item filter](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#list-item) was made for. You can use it to look for buckets where at least one lifecycle rule matches multiple conditions, like:

```yaml
- name: aws-s3-lifecycle
  resource: aws.s3
  filters:
    - type: list-item
      key: Lifecycle.Rules
      attrs:
        - Status: Enabled
        - Filter.Prefix: empty
        - type: value
          key: Expiration.Days
          op: lte
          value: 10
```
