### ISSUE TITLE
https://cloudcustodian.io/getting-started/policyStructure/ doesn't work

### ISSUE THREAD

**Issue by alberttwong** [cloud-custodian/cloud-custodian#9027]
### Describe the bug

If you follow the example for tag compliance on https://cloudcustodian.io/getting-started/policyStructure/, it doesn't work

### What did you expect to happen?

tagged with c7n_status: Resource does not meet policy: stop@2023/10/07 but it was maid_status: Resource does not meet policy: stop@2023/10/07

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
(custodian) [ec2-user@ip-172-31-25-81 ~]$ custodian version --debug

Please copy/paste the following info along with any bug reports:

Custodian:   0.9.31
Python:      3.9.16 (main, Sep  8 2023, 00:00:00)
             [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]
Platform:    posix.uname_result(sysname='Linux', nodename='ip-172-31-25-81.us-west-2.compute.internal', release='6.1.52-71.125.amzn2023.x86_64', version='#1 SMP PREEMPT_DYNAMIC Tue Sep 12 21:41:38 UTC 2023', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.1.1
attrs==23.1.0
boto3==1.28.41
botocore==1.31.41
docutils==0.18.1
importlib-metadata==5.2.0
jmespath==1.0.1
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.30.2
rpds-py==0.10.2
s3transfer==0.6.2
six==1.16.0
tabulate==0.9.0
urllib3==1.26.16
zipp==3.16.2
```

### Policy

```shell
(custodian) [ec2-user@ip-172-31-25-81 ~]$ cat tagexample.yml
policies:

- name: ec2-tag-compliance-mark
  resource: ec2
  comment: |
    Mark non-compliant, Non-ASG EC2 instances with stoppage in 4 days
  filters:
    - "State.Name": running
    - "tag:aws:autoscaling:groupName": absent
    - "tag:c7n_status": absent
    - or:
        - "tag:Owner": absent
        - "tag:CostCenter": absent
        - "tag:Project": absent
  actions:
    - type: mark-for-op
      op: stop
      days: 4
```

**Comment by alberttwong** [comment]
also it's pretty hard to help with content edits.   You just can't click and edit like other github projects.   

There's a better yaml that you can cut and paste and use (file name: tagexample.yml)
``` 
policies:

- name: ec2-tag-compliance-mark
  resource: ec2
  comment: |
    Mark non-compliant, Non-ASG EC2 instances with stoppage in 4 days
  filters:
    - "State.Name": running
    - "tag:aws:autoscaling:groupName": absent
    - "tag:c7n_status": absent
    - or:
        - "tag:Owner": absent
        - "tag:CostCenter": absent
        - "tag:Project": absent
  actions:
    - type: mark-for-op
      op: stop
      days: 4
```

run it by `custodian run -s . tagexample.yml --dryrun` and `custodian run -s . tagexample.yml`
