### ISSUE TITLE
Match multiple values in network-location filter 

### ISSUE THREAD

**Issue by ahlgreno** [cloud-custodian/cloud-custodian#9055]
### Describe the feature

For some tags, we have multiple values that mean the same thing. As is, the [network-location](https://cloudcustodian.io/docs/aws/resources/aws-common-filters.html#network-location) filter can only compare the equivalence of strings.

A better solution would be if the network-location filter was able to compare multiple values as equivalent from a list.

Feature request add the option `match: in` that would take a value type of a list of strings, and if the key value for the resources was contained in the provided list, the filter would consider this a match.

```
policies:
  - name: ec2-mismatched-sg-remove
    resource: ec2
    filters:
      - type: network-location
        compare: ["resource","security-group"]
        key: "tag:NetworkLocation"
        match: in
        value:
          - Enterprise
          - EntFacing
 ```

### Extra information or context

PR: https://github.com/cloud-custodian/cloud-custodian/pull/9160
