### ISSUE TITLE
Azure resource filtering should not be case-sensitive

### ISSUE THREAD

**Issue by ikraemer-dd** [cloud-custodian/cloud-custodian#9089]
### Describe the bug

As a pre-requisite, the subscription I am running the tests against has a storage account named `/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Storage/storageAccounts/zzz`.

When I use this policy, I get 1 resource:
```
policies:
  - name: storage-account-upper-and-lower-case
    description: |
      Find a storage accounts (upper and lower cases)
    resource: azure.storage
    filters:
      - type: value
        key: id
        op: in
        value: /subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Storage/storageAccounts/zzz
```

When I use this other policy, I get no resource:
```
policies:
  - name: storage-account-lower-case
    description: |
      Find a storage accounts (lower cases)
    resource: azure.storage
    filters:
      - type: value
        key: id
        op: in
        value: /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/zzz
```

### What did you expect to happen?

I expect that the default behaviour is to compare resource names in a case-insensitive way, as Microsoft [doc](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) states:

> Always perform a case-insensitive comparison of names. 

Hence, I would expect both policies to have the same result, and to output 1 resource.

### Cloud Provider

Microsoft Azure

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.31
Python:      3.9.9 (main, Jul 26 2022, 18:58:42)
             [Clang 13.1.6 (clang-1316.0.21.2.5)]
Platform:    posix.uname_result(sysname='Darwin', nodename='COMP-XDHVVGQ43V', release='22.6.0', version='Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed:

PyJWT==2.8.0
adal==1.2.7
applicationinsights==0.11.10
apscheduler==3.10.4
argcomplete==3.1.1
attrs==23.1.0
azure-common==1.1.28
azure-core==1.29.3
azure-cosmos==3.2.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-functions==1.17.0
azure-graphrbac==0.61.1
azure-identity==1.14.0
azure-keyvault==4.2.0
azure-keyvault-certificates==4.7.0
azure-keyvault-keys==4.8.0
azure-keyvault-secrets==4.7.0
azure-mgmt-advisor==9.0.0
azure-mgmt-apimanagement==1.0.0
azure-mgmt-applicationinsights==1.0.0
azure-mgmt-appplatform==8.0.0
azure-mgmt-authorization==1.0.0
azure-mgmt-batch==15.0.0
azure-mgmt-cdn==10.0.0
azure-mgmt-cognitiveservices==11.0.0
azure-mgmt-compute==19.0.0
azure-mgmt-containerinstance==7.0.0
azure-mgmt-containerregistry==8.0.0b1
azure-mgmt-containerservice==15.1.0
azure-mgmt-core==1.4.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-costmanagement==1.0.0
azure-mgmt-databricks==1.0.0b1
azure-mgmt-datafactory==1.1.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-dns==8.0.0b1
azure-mgmt-eventgrid==8.0.0
azure-mgmt-eventhub==8.0.0
azure-mgmt-frontdoor==1.1.0
azure-mgmt-hdinsight==7.0.0
azure-mgmt-iothub==1.0.0
azure-mgmt-keyvault==8.0.0
azure-mgmt-logic==9.0.0
azure-mgmt-managementgroups==1.0.0b1
azure-mgmt-monitor==2.0.0
azure-mgmt-msi==1.0.0
azure-mgmt-network==17.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==1.0.0
azure-mgmt-rdbms==8.1.0
azure-mgmt-recoveryservices==2.5.0
azure-mgmt-redhatopenshift==1.3.0
azure-mgmt-redis==12.0.0
azure-mgmt-resource==16.1.0
azure-mgmt-resourcegraph==7.0.0
azure-mgmt-search==8.0.0
azure-mgmt-security==1.0.0
azure-mgmt-servicebus==8.2.0
azure-mgmt-servicefabric==1.0.0
azure-mgmt-sql==1.0.0
azure-mgmt-storage==17.1.0
azure-mgmt-subscription==1.0.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-web==2.0.0
azure-nspkg==3.0.2
azure-storage-blob==12.17.0
azure-storage-common==2.1.0
azure-storage-file==2.1.0
azure-storage-file-share==12.13.0
azure-storage-queue==12.6.0
boto3==1.28.41
botocore==1.31.41
c7n==0.9.31
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
cryptography==41.0.3
distlib==0.3.7
docutils==0.18.1
google-api-core==2.11.1
google-api-python-client==2.97.0
google-auth==2.22.0
google-auth-httplib2==0.1.0
google-cloud-appengine-logging==1.3.1
google-cloud-audit-log==0.2.5
google-cloud-core==2.3.3
google-cloud-logging==3.6.0
google-cloud-monitoring==2.15.1
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.5.0
googleapis-common-protos==1.60.0
grpc-google-iam-v1==0.12.6
grpcio==1.57.0
grpcio-status==1.57.0
httplib2==0.22.0
idna==3.4
importlib-metadata==5.2.0
isodate==0.6.1
jmespath==1.0.1
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
msal==1.23.0
msal-extensions==1.0.0
msrest==0.7.1
msrestazure==0.6.4
netaddr==0.7.20
oauthlib==3.2.2
portalocker==2.7.0
proto-plus==1.22.3
protobuf==4.24.2
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pyjwt==2.8.0
pyparsing==3.1.1
pyrate-limiter==2.10.0
python-dateutil==2.8.2
pytz==2023.3.post1
pyyaml==6.0.1
referencing==0.30.2
requests==2.31.0
requests-oauthlib==1.3.1
retrying==1.3.4
rpds-py==0.10.2
rsa==4.9
s3transfer==0.6.2
six==1.16.0
tabulate==0.9.0
typing-extensions==4.7.1
tzdata==2023.3
tzlocal==5.0.1
uritemplate==4.1.1
urllib3==1.26.16
zipp==3.16.2
```

### Policy

```shell
policies:
  - name: storage-account-lower-case
    description: |
      Find a storage accounts (lower cases)
    resource: azure.storage
    filters:
      - type: value
        key: id
        op: in
        value: /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/zzz
```

**Comment by kapilt** [comment]
`value_type: normalize` is intended to support this use case.

**Comment by ikraemer-dd** [comment]
Hi!
My use case is write a policy finding all resources that match a filter, but to exclude a list of known resources. 
Hence, my policy looks like:

policies:
  - name: storage-account-lower-case
    description: |
      Find a storage accounts (lower cases)
    resource: azure.storage
    filters:
      - type: value
        key: id
        op: not-in
        value: 
        - /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/zzz
        - /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/aaa

I could not find how to make `value_type: normalize` option work with a list of values. Is there a way?

**Comment by kapilt** [comment]
yeah we should be able to do that in process_value_type as another condition for normalize re list of strings.

**Comment by ikraemer-dd** [comment]
Indeed, i missed this! The following policy addresses exactly my use-case.
```
policies:
  - name: storage-account-matching-a-list
    resource: azure.storage
    filters:
      - type: value
        key: id
        op: in
        value: 
        - /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/zzz
        - /subscriptions/xxx/resourcegroups/yyy/providers/microsoft.storage/storageaccounts/aaa
        value_type: normalize
```
Thank you!
