### ISSUE TITLE
aws.asg - Set desired capacity to the maximum taken from cloudwatch metrics for a specific period

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#9111]
### Describe the feature

I am always frustrated when I have to create my own python script or bash script to save an attribute (desired_size) to a tag if the tag value is less than the attribute

This policy

```yaml
policies:
  - name: asg-set-max-desired-capacity
    resource: asg
    actions:
      - type: resize
        restore-from-metrics:
          name: GroupDesiredCapacity
          statistics: Maximum
          days: 30
          # start-time: '30 days ago'
          # end-time: 'now'
          period: '30 days'
          # dimensions:
          #   name: AutoScalingGroupName
          #   value: # if empty then assume to be name of the auto scaling group found
          jmespath_query: max(Datapoints[].Maximum)
```

should match this cli output

```bash
$ aws cloudwatch get-metric-statistics \
  --namespace AWS/AutoScaling \
  --metric-name GroupDesiredCapacity \
  --statistics Maximum \
  --start-time $(date -d"30 days ago" +%s) \
  --end-time $(date +%s) \
  --period $(($(date +%s)-$(date -d "30 days ago" +%s))) \
  --dimensions Name=AutoScalingGroupName,Value=xyz  \
  --query 'max(Datapoints[].Maximum)'

10.0
```

so then when the policy runs, the desired capacity should be set to `10`

### Extra information or context

I'd like to pin asgs to the maximum recorded in a specific time frame

My workaround, for now, is to run a script that tags each autoscaling group with the maximum returned by the above awscli command. Then I can run the following policy.

```yaml
policies:
  - name: asg-set-max-desired-capacity
    resource: asg
    filters:
      - "tag:max-desired-capacity": present
    actions:
      - type: resize
        restore-options-tag: max-desired-capacity
```
