### ISSUE TITLE
Run validate on policies using c7n-org

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#9153]
### Describe the feature

I am always frustrated when I spend hours and hours on this policy, use python to debug, step through the code

```yaml
policies:
  - name: s3-do-action-on-new-buckets
    resource: aws.s3
    conditions:
      - region: us-east-1
    filter:
      - type: value
        key: CreationDate
        op: gt
        value_type: date
        value: "2023/11/01"
```

Only to find, hours/days later, that I used `filter` instead of `filters` and that's why my S3 buckets were unfiltered.

### Extra information or context

cloudcustodian slack thread

https://cloud-custodian.slack.com/archives/CAL4P6YE6/p1699907884836799
