### ISSUE TITLE
extend c7n to support custom filter

### ISSUE THREAD

**Issue by liualexiang** [cloud-custodian/cloud-custodian#9187]
### Describe the feature

Is it possible for c7n to support custom filter?

* custom filter code like:
```
from c7n.filters.core import Filter
from c7n.manager import resources
from c7n.utils import type_schema

class MissingOwnerTagFilter(Filter):
    schema = type_schema('missing-ownertag')
    permissions = ('ec2:DescribeTags',)
    def process(self, resources, event=None):
        return [r for r in resources if not any(t['Key'] in ['Owner', 'owner'] for t in r.get('Tags', []))]

resources.subscribe(resources.EVENT_FINAL, MissingOwnerTagFilter.register('missing-ownertag', MissingOwnerTagFilter))
```

* policy like:
```
policies:
  - name: missing-owner-tag
    resource: aws.ec2
    filters:
      - type: missing-ownertag
```

* get resource through custom filter
export CUSTODIAN_EXT_DIRS="/path/to/your/filters"
custodian run -s . policy.yml

**Comment by ajkerrigan** [comment]
There's no custom/plugin support for defining your own filters in code. More discussion on that [here](https://github.com/cloud-custodian/cloud-custodian/issues/8296#issuecomment-1435703681).

That said, many focused filters can be expressed using Custodian generic filters. In your example, that might be something like:

```yaml
policies:
  - name: sqs-missing-owner-tag
    resource: aws.sqs
    filters:
      - not:
        - type: value
          key: Tags[].Key
          op: intersect
          value:
            - Owner
            - owner
```

And if you wanted to define that filter once and reuse it in multiple policies, you can do so with YAML anchors & aliases:

```yaml
vars:
  missing_ownertag_filter: &missing_ownertag_filter
    not:
      - type: value
        key: Tags[].Key
        op: intersect
        value:
          - Owner
          - owner

policies:
  - name: sqs-missing-owner-tag
    resource: aws.sqs
    filters:
      - *missing_ownertag_filter

  - name: ec2-missing-owner-tag
    resource: aws.ec2
    filters:
      - *missing_ownertag_filter
```
