### ISSUE TITLE
Unable to perform actions on PutSecretValue event (AWS)

### ISSUE THREAD

**Issue by roiko2** [cloud-custodian/cloud-custodian#9254]
### Describe the bug

I have policy which should tag a secret every time its value is modifed.
For doing this, im using cloudtrail and the following configuration:
```
      events:
        - ids: responseElements.arn
          source: secretsmanager.amazonaws.com
          event: PutSecretValue
```
The lambda is triggered every time the secret value changed, but its not doing anything...
In the lambda logs im seeing:
`Found resource ids:['arn:aws:secretsmanager:us-east-1....']`
`Resources []`
Looks like it catches the correct secret arn, but from some reason it doesn't find the resource...

### What did you expect to happen?

Lambda to run on the related secret resource

### Cloud Provider

Amazon Web Services (AWS)
