### ISSUE TITLE
The error in determining the region of aws health type resources causes a bug that cannot be deployed.

### ISSUE THREAD

**Issue by xiaoen-liu** [cloud-custodian/cloud-custodian#9340]
### Describe the bug

Based on the data from https://github.com/boto/botocore/blob/develop/botocore/data/endpoints.json#L8748-L8780 . the AWS health service appears to be a special case as it exhibits characteristics of both a global service and a regional service.Therefore, an error occurs when deploying a Health-event policy specifying a region other than us-east-2.

I think we should make an exception for health-event here.
https://github.com/cloud-custodian/cloud-custodian/blob/main/c7n/resources/aws.py#L796

### What did you expect to happen?

```
policies:
  - name: phd-test
    resource: health-event
    mode:
      type: periodic
      role: role
      schedule: "rate(1 day)"
    filters:
      - type: value
        key: "lastUpdatedTime"
        op: less-than
        value_type: age
        value: 1
```

2024-03-10 20:34:56,999: c7n.policies:WARNING policy:phd-test resources:health-event not available in region:ap-northeast-1
2024-03-10 20:34:56,999: custodian.commands:WARNING Empty policy file(s).  Nothing to do.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
policies:
  - name: phd-test
    resource: health-event
    mode:
      type: periodic
      role: role
      schedule: "rate(1 day)"
    filters:
      - type: value
        key: "lastUpdatedTime"
        op: less-than
        value_type: age
        value: 1
```

2024-03-10 20:34:56,999: c7n.policies:WARNING policy:phd-test resources:health-event not available in region:ap-northeast-1
2024-03-10 20:34:56,999: custodian.commands:WARNING Empty policy file(s).  Nothing to do.
```


### Policy

_No response_

### Relevant log/traceback output

_No response_

### Extra information or context

_No response_
