### ISSUE TITLE
Strange behavior for offhours policy, only react on one single specific tag

### ISSUE THREAD

**Issue by jnancel** [cloud-custodian/cloud-custodian#9387]
### Describe the bug

I'm testing the offhours policy on my own, first trying to work out how the filter works but I'm facing a very strange issue. The number in offhour is an example so that I can test it any time.

Here's my policy : 
```
policies:
  - name: rds-off-hours-stop
    resource: rds
    comments: |
      Stop RDS instances as per schedule
    filters:
      - and:
        - "tag:infra:schedule": OfficeHours
        - type: offhour
          weekends: false
          default_tz: utc
          offhour: 9
          opt-out: true
          tag: infra:schedule:overwrite
```

It's working well until I try to add an exception in the `infra:schedule:overwrite` tag on one of the RDS. I'm adding the following exception `offu3du28M-Fu2c22u29` as per documentation but it still displays the same number of resources.

So I figured maybe he has an issue with the `:` so I just tried `toto` in tag parameter and I updated my RDS accordingly and it worked.

After that, I tried many many tag keys : `tata`, `azer`, `schedule:overwrite`, `schedule_overwrite`, maid_offhours (by removing the tag parameter) but it still doesn't work. And every time when I come back to `toto` as tag key, then it worked...

### What did you expect to happen?

I expect that with the policy I'm testing, setting the `infra:schedule:overwrite` tag to `offu3du28M-Fu2c22u29` on an RDS would exclude it from the results I get.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Please copy/paste the following info along with any bug reports:

Custodian:   0.9.34
Python:      3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='JNANCEL-PAL', release='4.4.0-19041-Microsoft', version='#3996-Microsoft Thu Jan 18 16:36:00 PST 2024', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.2.1
attrs==23.2.0
boto3==1.34.21
botocore==1.34.21
docutils==0.18.1
importlib-metadata==6.11.0
jmespath==1.0.1
jsonschema==4.21.0
jsonschema-specifications==2023.12.1
python-dateutil==2.8.2
pyyaml==6.0.1
referencing==0.31.1
rpds-py==0.17.1
s3transfer==0.10.0
six==1.16.0
tabulate==0.9.0
urllib3==1.26.18
zipp==3.17.0
```

### Policy

```shell
policies:
  - name: rds-off-hours-stop
    resource: rds
    comments: |
      Stop RDS instances as per schedule
    filters:
      - and:
        - "tag:infra:schedule": OfficeHours
        - type: offhour
          weekends: false
          default_tz: utc
          offhour: 9
          opt-out: true
          tag: infra:schedule:overwrite
```
