### ISSUE TITLE
Cloud Custodian Periodic Mode for analysing metrics filters working wrong compared to pull mode.

### ISSUE THREAD

**Issue by theakshai** [cloud-custodian/cloud-custodian#9402]
### Discussed in https://github.com/orgs/cloud-custodian/discussions/9401

<div type='discussions-op-text'>

<sup>Originally posted by **theakshai** April  3, 2024</sup>
Hi,

I am trying to find the under utilized ec2 resources using c7n policies,

The policy:

```
policies:
  - name: ec2-underutilized
    resource: ec2
    mode:
      type: periodic
      schedule: "rate(1 day)"
      role: role_arn
      timeout: 900
      memory: 1024
    filters:
      - type: metrics
        name: CPUUtilization
        namespace: 'AWS/EC2'
        days: 30
        period: 3600
        statistics: Maximum
        value: 5
        op: less-than
```

When I ran the policy in local it gave total of 22 ec2 count as oboslete. I cross verified it using boto3 script and cloud watch console.
When I deployed in periodic mode, It is not working properly as it gives the count as 396. Help me or Educate me why the discremency is happening with only metrics filters.
        
        </div>
