### ISSUE TITLE
'unused' filter used with aws.ami is not working as expected

### ISSUE THREAD

**Issue by ks-ihsm** [cloud-custodian/cloud-custodian#9452]
### Describe the bug

Using the unused filter in aws.ami policy caused us cancel launch permission of an ami even when we are using the AMI in production.

We are using this policy in the account where our AMI is shared. The moment this policy was executed there were a 1+ instances running in the account. 
Still the AMI got cancelled launch permission blocking instances to launch in that account.

```
policies:
  - name: ami-cancel-launch-permission
    resource: ami
    description: |
        This policy cancels launch permission of the shared ami images that are older than 14 days and do not have any instances spawned from it.
    query:
      - ExecutableUsers: [self]
      - Owners: ["xxxxxxxxxxxxx"]
    filters:
      - type: unused
        value: true
      - type: image-age
        days: 14
    actions:
      - type: cancel-launch-permission
        dryrun: false
````

### What did you expect to happen?

I expected 2 + 2 to equal 4, but instead 2 + 2 equaled 6!

### Cloud Provider

Amazon Web Services (AWS)
