### ISSUE TITLE
Filter an ec2 instance by it's instance type

### ISSUE THREAD

**Issue by mshantanu** [cloud-custodian/cloud-custodian#9473]
### Describe the feature

My use case is really simple but I think it's not supported by cloud-custodian yet. I want to filter out all the **EC2** machines that are not allowed to be provisioned. Let's say, for example, we only allow **m3.medium** and **m4.xlarge** and any other machine types should be terminated.

**Comment by ajkerrigan** [comment]
You can use the built-in [value filter](https://cloudcustodian.io/docs/filters.html#value-filter) to check arbitrary resource properties. For example, this would skip instances using the instance types you mentioned and match others:

```yaml
policies:
  - name: ec2-instance-types
    resource: aws.ec2
    filters:
      - type: value
        key: InstanceType
        op: not-in
        value:
          - m3.medium
          - m4.xlarge
```

You can make this fancier as needed, by:

- Using [value from](https://cloudcustodian.io/docs/filters.html#value-from) to look up supported instance types so you don't have to hardcode them into the policy
- Using event based execution modes to terminate instances on launch, similar to the [block resources in non-standard regions](https://cloudcustodian.io/docs/aws/examples/blocknonstandardregionresources.html) example
