### ISSUE TITLE
Add custom fields to reports directly within the policy yaml

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#9481]
### Describe the feature

I am always frustrated when I have to recall a specific field for a specific policy that I need to report on.

https://cloudcustodian.io/docs/quickstart/advanced.html

It would be nice if I could codify the field itself within the policy so I can run my reports without having to recall the specific command or without having to run different commands per report.

e.g. instead of this

```bash
custodian report -s . \
  --field "AccessKey1LastRotated"='"c7n:credential-report".access_keys[0].last_rotated' \
  policies/iam-unused.yml
```

I can add this to my policy

```diff
policies:
  - name: iam-deactivate-old-keys
    resource: iam-user
    conditions:
      - region: us-east-1
    report:
+     default_fields: true
+     fields:
+       - key: AccessKey1LastRotated
+         value: "\"c7n:credential-report\".access_keys[0].last_rotated"
    filters:
      - type: credential
        key: access_keys.active
        value: true
        op: eq
      - type: credential
        key: access_keys.last_rotated
        value_type: age
        value: 30
        op: greater-than
      - type: credential
        key: access_keys.last_used_date
        value_type: age
        value: 365
        op: greater-than
      # Workaround in https://github.com/cloud-custodian/cloud-custodian/issues/5583#issuecomment-1603010775
      - type: value
        key: length("c7n:matched-keys")
        value: 1
        op: gte
```

and simply run the report bare

```bash
custodian report -s . policies/iam-unused.yml
```

**Comment by SomeCleverUsername** [comment]
That would be a really nice enhancement. Did you found a way around this @nitrocode ?

I found the following to be already working, but only for "standard" fields.
```
policies:
  - name: security-groups
    resource: security-group
    report:
      fields:
        - Description
        - GroupName
        - Tags
        - VpcId
        - OwnerId
        - Email='Tags[?Key==`Email`].Value | [0]'
        - ManagedBy='Tags[?Key==`Managed-by`].Value | [0]'
```

However, it does not work for JMESPath-expressions (`ManagedBy='Tags[?Key==`Managed-by`].Value | [0]'`), which is very unfortunate.

And you still have to specify the extra fields during the invocation of c7n-org-report, e.g
`c7n-org report -c accounts.yml -s org-runs/ -u sg_inventory.yml --field Description=Description --field GroupName=GroupName --field Tags=Tags --field Email=Email --field ManagedBy=ManagedBy > testreport.csv`

**Comment by nitrocode** [comment]
Here is one example of the above implementation in shell and yq.

Prereqs

- passing in the policy file
- output is stored in output/policy-file-without-dot-yml-extension
- `policies[].report.fields` uses a key/val format
- all policies within the policy file use the same fields since the fields will be attached to every entry in the output or they will be empty

`run-report.sh`

```bash
#!/bin/bash

POLICY_FILE=$1
OUTPUT_FILE=output/$(basename $POLICY_FILE .yml)

FIELDS=()

# Extract fields correctly from YAML
while IFS=: read -r key val; do
  # Clean up key and value
  key=$(echo "$key" | sed 's/^ *"//; s/" *$//')
  val=$(echo "$val" | sed 's/^ *//')  # Don't strip quotes from value!
  FIELDS+=(--field "$key=$val")
done < <(yq '.policies[].report.fields[]' $POLICY_FILE)

CMD="c7n-org report -c accounts-dry-run.yml -s $OUTPUT_FILE -u $POLICY_FILE"

echo "$CMD" "${FIELDS[@]}"
eval "$CMD" "${FIELDS[@]}"
```

policy excerpt
```yaml
    report:
      fields:
        - "AccessKey0Active": '"c7n:matched-keys"[0].active'
        - "AccessKey0LastUsed": '"c7n:matched-keys"[0].last_used_date'
        - "AccessKey1Active": '"c7n:matched-keys"[1].active'
        - "AccessKey1LastUsed": '"c7n:matched-keys"[1].last_used_date'
```

Finally run it

```bash
$ ./run-report.sh policies/iam-deactivate-old-keys.yml
c7n-org report -c accounts-dry-run.yml -s output/iam-deactivate-old-keys -u policies/iam-deactivate-old-keys.yml --field AccessKey0Active='"c7n:matched-keys"[0].active' --field AccessKey0LastUsed='"c7n:matched-keys"[0].last_used_date' --field AccessKey1Active='"c7n:matched-keys"[1].active' --field AccessKey1LastUsed='"c7n:matched-keys"[1].last_used_date'
"Account","Region","Policy","UserName","CreateDate","AccessKey0Active","AccessKey0LastUsed","AccessKey1Active","AccessKey1LastUsed"
"snip","us-east-1","iam-deactivate-old-keys","adminops","2021-05-12T17:38:07+00:00","True","2025-05-30T18:20:00Z","",""
...
```
