### ISSUE TITLE
validate pre-commit hook?

### ISSUE THREAD

**Issue by jmreicha** [cloud-custodian/cloud-custodian#9555]
### Describe the feature

It would be nice to get fast feedback for testing policy validations when committing changes with a pre-commit hook. Not sure if this has been requested before, apologies if so.

### Extra information or context

Currently I am testing validations manually and sometimes forget.

**Comment by ajkerrigan** [comment]
I believe the idea has come up before, though at a glance I don't see other issues so thanks for filing :+1: . Tthere's nothing official today, though you can certainly use local hooks effectively if that's helpful. If you're running in an environment that already has custodian installed locally, you can use something like:

#### .pre-commit-config.yaml
```yaml
repos:
- repo: local
  hooks:
  - id: c7n-validate
    entry: custodian validate
    language: system
    name: Validate Cloud Custodian Policies
    files: policies/.*\.y?ml$
```

While if you're looking for something that _doesn't_ assume that custodian is already available, you could lean on the Custodian Docker image instead. (Note: I've tried the [docker](https://pre-commit.com/#docker) and [docker_image](https://pre-commit.com/#docker_image) support which sounds smoother in theory, but it auto-mounts local code to `/src` inside the container which clobbers the custodian source and prevents the image from working properly).

#### ./bin/c7n-validate.sh
```bash
#!/usr/bin/env bash
set -euo pipefail

for f in $*; do
	echo "Validating $f..."
	docker run -v "$PWD":/precommit:rw,Z "cloudcustodian/c7n:0.9.37.0" validate "/precommit/$f"
done
```

#### .pre-commit-config.yaml
```yaml
repos:
  - repo: local
    hooks:
      - id: c7n-validate
        name: Validate Cloud Custodian Policies
        language: script
        entry: ./bin/c7n-validate.sh
        files: policies/.*\.y.*ml$
```

It's worth raising this on a community meeting call or in Slack though - if it's something folks are interested in, it could be reasonable to provide an official hook :thinking: .
