### ISSUE TITLE
No documentation of "member-role"

### ISSUE THREAD

**Issue by 43976989** [cloud-custodian/cloud-custodian#9576]
### Describe the bug

As far as I can find, there are several deployment options for custodian on AWS, which intersect with several different execution modes:

1. Local/Docker, and it creates the various Lambda functions directly in the target accounts
2. Centralised using c7n-org, but it still creates Lambda functions directly in target accounts (so it's distributed in a leaf style)
3. Centralised and assumes roles in target accounts.

The problem is there's virtually no documentation for #3, and the existing documentation is vague or sometimes even misleading. For example, [execution options](https://cloudcustodian.io/docs/aws/lambda.html#execution-options) for Lambda states you can "make a policy execute in a different account using assume_role." That doesn't seem to work in testing for x-account roles assumption though, and instead "member-role" needs to be used? The documentation is frustratingly vague or entirely non-existent though.

Using the following template, and it does NOT work, despite it seeming like this is what the [documentation advises](https://cloudcustodian.io/docs/aws/lambda.html#execution-options):
```
    mode:
        type: cloudtrail
        role: arn:aws:iam::{account_id}:role/AccountALambdaExecutionRole
        execution-options:
          assume_role: arn:aws:iam::{account_id}:role/AccountBRemediationRole
          metrics: aws
```

In contrast, this segment DOES work:

```
    mode:
        type: cloudtrail
        role: arn:aws:iam::{account_id}:role/AccountALambdaExecutionRole
        member-role: arn:aws:iam::{account_id}:role/AccountBRemediationRole
```

Which is the correct/recommended way to do this? Either way, it should probably be in the documentation, no? The only reference I can find is in [the schema](https://cloudcustodian.io/docs/aws/resources/aws-modes.html#cloudtrail), but there's zero explanation.

Semi-related, it seems like c7n-org is the expected tool to be used if running across an org, but per https://github.com/cloud-custodian/cloud-custodian/issues/5584 and a couple of other comments I've found, it seems like c7n-org doesn't support a centralised deployment - it'd be awesome if the documentation called that out.

### What did you expect to happen?

Documentation actually includes the roles/keys that are needed.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.36
Python:      3.10.2 (main, Jun 10 2024, 11:17:48) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]
Platform:    posix.uname_result(sysname='Linux', nodename='xxx', release='4.14.336-257.568.amzn2.x86_64', version='#1 SMP Sat Mar 23 09:49:55 UTC 2024', machine='x86_64')
Using venv:  True
Docker: False
Installed:
 
argcomplete==3.3.0
attrs==23.2.0
boto3==1.34.92
botocore==1.34.92
docutils==0.18.1
importlib-metadata==6.11.0
jmespath==1.0.1
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
python-dateutil==2.9.0.post0
pyyaml==6.0.1
referencing==0.31.1
rpds-py==0.18.0
s3transfer==0.10.1
six==1.16.0
tabulate==0.9.0
urllib3==1.26.18
zipp==3.18.1
```
