### ISSUE TITLE
SNS Topic Policy Statement Filter Requires strict ordering

### ISSUE THREAD

**Issue by armichaud** [cloud-custodian/cloud-custodian#9577]
### Describe the bug

Similar to #8442 

Given the following filter for an SNS topic:

```yaml
- type: has-statement
  statements:
  - Action:
    - SNS:GetTopicAttributes
    - SNS:SetTopicAttributes
    - SNS:AddPermission
    - SNS:RemovePermission
    - SNS:DeleteTopic
    - SNS:Subscribe
    - SNS:ListSubscriptionsByTopic
    - SNS:Publish
    - SNS:Receive
      Condition:
        Bool:
          aws:SecureTransport: 'false'
      Effect: Deny
```

The filter is sensitive to the order of the actions – specifically, they must be in the _reverse_ order of how they are listed in the filter. In this case, it must be `["SNS:Receive", "SNS:Publish", "SNS:ListSubscriptionsByTopic", "SNS:Subscribe", "SNS:DeleteTopic", "SNS:RemovePermission", "SNS:AddPermission", "SNS:SetTopicAttributes", "SNS:GetTopicAttributes"]`
SNS topics that have these same actions but in another order will not match.

### What did you expect to happen?

I would expect that the order of these actions would not matter, and that the filter would match if they appeared in any order. 

### Cloud Provider

Amazon Web Services (AWS)
