### ISSUE TITLE
Service in unsupported region

### ISSUE THREAD

**Issue by jerryhxu** [cloud-custodian/cloud-custodian#9585]
### Describe the feature

Currently, AWS Bedrock is only supported in limited regions as specified in this document: (https://docs.aws.amazon.com/bedrock/latest/userguide/bedrock-regions.html). If a custodian policy is executed in an unsupported region, it will retry multiple times and eventually timeout with error.

I wonder if it is possible to have a more graceful exist from custodian that can give warning message like 'region is not supported'.

**Comment by kapilt** [comment]
so we primarily determine region support for a service based on service published sdk metadata which is accessible via

>>> s.get_available_regions('bedrock')
['ap-northeast-1', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'sa-east-1', 'us-east-1', 'us-west-2'

in the context of a service which has differential support based on api methods, this probably needs more thought.

for example what policy contents got that generate that error message and which region did you execute against?

**Comment by jerryhxu** [comment]
Here is a sample policy that executes against us-east-2 region.
```
- name: test-policy
  resource: aws.bedrock-knowledge-base
  filters:
  - not:
    - or:
      - storageConfiguration.type: OPENSEARCH_SERVERLESS
      - storageConfiguration.type: RDS
```
It uses `bedrock-agent` service.

The following code will return empty list. I think it is a problem from aws api.
```
s = Session()
response = s.get_available_regions('bedrock-agent')
```
