### ISSUE TITLE
CC Lambdas failing for `awscc` resources deployed via `c7n_org`

### ISSUE THREAD

**Issue by guusvw** [cloud-custodian/cloud-custodian#9605]
### Describe the bug

We're deploying out CloudCustodian as Lambdas to a set of AWS accounts via `c7n_org`.
We're now having the first policy in place which is using [`awscc`](https://pypi.org/project/c7n-awscc/) resources, but it seems not to work.

The policy looks like this:

```yaml
  - name: set-athena-workgroup-encryption
    mode:
      execution-options:
        metrics_enabled: true
        output_dir: s3://moia-cloud-custodian-reports/{account_id}/
      type: periodic
      schedule: "cron(0 8 ? * MON-FRI *)"
      role: arn:aws:iam::{account_id}:role/rol-cloud-custodian-execution
      tags:
        Owner: Platform Engineering
        Service: Cloud Custodian
    tags:
      - region:eu-central-1
      - region:eu-west-1
    resource: awscc.athena_workgroup
    filters:
      - type: value
        key: Name
        value: "primary"
      - type: value
        key: "WorkGroupConfiguration.ResultConfiguration.EncryptionConfiguration.EncryptionOption"
        value: absent
    actions:
      - type: update
        WorkGroupConfigurationUpdates:
          EnforceWorkGroupConfiguration: true
          ResultConfigurationUpdates:
            EncryptionConfiguration:
              EncryptionOption: SSE_S3
```

The installation part for our custodian/c7n-org in our pipeline looks something like this:

```Makefile
CLOUD_CUSTODIAN_VERSION=0.9.38
CLOUD_CUSTODIAN_AWS_CC_VERSION=0.1.23
CLOUD_CUSTODIAN_ORG_VERSION=0.6.37

custodian-dependencies:
	pip3 install c7n==$(CLOUD_CUSTODIAN_VERSION) c7n-org==$(CLOUD_CUSTODIAN_ORG_VERSION) c7n-awscc==$(CLOUD_CUSTODIAN_AWS_CC_VERSION)
```

When the Lambda is invoke, the out is:
```
{
  "errorMessage": "No module named 'c7n_awscc'",
  "errorType": "ModuleNotFoundError",
  "requestId": "fafdeb58-b3ef-4f73-9f93-c5086091770d",
  "stackTrace": [
    "  File \"/var/task/custodian_policy.py\", line 4, in run\n    return handler.dispatch_event(event, context)\n",
    "  File \"/var/task/c7n/handler.py\", line 154, in dispatch_event\n    load_resources(StructureParser().get_resource_types(policy_data))\n",
    "  File \"/var/task/c7n/resources/__init__.py\", line 20, in load_resources\n    load_providers(set(pmap))\n",
    "  File \"/var/task/c7n/resources/__init__.py\", line 73, in load_providers\n    from c7n_awscc.entry import initialize_awscc\n"
  ]
}
```

During the deployment we're seeing a bunch of 
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--
22 | WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
23 | Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
24 | To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
25 | ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
26 | c7n 0.9.38 requires boto3==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have boto3 1.34.140 which is incompatible.
27 | c7n 0.9.38 requires botocore==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have botocore 1.34.140 which is incompatible.
28 | c7n 0.9.38 requires s3transfer==0.10.1; python_version >= "3.8" and python_version < "4.0", but you have s3transfer 0.10.2 which is incompatible.
29 | c7n 0.9.38 requires urllib3==1.26.19; python_version >= "3.8" and python_version < "4.0", but you have urllib3 2.2.2 which is incompatible.
30 | c7n-org 0.6.37 requires boto3==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have boto3 1.34.140 which is incompatible.
31 | c7n-org 0.6.37 requires botocore==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have botocore 1.34.140 which is incompatible.
32 | c7n-org 0.6.37 requires s3transfer==0.10.1; python_version >= "3.8" and python_version < "4.0", but you have s3transfer 0.10.2 which is incompatible.
33 | c7n-org 0.6.37 requires urllib3==1.26.19; python_version >= "3.8" and python_version < "4.0", but you have urllib3 2.2.2 which is incompatible.
34 | c7n-awscc 0.1.23 requires boto3==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have boto3 1.34.140 which is incompatible.
35 | c7n-awscc 0.1.23 requires botocore==1.34.128; python_version >= "3.8" and python_version < "4.0", but you have botocore 1.34.140 which is incompatible.
36 | c7n-awscc 0.1.23 requires s3transfer==0.10.1; python_version >= "3.8" and python_version < "4.0", but you have s3transfer 0.10.2 which is incompatible.
37 | c7n-awscc 0.1.23 requires urllib3==1.26.19; python_version >= "3.8" and python_version < "4.0", but you have urllib3 2.2.2 which is incompatible.

```
but the new Lambdas appear.

### What did you expect to happen?

A CC Lambda which update Athen Workgroup configuration via the `awscc` package

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
CLOUD_CUSTODIAN_VERSION=0.9.38
CLOUD_CUSTODIAN_AWS_CC_VERSION=0.1.23
CLOUD_CUSTODIAN_ORG_VERSION=0.6.37
```

### Policy

```shell
- name: set-athena-workgroup-encryption
    mode:
      execution-options:
        metrics_enabled: true
        output_dir: s3://moia-cloud-custodian-reports/{account_id}/
      type: periodic
      schedule: "cron(0 8 ? * MON-FRI *)"
      role: arn:aws:iam::{account_id}:role/rol-cloud-custodian-execution
      tags:
        Owner: Platform Engineering
        Service: Cloud Custodian
    tags:
      - region:eu-central-1
      - region:eu-west-1
    resource: awscc.athena_workgroup
    filters:
      - type: value
        key: Name
        value: "primary"
      - type: value
        key: "WorkGroupConfiguration.ResultConfiguration.EncryptionConfiguration.EncryptionOption"
        value: absent
    actions:
      - type: update
        WorkGroupConfigurationUpdates:
          EnforceWorkGroupConfiguration: true
          ResultConfigurationUpdates:
            EncryptionConfiguration:
              EncryptionOption: SSE_S3
```
