### ISSUE TITLE
 app-elb type target-group TargetHealthDescriptions[] size 0 returns load balancers with valid targets

### ISSUE THREAD

**Issue by andrewhibbert** [cloud-custodian/cloud-custodian#9634]
### Describe the bug

 app-elb type target-group TargetHealthDescriptions[] size 0 returns load balancers with valid targets

### What did you expect to happen?

Should only see Load Balancers with no targets

### Cloud Provider

Amazon Web Services (AWS)

### Policy

```shell
resource: app-elb
filters:
        - type: target-group
          key: TargetHealthDescriptions[]
          value_type: size
          value: 0
          op: eq
```

**Comment by andrewhibbert** [comment]
Seems like the following works:
```
filters:
  - type: target-group
    key: "@"
    value: empty
```

As seen in https://github.com/orgs/cloud-custodian/discussions/7373

**Comment by andrewhibbert** [comment]
This policy works:
```
    resource: app-elb
    filters:
        - or:
            - type: target-group
              key: "[].TargetHealthDescriptions[]"
              value: empty
            - type: target-group
              key: "@"
              value: empty
            - not:
              - type: listener
                key: "@"
                value: present
```
