### ISSUE TITLE
JMESPath Function from_json for c7n-left

### ISSUE THREAD

**Issue by anna-shcherbak** [cloud-custodian/cloud-custodian#9676]
### Describe the feature

Is it possible to add JMESPath function `from_json` for c7n-left.

This would help avoid creating complex regex expressions, such as:
```
policies:
  - name: test
    resource: terraform.aws_iam_role
    filters:
      - type: value
        key: assume_role_policy
        op: regex
        value: ".*\\\"Principal\\\":\\\"*\\\".*"
```
And this is a simple expression, we need to create multiple to cover the presence of spaces, or square brackets, etc. 
From the documentation, it seems like `from_json` function is what would be really helpful here.
