### ISSUE TITLE
Enrich annotations for db-parameter filters for aws.rds-cluster-param-group

### ISSUE THREAD

**Issue by KarlCF** [cloud-custodian/cloud-custodian#9754]
### Describe the feature

I'm looking to improve results on the db-parameter filters for the aws.rds-cluster-param-group resource (possibly also the aws.rds-param-group resource) to also provide further key/value information on matches. 

## Example

```yaml
  - name: aws-rds-cluster-param-group-testing
    resource: aws.rds-cluster-param-group
    filters:
      - or:
        - type: db-parameter
          key: "character_set_client"
          value:
            - utf8mb4
            - utf8
          op: in
        - type: db-parameter
          key: "character_set_server"
          value:
            - utf8mb4
            - utf8
          op: in
```

Results:
```json
[
  {
    "DBClusterParameterGroupName": "example",
    "DBParameterGroupFamily": "aurora5.6",
    "Description": "Test policy parameter group",
    "DBClusterParameterGroupArn": "arn:aws:rds:us-east-2:123456789012:cluster-pg:example",
    "Tags": [],
    "c7n:MatchedDBParameter": [
      "character_set_client",
      "character_set_server"
    ]
  }
]
```

Intended results:
```json
[
  {
    "DBClusterParameterGroupName": "example",
    "DBParameterGroupFamily": "aurora5.6",
    "Description": "Test policy parameter group",
    "DBClusterParameterGroupArn": "arn:aws:rds:us-east-2:123456789012:cluster-pg:example",
    "Tags": [],
    "c7n:MatchedDBParameter": [
      "character_set_client": "utf8",
      "character_set_server": "utf8"
    ]
  }
]
```

### Extra information or context

Adding an extra c7n annotation would also be an alternative to enriching the existing one.
