### ISSUE TITLE
Support removing unused iam permissions with data taken from access analyzer

### ISSUE THREAD

**Issue by nitrocode** [cloud-custodian/cloud-custodian#9780]
### Describe the feature

I am always frustrated when I have to least privilege inline IAM policies on roles and managed customer IAM policies by hand.

The access analyzer data is helpful to least privilege roles. At the moment, I use that data manually to remove unused perms.

It would be nice if cloud custodian could do this automatically.

ref: https://cloud-custodian.slack.com/archives/CAL4P6YE6/p1728674052913299

```yaml
settings:
  unused: '30 days' &unused
policies:
- name: iam-policy-remove-unused-permissions
  resource: iam-policy
  filters:
    # only used roles
    - type: used

    # only find unused permissions in the last 30 days
    - type: analyzer
      unused: *unused

    # maybe have an exclusion list of policies
    # ...
  actions:
    # remove unused permissions if they have been unused for X amount of time
    - type: remove-unused-permissions
      unused: *unused
```
