### ISSUE TITLE
aws - service quota error in multiplier logic

### ISSUE THREAD

**Issue by pearceav** [cloud-custodian/cloud-custodian#9790]
### Describe the bug

```yaml
- name: service-quota-usage-increase-s3-buckets
      description: |
          If the usage is over 80% request increase
      resource: aws.service-quota
      filters:
        - UsageMetric: present
        - type: value
          key: QuotaCode
          value: L-DC2B2D3D # number of General purpose S3 buckets
        - type: usage-metric
          limit: 80
      actions:
      - type: request-increase
        multiplier: 1.2
```

When running the above within a lambda function, I got a TypeError:

```python
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 365, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/quotas.py", line 327, in process
    count = math.ceil(multiplier * r['Value'])
TypeError: can't multiply sequence by non-int of type 'float'
```

### What did you expect to happen?

I expected no error.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.38
Python:      3.8.10 (default, Sep 11 2024, 16:02:53)
             [GCC 9.4.0]
Platform:    posix.uname_result(sysname='Linux', nodename='VSR911GTR2', release='5.15.133.1-microsoft-standard-WSL2', version='#1 SMP Thu Oct 5 21:02:42 UTC 2023', machine='x86_64')
Using venv:  True
Docker: False
Installed:

argcomplete==3.4.0
attrs==23.2.0
boto3==1.34.128
botocore==1.34.128
docutils==0.18.1
importlib-metadata==6.11.0
importlib-resources==6.4.0
jmespath==1.0.1
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
pkgutil-resolve-name==1.3.10
python-dateutil==2.9.0.post0
pyyaml==6.0.1
referencing==0.31.1
rpds-py==0.18.1
s3transfer==0.10.1
six==1.16.0
tabulate==0.9.0
urllib3==1.26.19
zipp==3.19.2
```

### Policy

```shell
- name: service-quota-usage-increase-s3-buckets
      description: |
          If the usage is over 80% request increase
      resource: aws.service-quota
      filters:
        - UsageMetric: present
        - type: value
          key: QuotaCode
          value: L-DC2B2D3D # number of General purpose S3 buckets
        - type: usage-metric
          limit: 80
      actions:
      - type: request-increase
        multiplier: 1.2
```

### Relevant log/traceback output

```shell
Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 365, in run
    results = a.process(resources)
  File "/var/task/c7n/resources/quotas.py", line 327, in process
    count = math.ceil(multiplier * r['Value'])
TypeError: can't multiply sequence by non-int of type 'float'
```

### Extra information or context

changing line 327 to this resolves the error.

```python
count = math.ceil(float(multiplier) * r['Value'])
```
