### ISSUE TITLE
aws - wafv2 - get all waf rules

### ISSUE THREAD

**Issue by Singha22** [cloud-custodian/cloud-custodian#9870]
### Describe the feature

I want to be be able to read all the rules of a waf. Right now, it just shows the rules and the rule groups attached, but I want to see all the rules associated to the rule groups in one consolidated way.

Example yaml filter
```yaml
- type: rules
- key: c7n:WebACLAllRules[].Type
- value: RuleGroup
- op: eq

```
### Extra information or context

I am working on this enhancement.
