### ISSUE TITLE
Azure.storage - Add an action to enable/disable blob anonymous access.

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#9914]
### Describe the feature

A common Azure compliance check verifies that anonymous blob access is disabled on storage accounts. Please add an action which allows enabling/disabling this setting similar to this API call:

az storage container set-permission
  --name cc-project5-container
  --account-name abcdabcdabcd123412341234
  --public-access off

### Extra information or context

Azure docs - https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-prevent?tabs=portal#remediate-anonymous-access-for-the-storage-account

CIS control ID - 4.17 Ensure that 'Allow Blob Anonymous Access' is set to 'Disabled'

**Comment by jtroberts83** [comment]
Digging into this — there are actually two distinct settings here, and it's worth being precise:

- **Container level** (`properties.publicAccess` = None/Blob/Container): already covered by the `set-public-access` action on `azure.storage-container`. The `az storage container set-permission` example in my original post maps to this, so that part is already solved.
- **Account level** (`allowBlobPublicAccess`): the *master switch* the CIS control "Allow Blob Anonymous Access = Disabled" actually targets. When set to `false` it denies anonymous access across all containers regardless of their individual `publicAccess` value (per the [MS docs, storage-account remediation section](https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-prevent?tabs=portal#remediate-anonymous-access-for-the-storage-account)). This one was **not** implemented on `azure.storage`.

My original example muddied the two — apologies. The account-level switch is the missing piece, so I've opened #11126 adding a `set-blob-public-access` action to `azure.storage`:

```yaml
policies:
  - name: disable-blob-anonymous-access
    resource: azure.storage
    filters:
      - type: value
        key: properties.allowBlobPublicAccess
        value: true
    actions:
      - type: set-blob-public-access
        value: False
```
