### ISSUE TITLE
Enable Azure Subscription Budget extraction

### ISSUE THREAD

**Issue by ShruthiMulgund** [cloud-custodian/cloud-custodian#9971]
### Describe the feature

Currently, we lack the ability to extract budget information at the subscription level in Azure.

It would be great if this could be provisioned at the earliest.

**Comment by Samyakshrma** [comment]
Can i work on this feature?

**Comment by ajkerrigan** [comment]
Sure @Samyakshrma, if you're up for working on it that'd be great.

**Comment by calebsyring** [comment]
@ajkerrigan it looks like the API in question is https://learn.microsoft.com/en-us/rest/api/cost-management/budgets/get?view=rest-cost-management-2025-03-01&tabs=HTTP

Do we want this to be a filter on the subscription resource or its own resource? Could you provide an example policy?

**Comment by ajkerrigan** [comment]
> [@ajkerrigan](https://github.com/ajkerrigan) it looks like the API in question is https://learn.microsoft.com/en-us/rest/api/cost-management/budgets/get?view=rest-cost-management-2025-03-01&tabs=HTTP
> 
> Do we want this to be a filter on the subscription resource or its own resource?

It can be its own resource - an Azure-flavored take on [`aws.budget`](https://cloudcustodian.io/docs/aws/resources/budget.html). Probably using the [List](https://learn.microsoft.com/en-us/rest/api/cost-management/budgets/list) API rather than the `Get`.

> Could you provide an example policy?

The most bare bones "show me the budgets" would be something like:

```yaml
policies:
  - name: azure-budget-list
    resource: azure.budget
```

Since each resource includes a [bunch of fields](https://learn.microsoft.com/en-us/rest/api/cost-management/budgets/list?view=rest-cost-management-2025-03-01&tabs=HTTP#budget) that would also give us value filters for things like category & amount:

```yaml
policies:
  - name: azure-budget-list
    resource: azure.budget
    filters:
      - properties.category: Cost
      - type: value
        key: properties.amount
        op: greater-than
        value: 1000
```

It would be a nice-to-have to annotate resources with a usage percentage (`properties.currentSpend.amount` / `properties.amount` * `100`) so we could filter on budgets with high usage... but that's scope creep for the core request.
