### ISSUE TITLE
Add additional match criteria for has-statement filter

### ISSUE THREAD

**Issue by jerryhxu** [cloud-custodian/cloud-custodian#9980]
### Describe the feature

I would like to enhance the functionality of `has-statement` filter to add `whitelist_orgids`. In some use cases, we need to match a statement where PrincipalOrgID is in a list of IDs. 

The potential change is to add 
```
       - name: vpc-endpoint-policy
          resource: aws.vpc-endpoint
          filters:
             - type: has-statement
                statements:
                  - Action: "*"
                     Effect: "Allow"
                whitelist_orgids:
                   - o-abcdefghij
```

### Extra information or context

I plan to work on this issue
