### ISSUE TITLE
Support subnet and security-group filters in list-item

### ISSUE THREAD

**Issue by mattheidelbaugh** [cloud-custodian/cloud-custodian#9982]
### Describe the feature

It would be useful to be able to use subnet and security-group filters within the list-item filter.  Currently there is no way to write a policy which does something like "identify resources with an attached security group whose name matches a regex and which has a specific tag.  A filter such as
```
filters:
- type: security-group
   key: tag:Foo
   value: Bar
- type: security-group
   key: GroupName
   op: regex
   value: ^MySG.*
```
will return a resource which has one security group with the tag `Foo: Bar` and another security group named `MySG123` when what I really want is to be shown only resources that have a single security group that matches both filters.  For example something like this:
```
filters:
- type: list-item
   attrs:
    - type: security-group
       key: tag:Foo
       value: Bar
    - type: security-group
       key: GroupName
       op: regex
       value: ^MySG.*
```
