### ISSUE TITLE
Not + Or not working when filtering on tag?

### ISSUE THREAD

**Issue by major0** [cloud-custodian/cloud-custodian#9998]
### Describe the bug

An `or` filter involving a `tag` is not working as expected. Filter behaves as if the tag line doesn't exist at all.

I have attempted to add a `custodian:ignore` tag to all of my policies such that, if set, then custodian will not mark resources for deletion, and if marked it _should_ unmark them.

Policy
```yaml
policies:
  - name: eip-mark-unused-deletion
    resource: elastic-ip
    description: |
        Mark any unused EIP's for deletion in 14 days.
    filters:
    - "tag:custodian:ignore": empty
    - "tag:custodian:status:eip-unused": absent
    - InstanceId: absent
    - AssociationId: absent
    actions:
    - type: mark-for-op
      tag: "custodian:status:eip-unused"
      tz: utc
      op: release
      days: 14

  - name: eip-unmark-unused-deletion
    resource: elastic-ip
    description: |
        Remove the custodian:status:eip-unused tag from any eip which has instances attached
    filters:
    - "tag:custodian:status:eip-unused": not-null
    - not:
      - or:
        - "tag:custodian:ignore": empty
        - InstanceId: absent
        - AssociationId: absent
    actions:
    - type: remove-tag
      tags: ['custodian:status:eip-unused']
```

I have attempted to refactor the code to remove the `:`'s from the tags, but that does not seem to change its behavior in anyway.

What is interesting is that the `eip-mark-unused-deletion` properly ignores any resources with `custodian:ignore` set to `true` and the like, but `eip-unmark-unused-deletion` does not remove the `custodian:status:eip-unused` tag if I subsequently set `custodian:ignore` to true.

### What did you expect to happen?

I expect Cloud Custodian to properly filter/honor on the `custodian:ignore` tag and subsequently remove the `custodian:status:eip-unused` tag.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.43
Python:      3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0]
Platform:    posix.uname_result(sysname='Linux', nodename='MFERRELL-LAP1', release='5.15.167.4-microsoft-standard-WSL2', version='#1 SMP Tue Nov 5 00:21:55 UTC 2024', machine='x86_64')
Using venv:  False
Docker: False
Installed:

argcomplete==3.5.3
attrs==25.1.0
boto3==1.36.11
botocore==1.36.11
cffi==1.17.1
cryptography==43.0.3
docutils==0.18.1
importlib-metadata==8.4.0
jmespath==1.0.1
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
portalocker==2.10.1
pycparser==2.22
python-dateutil==2.9.0.post0
pyyaml==6.0.2
referencing==0.35.1
rpds-py==0.20.1
s3transfer==0.11.2
six==1.17.0
tabulate==0.9.0
typing-extensions==4.10.0
urllib3==1.26.20
zipp==3.20.2
```

### Policy

```shell
policies:
  - name: eip-mark-unused-deletion
    resource: elastic-ip
    description: |
        Mark any unused EIP's for deletion in 14 days.
    filters:
    - "tag:custodian:ignore": empty
    - "tag:custodian:status:eip-unused": absent
    - InstanceId: absent
    - AssociationId: absent
    actions:
    - type: mark-for-op
      tag: "custodian:status:eip-unused"
      tz: utc
      op: release
      days: 14

  - name: eip-unmark-unused-deletion
    resource: elastic-ip
    description: |
        Remove the custodian:status:eip-unused tag from any eip which has instances attached
    filters:
    - "tag:custodian:status:eip-unused": not-null
    - not:
      - or:
        - "tag:custodian:ignore": empty
        - InstanceId: absent
        - AssociationId: absent
    actions:
    - type: remove-tag
      tags: ['custodian:status:eip-unused']
```

### Relevant log/traceback output

```shell

```
